### ISSUE TITLE
Isotope\Model\ProductCollection::getItemForProduct()

### ISSUE THREAD

**Issue by katgirl** [isotope/core#1000]
Die Funktion getItemForProduct findet nicht Produkte die eigene Attribute verwendet, die durch den Kunden eingeben werden.

https://github.com/isotope/core/blob/master/system/modules/isotope/library/Isotope/Model/ProductCollection.php#L733

z.B. Wie in https://github.com/isotope/core/blob/master/system/modules/isotope_rules/library/Isotope/Rules.php#L97

Produkt mit einem Attribute welches durch den Kunden selbst bestimmt werden kann. z.B. Länge

Ein einfaches Beispiel an dem Hook:

``` php
public function attributePrice($fltPrice, $objSource, $strField, $intTaxClass)
{  
    if ($objSource instanceof IsotopePrice && ($strField == 'price' || $strField == 'low_price')) 
    {
$objItem = Isotope::getCart()->getItemForProduct($objSource->getRelated('pid'));
var_dump($objItem);
    }
  return $fltPrice;
}
```

**Comment by MoniqueHahnefeld** [comment]
+1
