### ISSUE TITLE
Ghost Versandart in checkout

### ISSUE THREAD

**Issue by tpk109** [isotope/core#1006]
![post](https://f.cloud.github.com/assets/6112444/2287412/ddb8e850-9fec-11e3-8cff-26db0a84e788.jpg)
![kasse](https://f.cloud.github.com/assets/6112444/2287424/fc71ec4c-9fec-11e3-82a5-4cdaf6beaece.jpg)

**Comment by mohanaraj1812** [comment]
Where to found this configuration settings? In my shop i did't find this setting.
