### ISSUE TITLE
Sofortüberweisung Input-Hash falsch

### ISSUE THREAD

**Issue by H-W6** [isotope/core#1034]
Egal, welchen Hash-Algorithmus ich auswähle, erscheint folgende Fehlermeldung:
"Der übergebene Input-Hash stimmt nicht mit dem von uns berechneten Input-Hash überein. Wenn Sie der Shopbetreiber sind, überprüfen Sie bitte, ob das in Ihrem Shopsystem gespeicherte Projektpasswort mit dem Projektpasswort in den Projekteinstellungen Ihres Anbietermenüs übereinstimmt."
Ich nutze Contao 3.2.8 und isotope 2.0.4 stable
Projekt-ID, Kundennummer und das Passwort sind in der Shopkonfiguration korrekt eingegeben und leider kann auch der Kundenservice bei SOFORT nicht weiterhelfen.

**Comment by michaelsalzburg** [comment]
Ich hatte denselben Fehler bei mir eben auch und konnte ermitteln, an was das gelegen hatte. Jedes Mal, wenn in dem PostSale-Request spezielle Sonderzeichen vorkommen (in meinem Fall hatte der Name der Bank eine Klammer im Namen), werden diese durch `\Input::post('xxx')` encodiert, weshalb aus einer Klammer dann z.B. `&#41;` wird. Somit stimmt klarerweise der Hash nicht mehr.

Ich hätte das Problem nun gelöst, indem ich in der system\modules\isotope\library\Isotope\Model\Payment\Sofortueberweisung.php den Zusammenbau des $arrHash folgendermaßen abändere:
`$arrHash = array(
            'transaction'               => \Input::post('transaction'),
            'user_id'                   => \Input::post('user_id'),
            'project_id'                => \Input::post('project_id'),
            'sender_holder'             => \Input::post('sender_holder', true),
            'sender_account_number'     => \Input::post('sender_account_number'),
            'sender_bank_code'          => \Input::post('sender_bank_code'),
            'sender_bank_name'          => \Input::post('sender_bank_name', true),
            'sender_bank_bic'           => \Input::post('sender_bank_bic'),
            'sender_iban'               => \Input::post('sender_iban'),
            'sender_country_id'         => \Input::post('sender_country_id'),
            'recipient_holder'          => \Input::post('recipient_holder', true),
            'recipient_account_number'  => \Input::post('recipient_account_number'),
            'recipient_bank_code'       => \Input::post('recipient_bank_code'),
            'recipient_bank_name'       => \Input::post('recipient_bank_name', true),
            'recipient_bank_bic'        => \Input::post('recipient_bank_bic'),
            'recipient_iban'            => \Input::post('recipient_iban'),
            'recipient_country_id'      => \Input::post('recipient_country_id'),
            'international_transaction' => \Input::post('international_transaction'),
            'amount'                    => \Input::post('amount'),
            'currency_id'               => \Input::post('currency_id'),
            'reason_1'                  => \Input::post('reason_1', true),
            'reason_2'                  => \Input::post('reason_2', true),
            'security_criteria'         => \Input::post('security_criteria'),
            'user_variable_0'           => \Input::post('user_variable_0', true),
            'user_variable_1'           => \Input::post('user_variable_1', true),
            'user_variable_2'           => \Input::post('user_variable_2', true),
            'user_variable_3'           => \Input::post('user_variable_3', true),
            'user_variable_4'           => \Input::post('user_variable_4', true),
            'user_variable_5'           => \Input::post('user_variable_5', true),
            'created'                   => \Input::post('created'),
            'notification_password'     => $this->sofortueberweisung_project_password,
        );`

Sorry, der Code wird etwas unleserlich dargestellt. Was ich gemacht habe: bei allen Werten, die möglicherweise Sonderzeichen enthalten könnten, habe ich `\Input::post('xxx')` durch `\Input::post('xxx', true)` ersetzt.
Dadurch werden die Klammern von `\Input::post()` wieder richtig als Klammern und nicht als HTML-Ersetzungen widergegeben und die Überprüfung des Hashes funktioniert wieder.

**Comment by aschempp** [comment]
wäre es nicht am einfachsten einfach immer `true` zu übergeben? Bei allen Parametern ohne Sonderzeichen sollte das doch keinen Unterschied machen?

**Comment by michaelsalzburg** [comment]
@aschempp Gebe ich dir Recht, das sollte keinen Unterschied machen!

**Comment by aschempp** [comment]
Fixed in c5a2441bbc3a9a921210f19cfdac48d0b5ced63c
