### ISSUE TITLE
Unpublished products in product variant list

### ISSUE THREAD

**Issue by seaneble** [isotope/core#1120]
The product variant list of Isotope 2.1.1 shows unpublished products if the variants themselves are published.
- Product X (hidden)
  - Variant X.Y (published)
  - Variant X.Z (hidden)

Variant X.Y is shown in the product variant list (bug) but leads to an error page (404) in the detail view (correct).

**Comment by tsarma** [comment]
I don't see this necessarily as a bug. In some cases this behaviour might be needed.
