### ISSUE TITLE
Enhancement: Status to mark a order as shipped

### ISSUE THREAD

**Issue by Zeromax** [isotope/core#1145]
It is possible to say in a status "Order is paid". If this Status happened, the order gets a pay date and some other stuff.

Is it possible to have this for a shipped status as well? So I can select in a status, that when this one is reached, the Order is shipped and the shipped date is set automatically.

That would be cool ;)

**Comment by CodeAlDente** [comment]
In addition to this, it would be nice to also add a tracking number and to let the customer know, how he can track his package and where he can enter the tracking number.

**Comment by aschempp** [comment]
I think this has been implemented meanwhile.
