### ISSUE TITLE
Universal Analytics tauglich machen

### ISSUE THREAD

**Issue by BigBerny** [isotope/core#1153]
Hallo
Kann es sein, dass Isotope beim Google Tracking noch die alte Schnittstelle nutzt? Seit einigen Wochen setzt ja Google auf Universal Analytics (war lange Beta) und da haben sich einige Dinge geändert.

Hier ist das ganze ziemlich übersichtlich aufgezeigt:
http://misterphilip.com/universal-analytics/migration/ecommerce

**Comment by BigBerny** [comment]
Wäre es möglich, euch im Gegenzug finanziell zu unterstützen? Leider habe ich nicht genügend Zeit, mich richtig einzuarbeiten. Scheint ja leider hardcoded zu sein.

**Comment by aschempp** [comment]
Das ginge natürlich auch, bitte aber per E-Mail an info@isotopeecommerce.org

**Comment by aschempp** [comment]
Closing since we don't plan to support analytics in PHP anymore in upcoming versions.
