### ISSUE TITLE
Define defaults for shipping and billing and don't ask for them in checkout

### ISSUE THREAD

**Issue by comede** [isotope/core#1217]
I can deactivate payment and billing in the checkout-config. But then no shipping and billing method is choosen. That's causing trouble with notifications triggered by a sucessfull payment.

It would be nice if I could define defaults in backend or config and wouldn't be forced to ask the user for these steps where he has no choice.

Iso 2.1.3
Contao 3.2.13

**Comment by matzke** [comment]
+1

**Comment by aschempp** [comment]
Added in upcoming Isotope 2.4

**Comment by matzke** [comment]
nice. thankx.
