### ISSUE TITLE
Product List and filter too slow

### ISSUE THREAD

**Issue by Chibko** [isotope/core#1262]
Hello,
I have a store with 5000 simple products (no variants) with numerous attributes.
It takes very long time (40s and more…) to show products with the Product List Module.

I take a look at the findAvailableBy function in Product.php model.
- This function takes 40s to find the products.
- I remove the "$objProduct->isAvailableInFrontend()" test, and now the function takes 2s to get products ! 

I have the same problem with filters. It takes too long to show products, and often fail.
- I have make a custom version of the buildSqlFilters function in the RequestCache Model :
$strWhere = "((" . implode(' AND ', $arrWhere) . "))";

Now search and filters work very quicky.

Hope it helps…

**Comment by bennyborn** [comment]
I experienced a similar problem when searching for products by keyword.
The query built for the search contains a subselect which is slowing down the whole query.

With the subselect, which seems to do nothing for me except adding unnecessary iterations, the search took about 56s, without only 117ms.

Shop contains around 200 products with 100 variants each.

Quickfix for me was to remove the entire subselect from the $strWhere in Isotope\ModuleProductList::findProducts

**Comment by aschempp** [comment]
Can you write down the subselect you removed?

**Comment by bennyborn** [comment]
Sure, "original" version of the query produced looks like this

`(((tl_iso_product.sku LIKE ? OR IFNULL(translation.name, tl_iso_product.name) LIKE ? OR IFNULL(translation.description, tl_iso_product.description) LIKE ? OR tl_iso_product.suchbegriffe LIKE ?)) OR tl_iso_product.id IN (SELECT tl_iso_product.pid FROM tl_iso_product AS tl_iso_product WHERE tl_iso_product.language='' AND (tl_iso_product.sku LIKE ? OR IFNULL(translation.name, tl_iso_product.name) LIKE ? OR IFNULL(translation.description, tl_iso_product.description) LIKE ? OR tl_iso_product.suchbegriffe LIKE ?) AND tl_iso_product.published='1' AND (tl_iso_product.start='' OR tl_iso_product.start<1426235049) AND (tl_iso_product.stop='' OR tl_iso_product.stop>1426235049)))`

And I replaced it with

`(((tl_iso_product.sku LIKE ? OR IFNULL(translation.name, tl_iso_product.name) LIKE ? OR IFNULL(translation.description, tl_iso_product.description) LIKE ? OR tl_iso_product.suchbegriffe LIKE ?)) )`

Of course tl_iso_product_suchbegriffe is a custom field of mine and I left out some other fields on purpose but the main thing slowing everything down was that subselect.

**Comment by aschempp** [comment]
Well that would mean if your description was in a variant it would not be found by the product search…?

**Comment by bennyborn** [comment]
Maybe, didn't try - if I remember correctly I did not have a single shop with variants that got descriptions any different to the parent yet. But anyway I guess you must agree that the performance of this query can't be left untouched, as I said it's (in my case) 56 seconds VS. 117ms (!). We need another solution although I don't have any good one yet. Maybe we could check if any of the variants got descriptions at all before building the query?

**Comment by aschempp** [comment]
I'm closing this as the ticket does not provide a solution. We're well aware that performance is not great, but it will improve with every version and every version of Contao (there have been major improvements in Contao 3.5 for example).

**Comment by adamffyl** [comment]
Not sure if this is still an issue for you, but you could also try our make-shift extension isotope_direct that uses direct SQL for simpler sites.
