### ISSUE TITLE
[2.1.9] Vorhandene Adresse wird bei Auswahl in Kasse nicht validiert

### ISSUE THREAD

**Issue by Mynyx** [isotope/core#1323]
In der Kasse wird eine im Adressbuch vorhandene Adresse, die als Rechnungs- oder Versandadresse ausgewählt wird, nicht validiert.
Eine Lösungsidee wäre eine nicht valide Adresse in das Formular bei "Neue Adresse anlegen" zu übertragen und dort die Korrektur zu ermöglichen.

**Comment by aschempp** [comment]
Closed due to inactivity.
