### ISSUE TITLE
Feldlänge von Attributen

### ISSUE THREAD

**Issue by Skipman** [isotope/core#1329]
Gibt man eine Feldlänge für ein Attribut an, wird dieses nicht in die DB übernommen. Beispiel:
Im Contao Backend eingegebene Zeichenlänge 50 Zeichen ergibt in der DB ein Textfeld mit 255 Zeichen.

**Comment by aschempp** [comment]
Fixed in f6fc513458cf0dc1bd8dff176a2bb384a5fa5ac2
