### ISSUE TITLE
Kein RTE beim Beschreiben einer Variante

### ISSUE THREAD

**Issue by cepharum** [isotope/core#1335]
Wenn man unter "Produkte" Varianten zu einem Produkt bearbeitet, erscheint initial die Bearbeitungsansicht für die gewählte Variante mit Häkchen bei "Vorgabe-Wert nutzen" zur Beschreibung der Variante:

![variant-editor-initial](https://cloud.githubusercontent.com/assets/4108982/5329239/dc48af60-7da3-11e4-9426-fb5e2b9fdf86.png)

Klickt man auf das Häkchen erscheint eine Textbox ohne RTE, in die man Text eingeben kann:

![variant-editor-text-entered](https://cloud.githubusercontent.com/assets/4108982/5329240/efef0c4e-7da3-11e4-9cca-8dc85f2cf1e4.png)

Wenn man nun speichert (hier im Test ohne zu schließen), dann wird das Fehlen einer Beschreibung bemängelt und das Feld hat endlich einen RTE:

![variant-editor-saved](https://cloud.githubusercontent.com/assets/4108982/5329242/0e3b79a8-7da4-11e4-9402-2f79c9100f09.png)

Contao-Setup bzgl. Extensions ist wie folgt:

![variant-editor-setup](https://cloud.githubusercontent.com/assets/4108982/5329246/39a14ffa-7da4-11e4-8b79-30b1d7a0e26a.png)

**Comment by aschempp** [comment]
I only fixed this for Isotope 2.2 because in version 2.1 we would also support Contao 3.2 with tinyMCE 3.
