### ISSUE TITLE
Individuelles Galerie-Template erzeugt leere Divs

### ISSUE THREAD

**Issue by k-webdesign** [isotope/core#1337]
Hi,

ich habe der Galerie für den Produktleser ein Custom gallery template zugewiesen (Kopie von iso_gallery_standard, in dem ich lediglich der .image_container eine bestimmte Klasse hinzugefügt habe).

Im Produkttyp weise ich dann ja die passenden Galerien zu. Im Frontend bekomme ich den Code ohne Content, also leere divs. 

So sollte es aussehen (vollständiger Code siehe Firebug, es geht um class="col-xs-12 visual" und die Zeile darunter):
![bildschirmfoto 2014-12-07 um 21 46 22](https://cloud.githubusercontent.com/assets/4130440/5332544/8ed917f8-7e5a-11e4-9142-0e9ebe53a321.png)

So sieht's aus:
![bildschirmfoto 2014-12-07 um 21 47 18](https://cloud.githubusercontent.com/assets/4130440/5332554/efa141aa-7e5a-11e4-94d8-b90f39552097.png)

VG Kim

**Comment by aschempp** [comment]
Die 2.2.1 ist seit gestern da, lass mich wissen ob es damit geht :)

**Comment by aschempp** [comment]
Any news?

**Comment by k-webdesign** [comment]
Jepp, jetzt ist alles wieder paletti. Danke!
