### ISSUE TITLE
Einschränkender Filter - Isotope 2.2.0

### ISSUE THREAD

**Issue by Hairlando** [isotope/core#1340]
Hallo, 

Der Filter wird im Frontend nicht ausgegeben...Sehe zwar die mod_iso_cumulativefilter block klasse, aber die ist leer...verstehe nicht wieso. Es muss doch funktionieren.

Gibt es da einen bekannten bug? 

Vielen Dank

**Comment by aschempp** [comment]
The solution will be to disable filtering on attributes that have options set in the product.

**Comment by aschempp** [comment]
Möglicherweise ist #1319 dein Problem, ich kann das nicht nachstellen.

**Comment by aschempp** [comment]
Hast du mal ein Update auf 2.2.1 gemacht und geprüft ob das Problem noch besteht?

**Comment by aschempp** [comment]
Kannst du hier noch Feedback geben?

**Comment by aschempp** [comment]
Closing this without feedback, let's reopen when there is more info.
