### ISSUE TITLE
getTaxFreeSubtotal in Templates

### ISSUE THREAD

**Issue by EDsolution** [isotope/core#1345]
Could you make one variable which could be used in templates (lister, reader, collection, ...) with which you could echo price - (minus) VAT / TAX.

For example I've wrote this code in ProductCollection.php
$objTemplate->subtotal_tax_free   = Isotope::formatPriceWithCurrency($this->getTaxFreeSubtotal());
with which I can show price without VAT / TAX.

Everything is there we only need to make it "printable" :)

tnx.

**Comment by EDsolution** [comment]
It seems that this isn't working in 2.2.2 anymore - mine or yours :)

**Comment by EDsolution** [comment]
Hm...getTaxFreeSubtotal isn't calculated right way.

I have tax set to 22%.

In cart - total = 759€
echo \Isotope\Isotope::formatPriceWithCurrency($this->collection->getTaxFreeSubtotal() = 622,15€
But it should be 622,13€

If I echo $surcharge['total_price'] the total tax value is right, 136,87€.

**Comment by EDsolution** [comment]
Hm..it works very strange. When you have one item it calculate ok, if you than change quantity to 5 it doesn't, if you have more than 5 product, it doesn't - random errors :)

Here is the image of my basket and calculation (tax is 22%).
http://dev.edsolution.si/tax-free-error.jpg

**Comment by EDsolution** [comment]
OK I figure out that calculation works wrong when the product has rule, every time.

**Comment by aschempp** [comment]
I have added `tax_free_total` and `tax_free_subtotal` as template variables. For any other topic, please create a new issue.
