### ISSUE TITLE
"Related products" - Multilanguage

### ISSUE THREAD

**Issue by EDsolution** [isotope/core#1346]
Hi,
my site structure is like that:

EN
- Category 1
- Category 2
- Reader

SL
- Kategorija 1
- Kategorija 2
- Podrobnosti

Now i'm using Reader page options in site structure to point where product reader is. On reader page I have module product_reader and product list which is "related" ("Current Product's Categories").

The issues (our location is product reader page).
If I'm on EN version the related product url points to en/category_1/product.html - OK

If I'm on SL version the related product url points to sl/category_1/product.html - but it should points to sl/kategorija_1/product.html - because of that we get 404.

**Comment by EDsolution** [comment]
This isn't fixed jet, right?

**Comment by aschempp** [comment]
I assume you are using Isotope 2.1. We have fixed that problem in 2.2 already, but unfortunately it required quite some code changes and can't be backported to 2.1

**Comment by EDsolution** [comment]
Nop, I'm using Isotope 2.2.0

**Comment by EDsolution** [comment]
Can you point me where you have fixed this bug - I need to solve this.

Tnx.

**Comment by aschempp** [comment]
The issue should actually be reopened I guess because you said it's in 2.2

**Comment by aschempp** [comment]
Will be fixed in 2.2.2

**Comment by EDsolution** [comment]
Tnx for info.

**Comment by EDsolution** [comment]
Hm..as noticed this is not only the bug in link. 
It also doesn't generate the right products within this category. If you select "current's product category" in module setting it displays product from other category - or is this cache problem?

**Comment by aschempp** [comment]
If you select "current's product category" it will show products from all categories assigned to the current product.

**Comment by EDsolution** [comment]
It does and it doesn't. 

If you purge data and you go to product 1 it will show the related product in the same category. But when you go to product in Y category it will show again the same related product as before, that's because it uses product cache and it's always the same for all product - no matter in which category you are.

**Comment by aschempp** [comment]
You're right… please create a new ticket for that issue.

**Comment by EDsolution** [comment]
done

https://github.com/isotope/core/issues/1383
