### ISSUE TITLE
[2.1.9] Versandkosten werden aus Bestellung nur mit vom Versand ausgeschlossenen Artikel nicht entfernt

### ISSUE THREAD

**Issue by Mynyx** [isotope/core#1347]
Wenn in den Warenkorb ein normaler Artikel und ein Artikel, der vom Versand ausgeschlossen ist, gelegt werden und in der Kasse eine Versandart ausgewählt wird, werden korrekterweise Versandkosten berechnet.
Wird nun allerdings der normale Artikel entfernt und die Kasse nur mit dem vom Versand ausgeschlossenen Artikel erneut aufgerufen, werden die Versandkosten nicht entfernt. In der abgesendeten Bestellungen werden also fehlerhaft Versandkosten berechnet.

**Comment by aschempp** [comment]
Dies ist leider ein bekanntes Problem in der 2.1, welches wir nicht so einfach lösen konnten. In der 2.2 tritt das nicht mehr auf, du müsstest also aktualisieren um das zu beheben.
