### ISSUE TITLE
Hersteller im im iso_reader ausgeben

### ISSUE THREAD

**Issue by Hairlando** [isotope/core#1348]
Eigentlich sollte es ganz einfach sein. Hab ein Attribut für Hersteller erstellt im Backend [Select-Menü]. 
Im Backend wird ein neues Produkt erstellt und als Hersteller zb. Loreal ausgewählt. 
Jetzt soll der Hersteller in der Produkt-Detailansicht angezeigt werden (iso_reader).

Hab´s mit dem Code ausprobiert aber da wird nur die Hersteller ID ausgegeben. Im Fall von Loreal die Nr. 3. 
Hier der Code der nicht funktioniert:

<?php echo $this->generateAttribute('hersteller'); ?>

Wie muss der Code lauten damit der Name Loreal ausgegeben wird?

Danke

**Comment by Toflar** [comment]
Hi,
Dies ist der Issue-Tracker von Isotope. Support für Fragen aller Art gibt's im [Contao Community Forum](https://community.contao.org).
