### ISSUE TITLE
Checkout Formular (AGB & Widerrufsbelehrung) Fehler bei Validierung

### ISSUE THREAD

**Issue by emkayy** [isotope/core#1349]
Formular:
2 Checkbox Inputs, jeweils required

Beim Absenden ohne Auswahl wird korrekt validiert und Fehlermeldungen ausgegeben.

Schickt man dann jedoch nochmal ab, ohne dass beide angekreuzt sind, kommen zwar Fehlermeldungen, aber beide Checkboxen sind mit "checked" vorausgewählt.

Diese muss der Benutzer laut Gesetzgeber aber selber setzen und dürfen nicht vorausgewählt sein.

**Comment by emkayy** [comment]
Frage: Warum hat das Formular ein novalidate Attribut. Das würde doch viel schon im voraus klären, ohne, dass die Seite neu geladen und serverseitig validiert werden muss?

**Comment by aschempp** [comment]
Ich habe diesen Fehler auch schon gesehen, kann ihn aber nicht mehr reproduzieren. Ich brauche etwas genauere Angaben:
 - welche Version von Isotope und Contao
 - wie heisst das Feld und die Optionen genau

**Comment by emkayy** [comment]
Contao 3.3.5
Isotope 2.1.7 	2
2 Felder:
1. Name: agb  Wert: 1
2. Name: widerruf  Wert: 1

**Comment by aschempp** [comment]
Dann müsstest du erst mal ein Update auf 2.1.11/2.1.12 machen und sehen ob das Problem noch besteht.

**Comment by martinmildner** [comment]
Contao 3.4.0, Isotope 2.2.2
Habe ein Formular mit Checkbox (Pflichtfeld) eingebunden. Obwohl es angeklickt wird, wird man nicht zum Bezahlvorgang weitergeleitet (Validiert wird richtig). Ohne Pflichtfeld klappt es.
Schätze einmal, dass es zu dem Problem gehört...

**Comment by aschempp** [comment]
@martinmildner das kann eigentlich nicht sein. Habt ihr das Problem gelöst und einen Fehler gefunden?

**Comment by martinmildner** [comment]
leider nein, ist noch nicht gelöst (leo hatte noch keine zeit). möchtest du es dir kurz ansehen? jederzeit...

**Comment by aschempp** [comment]
Naja, wenn ich mir das bei dir ansehen und beheben soll: https://circle.isotopeecommerce.org ;-)

Ansonsten kann Leo gerne einen Pull Request mit der Korrektur machen, wenn er dazu kommt.

**Comment by aschempp** [comment]
Ich schliesse das Ticket mangels weitere Informationen.

**Comment by martinmildner** [comment]
sorry für die späte anwort: in kombination mit der extended_checkbox erweiterung hat es nicht geklappt. mit dem standard formular klappt alles! lg martin
