### ISSUE TITLE
Inserttags in gecachten Seiten werfen Fehler

### ISSUE THREAD

**Issue by volkerrichert** [isotope/core#1350]
Wenn ich ein inserttag ala {{cache_isotope::cart_items_label}} benutze, dann landet das im cache-file, wenn der cache aktiv ist. Soweit so gut.

Wenn das aber ausgespielt wird, dann wird das Tag ausgewertet ohne das $objPage gesetzt ist. Das wird erst in der run-Methode bestimmt. Die Auslieferung der cache erfolgt aber schon im __construct.Damit liefert getCart() null zurück. Das hat dann folgende Meldung zur Folge:

Fatal error: Call to a member function countItems() on a non-object in /var/www/vrichert/bsqh/htdocs/composer/vendor/contao-legacy/isotope/TL_ROOT/system/modules/isotope/library/Isotope/Frontend.php on line 223
Call Stack

 |Time|Memory|Function|Location
------------|------------|------------|------------|------------
1|0.0012|245936|{main}( )|../index.php:0
2|0.1842|9016008|Contao\FrontendIndex->__construct( )|../index.php:21
3|0.1842|9016160|Contao\FrontendIndex->outputFromCache( )|../FrontendIndex.php:37
4|0.1851|9086328|Contao\Controller->replaceInsertTags( )|../FrontendIndex.php:383
5|0.1890|9572888|Isotope\Frontend->replaceIsotopeTags( )|../Controller.php:1718

CTO 3.4.0
Isotope 2.2.1.9007

Grüße,

Volker

**Comment by aschempp** [comment]
Du kannst einen Warenkorb-bezogenen InsertTag auf einer gecachten Seite nicht einsetzen. Das System weis ja nichts vom aktuellen Warenkorb weil die Seite gecacht ist.

**Comment by volkerrichert** [comment]
Genau da drum geht es doch. Wir ist klar, dass des InsertTAG die Seite nicht kennt. Die Frage ist eher, ob das nicht mehr als sinnvoll wäre. I.d.R. hat man ja heute auf allen Seiten eine Referenz zum Warenkorb. Das würde den kompletten Cache von Contao unnütz machen.

Insb. sollte es nicht in einer Exception enden.

Aber ich habe auch drüber nachgedacht. Ich denke es sollte im cache file auch die PageId hinterlegt werden. Dann könnten InsertTags sich die Seite ggf manuel holen

**Comment by aschempp** [comment]
Ein Warenkorb macht den ganzen Cache unnütz, das ist so. Genauso wie ein angemeldeter User in Contao. Das lässt sich nicht ändern.

**Comment by volkerrichert** [comment]
Bei einem angemeldeten User verstehe ich das auf Grund der Art des CTO-Caches sogar. Das wäre einiges an Aufwand, aber nicht unmöglich. Die Session ist ja trotzdem da, also spräche nix dagegen den Warenkorb nachträglich per InsertTag in die Seite zu rendern.

Oder übersehe ich was?

**Comment by volkerrichert** [comment]
ich habe testweise mal eine

```php
$objPage = \PageModel::findPublishedByIdOrAlias([pageId]);
```

ins CacheFile eingebaut. Dann geht es. Also würde es gehen. Man müsste Leo überzeugen die PageId mit ins Cachefile zu schrieben

**Comment by aschempp** [comment]
Wenn die Seite aus dem Cache ausgeliefert wird, besteht keine Datenbankverbindung. Entsprechend sind auch keine Informationen zum Warenkorb verfügbar, und dein Aufruf würde den Cache "sinnlos" machen.

**Comment by volkerrichert** [comment]
Dann bau das Model die wohl von alleine wieder auf. 

```php
$objPage = \PageModel::findPublishedByIdOrAlias([pageId]);
var_dump($objPage);die;
```

liefert mir im Cachefile eingebaut die passende Seite.

```php
object(Contao\Model\Collection)[87]
  protected 'strTable' => string 'tl_page' (length=7)
  protected 'intIndex' => int -1
  protected 'arrModels' => 
    array (size=1)
      0 => 
        object(Contao\PageModel)[86]
          protected 'blnDetailsLoaded' => boolean false
          protected 'arrData' => 
            array (size=61)
              'id' => string '24' (length=2)
              'pid' => string '10' (length=2)
              'sorting' => string '128' (length=3)
              'tstamp' => string '1415649269' (length=10)
...
```

**Comment by aschempp** [comment]
Ja das baut sie auf, aber damit "zerstörst" du den Sinn des Caches.

**Comment by volkerrichert** [comment]
Natürlich, wenn ein Cache nur dafür da wäre das zu verhindern. Letztlich geht es aber um schnelle Auslieferung der Seite. Und immerhin kann man alles andere aus dem Cache holen. Sonst würde man alles live rendern und das wäre langsamer.

**Comment by volkerrichert** [comment]
aber sei es drum. Ist kein "Bug" in dem Sinne von isotope, mal von dem unglücklichen Verhalten einer exception abgesehen. dann sollte es die cache_-Varianten besser nicht geben.

**Comment by volkerrichert** [comment]
Trotzdem danke fürs ansehen.
