### ISSUE TITLE
Lazy generate images

### ISSUE THREAD

**Issue by Toflar** [isotope/core#1351]
Even though the closure `getGallery()` is sort of lazy load (because if you don't call it, none gets generated) it's not optimized enough yet. E.g. when I only call `generateMainImage()` and don't need to call `generateGallery()` - which is very, very likely in the product list - it should only call `\Image::get()` on those calls. However, right now it's called already whenever a gallery object is created (see `Gallery\Standard::setFiles()` which calls `Gallery\Standard::addImage()`.

**Comment by aschempp** [comment]
Closing this in favor of #1360
