### ISSUE TITLE
error in composer.json of v2.1.10?

### ISSUE THREAD

**Issue by fritzmg** [isotope/core#1352]
The [composer.json of 2.1.10](https://github.com/isotope/core/blob/2.1.10/composer.json) says
```JSON
 "terminal42/namespace-class-loader":">=1.0.1,<2.0",
```
This leads to
```
Problem 1
- Installation request for isotope/isotope-core >=2.1.10.0,<2.2-dev -> satisfiable by isotope/isotope-core[2.1.10].
- isotope/isotope-core 2.1.10 requires terminal42/namespace-class-loader >=1.0.1,<2.0 -> no matching package found.
```
when installing via composer. It should be
```JSON
 "terminal42/contao-namespace-class-loader":">=1.0.1,<2.0",
```
shouldn't it?

https://packagist.org/packages/terminal42/contao-namespace-class-loader
https://community.contao.org/de/showthread.php?55142-isotope-%FCber-composer-updaten-von-2-1-9-auf-2-1-10

**Comment by bytehead** [comment]
confirmed, I have the same error.

**Comment by bytehead** [comment]
It's fixed in the current hotfix branch: https://github.com/isotope/core/blob/hotfix/2.1.11/composer.json#L22
