### ISSUE TITLE
Fatal error: getLowestTier() ...isotope\library\Isotope\Model\Product\Standard.php on line 320

### ISSUE THREAD

**Issue by davorgit** [isotope/core#1353]
$this->getPrice() gets null, so it cannot be called like this: $this->getPrice()->getLowestTier()
needs some kind of condition and error handling with appropriate message

this is my first time usage of isotope module so I don't have a clue what is missing in BE
Update:  i know it's price but some info or default setting for this would also solve the issue

**Comment by aschempp** [comment]
Does your product have a price?

**Comment by davorgit** [comment]
Yes, when I added price error was gone.
