### ISSUE TITLE
If cache disabled or not built yet, products are not loaded

### ISSUE THREAD

**Issue by davorgit** [isotope/core#1354]
If jquery is On and mootools are Off the products are not loaded because of js error.
Solution would be to add condition for $objPage->hasMooTools and $objPage->hasJQuery only for document ready part, since isotope.js is written in plain javascript.

**Comment by Toflar** [comment]
The case where "MooTools is off" does not exist. MooTools is a requirement for Isotope to work properly.

**Comment by davorgit** [comment]
well I'm using jquery and other third party js code, so in my case i have to disable mootools otherwise I have conflicts

**Comment by Toflar** [comment]
That does not change the requirements of Isotope. Either use jQuery in noConflict() mode and make your code MooTools compatible or don't use Isotope - those are the two options you have :)=

**Comment by davorgit** [comment]
Are you sure that all isotope scripts run in no-conflict mode, like Leo suggested? 

// MooTools
(function($) {
  // Your code goes here
})(document.id);

**Comment by aschempp** [comment]
There's also a third option: you can obviously build the Isotope features that requiere MT using jQuery. Thanks to the extensibility of Javascript that should be possible without touching Isotope core…=

**Comment by davorgit** [comment]
> There's also a third option: you can obviously build the Isotope features that requiere MT using jQuery. Thanks to the extensibility of Javascript that should be possible without touching Isotope core…

**Comment by davorgit** [comment]
Yea, but I see there is a lot of inline js places where I would have to extend lots of classes to do that ..so it would be much easier and nicer, to do that in core I think.
Anyway I sorted out with placing jQuery library and third party script at the bottom without noConflict mode. Thanks for help.
