### ISSUE TITLE
Isotope Gallery only includes the last JavaScript template on AJAX request

### ISSUE THREAD

**Issue by fritzmg** [isotope/core#1357]
There is a small error in [Isotope\Model\Gallery\Standard](https://github.com/isotope/core/blob/master/system/modules/isotope/library/Isotope/Model/Gallery/Standard.php), at line [#174](https://github.com/isotope/core/blob/master/system/modules/isotope/library/Isotope/Model/Gallery/Standard.php#L174), which causes only the last of the JavaScript templates to be actually included in the source (in the AJAX request). Instead of
```php
$strScripts = $objScript->parse();
```
it should say
```php
$strScripts.= $objScript->parse();
```

**Comment by aschempp** [comment]
why would you select multiple javascript templates?

**Comment by fritzmg** [comment]
In my case: I am using a JavaScript Template for the Lightbox/Mediabox and another for a jQuery selectBox for example (plugin for individually styled selectboxes) - which is used for the variant select box.
