### ISSUE TITLE
Warning: Missing argument 3 for NotificationCenter\tl_nc_language

### ISSUE THREAD

**Issue by swisschris** [isotope/core#1358]
Seit dem Update auf Isotope 2.2.1 erscheint der Fehler, wenn einer Benachrichtigung eine neue Nachricht hinzugefügt oder eine bestehende Nachricht verändert werden möchte. Das Erstellen neuer Benachrichtigungen ist möglich.

```
Sprachen

Warning: Missing argument 3 for NotificationCenter\tl_nc_language::generateWizardList(), called in /kunde/shop/system/modules/dcawizard/widgets/DcaWizard.php on line 154 and defined in system/modules/notification_center/classes/tl_nc_language.php on line 58
#0 system/modules/notification_center/classes/tl_nc_language.php(58): __error(2, 'Missing argumen...', '/kunde/...', 58, Array)
#1 system/modules/dcawizard/widgets/DcaWizard.php(154): NotificationCenter\tl_nc_language->generateWizardList(Object(Contao\Database\Mysql\Result), 'languages')
#2 system/modules/core/library/Contao/Widget.php(607): Contao\DcaWizard->generate()
#3 system/modules/core/templates/backend/be_widget.html5(3): Contao\Widget->generateWithError(true)
#4 system/modules/core/library/Contao/BaseTemplate.php(92): include('/kunde/...')
#5 system/modules/core/library/Contao/Widget.php(553): Contao\BaseTemplate->parse()
#6 system/modules/core/classes/DataContainer.php(520): Contao\Widget->parse()
#7 system/modules/core/drivers/DC_Table.php(1868): Contao\DataContainer->row('{title_legend},...')
#8 system/modules/core/classes/Backend.php(568): Contao\DC_Table->edit()
#9 contao/main.php(142): Contao\Backend->getBackendModule('nc_notification...')
#10 contao/main.php(293): Main->run()
#11 {main}

Fatal error: Call to a member function generateRowOperation() on a non-object in /kunde/public_html/shop/system/modules/notification_center/classes/tl_nc_language.php on line 78

**Comment by swisschris** [comment]
Gibt es eine Möglichkeit, wie die Lösung des Problems etwas beschleunigt werden könnte? Lässt sich dieser Fehler beheben, indem eine Erweiterung ge-downgradet wird?

**Comment by aschempp** [comment]
Naja, beschleunigen lässt sich dass in dem Du (oder der Entwickler deines Vertrauens) das Problem analysierst, und uns eine Fehlerkorrektur danach als Pull Request zur Verfügung stellst. Wir haben unsere Gedanken diesbezüglich auf unsere Webseite festgehalten: https://www.terminal42.ch/de/open-source.html

**Comment by swisschris** [comment]
Was würdet ihr denn dafür kosten? Ich finde den Shop prima und habe noch ein paar Interessenten, denen ich gerne Isotope anbieten würde. Aber dafür muss erst einmal einer sauber laufen...

**Comment by aschempp** [comment]
Wir biete Support im Rahmen des Isotope Circle (siehe https://circle.isotopeecommerce.org).

**Comment by aschempp** [comment]
Ich kann das Problem nicht nachvollziehen. Es hat aber sowieso nichts mit Isotope zu tun, sondern mit NotificationCenter und/oder DcaWizard. Bitte stell sicher dass du die entsprechenden Erweiterungen auf dem neusten Stand hast.
