### ISSUE TITLE
[2.1.9] Wrong order of months in chart

### ISSUE THREAD

**Issue by seaneble** [isotope/core#1359]
![statistik-reihenfolge](https://cloud.githubusercontent.com/assets/1255670/6016413/dd59617c-ab81-11e4-873d-d6c55869a404.png)

**Comment by aschempp** [comment]
Please update to the laste version and see if the issue still exists.

**Comment by seaneble** [comment]
The composer clients tells me 2.1.9 is the most current release. I will look into the reason for this, as indeed there is a newer version. This could take until next week.

**Comment by aschempp** [comment]
2.1.10 has a problem on Composer. We'll release 2.1.11 next week, I suggest you wait until that ;-)

**Comment by aschempp** [comment]
2.1.11 is available, please update and check again

**Comment by seaneble** [comment]
I installed the update, but the issue unfortunately remains.

**Comment by aschempp** [comment]
Related to #1163 but that only fixed day view. Now fixed for everything.
