### ISSUE TITLE
Product Management - Edit Multiple -> move selected to a group not working

### ISSUE THREAD

**Issue by davorgit** [isotope/core#1362]
to reproduce:
- click on Edit Multiple
- select let's say 10 products
- click on button Group
- select group to move to
- click Apply

Result: nothing happens products are not moved nor visible in a group

**Comment by aschempp** [comment]
I can't reproduce this, which version of Isotope do you use?

**Comment by davorgit** [comment]
I think latest, I've updated everything including Isotope, thru extension manager after the problems with dcawizard.

**Comment by aschempp** [comment]
This works perfectly fine for me in Isotope 2.1.11 and 2.2.2
