### ISSUE TITLE
PayPal Payment Data Transfer

### ISSUE THREAD

**Issue by Mynyx** [isotope/core#1364]
Bei der PayPal-Schnittstelle sollte zur Benachrichtigung über den Zahlungsvorgang zum Abschluss der Bestellung die PDT-Schnittstelle genutzt werden (Payment Data Transfer).

Eine ausführliche Beschreibung findet sich unter https://developer.paypal.com/docs/classic/ipn/integration-guide/IPNPDTAnAlternativetoIPN/.

> With PDT, your site is notified immediately when a customer completes payment. With IPN, however, there is a material lag between the time a customer completes payment and the time your site receives notification of this event.

Bei der IPN-Schnittstelle kann es leider dazu kommen, dass die Benachrichtigung nicht innerhalb einer Minute erfolgt, sodass der Kunde eine Fehlermeldung erhält, dass die Zahlung nicht erfolgreich war. Weiterhin ist es bei einer erheblichen Verzögerung möglich, dass die Zahlung nicht mehr zugeordnet werden kann.

**Comment by aschempp** [comment]
Ich schliesse das mal weil die PayPal API sich in den letzten 8 Jahren sicher wieder geändert hat und PDT wohl auch nicht mehr aktuell ist 😂
