### ISSUE TITLE
[2.2.2] Position Wasserzeichen

### ISSUE THREAD

**Issue by dengelstein** [isotope/core#1365]
Unter Shop-Konfiguration / Galerie bearbeiten kann die Position des Wasserzeichens nicht definiert werden. Die Felder sind zwar vorhanden, aber im Dropdown Menü ist keine Auswahl vorhanden.

**Comment by aschempp** [comment]
Wohl ein Contao 3.4-Problem, weil da die Responsive-Images dazugekommen sind.
