### ISSUE TITLE
Nested Form: Coupon-Modul

### ISSUE THREAD

**Issue by k-webdesign** [isotope/core#1366]
Hi,

die Eingabe des Coupon-Codes ist ein verschachteltes Formular:
![gutschein](https://cloud.githubusercontent.com/assets/4130440/6185806/ffdaf97e-b372-11e4-946f-37aa3012146e.PNG)

VG

**Comment by aschempp** [comment]
Für @Toflar 

http://www.w3.org/TR/2011/WD-html5-20110525/forms.html#the-form-element
> Content model:
> Flow content, but with no form element descendants.
