### ISSUE TITLE
payment paypal failed or just reloading waitng message

### ISSUE THREAD

**Issue by davorgit** [isotope/core#1368]
paypal successfully processed payment and redirected back to Isotope store but Isotope just refreshes process page and sometimes after a while redirects to /checkout/failed

Steps to reproduce:
- add ie. two products to cart
- press checkout
- do not login and continue without user login or registration
- fill out form end complete further steps
- press order
- what for redirect (You will be redirected to the payment gateway website.)
- fill in paypal developer test account personal data to register (email, password)
- wait for authentication
- press Pay Now button
- wait for loading message
- on screen Thanks for your order press link: Return to test account's Test Store
- redirects to /checkout/complete?uid=54dde1603941a1%2e40978611
- now you have infinite reload loop (eventually it redirect to failed page after 12-13 attempts)
- Orders module section doesn't show any records also
tried several times with no success ..I will try with registered user and report

![pptest](https://cloud.githubusercontent.com/assets/1269067/6187080/394540ca-b382-11e4-90cd-7c3aca4c65bb.jpg)

**Comment by Toflar** [comment]
Version of Isotope?

**Comment by aschempp** [comment]
You need to correctly set up IPN in your payment receiver accont.

**Comment by davorgit** [comment]
ver 2.2.1

**Comment by davorgit** [comment]
sorry for questioning here maybe it could help someone else:
What do I set for IPN Notification URL?

**Comment by aschempp** [comment]
There are tons of resources about that on the internet, I'm sure google would tell you…

Here's one: http://www.jotform.com/help/276-How-to-Enable-IPN-for-Paypal
The URL does not matter for Isotope.

**Comment by davorgit** [comment]
Thank you sir!
I would recommend to put some sort of notification message in the label for input PayPal Account* at the BE
like (Do not forget to set IPN) 

just to remember and for newbies ;)

**Comment by aschempp** [comment]
Yeah, it should actually be in the documentation, but thats currently in german only :-(
