### ISSUE TITLE
Order ID not incremented using non registered user

### ISSUE THREAD

**Issue by davorgit** [isotope/core#1370]
ver. 2.2.2
did not test yet registered user

![increment](https://cloud.githubusercontent.com/assets/1269067/6199287/2c0e2084-b43b-11e4-93a9-716aaeba9075.jpg)

**Comment by aschempp** [comment]
Do you possibly have multiple root sites with different store IDs?

**Comment by davorgit** [comment]
nope, only one root and one store id
I was thinking maybe it was something wrong because of testing with ngrok at the time when I didn't have IPN set
When I truncated order table then it was ok

**Comment by aschempp** [comment]
I'll close this then.
