### ISSUE TITLE
Product management - Image error in 2.2.2

### ISSUE THREAD

**Issue by EDsolution** [isotope/core#1372]
Hi,
I've just updated from 2.2.0 to 2.2.2 and when I add an image to a product there is no image, the image src is empty.

That goes for Product management product list and also in where you add/edit product.

**Comment by aschempp** [comment]
Which version of Contao?

**Comment by EDsolution** [comment]
3.4.4

**Comment by EDsolution** [comment]
Contao 3.4.4.

On frontend everything is OK.

**Comment by EDsolution** [comment]
Hm...now it doesn't work in front-end also.

**Comment by EDsolution** [comment]
Solved. 
There was no problem with Isotope version, but images were corrupted and the GD image library could not handle it.

Sorry, my mistake :|
