### ISSUE TITLE
Isotope bindet isotope.min.js in alle Seiten ein, auch wenn kein Isotope-Modul/-CE aktiv ist

### ISSUE THREAD

**Issue by NinaG** [isotope/core#1374]
Eigentlich sollte Isotope die isotope.min.js nur dann in den Header von Seiten einbinden, wenn auf diesen ein Isotope-Modul/-CE vorhanden ist. Aktuell wird das Javascript aber immer auf allen Seiten der gesamten Website eingebunden.

Das ist aus mehreren Gründen problematisch, insbesondere wenn die eigentliche Website (bis auf die "echten" Shop-Seiten) auf jQuery basiert und nun hier plötzlich ein MooTools-Script daher kommt. Ebenso kann es dadurch zu Problemen mit anderen Scripts der Seiten kommen (wie in aktuellen Projekten geschehen). 

Das ist ein fataler Fehler, der uns derzeit bei einem Projekt dazu zwingt, andere Scripte umprogrammieren zu lassen und jede einzelne Seite der Website in unterschiedlichen Browsern nachzutesten, weil sie wegen diesem unpassenden Script in gewissen Browsern nicht mehr funktionieren.

**Comment by NinaG** [comment]
Testcase, wie im Forum-Thread beschrieben:

* Contao 3.4.4 (aber auch schon mit 3.3.7 getestet) frisch installieren
* Isotope 2.2 - frisch über ER installiert (auch schon mit Isotope 2.0 getestet)
* In Isotope nur eine Testkonfig anlegen (Pflichtfelder), sonst nichts konfigurieren
* On der Seitenstruktur eine neue Struktur starten, beim Startpunkt der Website die Isotope-Testkonfig angeben und ein paar Testseiten ohne Inhalt anlegen
* Ein neues Testlayout ohne Inhalt (damit Contao keine Fehlermeldung wegen fehlendem Layout ausgibt). erstellen und dem Startpunkt der Website zuweisen
* Auf den Seiten/im Layout kein einziges eingebundenes Modul,/kein Inhaltselement.

Voila, im Frontend auf der Testseite erscheint das Javascript:
http://isotope-test.ninagerling.de/ (im Header des Quelltextes).

Geb euch gerne einen Zugang, wenn ihr wollt. 

Getestet bei All-Inkl und Uberspace.

**Comment by aschempp** [comment]
Here's the reason: https://github.com/isotope/core/commit/fbf9d341715f0f5679b53479a485c601551866da#diff-6ae8d0caf72c4193990ee4ad4a2649a7R99
