### ISSUE TITLE
[2.2.2] problems with change productdata

### ISSUE THREAD

**Issue by MoniqueHahnefeld** [isotope/core#1375]
Contao 3.4.2
Hi,
in the demo I've installed is a strange problem, seams to be a bug.
After add a custom product type and change the product type of product "outer-space-2042" the teaser data is not updated. In the Frontend I see still the old one. 

The product type before was with variants. So I set it back and delete the generated variants. Problem still exists. I have for testings a checkbox attribute where I can select products (custom database table - tl_iso_product.id). In this checkbox I can see the product "2042 Outer space" tree times.
How is this possible? Seems that there are old datas in the table. Maybe a bug in the delete event function or something?

Thx a lot :)

(no urgent matter for me)

**Comment by aschempp** [comment]
Ich glaube wenn du die grundlegende Konfiguration eines Produkt änderst, solltest du auch das Produkt neu anlegen. In einem Real-World Szenario wird das nie vorkommen (ein Wein wird nicht plötzlich zu einem Buch). Der Aufwand diese Sonderfälle abzufangen ist einfach unnötig hoch.
