### ISSUE TITLE
calculateAmountIncludedInPrice logic

### ISSUE THREAD

**Issue by siggj** [isotope/core#1376]
In the TaxRate class in Model package, calculateAmountIncludedInPrice method,  when isPercentage is true, why the method return 

$fltPrice - ($fltPrice / (1 + ($this->getAmount() / 100))) 

and not  

$fltPrice / 100 * $this->getAmount() ?

I don't understand this logic because if i have a product (CHF 100) and a tax (8%) the total tax must be CHF 8 if the tax is include in price.. 

Any explications ?

**Comment by aschempp** [comment]
The tax is not 8, the tax is 7.40.
100$ is 108% of the net value, the net value is 92.60

**Comment by siggj** [comment]
Well, so i can't have something like this when i display the cart : 

Product 1 : 100$
Tax include in product price (8%) : 8$
Total : 100$

**Comment by aschempp** [comment]
Yes you can, but the tax value will be 7.40$ because thats mathematically correct ;-)
