### ISSUE TITLE
Current's product category - cache issue

### ISSUE THREAD

**Issue by EDsolution** [isotope/core#1383]
If you purge data and you go to product 1 it will show the related product in the same category. But when you go to product in Y category it will show again the same related product as before, that's because it uses product cache and it's always the same for all product - no matter in which category you are.

I've expirianced this almost in every version - the solution was to set false on $blnCacheProducts but I doubt that this is the right solution.

**Comment by aschempp** [comment]
Which version of Isotope?

**Comment by EDsolution** [comment]
I think that everyone, even latest.
