### ISSUE TITLE
Demo SQL kann nicht importiert werden

### ISSUE THREAD

**Issue by patric-eberle** [isotope/core#1384]
Beim Versuch die Isotope Demo auf Mac OS X zu installieren, erhalte ich einen Fehler sowohl in Sequel Pro als auch beim Versuch die SQL-Datei über /contao/install.php einzuspielen.

Fehler in Sequel Pro:
Beim Importieren der Datei ist ein Fehler aufgetreten, da sich nicht mit dem ausgewählten Zeichensatz (Automatisch erkennen - Unicode (UTF-8)) gelesen werden konnte.

**Comment by aschempp** [comment]
Das Problem hatte ich auch schon, versuch es bitte mal mit phpMyAdmin

**Comment by Toflar** [comment]
Habe ich auch ständig, das ist glaube ich ein Sequel Pro-Issue. Immer wenn ich den Content manuell paste und alle Queries ausführe geht's. Nur mit der Import-Funktion nicht O.o

**Comment by patric-eberle** [comment]
Habe jetzt die Daten testweise noch mit phpMyAdmin importiert. Der schien das nicht so kritisch zu sehen und hat den Import gemacht. Den Vorgänger-Dump für 2.2.1 konnte ich übrigens auch mit Sequel importieren.
