### ISSUE TITLE
 Attribut-Typ Select-Menü & Optionen Gruppe (optgroup)

### ISSUE THREAD

**Issue by rflx** [isotope/core#1387]
Hi,
sobald man beim Attribut-Typ Select-Menü die Optionen mittels Gruppe (optgroup) gruppiert, wird ein leeres Select-Menü im Frontend ausgegeben. Verwendet man keine Optionen Gruppe bei den Attributen wird die Ausgabe im Frontend erfolgreich ausgegeben.

Contao 3.4.3
![bildschirmfoto 2015-03-09 um 09 52 33](https://cloud.githubusercontent.com/assets/7251106/6552111/332d68d4-c642-11e4-8204-5a1538b0c295.png)

**Comment by aschempp** [comment]
Verwendest du das Select-Menü als Varianten-Attribut?

**Comment by rflx** [comment]
Genau, habe es als Varianten-Attribut verwenden wollen.

**Comment by aschempp** [comment]
Ein Varianten-Attribut kann keine Gruppen haben.
