### ISSUE TITLE
Manual product sorting is not working

### ISSUE THREAD

**Issue by davorgit** [isotope/core#1388]
I have this js error:
Isotope.makePageViewSortable is not a function

**Comment by delirius** [comment]
Bei mir funktioniert es auch nicht, gleiche Fehlermeldung. Contao 3.4.4 mit Isotope 2.2.2, Chrome und Firefox

**Comment by EDsolution** [comment]
Hi. I have test manual sorting in Isotope 2.4.0 RC and Contao isotope 3.5.14 and there is no sorting / move option in Product management. I've also try to isotope via Group or Page but there is no move icon or drag mode.

Or is there something else / more to do to make this happen?

Thanks.

**Comment by EDsolution** [comment]
Nevermind...found the hidding icon :)
