### ISSUE TITLE
be-rendering > options source > foreign key Ausgabefehler

### ISSUE THREAD

**Issue by Hauge** [isotope/core#1389]
Seit 2.2.2 wird in der Variantenansicht die ID und nicht mehr der Titel ins backend gerendered:
![varianten](https://cloud.githubusercontent.com/assets/1571133/6551070/9c3cc4c4-c632-11e4-9322-c444fd412f9c.jpg)

**Comment by aschempp** [comment]
Ich vermute du verwendest den neuen Options-Manager in Version 2.2?

**Comment by Hauge** [comment]
ja.
