### ISSUE TITLE
 [Iso 2.2.2] Bildgröße einstellen im BE bei "Bestellungen" 

### ISSUE THREAD

**Issue by xantippe** [isotope/core#1390]
In meiner Detailansicht der bestellung habe ich "riesige" Bildchen meiner Produkte - kann das irgendwo eingestellt werden?

siehe auch:
https://community.contao.org/de/showthread.php?55903-Iso-2-2-2-Bildgr%F6%DFe-einstellen-im-BE-bei-quot-Bestellungen-quot

Beispiel:
![bestellung](https://cloud.githubusercontent.com/assets/1045318/6554929/00a01578-c661-11e4-8aca-84100ab0c7fe.jpg)

**Comment by aschempp** [comment]
Bitte wende dich für Fragen an's Community-Forum (https://community.contao.org/de/forumdisplay.php?111-isotope) oder alternativ den Isotope Circle (https://circle.isotopeecommerce.org).

**Comment by xantippe** [comment]
In der Community bin ich verewigt...

=> mit scheint es eher ein Bug, wenn es nicht so gewollt ist, oder eine FR, wenn es keinem aufgefallen ist

**Comment by xantippe** [comment]
könnte mit dem hier passen... 
https://github.com/isotope/core/issues/1189

**Comment by aschempp** [comment]
Es ist eine Konfiguration, du brauchst ein Modul mit einer Galerie ;-)

**Comment by xantippe** [comment]
habe drei Stück
![konfig-galerie](https://cloud.githubusercontent.com/assets/1045318/6555911/f1210338-c669-11e4-9890-e7f391543546.jpg)

**Comment by xantippe** [comment]
Die Galerie war nicht das "Problem" - Die Anzeige der Bestellungen im BE zieht das gleiche Template wie bei dem FE-Modul "Bestellungsdetails" - wenn da nix gesetzt ist, werden die Bilder in max. Größe angezeigt...
