### ISSUE TITLE
FR: zu hasImages() noch hasGalleryImages()

### ISSUE THREAD

**Issue by xantippe** [isotope/core#1393]
Hallo,

aktuell kann man mit hasImages() abfragen, ob man in einer Gallerie ein Bild erhält - leider wird ein TRUE geliefert, wenn man zwar keine Produktbilder aber Fall-Back-Bild hat.

Hier wäre es zur Unterscheidung gut, wenn man explizit nach Produktbildern z.B. per hasGalleryImages() abfragen könnte.

Workaround z.Z.
```
if(strpos($this->getGallery('images')->generateMainImage(), 'produkt_dummy.jpg') !== false) {
// kein Produktbild
}
```

**Comment by Toflar** [comment]
Könnte man abfangen wenn man meine `hasPlaceHolderImage()` `public` statt `protected` machen würde...
https://github.com/isotope/core/pull/1360

**Comment by xantippe** [comment]
hmmm... soweit ich das verstanden habe, prüft ```asPlaceHolderImage()``` (Checks if a placeholder image is defined) ab, ob ein Placeholder definiert wurde...

... meine "Fragestellung" ist ja: "ist ein Produktbild vorhanden?" - wobei mit Produktbild nicht der Placeholder gemeint ist sondern ein "echtes"

**Comment by Toflar** [comment]
In meinem PR könntest du einfach `if ($this->getGallery('images')->size() >= 1)` machen. Nicht jede Galerie hat ja zwingend ein Haupt-Bild und eine Galerie. Es könnte auch eine geben, die immer nur das 1. Bild behandelt, da würde eine `hasGalleryImages()` gar keinen Sinn ergeben.

**Comment by Toflar** [comment]
Ist jetzt im "develop"-Branch, kannst du mal schauen, ob das dein Problem löst?

**Comment by aschempp** [comment]
Closing this without feedback, let's reopen when there is more info.
