### ISSUE TITLE
Produkt Attribute Einstellungen werden nicht eingehalten

### ISSUE THREAD

**Issue by rakias** [isotope/core#1395]
Hallo,

habe ein Produkt, welches 3 Attirbute mit unterschiedlichen Werten beinhaltet. Die Attribute 2 und 3 sind kombinierbar. Sobald ich aber das zweite Attribut ändere, wird mir generell das Standardprodukt angezeigt. Es wird also nicht die Artikelvariante angezeigt. Woran kann das liegen?

**Comment by aschempp** [comment]
Was heisst "Attribut 2 und 3 sind kombinierbar"? Welche Attribut-Typen hast du verwendet?

**Comment by rakias** [comment]
Ok, sorry das ich nicht so ausführlich war. Ich nutze Contao 3.4 mit Isotope 2.2.2. Ich habe einen Artikel mit 3 Attributen (Farbe, Größe, Bettüberwurf). Diesen Artikel gibt es in jeder Farbe und Größe mit und ohne den entsprechenden Bettüberwurf. Der Bettwüberwurf ist der dritte Parameter und ist abhängig von der Größe des Artikels. Also vom zweiten Parameter. Je nachdem welche Größe der Artikel hat, wird entsprechend  der dritte Parameter in der Größe angezeigt. Das funktioniert auch alles soweit. Sobald ich aber dann den zweiten Parameter wieder ändere, wird mir das Standardprodukt eingeblendet. 
Habe jetzt auch zwischendurch einen unabhängingen Test mit Varianten gemacht. Ein Artikel mit zwei Attributen. Unterschiedliche Größen und Farben. Sobald im zweiten Produkt eine Größe nicht vorhanden ist, welche im ersten Artikel vorhanden ist, wird das erste Produkt eingeblendet. Das darf nicht sein. Es muß das vorausgewählte Produkt mit der entsprechenden Farbe stehen bleiben.
Was kann man hier tun? Falls es zu komplex erklärt ist, kann ich auch gernen einen Link zu senden.

**Comment by aschempp** [comment]
Ich weis was du meinst, aber das geht leider nicht anders. Die Attribute werden "von oben nach unten" bearbeitet. Wenn du Attribut 2 änderst, werden alle nachfolgenden Optionen gelöscht und neu geladen, um entsprechend gültige Werte zu finden. Würde das nicht gemacht und die Option 3 wäre unpassend, wären alle Optionen leer (da keine gültige Kombination gefunden werden kann).

**Comment by rakias** [comment]
Hallo nochmals,

das kann ja nicht sein. Hier noch ein einfaches Beispiel. Als Standardprodukt habe ich das Produkt mit Farbe "braun" und der Größe "S" angelegt. Folgende Varinaten sind dazu angelegt:

Produktvarianten (Produkt 1)
Attribut 1 Farbe: braun
Attribut 2 Größe: S,M,XL

Produktvarianten (Produkt 2)
Atrribut 1 Farbe: hellgrau
Attribut 2 Größe: S, M, L

Ich wähle nun bei Produkt 1 die Farbe braun und die Größe XL aus. Ändere ich jetzt nun das Attribut Farbe auf hellgrau (Produkt 2), wird mir das Bild und entsprechend das Standardprodukt (Produkt 1) eingeblendet. Das Ergebnis ist somit falsch. Es muß doch das Produkt 2 mit z.B. der kleinsten Größe angezeigt werden.

**Comment by netzarbeiter** [comment]
Für mich kann dieses Ticket geschlossen bleiben.

Ich wähle bei Produkt 1 die Farbe braun und die Grösse XL aus. Ändere ich die Farbe auf hellgrau, wird dir das Bild nicht angezeigt, da es für dieses Produkt die Grösse XL nicht gibt. Das Bild wird erst geändert, wenn du eine passende Grösse (S, M, oder L) ausgewählt hast. Wenn die Grösse automatisch geändert werden würde, könnte das zu Fehlbestellungen (S statt XL) führen.

**Comment by rakias** [comment]
Ich sehe das genau anders. Ich ändere die Farbe, welches in diesem Fall das Hauptkriterium ist und es wird mir immer noch die andere Farbe angezeigt. 

Es ist korrekt, dass es die gewünschte Größe in der Farbe nicht gibt. Aber warum wechselt das Produkt nicht komplett auf "hellgrau" und zeigt mir nur die zur Verfügung stehenden Optionen an. Die Größe wird doch in dem Fall automatisch auf "S" heruntergefahren. Warum sollte mir dann auch nicht das Produkt in der aktuellen Farbe angezeigt werden? 

Wenn es so bleibt würde ich die falsche Farbe bestellen! Ich habe "hellgrau" ausgewählt und es wird "braun" bestellt!

**Comment by netzarbeiter** [comment]
In der [Demo](https://isotopeecommerce.org/de/demo.html) wird ein Weg aufgezeigt, wie es zur Zeit mit Isotope funktioniert.

![attribut](https://cloud.githubusercontent.com/assets/1942550/6669909/f00b9f8e-cbfb-11e4-8bf7-af3bdbd296c4.png)

**Comment by rakias** [comment]
Mittlerweile hab ich auch die Reihenfolge der Filter getauscht und das Ergebnis ist wieder falsch. Sobald es einen Artikel nicht in der Variante gibt, wird mir die falsche Produktnummer und damit das falsche Produkt angezeigt. Die Auswahlboxen zeigen keine Ungereimtheiten an. Das Produkt ist aber falsch. Fatal für eine Kundebestellung! Schade das es keinem auffällt. Ihr könnt mir ja gerne euer Beispiel zeigen, damit ich es nachvollziehen kann oder sogar sehen kann was ich angeblich falsch mache.....

**Comment by aschempp** [comment]
Ich glaube es gibt hier noch ein Missverständnis. Solange nicht in allen vorhandenen Optionen eine gültige Auswahl getroffen wurde, zeigt Isotope immer die Basis-Konfiguration an. Aus diesem Grund erscheint auch das graue (Fallback) Bild, wenn die Auswahl sich ändert. Das unvollständige Produkt kann aber nicht bestellt werden, da besteht also keine Gefahr.

**Comment by rakias** [comment]
Genau das ist doch das Problem. Warum sollte die PRODUKTNUMMER! und das Bild aus der Grundkonfiguration angezeigt werden? Hier sollte die getätigte Auswahl sofort aktualisiert werden und meinetwegen die "Basiskonfiguration" des ausgewählten Produkts (PRODUKTNUMMER und Bild) angezeigt werden.

**Comment by aschempp** [comment]
Hier ist dein Missverständnis: Ohne eine gültige Kombination von ALLEN Werten, kann kein Bild oder Produktnummer einer bestimmten Variante angezeigt werden.

**Comment by rakias** [comment]
Klicke bitte auf folgenden LInk:
http://htb.polaris-preview.de/hundebetten/swiss-greyge-velours.html

Wähle dann im Select Menu nur die Größe XXL aus. Es wird dir das korrekte Produkt inklusive Produktnummer BE-SV-XXL-GR angezeigt.

Jetzt tausche die Farbe auf "hellgrau" in der oberen Selectbox. Das Produkt gibt es in der Größe XXL nicht. Korrekterweise gehen die Auswahlboxen auf die Ausgangsgröße S zurück, da es keine XXL Auswahl gibt. 

Und jetzt zum Problem: Die Artikelnummer und das Produktbild im linken Bereich stimmen mit den Werten der Auswahlboxen nicht überein. Es wird die Artikelnummer BE-SV-S-GR
vom Basisprodukt verwendet. Das Produktbild ist entsprechend auch vom Basisprodukt. 

Hier müßte laut Auswahlboxen folgende Artikelnummer BE-SV-S-HG stehen. Das ist das Problem!

**Comment by netzarbeiter** [comment]
Die "S" ist dann nicht wirklich ausgewählt, wird aber angezeigt da du auf meinen Tipp mit "Bitte auswählen" verzichtet hast. Wende dich für Fragen betreffend Isotope bitte ans [Forum](https://community.contao.org/de/forumdisplay.php?111-isotope).

**Comment by aschempp** [comment]
Ein Basisprodukt kann keine Artikelnummer haben, weil das Basisprodukt immer nur die Basis für Varianten ist. In deinem Fall ist das Basisprodukt bereits die Variante S, was falsch ist.

**Comment by rakias** [comment]
Ich muß dem Basisprodukt doch eine Artikelnummer geben. Das ist ein Pflichtfeld. Ausschalten kann ich es leider auch nicht, obwohl diese Option unter Produkttypen angeblich gegeben ist. Das habe ich bereits getestet. Was mache ich falsch?
Hier ein kleiner Auszug zu den Varianten. Leider können wir keine Artikelnummer zu weisen. Diese wird vom Basisprodukt als Vorgabewert übernommen.
![attribute](https://cloud.githubusercontent.com/assets/11441297/6683808/0e0b0f94-cc8b-11e4-8fd1-654d13ea6253.jpg)

**Comment by aschempp** [comment]
Die Artikelnummer kannst du sehr wohl im Produkttyp konfigurieren. Wie @netzarbeiter wenden dich ggf. bitte an's Forum, das Ticketsystem ist für Bugs und Feature Requests.

**Comment by rakias** [comment]
Würde das das Problem lösen?
