### ISSUE TITLE
The "startTime" and "endTime" values seem to be restricting rules independently from "startDate" and  "endDate"

### ISSUE THREAD

**Issue by adamffyl** [isotope/core#1399]
In Isotope\Model\Rule::findByConditions, shouldn't the startTime and endTime restrictions be calcuated with the startDate and endDate values?  Otherwise, it seems like the rule would run from startDate to endDate, but be restricted to the startTime and endTime every day it runs.  If this is the intended functionality, shouldn't the user additionally be given the option to start the rule on a certain day at a certain time, and end it on a certain day at a certain time?

**Comment by aschempp** [comment]
The functionality is intended, but I agree that both versions would make sense.

**Comment by aschempp** [comment]
This seems to be implemented by https://github.com/isotope/core/pull/2120 🙃
