### ISSUE TITLE
[2.12] Falscher "date:added" Wert bei Erstellen eines neuen Produktes durch Kopieren

### ISSUE THREAD

**Issue by anjuis** [isotope/core#1400]
Value 0

**Comment by Toflar** [comment]
Version?

**Comment by anjuis** [comment]
2.12

**Comment by Toflar** [comment]
Die Version von Isotope natürlich, nicht die von Contao :)

**Comment by anjuis** [comment]
Warning: checkdate() expects parameter 1 to be long, string given in system/modules/core/library/Contao/Date.php on line 442
#0 [internal function]: __error(2, 'checkdate() exp...', '/www/htdocs/w01...', 442, Array)
#1 system/modules/core/library/Contao/Date.php(442): checkdate('}', 1, 'a:0:')
#2 system/modules/core/library/Contao/Date.php(89): Contao\Date->dateToUnix()
#3 system/modules/core/library/Contao/Widget.php(1340): Contao\Date->__construct('a:0:{}')
#4 system/modules/core/classes/DataContainer.php(249): Contao\Widget::getAttributesFromDca(Array, 'date', 'a:0:{}', 'date', 'tl_iso_product', Object(DC_ProductData))
#5 system/modules/isotope/drivers/DC_ProductData.php(636): Contao\DataContainer->row()
#6 system/modules/core/classes/Backend.php(430): DC_ProductData->edit()
#7 contao/main.php(142): Contao\Backend->getBackendModule('iso_products')
#8 contao/main.php(293): Main->run()
#9 {main}

Fatal error: Uncaught exception OutOfBoundsException with message Invalid date "a:0:{}" thrown in system/modules/core/library/Contao/Date.php on line 444
#0 system/modules/core/library/Contao/Date.php(89): Contao\Date->dateToUnix()
#1 system/modules/core/library/Contao/Widget.php(1340): Contao\Date->__construct('a:0:{}')
#2 system/modules/core/classes/DataContainer.php(249): Contao\Widget::getAttributesFromDca(Array, 'date', 'a:0:{}', 'date', 'tl_iso_product', Object(DC_ProductData))
#3 system/modules/isotope/drivers/DC_ProductData.php(636): Contao\DataContainer->row()
#4 system/modules/core/classes/Backend.php(430): DC_ProductData->edit()
#5 contao/main.php(142): Contao\Backend->getBackendModule('iso_products')
#6 contao/main.php(293): Main->run()
#7 {main}


1. Kopierte Produkte sind nicht mehr bearbeitbar. (Fehler oben) Gibt es da schon eine Lösung bis das Update da ist?

2. Unter "mehrere bearbeiten" lässt sich auch bei ohne die Kopierfunktion erstellten Produkten das Datum nicht neu setzen. Es fehlt die Auswahlmöglichkeit  "Date".

**Comment by aschempp** [comment]
Ich kann das Problem nicht nachvollziehen. `dateAdded` ist kein Wert welcher im Backend bearbeitet werden kann, hast du da etwas am DCA modifiziert?

**Comment by anjuis** [comment]
Nein, keine Modifizierung. 

Ist eine Entwicklungsinstallation, die Anzahl der betroffenen Produkte ist überschaubar, ich hoffe das dann korrigieren zu können.

**Comment by aschempp** [comment]
Warum schliesst du das Ticket?

**Comment by anjuis** [comment]
Wenn es nicht nachvollziehbar ist? Ich habe schon einen Date Eingabefeld im Backend bei jedem Produkt.

**Comment by aschempp** [comment]
Wie sieht die Konfiguration für das Feld aus?

**Comment by anjuis** [comment]
![download](https://cloud.githubusercontent.com/assets/3777247/8276567/55b8d500-18b8-11e5-9d0e-306e7bc86bb0.png)

**Comment by aschempp** [comment]
Ok, also unser Feld heisst `dateAdded`. Sollte also dein Feld nicht betreffen. Wir denn dein Feld nicht korrekt eingetragen oder das interne?

**Comment by anjuis** [comment]
Was meinst Du genau mit "dein Feld" - ich habe nichts eigenes eingebaut, lediglich in der Shopkonfiguration unter Attribute das Attribut "Date"  - nachträglich hinzugefügt. Die vorher erstellten und nicht mehr editierbaren Produkte habe ich jetzt gelöscht und gebe sie neu ein. Ich habe gerade versucht, den Fehler zu reproduzieren, zum Glück ohne Erfolg. Vielleicht ist der Grund für die Fehlermeldung wirklich nur das Hinzufügen des Attributes "Date" (Screenshot) und verbunden mit dem Kopieren von Produkten, die vor dem Hinzufügen des Attributes erstellt wurden.

**Comment by aschempp** [comment]
Ich versuche mal das zu reproduzieren :)

**Comment by tsarma** [comment]
Just a blind shot. The field name 'date' may not be optimal as it is a MySQL reserve word.

**Comment by anjuis** [comment]
Das Attribut "Date" ist bei Produkte unter "mehrere bearbeiten" nicht editierbar. Ist das so gewollt?

**Comment by aschempp** [comment]
Ich kann das leider nicht reproduzieren. Bitte nenne das Feld nicht `date` (interner Name), das könnte zu MySQL-Problemen führen.

**Comment by anjuis** [comment]
Kann ja sein, wird vielleicht nícht weiter relevant sein. habe aber definitiv KEINE Feldnamen ( date ) etc. selber gesetzt. Hier ein Screenshot aus der Demoinstallation.
![shop-konfiguration](https://cloud.githubusercontent.com/assets/3777247/8984747/e40d4802-36d3-11e5-963e-6e39ec88f249.png)

**Comment by aschempp** [comment]
Du hast ein eigenes Attribut erstellt, welches `date` heist ;-)
