### ISSUE TITLE
Zeilenumbruch bei Attribut Textarea

### ISSUE THREAD

**Issue by delirius** [isotope/core#1401]
Beim Attribute textarea (Durch den Kunden auswählbar) werden die Zeilenumbrüche nicht berücksichtigt.   Im E-Mail sowie im BE unter Bestellungen und im Rechnungs-PDF wird alles auf einer Zeile dargestellt.

**Comment by aschempp** [comment]
@Toflar wie sollen wir das lösen? Ist ja auch ein generelles Problem des Notification Center, weil das Token sowohl im Plain Text als auch HTML benutzt werden kann…

**Comment by Toflar** [comment]
Das Notification Center strippt doch automatisch Tags?
