### ISSUE TITLE
Kasse: Versandadresse bei Übereinstimmung mit Rechnungsadresse ersetzen

### ISSUE THREAD

**Issue by Mynyx** [isotope/core#1402]
Bei Absenden des Schrittes "Adresse" in der Kasse könnte, wenn die Versandadresse mit der Rechnungsadresse übereinstimmt (oder in der Rechnungsadresse lediglich weitere Felder ausgefüllt sind, die in der Versandadresse deaktiviert sind), die Versandadresse mit der Rechnungsadresse ersetzt werden.
Dadurch wäre bei der weiteren Bearbeitung der Bestellung erkennbar, dass es sich nicht um eine abweichende Versandadresse handelt und im Adressbuch des Benutzers würden ebenfalls keine "Duplikate" angelegt werden.

**Comment by aschempp** [comment]
Der Kunde kann ja wählen ob er die Rechnungsadresse verwenden will. Wenn er so "blöd" ist und sagt "Abweichende Adresse" aber dann trotzdem dasselbe eingibt, können wir ihm ja nicht wirklich helfen…
