### ISSUE TITLE
[2.2] Kasse Schritt /process/ ohne Validierung

### ISSUE THREAD

**Issue by Mynyx** [isotope/core#1403]
Bei Aufruf der Kasse Schritt /process/ erfolgt keine Validierung ggf. wird sogar eine "leere" Bestellung erstellt.

**Comment by Mynyx** [comment]
Fix in https://github.com/isotope/core/blob/master/system/modules/isotope/library/Isotope/Module/Checkout.php#L164
````
                // canCheckout will override the template and show a message
                if (!$this->canCheckout()) {
                    return;
                }
````

**Comment by aschempp** [comment]
Fixed in 0d2f54d
