### ISSUE TITLE
[2.12] Über das Backend definierte CSS-Klasse im Modul Produktliste wird ignoriert

### ISSUE THREAD

**Issue by anjuis** [isotope/core#1405]
Ich suche aktuell eine Möglichkeit, über Mediaqueries steuerbare Spaltensets auf die Produktlisten zu legen. Dazu war gedacht, für die jeweilige Produktliste eine Variation per CSS-Klasse zu definieren (z.B. 4-2-1). Mir ist übrigens überhaupt nicht klar, wie das mit den automatischen zugeordneten Koordinaten-Klassen funktionieren soll (-->"Wählen Sie die Anzahl der Spalten"), die Produkte vernünftig in ein responsives Design zu bringen. Die Anzahl der Spalten wird ja hier unabhängig von der Breite grundlegend festgelegt, oder habe ich da etwas übersehen?

**Comment by anjuis** [comment]
Ich suche aktuell eine Möglichkeit, über Mediaqueries steuerbare Spaltensets auf die Produktlisten zu legen. Dazu war gedacht, für die jeweilige Produktliste eine Variation per CSS-Klasse zu definieren (z.B. 4-2-1)
Ich glaube zwar noch nicht, dass das so funktioniert, aber jedenfalls ist mir das bei der Suche nach einer Lösung hier aufgefallen.

**Comment by aschempp** [comment]
Der Titel deines Tickets scheint nichts mit der Beschreibung zu tun zu haben? Die Auswahl der Spalten generiert dir lediglich CSS-Klassen, stylen musst du die selber.

**Comment by anjuis** [comment]
- um mit Mediaqueries eigene responsive Spaltensets (stylen) generieren zu können, würde ich dem Modul gerne eine Klasse mitgeben, das Feld ist jedoch ohne Wirkung -->
"[2.12] Über das Backend definierte CSS-Klasse im Modul Produktliste wird ignoriert"

Sorry für die Zusatzfrage, das gehört nicht in die Issues.

**Comment by aschempp** [comment]
Du machst wohl einen Standard-Fehler. Die CSS-Klasse aus dem Modul wird in einem Inhaltselement nicht übernommen. Das Forum kann dir hier weiterhelfen.

**Comment by anjuis** [comment]
Ok, danke, habe Ninas Beitrag gefunden, die Klasse und ID eines Moduls wird imho nur angezeigt, wenn das Modul über das Layout eingebunden wird und beim Modul im Inhaltselement ignoriert.
