### ISSUE TITLE
[2.2.3] Statistiken Datumsdarstellung fehlerhaft

### ISSUE THREAD

**Issue by Mynyx** [isotope/core#1406]
In der Gesamt-Statistik wird bei Zeitraum nur ein unformatierter Timestamp (z. B. 1427238000) angezeigt und bei der Produkt-Statistik ist die Darstellung in der Kopfzeile ebenfalls fehlerhaft (z. B. %25.%03.%15).

**Comment by aschempp** [comment]
Hast du die Templates für die Anzeige manuell angepasst? Die haben sich in der 2.2.3 geändert.

**Comment by Mynyx** [comment]
Nein, auch in einer Installation ohne individuelle Templates treten die Fehler auf.
