### ISSUE TITLE
Ordner /isotope verschieben nach /assets/isotope

### ISSUE THREAD

**Issue by Mynyx** [isotope/core#1407]
Wenn der Ordner /isotope mit den Produktbildern in der Ordnerstruktur nach /assets/isotope verschoben werden würde, hätte dies insbesondere den Vorteil, dass die Produktbilder grundsätzlich über die in den Contao-Einstellungen festlegbare Assets-URL geladen würden (statt wie derzeit nur teilweise in dem Fall, dass sie von Contao verkleinert und unter /assets/images abgelegt wurden).

**Comment by aschempp** [comment]
Das hat mit dem Ablageort wenig zu tun, aber vielleicht können wir das optimieren.
