### ISSUE TITLE
[2.2.3] Versionswiederherstellung von Produkt setzt Eingabe bei zwischenzeitlich hinzugefügten Attribut nicht zurück

### ISSUE THREAD

**Issue by Mynyx** [isotope/core#1408]
1. Ein Produkt anlegen
2. Ein neues Attribut anlegen und dem Produkttyp zuordnen
3. Produkt bearbeiten, Eintragung bei neuem Attribut vornehmen und speichern
4. Erste Version des Produktes wiederherstellen
=> Die Eintragung beim neuen Attribut ist immer noch vorhanden - bei der Versionswiederherstellung wird offenbar nicht geprüft, ob ein Attribut/Feld in der alten Version nicht vorhanden war

**Comment by aschempp** [comment]
Das ist ein generelles Contao-"Problem" und wäre bei jedem selber-definierten Feld der Fall. Vielleicht kann @leofeyer was dazu sagen ob wir das im Core ändern sollten?

**Comment by leofeyer** [comment]
Ich verstehe das Problem nicht ganz.

**Comment by aschempp** [comment]
The `tl_version` Tabelle speichert ein serialisiertes Array der vorherige Daten beim erzeugen einer Version. Beim wiederherstellen werden die Felder überschrieben, welche in diesen serialisierten Daten vorhanden sind. In neuen Feldern, welche in der Zwischenzeit hinzugefügt wurden, bleiben die vorhandenen Daten erhalten, obwohl sie nicht zu dieser Version gehören.

Dasselbe Problem gibt es übrigens auch wenn ein Feld entfernt wurde. Dann kommt ein DB-Error weil ein Feld nicht vorhanden ist das befüllt werden soll.

Vielleicht können wir das auf einen Schlag lösen? Könnte einen PR machen falls du das Problem auch siehst.

**Comment by leofeyer** [comment]
Ja, das Problem sehe ich auch. Gerne PR :)

**Comment by aschempp** [comment]
see https://github.com/contao/core/issues/7755
