### ISSUE TITLE
[3.4.5 - 2.2.3] iso_list_empty template missing

### ISSUE THREAD

**Issue by syncgw** [isotope/core#1414]
PHP Fatal error: Uncaught exception 'Exception' with message 'Could not find template "iso_list_empty"' thrown in U:\www\test\system\modules\core\library\Contao\TemplateLoader.php on line 123
#0 U:\www\test\system\modules\core\library\Contao\Controller.php(71): Contao\TemplateLoader::getPath('iso_list_empty', 'html5', 'templates/syncg...')
#1 U:\www\test\system\modules\isotope\library\Isotope\Template.php(60): Contao\Controller::getTemplate('iso_list_empty', 'html5')
#2 U:\www\test\system\modules\core\library\Contao\BaseTemplate.php(81): Isotope\Template::getTemplate('iso_list_empty', 'html5')
#3 U:\www\test\system\modules\core\library\Contao\Template.php(238): Contao\BaseTemplate->parse()
#4 U:\www\test\system\modules\core\classes\FrontendTemplate.php(38): Contao\Template->parse()
#5 U:\www\test\system\modules\isotope\library\Isotope\Model\Product\Standard.php(681): Contao\FrontendTemplate->parse()
#6 U:\www\test\system\modules\isotope\library\Isotope\Module\ProductList.php(234): Isotope\Model\Product\Standard->generate(Array)
#7 U:\www\test\system\modules\core\modules\Module.php(154): Isotope\Module\ProductList->compile()
#8 U:\www\test\system\modules\isotope\library\Isotope\Module\Module.php(86): Contao\Module->generate()
#9 U:\www\test\system\modules\isotope\library\Isotope\Module\ProductList.php(85): Isotope\Module\Module->generate()
#10 U:\www\test\system\modules\core\elements\ContentModule.php(56): Isotope\Module\ProductList->generate()
#11 U:\www\test\system\modules\core\library\Contao\Controller.php(469): Contao\ContentModule->generate()
#12 U:\www\test\system\modules\core\modules\ModuleArticle.php(187): Contao\Controller::getContentElement(Object(Contao\ContentModel), 'main')
#13 U:\www\test\system\modules\core\modules\Module.php(154): Contao\ModuleArticle->compile()
#14 U:\www\test\system\modules\core\modules\ModuleArticle.php(50): Contao\Module->generate()
#15 U:\www\test\system\modules\core\library\Contao\Controller.php(405): Contao\ModuleArticle->generate(false)
#16 U:\www\test\system\modules\core\library\Contao\Controller.php(269): Contao\Controller::getArticle(Object(Contao\ArticleModel), false, false, 'main')
#17 U:\www\test\system\modules\core\pages\PageRegular.php(129): Contao\Controller::getFrontendModule('0', 'main')
#18 U:\www\test\system\modules\core\controllers\FrontendIndex.php(250): Contao\PageRegular->generate(Object(Contao\PageModel), true)
#19 U:\www\test\index.php(20): Contao\FrontendIndex->run()
#20 {main}

**Comment by aschempp** [comment]
There is no such template, probably a misconfiguration of your frontend module
