### ISSUE TITLE
help wizzard bei Benachrichtigung -> Sprache 

### ISSUE THREAD

**Issue by kubjo** [isotope/core#1417]
Der help wizzard ist nicht sichbar bei benachrichtigung - neue Sprache ganz unten Attatchment!

**Comment by Toflar** [comment]
?

**Comment by kubjo** [comment]
Wie soll ich es sonst beschreiben?

**Comment by kubjo** [comment]
isotope 2.2 - Benachrichtigungen -> neue Benachrichtigungen -> Titel xxx Änderung Bestellstatus -> Speicher&Schließen -> xxx bearbeiten (gateway Email) -> Neue Nachricht -> Sprache verwalten-> Neue Sprache -> Deutsch-> deutsch bearbeiten-> "Attachments via tokens" (gaaaanz unten) -> ## eingeben und help wizzard suchen!

**Comment by thescrat** [comment]
@Toflar hier zum Nachlesen: https://community.contao.org/de/showthread.php?56709-isotope-2-2-Bitte-um-Hilfe-bei-Bug-Report&p=366327

Ich glaube es geht um die Bezeichnung "help wizard" welcher im Label steht. Es gibt aber kein Symbol (der eigentliche help wizard) sondern die Liste erscheint, sobald man "##" eingibt. Das steht im gleichen Dialog auch bei Empfänger. Vielleicht sollte man die Labelbezeichnung leicht abändern.

**Comment by aschempp** [comment]
Die Formulierung ist problematisch, das hatten wir schonmal festgestellt. @Toflar siehst du das auch so?

PS: Mit Isotope hat das "nichts zu tun", das ist das Notification Center (https://github.com/terminal42/contao-notification_center).

**Comment by kubjo** [comment]
Mit ist die Formulierung egal, natürlich wäre es schön, wenn sie konsistent wäre!
Hier zwei Screenshots:
![screenshot-1](https://cloud.githubusercontent.com/assets/715072/7177021/cd24de96-e423-11e4-8faf-c20eda9f45f2.jpg)
![screenshot-2](https://cloud.githubusercontent.com/assets/715072/7177022/cd3c844c-e423-11e4-88b4-def8251f60ae.jpg)
Man beachte jeweils den Scrollbalken! Es kommt erstmal viel whitespace, und wenn dann die tokens erscheinen werden diese abgeschnitten!

**Comment by Toflar** [comment]
Ich habe versucht das Problem mit Windows 7 und FF 37 nachzustellen. Kein Erfolg.

**Comment by aschempp** [comment]
Ich kann das Problem leider auch nicht reproduzieren… Du müsstest wohl einen Entwickler auf dein System ansetzen der uns mit einem Pull-Request weiterhelfen kann.
