### ISSUE TITLE
[3.4.5 - 2.2.3] Produkt mit Attributen

### ISSUE THREAD

**Issue by syncgw** [isotope/core#1420]
Hei,
ich habe ein Produkt, das 0,99 € pro STück kostet. Dazu gibt es 
- #1 Attribut (CheckBox) nicht ausgewählt +199,99 €
- #2 Attribut (Radio) mit Standard +11,99 €
- #3 Attribut (Checkbox-Multiselect) mit Standard +9,99 €
- #4 Attribut (CheckBox) nicht ausgewählt +14,99 €

Egal welche Anzahl (Quantity) ich eingebe - es kommt nur eine Gesamtsumme von 12,98 € im Cart an. Selbst wenn ich bei #3 eine zweite Checkbox anklicke +14,99 €, so erscheint der Text-Posten im Cart, aber die Summe bleibt 12,98 €.

Eigentlich hatte ich gehofft, die Rechnung wäre Anzahl x 0,99 € plus EINMALIGE Preiserhöhung pro gewähltem Attribut. Bin ich da Falsch mit meiner Denke??

**Comment by syncgw** [comment]
Über PN gebe ich auch gerne Amin-Zugriff auf Seite.

**Comment by aschempp** [comment]
Die Preiserhöhung sollte auf jeden Fall pro Stück berechnet werden. Es scheint aber für Checkboxen nicht zu funktionieren (gemäss deiner Beschreibung)…

**Comment by rpquadrat** [comment]
Der Checkbox-Bug ist auch in 2.3.0 RC1 noch vorhanden. Checkbox-Attribute werden nicht kalkuliert, sie werden zwar in den Warenkorb übernommen aber eben nicht kalkuliert. Wenn man das Attribut in ein Radio Element umwandelt, dann funktioniert es.

**Comment by aschempp** [comment]
Fixed in 53582607645fc360c18a7c209ebf7586d0a263b6

**Comment by rpquadrat** [comment]
Kann ich den Fix auch in 2.3.0 RC mergen?

**Comment by aschempp** [comment]
klar kannst du das, wenn du GIT kannst ^^
Ich werd das beim nächsten Release natürlich machen.

**Comment by rpquadrat** [comment]
Ich meinte eigentlich nur lokal bei mir :-)
Ich danke Dir für die Hilfe.
