### ISSUE TITLE
[2.2.3] Integritätscheck: Regelmodul aus > Erweiterungsverwaltung will Tabellen löschen

### ISSUE THREAD

**Issue by xantippe** [isotope/core#1421]
Hi,

der Integritätscheck meldete ich soll das Regelmodul ausschalten - ist z.Z auch nicht in Benutzung > daher gemacht...

beim Aktualisieren über die Erweiterungsverwaltung kommt nun die Meldung

```
ALTER TABLE `tl_iso_product_collection` DROP `coupons`;

DROP TABLE `tl_iso_rule`;
DROP TABLE `tl_iso_rule_restriction`;
DROP TABLE `tl_iso_rule_usage`;
```

Das macht zwar nix kaputt (wahrscheinlich) - ist aber m.E. dennoch "unschön"

**Comment by aschempp** [comment]
Das ist normal in Contao, wenn eine Erweiterung deaktiviert wird werden deren Tabellen gelöscht/zum löschen angeboten.

**Comment by xantippe** [comment]
hmm... unterbinden kann das nicht irgendwie?

ansonsten schreibe ich mal ein Ticket bei Contao - sollte doch machbar sein ähnlich wie die ".skip"-geschichte, das auch in den DCA(?) zu bringen

**Comment by aschempp** [comment]
Du hast das Modul deaktiviert, was genau gleich ist wie wenn du das Modul löschen würdest. Dann braucht es ja die Tabellen nicht mehr… Den Zusammenhang mit ".skip" versteh ich nicht, der Integrity-Check legt nämlich einfach eine .skip in den Ordner ;-)

**Comment by xantippe** [comment]
mit dem skip meine ich das im übertragenen Sinne, d.h. eine "Info" an Contao, dass die Tabellen/Spalten nur temporär nicht benötigt werden und die "Delete" Infos unterbleiben sollen...

es kann ja sein, ich habe Regeln definiert, die ich aktuell nicht brauche und das Modul deaktiviere - dann würden die Infos gekillt

ist soweit das Gleiche, dass ich ab und an per Contao Einstellungen eine Erweiterung raus nehme und eigentlich nicht möchte, dass gleich alle Tabellen gelöscht werden (bei Erweiterungsupdate)

**Comment by aschempp** [comment]
Es ist genau das gleich wie bei Contao, hat daher nichts mit Isotope zu tun.

**Comment by xantippe** [comment]
zu schnell auf Speichern geklickt... genau: ist ein Contao "Problem"

Dank!
