### ISSUE TITLE
[2.2.3] Payone Modul funktioniert nicht

### ISSUE THREAD

**Issue by giorgiojob** [isotope/core#1422]
Alle Daten von Payone: Sub-Account ID, Portal-ID, Sicherheitsschlüssel wurden korrekt eingeben. PayOne antwortet auch auf die Zahlung, allerdings immer nur mit einer einzeiligen Meldung.
Die Antworten sind immer Fehlermeldungen, die auf einem weißen Bildschirm erscheinen. Entweder stimmt der ammount nicht überein oder es wird die Währung nicht akzeptiert.
die Fehlermeldung lauten exakt:

Artikelgesamtwert stimmt nicht mit 'amount' überein.

Zahlart bei dieser Währung nicht verfügbar.

Die Fehlermeldung Währung kommt wenn man bei der Abwicklungsart Kreditkarte wählt. Die andere bei allen anderen Abwicklungsarten.
Bei einem Telefonat mit PayOne sagten mir diese, dass von uns gar keine Daten übergeben werden.
Wir haben einen normalen Account bei PayOne und die eingegeben Daten im Zahlungsmodul sind korrekt ansonsten würde ja auch gar nichts zurückkommen, oder?
Erstaunlich ist auch, dass in der Kasse bei der Zahlungsart Payone angezeigt wird und nicht die bei PayOne aktivierten Kreditkarten, jedenfalls kenne ich das so von Magento-Installationen in denen wir PayOne integriert haben.
Wozu dient eigentlich: Abwicklungsart? Muss man je nachdem was man bei Payone gebucht hat jedes mal eine weiteres Zahlungsmodul anlegen, dass dann einfach nur anders heißt. z.B. eines für Kreditkarten und eines für Rechnung (z.B. wenn man Sofortüberweisung mit bei Payone gebucht hat)?
Leider ist das Handbuch nicht aussagefähig und im Netz habe ich nur einen Post gefunden aus 2014 mit SSL Problemen.
Bei Payone haben wir in folgenden Feldern keine Einträge gemacht:
Erfolgs-URL: url zur Seite ...bestellung-abgeschlossen.html
TransactionsStatus URL: (keine Ahnung was da eingetragen werden soll)
Zurück-URL: URL zur Startseite da nur für Abbruch. Werden hier später noch eine spezielle Seite anlegen

Hilfe wäre nett, würde auch was zum Handbuch beitragen, damit die Lücke gefüllt wird.
Isotope 2.2.3 läuft bei uns in einer Contao 3.4.o Installation. Sonst ist alles OK und läuft einwandfrei im Test).

**Comment by aschempp** [comment]
Warum hast du das Ticket wieder geschlossen?

**Comment by giorgiojob** [comment]
Hallo,

habe es geschlossen, weil ich jetzt seit 2 Wochen daran herumbasteln und etwas weiter gekommen bin.
Der aktuelle Stand ist jetzt so: (auch gerade auf Github aktualisiert: https://github.com/isotope/core/issues/1442 <https://github.com/isotope/core/issues/1442>
und der unten folgenden Text wollte ich jetzt auch noch im Contao-Forum posten (too much? Was denkst Du lieber nur in Github?.

Wir haben folgende Konfiguration:
Contao 3.4.0
Isotope 2.2.3

keine exotischen Eigenentwicklungen drin und sonst nur Barzahlung/Überweisung als weitere Zahlungsmethode integriert.

Folgendes Problem tritt auf:

1. Payone läuft modulseitig im Testmodus
2. Bei bezahlen über PAyone wählen wir eine freigeschaltene Zahlungsmethode in diesem Fall PayPal oder Kreditkarte
3. Die Bestellung geht raus und das System versucht das OK von PAyone zu holen
4. nach 3-4 Versuchen taucht die Bestellung wieder auf dem Bildschirm auf mit der Meldung. "Zahlung konnte nicht ausgeführt werden bitte wählen Sie eine andere Zahlungsmethode."
5. Die Bestellung ist im Backend nicht sichtbar - logischerweise, weil diese ja augenscheinlich nicht durchführbar war mit der gewählten Zahlungsmethode
5. Nach ca. 1 Stunde (das ist die Zeit, die PAyone bei Misserfolg der Übertragung des Zahlungsstatus verstreichen lässt, bis die Daten zugestellt werden) kommt der Auftrag plötzlich als COMPLETE im System an. Egal ob PayPal oder Kreditkarte gewählt wurde.

Geht natürlich so nicht, da der Kunde ja erst die Meldung bekommt, dass seine Zahlung nicht durchführbar war und er anders bezahlen soll.

Nach Rücksprache mit Payone, die Live die Übermittlung der Bestelldaten mitverfolgt haben, geschieht folgendes:

1. Die Bestellung kommt bei PAyone an
2. Bei der Übermittlung der Zahlungserfolgsmeldung an den Shop wird PAyone gemeldet, dass der Shop angeblich keinen Zugriff zulässt.
3. Es kann auch sein, dass die SUCCESS Seite die bei Payone hinterlegt ist falsch ist. Wir haben eine "bestellung-erfolgreich.html" Seite angelegt und dort auch diese URL hinterlegt. Wenn über Vorkasse bezahlt wird also nicht Payone läuft alles komplett störungsfrei.

Interessanterweise lässt der Shop aber einen Zugriff, der vorher laut PAyone verweigert wurde, ca. eine Stunde später zu und die Zahlungsmeldung kann komplett übertragen werden.
Wir haben jetzt die Einstellungen der .htaccess des Isotope Shops in Verdacht gehabt und haben dort die IP´s von PAyone hinterlegen.
Die htaccess Datei von isotope sieht so aus:

<IfModule !mod_authz_core.c>
 # Apache 2.2
 <Files ~ "(postsale|group).php$">
   Order Allow,Deny
   Allow from all
 </Files>
</IfModule>
<IfModule mod_authz_core.c>
 # Apache 2.4
 <Files ~ "(postsale|group).php$">
   Require all granted
 </Files>
</IfModule>

Wir hatten jetzt an dieser Stelle folgendes eintragen:

<IfModule !mod_authz_core.c>
 # Apache 2.2
 <Files ~ "(postsale|group).php$">
    deny from all
    allow from 213.178.72.196 
    allow from 213.178.72.197 
    allow from 217.70.200
    allow from 185.60.20
 </Files>
</IfModule>
<IfModule mod_authz_core.c>
 # Apache 2.4
 <Files ~ "(postsale|group).php$">
    deny from all
    allow from 213.178.72.196 
    allow from 213.178.72.197 
    allow from 217.70.200
    allow from 185.60.20
 </Files>
</IfModule>


um Payone die Möglichkeit zu geben die Daten zu übertragen. Irgendwie aber unlogisch denn beim 2. Versuch die Daten zu übertragen klappt es ja. Jedenfalls ist die htaccess im Isotope Modul jetzt so hinterlegt bracht aber weder eine Verbesserung noch eine Verschlechterung.

Ist dieses Problem bekannt? Gibt es da eine entsprechende Lösung? Payone wird ja nicht so häufig eingesetzt jedenfalls nicht im ISOTOPE denke ich. Jedenfalls schweigt sich das Netzt da ein wenig aus.

Über Hilfe würde ich mich echt freuen, weil ich da schon seit ca. 2 Wochen immer wieder daran herumbastle.


Gruß

Giorgio

**Comment by giorgiojob** [comment]
Hallo,

habe gerade noch das PayPal Modul eingerichtet mit einem existenten Sandbox Konto und da habe ich den gleichen Effekt.

1. Es wird zu PAyPal weitergeleitet, die Daten werden korrekt übergeben
2. Nach Zahlung über PayPal wird korrekt zur Seite zurückgeleitet und dann sieht man auf der Shop Seite wie der Browser mehrmals versucht eine Seite aufzurufen und dann mit der bleichen Meldung abbricht, dass die Zahlung nicht durchgeführt werden konnte.
3. Im Backend ist kein Auftrag und bei den Sandboxkonten wurde der Kunde korrekt belastet allerdings kam auf dem Händlerkonto nichts an.

Kann es sein, dass ich bei der Konfiguration irgendwas versemmelt habe?

Wundere mich nur, falls das so ist, das alle Zahlungsmethoden mit den Cashmodul einwandfrei durchgehen, und auch alle Meldungen korrekt sind.
