### ISSUE TITLE
Reporting incorrectly calculating months

### ISSUE THREAD

**Issue by blairwinans** [isotope/core#1430]
While the reporting works well for other increments, months is the only place where things seem to have glitches. I tracked this down to the fact that we are using "+1 month" as the increment, which is happening here:

https://github.com/isotope/core/blob/master/system/modules/isotope_reports/library/Isotope/Report/SalesTotal.php#L207

If I set a date of Nov 30 through April 30, February goes missing (because it gets skipped over in the relative number of days used to calculate +1 month).

See here for what could be used as a solution:

http://stackoverflow.com/questions/5760262/php-adding-months-to-a-date-while-not-exceeding-the-last-day-of-the-month

Screenshot attached
![screen shot 2015-04-29 at 1 54 27 pm](https://cloud.githubusercontent.com/assets/1219241/7397569/4e0bec36-ee77-11e4-9914-e880847e6220.png)

Obviously, just resetting the date to the 1st of the month would be an obvious solution, too... However, it also throws the same types of errors on the weekly report if the days you select are not beginning of the week.

**Comment by aschempp** [comment]
This actually happened only if February did not contain any data.
