### ISSUE TITLE
FAQ Detail Seite  - Zielseite nicht gefunden

### ISSUE THREAD

**Issue by anjuis** [isotope/core#1432]
Nach dem Aktivieren der FAQ in der Demo funktioniert die FAQ-Detailseite nur bei deaktiviertem Isotope. Ist Isotope aktiviert, meldet der Browser Zielseite nicht gefunden. Contao 3.2.10 Isotope 2.1.12

**Comment by aschempp** [comment]
Welche Version von Isotope und Haste hast du installiert?

**Comment by anjuis** [comment]
Haste kenne ich nicht. Isotope wie oben beschrieben 2.1.12, upgedatet von der Version, die mit Contao 3.2.10 in der Demo enthalten ist, also 2.1.1.

**Comment by aschempp** [comment]
Das ist ein Fehler in Contao 3.2, wurde in Version 3.2.13 behoben (siehe https://github.com/contao/core/issues/7185)

**Comment by anjuis** [comment]
Ja gut, 10 Euro in die Updatekasse und das Problem war in 5 Minuten behoben.
