### ISSUE TITLE
[3.4.5 - 2.2.3] Dokument Template

### ISSUE THREAD

**Issue by syncgw** [isotope/core#1433]
Hei,
ich habe ein Dokument (Rechnung) definiert, dass im meinem Template-Verzeichnis ein neues Template nutzt. Sobald ich die Rechnung im BE aufrufe, wird das Template nicht gefunden:

Fatal error: Uncaught exception Exception with message Could not find template "iso_document_bill" thrown in U:\www\test\system\modules\core\library\Contao\TemplateLoader.php on line 123

#0 U:\www\test\system\modules\core\library\Contao\Controller.php(75): Contao\TemplateLoader::getPath('iso_document_bi...', 'html5')
#1 U:\www\test\system\modules\isotope\library\Isotope\Template.php(60): Contao\Controller::getTemplate('iso_document_bi...', 'html5')
#2 U:\www\test\system\modules\core\library\Contao\BaseTemplate.php(81): Isotope\Template::getTemplate('iso_document_bi...', 'html5')
#3 U:\www\test\system\modules\core\library\Contao\Template.php(238): Contao\BaseTemplate->parse()
#4 U:\www\test\system\modules\core\classes\FrontendTemplate.php(38): Contao\Template->parse()
#5 U:\www\test\system\modules\isotope\library\Isotope\Model\Document\Standard.php(152): Contao\FrontendTemplate->parse()
#6 U:\www\test\system\modules\isotope\library\Isotope\Model\Document\Standard.php(108): Isotope\Model\Document\Standard->generateTemplate(Object(Isotope\Model\ProductCollection\Order), Array)
#7 U:\www\test\system\modules\isotope\library\Isotope\Model\Document\Standard.php(29): Isotope\Model\Document\Standard->generatePDF(Object(Isotope\Model\ProductCollection\Order), Array)
#8 U:\www\test\system\modules\isotope\library\Isotope\Backend\ProductCollection\Callback.php(374): Isotope\Model\Document\Standard->outputToBrowser(Object(Isotope\Model\ProductCollection\Order))
#9 U:\www\test\system\modules\core\classes\Backend.php(413): Isotope\Backend\ProductCollection\Callback->printDocument(Object(Contao\DC_Table))
#10 U:\www\test\system\modules\core\controllers\BackendMain.php(126): Contao\Backend->getBackendModule('iso_orders')
#11 U:\www\test\contao\main.php(20): Contao\BackendMain->run()
#12 {main}

**Comment by aschempp** [comment]
Das Template darf nicht in einem Theme-Ordner liegen, oder dieser muss in der Shop-Config gewählt sein.

**Comment by syncgw** [comment]
Hä? Nirgendwo etwas von Theme erwähnt, nix im Theme-Ordner abgespeichert! Komischer Kommentar

**Comment by Toflar** [comment]
Der Kommentar ist nicht komisch. Dein Template darf nicht in einem Theme-Ordner liegen oder dieser muss in der Shop-Config ausgewählt sein, damit das Template gefunden werden kann. Lesen hilft.

**Comment by syncgw** [comment]
Danke für die Antwort - Liegt das Template doch gar nicht! Das Template liegt ganz normal im Benutzer-Ordner "templates\syncgw". Sonst könnte ich das Template doch gar nicht im Modul auswählen. Habe jetzt mal zur Klärung Bildchen angefügt. 
![p](https://cloud.githubusercontent.com/assets/2334583/7450198/69b93974-f242-11e4-8acb-1aa81d51b590.png)

**Comment by aschempp** [comment]
"syncgw" ist dein Theme-Ordner…

**Comment by syncgw** [comment]
Nope: 
![p](https://cloud.githubusercontent.com/assets/2334583/7450339/1cb9d794-f244-11e4-9702-d4d0c96899f7.png)

**Comment by aschempp** [comment]
Steht aber so in deinem Screenshot…

**Comment by Toflar** [comment]
Du musst den Ordner in der **SHOP-KONFIGURATION** auswählen.
