### ISSUE TITLE
[2.3.0-beta1] Datenbank aktualisieren Exception

### ISSUE THREAD

**Issue by Mynyx** [isotope/core#1436]
Fatal error: Uncaught exception Exception with message Query error: Duplicate entry '' for key 'uniqid' (ALTER TABLE `tl_iso_product_collection` ADD UNIQUE KEY `uniqid` (`uniqid`);) thrown in system/modules/core/library/Contao/Database/Statement.php on line 295
#0 system/modules/core/library/Contao/Database.php(207): Contao\Database\Statement->query('ALTER TABLE `tl...')
#1 system/modules/repository/classes/RepositoryManager.php(477): Contao\Database->query('ALTER TABLE `tl...')
#2 system/modules/repository/classes/RepositoryBackendModule.php(153): RepositoryManager->update('database')
#3 system/modules/core/classes/BackendModule.php(98): RepositoryBackendModule->compile()
#4 system/modules/repository/classes/RepositoryBackendModule.php(72): Contao\BackendModule->generate()
#5 system/modules/repository/classes/RepositoryManager.php(57): RepositoryBackendModule->generate()
#6 system/modules/core/classes/Backend.php(423): RepositoryManager->generate()
#7 system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('repository_mana...')
#8 contao/main.php(20): Contao\BackendMain->run()
#9 {main}

**Comment by zonky2** [comment]
I had the same error during the update by 2.2.4 to 2.3.5

```
Fatal error: Uncaught exception Exception with message Query error: Duplicate entry '' for key 'uniqid' (ALTER TABLE `tl_iso_product_collection` ADD UNIQUE KEY `uniqid` (`uniqid`);) thrown in system/modules/core/library/Contao/Database/Statement.php on line 295

#0 system/modules/core/library/Contao/Database.php(207): Contao\Database\Statement->query('ALTER TABLE `tl...')
#1 system/modules/repository/classes/RepositoryManager.php(477): Contao\Database->query('ALTER TABLE `tl...')
#2 system/modules/repository/classes/RepositoryBackendModule.php(153): RepositoryManager->update('database')
#3 system/modules/core/classes/BackendModule.php(98): RepositoryBackendModule->compile()
#4 system/modules/repository/classes/RepositoryBackendModule.php(72): Contao\BackendModule->generate()
#5 system/modules/repository/classes/RepositoryManager.php(57): RepositoryBackendModule->generate()
#6 system/modules/core/classes/Backend.php(423): RepositoryManager->generate()
#7 system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('repository_mana...')
#8 contao/main.php(20): Contao\BackendMain->run()
#9 {main}
```

may be, you should update the db migration with
```ALTER TABLE `tl_iso_product_collection` CHANGE `uniqid` `uniqid` VARCHAR(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL;```
