### ISSUE TITLE
[2.3.0-beta1] Inline Gallery Exception

### ISSUE THREAD

**Issue by Mynyx** [isotope/core#1438]
Recoverable error: Argument 3 passed to Isotope\Model\Gallery\Inline::addImageToTemplate() must be of the type array, string given, called in /www/htdocs/w013345d/contao/system/modules/isotope/library/Isotope/Model/Gallery/Standard.php on line 167 and defined in system/modules/isotope/library/Isotope/Model/Gallery/Inline.php on line 62
#0 system/modules/isotope/library/Isotope/Model/Gallery/Inline.php(62): __error(4096, 'Argument 3 pass...', '/www/htdocs/w01...', 62, Array)
#1 system/modules/isotope/library/Isotope/Model/Gallery/Standard.php(167): Isotope\Model\Gallery\Inline->addImageToTemplate(Object(Isotope\Template), Array, 'main', true)
#2 templates/iso_collection_default.html5(45): Isotope\Model\Gallery\Standard->generateMainImage()
#3 system/modules/core/library/Contao/BaseTemplate.php(88): include('/www/htdocs/w01...')
#4 system/modules/core/library/Contao/Template.php(250): Contao\BaseTemplate->parse()
#5 system/modules/core/classes/FrontendTemplate.php(46): Contao\Template->parse()
#6 system/modules/isotope/library/Isotope/Module/Cart.php(160): Contao\FrontendTemplate->parse()
#7 system/modules/core/modules/Module.php(282): Isotope\Module\Cart->compile()
#8 system/modules/isotope/library/Isotope/Module/Module.php(92): Contao\Module->generate()
#9 system/modules/isotope/library/Isotope/Module/Cart.php(70): Isotope\Module\Module->generate()
#10 system/modules/core/elements/ContentModule.php(59): Isotope\Module\Cart->generate()
#11 system/modules/core/library/Contao/Controller.php(476): Contao\ContentModule->generate()
#12 system/modules/core/modules/ModuleArticle.php(213): Contao\Controller::getContentElement(Object(Contao\ContentModel), 'main')
#13 system/modules/core/modules/Module.php(282): Contao\ModuleArticle->compile()
#14 system/modules/core/modules/ModuleArticle.php(67): Contao\Module->generate()
#15 system/modules/core/library/Contao/Controller.php(409): Contao\ModuleArticle->generate(false)
#16 system/modules/core/library/Contao/Controller.php(269): Contao\Controller::getArticle(Object(Contao\ArticleModel), false, false, 'main')
#17 system/modules/core/pages/PageRegular.php(133): Contao\Controller::getFrontendModule('0', 'main')
#18 system/modules/core/controllers/FrontendIndex.php(267): Contao\PageRegular->generate(Object(Contao\PageModel), true)
#19 index.php(20): Contao\FrontendIndex->run()
#20 {main}

**Comment by aschempp** [comment]
Das Problem wurde im Develop bereits behoben.
