### ISSUE TITLE
[ 2.2.4.9003 ] - Productlister and Attributes Issue

### ISSUE THREAD

**Issue by magic-77** [isotope/core#1439]
Hey Guys,
using Products with Attributes causes this error,
[ Contao 3.4.5, Isotope 2.2.4.9003 ]
Modul used: Produktvarianten-Liste

	Fatal error: Uncaught exception Exception with message Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB 
	server version for the right syntax to use near ')) OR tl_iso_product.pid IN (109,100) ) GROUP BY tl_iso_prod' at line 2 (SELECT tl_iso_product.*, IF(
	tl_iso_product.pid>0, parent.type, tl_iso_product.type) AS type, 'de' AS language, IFNULL(translation.name, tl_iso_product.name) AS name, IFNULL(translation.
	teaser, tl_iso_product.teaser) AS teaser, IFNULL(translation.description, tl_iso_product.description) AS description, IFNULL(translation.meta_title, 
	tl_iso_product.meta_title) AS meta_title, IFNULL(translation.meta_description, tl_iso_product.meta_description) AS meta_description, IFNULL(translation.
	meta_keywords, tl_iso_product.meta_keywords) AS meta_keywords, IFNULL(translation.images, tl_iso_product.images) AS images, tl_iso_product.images AS 
	images_fallback, c.sorting, t.id AS type__id, t.tstamp AS type__tstamp, t.name AS type__name, t.class AS type__class, t.fallback AS type__fallback, t.
	description AS type__description, t.prices AS type__prices, t.show_price_tiers AS type__show_price_tiers, t.list_template AS type__list_template, t.
	reader_template AS type__reader_template, t.list_gallery AS type__list_gallery, t.reader_gallery AS type__reader_gallery, t.attributes AS type__attributes, t.
	variants AS type__variants, t.variant_attributes AS type__variant_attributes, t.force_variant_options AS type__force_variant_options, t.shipping_exempt AS 
	type__shipping_exempt, t.downloads AS type__downloads FROM tl_iso_product LEFT OUTER JOIN tl_iso_product_category c ON tl_iso_product.id=c.pid LEFT OUTER JOIN 
	tl_iso_product translation ON tl_iso_product.id=translation.pid AND translation.language='de' LEFT OUTER JOIN tl_iso_product parent ON tl_iso_product.pid=parent
	.id LEFT JOIN tl_iso_producttype t ON tl_iso_product.type=t.id WHERE tl_iso_product.language='' AND tl_iso_product.published='1' AND (tl_iso_product.start='' 
	OR tl_iso_product.start<1431624434) AND (tl_iso_product.stop='' OR tl_iso_product.stop>1431624434) AND ( (tl_iso_product.id IN (109,100) AND tl_iso_product.
	type NOT IN ()) OR tl_iso_product.pid IN (109,100) ) GROUP BY tl_iso_product.id ORDER BY c.sorting) thrown in system/modules/core/library/Contao/Database/
	Statement.php on line 293

	#0 system/modules/core/library/Contao/Database/Statement.php(262): Contao\Database\Statement->query()
	#1 system/modules/isotope/library/Isotope/Model/TypeAgent.php(219): Contao\Database\Statement->execute(Array)
	#2 system/modules/isotope/library/Isotope/Model/Product.php(325): Isotope\Model\TypeAgent::find(Array)
	#3 system/modules/core/library/Contao/Model.php(840): Isotope\Model\Product::find(Array)
	#4 system/modules/isotope/library/Isotope/Model/Product.php(117): Contao\Model::findBy(Array, Array, Array)
	#5 system/modules/isotope/library/Isotope/Model/Product.php(270): Isotope\Model\Product::findPublishedBy(Array, Array, Array)
	#6 system/modules/isotope/library/Isotope/Module/ProductVariantList.php(110): Isotope\Model\Product::findAvailableBy(Array, Array, Array)
	#7 system/modules/isotope/library/Isotope/Module/ProductList.php(155): Isotope\Module\ProductVariantList->findProducts(NULL)
	#8 system/modules/core/modules/Module.php(154): Isotope\Module\ProductList->compile()
	#9 system/modules/isotope/library/Isotope/Module/Module.php(86): Contao\Module->generate()
	#10 system/modules/isotope/library/Isotope/Module/ProductList.php(85): Isotope\Module\Module->generate()
	#11 system/modules/isotope/library/Isotope/Module/ProductVariantList.php(51): Isotope\Module\ProductList->generate()
	#12 system/modules/core/elements/ContentModule.php(56): Isotope\Module\ProductVariantList->generate()
	#13 system/modules/core/library/Contao/Controller.php(469): Contao\ContentModule->generate()
	#14 system/modules/core/modules/ModuleArticle.php(187): Contao\Controller::getContentElement(Object(Contao\ContentModel), 'main')
	#15 system/modules/core/modules/Module.php(154): Contao\ModuleArticle->compile()
	#16 system/modules/core/modules/ModuleArticle.php(50): Contao\Module->generate()
	#17 system/modules/core/library/Contao/Controller.php(405): Contao\ModuleArticle->generate(false)
	#18 system/modules/core/library/Contao/Controller.php(269): Contao\Controller::getArticle(Object(Contao\ArticleModel), false, false, 'main')
	#19 system/modules/core/pages/PageRegular.php(129): Contao\Controller::getFrontendModule('0', 'main')
	#20 system/modules/core/controllers/FrontendIndex.php(250): Contao\PageRegular->generate(Object(Contao\PageModel), true)
	#21 index.php(20): Contao\FrontendIndex->run()
	#22 {main}

**Comment by magic-77** [comment]
Strange:
Deinstalled Isotope, and installed Version 2.2.3.9004
although this Step installs Version 2.2.4.9004, it solves my Problem...:-)

**Comment by aschempp** [comment]
I guess this issue can be closed then?
