### ISSUE TITLE
[2.2.4.9003] - No Products in List using Attributes

### ISSUE THREAD

**Issue by magic-77** [isotope/core#1440]
Hey Guys,
using the Modul "Productlist" with Products using Attributes give me just an notice
"Zurzeit sind in dieser Kategorie keine Produkte vorhanden."

After removing Attributes, deleting the Module, reinstall Modul, Products appear again in Lister

**Comment by magic-77** [comment]
Strange:
Deinstalled Isotope, and installed Version 2.2.3.9004
although this Step installs Version 2.2.4.9004, it solves my Problem...:-)

**Comment by aschempp** [comment]
I guess this issue can be closed then?
