### ISSUE TITLE
[2.2.3] It is possible to checkout/place an order multiple times

### ISSUE THREAD

**Issue by bulbul0** [isotope/core#1441]
User completes check out phase: /kasa/complete.html?uid=123456789abcd.12345678 and successfully places an order. Then the order gets fullfilled and the status changes accordingly.
In some time (digging in his browser history) the user checks out again with the same uid:  /kasa/complete.html?uid=123456789abcd.12345678. And he successfully places the same order again. All the notifications get fired, the order status cahnges.
I think it'is due to a dummy implementation of Order::isCheckoutComplete().
Contao version: 3.4.5

**Comment by aschempp** [comment]
Fixed in #5b363b6

**Comment by Zeromax** [comment]
@aschempp is it really usefull to show a 404?
Why not redirect to the `orderCompleteJumpTo` page? If this does not exist use the 404.

IMHO that would be the better solution.

**Comment by aschempp** [comment]
You're right, that would work too.

**Comment by aschempp** [comment]
Changed in 9476a5063ac73dce59688edce7f1c343c401993a

**Comment by mbrode** [comment]
If we place an order with saferpay we get a correct redirect back to contao and would be redirected to startpage cause the $objOrder->checkout_complete returns true. (Checkout.php, line 135)
Isotope set the checkout_complete status in Order.php (line 173). 
But so the customer don't see that the order was successfuly.

**Comment by aschempp** [comment]
Looks like you did not set a checkout confirmation page in the checkout module.

**Comment by mbrode** [comment]
No, sorry. I set them correctly.

**Comment by mbrode** [comment]
We check at line 135 of /isotope/library/Isotope/Module/Checkout.php if the payment came from saferpay, like: 

    if ($objOrder->checkout_complete && $objOrder->payment_id !== '7') {

But we should find a better solution. Maybe to change to the saferpay payment if the client use it. But we get no information like this at object $objOrder.
