### ISSUE TITLE
Isotope PayOne Modul Störung - Zahlungsdaten kommen erst nach 1 Stunde an

### ISSUE THREAD

**Issue by giorgiojob** [isotope/core#1442]
Wir haben folgende Konfiguration:
Contao 3.4.0
Isotope 2.2.3

keine exotischen Eigenentwicklungen drin und sonst nur Barzahlung/Überweisung als weitere Zahlungsmethode integriert.

Folgendes Problem tritt auf:

1. Payone läuft modulseitig im Testmodus
2. Bei bezahlen über PAyone wählen wir eine frei geschaltene Zahlungsmethode also PayPal oder Kreditkarte
3. Die Bestellung geht raus und das System versucht das OK von PAyone zu holen
4. nach 3-4 Versuchen taucht die Bestellung wieder auf dem Bildschirm auf mit der Meldung. Zahlung konnte nicht ausgeführt werden bitte wählen Sie…
5. Die Bestellung ist im Backend nicht sichtbar - logischerweise, weil diese ja augenscheinlich nicht durchführbar war mit der gewählten Zahlungsmethode
5. Nach ca. 1 Stunde (das ist die Zeit, die PAyone bei Misserfolg der Übertragung des Zahlungsstatus verstreichen lässt) kommt der Auftrag plötzlich als COMPLETE im System an. Egal ob PayPal oder Kreditkarte gewählt wurde.

Nach Rücksprache mit Payone, die Live die Übermittlung der Bestelldaten mitverfolgt haben, geschieht folgendes:

1. Die Bestellung kommt bei PAyone an
2. Bei der Übermittlung der Zahlungserfolgsmeldung an den Shop wird PAyone gemeldet, dass der Shop angeblich keinen Zugriff zulässt.
3. Es kann auch sein, daß die SUCCESS Seit die bei Payone hinterlegt ist falsch ist. Wir haben eine "bestellung-erfolgreich.html" Seite angelegt und dort auch diese URL hinterlegt. Wenn über Vorkaue bezahlt wird also nicht Payone läuft alles komplett störungsfrei.

Interessanterweise lässt der Shop aber einen Zugriff ca. eine Stunde später zu und die Zahlungsmeldung kann übertragen werden.
Wir haben jetzt die Einstellungen der .htaccess des Isotope Shops in Verdacht und wollten dort die IP´s von PAyone hinterlegen.
Die aktuelle htaccess Datei von isotope sieht so aus:

<IfModule !mod_authz_core.c>
 # Apache 2.2
 <Files ~ "(postsale|group).php$">
   Order Allow,Deny
   Allow from all
 </Files>
</IfModule>
<IfModule mod_authz_core.c>
 # Apache 2.4
 <Files ~ "(postsale|group).php$">
   Require all granted
 </Files>
</IfModule>

Wir hatten jetzt an dieser Stelle folgendes eintragen:

<IfModule !mod_authz_core.c>
 # Apache 2.2
 <Files ~ "(postsale|group).php$">
    deny from all
    allow from 213.178.72.196 
    allow from 213.178.72.197 
    allow from 217.70.200
    allow from 185.60.20
 </Files>
</IfModule>
<IfModule mod_authz_core.c>
 # Apache 2.4
 <Files ~ "(postsale|group).php$">
    deny from all
    allow from 213.178.72.196 
    allow from 213.178.72.197 
    allow from 217.70.200
    allow from 185.60.20
 </Files>
</IfModule>

um Payone die Möglichkeit zu geben die Daten zu übertragen. Irgendwie aber unlogisch denn beim 2. Versuch die Daten zu übertragen klappt es ja. Jedenfalls ist die htaccess im Isotope Modul jetzt so hinterlegt bracht aber weder eine Verbesserung noch eine Verschlechterung.

Ist diese Problem bekannt? Gibt es da eine entsprechende Lösung? Payone wird ja nicht so häufig eingesetzt jedenfalls nicht im ISOTOPE denke ich. Jedenfalls schweigt sich das Netzt da ein wenig aus.

Über etwas Hilfe würden wir uns echt freuen.

**Comment by giorgiojob** [comment]
Ich habe jetzt mal das PayPal Zahlungsmodul getestet.
Hier habe ich den gleichen Effekt. Die Zahlung wird zwar abgewickelt kommt aber gar nicht im Shop an.
Man kann im B Rowes sehen, daß das System mehrmals versucht eine Zahlungsbestätigung zu bekommen und dann mit einer Fehlermeldung abbricht.
Ich hab den Sandbox Modus verwendet von Paypla und da wird der Betrag beim Käufer abgezogen, kommt aber beim Händler nicht an, wird also nicht gutgeschrieben.
Kann es sein, da irgendwas in der Konfiguration nicht passt?
Wie gesagt Überweisung, Nachnahme als alles was mit dem Cash-Modul einzustellen ist läuft nur Payone und PayPal wollen einfach keine Daten übertragen bzw. können keine empfangen.

Was muss getan werden? Kann jemand helfen?

**Comment by aschempp** [comment]
Es scheint klar an deiner Installation zu liegen. Dieser Bereich hier ist für Fehlermeldungen zu Isotope. Bitte wende dich an das Community Forum (https://community.contao.org/de/forumdisplay.php?111-isotope), dort wurden solche Themen auch schon mehrfach behandelt.
