### ISSUE TITLE
Staffelpreise funktionieren nicht

### ISSUE THREAD

**Issue by lrschulte** [isotope/core#1443]
Hallo,

ich probiere seit 2 Tagen, Staffelpreise einzustellen. Habe dafür die Erweiterten Preise aktiviert und eine Preisstaffel im Produkt angelegt. Ebenso habe ich im Template folgende Zeile eingefügt:
```
<?php  
    if ($this->product->getPrice()->hasTiers()) { 
        echo $this->generateAttribute('price_tiers'); 
    } else { 
        echo $this->generatePrice(); 
    }
?> 
```

Die Preisstaffeln funktionieren jedoch nicht, es wird weiterhin der normale Preis angezeigt und im Warenkorb auch kein Rabatt übernommen.

Contao Version ist 3.4.5 und isotope 2.3.0

Viele Grüße
Lukas

**Comment by aschempp** [comment]
Die Staffelpreise funktionieren bei mir problemlos, das muss ein Konfigurationsfehler in deinem System sein.
