### ISSUE TITLE
iso_list Template print out the categories of the product

### ISSUE THREAD

**Issue by artiwebdesign** [isotope/core#1444]
Is it possible to print out the names of categories of a product in the List-Template or Reader-Template? I think it's very important for the Listing of new products and best sellers...
<code><?php foreach ($this->categories as $arrCategory): echo $arrOption['title']; endforeach; ?></code>

**Comment by aschempp** [comment]
The category names are not fetched, but the IDs should be available to the template. Probably best would be to use the existing hooks to add the information to the template on-the-fly.

**Comment by artiwebdesign** [comment]
Danke für die rasche Antwort! Ich hatte nicht gesehen das die anderen Beiträge auf deutsch sind, das macht es dann doch etwas einfacher :) Die ID`s sind irgendwie schon im Template vorhanden, nur bekomme ich die leider nicht ausgegeben. Über <code>print_r($this->catgeories)</code> funktioniert das leider nicht. Ich habe mal ein Bild von der Ausgabe der gesamten Template Daten ($this) angehangen. Geht das anders als bei den Options? 
![image](https://cloud.githubusercontent.com/assets/8812297/7916578/0f7c3a66-0885-11e5-925f-4e39ed7f0ae3.png)

**Comment by aschempp** [comment]
Ja die Options funktionieren komplett anders. Das lässt sich aber nicht so einfach in einem Ticket erklären.
Wende dich bitte an's Community Forum, dort gibt es einen extra Bereich für Fragen zu Isotope.

**Comment by artiwebdesign** [comment]
Danke, klar werde ich machen...
