### ISSUE TITLE
[2.2.4] cartMerged wird "zu oft" angezeigt

### ISSUE THREAD

**Issue by xantippe** [isotope/core#1445]
Das Popup mit ```Die unbestellten Produkte Ihres letzten Besuchs wurden wieder übernommen. Bitte prüfen Sie den Warenkorb-Inhalt.``` kommt bei *jeder* Seite des Check-out - selbst auf der Bestätigungsseite. 1x sollte reichen...

**Comment by aschempp** [comment]
Hast du deinen Shop so konfiguriert dass nach der Anmeldung direkt auf die Kasse gesprungen wird?

**Comment by xantippe** [comment]
ich habe eine "Vor-Seite" mit Auswahl "Gast/Kunde" inkl. Inhaltselement "Login-Weiterleitung" auf die eigentliche Kassenseite

https://www.robert-metcalf.de/liederladen/zur-kasse.html

**Comment by aschempp** [comment]
Ich kann das leider nicht reproduzieren. Bitte einen Entwickler auf dein System ansetzen der analysieren kann wo das Problem liegt. Ich schliesse das Ticket vorübergehend, aber gerne wieder öffnen sobald mehr Informationen vorhanden sind.
