### ISSUE TITLE
[2.2.4] addMetaTags und addCanonicalProductUrls vor generate setzen

### ISSUE THREAD

**Issue by xantippe** [isotope/core#1446]
Hallo Toflar,

wie im Post im Forum von Dir vorgeschlagen:

```
$this->addMetaTags($objProduct);
$this->addCanonicalProductUrls($objProduct);  
```
vor
```
$objProduct->generate($arrConfig);  
```
siehe https://community.contao.org/de/showthread.php?19970-SEO-Attribut-in-Title-Tag&p=371783&viewfull=1#post371783

**Comment by aschempp** [comment]
@Toflar please explain this to me

**Comment by aschempp** [comment]
Changed in 9382a69dcd1651ca6d5a540ca63073adb5c59ca8

**Comment by xantippe** [comment]
Änderung getestet - funktioniert super!
