### ISSUE TITLE
Order History does not show any orders for more than one store config

### ISSUE THREAD

**Issue by yrrad** [isotope/core#1449]
How to reproduce:
1. Setup at least 2 store configs with different currencies (i.e. EUR, USD)
2. Setup Order History module with both store configurations choosen in such order 1. EUR 2. USD
3. Place an order in USD.
4. No orders are displayed
5. Place order in EUR
6. Orders are displayed
7. Repeat process changing order of store configs in step 2 (i.e. 1. USD 2. EUR)

Conclusions:

Order History module supports only ONE store config. So it should be disallowed to chose more than one config or module sholud be amended to work flawlessly with many configs on the fly.

Tested on Contao 3.4.5, Isotope 2.2.4 & 2.3.0 beta 1, my SQL 5.5.35 UTF-8, PHP 5.4.21

**Comment by aschempp** [comment]
Fixed in efa5e4b29722851282dab2210ec819a2c91c99c2
