### ISSUE TITLE
FR: Nicht auswählbare Attribute im Frontend anzeigen.

### ISSUE THREAD

**Issue by Wagnerwagner** [isotope/core#1450]
Kleiner Verbesserungsvorschlag für das Attributsystem in Isotope. Zusätzlich zu den Optionen 'variant_option' und 'customer_defined' eine weitere Option 'option_attribute' im Attributmanager einführen. 
Durch Auswahl dieser Option wird es dem Administrator ermöglicht Eigenschaften für Produkte zu definieren die im Frontend lediglich ausgegeben werden (z.B. Checkbox-Menü und Select-Menü als einfache HTML-Liste, TEXTAREA und Textfeld mit ihrem Inhalt.). Gleichzeitig können damit Produkte durch entsprechende Einstellung nach diesen Attributen gefiltert und durchsucht werden, wie dies auch mit den normalen Optionen bisher möglich ist.

**Comment by aschempp** [comment]
Das ist doch bereits möglich? In dem du einfach eben nichts anklickst (und ggf. das Template anpasst)?

**Comment by Wagnerwagner** [comment]
Ich hab es probiert. (Bsp. Checkbox)
Attribut angelegt, mit Optionsmanager Optionswerte hinzugefügt, das Attribute dem Produkttyp hinzugefügt. und im Produkt die entsprechenden gewünschten Optionswerte ausgewählt. 
Anzeige Frontend => keine Ausgabe des entsprechenden Attributes.
Eine Ausgabe der im Produkt ausgewählten Optionen über 
 ```php
<?php echo $this->generateAttribute('InternerName'); ?>
```
im entsprechenden Template gibt lediglich eine Komma getrennte Liste der ausgewählten Optionsid's aus, nicht aber die gespeicherten und übersetzten Labels.

**Comment by aschempp** [comment]
die Ausgabe müsste manuell im Template gemacht werden, da Isotope nicht wissen kann wie es dargestellt werden soll.

**Comment by Wagnerwagner** [comment]
Ja aber wie, zumindest habe ich keine Variable oder Objekt gefunden welches die Labels der Produktoptionen enthält (kann es natürlich auch übersehen haben). Das Handbuch ist an dieser stelle leider nicht sehr hilfreich.

**Comment by aschempp** [comment]
Ja die Möglichkeiten per Template-Anpassung sind unendlich und nicht unbedingt einfach. Die Labels sind potentiell nicht direkt im Template, müssten also ggf. per PHP aus der Datenbank oder den Attribut-Objekten geholt werden. GitHub ist aber das falsche System für Hilfe, bitte wende dich dazu an's Community Forum.

**Comment by Wagnerwagner** [comment]
Erst mal danke für die Antwort. Das mit den Template-Anpassungen habe ich mir schon fast gedacht und Programmiertechnisch ist das wohl auch kein Problem. In GitHub habe ich das gestellt weil ich denke, dass es ein praktisches Feature währe, wenn der normale Admin (Redakteur) die Möglichkeit hat Attribute die über das Backend gepflegt werden im Frontend einfach als Inhalt auszugeben. Damit würde das Attribut System dann auch wirklich als Attribut funktionieren. Derzeit handelt es sich ja eher um ein System für Produktoptionen. Mein Vorschlag war als Verbesserung für das derzeitige Attribut (Option)-System gedacht. 

Was die Frage nach der Darstellung angeht so sehe ich die als recht einfach an. 
Attribute und deren Werte die im Backend als Text eingegeben werden können werden im Frontend auch als solcher ausgegeben. Attribute die auf einer Select, Radio oder Checkbox basieren werden als einfache UL>LI listen ausgeben. Die Darstellung dieser Daten kann dann vom Designer bzw. Entwickler per CSS angepasst werden (evtl. kann für diese Attribute auch ein Template für die reine Anzeige angelegt und angepasst werden).

**Comment by aschempp** [comment]
Wurde in 2.3 geändert (`generateAttribute` gibt jetzt die Labels zurück).
