### ISSUE TITLE
Main product not showing if there is no variants

### ISSUE THREAD

**Issue by tsarma** [isotope/core#1451]
I have enabled a variant for a product type. 
Added a product in product manager. If I didn't add any variants to this product, then this product don't get listed in product list.

IMHO even when there is no variants of a product is defined, the main product should show up in the list module (select from all catagories). Or am I not seeing something else.

Contao 3.4.5
Isotope 2.2.4 / 4

**Comment by tsarma** [comment]
I am closing this, with a fact that, In isotope, if you enabled a variant then there must be a variants of the product.

**Comment by akroii** [comment]
Can you explain whats going wrong? What do you mean with "variants of the products"?

**Comment by aschempp** [comment]
> In isotope, if you enabled a variant then there must be a variants of the product.

Absolutely true :-)

**Comment by tsarma** [comment]
@akroii : Actually my concept was wrong earlier. What i meant by "variants of the products" is,
For example, say you have defined a product of type T-Shirts and with size variation of S,M,L (attribute variants). Now when you add a product (T-Shirts) in BE product manager. Then you have to have "variants of the products", i.e T-Shirt of at least one variation S,M or L to show up in the product listing.

Other observations I have made, If variant is enabled to a product type then
- There must be at least one variant of that product! (otherwise, it will not show up in list)
- The main item shown is the variant with min. amount (only by price. No other attributes like color, size,)
- Only first variant item of same variant is shown (not all items with same variant attribute type is shown. i,e if have three T-Shirts with S, only first S will show)

I hope this helps

**Comment by akroii** [comment]
@tsarma but what happens if the product is shown in the lister and also in reader, but when you change product attribute (via select menu) in FE, the product details disappears.

**Comment by tsarma** [comment]
Sorry I didn't get myself into your situation do far, so I can't comment on why it disappears. May be someone else can help you. 

But in any case "the product details disappears" do not says much. Is there any message or just blank?  Are all attribute combinations (when you changed via select menu) valid enough to show any products? May be there is a similar set up in demo Isotope?

**Comment by akroii** [comment]
There is no message at all. local it works fine... but not on the server .
![bug](https://cloud.githubusercontent.com/assets/8830861/8164378/004487ba-1389-11e5-84f4-a8b77ccf8030.gif)
