### ISSUE TITLE
[2.3.0-beta1] "Warning: md5_file (... ) failed to open stream: No such file or directory" bei Verwendung "Mehrere Bearbeiten" in den Produkten

### ISSUE THREAD

**Issue by 47gn** [isotope/core#1453]
Hallo zusammen,

bei folgender Arbeitsweise im Backend taucht diese Warnung auf:

<code>Warning: md5_file(/kunden/x/kundenseiten/x/assets/images/p/produktbild_liste.jpg): failed to open stream: No such file or directory in composer/vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/Widget/MediaManager.php on line 207
#0 [internal function]: __error(2, 'md5_file(/kunde...', '/kunden/..', 207, Array)
#1 composer/vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/Widget/MediaManager.php(207): md5_file('/kunden/x.d...')
#2 system/modules/core/classes/DataContainer.php(320): Isotope\Widget\MediaManager->validate()
#3 composer/vendor/isotope/isotope-core/system/modules/isotope/drivers/DC_ProductData.php(957): Contao\DataContainer->row()
#4 system/modules/core/classes/Backend.php(639): DC_ProductData->editAll()
#5 system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('iso_products')
#6 contao/main.php(20): Contao\BackendMain->run()
#7 {main}
</code>

1.) Produkte aufrufen
2.) Klick "mehrere Bearbeiten"
3.) Auswahl "Bilder"
4.) Klick "weiter"
5.) Auswählen von jeweils einem Bild mit dem immer gleichen Dateinamen für die gelisteten (Produkt)Datensätze.
6.) Klick "Speichern".

Dann tritt eben der o.g. Fehler auf. Wenn ich im Modus "mehrere Bearbeiten" nur für einen Datensatz in der Liste ein Bild auswähle und speichere, dann erscheint keine Fehlermeldung.

**Comment by aschempp** [comment]
Welche Version von Isotope verwendest du? Und hast du ggf. etwas an den Dateien modifiziert? Weil der entsprechende Pfad kann gar nicht zustanden kommen…

**Comment by 47gn** [comment]
Ich hab gerade in der Überschrift die Version noch ergänzt, hatte ich vorhin vergessen. Es ist die 2.3.0 Beta 1. Modifiziert ist nur, dass was Du wegen den neuen Funktionen für den eingeschränkten Filter angepasst hast. Ansonsten habe ich eigentlich an Isotope (noch) nichts angepasst.
