### ISSUE TITLE
[2.2.4 3] (kleiner) Bug bei Anzeige Statistik

### ISSUE THREAD

**Issue by xantippe** [isotope/core#1454]
bei der Statistikanzeige Gesamt fehlt in der Spalte Zeitraum die aktuelle KW-Angabe wenn
* Auswahl Woche
* Enddatum kleiner aktuelles Datum

somit rutschen alle Spalten eins nach links...
![zwischenablage12](https://cloud.githubusercontent.com/assets/1045318/8137610/c98260d0-1144-11e5-9b6c-68395ddb7084.jpg)

Siehe Screenshot (erstellt am 12.11.2015)

**Comment by xantippe** [comment]
verstehe die Angabe "Milestone 2.1.4" nicht bin doch schon bei 2.2.4... ??

**Comment by aschempp** [comment]
Du schon, aber der Fehler nicht ;-)

**Comment by xantippe** [comment]
o.k.!

**Comment by aschempp** [comment]
Vorerst behoben in a86ebc6658ea1bf7d4d8c8c5195269e678286742, wobei die Lösung unschön ist und mal neu gebaut werden muss…
