### ISSUE TITLE
translation won't work with country code ISO 639-1 en-GB or en-US

### ISSUE THREAD

**Issue by eBlick** [isotope/core#1456]
When using the extended country codes type ISO 639-1 (e.g. en-GB or en-US) the translation tool in the isotope configuration does not seem to work.
The produkt specific translations work properly but all labels and attribute names will not be translated.
I have tried this in the demo installation, too.

![bildschirmfoto 2015-06-16 um 18 04 36](https://cloud.githubusercontent.com/assets/6641281/8188520/c0466416-1456-11e5-8789-76a10730cda5.png)
![bildschirmfoto 2015-06-16 um 18 03 54](https://cloud.githubusercontent.com/assets/6641281/8188788/33d3e2ae-1458-11e5-9761-1e87d678d5f8.png)

![bildschirmfoto 2015-06-16 um 18 28 37](https://cloud.githubusercontent.com/assets/6641281/8188522/c0809104-1456-11e5-8581-a120dc2dc464.png)

**Comment by aschempp** [comment]
@qzminski I assume we need to convert `-` to `_` in the translation class.

**Comment by aschempp** [comment]
Fixed in 33635967f50b7ef6882535ce9a5b281ef0af54d1
