### ISSUE TITLE
inherited filter in backend product list is confusing

### ISSUE THREAD

**Issue by eBlick** [isotope/core#1457]
after filtering a product - for example by name- , this filter stays when selecting a product variant (see screenshot).
![bildschirmfoto 2015-06-16 um 18 05 36](https://cloud.githubusercontent.com/assets/6641281/8188635/5aba2014-1457-11e5-9e2b-e07653a6c0f7.png)

The filter was set to product name "Madeira". When selecting the variants, the list is empty. This is annoying and confusing for editors. They believe that there are no variants at the first place.

**Comment by aschempp** [comment]
Fixed in 54909d7822d42990ca415d459788435af8047d28
