### ISSUE TITLE
2.3.0 Beta 1 - Nach Installation Fieldset verschwunden

### ISSUE THREAD

**Issue by saress** [isotope/core#1458]
Nach der Installation der aktuellen 2.3.0 Beta1 auf einem Contao 3.5 ist auf einmal im Formulargenerator das Fieldset Element komplett verschwunden und nicht mehr in der Feldtyp Auswahl verfügbar (ist übrigens das einzige Element das fehlt).

Ansonsten sind noch folgende Module installiert: calendarfield, changelanguage, efg. 
Vor der Installation von Isotope ging noch alles und es wurden bereits ein paar Formular angelegt, die jetzt natürlich in Bezug auf das fieldset Element nicht mehr editiert werden können.

Beste Grüße
Sares

**Comment by aschempp** [comment]
Isotope hat nichts mit dem Formulargenerator zu tun. Du hat vermutlich ein Tabellen-Layout aktiviert, dann ist das Fieldset im Core automatisch weg.

**Comment by saress** [comment]
Oje, wie unachtsam von mir. Ja, Du hast natürlich Recht, sorry für die Falschmeldung und danke für die schnelle Antwort!
