### ISSUE TITLE
Major performance improvement with a simple missing DB index

### ISSUE THREAD

**Issue by Toflar** [isotope/core#1460]
The following index must be added to `tl_iso_product`:

```php
$GLOBALS['TL_DCA']['tl_iso_product']['config']['sql']['keys']['pid,language'] = 'index';
```

I've debugged an installation with a lot of translations and it took me 8 minutes (!) on my localhost to search all 1600 product entries. This is because the product list joins the translations using the following SQL:

```sql
LEFT OUTER JOIN tl_iso_product translation ON tl_iso_product.id=translation.pid AND translation.language='de'
```

However, the database currently cannot use any index for this join and it thus takes forever.
The other solution would be to optimize the part of the code where it joins the translation table to make use of the already existing index

```php
'language,published,start,stop,pid'     => 'index',
```

but I don't think this makes sense here. After my optimization, the database query took 15 ms instead of 8 minutes :-)

**Comment by aschempp** [comment]
Reopening because we should backport this to 2.1 + 2.2
