### ISSUE TITLE
Manuelle Sortierung funktioniert nicht mehr

### ISSUE THREAD

**Issue by k-webdesign** [isotope/core#1461]
Die manuelle Sortierung funktioniert nicht mehr mit dem Drag'n'Drop. Man fährt über das Icon und es kommt das Icon mit allen 4 Himmelsrichtungen, aber man kann nichts mehr verschieben. 

Hier unter Contao 3.4.0 und Isotope 2.2.2

![produktsortierung](https://cloud.githubusercontent.com/assets/4130440/8283320/f6644898-18f6-11e5-854b-0edd4e2e4b15.jpg)

Siehe auch: https://community.contao.org/de/showthread.php?51493-Produkte-manuell-sortieren&p=360039&viewfull=1#post360039

**Comment by felixpfeiffer** [comment]
In Isotope 2.2.4 scheint das zu gehen.

**Comment by aschempp** [comment]
Könnte daran liegen dass es in der 2.2.3 behoben wurde, danke für den Tipp @felixpfeiffer ;-)

https://github.com/isotope/core/releases/tag/2.2.3

**Comment by k-webdesign** [comment]
Hmmmm. Seit meinem Update auf Isotope 2.2.5 und Contao 3.5.0 geht der Pagepicker nicht mehr. Der Klick auf "Anwenden" ist erfolglos mit der Fehlermeldung "Uncaught TypeError: Cannot read property 'getElementsByTagName' of null" in Zeile 32 der backend.min.js:1.
Ist das ein Problem von Isotope und hängt noch hiermit zusammen oder ist das der Core?

**Comment by aschempp** [comment]
Den Fehler kenne ich eigentlich aus der RC1 von Contao 3.5…
