### ISSUE TITLE
Sortierung in Produktvarianten-Liste

### ISSUE THREAD

**Issue by felixpfeiffer** [isotope/core#1462]
Ich habe eine Produktvariantenliste angelegt. Leider wird zum einen die manuelle Sortierung der Hauptprodukte nicht korrekt übernommen und teilweise werden die Varianten eines Produkts nicht fortlaufend angezeigt.

Das kann z.B. so aussehen: 

1. Varianten Produkt 1
2. Vier Varianten Produkt 2
3. Varianten Produkt 3
4. Vier weitere Varianten Produkt 2

Ich habe leider noch nicht ermitteln können, nach Welchem Muster diese Fehler auftreten.

Backend- und Fronten-Zugang bekommt ihr gerne per Skype.

**Comment by aschempp** [comment]
Kann es sein dass die in der Produktliste konfigurierte Sortierung darauf einen Einfluss hat? z.B. dass die Varianten andere Artikelnummern haben?

PS: Analyse auf Kundensystemen machen wir nur für [Circle-Mitglieder](https://circle.isotopeecommerce.org)

**Comment by felixpfeiffer** [comment]
Im Listen-Modul habe ich keine Sortierung ausgewählt. Die Varianten haben allerdings andere Artikelnummern.

**Comment by aschempp** [comment]
Kannst du herausfinden ob die Sortierung irgend einen Sinn macht? Also zum Beispiel die Artikelnummern oder Produktnamen auf- oder absteigend sortiert sind?

**Comment by aschempp** [comment]
*ping*

**Comment by aschempp** [comment]
Ich schliesse dies mangels Feedback
