### ISSUE TITLE
isotope 2.2.5.9002, Contao 3.5.0 - Produktleser verursacht 404

### ISSUE THREAD

**Issue by albirs** [isotope/core#1463]
Wenn bei im Betreff genannter Konstellation der Produktleser auf einer separaten Seite angezeigt werden soll, verursacht dieser ein 404. 

Produktliste und -Leser auf einer Seite funktionieren.

https://community.contao.org/de/showthread.php?57687-isotope-2-2-5-9002-Contao-3-5-0-Produktleser-verursacht-404

https://community.contao.org/de/showthread.php?51498-isotope-2-1-Produktleser-nicht-auf-Seite-mit-Produktliste&p=374288&viewfull=1#post374288

**Comment by aschempp** [comment]
Siehe auch https://community.contao.org/de/showthread.php?51498-isotope-2-1-Produktleser-nicht-auf-Seite-mit-Produktliste&p=374288#post374288

**Comment by aschempp** [comment]
Fixed in b3adf460bf1319392bf7c08a8f859a6e1b191545. This was actually due to my own ticket at https://github.com/contao/core/issues/7661 :D
