### ISSUE TITLE
"Anwenden" im Pagepicker der manuellen Sortierung ist nicht möglich

### ISSUE THREAD

**Issue by k-webdesign** [isotope/core#1464]
Seit meinem Update auf Isotope 2.2.5 und Contao 3.5.0 geht der Pagepicker bei der manuellen Sortierung unter dem Menüpunkt Produkte nicht mehr.

Der Klick auf "Anwenden" ist erfolglos mit der Fehlermeldung "Uncaught TypeError: Cannot read property 'getElementsByTagName' of null" in der backend.min.js:1.

**Comment by aschempp** [comment]
siehe #1488
