### ISSUE TITLE
Filtermöglichkeiten Gruppen und Kategorien in Contao 3.5.0 nicht möglich

### ISSUE THREAD

**Issue by ae69** [isotope/core#1465]
Seit dem Update von Contao 3.4.5 auf 3.5.0 ist die Auswahl von "Gruppen und Seiten" in der Produktauswahl nicht mehr möglich. Es läßt sich zwar der RadioButton der  gewünschte Seite  anklicken, aber beim Klick auf "Anwenden" passiert nichts :-(
Bei Isotope 2.2.4 oder 2.2.5 der gleiche Fehler

**Comment by aschempp** [comment]
Duplicate of https://github.com/isotope/core/issues/1464
