### ISSUE TITLE
Falsche Länderauswahl in Bestellprozess

### ISSUE THREAD

**Issue by Creational** [isotope/core#1466]
Als angemeldeter Frontend-User wird im Bestellprozess bei Rechnungs- und Versandadresse das falsche Land in der Länderauswahl ausgewählt. Die Auswahl wird immer auf das in der Shop-Konfiguration angegebene Standardland gesetzt.

Dieser Fehler tritt nur dann auf, wenn für den entsprechenden Frontend-User noch kein Eintrag im Adressbuch vorhanden ist (z.B. nach Neuregistrierung).

Getestet unter
Contao 3.4.5 / Isotope 2.2.5
Offizielle Demo Contao 3.5 beta1 / Isotope 2.3 beta1

**Comment by aschempp** [comment]
Fixed in 7780b7ea09988d5b53ecfd6c012bdcfe3b52dabe
