### ISSUE TITLE
Update documentation with new features

### ISSUE THREAD

**Issue by aschempp** [isotope/core#1469]
See blog posts for Beta and RC

**Comment by Toflar** [comment]
We're talking about:

> New cumulative filter settings

Done.

> New elevate zoom gallery

Done. Don't know if my sentence about the settings is right though? https://isotopeecommerce.org/de/handbuch/v/2.3/r/elevate-zoom-galerie.html

> PensoPay

I've added the incomplete page, as I personally am not able to document it: https://isotopeecommerce.org/de/handbuch/v/2.3/r/zahlungsart-pensopay.html


Can you?

**Comment by aschempp** [comment]
I would remove the first sentence:

> ~~Elevate Zoom bringt die Zoom-Galerie aus Isotope 1.4 zurück!~~ Die Galerie ist praktisch in der Detailansicht eines Produktes und erlaubt das "Zoomen" des Hauptbildes. Eine ausführliche Beschreibung der Galerie findet sich auf der Herstellerseite des jQuery-Plugins.

**Comment by Toflar** [comment]
Done. Still, is it correct that there are no elevate zoom specific settings? And what about PensoPay?

**Comment by aschempp** [comment]
There are gallery-specific settings.

![bildschirmfoto 2015-08-21 um 11 55 08](https://cloud.githubusercontent.com/assets/1073273/9405846/86b97a70-47fb-11e5-8280-2d94cd96d52a.png)
![bildschirmfoto 2015-08-21 um 11 55 20](https://cloud.githubusercontent.com/assets/1073273/9405845/86b8e97a-47fb-11e5-9863-af9df5090b67.png)


And there are the obvious settings of payment methods:

![bildschirmfoto 2015-08-21 um 11 57 08](https://cloud.githubusercontent.com/assets/1073273/9405870/cc9d5016-47fb-11e5-807a-7637b508f07d.png)
