### ISSUE TITLE
Hook for Address update

### ISSUE THREAD

**Issue by Zeromax** [isotope/core#1473]
It would be cool to have a hook in the address module when a address has changed.
With the old and new data like the `$GLOBALS['TL_HOOKS']['updatePersonalData']` from Contao.

That would offer for example to send a notfication for changed addresses.

Is it to late for 2.3, cause its already in the RC?

**Comment by aschempp** [comment]
Yes that's too late for 2.3, but certainly a good idea.

**Comment by aschempp** [comment]
Implemented in #1625
