### ISSUE TITLE
Eigene Attribute in Bestellbestätigung Mail

### ISSUE THREAD

**Issue by markknochen1** [isotope/core#1474]
Hallo,

im Template iso_collection_mail.html5 möchte ich gerne ein eigenes Attribut mit ausgeben, welches über die Shopkonfiguration erstellt worden ist.

Im Model ProductCollection.php habe ich das Attribut "webinarLink" hinzugefügt:

$arrItem = array(
            ....
'webinarLink'       => $objItem->getWebinarLink()
        );

die Methode getWebinarLink() ist im Model ProductCollectionItem.php hinzugefügt worden.

Aber ich kann im Template iso_collection_mail.html5 den Wert nicht per $item['webinarLink'] ausgeben ... vermutlich werden noch irgendwo anders die Werte für die einzelnen Artikel in der Bestätigungsmail gesammelt, aber ich kann nicht finden, wo ... oder ist mein Ansatz komplett falsch?

Danke

Mark

**Comment by markknochen1** [comment]
Bis zur letzten Seite der Bestellung ist $arrItem['webinarLink'] richtigerweise gefüllt.

das Feld "webinarLink" kommt auch im Template iso_collection_mail.html5 an, da ist es aber leer.

wenn ich allerdings $arrItem['webinarLink'] hart mit "TEST TEST TEST" fülle - das wiederum kommt
im Mail-Template an und wird auch ausgeben. 
Das ist doch eigenartig -> prinzipiell geht es, aber wenn ich den Wert per Funktion übergebe, dann 
wird nichts an das Mailtemplate weitegeleitet.

Auch das Zwischenspeichern in eine Variable, also:

$test = "TEST TEST TEST";
$arrItem = array(
'webinarLink' => $test
);

hilft nicht ....

Mark

**Comment by aschempp** [comment]
Änderungen an den Core-Dateien ist sicherlich immer falsch. Dieses Ticketsystem ist aber für Fehler und Feature-Requests, für Fragen wende dich bitte an's Community Forum.
