### ISSUE TITLE
Platzhalter für "In Datei schreiben" erlauben und ausgeben

### ISSUE THREAD

**Issue by jenda77** [isotope/core#1475]
Hallo, 

es wäre sehr toll, wenn man die Platzhalter von Isotope für die Möglichkeit "In Datei schreiben" verwenden und damit ausgeben könnte, genau wie es bei Mail geht. So könnte man sich die Daten in verschiedenen Formaten ausgeben lassen. Für eine Firma ist es wichtig, die Daten der Bestellungen auch noch aus Contao exportieren zu können. 

Liebe Grüße,
Jan

https://github.com/terminal42/contao-notification_center/issues/66

**Comment by aschempp** [comment]
@qzminski the notification center placeholders must be set up accordingly in the configuration file.

**Comment by jenda77** [comment]
Thank you. It would be great to allow the simple token too.

**Comment by qzminski** [comment]
Fixed in 1b2fed4. In 2.2 there is also a new notification type ```iso_memberaddress_change``` which was not yet in 2.1 but it could have those tokens as well.

**Comment by jenda77** [comment]
Great! Will it come with the next version - that means Istotope 2.3?

**Comment by aschempp** [comment]
See the milestone in this ticket, it will come with the next version of 2.1 and 2.2 and 2.3.

@qzminski would make sense to update that too?

**Comment by qzminski** [comment]
Yes it would. Shall I update or actually fix it in the 2.2.6 branch?

**Comment by aschempp** [comment]
What do you mean by «update» ?
