### ISSUE TITLE
Fallbacksprache - Auswahl nicht möglich

### ISSUE THREAD

**Issue by saress** [isotope/core#1476]
Es ist auf Grund eines CSS Problems nicht möglich, das Select Feld für die Fallback Sprache auszuwählen. Entfernt man bei:

```
.tl_version_panel .tl_formbody {
  position: relative;
}
```

das position:relative; ist die Select-Box wieder auswählbar.

Getestet haben wir das auf mehreren Rechner unter Windows 8.1, Firefox & Chrome (jeweils die aktuellsten Versionen). Einzig der Internet Explorer erlaubt die Auswahl ohne Probleme.

Contao 3.5.0, Isotope 2.3.0. beta1

Beste Grüße
Saress

**Comment by paulhaem** [comment]
Selbes Issue bei der aktuellen Isotope-Demo aufgetaucht nachdem Composer installiert wurde.

Ablauf:
 - Datenbank anlegen / SQL importieren
 - install.php aufrufen
 - Login
 - Composer installieren / Migration starten
 - Datenbank aktualisieren
 - bei beliebigem Produkt 'Deutsch' hinzufügen
 - Fallback kopieren
 - Speichern
 - Select-Field für Sprache nicht mehr auswählbar

Contao 3.5.27
Isotope 2.4.1

**Comment by aschempp** [comment]
beide Versionen sind doch veraltet?

**Comment by paulhaem** [comment]
Contao auf 3.5.28 upgedated
Isotope auf 2.4.3 upgedated

Select-Feld für die Sprachauswahl immer noch nicht auswählbar. Wird bei `.tl_version_panel .tl_formbody` die `position: relative` entfernt / überschrieben, ist das Feld wieder anklickbar. Scheint vom Select-Feld der Versionauswahl überlagert zu werden, siehe: https://github.com/isotope/core/issues/1850

**Comment by aschempp** [comment]
siehe #1850
