### ISSUE TITLE
Insert-Tag: {{cart::items}} - keine Anzeige im Title-Tag

### ISSUE THREAD

**Issue by saress** [isotope/core#1477]
Wir verwenden den oben genannten Insert Tag um in der Seitenstruktur den Seitennamen - z.B. Warenkorb ({{cart::items}}) - um die Anzeige der im Warenkorb abgelegten Produkte zu erweitern. In der Navigation wird die Anzahl auch erwartungsgemäß angezeigt, im Seitentitel der Seite wird allerdings nur die leere Klammer Warenkorb () angezeigt.

Eventuell handelt es sich hier um einen kleinen Bug?

Beste Grüße
Saress

**Comment by aschempp** [comment]
Welche Contao-Version verwendest du?

**Comment by saress** [comment]
Das ist die aktuelle LTS Version 3.5.0.

**Comment by aschempp** [comment]
Das Problem resultiert aus https://github.com/contao/core/issues/7097, darauf hat Isotope keinen Einfluss. Ich habe das Thema aber bei Contao nochmals gestartet.

**Comment by aschempp** [comment]
In Contao 4.2 wird das Problem gelöst sein (siehe https://github.com/contao/core-bundle/pull/473#issuecomment-208223912) :-)
