### ISSUE TITLE
Bildgröße - Bestellungen / Bestelldetails

### ISSUE THREAD

**Issue by saress** [isotope/core#1478]
Bearbeitet man eine Bestellung, so wird in den Bestelldetails das Produktbild in der vollen Größe angezeigt, was zu einem etwas zerstörten Layout im Backend führen kann. Eventuell wäre es hier sinnvoll, eine maximale Bildgröße für diese Ansicht zu hinterlegen.

Beste Grüße
Saress

**Comment by saress** [comment]
Kurze Ergänzung: Contao 3.5.0, Isotope 2.3.0 Beta 1

**Comment by aschempp** [comment]
Das Bild wird in der Grösse angezeigt, welche du in der Galerie konfiguriert hast (vorausgesetzt du hast eine Galerie zugewiesen…).

**Comment by saress** [comment]
Die Galerien habe ich angelegt, nur wie kann ich das im "Backend" beim Punkt "Bestellungen" dann zuweisen? An dieser Stelle kann ich mir ja nur mehr die entsprechenden eingegangen Bestellungen anschauen. Im Frontend funktioniert das natürlich alles, nur wenn man die Bestellungen im Backend editiert, passt die Bildgröße nicht.

**Comment by aschempp** [comment]
Der Backend-Punkt "Bestellungen" verwendet automatisch das erste Modul vom Typ "Bestelldetails" welches gefunden werden kann. Das ist nicht wirklich ideal, aber vielleicht eine Lösung für dich ;-)
