### ISSUE TITLE
Javascript Fehler in autosuggester.min.js

### ISSUE THREAD

**Issue by saress** [isotope/core#1479]
Editiert man bei den Benachrichtigungen die Inhalte (siehe unten), dann tauchen in der Javascript Konsole von Chrome zahlreiche Javascript Fehler auf, z.B.:

/system/modules/notification_center/assets/autosuggester.min.js:1 Uncaught SyntaxError: Invalid regular expression: /^request).(?!$)/: Unmatched ')' 

oder auch:

Uncaught TypeError: Cannot read property 'getPosition' of undefined

Die Autosuggest Vorschläge werden aber dennoch angezeigt.

Konkret habe ich einen Email-Gateway eingerichtet, dann unter Sprachen die entsprechenden Sprache definiert (Deutsch, Englisch-Englisch) und dann z.B. die deutsche Sprache editiert. Auftreten tut das Problem dann z.B. beim Editieren des "Rohtexts".

Contao: 3.5.0, Isotope 2.3.0 Beta 1, Windows 8.1, Chrome aktuellste Version

Beste Grüße
Saress

**Comment by aschempp** [comment]
Das wäre wohl ein Bug im Notification Center? 

/cc @Toflar

**Comment by Toflar** [comment]
Bitte den Debug-Modus aktivieren damit wir aussagekräftigere Infos haben.

**Comment by aschempp** [comment]
Ich schliesse das mal mangels Informationen. Falls der Fehler weiter besteht bitte ein Ticket beim Notification Center (https://github.com/terminal42/contao-notification_center) erstellen.
