### ISSUE TITLE
Bestellungen - mehrere bearbeiten, löschen fehlt

### ISSUE THREAD

**Issue by saress** [isotope/core#1483]
Geht man im Backend auf "Bestellungen", dann auf "Mehrere bearbeiten", dann fehlt bei den Optionen die Möglichkeit alle Bestellungen zu löschen. Sichtbar sind nur Kopieren, Überschreiben und Bearbeiten.

Contao: 3.5.0
Isotope: 2.3.0 Beta 1

Beste Grüße
Saress

**Comment by aschempp** [comment]
Das ist absichtlich aus Sicherheitsgründen so gebaut. Bestellungen sollten storniert und nicht gelöscht werden. Massen-Löschen macht nur auf Datenbank-Ebene Sinn.
