### ISSUE TITLE
Produkt  löschen - Lösch-Icon ausgegraut

### ISSUE THREAD

**Issue by saress** [isotope/core#1484]
Bei meiner Suche habe ich folgenden Issue gefunden: #1024 
Löscht man jetzt aber alle Bestellungen, so sollten auch die Produkte wieder gelöscht werden können, oder?

Gleiches Problem mit den ausgegrauten Lösch-Icons tritt übrigens auch bei Varianten eines Produkts auf, die lassen sich auch nicht mehr löschen habe ich gerade festgestellt.

Contao: 3.5.0
Isotope: 2.3.0 Beta 1

Beste Grüße
Saress

**Comment by aschempp** [comment]
Die Produkte können sich auch in einem Warenkorb befinden. Gegebenenfalls muss die Datenbank-Tabelle geleert werden. Bitte wende dich dazu aber an's Forum, da es sich nicht um einen Bug handelt.
