### ISSUE TITLE
Installation mit Composer unter Contao 3.5 läuft nicht

### ISSUE THREAD

**Issue by jenda77** [isotope/core#1486]
Ich habe gerade versucht, Isotope in Contao 3.5 mit dem Composer direkt aus diesem Ordner zu installieren, leider wird es nicht erlaubt (siehe Bildschirmfoto), dafür aber über contao-legacy/isotope... Ist es richtig?

Liebe Grüße,
Jan
![bildschirmfoto 2015-07-08 um 15 19 00](https://cloud.githubusercontent.com/assets/3715050/8571111/0fc80726-2585-11e5-83d3-bc569942ff9d.png)

**Comment by aschempp** [comment]
Das ist ein Fehler den wir beheben müssen… ich weis nicht genau ob du das mit Composer Konfiguration umgehen kannst, müsstest du mal googeln…

**Comment by jenda77** [comment]
Das habe ich probiert, leider ergebnislos. Man kann aber auch nicht die 2.3 RC installieren. Über den Ordner contao-legacy/isotope ging es...

**Comment by aschempp** [comment]
Warum kannst du die RC nicht installieren?

**Comment by jenda77** [comment]
Weil es nicht mit Contao 3.5 kompatibel ist - wenigstens steht es dort. 
![bildschirmfoto 2015-07-09 um 13 11 36](https://cloud.githubusercontent.com/assets/3715050/8593893/1a78ab46-263c-11e5-996a-8d98cb0ec1ba.png)

**Comment by aschempp** [comment]
Also da steht >= 3.5.0. Verwendest du eventuell noch die Beta oder RC von Contao 3.5?

**Comment by jenda77** [comment]
Ok, jetzt ging es, ich habe die richtige Contao-Version gehabt - mich hat nur der Hinweis Diese Paket-Version ist mit dieser Contao-Version nicht kompatibel verunsichert, daher habe ich es gar probiert. Entschuldige. Allerdings verschwanden mit der RC-Version alle Schaltflächen für Warenkorb & Co.
