### ISSUE TITLE
[2.3.0 RC1] Schaltflächen für Warenkorb & Co. verschwunden

### ISSUE THREAD

**Issue by jenda77** [isotope/core#1487]
Hallo, 

ich habe die aktuelle RC-Version aktiviert, allerdings verschwanden mit ihr alle Schaltflächen für Warenkorb & Co. in der Vollansicht, obwohl das in der Leservorlage aktiviert ist (ich aktivierte es probeweise auch in der Produktliste, allerdings wurde auch nichts gezeigt. Cache habe ich auch gelöscht.) 

Woran kann es liegen?

Liebe Grüße,
Jan

**Comment by aschempp** [comment]
Fehler ist bekannt und bereits behoben: https://github.com/isotope/core/blob/release/2.3.0/system/modules/isotope/docs/CHANGELOG-2.3.md
