### ISSUE TITLE
Bug product group selection [2.2.5 - 2.3] Contao 3.5

### ISSUE THREAD

**Issue by MoniqueHahnefeld** [isotope/core#1488]
Konsole Fehler bei Gruppe auswählen, im Popup meldet die Konsole diesen Fehler, sobald ich einen radiobutton zur Auswahl klicke.

>group.php?do=iso_products&table=tl_iso_group&field=gid&value=0:41 Uncaught TypeError: Theme.toggleSelect is not a functiononclick @ group.php?do=iso_products&table=tl_iso_group&field=gid&value=0:41

Ein weiterer Fehler erscheint wenn ich auf Anwenden gehe. Das JS wird hier abgebrochen.

>2backend.min.js:1 Uncaught TypeError: Cannot read property 'getElementsByTagName' of null(anonymous function) @ backend.min.js:1a @ 0cc96f7295d0.js:3

**Comment by aschempp** [comment]
@qzminski this should be fairly easy to solve. The same problem that was fixed in Contao 3.5 after RC afaik.

**Comment by MoniqueHahnefeld** [comment]
THX

**Comment by Fuzzyma** [comment]
I am not able to install 2.2.6 via extension repo in order to fix this issue. Is this not available yet?

**Comment by aschempp** [comment]
The list of available releases should answer your question: https://github.com/isotope/core/releases

**Comment by Fuzzyma** [comment]
Oh - only saw the "from 2.2.6"-stuff and thought this would be an release, too. Thank you!
