### ISSUE TITLE
Contao 4

### ISSUE THREAD

**Issue by tonimoeckel** [isotope/core#1489]
Moin,
ist bis jetzt schon in irgend einer Weise ein Update für Contao 4 geplant?
Viele Grüße :)

**Comment by aschempp** [comment]
Dass es von Contao 3 auf Contao 4 bisher kein Update gibt hat ja mit Isotope nichts zu tun. Isotope 2.3 wird aber mit Contao 4 kompatibel sein.

**Comment by tonimoeckel** [comment]
Alles klar hab mich nur gewundert weil offiziell im Composer 3.5 steht .. Danke !!! :)

**Comment by aschempp** [comment]
Danke, das muss ich ändern (auch wenn das CCA Composer-Plugin das bisher noch nicht installieren kann :( ).

**Comment by aschempp** [comment]
FIxed in c0d5b5fbdb03547dcd8ec719ad14002ff5bed5fa
