### ISSUE TITLE
Performance - Less Pings :) [css]

### ISSUE THREAD

**Issue by MoniqueHahnefeld** [isotope/core#1490]
Hi,

can we add the isotope.min.css and the Autocompleter.min.css add to the Layout-Settings "Stylesheet"?
The advantage of this will be that this files will be included with the other ones. That will reduce the pings.

**Comment by MoniqueHahnefeld** [comment]
cool, thx :) +1

**Comment by aschempp** [comment]
Changed in 3a81660d69f24e6fa9c912cdcf99008366569ad8
