### ISSUE TITLE
No HTML5 form validation?

### ISSUE THREAD

**Issue by Anke** [isotope/core#1493]
Hi,

in the isotopeecommerce.org blog you say "Wir nutzen HTML5-Features statt JavaScript-Magie", but it seems this statement doesn't apply to the checkout forms. 

If someone doesn't accept the terms and condition at the bottom of the form, the browser jumps back to the top of the page, i.e. many a customer might think the order has been processed. 

Is there any possibility (or a workaround) to activate the HTML5 validation, so I don't have to use JavaScript? (in use: Contao 3.5, isotope 2.3 beta)

Regards,
Anke

**Comment by aschempp** [comment]
Unfortunately we can't use the HTML5 validation because we have hidden input fields (in the address step). The browser would try to validate the invisible fields for the shipping address, if you select "use billing address".

**Comment by Anke** [comment]
I see.  Where (which template) can I enter something like

<code><?php if ($this->hasError): ?>
< p class="toperror" >Ihre Bestellung wurde noch nicht abgeschickt!<br>Bitte überprüfen Sie Ihre Eingaben in den markierten Feldern.< /p >
<?php endif; ?></code>

to show an error message at the top of the page? I tried several templates - to no avail.

**Comment by aschempp** [comment]
As far as I know, there is no `hasError` variable, so your code won't work…

**Comment by Anke** [comment]
In this case I'd propose this variable as an enhancement. It is present in common Contao forms, isn't it?

**Comment by aschempp** [comment]
Please create a separate issue for new feature requests (this is about HTML5 form validation).

**Comment by Anke** [comment]
See https://github.com/isotope/core/issues/1499
