### ISSUE TITLE
2.3 RC1: elevateZoom not working because of capitalized "Z" in filename

### ISSUE THREAD

**Issue by hubbd** [isotope/core#1496]
OBSERVATION:
when using the elevate zoom gallery a resource is automatically added to the html header:

script src="system/modules/isotope/assets/plugins/elevatezoom/jquery.elevatezoom-3.0.8.min.js"

PROBLEM:
But this cannot be loaded because: "The requested URL /system/modules/isotope/assets/plugins/elevatezoom/jquery.elevatezoom-3.0.8.min.js"

REASON:
the file is actually named "...elevatezoom/jquery.elevateZoom..." - with a capital Z.

FIX:
changing the filname (in the filesystem) to all lower case solves this problem: "jquery.elevatezoom-3.0.8.min.js"

TADA :-)

**Comment by aschempp** [comment]
Fixed in 6ba6dd2a4bda8533a7a1d6a9fdba0bae8a4b4532
