### ISSUE TITLE
2.3 RC1: Picture Upload not working if contao root folder itself is not accessible by webserver user

### ISSUE THREAD

**Issue by hubbd** [isotope/core#1497]
OBSERVATION
Picture Upload for items (Backend) seemed to work, but pictures weren't saved and gone when re-opened items page.

REASON
Even though all files in /webserverroot/contao-3.5.2/ were writable for webserver daemon user (debian: www-data), the root folder itself was not. So the isotope picture folder ./contao-3.5.2/isotope/ could obviously not be created.

PROBLEM
The contao requirements check ignores the root folder itself. So for everyone with the same setup it is not obvious why only just the saving of the isotope pictures doesn't work.

SUGGESTED FIX
This is probably not a widespread setup and problem, but maybe there should be an error message (at least to the log file) if the folder /isotope/ couldn't be created.

**Comment by Toflar** [comment]
But the `isotope` folder is part of the distribution? It should've been there all the time and doesn't have to be created?

**Comment by aschempp** [comment]
It is created by the extension repository or composer installer, which might fail. So maybe there's not much we can do…

**Comment by hubbd** [comment]
Makes sense! Well, since nobody seems to have have complained before me, let's assume it's an edge case. And those who have the same problem hopefully will stumble upon this thread!

**Comment by aschempp** [comment]
I guess we can close this issue then, agreed?
