### ISSUE TITLE
FR: Implementation of hasError variable

### ISSUE THREAD

**Issue by Anke** [isotope/core#1499]
It would be nice to have the hasError variable (as in Contao forms) to be able to place error messages like this at the top of the page:

<code><?php if ($this->hasError): ?> 
< p class="toperror" >Ihre Bestellung wurde noch nicht abgeschickt!Bitte überprüfen Sie Ihre Eingaben in den markierten Feldern.< /p > 
<?php endif; ?></code>

Main problem: People missing to select the mandatory legal condition (AGB) at the bottom of the page, the one of which will be outside the viewport after hitting submit due to page reload.

**Comment by aschempp** [comment]
This must be implemented in Haste (see https://github.com/codefog/contao-haste/issues/70)

**Comment by aschempp** [comment]
Looks like it's already available (https://github.com/codefog/contao-haste/issues/70#event-385231671)

try using 
```
<?php if (!$this->valid): ?> < p class="toperror" >Ihre Bestellung wurde noch nicht abgeschickt!Bitte überprüfen Sie Ihre Eingaben in den markierten Feldern.< /p > <?php endif; ?>
```
