### ISSUE TITLE
[2.2.5] Schreibfehler im Versandkostenrechner

### ISSUE THREAD

**Issue by baumisimon** [isotope/core#1500]
Im Versandkostenrechner ist ein Schreibfehler, wenn noch kein Land ausgewählt ist:
> Bitte geben Sie eine Lie**d**eradresse ein.

Ist sowohl in 2.2.5 als auch in der 2.3.0 RC2

Bin ich mit so "Kleinigkeiten" hier auch richtig?

**Comment by aschempp** [comment]
Das würdest du am besten direkt selber über www.transifex.com anpassen.

**Comment by baumisimon** [comment]
OK, erledigt :)

**Comment by aschempp** [comment]
Dann bitte Ticket schliessen ;-)
