### ISSUE TITLE
Attribut Datei-Upload: Upload mehrerer Dateien ermöglichen?

### ISSUE THREAD

**Issue by michelbalzer** [isotope/core#1501]
Könnte das „Datei Upload“-Attribut so erweitert werden, dass es mehrere Dateien annimmt?

(Der Core-Formulargenerator kann das ja auch, mimimi)

**Comment by aschempp** [comment]
Der Core-Uploader im Contao Formulargenerator kann das nicht, daher kann ich das im Frontend nicht ergänzen. Allerdings werden wir in der Version 2.4 Unterstützung für unser FineUploader Widget hinzufügen (siehe https://github.com/terminal42/contao-fineuploader)

**Comment by michelbalzer** [comment]
Ich hätte schwören können, dass das im Core geht. Nun gut, dann nicht.
