### ISSUE TITLE
Configure a reader page by pagesetting

### ISSUE THREAD

**Issue by katgirl** [isotope/core#1502]
In 2.2.5 you can set a reader page but ```$this->href``` have wrong page

The ```iso_readerJumpTo``` is only check by ```\Frontend``` but not by ```\Product``` or ```\Gallery```

**Comment by katgirl** [comment]
Workaround in ```iso_list_default```

```php
<h3><a href="<?php 
  global $objPage; 
  if ($objPage->iso_setReaderJumpTo && $objPage->iso_readerJumpTo ) { 
    echo Controller::replaceInsertTags("{{link_url::".$objPage->iso_readerJumpTo."}}")."/".$this->alias; 
  } else { 
    echo $this->href; 
  } ?>" title="<?php echo $this->label_detail; ?>"><?php echo $this->generateAttribute('name'); ?></a></h3>
```

**Comment by aschempp** [comment]
Die aktuelle Seite ist nicht zwingend auch die Reader-Seite. Wenn dein Produkt mehrere Listen-Seiten hat, wird immer dieselbe Reader-Seite (die Erste im Backend zugewiesene) verwendet.
