### ISSUE TITLE
Round rules-price

### ISSUE THREAD

**Issue by MoniqueHahnefeld** [isotope/core#1505]
Hi :)

description of my problem:
https://github.com/isotope/core/blob/master/system/modules/isotope_rules/library/Isotope/Rules.php#L115
>$fltPrice = 8.78
$objRules->current()->getPercentage() = -37;

// PHP_ROUND_HALF_UP oder kaufmänisch gerundet
https://de.wikipedia.org/wiki/Rundung#Kaufm.C3.A4nnisches_Runden
8.78/100\*63 = 5.6314 = 5.63
8.78/100\*37 = 3.2486 = 3.25

 >$fltDiscount = 100 + $objRules->current()->getPercentage(); //63
 $fltDiscount = round($fltPrice - ($fltPrice / 100 * $fltDiscount), 10); // works fine  3.2486

Why this? That makes the rounding bad. It could later be cutted to 2 steps after zero.
> $fltDiscount = $fltDiscount > 0 ? (floor($fltDiscount * 100) / 100) : (ceil($fltDiscount * 100) / 100);

Maybe it is better if the cut comes with the formatPrice-function?

**Comment by aschempp** [comment]
Schau mal bitte im release/2.3.0 Branch, da hat sich die Berechnung ggf. geändert.

**Comment by MoniqueHahnefeld** [comment]
Nein ist der selbe Code? oder worauf willst du hinaus – Habt ihr das schon auf dem Schirm?
https://github.com/isotope/core/blob/release/2.3.0/system/modules/isotope_rules/library/Isotope/Rules.php#115

**Comment by MoniqueHahnefeld** [comment]
@aschempp hast du hier schonmal nachsehen können?

**Comment by aschempp** [comment]
Ich habe jetzt glaub ich verstanden :D 

Die Regeln in Isotope runden immer zu Gunsten des Shop-Betreibers, es wird also nie aufgerundet sodass ein 8%-Gutschein nie 8.001% sein wird, sondern eher 7.999%.
