### ISSUE TITLE
When using options manager the internal field type is stored as varchar(255)

### ISSUE THREAD

**Issue by Toflar** [isotope/core#1507]
I don't think this is intentional, is it? When the `optionsSource` is a `table` then it's always an integer which would probably optimize the key which is added on filterable fields :)

**Comment by aschempp** [comment]
that key is only for the backend list as far as I know?

**Comment by Toflar** [comment]
It's only about the field type that should be an integer ;)

**Comment by aschempp** [comment]
Fixed in 3c3ea5085764cdf61ffb96c4f65210c216c56488
