### ISSUE TITLE
Add Checkout Modul ID to Collection [feature]

### ISSUE THREAD

**Issue by MoniqueHahnefeld** [isotope/core#1510]
Hi,

please can we add the Id of the used Checkout Modul to the ProductCollection?
It will be useful if someone want to get the settings of the Checkout Modul in an after order process.

Example:
I using the postOrderStatusUpdate hook: https://github.com/isotope/core/blob/124b377c94f722d0fec07cc3c46a626853686342/system/modules/isotope/library/Isotope/Model/ProductCollection/Order.php#l292

In my extension I add settings to the Checkout Modul, which I need for the postOrderStatusUpdate function. In the preCheckout hook I have no access to the current used Checkout Modul. It will be very difficult to get the id of used Checkout Modul on other way.
https://github.com/isotope/core/blob/e3b6293c5e2599adf2489f23a969160eb143d876/system/modules/isotope/library/Isotope/Module/Checkout.php#l196
// $objOrder->checkou_id = $this->id;

It will be only one field more an one line more. I can make a PR for this.

So I think it will be an enhancement.

**Comment by aschempp** [comment]
I have added the checkout module as second argument to `preCheckout` hook in 0d1ba6990cba03cfcfb8f7b585f2cb99e1185c16. This way anyone can do whatever necessary.

Be aware that you should probably not add the module ID to the order, but simply add your new configuration value. Simply use `$objOrder->my_value` and it will be stored in the order's `settings` array.

**Comment by richardhj** [comment]
Hello,
just noticed that every preCheckout (even the isotope_rule's preCheckout) throws a fatal error.
```php
                // !HOOK: pre-process checkout
                if (isset($GLOBALS['ISO_HOOKS']['preCheckout']) && is_array($GLOBALS['ISO_HOOKS']['preCheckout'])) {
                    foreach ($GLOBALS['ISO_HOOKS']['preCheckout'] as $callback) {
                        $objCallback = \System::importStatic($callback[0], $this);

                        if ($objCallback->$callback[1]($objOrder) === false) {
                            \System::log('Callback ' . $callback[0] . '::' . $callback[1] . '() cancelled checkout for Order ID ' . $this->id, __METHOD__, TL_ERROR);

                            static::redirectToStep('failed');
                        }
                    }
                }
```
You have to remove the $objOrder instance from importStatic() and add it two lines below ;)

**Comment by aschempp** [comment]
Already fixed in https://github.com/isotope/core/issues/1520

**Comment by MoniqueHahnefeld** [comment]
@aschempp Megacool! DANKE!!!
