### ISSUE TITLE
Bei Gastbestellung werden Preise nicht dem Land zugeordnet.

### ISSUE THREAD

**Issue by schaffen** [isotope/core#1513]
Hallo,

ich weiss nicht ob wirklich ein Bug, möchte Euch aber trotzdem die Frage stellen:

Isotope 2.2.5 / Contao 3.5
Gastbestellung im webShop - funktioniert soweit.
Allerdings werden beim Bestellprozess und Eingabe der Adresse und des entsprechenden Landes, die Preise in der Zusammenfassung nicht angepasst. 

Hättet Ihr vielleicht eine Idee dazu?
Vielen Dank für die Antwort.

lg
martin

**Comment by aschempp** [comment]
Worauf sollten sie denn angepasst werden?

**Comment by schaffen** [comment]
Im Grunde auf die zugehörigen Preisgruppen. Aber ich denke ich habe auch in meiner Überlegung einen Denkfehler. Deswegen anders gefragt:

Ist es irgendwie möglich bei Gastbestellung - Bestellprozess - Auswahl des Landes - diesen Gast einer Preisgruppe zuzuordnen?

Vielen Dank für die schnelle Antwort vorher!
LG
Martin

**Comment by aschempp** [comment]
Mit erweiterten Preisen lassen sich Preise für Mitglieder definieren und für Gäste (bzw. Fallback).

**Comment by schaffen** [comment]
Ich habe es mit Eintrag von mehreren Preisen und dazu gehörigen Steuersätzen - die wiederum einem Land zugeordnet waren - getestet. Leider werde dabei nicht die richtigen Preise ausgegeben. Sondern meist nur die Netto-Preise angezeigt. Auch wechseln die Preise nicht, wenn ich das Land des Mitgliedes ändere.

**Comment by aschempp** [comment]
Die Preise lassen sich nicht an Länder binden, nur an Mitgliedergruppen.

**Comment by schaffen** [comment]
Aber Steuersätze an entsprechendes Land und die werden eben leider nicht richtig angezeigt. 

Bitte vielmals um Verzeihung, wenn ich mich irre. Es kann leicht sein, dass ich den Wald vor lauter Bäumen nicht mehr sehen.

**Comment by aschempp** [comment]
Das kann ich leider so auch nicht beantworten, da ich dein System nicht kenne. Für Support gibt es das Community Forum oder https://circle.isotopeecommerce.org <https://circle.isotopeecommerce.org/>
