### ISSUE TITLE
2.3 RC2: Kann Produkt nicht in Produktgruppen verschieben

### ISSUE THREAD

**Issue by hubbd** [isotope/core#1515]
ZUM NACHVOLLZIEHEN:
Wenn ich unter "Produkte" auf das gelbe "Netzwerkordner"-Symbol klicke (Tooltip "Produkt ID n in eine Gruppe verschieben") öffnet sich als modales Fenster "Produktgruppen" mit einer Auflistung aller Produktgruppen mit Radio-Button zum Auswählen.

PROBLEM:
Wenn ich eine Produktgruppe auswähle und auf Anwenden klicke passiert ... Nichts!

ANALYSE:
Firebug-Konsole zeigt folgenden TypeError:
---->
TypeError: frm.document.getElementById(...) is null
http://dev.trendmoor.de/system/modules/isotope/assets/js/backend.min.js
Line 1
<----

Contao ist 3.5.2; Isotope 2.3RC2

**Comment by aschempp** [comment]
Ich kann den Fehler in der 2.3.0 stable nicht reproduzieren. Bitte auch den Browsercache leeren.
