### ISSUE TITLE
2.3 RC2: Attribute verschwinden nach Änderung des Typs

### ISSUE THREAD

**Issue by hubbd** [isotope/core#1516]
Zum Nachvollziehen:

1) Attribut "testAttr" anlegen:
- Typ: Textfeld
- Feldgruppe: Produktoptionen-Einstellungen

2) Attribut aktivieren in Produkttyp "testProdType"
- > Jetzt erscheint "testAttr" unter "Produktoptionen-Einstellungen" bei Produkten des Typs "testProdType"

3) Ändern des Typs von "testAttr" von Textfeld auf "Select-Menü"

4) Attribut verschwindet aus Eigenschaften des Produktes...

**Comment by aschempp** [comment]
Hast du für das Select-Menü vielleicht keine Optionen angelegt?

**Comment by hubbd** [comment]
Ich hatte Optionen angelegt und es hat auch alles funktioniert bis ich den Typ geändert habe. Habe die Felder mittlerweile schon längst wieder gelöscht. So kann ich es leider nicht nochmal rekonstruieren... Sorry.

**Comment by aschempp** [comment]
Ich kann das auch nicht reproduzieren. Einen Attributtyp ändern ist immer problematisch, das sollte wenn möglich vermieden werden.
