### ISSUE TITLE
"Bestellung nicht gefunden" nach Zahlung via Saferpay

### ISSUE THREAD

**Issue by daniel-melzer** [isotope/core#1517]
Bei einem bestehenden Shop (Contao 3.2 und Isotope 2.1.13) soll nun neben der Vorkasse (cash) auch die Zahlungen per Kreditkarte (saferpay) angeboten werden. Hier ergibt sich nun folgendes Problem:

Der Kunde wird auf die Payment Page von Saferpay geleitet, gibt seine Daten an und landet anschließend auf der Seite mit dem Modul Bestelldetails. Die Bestellung wird im Shop angelegt, Benachrichtigungen gehen raus und auch bei Saferpay ist die Zahlung zu sehen.

Jedoch erscheint anstatt den Bestelldetails der Hinweis "Bestellung nicht gefunden". Es gibt keine Fehler in den Logfiles. Das einzige was mir auffiel, sind die GET-Parameter. Bei Zahlungen mit der Methode Cash erhält die letzte Seite den Parameter <code>uid=[Bestellnummer].[hash]</code>, bei der Zahlung über Saferpay hingegen <code>?DATA=[XML]</code>.

**Comment by aschempp** [comment]
Kannst du bei Saferpay deaktivieren dass URL-Parameter mitgesendet werden?

**Comment by daniel-melzer** [comment]
Die Übergabe von URL-Parameter lässt sich sich nicht deaktivieren. Unter der Einstellung Datenübergabe wird nur der URL zur postsale.php eingetragen.

**Comment by aschempp** [comment]
Probier mal bei Saferpay nichts einzutragen (also z.B. keine Notify-URL). Die entsprechenden Infos sollten nämlich von Isotope bereits übermittelt werden.

**Comment by daniel-melzer** [comment]
Ich habe das nun mal ausprobiert und den Aufruf der postsale.php deaktiviert. Im Shop wird die Bestellung angelegt, aber wieder erscheint auf der Abschlussseite mit den Bestelldetails der Hinweis dass die Bestellung nicht gefunden werden konnte.

**Comment by daniel-melzer** [comment]
Das Problem konnte nun gelöst werden. Schuld war die Einstellung `VTConfig` der Payment Page. Hier muss die Option `PayInit` aktiviert werden.

Danke für die Unterstützung.

**Comment by aschempp** [comment]
Vielleicht magst du das im Handbuch ergänzen? https://isotopeecommerce.org/de/handbuch/v/2.3/r/zahlungsart-saferpay.html

**Comment by daniel-melzer** [comment]
Werde ich bei nächster Gelegenheit ergänzen.
