### ISSUE TITLE
Composer Client zeigt 3.5 als inkompatibel

### ISSUE THREAD

**Issue by aschempp** [isotope/core#1519]
Im Backend wird die Version 2.3 als nicht-kompatibel zu Contao 3.5 angezeigt. Wenn man's aber auswählt geht die Installation trotzdem. 

Ev. ein Composer Client problem? 

/cc @discordier

**Comment by discordier** [comment]
Kann sein, seh ich mir naechste Woche mal an.

**Comment by Fuzzyma** [comment]
Das gleiche gilt auch für den Extension-Manager. Dort kann man maximal Version 2.2.6 installieren.
2.3 taucht nirgends auf. (Ich habe Contao 3.5.2)

**Comment by aschempp** [comment]
Das kann nur ein Cache-Problem sein. Einfach oben auf «Installieren» klicken und dann Isotope auswählen. Dann wird die 2.3 erscheinen.

**Comment by Fuzzyma** [comment]
Jo hast Recht. Wenn man einfach isotope nochmal installiert (oder so tut) wird die 2.3 korrekt angezeigt und wenn man die dann installieren will kommt der update-screen. Funzt - danke!

**Comment by aschempp** [comment]
@discordier hattest du zufällig schon Zeit dafür gefunden?

**Comment by aschempp** [comment]
*bump*

**Comment by discordier** [comment]
Kann ich einfach nicht reproduzieren, bei mir sind alle 2.3er Versionen, inkl. betas als kompatibel gelistet.
Ist zwar ne C3.5.3, aber sollte doch dasselbe Problem haben
