### ISSUE TITLE
[2.3.0 stable] | Attribute (Mehrfach-Auswahl) werden im Frontend als ID ausgegeben

### ISSUE THREAD

**Issue by JohnnyWe** [isotope/core#1521]
Contao: 3.5.2
Isotope: 2.3.0 stable

Neuinstallation

Fehler:
Wenn einem Produkt mehrere Attribut-Optionen (Attribute -> Mehrfach-Auswahl) zugewiesen werden, werden im Frontend die IDs Komma-getrennt ausgeben.

Template: <?php echo $this->generateAttribute('Datenbank-Feld'); ?>

**Comment by aschempp** [comment]
Fixed in 03b743eb55853b6040f52698a0b2148ea67e7888
