### ISSUE TITLE
Address.php - Straße wird mit <br> getrennt

### ISSUE THREAD

**Issue by Fuzzyma** [isotope/core#1522]
In dem [Address-Model](https://github.com/isotope/core/blob/4339248354bca213b9bdf96abc567156eb1414ec/system/modules/isotope/library/Isotope/Model/Address.php#L222) wird die Straße aus `street_1`, `street_2`, `street_3` zusammengebaut indem einfach ein `<br>` dazwischen gepackt wird.
Designtechnisch ist das schwrierig weil man ein `<br>` nur mit `display:none` wieder weg bekommt.
Besser wäre es doch alle 3 parts in eigene spans zu packen.

Also statt

```javascript
$street = implode(($objPage->outputFormat == 'html' ? '<br>' : '<br />'), array_filter(array($this->street_1, $this->street_2, $this->street_3)));
```

einfach

```javascript
$street = '<span class="street_1">'.$this->street_1.'</span><span class="street_2">'.$this->street_2.'</span><span class="street_3">'.$this->street_3.'</span>';
```

Oder?

**Comment by aschempp** [comment]
Ein <span> würde (standardmässig) nicht zu einem Zeilenumbruch führen, hätte also nicht denselben Effekt. 
Du kannst das <br> übrigens per CSS einfach mit display:none belegen. Allerdings seh ich nicht warum man sowas wollte…?

**Comment by Fuzzyma** [comment]
nun gut - aus dem span ein div zu machen wäre jetzt ja kein Ding.

Es werden wohl viele Leute den Straßennamen ins erste und die Nummer ins zweite Feld eintragen.
Dazwischen ein Umbruch sieht eher blöd aus.
Abgesehen davon sollte man doch den User entscheiden lassen wie er es gerne hätte. Schließlich hat man auf alle anderen Elemente auch pingelig Zugriff. Warum nicht auf die Straßen-"Anteile"?

`display:none` habe ich oben auch schon erwähnt - da endet man dann mit sowas wie:
```css
br:first-child{
  display:none;
}
```

Sehr elegant...

**Comment by aschempp** [comment]
Sorry, aber in diesem Fall ist die Verwendung falsch. Wenn dein Besucher bei Postleitzahl seine Telefonnr. eingibt, können wir ihm auch nicht helfen… Vielleicht solltest du das zweite Strassen-Feld gar nicht anzeigen…

PS: Das Markup basiert auf dem [h-card](http://microformats.org/wiki/h-card) Standard, deshalb lässt sich das nicht einfach so ändern.

**Comment by Fuzzyma** [comment]
Wer redet denn von Telefonnummer?
Schonmal was von einer Hausnummer gehört?

**Comment by aschempp** [comment]
Ich meinte das als Beispiel. Wenn die Felder falsch ausgefüllt sind, können wir auch nicht helfen…

**Comment by albirs** [comment]
Gerne würden wir Straße und Hausnummer in **getrennten Feldern erfassen** aber im Frontend auf einer Zeile ausgeben.
Ein display: none für das `<br>` funktioniert dabei nur bedingt (da ohne Abstand zwischen den Teilen) und selbst mit [dieser](https://timonweb.com/css/how-replace-line-break-tags-br-spaces-css/) Lösung nur im Chrome aber nicht im Firefox. 

Wäre eine Mischung aus beiden Varianten `<span class="...">` und `<br>` denkbar? Dies würde die Ausgabe im Frontend nicht verändern, man hätte aber die Möglichkeit über CSS das <br> auszublenden und einen Abstand (oder was auch immer) zwischen die `<span>` -Tags einzubauen.

Würden zusätzliche `<span>` -Tags innerhalb des `<div class="street-address"></div>` das Markup von h-card verändern?
