### ISSUE TITLE
FatalError: Bestelldetails, Template im Backend nicht gefunden wenn geändert

### ISSUE THREAD

**Issue by Fuzzyma** [isotope/core#1523]
Geht man im Backend auf Bestellungen und sieht sich die Details einer beliebigen Bestellung an, gibt es einen **FatalError** wenn man im Bestellungsdetails-Modul ein anderes Template als das (überschriebene) Standardtemplate auswählt hat.

Stacktrace:
```
Fatal error: Uncaught exception Exception with message Could not find template "iso_collection_bestelldetails" thrown in D:\Repositories\apoident\system\modules\core\library\Contao\TemplateLoader.php on line 123

#0  C:\webroot\system\modules\core\library\Contao\Controller.php(76): Contao\TemplateLoader::getPath('iso_collection_...', 'html5')
#1  C:\webroot\system\modules\isotope\library\Isotope\Template.php(61): Contao\Controller::getTemplate('iso_collection_...', 'html5')
#2  C:\webroot\system\modules\core\library\Contao\BaseTemplate.php(81): Isotope\Template::getTemplate('iso_collection_...', 'html5')
#3  C:\webroot\system\modules\core\library\Contao\Template.php(277): Contao\BaseTemplate->parse()
#4  C:\webroot\system\modules\core\classes\FrontendTemplate.php(46): Contao\Template->parse()
#5  C:\webroot\system\modules\isotope\library\Isotope\Module\OrderDetails.php(109): Contao\FrontendTemplate->parse()
#6  C:\webroot\system\modules\core\modules\Module.php(282): Isotope\Module\OrderDetails->compile()
#7  C:\webroot\system\modules\isotope\library\Isotope\Module\Module.php(112): Contao\Module->generate()
#8  C:\webroot\system\modules\isotope\library\Isotope\Module\OrderDetails.php(68): Isotope\Module\Module->generate()
#9  C:\webroot\system\modules\isotope\library\Isotope\Backend\ProductCollection\Callback.php(98): Isotope\Module\OrderDetails->generate(true)
#10 C:\webroot\system\modules\core\classes\DataContainer.php(221): Isotope\Backend\ProductCollection\Callback->generateOrderDetails(Object(Contao\DC_Table), '')
#11 C:\webroot\system\modules\core\drivers\DC_Table.php(1907): Contao\DataContainer->row('{status_legend}...')
#12 C:\webroot\system\modules\core\classes\Backend.php(639): Contao\DC_Table->edit()
#13 C:\webroot\system\modules\core\controllers\BackendMain.php(131): Contao\Backend->getBackendModule('iso_orders')
#14 C:\webroot\contao\main.php(20): Contao\BackendMain->run()
#15 {main}
```

**Comment by Toflar** [comment]
Hast du den Fehler denn gelesen? Das sollte helfen. Dein Template muss an den richtigen Ort.

**Comment by Fuzzyma** [comment]
Der richtige Ort für ein Template ist meines Wissens ein Template-Ordner den man im Seitenlayout einstellt. Da wo auch alle anderen Templates liegen, die ich überschrieben habe.

In welchem Ordner sucht denn der bitte?

**Comment by Toflar** [comment]
Das Backend kennt aber kein Seitenlayout und auch kein Theme. Es muss direkt in `/templates` liegen.

**Comment by Fuzzyma** [comment]
Ich habe ja auch dieses Template nicht für das Backend ausgewählt sondern für mein Modul.
Warum benutzt denn Isotope das Modul, dass ich im Frontend einbinde auch im Backend?
Das kann doch so nicht gewollt sein

**Comment by Toflar** [comment]
Doch, so ist es im Moment.

**Comment by Fuzzyma** [comment]
Und was genau macht Isotope, wenn dieses Modul überhaupt nicht definiert ist?

PS: Am Rande: Vielen Dank für die Lösung!

**Comment by Toflar** [comment]
Es werden keine Details ausgegeben :)

**Comment by Fuzzyma** [comment]
hm - das ist immerhin auf seine eigene Weise konsistent ^^ - und wenn ich das Modul 2x definiere? Vll will ich ja im Frontend ein anderes Template als im Backend.

Könnte man also durchaus mal als enhancement auf die Liste setzen :).

**Comment by Toflar** [comment]
Gibt's schon: https://github.com/isotope/core/issues/1189

**Comment by aschempp** [comment]
PS: es wird das erste Modul genommen das es gibt. Wenns keins gibt wird ein Virtuelles mit Standard-Config erstellt. Es wird also schon was ausgegeben.
