### ISSUE TITLE
Bestellabschluss funktioniert nicht mehr

### ISSUE THREAD

**Issue by cs1982** [isotope/core#1524]
Ich habe das Problem, dass sich mindestens seit dem Update auf Isotope 2.3.0 stable (mit Contao 3.5.2) Bestellungen nicht mehr abschließen kann. Einige vermutete Zusammenhänge mit dem Problem konnte ich zwischenzeitlich ausschließen.
Es gibt nach wie vor keine Fehlermeldung, es geht nur einfach nicht weiter.
Im Forum habe ich das Problem und meine bisherigen Erkenntnisse geschildert:
https://community.contao.org/de/showthread.php?59056-Bestellabschluss-nicht-m%F6glich-amp-Produkte-mit-Varianten-gehen-nicht-mehr

Ich hoffe, Ihr habt Ideen wie das einzuordnen ist. Es kann gut sein, dass das Problem vor dem Computer sitzt, es hat aber schon lange funktioniert

**Comment by cs1982** [comment]
Ich habe die Stelle endlich gefunden, mit der das Problem unmittelbar zusammenhängt. Es klemmt beim Zusammenspiel mit der Erweiterung Extended Checkboxes. Ich habe ein Ticket erstellt: https://github.com/christianbarkowsky/contao-extended-checkbox/issues/1

Gern kann ich das Problem direkt in meiner XAMPP-Umgebung zeigen. Ich mache das terminlich passend.

**Comment by baumisimon** [comment]
Ich habe auch das Problem, dass der Bestellprozess seit isotope 2.3.0 nicht mehr abgeschlossen werden kann (ECB habe ich nicht installiert). Bei Klick auf "Kostenpflichtig bestellen" wird einfach nur eine weiße Seite angezeigt.
In der error.log bekomme ich 3 PHP-Warnings:
> PHP Warning: Illegal offset type in isset or empty in /system/modules/core/library/Contao/System.php on line 158
> #0 /system/modules/core/library/Contao/System.php(158): __error(2, 'Illegal offset ...', '/homepages/23/d...', 158, Array)
> #1 /system/modules/isotope/library/Isotope/Module/Checkout.php(198): Contao\System::importStatic('Isotope\\Rules', Object(Isotope\Module\Checkout))
> #2 /system/modules/core/modules/Module.php(282): Isotope\Module\Checkout->compile()
> #3 /system/modules/isotope/library/Isotope/Module/Module.php(112): Contao\Module->generate()
> #4 /system/modules/isotope/library/Isotope/Module/Checkout.php(85): Isotope\Module\Module->generate()
> #5 /system/modules/core/elements/ContentModule.php(59): Isotope\Module\Checkout->generate()
> #6 /system/modules/core/library/Contao/Controller.php(476): Contao\ContentModule->generate()
> #7 /system/modules/core/modules/ModuleArticle.php(213): Contao\Controller::getContentElement(Object(Contao\ContentModel), 'main')
> #8 /system/modules/core/modules/Module.php(282): Contao\ModuleArticle->compile()
> #9 /system/modules/core/modules/ModuleArticle.php(67): Contao\Module->generate()
> #10 /system/modules/core/library/Contao/Controller.php(409): Contao\ModuleArticle->generate(false)
> #11 /system/modules/core/library/Contao/Controller.php(269): Contao\Controller::getArticle(Object(Contao\ArticleModel), false, false, 'main')
> #12 /system/modules/core/pages/PageRegular.php(133): Contao\Controller::getFrontendModule('0', 'main')
> #13 /system/modules/core/controllers/FrontendIndex.php(267): Contao\PageRegular->generate(Object(Contao\PageModel), true)
> #14 /index.php(20): Contao\FrontendIndex->run()
> #15 {main}
> 
> PHP Warning: Illegal offset type in /system/modules/core/library/Contao/System.php on line 160
> #0 /system/modules/core/library/Contao/System.php(160): __error(2, 'Illegal offset ...', '/homepages/23/d...', 160, Array)
> #1 /system/modules/isotope/library/Isotope/Module/Checkout.php(198): Contao\System::importStatic('Isotope\\Rules', Object(Isotope\Module\Checkout))
> #2 /system/modules/core/modules/Module.php(282): Isotope\Module\Checkout->compile()
> #3 /system/modules/isotope/library/Isotope/Module/Module.php(112): Contao\Module->generate()
> #4 /system/modules/isotope/library/Isotope/Module/Checkout.php(85): Isotope\Module\Module->generate()
> #5 /system/modules/core/elements/ContentModule.php(59): Isotope\Module\Checkout->generate()
> #6 /system/modules/core/library/Contao/Controller.php(476): Contao\ContentModule->generate()
> #7 /system/modules/core/modules/ModuleArticle.php(213): Contao\Controller::getContentElement(Object(Contao\ContentModel), 'main')
> #8 /system/modules/core/modules/Module.php(282): Contao\ModuleArticle->compile()
> #9 /system/modules/core/modules/ModuleArticle.php(67): Contao\Module->generate()
> #10 /system/modules/core/library/Contao/Controller.php(409): Contao\ModuleArticle->generate(false)
> #11 /system/modules/core/library/Contao/Controller.php(269): Contao\Controller::getArticle(Object(Contao\ArticleModel), false, false, 'main')
> #12 /system/modules/core/pages/PageRegular.php(133): Contao\Controller::getFrontendModule('0', 'main')
> #13 /system/modules/core/controllers/FrontendIndex.php(267): Contao\PageRegular->generate(Object(Contao\PageModel), true)
> #14 /index.php(20): Contao\FrontendIndex->run()
> #15 {main}
> 
> PHP Warning: Illegal offset type in /system/modules/core/library/Contao/System.php on line 163
> #0 /system/modules/core/library/Contao/System.php(163): __error(2, 'Illegal offset ...', '/homepages/23/d...', 163, Array)
> #1 /system/modules/isotope/library/Isotope/Module/Checkout.php(198): Contao\System::importStatic('Isotope\\Rules', Object(Isotope\Module\Checkout))
> #2 /system/modules/core/modules/Module.php(282): Isotope\Module\Checkout->compile()
> #3 /system/modules/isotope/library/Isotope/Module/Module.php(112): Contao\Module->generate()
> #4 /system/modules/isotope/library/Isotope/Module/Checkout.php(85): Isotope\Module\Module->generate()
> #5 /system/modules/core/elements/ContentModule.php(59): Isotope\Module\Checkout->generate()
> #6 /system/modules/core/library/Contao/Controller.php(476): Contao\ContentModule->generate()
> #7 /system/modules/core/modules/ModuleArticle.php(213): Contao\Controller::getContentElement(Object(Contao\ContentModel), 'main')
> #8 /system/modules/core/modules/Module.php(282): Contao\ModuleArticle->compile()
> #9 /system/modules/core/modules/ModuleArticle.php(67): Contao\Module->generate()
> #10 /system/modules/core/library/Contao/Controller.php(409): Contao\ModuleArticle->generate(false)
> #11 /system/modules/core/library/Contao/Controller.php(269): Contao\Controller::getArticle(Object(Contao\ArticleModel), false, false, 'main')
> #12 /system/modules/core/pages/PageRegular.php(133): Contao\Controller::getFrontendModule('0', 'main')
> #13 /system/modules/core/controllers/FrontendIndex.php(267): Contao\PageRegular->generate(Object(Contao\PageModel), true)
> #14 /index.php(20): Contao\FrontendIndex->run()
> #15 {main}
nach auskommentieren der Zeilen 196-206 der Checkout.php funktioniert die Bestellung wieder...

**Comment by aschempp** [comment]
Duplicate of https://github.com/isotope/core/issues/1520
