### ISSUE TITLE
 Attribut Download wird im Frontend nicht angezeigt

### ISSUE THREAD

**Issue by kissinger99** [isotope/core#1525]
Hallo,

wie kann ich ein Download-Attribut in das Produktleser-Template iso_list_default.html5 integrieren?

Bei der Nutzung von <?php echo $this->generateAttribute('InternerName'); ?> wie unter https://isotopeecommerce.org/de/hand...downloads.html beschrieben erfolgt leider keinerlei Ausgabe im Frontend. Zu Beginn meiner Tests mit Isotope 2.3 war der Download-Link sichtbar, dann war er plötzlich weg.

Viele Grüße

Rüdiger

**Comment by aschempp** [comment]
Die Ausgabe ist wie beschrieben korrekt. Ich habe es selber gerade nochmals probiert, und bei mir funktioniert es problemlos. Die Tatsache dass es kurz da war und dann wieder weg deutet auf einen Konfigurationsfehler (z.B. Download-Dateien gelöscht).

**Comment by kissinger99** [comment]
Hallo Andreas, 

	danke für die Antwort. 

	Die Dateien sind vorhanden. Ich habe Isotope in einem anderen Projekt
installiert und neu eingerichtet, das gleiche: das Download-Attribut 
wird nicht angezeigt. 

	Gibt es vielleicht irgendwo eine Einstellung (Produkte, Attribut,
Modul) welche man beachten muss? 

	Oder was kann ich tun um den Grund für die Nicht-Anzeige zu finden? 

	Wo im Code wird die Funktion "generateAttribute" definiert? 

	Vielen Dank! 

	Rüdiger Hössel 

	RH-Web-Service 

	-----Original-Nachricht----- 

	Betreff: Re: [core] Attribut Download wird im Frontend nicht
angezeigt (#1525) 

	Datum: Mon, 14 Sep 2015 08:50:31 +0200 

	Von: Andreas Schempp <notifications@github.com> 

	An: isotope/core <core@noreply.github.com> 

	Die Ausgabe ist wie beschrieben korrekt. Ich habe es selber gerade
nochmals probiert, und bei mir funktioniert es problemlos. Die
Tatsache dass es kurz da war und dann wieder weg deutet auf einen
Konfigurationsfehler (z.B. Download-Dateien gelöscht). 

	—
Reply to this email directly or view it on GitHub [1].

Links:
------
[1] https://github.com/isotope/core/issues/1525#issuecomment-139978287

**Comment by aschempp** [comment]
Fragen bitte in's Community-Forum stellen. Deine lässt sich allerdings auch mit einer Suchfunktion im Code lösen ;-)

**Comment by kissinger99** [comment]
Hallo Andreas, danke für Deine Hilfe.

Das Problem konnte gelöst werden, ist ein bug.

Siehe:

https://community.contao.org/de/showthread.php?59118-Attribut-Download-wird-im-Frontend-nicht-angezeigt&p=384124#post384124

Beste Grüße!

Rüdiger
