### ISSUE TITLE
Download Attribut (Radio) wird im FE nicht ausgegeben

### ISSUE THREAD

**Issue by Ma3xl3** [isotope/core#1527]
Wenn im BE ein Download Attribut mit dem Feld-Typ "Radio-Button" hinzugefügt wird, gibt es im FE keine Ausgabe mit  der generateAttribute Methode. Mit dem Typ  "Checkbox" funktioniert es.
```php
<?php echo $this->generateAttribute('preface_index'); ?>
```

Das Attribut im BE sieht wie folgt aus:
![image](https://cloud.githubusercontent.com/assets/1608186/9847324/6b5f609c-5ad8-11e5-95ac-e69447c9ba4d.png)

Das Problem liegt meiner Ansicht daran, dass im File system/modules/isotope/library/Isotope/Model/Attribute/Downloads.php in der Zeile 72 multiSRC ein Array sein müsste, beim Typ Radio jedoch nur ein String mitgegeben wird.
```php
$objContentModel->multiSRC = $objProduct->{$this->field_name};
```
In der Methode ContentDownloads (ab Zeile 57) ist folgende Abfrage:
```php
		// Return if there are no files
		if (!is_array($this->multiSRC) || empty($this->multiSRC))
		{
			return '';
		}
```
Das wird der Grund sein weshalb kein Download ausgegeben wird.

Systemumgebung:
Contao 3.5.3
Isotope 2.3.0

**Comment by aschempp** [comment]
Fixed in fa4e9913075a45ae06973b70226ecd613b1ddae9

**Comment by kissinger99** [comment]
Hallo!

Nach Update von Isotope 2.3 auf 2.3.1 erhalte ich anstelle des Download-Links im Frontend folgende Meldung:

Dieses Element verwendet noch das alte Contao 2 SRC-Format. Haben Sie die Datenbank aktualisiert?

Was ist da zu tun?

Danke!

**Comment by aschempp** [comment]
Probier mal das Produkt zu bearbeiten und neu zu speichern.

**Comment by kissinger99** [comment]
Habe ich gemacht,Fehlermeldung bleibt. Datenbank ist aber aktuell.

**Comment by kissinger99** [comment]
Hier ein Link: http://extru.clever-house.de/de/display-und-klemmprofile/klemmprofil-ph-h-1.html

**Comment by kissinger99** [comment]
Hallo!

Ich habe jetzt folgendes versucht: In den Attribut-einstellungen habe ich von checkbox auf Radiobutton umgestellt.

Dann das Produkt editiert und eine PDF-Datei eingetragen.

Nun erscheint wieder der Download-Link.

**Comment by Ainschy** [comment]
Ich habe das Problem, das ich die Auswahl Checkbox, weil mehrere Dateien zum Download, nicht mehr nutzen kann. Die Dateien befinden sich im files Ordner unter Contao. Der Fehler trat erst nach dem Update auf isotope 2.3. auf.

Contao 3.5.4. und isotope 2.3.1 sind im Einsatz.

Ich nutze das Download Attribut um Produkt Informationen in der Detail Ansicht anzubieten. Ich nutze es nicht als Download Artikel.

**Comment by aschempp** [comment]
Dieses Ticket ist schon geschlossen, bitte ggf. ein neues erstellen. Das Problem dürfte aber in https://github.com/isotope/core/commit/08322eaf3a242b2f2d5a05ec0a7cbc0e46ac251f bereits behoben sein.

**Comment by Ainschy** [comment]
Danke werde ich prüfen und ggf. ein neues Ticket erstellen.
