### ISSUE TITLE
Feature Request: Konfiguration Mitgliedergruppen zuweisen

### ISSUE THREAD

**Issue by hubbd** [isotope/core#1531]
Falls ich es richtig verstehe ist es aktuell so:
Für jeden Gast oder eingeloggtes Mitglied gilt die Shopkonfiguration, die als Standard markiert ist.
Eine andere Konfiguration kann nur über den "Shopkonfigurations-Wechsler" erreicht werden.
Soweit richtig?
Ich fände es gut, wenn es eine Einstellungsoption gäbe in den Eigenschaften einer Mitgliedergruppe über die man einer Mitgliedergruppe eine von der Standardkonfiguration abweichende Shopkonfiguration zuweisen kann.
Damit würde lästige Workarounds (z.B. Weiterleiten bei Anmeldung zu ...?config=2) entfallen.

Apropos: Was ist denn aktuell "Best Practice" um das gewünschte Ergebnis zu erreichen?

**Comment by aschempp** [comment]
Welchen Unterschied haben denn die Shop-Configs bei dir, dass die für Mitgliedergruppen unterschiedlich sind?

**Comment by hubbd** [comment]
Konkretes Beispiel: B2B und B2C

Es wäre schön das über einen Login hinzubekommen:

Wenn sich jemand aus Mitgliedergruppen "Fachhandel" einloggt, gilt Shopkonfiguration B2B, bei "Verbraucher" B2C und später vielleicht bei "Großhandel" oder "Ausland" oder "Zertifizierter Händler"... jeweils eine angepasste Shopkonfiguration.

Die unterscheiden sich z.B. durch Preisauszeichnung, Preisstaffelung, Angebotsumfang, Nummernkreise, ...

Aber vielleicht stehe ich ja auch auf dem Schlauch. Was wäre denn "Best Practice für B2B UND B2C in Isotope"?

**Comment by aschempp** [comment]
Zwei Domains/Subdomains?

**Comment by aschempp** [comment]
Closing this in favor of #1597
