### ISSUE TITLE
Produkt Typ als CSS-Klasse in die einzelnen Produkte aufnehmen

### ISSUE THREAD

**Issue by Benjaminscherf** [isotope/core#1532]
Es währe sehr Hilfreich, wenn der Produkt-Typ als CSS Klasse in den einzelnen Artikel mit aufgenommen wird. So ist es möglich den einzelnen Artikel auch innerhalb seiner normalen Kategorie-Liste auszuweisen, wenn eine Kategorie-Liste Artikel mehrere Produkt-Typen enthält.  Z.B. für Ausverkaufsaktionen einzelner Artikel.

Beste Grüße

**Comment by aschempp** [comment]
Am sinnvollsten wäre wohl ein Eingabefeld für eine CSS-Klasse im Produkttyp.
