### ISSUE TITLE
[2.2.6] Bug in token ##collection_locked#

### ISSUE THREAD

**Issue by xantippe** [isotope/core#1533]
der simple token ##collection_locked## wird ersetzt z.B. zu ```<4431Wed, 05 Aug 2015 22:37:44 +02002015810>05pm31Europe/Berlin``` und nicht zu einem Timestamp

Isotope 2.2.6

**Comment by aschempp** [comment]
Isotope  2.2.6 wird nicht mehr unterstützt. Bitte versuche es in Isotope 2.3 nochmals.

**Comment by xantippe** [comment]
habe z.Z. (noch) kein 2.3 - wenn sich an der Stelle nix geändert hat, dürfte der Bug auch noch bestehen ;-)

**Comment by aschempp** [comment]
Duplicate of #1539
