### ISSUE TITLE
Module should be in Order-Hooks

### ISSUE THREAD

**Issue by Defcon0** [isotope/core#1534]
Hello,

I just wrote some hook implementations and ended up using only the preCheckout hook since this is the only one passing in the checkout module.

It would be really neat if one could use the module in all order-specific hooks. Currently there's no way to get the module in this hooks besides saving its id in the session and reading it in the second hook.

Would that be possible?

Bye Defcon0

**Comment by aschempp** [comment]
The checkout is not necessarily done in the frontend module. Imagine creating an order in the backend…

**Comment by Defcon0** [comment]
OK, then the only way to get the module id is saving it to the session in preCheckout, right?

It's just a little unintuitive that the preCheckout hook contains a module and the postCheckout doesn't.

**Comment by aschempp** [comment]
You should store the necessary data in the order, for example using the preCheckout hook. I would not suggest to store the module ID because you don't know if the frontend module changes.
