### ISSUE TITLE
Use last address as default

### ISSUE THREAD

**Issue by Fuzzyma** [isotope/core#1537]
Is it possible to define the last used address as default address?

Also: In my opinion the intended behaviour should be to select the first given address when noone is set as default because the user will most likely choose this instead of a new address.
In my installation the fields for new address are always open even when an address is present.

Is this a bug or a feature?
Any Idea how to accomplish this?

**Comment by aschempp** [comment]
There are two options to control this. 

1: enable "save in address book" in the check out module

2: enable "set as default billing addess" or "set as default shipping address" in the shop configuration

**Comment by Fuzzyma** [comment]
Thanks for the fast reply.
Option 1 is already active but I cant figure out where to set option 2.
Btw: Iam using Isotope 2.3.0 - maybe somthing already changed

**Comment by aschempp** [comment]
Option two is set for the addesses in the shop configuration.

**Comment by Fuzzyma** [comment]
You mean you have to mark one address as default billing address?
Well - why I have to choose a default billing address to achieve this? It should be teh first address marked (or the last used) when no default is given.
Adding a new address is more or less the edge case which will not happen that often.
Also you cant mark one address as default in the frontend-module (addressbook)

**Comment by aschempp** [comment]
If there is no default address, the input fields will be shown. I can't see a problem with that…?

> Also you cant mark one address as default in the frontend-module (addressbook)

You sure can, if the appropriate field is shown (module configuration) ;-)
