### ISSUE TITLE
Multiple choice attributes - it does not work properly

### ISSUE THREAD

**Issue by 100Perski** [isotope/core#1538]
Sorry for my english in advance.
Applies "Drop-down menu" and "list checkbox".
By ticking for 1 product, 2 or more attribute BE options, this product is not published in the FE when the filter you choose any of these options. It only works when you activate the BE only one option. In the BE department properly for all listed cases.

**Comment by aschempp** [comment]
Do you use the regular filter or the cumulative filter module?

**Comment by 100Perski** [comment]
Regular filter

**Comment by aschempp** [comment]
Also see https://community.contao.org/de/showthread.php?60397-Problem-ISOTOPE-Filter&p=393072
