### ISSUE TITLE
Inserttag "formatted_datetime" gibt nur teilweise Bestelldatum aus

### ISSUE THREAD

**Issue by connine** [isotope/core#1539]
In Benachrichtigungen wird unter Nutzung des Inserttags "formatted_datetime" das Bestelldatum zum Teil nicht ausgegeben. Das Problem scheint abhängig von der Bezahlmethode zu sein. 

Folgender Text steht in der Benachrichtigung im BE
```
Datum: 
{{formatted_datetime::##collection_locked##::d.m.Y}}
##collection_locked##
```

Werden Produkte über die Zahlungsmodalität "Cash" bezahlt, steht in der E-Mail z.B.

```
Datum: 
22.09.2015
1442919698
```

Werden Produkte über Paypal bezahlt, steht in der E-Mail 

```
Datum:  

1442992835
```

Isotope 2.2.5
Notification Center 1.3.0

**Comment by connine** [comment]
Ich habe gerade die gleiche Beobachtung bei einem anderen Shop gemacht:
Contao 3.3.7
Isotope: 2.2.0

Auch hier wird Paypal genutzt, allerdings im Zusammenhang mit Payone als Zahlungsanbieter.

**Comment by aschempp** [comment]
Das macht irgendwie überhaupt keinen Sinn… kannst du das bitte mal mit Isotope 2.3 testen? Version 2.2 wird nicht mehr unterstützt, und ein Update sollte keine Auswirkungen haben.

**Comment by connine** [comment]
Ja ich weiß, das klingt bisschen merkwürdig. Leider kann ich das zu Zeit nicht mit der neuen Version testen, da ich dafür auch von Contao ein Update machen müsste. Das ist ist zeitlich grad nicht drin.

Bei Paypal-Zahlungen habe ich aber außerdem noch bemerkt, dass ein weiterer Inserttag nicht funktioniert. Die Kontaktadresse am Ende einer E-Mail lasse ich durch 
```
{{custom::shop_mail_fussnote}}
```
ausgeben (eigener Inserttag aus der Erweiterung inserttags Version 1.9.2.9008).

Bei E-Mails an Kunden, die auf Rechnung bezahlt haben (Zahlungsmodalität Cash) wird der Inserttag korrekt ersetzt, bei Kunden mit Paypal-Zahlung nicht... sprich der Text fehlt dann.

**Comment by aschempp** [comment]
Ich weis warum :-(
https://github.com/isotope/core/blob/master/system/modules/isotope/postsale.php#L66-L67

**Comment by connine** [comment]
Kurze Frage noch dazu: ich nutze auch den Hook generateDocumentNumber. Allerdings scheint der bei Paypal-Zahlungen auch nicht ausgeführt zu werden. Kann das sein? Dieser Hook ist doch eigentlich bei $GLOBALS['ISO_HOOKS'] drin und nicht 'TL_HOOKS'

**Comment by aschempp** [comment]
We need to revert the changes from https://github.com/isotope/core/commit/bbc6b73ee0480ef93c0e5a1b1d1eba8f39e0b13c. We can only do that in the beta version of 2.4 because we're not sure about the side effects.

**Comment by aschempp** [comment]
Should be fixed in 8e99f3f4eacc038699b014a9e3fd9017ede1e3e0. Please test the latest develop branch.
