### ISSUE TITLE
Shipping Calculator doesn't work when using second flat-price in shipping group

### ISSUE THREAD

**Issue by cs1982** [isotope/core#1541]
I defined an shipping group like shown in the attached image. Shipping Costs are determinend by weight. The checkout module calculates right. The Shipping Calculator shows "Leider können die Produkte zur Zeit nicht in Ihr Land geliefert werden. Bitte wählen Sie eine andere Versand-Adresse oder nur Artikel die nicht versendet werden müssen (z. B. Download-Artikel)." when achiving the second weight-area.

![isotope_versandkostengewicht](https://cloud.githubusercontent.com/assets/3968448/10119248/978591b6-6490-11e5-9a6a-32308c9f1c56.PNG)

I'm using Isotope 3.5.1 with Contao 3.5.3.

**Comment by aschempp** [comment]
Did you also set up the cart address module? Because by default the cart does not have a shipping address for guests, which means they likely can't be shipped.

**Comment by aschempp** [comment]
I'm closing this as invalid as its likely a misconfiguration and further information is missing. Feel free to reopen if you have more info.
