### ISSUE TITLE
Varianten Standard-Option funktioniert nicht

### ISSUE THREAD

**Issue by Wagnerwagner** [isotope/core#1546]
Man kann bei Attributen festlegen welche Option standardmäßig ausgewählt werden soll. Für normale Attribute schein das auch zu funktionieren. Verwendet man ein Attribut aber zum erstellen von Produktvarianten funktioniert dies nicht mehr, was problematisch ist, da zwar die Auswahl (egal ob Checkbox, Radiobutton oder Select) noch die Standardauswahl verwendet. das Produkt im Produktleser aber leider nicht auf die Variante Vorausgewählt wird. Ausserdem kann man so nicht mehr Steuern welche Produktvariante als Standard angezeigt wird. Bsp.
Von einem Produkt gibt es 2 Varianten, Das Produkt selber für Preis x und ein Muster für Preis y<x. Man möchte natürlich, dass die Kunden das Produkt so einfach wie möglich bestellen können und nicht das Muster.

**Comment by aschempp** [comment]
Eine bestimmte Variante standardmässig auszuwählen geht in Isotope bisher nicht. Das Dropdown sollte aber immer auf leer stehen (gemäss deiner Aussage ist da aktuell ein Bug).

**Comment by aschempp** [comment]
Fixed in 3ac89edc55dfbeb150255f0bdeca398845f5afdd
