### ISSUE TITLE
[2.3.1] Regeln und Gutscheine weg

### ISSUE THREAD

**Issue by thescrat** [isotope/core#1547]
Hi,

leider wird im Warenkorb das Template iso_coupons nicht mehr gerendert.

Forum:
https://community.contao.org/de/showthread.php?59471-Gutscheine-und-Regeln-f%FCr-Isotope-2-3-1

**Comment by Ainschy** [comment]
Schau doch mal ob deine Regeln richtig greifen. 
Bei mir hatte ich bei Produkt-Einschränkungen -> Kategorie -> die Eltern-Kategorie meiner Produkte ausgewählt. Was zu keinem Erfolg führte.

Erst als ich die Kategorie/Ordner der Produkte selbst auswählte wurde die Regel beachtet.

Vielleicht hilft das bei der Fehlersuche.

**Comment by Toflar** [comment]
Hab's grad mit Oli angeschaut und es läuft alles einwandfrei. Hat also nichts mit dem Template zu tun.

**Comment by Ainschy** [comment]
Nach weiteren Tests stellte sich heraus, das das Enddatum nicht ausgewertet wird. Trägt man eine Zeit im Feld Endzeit ein, so wird diese Auswertung auf das aktuelle Datum durchgeführt.

Getestet mit isotope 2.3.1 unter Contao 3.5.4

**Comment by aschempp** [comment]
Hast du beim Datum etwas eingetragen? Es ist korrekt dass die Zeit auf den aktuellen Tag ausgewertet wird, wenn kein Datum vorhanden ist.

**Comment by Ainschy** [comment]
So langsam scheint mir die Einstellung für das Startdatum und Enddatum sowie die Startzeit und Endzeit klar zu werden.

Ich glaubte es sei wie bei der Event Verwaltung unter Contao: Startdatum + Startzeit bis Enddatum + Endzeit. = Spanne der Gültigkeit.

Aber es ist dann doch ganz anderes:
Im Zeitraum von Startdatum bis Enddatum in der Zeit zwischen Startzeit und Endzeit. sprich täglich zwischen Startzeit und Endzeit von Startdatum bis Enddatum.
So ergibt die Funktion einen Sinn.

Sinnvoll wäre es hier eine Unterscheidung machen zu können.

**Comment by aschempp** [comment]
siehe https://github.com/isotope/core/issues/1399 :9

**Comment by thescrat** [comment]
@aschempp Das Hauptproblem dieses Tickets ist gelöst. Es war kein Bug. Im Templateverzeichnis lag eine mod_iso_cart ohne "$this->custom" und daher wurden die Gutscheine nicht gerendert.

Ein Problem mit dem Datum/Zeit konnte ich nicht feststellen.

**Comment by aschempp** [comment]
danke für die Info

**Comment by Ainschy** [comment]
Dann sollte die Funktionsweise ins Handbuch aufgenommen werden ;-)

**Comment by aschempp** [comment]
https://isotopeecommerce.org/de/handbuch-schreiben.html

**Comment by Toflar** [comment]
Ist drin: https://isotopeecommerce.org/de/handbuch/v/2.3/r/regeln_produkt.html#deeplink-datum-zeit-einschraenkungen
