### ISSUE TITLE
Error nach "kostenpflichtig bestellen"

### ISSUE THREAD

**Issue by laRocca** [isotope/core#1549]
Fatal error: Call to undefined method Isotope\Rules::deleteRuleUsages() in /var/www/vhosts/reindesign.eu/shop2/system/modules/isotope/library/Isotope/Model/ProductCollection.php on line 568

-> nach "aktualisieren" im Browser ist die Bestellzusammenfassung zu sehen und die Bestellung geht ganz normal durch ins System…

**Comment by aschempp** [comment]
welche Version verwendest du?

**Comment by laRocca** [comment]
Version 2.2.6

**Comment by aschempp** [comment]
Die Funktion ist bei mir vorhanden, das scheint ein Problem auf deinem System zu sein. Die Version 2.2 wird ausserdem nicht mehr unterstützt, du solltest auf die 2.3 aktualisieren.
