### ISSUE TITLE
Shop config should also be assignable to a non-root page

### ISSUE THREAD

**Issue by Defcon0** [isotope/core#1550]
Hello folks,

in our current project using isotope we are facing the issue that different shop configs should be used on the same domain (i.e. under the same root).

Would it be possible to add an option to override the root shop config with one in a sub page of the root? Isotope::getConfig() should then check for a shop config set in the current page. If none is set, use the root config and so on. Of course, this only affects the frontend.

**Comment by aschempp** [comment]
Shop configs are not really intended for that. Can you explain the use case?

**Comment by Defcon0** [comment]
In our module contao-isotope_plus we added some stock functionality. It's a first draft so production use wouldn't be a good idea at the moment :)

We added a flag to validate the stock in the shop config, in the product type and in the product. In addition you can override the global (root) config in the current page. The priority is as follows:

root config
page config
product type
product

The reason for this stuff is a requirement stating that one product on some page is stock-validated and in another one, it's simply not.

Maybe, there's a better way to do that in Isotope, but this one works at the moment.

**Comment by aschempp** [comment]
That does not make sense to me at all, why would a product that is in stock not be validated on some pages? Why not simply create a different product if that's really the case?

**Comment by Defcon0** [comment]
At first, this also had been my thoughts :) The reason is, that one time the product is sold in public, the other time b2b in a restricted area on the website. Public users order small quantities, b2b users order large ones (also in sets which is another thing I need to configure on a page level).

Of course, you could do that with multiple products, but this makes stock statistics and order management more complicated (because in reality, the products just don't differ). In addition, this affects hundreds of products. It would be a large overhead to duplicate every single product just for some other validation config.

**Comment by aschempp** [comment]
That's an interesting use case. But it would mean you can't set the stock handling per product, right? Otherwise it would always override the shop config / page settings ?

**Comment by Defcon0** [comment]
You're totally right. But this behavior is intended, indeed :) The developer should have the opportunity to set the property rather globally or specifically to a certain product. Overriding should also be possible since it's always a matter of proportions. If you have 100 products in a product type and only one should be validated against the stock, it's a good idea to set "skipStockValidation" in the product type and override it in just the one product instead of setting it in 99 products separately :)

With the global shop config and the per page config it's just the same. But I'm not too deep into Isotope yet to say if such a per page handling would case side effects since the shop config is also linked to the cart.

**Comment by aschempp** [comment]
That's exactly the problem. Currently you can have only one config per root page. Imagine a different config with different currency, that can't work with the cart.

Maybe your problem can simply be fixed by using a subdomain for the B2B shop?

**Comment by Defcon0** [comment]
In our case this is simply not expressive enough. Setting it domain wide is too general, since there's different validation handling on one single domain :-(

**Comment by aschempp** [comment]
I would suggest to move the general configuration outside of the shop config. Into something like a stock handling config. And then assign it per page. Unfortunately we can't implement shop config per pages as we just figured out together…

**Comment by Defcon0** [comment]
OK, but thanks for discussing the issue :)!
