### ISSUE TITLE
Versandkosten mit deaktivierten CheckoutStep

### ISSUE THREAD

**Issue by Fuzzyma** [isotope/core#1553]
Wenn man den Checkoutstep für die Vesandkosten deaktiviert, werden die Versandkosten (auch wenn welche eingerichtet sind) nicht angerechnet.

Wenn eine Versandart angelegt ist und diese auch aktiviert ist, sollte diese auch auf dem Preis draufgeschlagen werden egal ob diese nun explizit ausgewählt wurde oder nicht.

**Comment by aschempp** [comment]
Wenn der Schritt deaktiviert wird, wird die komplette Versandbehandlung deaktiviert. Sonst müsstest du selber einen neuen Schritt programmieren…

**Comment by Fuzzyma** [comment]
warum sollte man eine Versandkosten Art _auswählen_ können wenn es nur eine gibt?

**Comment by aschempp** [comment]
Man muss sie nicht auswählen, sondern bestätigen ;-)

**Comment by Fuzzyma** [comment]
ja schon klar ...
