### ISSUE TITLE
[2.3.1] Shops mit 2 ShopID's nicht möglich

### ISSUE THREAD

**Issue by ae69** [isotope/core#1556]
Habe eine Homepage mit ISOTOPE 2.2.6 erstellt und zwei Shops konfiguriert (ein Shop und einen Catalog sprich-> Shop ohne Preise zum Anfordern von Unterlagen).
Man konnte sowohl Unterlagen anfordern als auch im Shop bestellen.
**Nach dem Update** erscheint beim "In den Warenkorb" ein Fatal Fehler beim Versuch im jeweils anderen Shop etwas in den Warenkorb zu legen

**Fatal error: Uncaught exception Exception with message Query error: Duplicate entry 'cebb8fae50e75b13628594b778541a68d2da7e7f' for key 'uniqid' (INSERT INTO tl_iso_product_collection (type, uniqid, tstamp, member, config_id, store_id) VALUES ('cart', 'cebb8fae50e75b13628594b778541a68d2da7e7f', 1444988322, 0, '2', 1)) thrown in Z:\xampp\htdocs\system\modules\core\library\Contao\Database\Statement.php on line 295**

Habe nun gesehen, in der Datenbank wird mit "tl_iso_product_collection.php" ein Unique-Key angelegt
```
     'sql' => array
        (
            'keys' => array
            (
                'id'                        => 'primary',
                'uniqid'                    => 'unique',
                'member,store_id,type'      => 'index',
                'uniqid,store_id,type'      => 'index',
                'source_collection_id,type' => 'index',
            ),
```
daher können zwei Datensätze mit "Cart" nicht angelegt werden.
Habe den UniqueKey uniqid gelöscht, und jetzt funktioniert die Homepage wieder.

Bitte um Überprüfung, da ich natürlich jetzt nicht wissen kann welche Fehler ich mir dadurch wieder eingebaut habe :-(
Danke schön und liebe Grüsse aus Wien
PS. Sonst ist ISOTOPE wirklich super Danke

**Comment by aschempp** [comment]
Mach bitte erst mal ein Update, die 2.2 wird nicht mehr unterstützt.

**Comment by ae69** [comment]
Ich habe ja auf 2.3.1 upgedatet,das Problem tritt ja erst mit der Version auf !!!

**Comment by ae69** [comment]
Die Ändeung mit dem unique key wurde hier durchgeführt:
https://github.com/isotope/core/commit/b3816267d52ddad65a331f7e04d7b4426f94eba6

**Comment by aschempp** [comment]
Es sieht aus als wäre auf deinem System zwei mal derselbe zufällige 32-stellige Code generiert worden. Sehr unwahrscheinlich/unlogisch. Hast du Erweiterungen für Isotope installiert? Und kannst du die Datensätze aus phpMyAdmin mit dem Unique Key mal "fotografieren" ?

**Comment by ae69** [comment]
Hier liegt das Problem:
Gleiche uniqid unterschiedliche store_id

ISOTOPE_TEMP_CART=cebb8fae50e75b13628594b778541a68d2da7e7f;  ist natürlich gleich nur die store_id ist anders

Das war der Grund warum ich Isotope 2.2.6 ausführlich getestet habe um 2 Shops (1xCatalog ohne Preise und 1x Shop) zu verwenden.
Der Kunde kann aus dem Catalog Datenblätter anfordern und im Webshop was anderes bestellen!

![unique](https://cloud.githubusercontent.com/assets/8656733/10571946/0991e380-7644-11e5-87bb-3d5e11dec40a.PNG)

**Comment by aschempp** [comment]
Ok, ich glaube wenn man die Shop-Config wechselt könnte das tatsächlich zu einem Problem führen.

**Comment by aschempp** [comment]
Wie unterscheiden sich die beiden Shops? Verwendest du Subdomains?

**Comment by ae69** [comment]
Nein, ich verwende ein Shop als "Catalog->Produkte". das andere als echtes Shop.
Siehe  http://intranet.elsinger.at (nur als Test-Domain, wenn alles fertig ist dann auf elsinger.at)

**Comment by aschempp** [comment]
Wie kann der Shop dann mehrere Shop-IDs haben? Eine Shop-ID ist ja an eine Root-Seite gebunden und kann sich innerhalb einer Domain nicht ändern… ausser du hast da etwas von Hand programmiert?

**Comment by ae69** [comment]
Hier ein paar Bilder zum Verständnis

![shop1](https://cloud.githubusercontent.com/assets/8656733/11500767/87b2f6e8-982f-11e5-85d2-490456ddd9c3.PNG)
![shop2](https://cloud.githubusercontent.com/assets/8656733/11500774/8acf752c-982f-11e5-9679-54b8ff40a784.PNG)
![shop3](https://cloud.githubusercontent.com/assets/8656733/11500776/8d7670be-982f-11e5-9692-9f8ad1cf1124.PNG)

Hat auch alles bis zu derÄnderung mit dem uniquekey funktioniert:

![shop4](https://cloud.githubusercontent.com/assets/8656733/11500777/908ff6da-982f-11e5-8347-faa774d88d81.PNG)

**Comment by aschempp** [comment]
Ok. Zuerst: Du hast dein Contao falsch konfiguriert. Es ist nicht vorgesehen mehrere Root-Seiten ohne Domain zu haben. Aktuell funktioniert das, aber es ist "falsch".
Ich habe eine Lösung in 2.3.2 eingebaut, welche dafür sorgen sollte dass die Unique-IDs immer eindeutig sind. In deinem Fall wird das allerdings dazu führen dass beim Wechsel der Root-Seite der bestehenden Gast-Warenkorb verloren geht…

**Comment by ae69** [comment]
Herzlichen Dank, mit der Version 2.3.2 funktioniert die Sache wieder so wie vorher, dank Deiner Lösung. Beim Wechseln der Root-Seiten bleibt auch der Warenkorb erhalten.
Vielen Dank, ich dachte schon ich muß eine eigene Shop-Domain und eine Catalog-Domain aufbauen.
Schöne Grüsse aus Wien und ISOTOPE ist spitze.
