### ISSUE TITLE
Pass options to generateAttribute() to allow for raw options instead of <ul>

### ISSUE THREAD

**Issue by Toflar** [isotope/core#1558]
The template helper `generateAttribute()` should allow to pass an optional `noHtml` or so param for option attributes.

Right now when you have a multiple select and you go for `echo $this->generateAttribute('select_field')` it will output a `<ul>` formatted list. However, what if I want to display something else than the `<ul>` list with it?
Of course you can get the raw values using `$this->select_field` but you would need to call `deserialize()` in combination with haste utilities. So in the easiest case you have to write something like this:

```php
$options = deserialize($this->select_field, true);

foreach ($options as &$v) {
    $v = \Haste\Util\Format::dcaValue('tl_iso_product', 'select_field', $v);
}

// Output every value with it's label here now.
```

I'd prefer to have something like this;

```php
foreach ($this->generateAttribute('select_field', ['noHtml' => true]) {
     // Output every value with it's label here now.
}
```

This would make the template a whole lot more consistent.
Why `noHtml` and not `raw` or something else? Well, prepared labels are not `raw` either, right? The equivalent of `raw` would be `$this->select_field` but what I want is everything except for the automated html markup. So, `noHtml` but I'm open for input :-)

**Comment by aschempp** [comment]
Here are a few suggestions, what should we use?
 - `noHtml`
 - `raw`
 - `noList`

**Comment by Toflar** [comment]
I'd go for `noHtml` but would accept `noList` as well. Just not `raw`.

**Comment by Toflar** [comment]
Please reopen, the options should get their values, not just the labels.

If you use the options wizard and enter something like

Key | Label
------------ | -------------
key_1 | Label 1
key_2 | Label 2

The following code

```php
var_dump($this->generateAttribute('select_field', ['noHtml' => true]));
```

now produces this

```
array(2) { [0]=> string(7) "Label 1" [1]=> string(7) "Label 2" }
```

You only get the labels now, not the values anymore and you need to manually assign the label to the keys again.
To be more convenient, it should produce either this:

```
array(2) { ["key_1"]=> string(7) "Label 1" ["key_2"]=> string(7) "Label 2" }
```

or even this (to support more attributes and not only regular key->value):

```php
array(2) { [0]=> array(2) { ["key"]=> string(5) "key_1" ["label"]=> string(7) "Label 1" } [1]=> array(2) { ["key"]=> string(5) "key_2" ["label"]=> string(7) "Label 2" } }
```

**Comment by aschempp** [comment]
I have updated the code to correctly return key-value pairs
