### ISSUE TITLE
Product Category outside of the currently filtered site (category) in the Product List is not selectable

### ISSUE THREAD

**Issue by cs1982** [isotope/core#1560]
When using a category filter (site filter) in the Product List, it is impossible to select an other category (site) while editing a product. I'm not sure if it's a bug or a feature. In my opinion it should be possible to select an category outside the current filter.

**Comment by aschempp** [comment]
What module do you use? There is no category filter module?

**Comment by cs1982** [comment]
Ah, sorry. Beer an thinking doesn't fits.
I had the described issue on BE in the Product List.

**Comment by aschempp** [comment]
Can you post a screenshot?

**Comment by cs1982** [comment]
Here are the screen shots. Sorry for delay.
1. Page-Filter
![isotope_1](https://cloud.githubusercontent.com/assets/3968448/10896991/c2721756-81bd-11e5-8795-b223a9aeac80.PNG)
2. Shortend l
![isotope_2](https://cloud.githubusercontent.com/assets/3968448/10897021/fd12220c-81bd-11e5-8c9f-604c34f501b0.PNG)
ist in Category Picker

**Comment by aschempp** [comment]
I cannot reproduce this in latest Contao and Isotope. Please make sure you have the latest versions and try again. Let me know if the issue still exists.
