### ISSUE TITLE
Rules: Gutscheincode mit Gültig-Bis-Datum geht nicht

### ISSUE THREAD

**Issue by cs1982** [isotope/core#1562]
Ich nutze I 2.3.1 mit C 3.5.4 und einige Gutscheincodes (Rules). Beim Testen eines anderen Sachverhalts ist aufgefallen, dass Codes mit einem Gültig-Bis-Datum nicht eingelöst werden können. Konfiguriert war das Bis-Datum 31.12.2015, Zeit 23:59.
Als ich das Datum raus genommen habe, funktionierte es sofort.

Weitere Konfigdetails der Regel:
Regel: -12%
auf gesamten Warenkorbwert
Mindestbestellwert 20 €
max. Bestellwert 0 (unbeschränkt)
nur für Mitgliedsgruppe "Neukunden"
nur Einmalige Verwendung
keine Shop-Beschränkung (0)

**Comment by aschempp** [comment]
Ich kann dieses Problem nicht reproduzieren. Hast du ev. auch eine Startzeit gesetzt? Beachte dass Zeit und Datum unabhängige Werte sind (siehe auch https://github.com/isotope/core/issues/1399)

**Comment by cs1982** [comment]
Ich wünsche ein gesundes neues Jahr!
Entschuldigt die späte Rückmeldung. Zur Frage: nein, Startzeit und Endezeit sind leer, nur ein Startdatum ist gesetzt. Die angehängten Bilder zeigen die Konfig, wie sie im Einsatz ist und funktioniert.
![isotope_rule_config_1](https://cloud.githubusercontent.com/assets/3968448/12073656/776874a8-b129-11e5-8b8b-e1888a06405c.PNG)
![isotope_rule_config_2](https://cloud.githubusercontent.com/assets/3968448/12073657/7768c796-b129-11e5-802d-9225f4aadcfb.PNG)

**Comment by aschempp** [comment]
Ich kann das leider noch immer nicht reproduzieren. Falls du es bei dir nochmals nachstellen kannst, zeig mir bitte die Config welche **nicht** funktioniert. Ich schliesse das Ticket vorübergehend, sobald es neue Infos gibt können wir es gerne wieder öffnen.
