### ISSUE TITLE
Option Source Product

### ISSUE THREAD

**Issue by error08** [isotope/core#1563]
Bei der Verwendung der Option Source "Product" werden alle Optionen angezeigt,die dem Attributnamen zugeordnet sind und nicht die,die zu dem entsprechendem Produkt hinterlegt wurden. 
Dieses Verhalten tritt auf wenn bei einem Produkt keine Optionen hinterlegt wurden. 

Hier sollte m.M. das Attribut im Frontend komplett ausgeblendet werden,da es keine Option zu wählen gibt.

Teilweise werden auch alle Optionen zu einem Attribute über alle Produkte angezeigt,wenn zu einem Produkt eine Teilmenge derer hinterlegt wurde. Unter welchem konkreten Bedingungen das passiert konnte ich noch nicht sicher nachstellen.

Meines Erachtens sollten immer nur die zum Attribut und Produkt hinterlegten Optionen sichtbar sein wenn als Option Source "Produkt" eingestellt ist.

**Comment by aschempp** [comment]
Ein Attribut mit Option Source "Product" kann doch gar keine Option direkt im Attribut haben?

**Comment by error08** [comment]
Ich versuche es mal an einem Bsp. zu beschreiben:

Attribut "Textaufdruck" als Option Source = Produkt

Produkt 1 (Werte für Attribut Textaufdruck: Text1,Text2, Text3)
Produkt 2 (Werte für Attribut Textaufdruck: Text1, Text4, Text5)
Produkt 3 (Werte für Attribut Textaufdruck: Text2, Text4)
Produkt 4 (Werte für Attribut Textaufdruck: keine eingegeben)

Ich würde es nun gut finden, wenn das Attribut im Frostend nun nur bei Produkt 1-3 eingeblendet wäre, da Produkt 4 keine Werte zu dem Attribut hinterlegt hat.

Und als Fehlverhalten habe ich festgestellt, dass nach dem Hinzufügen eines ersten Produkt in den Warenkorb bei allen weiteren Produkten plötzlich alle Werte des Attributs über alle Produkte als Auswahl erscheinen (Bsp: für Produkt 2: Text1,Text2, Text3, Text1, Text4, Text5, Text2, Text4) 
Zudem auch wie im Bsp. mehrfach (Text1). Das einigste Produkt, bei dem diese Verhalten nicht aufritt ist das Produkt, das als erstes in den Warenkorb gelegt wurde. Hier passt die Auswahl nach wie vor.

**Comment by aschempp** [comment]
Aktuell ist es vorgesehen dass für ein Attribut immer Optionen vorhanden sein sollten. In deinem Fall solltest du zwei Produkttypen machen und dem zweiten das Feld *Textaufdruck* entfernen.

**Comment by aschempp** [comment]
Das Optionen-Problem muss ich mir aber ansehen :)

**Comment by error08** [comment]
Bis wann ist geplant die Version 2.3.3. freizugeben?

**Comment by aschempp** [comment]
Wir haben keinen festen Release-Plan, die Releases hängen von meiner Freizeit und Kundenaufträgen ab. Solltest du das dringend benötigen kann ich dir den [Isotope Circle](https://circle.isotopeecommerce.org) empfehlen.

**Comment by error08** [comment]
Mit dieser Änderung werden nun Attribute mit Quelle Option-Manager ( Definition am Produkttyp) unter gewissen Bedingungen nicht mehr angezeigt. An welchen Bedingungen dies liegt konnt ich noch nicht herausfinden

**Comment by error08** [comment]
Habe dieses Attribut gelöscht und neu angelegt, nun geht es... Komisch!

**Comment by tsarma** [comment]
This breaks checkbox attribute with single option for product setting. I have defined a checkbox field to mark some products and to filter these in my product listing module, which i can't do it now.

Also you are forced to check "Multiple selection" for the attribute, otherwise you can't save product because the field type in tl_product set as char(1) not blob.

**Comment by aschempp** [comment]
Please create a new issue if something was assigned to a milestone and closed.
