### ISSUE TITLE
Produktdetails werden nach Attributauswahl neu geladen

### ISSUE THREAD

**Issue by error08** [isotope/core#1564]
Wenn ich das korrekt verstanden habe, werden die Produktdetails nur nachgeladen, sobald ein Attribut als Variantenattribut angelegt ist. Und dadurch im Array $GLOBALS['AJAX_PRODUCTS'] steht.

Nachdem ich ein Attribut als Variantenattribut markiert hatte und die Markierung wieder entferne, werden die Daten bzgl. der Variantenattribute nicht vollständig aus der Tabelle tl_iso_producttypes gelöscht. Zudem werden die Produktdetails beim Ändern dieses Attributes (kein Variantenattribut mehr) jedes Mal neu geladen. Bei Attributen, die noch nie als Variatenattribut konfiguriert waren, tritt diese Verhalten nicht auf.

**Comment by aschempp** [comment]
Kannst du beschreiben wie das Attribut genau konfiguriert wurde?

**Comment by error08** [comment]
Es geht hier um das Attribut Farbe, welches zuerst als ein Attribut für Varianten angelegt wurde. 
Später wurde die Option "für Varianten verwenden" wieder entfernt. (nur der Haken) und wurde als Options source = Produkt konfiguriert. Sodass die Werte für dieses Attribut beim jedem Produkt einzeln hinterlegt werden können.
Aktuelle Konfig:

![konfig](https://cloud.githubusercontent.com/assets/4061613/11408688/0bce0a40-93bb-11e5-8fc1-013d24d97ff3.png)


Zusätzlich gibt es noch zwei weitere Attribute pro Produkt (Textaufdruck, Größe), eines mit der selben Options source Einstellung und das andere mit Options source = Option Manager. 
Im Frontend verhalten es sich aktuell so, das nach einer Auswahl für Textaufdruck oder Größe kein Nachladen der Seite ausgelöst wird, allerdings beim einer Auswahl für das Attribut Farbe wird die Seite nachgeladen. Dieses Verhalten kenne ich sonst nur, wenn ein Attribut in Varianten verwendet wird.

**Comment by aschempp** [comment]
Dies passiert, weil die Optionen im Produkt einen Preis haben könnten. Deshalb muss Isotope das Produkt neu laden, falls sich der Preis geändert hat. Ggf. könnte man das aber optimieren…

**Comment by error08** [comment]
Ok, der unschöne Effekt beim nachladen werden weitere Attributfelder die Pflicheingaben sind als Fehler ausgewiesen,weil noch kein Wert eingegeben / ausgewählt wurde.

**Comment by aschempp** [comment]
Ich denke diese Fehlermeldung ist mittlerweile durch https://github.com/isotope/core/issues/1966 behoben (seit Isotope 2.5.13)
