### ISSUE TITLE
Feature-Request: Produkt-Variante vorausgewählt

### ISSUE THREAD

**Issue by netzarbeiter** [isotope/core#1565]
Es wäre super, wenn man die Möglichkeit hätte eine Produkt-Variante vorausgewählt im Frontend anzuzeigen.

**Comment by tsarma** [comment]
Would that be something like having variants its own alias/URL.

**Comment by aschempp** [comment]
No, this is about setting a default variant to be seletect on page load

**Comment by Irontale** [comment]
Is this enhancement already in the lastest version?

**Comment by aschempp** [comment]
it's assigned to the 2.4 milestone, the latest stable release is 2.3.5 ;-)
