### ISSUE TITLE
Ausweis der Versandkosten bereits im Warenkorb

### ISSUE THREAD

**Issue by error08** [isotope/core#1568]
Aktuell können die Versandkosten nicht bereits im Warenkorb ausgewiesen werden. Dies wird teilweise schon als nicht rechtskonform in Deutschland angesehen... :(
Ich weiß,es macht auch nur Sinn,wenn die Versandkosten immer gleich sind und 
für den Warenkorb errechnet werden können. Dennoch eine Option im Warenkorb sehr hilfreich
die Versandkosten bereits hier ausweisen zu können.

**Comment by aschempp** [comment]
Es gibt ein Modul "Versandkostenrechner" in Isotope 2.3, welches frei platziert werden kann (z.B. auf der Warenkorb-Seite).
