### ISSUE TITLE
Isotope does not resize product images on upload

### ISSUE THREAD

**Issue by CodeAlDente** [isotope/core#1569]
I'm using Contao V3.5.3 together with Isotope V2.3.1#3

**Comment by aschempp** [comment]
It resizes them on output, why should it resize on upload?

**Comment by CodeAlDente** [comment]
Well, I need thumbnails for them. I can't confirm, that they get resized after the upload. Only few pictures have a thumbnail, the rest kept it's original size. In my case we're talking about photos with a pixel resolution of 4000x4000. And those thumbnails that have been created are way too small.

I found a temporary workaround by adding a custom stylesheet via stylish, so the overview is clear for the moment. But we need a permanent solution.

**Comment by aschempp** [comment]
That's what galleries are for (see shop configuration).

**Comment by CodeAlDente** [comment]
I'm talking about the pictures that are displayed on the products overview and about the pictures that are listed inside the product details. The settings I made for the galleries seem not to affect the images here.

**Comment by aschempp** [comment]
Correct. But images 4000x4000 is too large for Contao to handle (see system settings), otherwise they would have been adjusted.
