### ISSUE TITLE
Attribut Select-Menü Probleme

### ISSUE THREAD

**Issue by loettgers** [isotope/core#1570]
Hallo,
ich bin mir nicht sicher, ob das nur bei mir auftritt:
seit dem ich auf Version 2.3.1 ein Update gemacht hat, werden mir die Werte (multiple) des Select-Menü-Attributes nur als komma-getrennter String zurückgegeben. Früher war es immer ein serialisiertes Array.

Vielen Dank,
Steven

**Comment by aschempp** [comment]
Das ist korrekt. Wir haben das in Version 2.3 optimiert, weil mit kommaseparierten Werten die Datenbank durchsucht werden kann.
