### ISSUE TITLE
[2.3.1] ##form_Checkbox-Menü## oder ##form_Select-Menü## ergibt 'Array'

### ISSUE THREAD

**Issue by ae69** [isotope/core#1571]
Bei Verwendung von ##form_Checkbox-Menü## oder ##form_Select-Menü## wird nur die Bezeichnung 'Array' an Stelle der Inhalte im Dokument ausgegeben. Bei Form-Inhalten ohne Array ist alles ok. Oder gibt es hier einen Trick??
Danke

**Comment by aschempp** [comment]
Von welchem Dokument sprichst du? Dokumente (PDFs) können keine Simple Tokens?

**Comment by ae69** [comment]
Sorry ich meinte **Nachrichten**, wenn ein e-mail generiert wird: z.B.

Danke für Ihre Anfrage über:
##cart_html##
Weitere Mitteilung: ##form_textfeld##
Sie möchten: ##form_todo##
[nbsp]
##billing_address##
Sie erhalten die Unterlagen per: ##shipping_label##


##form_todo## ist ein checkbox menu und ergibt "Array"
Unter Bestellungen im backend wird es korrekt angezeigt.

Ich habe jetzt 4 einzelne Checkboxes gemacht, dann gehts natürlich.

**Comment by aschempp** [comment]
Dachte ich mir fast. Dann ist es allerdings ein Problem des [Notification Centers](https://github.com/terminal42/contao-notification_center). Sollte aber eigentlich nicht auftreten, wenn du die neuste Version hast.
