### ISSUE TITLE
Rechnungsnummer zusätzlich zur Bestell-Nummer

### ISSUE THREAD

**Issue by error08** [isotope/core#1572]
Könnte man zusätzlich zur Bestellnummer ein Feld Rechnungsnummer aufnehmen, welche auch in der Bestell-Übersicht ausgewiesen sowie auf Dokumenten und in Benachrichtigen genutzt werden könnte?

Denn beide Nummer sind nicht zwangsläufig identisch. Die Bestell-Nummer wird nach Eingang einer Bestellung erzeugt. Dies bedeutet allerdings nicht zwangsläufig, dass diese Bestellung auch bezahlt und dementsprechend ausgeliefert wird. Das Bestell-Dokument hierzu ging allerdings an den Kunden raus, somit kann man diese Bestellung auch nicht einfach löschen.

Als Zeitpunkt zur Erzeugung der Rechnungsnummer würde ich den Zustandsübergang der Bestellung in "bezahlt" ansehen. An dieser Stelle würde der Kunde eine Rechnung als Dokument bekommen.

Als "Rechnungsnummer" könnte nun wieder die Bestellnummer genommen werden. Für den Kunden ist dies auch irrelevant. Nur muss man dem Finanzamt dann erklären, warum in den Rechnungsnummer Lücken entstanden sind. Nach meiner Erfahrung sehen sie das nicht so gerne.

Daher die Frage, könnte man hier eine 2. Nr. aufnehmen, welche im Zuge eines Bestellstatus-Übergangs erzeugt wird. Dies könnte ähnlich konfigurierbar sein wie der Haken "Die Bestellung wurde bezahlt".

**Comment by aschempp** [comment]
Isotope ist kein Warenwirtschafts-System. Nach deinem Beispiel müssten wir auch Lieferscheine etc. führen.

> Nur muss man dem Finanzamt dann erklären, warum in den Rechnungsnummer Lücken entstanden sind.

Die Bestellnummern sind absolut fortlaufend. Sollte eine Bestellung nicht stattfinden solltest du diese stornieren und nicht löschen (deshalb kann ein normaler User das auch nicht).
