### ISSUE TITLE
Product Variant List errorneous

### ISSUE THREAD

**Issue by tsarma** [isotope/core#1573]
Product Variant list returns unexpectedly many products. 

Contao: 3.5.4
Isotope: 2.3.1 Build 4
Installed Demo Isotope Shop

In demo example:
T-Shirt-> 2008 Würzburg has 8 variants. 

On the T-Shirt page's article I've placed a module (Product Variant list). It shows more then 80 T-Shirts depending upon the modules 'categry Scope' settings.

Module Settings used:
Numbers of Items : 0
Items per Page: 0
Category Scope: Current Product's Categories
Condition: 
Custom module template: -
Product list template: -

**Comment by aschempp** [comment]
Are some of them duplicates?

**Comment by tsarma** [comment]
Inserting 
```php
print_r($arrColumns); die();
```
just before 
```php
$objProducts = Product::findAvailableBy(...
```
in /isotope/Module/ProductVariantList.php


```code
Array ( [0] => ( (tl_iso_product.id IN (30,20,30,20,29,29,31,31,32,32,34,34,35,35,36,36,37,37,20,20,29,29,143,143,141,141,179,179,20,20,29,29,30,30,31,31,35,35,32,32,36,36,34,34,37,37,179,179) AND tl_iso_product.type NOT IN (2,19)) OR tl_iso_product.pid IN (30,20,30,20,29,29,31,31,32,32,34,34,35,35,36,36,37,37,20,20,29,29,143,143,141,141,179,179,20,20,29,29,30,30,31,31,35,35,32,32,36,36,34,34,37,37,179,179) ) )
```

**Comment by tsarma** [comment]
If my understanding of module "Product Variant List" is to list list all variants of the particular product, then in my opinion the method ```findProducts``` of class ```ProductVariantList``` may wrong. 

My understanding:
Screen 1
![screen shot 2015-12-01 at 17 31 48](https://cloud.githubusercontent.com/assets/683894/11507283/923102da-9853-11e5-88fc-272ac8ee2cb1.png)

When I click the variants icon, I come to screen 2

![screen shot 2015-12-01 at 17 32 10](https://cloud.githubusercontent.com/assets/683894/11507311/bcd94592-9853-11e5-8f2f-278d2e7197f2.png)

Now when I place a module ```Product Variant List``` on the reader page, I expect a list of above products in screen 2 marked with red boxes.


I am saying  method ```findProducts``` of class ```ProductVariantList``` may be wrong, because ```$arrProductIds``` are selected with criteria based on catagories (Page Ids), whereas It should be based on the parent product ID. Am I wrong in my assumption!!

**Comment by aschempp** [comment]
Yes your assumption is wrong. The product variant list is not related to the current product. It just shows all product variants of a category instead of all products of that category.
