### ISSUE TITLE
Auswertung "Verkäufe pro Produkt"

### ISSUE THREAD

**Issue by error08** [isotope/core#1576]
Bei der Auswertung Verkäufe pro Produkt wäre ein zusätzlicher Ausweis der Anzahl der verkauften Produkte m.E. 
![ohne titel](https://cloud.githubusercontent.com/assets/4061613/11452060/1e3024ae-95da-11e5-8c44-7768de505c62.jpg)
sinnvoll.

**Comment by aschempp** [comment]
see #1577
