### ISSUE TITLE
Bilder im Backend "OrderDetails" nicht skaliert

### ISSUE THREAD

**Issue by error08** [isotope/core#1578]
So wie ich gesehen habe, wird für die Anzeige der Order Details im Backend u.a. auch die Produktliste "iso_collection_default" genutzt. Hier wird u.a. die Funktion generateMainImage genutzt, die die Produktbilder analog der hinterlegten Galerien erzeugt / skaliert.
Dies scheint im Backend allerdings nicht zu funktionieren / eingebunden zu sein.
Hier sind die Bilder aller Produkte in Originalgröße, welche u.U. ziemlich groß sind.
Hier wäre es sinnvoll die selbe Galerien wie im Frontend zu nutzen / einzubinden.

**Comment by aschempp** [comment]
Wir sollten in er Shop-Config eine entsprechende Konfiguration einführen.

**Comment by error08** [comment]
Ich habe mir die Änderung gerade angeschaut. Wo ist jetzt der Unterschied zu vorher außer das pro Konfiguration ein OrderDetails-Template konfiguriert werden kann. Als Template überschreiben konnte man es ja prinzipiell. Das Problem mit den Bilder besteht immer noch. Zusätzlich müsste hierzu m.E. noch das Collection-Template fürs OrderDetails-Modul konfigurierbar sein.

**Comment by aschempp** [comment]
Du konfigurierst kein Template sondern ein Modul. Im Modul dann die Gallerie.

**Comment by error08** [comment]
Ah, sorry. Ich hatte das Module übersehen. Läuft! Super!
