### ISSUE TITLE
1 Gutschein pro Bestellung

### ISSUE THREAD

**Issue by laRocca** [isotope/core#1580]
Hallo zusammen,

ich habe eigentlich genau das gleiche Problem wie  [dieser Zeitgenosse,](https://community.contao.org/de/showthread.php?60262-1-Gutschein-pro-Bestellung&p=392060#post392060) nur leider finde ich dazu keine Lösung im Forum, Netz, etc…
Gibt es denn mittlerweile eine?

LG & Danke schon mal 

edit// Zum besseren Verständnis:
Aktuell kann man 2 Gutscheine gleichzeitig nutzen, die sich dann aufaddieren: Nach Eingabe eines 10% Gutscheins, kann man noch einen anderen 10% Gutschein eingeben und hat dann 20% Rabatt… und das kann man so fortführen…

**Comment by aschempp** [comment]
Das ist korrekt. Bisher gibt es keine Einstellung dass nur ein Gutschein-Code verwendet werden darf …
