### ISSUE TITLE
Warenkorb Mini + Gutschein-Rabatt anzeigen 

### ISSUE THREAD

**Issue by laRocca** [isotope/core#1581]
Hallo zusammen,

kann ich mir im Mini-Warenkorb auch den Rabatt, den ich durch Gutscheineinlösen erhalte, bereits anzeigen lassen?

**Comment by aschempp** [comment]
Das wäre eine Anpassung des Templates. Bitte wende dich dazu ans Community Forum, das Ticketsystem ist für Bug Reports.
