### ISSUE TITLE
Class CumulativeFilter private methods

### ISSUE THREAD

**Issue by tsarma** [isotope/core#1583]
Please make methods inside class ```CumulativeFilter``` not private. It can't be overwritten easily without duplication of lots of code block.

**Comment by aschempp** [comment]
They are currently private because I'm not sure if they are final. As soon as they are not private, we need to keep API compatibility.
What do you need to override?

**Comment by tsarma** [comment]
I needed to override private method ```addFilter``` to add extra filter conditions.


My Cumulative Filter settings:

![screen shot 2016-01-20 at 09 05 13](https://cloud.githubusercontent.com/assets/683894/12443089/933e828c-bf55-11e5-8b6d-0afd5233ed41.png)


My Overwritten method:

![screen shot 2016-01-20 at 09 05 48](https://cloud.githubusercontent.com/assets/683894/12443094/9757998a-bf55-11e5-8e75-8799f2b61f5f.png)

Where: 
```show_master``` == dca checkbox field for module CF
```showin_list``` == product attribute of type checkbox.

**Comment by aschempp** [comment]
The position you want to add seems wrong to me, as it would be added multiple times. 
I have changed access to `activeFilters` in 4405343a2b68ccfcb0a1208e4fe38b6765e8ea4e which you should probably override/append in the constructor method of your child class.

**Comment by tsarma** [comment]
Thank you, I'll change mine accordingly
