### ISSUE TITLE
Messages Module - Zeilenumbrüche 

### ISSUE THREAD

**Issue by DrDreave** [isotope/core#1585]
Guten Morgen,
bei uns ist nach der Übertragung des Shops auf das Live-System ein Fehler aufgetreten.
Das Legen eines Produkts in den Warenkorb wurde nicht durch Anzeige des Overlays bestätigt.

Das Problem bestand darin, dass die Zeilenumbrüche auf dem Live-Server nicht zuverlässig entfernt wurden, sodass das Javascript das *mod_iso_messages* Template als Parameter nicht richtig interpretieren konnte und den Ablauf mit einem 
*Uncaught SyntaxError: Unexpected token ILLEGAL*
beendete.

Verantwortlich war der Aufruf von
```javascript
Isotope.displayBox()
````
eingefügt in den Body im Isotope\Frontend#injectScripts

```php

public function injectScripts($buffer)
{
    ...
    $template = new \FrontendTemplate('iso_scripts');
    if ($hasProducts) {
        $template->hasProducts = true;
        $template->loadMessage = specialchars($GLOBALS['TL_LANG']['MSC']['loadingProductData']);
        $template->products    = json_encode($GLOBALS['AJAX_PRODUCTS']);
    }

    if ($messages !== '') {
        $template->hasMessages = true;
        $template->messages = str_replace(array("\n", "'"), array('', '\''), $messages);
    }

    $buffer = str_replace('</body>', $template->parse() . '</body>', $buffer);
    ...
}
```

Das Ergänzen des ```str_replace```Aufrufs (Zeile 282), zur Entfernung der Umbrüche, schaffte in unserem Fall Abhilfe:
```php
    $template->messages = str_replace(array("\n", "'", "\r", "\t", '<!-- indexer::stop -->', '<!-- indexer::continue -->'), array('', '\'', '', '', '', ''), $messages);
```
Die Indexer-Kommentare wurden vorsichtshalber ebenfalls entfernt.
Es wäre schön, wenn diese Änderung mit in den Core übernommen werden könnte.

Vielen Dank.
LG Dave

**Files:**
- system/modules/isotope/library/Isotope/Frontend.php
- system/modules/isotope/templates/isotope/iso_scripts.html5
- templates/mod_iso_messages.html5 | Custom Template

**Comment by aschempp** [comment]
Welche Version verwendet ihr? Dieses Problem sollte seit 2.1.15 bzw. 2.2.6 behoben sein:

**Comment by aschempp** [comment]
Ich schliesse dies vorerst, bei weiteren Infos gerne wieder öffnen.
