### ISSUE TITLE
Postfinance owneraddress too long

### ISSUE THREAD

**Issue by netzarbeiter** [isotope/core#1586]
The customer added an information longer than 35 character in the field street_2.

Postfinance has rejected the order with the following message:
*owneraddress too long : length 10 MAX:35 numeric bytes*

I have added a limitation to the concerning field:
```php
$GLOBALS[‚TL_DCA']['tl_iso_addresses']['fields']['street_2']['eval']['maxlength'] = 35;
```

**Comment by aschempp** [comment]
Unfortunately, the Postfinance documentation does not say anything about this. I have now limited the address and city length when submitting data to Postfinance, but their length in Isotope is not limited.
