### ISSUE TITLE
[2.3.x] Edit Multiple/doNotShow Logic looks wrong

### ISSUE THREAD

**Issue by blairwinans** [isotope/core#1589]
I cannot get custom attributes to show up in the Edit Multiple palette.

I am looking at line [349](https://github.com/isotope/core/blob/master/system/modules/isotope/library/Isotope/Backend/Product/DcaManager.php#L349) in the DCA Manager, and the logic makes no sense to me. Am I wrong that it will almost always evaluate to true as it is?

It seems like it should be grouped like so:

`if ((!isset($arrField['attributes']) || $arrField['inputType'] == '') && $name != 'inherit')`

Then all my custom attributes show up nicely, as well as the inherit option.

**Comment by aschempp** [comment]
Event my IDE says you're right ;-)
