### ISSUE TITLE
Fatal error: Class 'StringUtil' not found Address.php on line 136

### ISSUE THREAD

**Issue by danielroeding** [isotope/core#1596]
Hallo zusammen,
im Bestellprozess __nach Auswahl der Zahlmethode__ wird auf der Seite /review.html folgende Fehlermeldung angezeigt.

Fatal error: Class 'StringUtil' not found in /www/htdocs/w0136b58/mportable.de_350/mportable.de/system/modules/isotope/library/Isotope/Model/Address.php on line 136

Im System Log kommt kein Fehler an.

Versucht habe ich es bereits mit __Contao 3.5.0 und 3.5.6 jeweils in Kombination mit Isotope 2.3.2.__
Auf dem Server läuft __PHP 5.4.45-nmm1__ laut Contao Check 10.11 und alles ist grün.
Hoster ist __all-inkl.com__

Was kann ich noch versuchen?
__Danke im voraus.__

**Comment by Toflar** [comment]
In 3.5.6 muss es funktionieren. 3.5.0 natürlich nicht, siehe Minimalanforderungen.

**Comment by danielroeding** [comment]
Also könnte es an meinem Contao Update auf 3.5.6 liegen.
Dann werde ich das mal überprüfen.
Danke erstmal.

**Comment by danielroeding** [comment]
Problem gelöst.
Bei dem Update sind einige Dateien im Ordner System/Core nicht überschrieben worden. 

Danke.
