### ISSUE TITLE
Isotope Translation Module {{isolable:: }}

### ISSUE THREAD

**Issue by tsarma** [isotope/core#1599]
This is a suggestion, not really an issue.
Please make Isotope translation a separate module and define it as dependency for Isotope. The translation module {{isolable:: }}, is such a useful module for multi-language site that I think it deserve to be standalone. 

Use cases: 
- Forms Fields
- Module Headings.

In this way we may avoid having to duplicate many forms, modules and some general meta informations.

Blödsinn??

**Comment by aschempp** [comment]
Unfortunately, that will not work as the labels that are translatable must explicitly support the extension, which will not be the case for any core modules etc.
I recommend to use inserttags for this, by placing the labels in translation files or using an extension.

**Comment by tsarma** [comment]
Inserttags {{iflng::de}}...{{iflng::fr}}...{{iflng::en}}... is cumbersome and not feasible in short available space inside input fields.

What about if you integrate it into your changelanguage module!

**Comment by aschempp** [comment]
changelanguage is about switching languages in the frontend, nothing to do with labels.

I was talking about `{{label::*}}` and not `{{iflng::*}}`: https://docs.contao.org/books/manual/3.5/en/04-managing-content/insert-tags.html
