### ISSUE TITLE
"Bitte füllen Sie das Feld aus"

### ISSUE THREAD

**Issue by kubjo** [isotope/core#1600]
Hi Leute,
bei einer Kundin von mir taucht das Problem aus der 3.5.5 "Bitte füllen Sie das Feld aus" (Links oben) in einer 3.5.6. im Isotope-Shop auf, wenn Sie eine Farbvariante mit Beschreibung einfügen will.

- Check -> alles da!
- Install.php -> Alles gut!
- ER -> Aller Erweiterungen OK,
- Cache gelöscht -> neu aufgebaut

Was kann ich noch machen?

**Comment by aschempp** [comment]
Frontend oder Backend ?

**Comment by kubjo** [comment]
Frontend, gleiches Erscheinungsbild wie Fehler in contao 3.5.5. der zu 3.5.6 führte:
https://github.com/contao/core/issues/8131

**Comment by aschempp** [comment]
Dann scheint es ein unsichtbares Feld zu geben. Solche macht Isotope aber selber eigentlich nicht… du müsstest mal rausfinden welches Feld das ist.

**Comment by kubjo** [comment]
Wenn man etwas speichern möchte, erscheint ober links im Viewport des Browsers eine Meldung in einer "Sprechblase" Bitte füllen Sie dieses Feld aus. Wie könnte ich herausfinden, welches Feld gemeit ist? Kann ich einen Screenshot hier einfügen? Alt+Umschalt+s (Win Firefox) bewirkt das Selbe!

**Comment by aschempp** [comment]
Schau dir den Quelltext der Seite an, welche Formularfelder es gibt die ggf. nicht angezeigt werden.

**Comment by kubjo** [comment]
Nichts zu machen, werder mit FireBug noch der normale Quelltext zeigt da etwas an. Würde Dir ein Backend zugang etwas bringen?

**Comment by aschempp** [comment]
Das wäre dann direkten Kundensupport, den bieten wir im Rahmen des Isotope Circle (https://circle.isotopeecommerce.org) an.

**Comment by kubjo** [comment]
Geht das auch einmalig?

**Comment by netzarbeiter** [comment]
Klar, einmalig für ein Jahr.

**Comment by kubjo** [comment]
Ich dachte Abrechnung nach Aufwand.

**Comment by aschempp** [comment]
Das widerspräche doch meiner Aussage *den bieten wir im Rahmen des Isotope Circle an.*?

**Comment by kubjo** [comment]
Was kann ich noch machen?

**Comment by kubjo** [comment]
Habe das Problem jetzt auf einer frischen Installation des Demoshops nachgestellt und reproduzieren können. Hier grob meine Schritte: 
- Demoshop frisch installiert
- Contao via Live-Update auf 3.5.6 upgedated
- Isotope auf 2.3.3 upgedated
- Varianten der T-Shirts entsprechend meines  "Problemshops" angepasst.
-> Fehler tritt auf!

Die zwei unsichtbaren Pflichtfelder wurden gefunden: Das sind genau die zwei Eingabefelder für "Artikelnummer" und "Name", welche jedoch mittels Checkbox "Vorgabe-Wert nutzen" ausgeblendet werden. Beim Speichern der Variante moniert jedoch der Browser, dass diese Felder nicht ausgefüllt sind.

<input style="display: none;" name="sku" id="ctrl_sku" class="tl_text mandatory" value="" required="" maxlength="128" autofocus="" onfocus="Backend.getScrollOffset()" type="text">

Isotope müsste hier also entweder beim Setzen der Checkbox das Required-Attribut des Feldes entfernen oder den Vorgabewert automatisch aus den allgemeinen Produktdaten mit in diese Felder übernehmen.

Mein Demoshop, ist online zugänglich, wenn sich jemand für die Konfiguration interessiert, kann er gerne die Zugangsdaten von mir erhalten!

Ich hoffe hierdurch einen kleinen Teil zur Verbesserung von isotope als OpenSource beizutragen!

Grüße aus Ludwigsburg
Jochen Kubik

**Comment by aschempp** [comment]
Super, vielen Dank für die ausführliche Beschreibung. Jetzt erst ist mir klar geworden dass das Problem im Backend besteht, bisher dachte ich im Frontend ;-)

**Comment by kubjo** [comment]
Ja, sorry  für die Verwechslung in der ersten Antwort! Willst Du dir das mal im Demoshop anschauen?
