### ISSUE TITLE
PAYONE: Falscher Request Typ - 

### ISSUE THREAD

**Issue by danielroeding** [isotope/core#1601]
Hallo zusammen,

bei der Verwendung von Payone als Zahlungsanbieter tritt folgender Fehler auf wenn im Shop die Bezahlung abgesendet wird.

Es öffnet sich die Seite: https://secure.pay1.de/frontend/
Dort erscheint: Bitte korrekten Requesttyp angegeben. (createaccess)

Auf Nachfrage bei Payone kam diese Antwort:
Der Request createaccess ist nur im Rahmen des Moduls Contract (Aggregiertes Micropayment)
nutzbar, da hier ein spezielles Portal zur Verfügung gestellt werden muss. 
Wenn es schlicht um eine Zahlung geht, dann läuft das normalerweise über die requests preauthorization (Reservierung) und capture. Alternativ direkt über authorization.

In der Shop Konfiguration habe ich beide Optionen (Autorisieren / Autorisieren und Einnehmen) bereits getestet ohne Auswirkungen. Scheinbar wird diese Option nicht richtig verarbeitet.

Hat da jemand eine Idee?

**Comment by aschempp** [comment]
Isotope liefert nirgends die type `createaccess`, hast du vielleicht das Template angepasst?

Es wird entweder `preauthorization` oder `authorization` gesendet, abhängig von der Einstellung im Backend.

**Comment by danielroeding** [comment]
Richtig. Ich kann mir auch nicht erklären wo der falsche request her kommt.

Template Anpassungen habe ich nicht gemacht.

Bei payone ist allerdings der Demo Modus aktiv.

Am Montag, 25. Januar 2016 schrieb Andreas Schempp :

> Isotope liefert nirgends die type createaccess, hast du vielleicht das
> Template angepasst?
>
> Es wird entweder preauthorization oder authorization gesendet, abhängig
> von der Einstellung im Backend.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/isotope/core/issues/1601#issuecomment-174594912>.
>


-- 


Mit freundlichem Gruß
Daniel Röding

___________________________________
DIE.PIXELSCHIEBER

Daniel Röding
Rottland 18
27637 Nordholz
Fon: 04741.9718950 -0
Mobil: 0151 560 12 987
Fax: 04741.9718950 -9

danielroeding@die-pixelschieber.com
www.die-pixelschieber.com

**Comment by danielroeding** [comment]
![cursor_und_mozilla_firefox](https://cloud.githubusercontent.com/assets/12136943/12591886/34c2b81c-c46a-11e5-9f29-bcb2663332b2.jpg)

**Comment by aschempp** [comment]
Hast du hier noch etwas herausgefunden?

**Comment by aschempp** [comment]
Ich schliesse dies vorerst, bei weiteren Infos gerne wieder öffnen.

**Comment by danielroeding** [comment]
Dieses Problem konnte gelöst werden.
Bei allen Zahlungsarten wurde fälschlicher Weise bei der PAYONE Portal-ID eine Stelle zu wenig angegeben. Daraus deutete PayOne ein anderes / falsches Zahlungsverfahren und schmiss entsprechend einen Fehler raus.
