### ISSUE TITLE
[PHP7] Check compatibility of core as well as all the dependencies

### ISSUE THREAD

**Issue by Toflar** [isotope/core#1602]
| Extension                                | Status   | Related Issue(s) |
|------------------------------------------|----------|---------------|
| isotope/core                             | resolved  | [#1602](https://github.com/isotope/core/issues/1602),  [#1584](https://github.com/isotope/core/issues/1584) |
| terminal42/contao-conditionalselectmenu  | resolved  |               |
| terminal42/contao-namespace-class-loader | resolved  |               |
| terminal42/dcawizard                     | resolved  |               |
| codefog/contao-haste                     | resolved | [#74](https://github.com/codefog/contao-haste/pull/74) |
| menatwork/contao-multicolumnwizard       | resolved  |               |
| terminal42/contao-tablelookupwizard      | resolved  |               |
| terminal42/notification_center           | resolved  | [#86](https://github.com/terminal42/contao-notification_center/issues/86) |
| terminal42/dc_multilingual               | resolved | [#33](https://github.com/terminal42/contao-DC_Multilingual/issues/33) |

Status can be any of these:

* testing: Nobody has reported either non-compatibility or compatibility yet.
* reported: Somebody has tested and found issues. They must be reported in the respective extension's issue tracker and linked in the column "Related Issue(s)" in this issue.
* resolved: The compatibility has been accomplished.

**Comment by Mynyx** [comment]
terminal42/contao-notification_center#86

**Comment by Mynyx** [comment]
#1584 ist fixed, #1602 nur diese Übersicht

**Comment by Toflar** [comment]
Dessen bin ich mir bewusst...

**Comment by qzminski** [comment]
Did some tests on my localhost with PHP 7.0.0:

- [X] terminal42/contao-conditionalselectmenu
- [X] terminal42/contao-namespace-class-loader
- [X] terminal42/dcawizard
- [X] menatwork/contao-multicolumnwizard
    - duplicate select issue - https://github.com/menatwork/MultiColumnWizard/issues/188
- [X] terminal42/contao-tablelookupwizard
- [ ] terminal42/dc_multilingual
    - see https://github.com/terminal42/contao-DC_Multilingual/issues/33

**Comment by qzminski** [comment]
terminal42/notification_center should be now compatible with PHP7 as well.

https://github.com/terminal42/contao-notification_center/issues/86

**Comment by qzminski** [comment]
@Toflar I think you can update the table again and since all dependencies are resolved everything together can be tested.

**Comment by Toflar** [comment]
Done. Have all the new versions of the extensions been released?

**Comment by qzminski** [comment]
I think so, yes:

- codefog/contaohaste 4.11.3
- terminal42/contao-notification_center 1.3.5
- terminal42/contao-DC_Multilingual 2.1.3

**Comment by Toflar** [comment]
@netzarbeiter can you test then, please? :)

**Comment by aschempp** [comment]
are we done here? 😄

**Comment by Toflar** [comment]
Yes, everything has been resolved.
