### ISSUE TITLE
neuer Hook der ausgeführt wird, sobald die Bestellung bezahlt wurde / Datum gesetzt wurde

### ISSUE THREAD

**Issue by error08** [isotope/core#1604]
Ich finde einen neuen Hook sinnvoll, der ausgeführt wird sobald eine Bestellung bezahlt wurde.
Aktuell hab ich das Problem, dass ich abhängig von der Bezahlung der Bestellung (date_paid) ein Feld speichere, welches ich dann in der Email und in den PDF-Dokumenten benutzten möchte.
Der preOrderStatusUpdate-Hook kommt hier zu früh und der postOrderStatusUpdate-Hook ist zu spät, da die NotificationTokens (getNotificationTokens) schon generiert wurden.
Ich habe es auch mit der Methode  ```$objNewStatus->isPaid()``` im Hook preOrderStatus Update  versucht, hier wird bei mir allerdings nur ein String-Objekt mit der Status-ID zurück.
Ich verstehe nicht, warum hier nicht das Status-Objekt übergeben wird...

**Comment by aschempp** [comment]
Was möchtest du denn erreichen?

**Comment by error08** [comment]
Einen Wert in die Datenbank schreiben, nachdem die Bestellung als bezahlt markiert wird. Diesen Wert benötige ich anschließend im Hook getNotificationTokens um den Wert mit in den Benachrichtigungen und in Dokumenten auszugeben.

**Comment by aschempp** [comment]
`preCheckout` und `postCheckout` helfen auch nicht?

**Comment by error08** [comment]
Werden die auch ausgeführt wenn die Bestellung später im Backend auf bezahlt gesetzt wird,nach der Bestellprozess schon abgeschlossen ist?

**Comment by aschempp** [comment]
Nein

**Comment by aschempp** [comment]
Ich denke du müsstest den entsprechenden Wert einfach beim Hook `getNotificationTokens` speichern… und ggf. noch beim `postOrderStatusUpdate` zur Sicherheit.
