### ISSUE TITLE
Währungssymbol erscheint in generierten Dokumenten nicht

### ISSUE THREAD

**Issue by error08** [isotope/core#1605]
Währungssymbol erscheint in generierten Dokumenten nicht. Die Tabelle mit den Artikeln und den Summe erscheint ohne Währungssymbol. Hier sollte die gleich Ansicht wie in der Mail, Warenkorb und Kassen möglich sein.

**Comment by error08** [comment]
Problem tritt mit der Mail-App unter dem AppleOS El Capitan auf. Unter Yosemite funktioniert es.
Teste es diese Woche noch mit Outlook unter Windows

**Comment by aschempp** [comment]
wie kann das am Betriebsystem liegen? Verwendest du HTML-Emails?

**Comment by error08** [comment]
Ja,verwende HTML-Mails. Wie geschrieben unter El Capitan wird es weder in der Mail-App noch in einer Anzeigeanwendung für PDFs angezeigt. Unter Yosemite geht es,sowie mit iOS oder Windows 10 - die gleiche PDF-Datei

**Comment by aschempp** [comment]
Kannst du das PDF zur Verfügung stellen?

**Comment by error08** [comment]
Ich kläre das mit dem Kunden ab. Kann ich dies per Mail zusenden?

**Comment by aschempp** [comment]
Nicht ideal (weil nicht für alle Ticket-Interessenten reproduzierbar) aber in diesem Fall verständlich. Am einfachsten an info@isotopeecommerce.org (siehe https://isotopeecommerce.org/de/impressum.html)

**Comment by qzminski** [comment]
I have tested the PDFs on the following systems and apps:

- Windows 10: Adobe reader, Adobe acrobat
- Windows 8: Reader
- OSX El Capitan: Preview

Everything works fine for me and the Euro sign is visible.

**Comment by aschempp** [comment]
I'm closing this as invalid. It is probably related to https://github.com/isotope/core/issues/1539
