### ISSUE TITLE
Zahlung mit Paypal schlägt fehl

### ISSUE THREAD

**Issue by error08** [isotope/core#1607]
Die Zahlung über die Paypal-Schnittstelle schlägt fehl obwohl per Paypal bezahlt wurde.
Nach dem Bestellabschluss wird man auf Paypal weitergeleitet, dort wird abschließend bezahlt.
Leider kommt diese Information nicht in Isotope an. Man sieht auch der Seite, wie sie sich immer wieder aktualisiert und irgendwann mit der Bestellung fehlerhaft auf die Bestellübersicht zurückfällt.

Das Schlimme daran ist, die Bestellung kommt so auch nicht ins System, d.h. der Kunde hat bezahlt und wenn er das Fenster schließt ist die Bestellung weg...
Würde es Sinn machen, die Bestellung zwischenspeichern bevor man zum Zahlungsdienstleister wechseln und den Status updatet nachdem man zurückkommt bzw. die Rückmeldung erhält?

**Comment by error08** [comment]
Es lag an der fehlenden IPN-Einstellung. Vllt. macht es dennoch Sinn solche Bestellungen im System (zwischen) zu speichern, damit sie auch im schlimmsten Fall nicht verloren sind.

**Comment by aschempp** [comment]
Die Bestellungen werden in der Datenbank gespeichert, aber im Backend erscheinen nur vollständige Bestellungen.

**Comment by error08** [comment]
Können diese nicht als fehlerhaft im Backend ausgewiesen werden, so könnte der Shopbetreiber die Zahlung checken und auch diese Bestellungen manuell abschließen.
Wenn sie nur in der DB sichtbar sind, muss hier immer ein Admin eingreifen und ggf. die Bestellungs-Leichen bereinigen.

**Comment by aschempp** [comment]
Das sehe ich nicht so. Wenn der Shop korrekt funktioniert, dann würde der Besucher eine entsprechende Meldung bekommen und die Zahlung nochmals durchführen. Danach hätte man dann zwei Bestellungen im System. An der Tatsache dass der Shop falsch konfiguriert ist führt kein Weg vorbei…

**Comment by error08** [comment]
Ok verstehe ich. Wie kann man sicher die Bestellungsleichen löschen? Einfach mit einem Delete auf der Product-Collection-Tabelle? Reicht dies?

**Comment by aschempp** [comment]
Das ist eigentlich nicht nötig. Die Bestellungen werden bei erfolgreichem Abschluss oder beim löschen des Warenkorbs (bei Gästen z.B. nach 30 Tagen) entfernt.

**Comment by fokus-ux** [comment]
Nach Tagen der Recherche und Debuggings habe ich nun auch eine weitere Fehlerursache gefunden, weshalb das beschriebene Problem (PayPal Bezahlung erfolgt, Bestellung erscheint nicht in Isotope -> „Der Bezahlvorgang ist fehlgeschlagen. Bitte versuchen Sie es erneut oder wählen Sie eine andere Bezahlmethode.“) mit PayPal auftreten kann.

Es lag im Fall unseres Kunden an seiner Piwik Installation, die in der php.ini die Einstellung "always_populate_raw_post_data=-1" erfordert. Mit dieser Einstellung scheint die Rückmeldung von der Paypal IPN (sofortige Zahlungsbenachrichtigung) nicht mehr zu funktionieren...

Nochmal zusammengefasst für alle die mit PayPal und Isotope (daran liegt es meistens nicht!) am Verzweifeln sind. 

Mögliche Ursachen:

1. In eurem PayPal muss IPN (sofortige Zahlungsbenachrichtigung) aktiviert sein! Die Rückleitungs-URL spielt keine Rolle, da Sie von Isotope überschrieben wird. Es muss seit neustem, laut PayPal, eine verschlüsselte Seite, also "https://..." sein. Wenn Ihr kein SSL nutzt (solltet ihr aber) dann könnt ihr auch einfach z.B. "https://paypal.de" eintragen. Wie gesagt, Isotope überschreibt diesen Wert! 
2. Die E-Mail-Adresse, die im Isotope Module "Kasse" eingetragen ist, MUSS die primäre/Standard Email-Adresse eures PayPal-Kontos sein. 
3. Strato Kunden müssen unbedingt im Backend die Einstellung "Sicherheit/ServerSide Security/ Filter gegen Gästebuch-Spam" deaktivieren. Diese block die PayPal IPN Rückmeldung 
4. Piwik und PayPal IPN vertagen sich nicht, da Piwik die Einstellung always_populate_raw_post_data=-1 voraussetzt. Nutzt Google Analytics (getestet)oder ein anderes Tool (nicht getestet)

Ich hoffe, das hilft dem Einen oder Anderen!

**Comment by netzarbeiter** [comment]
Wer seine Piwik-Installation (ab 2.15.0) unter PHP 7 laufen lässt, braucht die Einstellung «always_populate_raw_post_data=-1» nicht mehr.

**Comment by kubjo** [comment]
Hallo fokus-ux, danke dass Du Dich da so reinhängst!
Ich habe 2 Fragen zu Deinen Punkten 1 und 2:
zu1.) "In eurem PayPal..."  Meinst Du damit eine Einstellung im Backend bei PayPal im Händlerkonto?
zu2.) Ich habe das Isotop-Modul "Kasse" geöffnet (Themes>Frontendmodule>Kasse) dort aber keine Möglichkeit gefunden eine Email Adresse zu hinterlegen. Bin ich auf der falschen Spur?

Grüße
Jochen

**Comment by aschempp** [comment]
Bitte verwendet das Forum für Diskussionen: https://community.contao.org/de/showthread.php?14883-PayPal-Anbindung-von-isotope&p=403551&viewfull=1#post403551
