### ISSUE TITLE
Neuer Hook um weitere/eigene Felder in einem PDF-Dokument zu benutzen/auszugeben

### ISSUE THREAD

**Issue by error08** [isotope/core#1609]
Neuer Hook um eigene Felder analog getNotificationToken in PDF Dokumenten zu nutzen.
Aktuell geht dies nur in Benachrichtigungen (Mail)

**Comment by aschempp** [comment]
Kannst du dafür nicht eine eigene Dokumenten-Klasse verwenden?

**Comment by error08** [comment]
Ich prüf das mal. Ggf. kann ich den Hook `generateDocumentTemplate` dazu benutzen.

**Comment by aschempp** [comment]
Hat's damit geklappt? Dann bitte das Ticket schliessen.

**Comment by error08** [comment]
Bin leider noch nicht dazu gekommen es zu testen, da ich es zum Zeitpunkt der Ticketerstellung bereits individuell gelöst hatte. Diese Lösung ist allerdings nicht updatesicher. Werde es testen. Ticket kann geschlossen werden.
