### ISSUE TITLE
Wochenansicht Auswertungen & Statistik zeigt die Werte der KW 1-9 nicht an

### ISSUE THREAD

**Issue by error08** [isotope/core#1610]
Wochenansicht Auswertungen & Statistik zeigt die Werte der KW 1-9 nicht an, da die Abfrage der KW in im Having-Statment mit führenden Nullen erfolgt, die Funktion WEEKOFYEAR die KW ohne führenden Nullen zurückliefert.

Aktuell sieht die Stelle zur Ermittlung der Parameter für das SQl-Statment so aus:
```javascript
 public function getSqlField($fieldName)
    {
        return "CONCAT(FLOOR(YEARWEEK(FROM_UNIXTIME($fieldName), 3) / 100), WEEKOFYEAR(FROM_UNIXTIME($fieldName)))";
    }
```

Würde dies nicht genügen? Tut zumindest nach den ersten Tests:
```javascript
public function getSqlField($fieldName)
    {
        return "YEARWEEK(FROM_UNIXTIME($fieldName),3)";
    }
```

**Comment by aschempp** [comment]
You're absolutely right. The complex SQL was related to calculating the correct year, but apparently your method does exactly the same :D
