### ISSUE TITLE
Variant update onchange

### ISSUE THREAD

**Issue by memikeandi** [isotope/core#1611]
I have Isotope 2.1.0 and Contao 3.2.7. 
I have a producttype with color variants but on the reader page when I choose a different color option the product doesn´t change to the selected variant you have to use the update button. Is there a way to change to the variant directly on select?

**Comment by aschempp** [comment]
You should update your installation. Isotope 2.1 is no longer maintained. More information about changes are available in the release log: https://github.com/isotope/core/releases

**Comment by memikeandi** [comment]
Ok, thanks!
