### ISSUE TITLE
Kein simple token für Artikelnummern

### ISSUE THREAD

**Issue by Rainer-Maria** [isotope/core#1612]
An PayPal werden die Artikelnummern übergeben, es fehlt jedoch ein simple token dafür. Für den Shopadmin wäre die Arbeit bei anderen Zahlungsweisen deutlich einfacher, wenn man die Artikelnummern immer mit ausgeben könnte.

**Comment by aschempp** [comment]
Eine Artikelnummer wofür?

**Comment by Rainer-Maria** [comment]
Die Artikelnummer des jeweiligen Produkts., das erworben wurde. Diese wird an paypal von isotope übergeben.

**Comment by Rainer-Maria** [comment]
Artikelnummern sind ja ein Pflichtfeld. Das sollte auch per simple tokens auslesbar sein.

**Comment by aschempp** [comment]
Ich meinte an welcher Stelle das sie fehlt?

**Comment by Rainer-Maria** [comment]
Bei der Mail an den Shopadmin kann man mit ##cart_text## den Inhalt der Bestellung auslesen. Die Artikelnummern sind jedoch nicht dabei.

**Comment by aschempp** [comment]
Das lässt sich doch durch anpassen des Templates beliebig ändern?

**Comment by Rainer-Maria** [comment]
wo bitte ändere ich die Ausgabe von ##cart_text## ? Vielen herzlichen Dank!

**Comment by aschempp** [comment]
Die Ausgabe entspricht dem Collection-Template (wählbar in der Benachrichtigung).

**Comment by Rainer-Maria** [comment]
Ok. Wäre nur schön, wenn das gleich bei der Grundeinstellung voreingestellt wäre. Danke!
