### ISSUE TITLE
Fehler bei simple tokens bei if-elsif-else-endif

### ISSUE THREAD

**Issue by Rainer-Maria** [isotope/core#1613]
Das folgende Konstrukt 
{if ##billing_address_salutation##=="Frau"}
Sehr geehrte Frau ##billing_address_lastname##,
{elseif ##billing_address_salutation##=="Herr"}
Sehr geehrter Herr ##billing_address_lastname##,
{else}
Sehr geehrte/r ##billing_address_firstname## ##billing_address_lastname##,
{endif}

erzeugt folgenden Fehler (vollständiger Pfad gekürzt)

[28-Feb-2016 14:23:43 Europe/Berlin] PHP Parse error:  syntax error, unexpected 'else' (T_ELSE) in .../system/modules/core/library/Contao/StringUtil.php(523) : eval()'d code on line 5
[28-Feb-2016 14:23:43 Europe/Berlin] PHP Fatal error: Uncaught exception 'Exception' with message 'Error parsing simple tokens ()' thrown in .../system/modules/core/library/Contao/StringUtil.php on line 530
#0 .../system/modules/haste/library/Haste/Util/StringUtil.php(59): Contao\StringUtil::parseSimpleTokens('{if ##billing_a...', Array)
#1 .../system/modules/notification_center/library/NotificationCenter/MessageDraft/EmailMessageDraft.php(143): Haste\Util\StringUtil::recursiveReplaceTokensAndTags('{if ##billing_a...', Array, 1)
#2 .../system/modules/notification_center/library/NotificationCenter/Gateway/Email.php(96): NotificationCenter\MessageDraft\EmailMessageDraft->getTextBody()
#3 .../system/modules/notification_center/library/NotificationCenter/Model/Message.php(54): NotificationCenter\Gateway\Email->send(Object(NotificationCenter\Model\Message), Array, 'de')
#4 .../system/modules/notification_center/library/NotificationCenter/Model/Notification.php(49): NotificationCenter\Model\Message->send(Array, 'de')
#5 .../system/modules/isotope/library/Isotope/Model/ProductCollection/Order.php(271): NotificationCenter\Model\Notification->send(Array, 'de')
#6 .../system/modules/isotope/library/Isotope/Backend/ProductCollection/Callback.php(463): Isotope\Model\ProductCollection\Order->updateOrderStatus('11')
#7 .../system/modules/core/drivers/DC_Table.php(2050): Isotope\Backend\ProductCollection\Callback->executeSaveHook(Object(Contao\DC_Table))
#8 .../system/modules/core/classes/Backend.php(650): Contao\DC_Table->edit()
#9 .../system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('iso_orders')
#10 .../contao/main.php(20): Contao\BackendMain->run()
#11 {main}

**Comment by aschempp** [comment]
Dein Syntax ist falsch: https://docs.contao.org/books/manual/3.5/de/04-inhalte-verwalten/newsletter.html#newsletter-personalisieren
