### ISSUE TITLE
keine alphabetische Sortierung bei Bestellstatus

### ISSUE THREAD

**Issue by Rainer-Maria** [isotope/core#1614]
In der Shop-Konfiguration - Bestellstatus werden die einzelnen Stati nicht alphabetisch sortiert.

**Comment by aschempp** [comment]
Die Sortierung wird im Backend manuell definiert (über die blauen Sortier-Pfeile).

**Comment by Rainer-Maria** [comment]
Naja, das läuft doch sonst in Contao an vielen Stellen automatisiert. Z.B. bei isotope  -> Benachrichtigungen.

**Comment by aschempp** [comment]
Die Reihenfolge der Bestellstatus ist normalerweise nach «Priorität» (also zuerst Versendet (=V), dann Erledigt (=E)) gewünscht.
