### ISSUE TITLE
Fehler bei der Konfiguration des Status bei neuen Bestellungen

### ISSUE THREAD

**Issue by Rainer-Maria** [isotope/core#1615]
in der Shop-Konfiguration - Konfiguration - Standard wird der Status für neue Bestellungen als Pflichtoption eingestellt. im Tooltipp dazu heißt es: "Wählen Sie einen passenden Status für neue Bestellungen aus. Ein Zahlungsmodul kann diese Angaben überschreiben."

Das geschieht jedoch nicht. Es erfolgt die Ausgabe aus der Konfiguration *und* aus dem Zahlungsmodul.

Entweder ist der Tooltipp anzupassen oder es ist ein Fehler.

**Comment by aschempp** [comment]
Ich verstehe das Problem leider nicht.

**Comment by aschempp** [comment]
Ich schliesse dies mangels weitere Informationen. Gerne wieder öffnen falls es noch weiteres gibt.
