### ISSUE TITLE
Bug bei Regel und Gutscheine  -> Produkteinschränkungen

### ISSUE THREAD

**Issue by kt-EDNT** [isotope/core#1617]
**Kein Text- oder Auswahlfeld vorhanden**

Hallo,

Ich wollte, wenn der Kunde eine bestimmte Produktoption auswählt, einen Rabatt gewähren.
Mein Lösung hierfür führte über Regeln und Gutscheine -> Produkteinschränkungen -> Produktattribute. Hier habe ich den Namen meines angelegten Attributs ausgewählt und wollte dann die Attributbedingung setzen. Jedoch kann ich dort nur das Dropdownfeld bedienen. 

Im Handbuch steht dazu:

> Produktattribute
> Hier kannst du die Regel auf bestimmte Produktattribute beschränken. Wähle das Produktattribut und bestimme die Attributbedingungen:
> ist gleich
> ist nicht gleich
> weniger als
> größer als
> weniger als oder ist gleich
> größer als oder ist gleich
> Beginnt mit
> Endet mit
> beinhaltet
> je nachdem welches Attribut du gewählt hast steht dir ein Text- oder Auswahlfeld zur Verfügung.

Es sollte mir also ein Text- oder Auswahlfeld zur Verfügung stehen. Dieses Feld erscheint bei mir jedoch nicht. Somit kann ich keine Unterscheidung zwischen meinen Attributoptionen vornehmen.

Interessant wäre es vielleicht noch zu erwähnen, dass der Hilfstext bei beiden Feldern (Name des Attributs und Bedingung gleich lautet).

Mein ausgewähltes Attribut:
Radio-Button-Menü
Produktoptionen-Einstellungen
vom Kunden auswählbar
Optionen-Manager
Pflichtfeld

Ich verwende Contao 3.5.3 mit Isotope 2.3.3 Build 4

Wäre nett wenn mir jemand weiterhelfen könnte und sage schon mal vielen Dank dafür.

**Comment by aschempp** [comment]
Kann es sein dass die Erweiterung MultiColumnWizard nicht installiert ist?

**Comment by kt-EDNT** [comment]
Die Erweiterung MultiColumnWizard ist/war bereits installiert.

Ist ja schon eine Weile her und wir haben den Rabatt dann anderweitig ausgewiesen, aber auch wenn ich heute den oben beschrieben Weg noch einmal gehe, komme ich nicht weiter als damals.
Es erscheint einfach kein Text- oder Auswahlfeld.

**Comment by hh-com** [comment]
Ich denke ich kann dieses Verhalten auch bestätigen.
Getestet in Contao 3.5.12 / Isotope 2.3.5 und 2.4

**Attribute:**
Type: Checkbox-Menü (Scheinbar auch Radio-Button-Menü und auch beim Textfield)
Durch den Kunden auswählbar
Optionen-Quelle: Produkt

Das Attribut wird ganz normal im Produkttype eingebunden.

Nun wird eine Regel erstellt welches auf Produktattribute eingeschränkt wird.
Es wird nun ein Button für das Auswahl-Popup angezeigt.
Klickt man darauf kommt "Ein Fehler ist aufgetreten!".
Im Log steht:
Table "tl_iso_attribute_option" is not allowed in module "iso_rules"

Der Fehler verschwindet, wenn man "Durch den Kunden auswählbar" entfernt und statt Optionen-Quelle: Optionen-Manager wählt.

**Comment by aschempp** [comment]
Ich schliesse dies vorerst Aufgrund des Alters. Gerne wieder öffnen falls das Problem noch besteht.

**Comment by marwenDD** [comment]
Hallo zusammen,
Gibt es eine Lösung für diese issue?
Ich habe genau das gleiche Problem wie @kt-EDNT, und ich komme nicht weiter
Bitte Hilfe

**Comment by marwenDD** [comment]
Ok ich habe es gelöst!
unter isotope E-commerce > Regeln & Gutscheine > Erweiterte Einschränkungen
für mich habe ich Radiobox-menu (Rabatt  Ja oder Nein) verwendet für meine Attribute aber ich denke schon dass für Checkbox oder Selectmenu genau funktionnierren würde, habe aber nicht getestet

1- unter Produkt-Einschränkungen: 
- Produktattribute auswählen
- Namen des Attributes* auswählen
- Attributbedingungen **ist nicht gleich** auswählen
-->speichern und schließen

2- unter Attribute 
- Durch den Kunden auswählbar häkchen machen
- unter Optionen-Quelle > Optionen-Manager > Optionen bearbeiten die Bezeichnung der Option einfach umgekehrt benennen.
- wähle deine Standartoption 
-->speichern und schließen
