### ISSUE TITLE
Datumsfeld "strDateField" in File Sales.php updatesicher zur Verfügung stellen

### ISSUE THREAD

**Issue by error08** [isotope/core#1620]
Kann das Feld $strDateField aus der Klasse Sales updatesicher als konfigurierbarer Wert entweder in den Config-Files oder im Backend zur Verfügung gestellt werden??

`` 
// Allow extensions to use date_paid or date_shipped
   protected $strDateField = 'locked';
``

**Comment by aschempp** [comment]
Was möchtest du damit erreichen?

**Comment by error08** [comment]
Das die Einstellung bei einem Versionsupdate von Isotope nicht überschrieben wird. Ich habe das Datum für einen Kundenshop auf date_paid eingestellt. Dies sollte mit dem nächsten Update nicht wieder überschrieben werden.

**Comment by error08** [comment]
Hierzu müsste natürlich auch die Where-Bedingung in den Auswertungen angepasst werden. Dies ist mir erstmal auf die Füße gefallen :)
`WHERE o.type='order' AND o.order_status>0 AND o.$this->strDateField!=''`

**Comment by aschempp** [comment]
Inwiefern müsste die `WHERE`-Bedingung angepasst werden? Die Idee des `protected` Feldes ist eigentlich dass man seinen eigenen Report (eigene PHP-Klasse) erstellt und das entsprechend umkonfigurieren könnte.

**Comment by error08** [comment]
In meinen Fall soll das Bezugsdatum nicht das Feld locked sonder date_paid sein. Da dies für alle Sales-Reports gelten soll,war meine Idee dieses Feld updatesicher ändern zu können.
Das es funktioniert müsste im SQL-Statement die Stellen mit dem Feld locked durch die Variable ersetzt werden.
Wenn der Sinn war,die vorhanden Reports zu kopieren,um das eine Feld zu ändern kann ich auch das machen. So würde man die Weiterentwicklung der Orginalreports ggf. nicht mitbekommen.

**Comment by aschempp** [comment]
In 2.4 gibt es nun ein Dropdown zur Auswahl des Report-Feldes.
