### ISSUE TITLE
weitere Diagramm-Typen für Isotope-Reports

### ISSUE THREAD

**Issue by error08** [isotope/core#1621]
Aufnahme weiterer Diagramm-Typen z.B. Pie-Charts. Würde gerne Pie-Charts für diverse Auswertung nutzen. z.B. die Aufzeilung der verkauften Produkte nach Produkttypen. xCharts unterstützt solche von Haus aus nicht. Macht es Sinn eine andere Chart-Library zu implementieren wie z.B. chartjs.org oder NVD3.org? Könnte hierzu auch Unterstützung anbieten.

**Comment by aschempp** [comment]
Nach meinem Wissen verwendet xCharts intern bereits D3, die benötigten JS-Dateien sollten also bereits vorhanden sein.

**Comment by error08** [comment]
D.h.? Eine weitere Bibliothek kann implementiert werden oder die vorhanden getauscht?

**Comment by aschempp** [comment]
Ich bin mir nicht sicher was du meinst. **Ich** habe aktuell nicht vor die Bibliothek zu tauschen, weil sie meinen Anforderungen genügt. Wenn du aber einen Pull Request für weitere Reports machen willst, kannst du gerne eine andere Bibliothek vorschlagen.
