### ISSUE TITLE
Änderungen in iso_list_default.html5 werden nicht aktiv

### ISSUE THREAD

**Issue by NinaG** [isotope/core#1622]
Isotope 2.3.4 Build 6
Contao 3.5.8

Ich habe einen ganz aktuellen Isotop-Shop mit einem modifizierten iso_list_default.html5 Template in einem Template-Unterordner (Theme und List-Modul verweisen darauf). Trotz leeren aller Caches in Contao, sowohl testweise Browserwechsel, etc. reagiert die Listenansicht nicht auf die Modifikationen.

Die Änderungen im reader-Template hingegen werden sofort erkannt und umgesetzt.

**Comment by NinaG** [comment]
Ich glaube, es hat sich erledigt. Es gab noch einen zweiten Template-Ordner in dem auch eine iso_list_default zeigte. Auch wenn das Shop-Layout nicht darauf verwiese, hat der Shop scheinbar dennoch darauf zugegriffen. Ich habe den Ordner gelöscht und voilá, der Shop reagiert aufs richtige Template.

**Comment by aschempp** [comment]
Du hast wohl in der Shopconfig darauf verwiesen ;-)

**Comment by NinaG** [comment]
Jau. Dummer Fehler :)
