### ISSUE TITLE
Attribute type textarea is limited to 64KiB

### ISSUE THREAD

**Issue by tsarma** [isotope/core#1623]
Please make attribute of type textarea as MySql MEDIUMTEXT. Because very long product specification table can not be stored in MySql TEXT.

Isotope\Model\Attribute\TextArea
```php
 $arrData['fields'][$this->field_name]['sql'] = "mediumtext NULL";
```

**Comment by Toflar** [comment]
I think we should not do this. It's wrong to just use up database space, if it's not needed.

@aschempp if we changed all the

```php
$arrData['fields'][$this->field_name]['sql'] = 'whatever';
```

to

```php
if (!isset($arrData['fields'][$this->field_name]['sql'])) {
     $arrData['fields'][$this->field_name]['sql'] = 'whatever';
}
```

in Isotope 2.4, @tsarma could just adjust his `dcaconfig.php` to make this change?

**Comment by tsarma** [comment]
OK thanks for alternative suggestion, it works too.
