### ISSUE TITLE
Geschütztes Leerzeichen bei Währungssymbol

### ISSUE THREAD

**Issue by mecintosch** [isotope/core#1628]
In der Shopkonfiguration kann das Leerzeichen aktiviert werden.
Aber sollte es nicht ein geschütztes Leerzeichen (`&nbsp;`) sein und nicht ein normales?
Währung und Preis sind doch eine Einheit und sollten immer beieinander stehen.

Vor allem im Warenkorb wird oft die Wärung und der Preis getrennt da wenig Platz in der Breite.

**Comment by aschempp** [comment]
Closing in favor of #1634
