### ISSUE TITLE
Error in logic for Isotope Upgrader To0020010064.php

### ISSUE THREAD

**Issue by blairwinans** [isotope/core#1632]
The variable `$arrUpdate` gets overwritten when there are multiple mediaManager fields. It should be moved up before the `foreach`.

See [Isotope/Upgrade/To0020010064.php#L43](https://github.com/isotope/core/blob/master/system/modules/isotope/library/Isotope/Upgrade/To0020010064.php#L43)

**Comment by aschempp** [comment]
oh well… :see_no_evil:
