### ISSUE TITLE
Product List: number of columns as CSS class

### ISSUE THREAD

**Issue by cs1982** [isotope/core#1636]
It would be helpfull, if the number of cols (defined in module) is represented as CSS class in mod_iso_productlist.

e.g.:
1col, 2col, ..., ncol.

Workaround: manually defined class

**Comment by cs1982** [comment]
Oh, the workaround means to define a CSS class in module. This does not work. The in the module Product List defined CSS class is not shown in FE.
The class in Article Element "Module" works.

**Comment by aschempp** [comment]
There should already be classes generated? `col_0, col_1, col_first, col_last` etc?

**Comment by aschempp** [comment]
I'm closing this due to no feedback.

**Comment by cs1982** [comment]
Sorry for late response.
I mean, it should be usefull, if the total number of columns would be an css class. Not a counter, the configured number of columns. So it would be possible to define css with releative width for the expected cases. eg: 2 cols -> 50%, 3 cols -> 33%, 4 cols -> 25%

**Comment by aschempp** [comment]
I think that *number of columns* is very much outdated in a responsive world…
