### ISSUE TITLE
Translations: Round brackets are beeing ignored

### ISSUE THREAD

**Issue by eBlick** [isotope/core#1637]
Translation entries that include round brackets within the origin language are beeing ignored and not translated.
It works with square brackets.

**Comment by aschempp** [comment]
Aah, our beloved input encoding… thanks for reporting :D

**Comment by aschempp** [comment]
Are you using Isotope 2.3 (latest version)?

**Comment by eBlick** [comment]
Yes, Version 2.3.4 Reference: 49a3f45a
