### ISSUE TITLE
product image link target should open in lightbox

### ISSUE THREAD

**Issue by eBlick** [isotope/core#1642]
In a project wie have products images that use link-target to display a different product image.
This image currently opens in a new tab due to the "target="_blank" tag in the specific gallery-template.

Is there any chance to open these images in a lightbox like the "normal" images within the current page?

Inserting these images with a second module (customized gallery  template) via insert tag does not work because changing variants will not change the  variant images.

**Comment by aschempp** [comment]
Please refer to the community forums for questions and support. The issue system is for bug reports and feature requests.

**Comment by eBlick** [comment]
Sorry for this misunderstanding. It was meant to be a feature request.
Of course we are building a workaround in order to manage this gallery behavior at present.

The handling of the MediaManager fields is rather limited. Therefore I suggest to add the title attribute as well as the selection to open it either in the same window, a new window or in a lightbox.
Also the possibility to add images from the file management rather than upload them would be very helpful.
