### ISSUE TITLE
Translation Issue: Product Image title / alt not translated

### ISSUE THREAD

**Issue by eBlick** [isotope/core#1643]
We added additional image attributes (type Media Manager) and captured alt-tags and titles to the uploaded images.
These are not beeing translated into other languages.
Example:

![bildschirmfoto 2016-04-16 um 17 21 39](https://cloud.githubusercontent.com/assets/6641281/14581940/bf0c08fa-03fa-11e6-8127-77d87b76d6ee.png)

![bildschirmfoto 2016-04-16 um 17 22 39](https://cloud.githubusercontent.com/assets/6641281/14581942/cdb0f7bc-03fa-11e6-99d1-a866eaa31a60.png)

Output is still german on the dutch website:

![bildschirmfoto 2016-04-16 um 17 46 30](https://cloud.githubusercontent.com/assets/6641281/14582063/365aee76-03fb-11e6-87a3-c5c52fdafa6e.png)

**Comment by aschempp** [comment]
If you set the radio to "all", then you must re-add the pictures (and labels) in each language. Set it to "Text" to translate in each language of a product. I can't see whether you correctly added the translated values in that picture…

**Comment by aschempp** [comment]
Is there any further information? Otherwise I'll need to close this ticket…
