### ISSUE TITLE
Demo SQL Script is broken

### ISSUE THREAD

**Issue by francwalter** [isotope/core#1646]
Hallo
there is that [demo site](https://isotopeecommerce.org/de/demo.html) where I can download a whole contao install with a working isotope.
But the SQL-Script in [the isotope_demo_2.3.4.zip](https://isotopeecommerce.org/files/demo/isotope_demo_2.3.4.zip) (or the tar.gz), the file isotope_ecommerce.sql is not working.
It will not INSERT INTO `tl_files` ... because there must be some encoding problem when saving that file.
MySQL says: 
`Duplicate entry 'B?{?U\xA5\x11?(\xBC0[5g?' for key 'uuid'`

Could somebody fix it and upload a working sql?
Thanks.

frank

**Comment by francwalter** [comment]
When I use the commandline on Mac and also on PC this script is working!
I mean:
`mysql -u root -p isotope < /path/to/isotope_ecommerce.sql`
But not with any know by me tool for Mysql Queries (Toad, Workbench or the old MySQL QueryBrowser) which are set all to utf8 by the way.
But I can backup then with MySQL Administrator the db and this skript then I indeed can restore successful, so it must be some encoding thing.

**Comment by fritzmg** [comment]
Yes, as mentioned in the forum, the binary fields were not exported in hexadecimal notations, which can lead to such problems.

**Comment by francwalter** [comment]
You mean this thread in the german forum: [Isotope Demo installiert - CSS fehlt anscheinend](https://community.contao.org/de/showthread.php?62328-Isotope-Demo-installiert-CSS-fehlt-anscheinend&p=407271&viewfull=1#post407271)

**Comment by netzarbeiter** [comment]
Can you please try it with the following copy?

[isotope_ecommerce.sql.gz](https://github.com/isotope/core/files/246408/isotope_ecommerce.sql.gz)

**Comment by francwalter** [comment]
Yes, this works! I imported it with Toad for Mac and no errors. The blob are with hex, this is better. Thanks.
