### ISSUE TITLE
Auswertung: Gutscheine werden nicht berücksichtigt

### ISSUE THREAD

**Issue by valentin-** [isotope/core#1647]
In der Auswertung werden Bestellungen mit Gutscheincodes mit dem Wert ohne Code gerechnet.

**Beispiel:**
- Bestellung 1: 499
- Bestellung 2: 499
- Bestellung 3: 199 (mit Gutscheincode, sonst 499)

**Auswertung:**
499 * 3 / 1,2 (MwSt.) = 1247,5

**Richtig wäre:**
(499*2 + 199) / 1,2 (MwSt.) = 997,5

![bildschirmfoto 2016-05-04 um 09 27 10](https://cloud.githubusercontent.com/assets/90033/15007708/3ffcc556-11db-11e6-901c-2066465c1dae.png)
![bildschirmfoto 2016-05-04 um 09 27 00](https://cloud.githubusercontent.com/assets/90033/15007710/4323787e-11db-11e6-856f-105adbac5364.png)

**Comment by aschempp** [comment]
Der Report "pro Produkt" rechnet mit den Produktpreisen und ignoriert alle Zu- oder Abschläge (auch Versandkosten etc.). Aus meiner Sicht ist der Report daher korrekt.
