### ISSUE TITLE
Select-Menü vergibt Option-Attribut falsch

### ISSUE THREAD

**Issue by Irontale** [isotope/core#1649]
Beim erstellen von zwei Produkt-Varianten wird folgender Code ausgegeben:

`<select class="select mandatory" name="printer" id="ctrl_printer_fmd11_product_3" required="">`
`	<option value="">Bitte auswählen</option>`
`	<option value="1" selected="">ohne Drucker</option>`
`	<option value="2" selected="">mit Drucker</option>`
`</select>`

Durch das `selected` bei den beiden Optionen kann es sich nicht entscheiden und zeigt immer automatisch die letzte Option an, normalerweise sollte ja "Bitte Auswählen" als Standardoption festgelegt sein. Entfern ich manuell die beiden selected-Attribute passt alles.

![isotopeecommerce_selected_issue](https://cloud.githubusercontent.com/assets/6862218/15421343/056879d6-1e73-11e6-9179-1333bd905687.png)

**Comment by Irontale** [comment]
Es liegt am Bootstrap Template _formhelper_element_select.html5_.

if(in_array($option['value'], $this->element->getValue(true))) {
	$child->setAttribute('selected', true);
}

Konnte bisher aber noch keine Lösung finden.

**Comment by Irontale** [comment]
Wäre es denkbar möglich, dass bei den Optionen fehlerhafte Werte übergeben werden, die von contao-bootstrap richtig interpretiert werden?

**Comment by aschempp** [comment]
Die Frage kann ich leider nicht beantworten.
