### ISSUE TITLE
Falsche Preisanzeige in Produkt-Detail-Ansicht bei Änderung  Variante (Contao 3.5.12 /Isotope 2.3.5/5)

### ISSUE THREAD

**Issue by kissinger99** [isotope/core#1651]
Hallo!

Die Produkte in meinem Shop haben 4 Varianten. Es gibt aber nicht alle Kombinationen von Varianten.

Wenn ich im SELECT eine Variante auswähle die nicht zu den anderen 3 angezeigten Varianten passt, also diese Kombination nicht existiert, sollte doch eine mögliche Variante mit zugehörigem Preis angezeigt werden (so habe ich das im Forum gelesen).

Aber es wird nicht der richtige Preis angezeigt.

Ist das ein Fehler oder woran liegt das?  

Vielen Dank!

**Comment by aschempp** [comment]
Ich verstehe leider nicht ganz. Kannst du etwas konkreter beschreiben (z.B. Varianten) und ggf. einen Screenshot hinzufügen?

**Comment by kissinger99** [comment]
Hallo Andreas,
 
danke für Deine Antwort.
 
Hier ist der Link zum Testshop, da kannst du es dir anschauen:
 
http://shop.clever-house.de/cenovkove-listy-k-nalepeni/cenovkova-lista-dbr.html
 
Ändere mal bitte das erste SELECT-Feld (19mm usw.)
 
24mm -> Preis 13 Kc ist ok
 
33mm -> Preis 19 Kc ist ok
 
55mm -> Preis 10 Kc  ist falsch, die Kombination 55mm und 9mm ploch paska 
(3. SELECT-Feld) existiert nicht.
 
Im Feld werden die beiden für 55mm möglichen Werte 12 mm ploch paska und 
12mm penova paska angezeigt.
 
Aber der Preis für die angezeigte Variantenkombination ist falsch.
 
Der richtige Preis ist 27 Kc, der wird aber erst angezeigt wenn du z.B. die 
Länge 1000mm oder 1250 mm änderst.
 
Ich hoffe ich habe mich jetzt verständlicher ausgedrückt.
 
Vielen Dank!
 
Rüdiger Hössel
RH-Web-Service
 
 
 
 
-----Original-Nachricht-----
Betreff: Re: [isotope/core] Falsche Preisanzeige in Produkt-Detail-Ansicht 
bei Änderung Variante (Contao 3.5.12 /Isotope 2.3.5/5) (#1651)
Datum: 2016-05-26T09:02:28+0200
Von: "Andreas Schempp" <notifications@github.com>
An: "isotope/core" <core@noreply.github.com>
 
 
 
Ich verstehe leider nicht ganz. Kannst du etwas konkreter beschreiben (z.B. 
Varianten) und ggf. einen Screenshot hinzufügen?
—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/isotope/core/issues/1651#issuecomment-221793273>
 
﻿

**Comment by aschempp** [comment]
Welche Isotope-Version verwendest du? Isotope zeigt normalerweise immer eine leere Option an, ohne funktioniert es nicht korrekt.

**Comment by kissinger99** [comment]
Hallo Andreas!
 
Ich verwende die neuste Isotope-Version 2.3.5 / Build 5
 
Muss ich, damit es funktioniert, irgendwas anpassen oder ändern?
 
Beste Grüße!
 
Rüdiger Hössel
RH-Web-Service
 
 
 
 
-----Original-Nachricht-----
Betreff: Re: [isotope/core] Falsche Preisanzeige in Produkt-Detail-Ansicht 
bei Änderung Variante (Contao 3.5.12 /Isotope 2.3.5/5) (#1651)
Datum: 2016-05-26T12:29:51+0200
Von: "Andreas Schempp" <notifications@github.com>
An: "isotope/core" <core@noreply.github.com>
 
 
 
Welche Isotope-Version verwendest du? Isotope zeigt normalerweise immer 
eine leere Option an, ohne funktioniert es nicht korrekt.
—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/isotope/core/issues/1651#issuecomment-221835437>
 
﻿

**Comment by kissinger99** [comment]
Hallo Andreas!

Ich habe nun in jedem Attribut eine leere Option eingefügt und es funktioniert jetzt.

Allerdings passen 2 Sachen nicht:

1) Die Reihenfolge in welcher zum Auswählen einer Option aufgerufen wird. Wenn ich die erste Option auswähle, werde ich zur Auswahl des dritten Elements aufgefordert. Es sollte ja das zweite folgen. Wenn ich die Reihenfolge der Attribute ändere, das gleiche Resultat.

2) Wenn nur noch ein SELECT zum Auswählen übrig ist kommt keine Meldung.

Du kannst dir das auf der Testpage anschauen.

Vielen Dank!

**Comment by aschempp** [comment]
Es scheint deine Probleme liegen nicht an Isotope sondern deiner Konfiguration. Wende dich dazu bitte ans Contao Community Forum (https://community.contao.org) oder melde dich für den Isotope Circle (https://circle.isotopeecommerce.org) an.
