### ISSUE TITLE
Item option not translated in PDF document

### ISSUE THREAD

**Issue by qzminski** [isotope/core#1653]
When generating the PDF document the item options do not seem to be translated, although the global language is set correctly. The line that responsive for it is:

https://github.com/isotope/core/blob/master/system/modules/isotope/library/Isotope/Model/ProductCollection.php#L1488

I have used the following workaround:

```php
$data['options'] = Translation::get(Isotope::formatOptions($item->getOptions()));
```

I am not sure if it's really a bug or if I am missing something, so reported as an issue and not PR.

**Comment by aschempp** [comment]
Are you sure this needs fixing? The options are stored in the language the order was placed, so they should already be correct?

**Comment by qzminski** [comment]
Sorry, can no longer reproduce this.
