### ISSUE TITLE
Backport paymentForm()

### ISSUE THREAD

**Issue by richardhj** [isotope/core#1654]
Isotope 1 provided the function ```paymentForm()``` for payment methods to include a payment condition form for example (see screenshot).
As I noticed, this method was dropped with Isotope 2. I studied all existing payment methods to find a way to integrate this form. The ```checkoutForm()``` will not help in this case as it will be shown after the checkout process.

### Screenshot
![bildschirmfoto 2016-05-30 um 22 11 20](https://cloud.githubusercontent.com/assets/1284725/15657695/786daa30-26b3-11e6-939f-2ce6250b8d4d.png)

**Comment by aschempp** [comment]
This feature has been dropped because its not necessary. You should add your own checkout step to the payment page and handle payment selection using some javascript (show/hide your form).
