### ISSUE TITLE
Cart Module: CSS ID and Class are not shown in html

### ISSUE THREAD

**Issue by cs1982** [isotope/core#1655]
If I define an css id or class in the cart module, the value is not put out in html. It tried it with standard templates too, without effect.
I updated to C 3.5.15 and I2.3.5 several days before and believe it did work with the previous versions.
Is it an Isotope or Contao issue?

**Comment by cs1982** [comment]
If I define the css id/ class in the content element 'module cart', the output is like expected.

**Comment by aschempp** [comment]
CSS ID and class are not inherited from module to content element in Contao 3. thats the standard behavior. It has been changed in Contao 4, you could update your installation to benefit from that.
