### ISSUE TITLE
[2.3.5] Verknüpfte Kategorien werden im Frontend nicht geupdated bzw. angezeigt 

### ISSUE THREAD

**Issue by siegelsupport** [isotope/core#1656]
Nach Update von Contao auf 3.5.12 mit Isotope 2.3.5 werden Änderungen bzw. neue Hinzugefügte Produkte in den verknüpften Kategorien nicht mehr dargestellt bzw. umgesetzt. In der DB kommt alles an, im Frontend leider nicht.

**Comment by aschempp** [comment]
Aus der Fehlerbeschreibung kann ich leider nicht erkennen warum. Bei mir funktioniert die Zuweisung. Vielleicht hast du keinen Preis im Produkt, nicht veröffentlicht etc?

**Comment by aschempp** [comment]
Hast du mir noch weitere Informationen? Andernfalls muss ich das Ticket schliessen…

**Comment by siegelsupport** [comment]
Ich versuche die nächsten Tage nochmal weitere Informationen zu liefern. Das Problem besteht jedenfalls noch. Bsten Dank für Dein Nachfragen.

**Comment by siegelsupport** [comment]
es tut mir leid, das war wohl meine eigene Blödheit, ich habe tatsächlich nie den cache gelöscht. es geht natürlich alles. sorry
