### ISSUE TITLE
Paypal Endpunkte geändert

### ISSUE THREAD

**Issue by baumannsven** [isotope/core#1657]
Bei Paypal haben sich die Endpunkte geändert.

https://github.com/isotope/core/blob/master/system/modules/isotope/library/Isotope/Model/Payment/Paypal.php#L50

alte Zeile:
$objRequest->send(('https://www.' . ($this->debug ? 'sandbox.' : '') . 'paypal.com/cgi-bin/webscr?cmd=_notify-validate'), file_get_contents("php://input"), 'post');

neue Zeile:
$objRequest->send(('https://ipnpb.' . ($this->debug ? 'sandbox.' : '') . 'paypal.com/cgi-bin/webscr?cmd=_notify-validate'), file_get_contents("php://input"), 'post');

Beschreibung von Paypal:
Die Endpunkte ipnpb.paypal.com und ipnpb.sandbox.paypal.com akzeptieren nur HTTPS-Verbindungen. Wenn Sie zurzeit www.paypal.com benutzen, sollten Sie zu ipnpb.paypal.com wechseln, sobald Sie Ihren Code aktualisieren, um HTTPS zu nutzen.

Ist im Shop getestet worden und funktioniert.

**Comment by aschempp** [comment]
Funktioniert aber dann nur über HTTPS, und die bestehenden auch über HTTP. Wenn wir das einfach ändern würden bestehende Shops ohne SSL nicht mehr funktionieren…?

**Comment by baumannsven** [comment]
Dann würde ich das so lösen.

$subdomain = 'www';
if (protocol === 'https'){
  $subdomain = 'ipnb';
}

$objRequest->send(('https://' . $subdomain . '.' . ($this->debug ? 'sandbox.' : '') . 'paypal.com/cgi-bin/webscr?cmd=_notify-validate'), file_get_contents("php://input"), 'post');

**Comment by baumannsven** [comment]
Ich habe Paypal kontaktiert sobald ich näheres weiß was die IPN angeht werde ich es hier mitteilen

**Comment by baumannsven** [comment]
Habe nun alle Informationen gesammelt was die Endpunkte von Paypal angehen.
Der ipnpb.paypal.com Endpunkt ist ausschließlich vor Shops mit SSL Zertifikat. Daher müsste man es wie oben in der vorgeschlagenen If Schleife realisieren.

@aschempp

**Comment by aschempp** [comment]
Funktioniert denn TLS nicht mit der WWW-Adresse? Weil nach meinem Wissen nutzen das sicherlich sehr viele bereits jetzt schon?

Ausserdem kommt bezüglich PayPal bzw. allgemein Anforderungen einiges auf uns zu: https://www.paypal-knowledge.com/infocenter/index?page=content&widgetview=true&id=FAQ1913&viewlocale=de_DE

**Comment by aschempp** [comment]
Ich habe mich nochmals mit dem Thema beschäftigt und festgestellt dass wir gar kein Problem haben, da wir schon immer nur HTTPS verwenden. Ich dachte erst es ist abhängig von der Webseite 😎 

Die URL ist in Isotope 2.4 entsprechend angepasst. Relevante Infos: https://www.paypal-knowledge.com/infocenter/index?page=content&widgetview=true&id=FAQ1916&viewlocale=de_DE
