### ISSUE TITLE
Google Analytics - Kleiner Bug

### ISSUE THREAD

**Issue by baumbaTz** [isotope/core#1660]
Wenn man in Shop-Konfiguration -> Konfigurationen eine Konfiguration bearbeitet und unten das Google Analytics Ding aufklappt, nichts eintippt und dann wieder zuklappt lässt sich diese Konfiguration nicht mehr speichern.

Nur wenn man irgendetwas in das Feld "Konto" eintippt kann man wieder speichern.

Ich vermute mal sobald das Feld aufgeklappt war wird das "Konto" Feld geprüft, egal ob es aktiviert ist oder nicht?

bisdenndann
björn

**Comment by Toflar** [comment]
Ich glaube das ist der html5 not focussable validation Fehler, der nichts mit Isotope zu tun hat. Das dürfte bei anderen Contao Masken auch der Fall sein. Ist Contao aktuell?

**Comment by baumbaTz** [comment]
Hmmm. Mag natürlich sein. Contao Version ist 3.5.12 und Isotope ist Version 2.3.5 aus dem Erweiterungskatalog.

**Comment by Toflar** [comment]
https://github.com/contao/core/issues/8192 - guck mal in der Browserkonsole ob du auch das "not focusable" kriegst, dann ist es definitiv das gleiche Problem und wir können das Ticket hier schliessen.

**Comment by baumbaTz** [comment]
Ja ist das gleiche Problem. Kann hier also geschlossen werden. Danke :)
