### ISSUE TITLE
Product Reader - Navigation active class

### ISSUE THREAD

**Issue by Irontale** [isotope/core#1661]
Situation:
Opening a page, containing a product list and a product reader. The li-element of the opened navigation gets a `active` class.

When you now open a product, the `active` turns into a `trail`. So far so good. But theres no other active appearing? The `trail` ends in an open end. I don't have any options to show the user his current position on my site.

Theoretically you are still on the same page. So why can't the `active` still be on the same position, when you open the product details?

**Comment by aschempp** [comment]
In my opinion, because the current product does not have a navigation item. The category page is the parent of the product (therefore it has a `trail` class). But feel free to discuss, I'm open to opinions :)

**Comment by Irontale** [comment]
I understand the idea of the parent page, but shouldn't there be always a `active` class? I thought the concept behind a `trail` is to end in an `active`?

I had a look at the news module, and figured out it follows the same idea of the parent page:
http://demo.contao.org/en/news.html (active)
http://demo.contao.org/en/news-detail/new-contao-versions-in-short-intervalls.html (trail, no active)

**Comment by aschempp** [comment]
The news do not work the same as Isotope, we spend some great thoughts in improving that concept. There must not always be an active page in the navigation, like if the active page is checked to "hide in navigation" (as u usually do with a reader page) it would result in the same.

**Comment by Irontale** [comment]
I see. But then there's no unique point of identifying, in which product list / category you currently are.

Concrete:
I am using `isActive` in the navigation template to set my current location in a drilldown menu. I am doing this by adding a class to the active li-element. That's the point where I noticed the missing `active` when opening the product details. I don't want to change your idea of handling the list / reader problem, but is there any alternative to mark the corresponding li-Element (last trail)?

```
root
|_ products (trail)
	|_ category1 (active)	<- current li

root
|_ products (trail)
	|_ category1 (trail)	<- current li?
		|_ product1
```

**Comment by Irontale** [comment]
Problem solved. I figured out that the position mark doesn't have to be unique. So I just checked for isTrail or isActive to attach the class to all the li-Elements.

But I am still not 100% sure about the idea behind trail / active. Basically you are still on the same page (list + reader).

**Comment by aschempp** [comment]
Technically you are (mostly, depending on your setup), but from a user perspective you're not.

**Comment by Irontale** [comment]
True. Thank you anyway. :-)
