### ISSUE TITLE
[2.3.5] Bug - PostFinance PSP

### ISSUE THREAD

**Issue by HumanDigital** [isotope/core#1662]
Beim Bezahlungsprozess wird unter anderem auch die Telefonnummer der Billing-Address an PostFinance weiter gegeben. Wenn in der Telefonnummer eine runde Klammer enthalten ist, läuft die PostFinance auf einen Fehler.
Das Problem aus unserer Sicht ist, dass wir im Registationsprozess oder beim Anlegen einer neuen Versandadresse beim Telefonnummer-Feld, contaoseitig nicht unterbinden können, dass Klammern eingefügt werden, da die Eingabeprüfung "Telefonnummer" runde Klammern erlaubt.

Wir haben als Abhilfe in der Datei PSP.php, in der Funktion preparePSPParams() OWNERTELNO, einen Regex eingefügt, der uns nur die Zahlen durchlässt, ist aber halt eben nicht updatesicher...

Wir würde uns freuen, wenn in der nächsten Version ein solcher Filter drin wäre.
Vielen, vielen Dank für Eure super Arbeit. Wir haben viel Freude am Shop.

**Comment by aschempp** [comment]
Könnt ihr die nötigen Änderungen bitte als Pull Request zur Verfügung stellen?

**Comment by HumanDigital** [comment]
Hallo Andreas

Können wir, ist aber noch eine quick und dirty Lösung…
Dann würde ich noch genau herausfinden wollen, was die PSP zulässt.
Da wir zur Zeit grad in der Arbeit ersaufen, brauchen wir dafür etwas Zeit … kommt aber ;-)

Vielen Dank.
Lieber Gruss
Christoph

**Comment by aschempp** [comment]
*ping*

**Comment by HumanDigital** [comment]
Hallo Andreas, 

ich habe am 11. August in Github einen Branch erstellt, die Anpassung gemacht,  und einen Pull Request gemacht mit einer Nachricht an Dich.
Als ich das abgeschickt habe konnte ich meinen Anpassungen sehen … wenn ich jetzt den Pull Request  aufrufe, sehe ich nur noch die Nachricht an Dich, aber nicht mehr die Änderungen im Quellcode …

Ist der Pull Request wie gewünscht bei Dir angekommen oder fehlt da noch was …

Vielen Dank für kurze Info

Liebe Grüsse
Heidi

HumanDigital GmbH • webDevelopment - macSupport - voipTelefonie
Seestrasse 29 | 8846 Willerzell SZ | Telefon 044 770 32 08
team@humandigital.ch | www.humandigital.ch <http://www.humandigital.ch/>

**Comment by aschempp** [comment]
Ich habe leider keinen Pull Request bekommen, kannst du den nochmals machen?

**Comment by Toflar** [comment]
Ist kein PR, der Commit wurde aber referenziert: https://github.com/HumanDigital/core/commit/c2070301a1f2aff470971a62e5b387e362be56e0

**Comment by HumanDigital** [comment]
Hallo Ihr Lieben, 

anbei ein Screenshot von dem, was ich auf GitHub sehe …
Könnt Ihr anhand dessen sehen, was ich tun muss, damit es für Euch ein Pull Request ist?


Danke vielmal
und liebe Grüsse

Heidi





Danke vielmal
und liebe Grüsse

Heidi

HumanDigital GmbH • webDevelopment - macSupport - voipTelefonie
Seestrasse 29 | 8846 Willerzell SZ | Telefon 044 770 32 08
team@humandigital.ch | www.humandigital.ch <http://www.humandigital.ch/>

**Comment by aschempp** [comment]
Übernommen in e4965b90710316a3148f0dd7325a6482384dc4d0
