### ISSUE TITLE
Select-Menu trigger change

### ISSUE THREAD

**Issue by Irontale** [isotope/core#1663]
Hey,
I am using a select plugin to hide the original variant select menu and display a searchable dropdown. I triggered the change of the original variant select menu when a option is selected but it won't change at all. Did I just overlook something or is this a bug?

**Comment by aschempp** [comment]
Isotope reloads the content of a product if a variant is selected, so your script might need to handle that.

**Comment by Irontale** [comment]
And how am I supposed to reload the content of a product via JS?

**Comment by aschempp** [comment]
Isotope does the reload. Implementation depends on your website, I can't tell you how to develop your extensions. As an example, if you use jQuery, you could register on the global ajax events (see http://andys-imac.local:51067/Dash/abylcyob/api.jquery.com/category/ajax/global-ajax-event-handlers/index.html)

**Comment by Irontale** [comment]
It's not an extension. I implemented [select2](https://select2.github.io/) to make the select-menu searchable. Now I need to trigger / activate Isotope and tell it to reload the product content or do I have to do it all the way via ajax? Btw your link is not working.

**Comment by aschempp** [comment]
Isotope is using the standard change event of select menus, so maybe your script should trigger them.

**Comment by Irontale** [comment]
Now we are talking! ;)
I already added my own `change` listener to check for a successfull trigger of the original select-menu but the only result I get is the console output I made.

```
(function($) {
	$(document).ready(function(){
		// init of the select2-plugin
		$('select').select2();
		
		// add event handler when a result of the select2-menu is clicked
		$('select').on('select2:select', function (obj){ 
		
			// trigger change event on the original select-menu
			$(obj.currentTarget).change(); 
			
		});
		
		// change event handler of the original-select menu
		$('select').change(function(event) { 
			console.log(event.currentTarget);
		});
	});
})(jQuery);
```

**Comment by Irontale** [comment]
fun fact: I also used the select2-menu with the filter sorting menu and it's working flawlessly.

**Comment by aschempp** [comment]
I'm sorry but I can't assist you in how to fix your local problem. This issue tracker is for bugs and feature requests in Isotope, please use the [Contao Community Forums](https://community.contao.org) or [Isotope Circle](https://circle.isotopeecommerce.org) for questions.

**Comment by Irontale** [comment]
Thank you for your help. I already opened a [topic](https://community.contao.org/de/showthread.php?62658-Select-Plugin-Event-Weiterleitung) (written in german) a few weeks ago @ Contao Community Forums but no response so far. I wouldn't have gone here otherwise, because I really don't get why the change event won't trigger an update.

**Comment by aschempp** [comment]
Looks like noone has some free time available to help you out :-(
I suggest to try other forums like StackOverflow (maybe there's a support forum for Select2), try to understand the Select2 code or find a developer who does that for you.
