### ISSUE TITLE
Menge auf der Artikelseite wird nicht aktualisiert / Amount on the product page is not updated

### ISSUE THREAD

**Issue by koopoo69** [isotope/core#1664]
Leider wird die Mengenangabe auf der Artikelseite/Produktdetailseite nicht aktualisiert so wie es auf der Warenkorbseite der Fall ist. 

Unfortunately, the amount indicated on the product page / product detail page is not updated as it is the case on the shopping cart page.

**Comment by aschempp** [comment]
Das ist bisher auch nicht vorgesehen. Der angezeigte Preis entspricht dem Produktpreis und nicht dem Totalpreis.

**Comment by koopoo69** [comment]
Danke für die Information.
