### ISSUE TITLE
[2.3.5] "Import assets" with subfolders not working correctly(?)

### ISSUE THREAD

**Issue by design23** [isotope/core#1666]
I have created the folder "images" with several subfolders included. 
Structure looks like this:

images (main folder)
  _CD-180R (subfolder)
  CD-180RM (subfolder)
  CD-180RR (subfolder)
  ..._

In the subfolders are images for the product.
The product's sku matches one of the subfolders.

When I try to import assets and choose the "import" folder I just get the message "The folder did not contain any files to be imported."

Is this a bug or did I just not understand the way it works?

**Comment by aschempp** [comment]
I must confess that I have not used this feature for years. From your initial description, I would say everything was correctly set up. Are the folder names in correct capitalization?

**Comment by design23** [comment]
Ha, thought so... Am I the only one who wants to use this feature? ;-)

Yes, folders and filenames are correct (capitalization) – double and triple checked that already.

**Comment by aschempp** [comment]
Maybe related to #1670 ?

**Comment by design23** [comment]
You mean I should try to use lower case for the filenames?
At the moment, the folders and the files themselves all use upper case.

**Comment by aschempp** [comment]
Trying it wouldn't harm ;-)
