### ISSUE TITLE
Einbindung von Saferpay: Bezahlung "failed" 

### ISSUE THREAD

**Issue by laRocca** [isotope/core#1667]
Hallo,

hatte bereits im [Contao-Forum](https://community.contao.org/de/showthread.php?62596-Einbindung-von-Saferpay-Bezahlung-quot-failed-quot&p=409525#post409525) diese Frage gestellt vor einiger Zeit, aber leider keine Reaktion erhalten, deshalb versuche ichs hier…

Ich versuche gerade in meinem Shop (www.frieden-berg.de - Contao 3.5.4 + Isotope 2.3.1.9003) meine Zahlungsart "Saferpay" mit meinem Testaccount einzurichten und zu testen – hier mal meine Konfiguration des Zahlungsmittels
![attachment](https://cloud.githubusercontent.com/assets/4539461/16383663/54305760-3c86-11e6-8385-a5237c83eca6.jpg)

Im Kassen-Modul habe ich das Zahlungsmittel freigegeben und mich bei der Einrichtung der Payment Page an die [Isotope Manual](https://isotopeecommerce.org/de/hand...-saferpay.html) gehalten
![payment-page](https://cloud.githubusercontent.com/assets/4539461/16383822/f700f170-3c86-11e6-9908-f55e243e71a1.jpg)

Wenn ich im Shop die neue Zahlungsart im Warenkorb auswähle und schließlich zur Bestellübersicht gelange und dort "kostenpflichtig bestellen" klicke, werde ich nicht auf die Payment-Page weitergeleitet, sondern auf "failed.html" und erhalte eine Fehlermeldung: "Der Bezahlvorgang ist fehlgeschlagen. Bitte versuchen Sie es erneut oder wählen Sie eine andere Bezahlmethode."
**Woran könnte es liegen?
Muss ich etwas mit der API machen, die ich in Saferpay angelegt habe und wenn ja, was?**

**Comment by aschempp** [comment]
Ich kann das leider nicht direkt beantworten, aber schau mal was im Contao Backend Log und im Ordner  `system/logs` zu finden ist.

**Comment by laRocca** [comment]
Super! Da hab ich wirklich noch nicht reingeschaut. Der Log sagt:
"… das Zertifikat-Hosting nicht freigeschaltet. Bitte wenden Sie sich an service@saferpay.com, um den Zusatzdienst zu aktivieren.<br><br>The certificate hosting service is not activated for the Saferpay …"

Ich habe damit jetzt erst mal Saferpay angeschrieben.

Danke schon mal für die Antwort!

**Comment by laRocca** [comment]
Hier die schnelle Antwort des Saferpay-Supports:

> Hi, it seems that you want to use the Payment Page over the old HI (https interface). We recommend to use the JSON API, as the old interfaces won't receive new features. JSON API: http://saferpay.github.io/jsonapi/ If you insist on using the HI, you'll have to use the general test account, as the individual accounts are only supporting the new JSON API - you can find the general account here: https://www.six-payment-services.com/en/site/saferpay-support/testaccount/general_test_account.html Best regards, Claudio

Soll ich dann einfach die Saferpay Account-ID in meinem Zahlungsmittel auf die des allg. Testaccounts anpassen oder muss ich irgendwas mit der API machen?
