### ISSUE TITLE
Einbindung von Saferpay

### ISSUE THREAD

**Issue by laRocca** [isotope/core#1668]
Hallo,

im Bezug auf meine [Anfrage](https://github.com/isotope/core/issues/1667) hier nun mal der Dialog mit dem Support. Die meinen nämlich, dass evtl. Isotope Saferpay garnicht mehr einbinden kann.
Ist dem so?

![saferpay-support-dialog](https://cloud.githubusercontent.com/assets/4539461/16412888/e766de70-3d2e-11e6-8d5f-1534b4b00003.jpg)

**Comment by aschempp** [comment]
Das kann ich leider nicht beantworten. Wir wurden vor mehreren Jahren mit der Entwicklung des entsprechenden Zahlungsmoduls beauftragt, seither wurde es aber nicht weiterentwickelt, womöglich wird es vom entsprechenden Kunden gar nicht mehr genutzt. Auch haben wir keinen Auftrag von Saferpay dies aktuell zu halten. Entsprechend kann es gut sein, dass sich die Schnittstelle geändert hat und nicht mehr funktioniert.

Im Sinne von Open Source wäre es nun ideal, wenn du dich um die Behebung des Fehlers kümmern könntest, und deine Erfahrungen wieder in die Community zurück bringst (siehe auch https://www.terminal42.ch/de/open-source.html).

**Comment by laRocca** [comment]
OK, alles klar, das kann ich selbst nicht. Aber danke für die Antwort!

**Comment by aschempp** [comment]
Wende dich für Aufträge bitte per E-Mail an uns: https://isotopeecommerce.org/de/kontakt.html

**Comment by devisualgmbh** [comment]
@laRocca Hi did you found a solution for the saferpay payment module & Isotope? 
I am having the same problem. Love to hear from you

**Comment by laRocca** [comment]
No - unfortunately not. The customer didn't want to spend any money ::rolleyes

**Comment by devisualgmbh** [comment]
@laRocca Did you used another gateway? I am looking at Postfinance as an option

**Comment by laRocca** [comment]
Hello! We didn't finally use any other gateway, but I checked another one and it worked perfectly: saferpay

**Comment by devisualgmbh** [comment]
Hi, meinst du das du den paymentmodule Saferpay in Isotope nutzes?
Bin gespannt wie du das gemacht hast, weil die Testzugang von saferpay bei mir nicht funktioniert....

**Comment by laRocca** [comment]
war bei mir auch so - frag mal den technischen service an - die sind unfassbar hilfsbereit! ohne die hätte ich das auch nicht hingekriegt!

**Comment by devisualgmbh** [comment]
Aha, top. Saferpay ist schon die beste option in der Schweiz ;-)
Danke für diene hinweiss!

**Comment by laRocca** [comment]
Gerne!
