### ISSUE TITLE
Probleme mit Groß- und Kleinschreibung der Subfolders

### ISSUE THREAD

**Issue by loettgers** [isotope/core#1670]
Hallo,

wenn die Dateinamen der Produktbilder mit einem Großbuchstaben anfangen, gibt es hier ein Problem:

MediaManager.php, Zeile 449:
return 'isotope/' . substr($strFile, 0, 1) . (!$blnFolder ? ('/' . $strFile) : '');

Wäre das so nicht besser?
return 'isotope/' . strtolower(substr($strFile, 0, 1)) . (!$blnFolder ? ('/' . $strFile) : '');

Viele Grüße,
Steven

**Comment by aschempp** [comment]
Wo liegt das Problem?

**Comment by loettgers** [comment]
Also bei mir gab es Probleme:
Ich habe die Bilder mit dem Importtool zugewiesen. Wenn ich dann im Backend versucht habe, einen Datensatz zu bearbeiten, war das Bild nicht mehr vorhanden.

Beim Debuggen habe ich dann festgestellt, dass die Methode getFilePath den ersten Großbuchstaben für den Subfolder nimmt, z. B. isotope/W/W21.jpg.

Das Bild konnte dann natürlich nicht gefunden werden, da das Bild ja unter Kleinbuchstaben abgelegt wurde, isotope/w/W21.jpg.

Demnach mein Vorschlag.

**Comment by aschempp** [comment]
Meinst du mit "Import-Tool" die Funktion "Assets importieren" oder die normale Bild-hochlade-Funktion? Und verwendest du die neuste Version von Isotope (2.3.5)?

**Comment by loettgers** [comment]
Ja, genau „Assets importieren“ habe ich gemeint ;-) Isotope Version ist die aktuellste: 	2.3.5.9006.
Das tieferliegende Problem scheint zu sein, dass der Asset-Importer – im Gegensatz zum MediaManager-Widget – die Dateinamen nicht in Kleinbuchstaben umwandelt …
