### ISSUE TITLE
[2.3.4] Canonical Tag verweist auf unveröffentlichte Seiten

### ISSUE THREAD

**Issue by Mynyx** [isotope/core#1671]
Bei der Generierung des Canonical Tag für eine Produktseite wird nicht geprüft, ob die entsprechende Kategorie/Seite auf die verwiesen wird auch veröffentlicht ist, sondern es wird stets auf die oberste Seite in der Kategorienauswahl verwiesen.

**Comment by aschempp** [comment]
@qzminski apparently we do not check publishing status of a page when generating the `<link rel=cannonical` header tag. Can you investigate and fix that?

**Comment by aschempp** [comment]
Fixed in #1686
