### ISSUE TITLE
[2.3.4] Breadcrumb bei Fehlerseite wenn Produkt auf nicht veröffentlichter Seite

### ISSUE THREAD

**Issue by Mynyx** [isotope/core#1673]
Wenn ein Produkt aufgerufen wird, das sich auf einer nicht veröffentlichten Seite befindet, wird korrekt ein 404-Fehler erzeugt.

Jedoch wird das Produkt auf der Fehlerseite in der Breadcrumb-Navigation angezeigt, dies dürfte jedoch nicht sein, denn nicht gefundene Elemente werden in der Breadcrumb-Navigation grundsätzlich nicht angezeigt.

**Comment by aschempp** [comment]
Warum hast du denn eine Breadcrumb-Navigation auf der 404-Seite??

**Comment by Mynyx** [comment]
Die Breadcrumb-Navigation ist im Seitenlayout eingebunden und wird daher auch auf der 404-Seite angezeigt.

**Comment by aschempp** [comment]
Der Fehler liegt aber doch dann in dieser Konfiguration. Denn auch für alle anderen Seiten die nicht gefunden werden würde im Breadcrumb etwas sinnloses stehen?

**Comment by Mynyx** [comment]
In diesem Fall wird der Titel der Fehlerseite in der Breadcrumb-Navigation angezeigt z. B. "Seite nicht gefunden".

Der Fehler liegt bei Isotope, das eben dennoch das Produkt in der Breadcrumb-Navigation anzeigt, die Module des Contao Core arbeiten bei unveröffentlichten Seiten/Elementen korrekt.

**Comment by aschempp** [comment]
@qzminski original description says:

> if a product is assigned to a non-published page, the frontend will render a 404 error. However, the breadcrumb on that 404 page will still show the product name, because apparently the breadcrumb modifier (hook) does not check for that.

**Comment by aschempp** [comment]
Closed in favor of #1690
