### ISSUE TITLE
[2.3.5] "Elevate Zoom gallery" funktioniert nur beim ersten Produkt

### ISSUE THREAD

**Issue by MarcelBurri** [isotope/core#1674]
Wenn "Elevate Zoom gallery" in der Galerie ausgewählt wird und man diese Galerie unter "Produktetypen" / "Galerie auflisten" auswählt, funktioniert der Zoom nur auf dem ersten Produkt.

Vielleicht hängt es damit zusammen, das wenn man Produkte erstellt und da ein Bild hochlädt, dass alle Bilder die selbe ID erhalten. 

[Siehe auch: ](https://community.contao.org/de/showthread.php?63119-Probleme-mit-Produkte-Varianten-und-Zoom-Anzeige)

**Comment by Aybee** [comment]
Selbst wenn es nicht daran läge, wäre zweimal die gleiche ID auf der Seite ein Bug.

**Comment by aschempp** [comment]
@qzminski the elevate zoom gallery must not use the same CSS ID for each container, it should be related to the product ID or something.

**Comment by aschempp** [comment]
Closed in favor of #1685
