### ISSUE TITLE
[2.3.5] Automatische Preisanpassung bei Varianten funktioniert nicht

### ISSUE THREAD

**Issue by MarcelBurri** [isotope/core#1675]
Wenn man Varianten verwendet und im Frontend eine Auswahl trifft, wird der Preis nicht automatisch angepasst.

[Siehe auch](https://community.contao.org/de/showthread.php?63119-Probleme-mit-Produkte-Varianten-und-Zoom-Anzeige)

**Comment by aschempp** [comment]
In Version 2.3 musst du Mootools aktivieren damit Isotope funktionert.
