### ISSUE TITLE
[2.3.4] Produkt bearbeiten: Link zu Seitenstruktur bearbeiten auch wenn Recht fehlt

### ISSUE THREAD

**Issue by Mynyx** [isotope/core#1677]
Wird beim Bearbeiten eines Produktes bei Kategorien auf "Auswahl ändern" geklickt, öffnet sich der Dialog "Seiten auswählen". Hier wird stets ein Link "Die Seitenstruktur bearbeiten" angezeigt, auch wenn der Benutzer gar nicht über das Recht für das Modul Seitenstruktur verfügt.

**Comment by aschempp** [comment]
Besteht dieses Problem nicht an allen Stellen in Contao, zum Beispiel wenn er in einem Inhaltselement eine Seite auswählen kann?

**Comment by aschempp** [comment]
This bug should be fixed in Contao core.
