### ISSUE TITLE
Problem with MultiColumnWizard 3.3.3

### ISSUE THREAD

**Issue by memikeandi** [isotope/core#1680]
I get the following error when trying to make a new/edit a store config
`Address fields

Fatal error: Uncaught exception Error with message Function name must be a string thrown in system/modules/multicolumnwizard/MultiColumnWizard.php on line 866
#0 system/modules/multicolumnwizard/MultiColumnWizard.php(479): MultiColumnWizard->initializeWidget(Array, 0, 'name', 'label')
#1 system/modules/core/library/Contao/Widget.php(684): MultiColumnWizard->generate()
#2 system/modules/core/templates/backend/be_widget.html5(3): Contao\Widget->generateWithError(true)
#3 system/modules/core/library/Contao/BaseTemplate.php(88): include('/var/www/html/n...')
#4 system/modules/core/library/Contao/Widget.php(630): Contao\BaseTemplate->parse()
#5 system/modules/core/classes/DataContainer.php(546): Contao\Widget->parse()
#6 system/modules/core/drivers/DC_Table.php(1951): Contao\DataContainer->row('\n            {n...')
#7 system/modules/isotope/library/Isotope/BackendModule/BackendOverview.php(223): Contao\DC_Table->edit()
#8 system/modules/isotope/library/Isotope/BackendModule/BackendOverview.php(69): Isotope\BackendModule\BackendOverview->getModule('configs')
#9 system/modules/core/classes/Backend.php(423): Isotope\BackendModule\BackendOverview->generate()
#10 system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('iso_setup')
#11 contao/main.php(20): Contao\BackendMain->run()
#12 {main}`

**Comment by Toflar** [comment]
Did you install via ER2 or Composer? @davidmaack are you sure the latest version of MCW is in the ER2?

**Comment by davidmaack** [comment]
Hmm, the ER2 wasn´t up to date. I Just released the latest version of the MCW for the ER2.
@memikeandi: can you update the MCW if you are using the ER2 and give it another try?

**Comment by aschempp** [comment]
Are you maybe using PHP 7? Then you must update to the latest version of MultiColumnWizard

**Comment by Toflar** [comment]
He did, but it was not up to date in ER2.

**Comment by aschempp** [comment]
I assume this is fixed with latest MCW
