### ISSUE TITLE
BE-Filter: ID statt Name im Auswahlfeld bei Checkbox aus eigener Datenbank-Tabelle

### ISSUE THREAD

**Issue by michelbalzer** [isotope/core#1683]
Ich habe ein Checkbox-Menü-Attribut, dass sich seine Werte aus einem MetaModel holt. (Also Optionen-Quelle: Eigene Datenbank-Tabelle)

Markiere ich es als „Filterbar im Backend“ wird mir im Sortierungsfeld der BE-Produktliste die ID statt eines Titels angezeigt. Sollte sich das Feld die Bezeichnung nicht aus „Fremdtabelle und Feld“ holen? Ich habe es auch mal probehalber von `mm_bikemodel.combined_label` (combined value) auf `mm_bikemodel.title` (text) gestellt, half auch nicht.

Es ist die erste 2.4 Beta (composer siehe unten).

**Attribut-Einstellungen**
![bildschirmfoto 2016-08-08 um 17 32 47](https://cloud.githubusercontent.com/assets/1337412/17485695/af7b5826-5d8e-11e6-9e79-d3e8a447cf95.png)

**Sortierungs-Select**
![bildschirmfoto 2016-08-08 um 17 31 33](https://cloud.githubusercontent.com/assets/1337412/17485694/af7aa21e-5d8e-11e6-9df4-f39232123028.png)

**Composer**

    {
        "name": "local/website",
        "description": "A local website project",
        "type": "project",
        "license": "proprietary",
        "require": {
            "cliffparnitzky/birthday-mailer": "1.3.x-dev",
            "comolo/contao-supertheme": ">=2.3.1.0,<2.4-dev",
            "contao-community-alliance/composer-client": "~0.12",
            "contao-community-alliance/dc-general": "dev-hotfix/beta-37 as 2.0.0-beta36",
            "contao-legacy/e-spin_dcaconfig-editor": ">=1.0.0.9008,<1.1-dev",
            "contao-legacy/easyupdate3": ">=3.3.3.9005,<3.4-dev",
            "contao-legacy/frontend_editor": ">=2.2.6.9003,<2.3-dev",
            "contao-legacy/simple_columns": ">=1.6.2.9002,<1.7-dev",
            "isotope/isotope-core": ">=2.4.0.0-beta1,<2.5-dev@beta",
            "menatwork/semantic_html5": ">=1.2.0.0,<1.3-dev",
            "metamodels/attribute_select": ">=2.0.0.0-alpha11,<2.1-dev@alpha",
            "metamodels/bundle_all": ">=2.0.0.0,<2.1-dev",
            "metamodels/core": ">=2.0.0.0-alpha12,<2.1-dev@alpha",
            "terminal42/contao-mailusername": ">=1.0.5.0,<1.1-dev"
        },
        "prefer-stable": true,
        "minimum-stability": "dev",
        "config": {
            "preferred-install": "dist",
            "cache-dir": "cache",
            "component-dir": "../assets/components"
        },
        "repositories": [
            {
                "type": "composer",
                "url": "https://legacy-packages-via.contao-community-alliance.org/"
            },
            {
                "type": "artifact",
                "url": "packages"
            },
            {
                "type": "composer",
                "url": "https://legacy-packages-via.contao-community-alliance.org/"
            }
        ],
        "extra": {
            "contao": {
                "migrated": "done"
            }
        }
    }

**Comment by aschempp** [comment]
Fixed in #1693
