### ISSUE TITLE
[2.3.4] Seiten mit Modul Produktleser und Einstellung "Eine 404 Fehlerseite anzeigen" in Sitemap

### ISSUE THREAD

**Issue by Mynyx** [isotope/core#1696]
Auch Seiten, auf denen ein Modul Produktleser mit der aktivierten Einstellung "Eine 404 Fehlerseite anzeigen" eingebunden ist, werden in der Sitemap aufgelistet, obwohl diese bei Aufruf ohne Produktalias stets einen Fehler 404 erzeugen.

**Comment by aschempp** [comment]
Ich denke du müsstest die Seite als "nicht im Sitemap" konfigurieren. Isotope weis nicht auf welchen Seiten sich ein Reader-Modul befindet und kann das nicht übernehmen.

**Comment by tsarma** [comment]
I had the same problem on https://www.alporto.ch
What I did is, put following code in my custom config file

```php
/* Removing product detail page from sitemap */
$key = -1;
foreach($GLOBALS['TL_HOOKS']['getSearchablePages'] as $k => $v) {
    if($v[1] == 'addProductsToSearchIndex' ) {
        $key = $k;
        break;
    }
}

if($key !== -1) {
    unset($GLOBALS['TL_HOOKS']['getSearchablePages'][$key]);
}
```
