### ISSUE TITLE
[2.3.5] Produkte-Eingabemaske: Übersetzung Tracks und Date fehlt

### ISSUE THREAD

**Issue by Samson1964** [isotope/core#1698]
Ich schaue mir Isotope gerade zum ersten Mal an. In der Demo fiel mir das auf:
![isotope_produkte](https://cloud.githubusercontent.com/assets/4542730/18144766/93bf5f82-6fc8-11e6-95cf-43e7367b055e.jpg)
Mir war nicht klar, woher die Zahl bei Tracks kommt. Bei den Artikeln unter Database fand ich das Inhaltselement. Nach 3 Jahren Erfahrung mit Contao hatte ich sowas vermutet. Hier muß ein guter Hilfetext hin.

**Comment by Toflar** [comment]
Was hat ein Produkte-Attribut mit "Artikeln" und "Database" und erst recht mit "Inhaltselement" zu tun? Ich verstehe leider nicht mal ansatzweise worauf du hinaus willst.

**Comment by aschempp** [comment]
Das ist definitiv kein Isotope-Fehler. Bitte wende dich ans Contao Forum (https://community.contao.org)

**Comment by Samson1964** [comment]
Den oben gezeigten Screenshot erreicht man im BE über "Produkte" (Bereich Isotope eCommerce) und dort das Produkt "Mark Lanegan - Field Songs" bearbeiten. Ich hätte gedacht die beiden Felder Tracks und Date gehören zum Isotope-DCA. Bei einer Suche in den drei Isotope-Verzeichnissen habe ich sie aber nicht gefunden. 

Wiedergefunden habe ich sie in der Shop-Konfiguration unter Produkttypen:
![zwischenablage01](https://cloud.githubusercontent.com/assets/4542730/18243194/542ffc7e-735a-11e6-8317-19339c93e4d2.jpg)

Bzgl. meiner Aussage mit "Inhaltselement" meinte ich die von Euch angelegte Contao-Seitenstruktur mit der Seite "Database" und der Unterseite "Music" mit den Artikeln für die einzelnen CD's.
Im Feld "Tracks" wird die ID des Inhaltselements aus diesen Artikeln eingetragen. Genau dieser Hinweis fehlt mir als Label/Hilfetext. Ebenso natürlich auch beim Feld "Date".

Wenn die Felder Tracks und Date nicht zum Isotope-Universum gehören, dann bitte ich um Entschuldigung für mein Versehen. Wobei ich Tracks im Contao-Universum auch noch nicht im Core-DCA angetroffen habe. Aber irgendwoher muß es ja kommen.

Außerdem wäre es doch mal ganz nett im Handbuch etwas mehr auf den Workflow beim Erstellen von Produkten einzugehen und wie man Detailbeschreibungen von Produkten anlegen kann. Im Moment denke ich, geht das nur so:

1. Inhaltselement in einem Artikel anlegen
2. Die ID des Inhaltselements in das Feld "Tracks" eintragen

**Comment by netzarbeiter** [comment]
Die beiden Attribute «Tracks» und «Date» wurden für die Anzeige der Liederliste in der Demo erstellt und dienen als Beispiel für die Möglichkeiten von Isotope eCommerce. Ich werde die Dokumentation dazu in einer der nächsten Demo-Versionen verbessern.

Für Detailbeschreibungen von Produkten empfehle ich das Feld «Beschreibung [description]» im Produkttyp auszuwählen.
