### ISSUE TITLE
Category page stuck on Loading products ...

### ISSUE THREAD

**Issue by primafranko** [isotope/core#1699]
Hello guys. 

I don't know exactly how to reproduce this problem since I don't know what's causing it, but it has happened to me the second time - different sites.

I've been adding the products as usual, and all of the sudden the page that displays category A (products list) stops working - no products are loaded, only the text "Loading products ...", while the page that displays category B is working as should.

Deleting the last added products doesn't help. The only way to make it work was to create another page that will display category A and edit all the products to point to the new category page, which is a problem when you have a lot of products.

I found this thread which is something I get: https://community.contao.org/de/showthread.php?50660-Mehrsprachiger-Shop-Loading-Products

I can provide the site url of mine also, but would rather do it private.

Thanks

**Comment by aschempp** [comment]
Which version of Isotope are you using? Make sure MooTools is enabled if you're not on the latest develop from GitHub…

**Comment by primafranko** [comment]
Thanks for getting back.

Contao version 3.5.15
Isotope version 2.3.5

MooTools are enabled on the category list pages.

**Comment by aschempp** [comment]
Unfortunately I can't tell you why that happens then. Basically Isotope has an internal timer that detects if a product list takes longer than one second to render. If that happens it internally stores that page ID and the product list ID and from then on renders the "loading" message. It will then fetch the products using an ajax request. Somehow I assume this ajax request is not working correctly, you should probably ask a Javascript developer to analyze your website.

**Comment by primafranko** [comment]
This is just bizzare, that hasn't happened to me anywhere before.

I already rebuilt the site from scratch and updated from 3.4.5 to 3.5.15 and upgraded isotope from 2.2.0 to 2.3.5.

Another thing that happened was that checkout isn't working properly anymore, out of the blue. Javascript not working again..

Does someone have any clue why this is happening? How could I even trigger that? Should I have mootools enabled on every site?

**Comment by michelbalzer** [comment]
Might have something to do or is related to #1694.

I probehalber edited system/modules/isotope/templates/modules/mod_iso_productlist_caching.html5 to the changes in https://github.com/isotope/core/commit/d331fb2ee6745f40993cadc0a04133e68c72493c and tada, products were loaded some time after.

I'm on 2.4-beta1, though.

**Comment by primafranko** [comment]
Thanks for the info, will look at it for sure

**Comment by aschempp** [comment]
Looks like this is fixed then.
