### ISSUE TITLE
Option 'default variant' nicht sichtbar, bei generierten Varianten

### ISSUE THREAD

**Issue by NinaG** [isotope/core#1700]
Wenn ich eine Variante über den Link "Variante hinzufügen" anlege, habe ich die Option "default variant" mit der ich angeben kann, dass diese Variante die Standardvariante des Gesamtprodukts ist.

Wenn ich Varianten über den Link "Varianten generieren" angelegt habe und danach die Varianten bearbeiten möchte, fehlt dort diese Option. Ich vermute, dass das ein Fehler ist, da ich keinen logischen Grund für dieses Vorgehen erkennen kann.

**Comment by NinaG** [comment]
In der Variantenliste wird die Option mittels Stern-Symbol übrigens schon angezeigt, nur nicht in der Bearbeiten-Formularansicht der einzelnen generierten Variante.

**Comment by aschempp** [comment]
Hmm, das Feld "Standard-Variante" sollte eigentlich nie angezeigt werden. Warst du eventuell im Modus "Mehrere Bearbeiten"?

**Comment by aschempp** [comment]
Ich kann dies nicht reproduzieren, bei mir wird das Feld nie angezeigt, die Standard-Variante lässt sich nur über das Sternchen-Icon konfigurieren.
