### ISSUE TITLE
Insert Tag with uncached throws error

### ISSUE THREAD

**Issue by tsarma** [isotope/core#1702]
I have enabled contao page cache, and in the template fe_page i've put `{{cart::quantity|uncached}}`. Now when I open the cached page (2nd time) it throws error massage below
`Recoverable error: Argument 1 passed to Isotope\InsertTag::getValueForCollectionTag() must implement interface Isotope\Interfaces\IsotopeProductCollection, null given, called in /var/www/html/system/modules/isotope/library/Isotope/InsertTag.php on line 38 and defined in system/modules/isotope/library/Isotope/InsertTag.php on line 73`

Setup: Contao 3.5.14, Isotope 2.3.5

**Comment by aschempp** [comment]
You cannot use cached pages with Cart information on it. The cart is not available in cached mode.
