### ISSUE TITLE
Payment percentage including shipping price

### ISSUE THREAD

**Issue by sietsevandreven** [isotope/core#1703]
We came up with a problem in the Isotope webshop. We use added percentages with for example paypal and creditcard so that the user who pays with that payment method pays an additional 3 or 4,5%. For now it only calculates the percentages over price and VAT. Our problem is that we need the shipping costs in that calculation as well. This is currently not implemented, but is really a necessary part of a webshop.

**Comment by aschempp** [comment]
Unfortunately, that is currently not possible in Isotope by design. Also think about what should happen if the shipping cost is also percentage? Some might want to calculate that based on payment surcharge?

**Comment by sietsevandreven** [comment]
The webshop we are talking about sends, among other things, products outside EU. That means that shipping costs are higher than the actual product price. The payments are controlled bij a payment service provider, that service is paid, they calculate the costs over everything together, including product price and shippings costs. So we need to calculate the paypal percentages over the whole total price. Right now it only calculates over the product price.

We made a change in the Core. Not the best way to make changes but it is the only workaround available. this is the before and after code:

Before:   
   public function getPrice(IsotopeProductCollection $objCollection = null)
    {
        if (null === $objCollection) {
            $objCollection = Isotope::getCart();
        }

        if ($this->isPercentage()) {
            $fltPrice = $objCollection->getSubtotal() / 100 * $this->getPercentage();
        } else {
            $fltPrice = (float) $this->arrData['price'];
        }

        return Isotope::calculatePrice($fltPrice, $this, 'price', $this->arrData['tax_class']);
    }
              
After:     
                 public function getPrice(IsotopeProductCollection $objCollection = null)
    {
        if (null === $objCollection) {
            $objCollection = Isotope::getCart();
        }

        if ($this->isPercentage()) {
            $fltPrice = ($objCollection->getSubtotal()+$objCollection->getShippingSurcharge()->total_price) / 100 * $this->getPercentage();
        } else {
            $fltPrice = (float) $this->arrData['price'];
        }

        return Isotope::calculatePrice($fltPrice, $this, 'price', $this->arrData['tax_class']);
    }


And if you are not supporting this, is there a way to overwrite an abstract class? In that way we can make sure the custom function doesn't disappear with Contao Isotope updates.

**Comment by aschempp** [comment]
I think the best way would be to create a custom payment method that calculates the price differently. Payment methods are easily extendable.
