### ISSUE TITLE
Question: order document with product url

### ISSUE THREAD

**Issue by Irontale** [isotope/core#1704]
Hey there,
I've got following question here:
Is it possible to get a **href-tag** of each product into a order document which will be exported into a pdf? It's very pity that I can link the products in the cart or the order history but not the ones in the invoices.

**Comment by aschempp** [comment]
The template used for the invoice is exactly the same as the cart or order. Just adjust it with the necessary information. You can compate iso_collection_default and iso_collection_invoice to find the differences.

**Comment by Irontale** [comment]
Thank you, I'll test this asap.
