### ISSUE TITLE
Custom attribute shown on shopping cart page and invoice

### ISSUE THREAD

**Issue by primafranko** [isotope/core#1706]
Hi guys.

It's not actually a bug, but something I have not found anywhere and it might help someone who looks for the same answer.

Isotope does not offer a solution for multiple vendors, but that doesn't mean you can't have other people sell their products through your page. Now what I did was I added the custom attribute [seller_id], so I could tell who the product belongs too.

The problem I have right now is this:
I have to show this custom attribute somewhere, either on the backend (preferably) where pending orders are shown or on the invoice.

So right now, the backend orders page has the following attributes shown: 
Order ID 	Placed 	Billing address 	Total 	Order status

How could I add another column with my custom attribute to it?

If this one would be too hard to do, how could I add my custom attribute to the invoice? I have tried `<?php echo $this->generateAttribute('seller_id'); ?>` with no luck. It does work on the reader page though.

Thanks.

**Comment by aschempp** [comment]
Adding it to the backend view would require extensive PHP knowledge. In the invoice it should work fine, but you forgot to tell it about which product. Try this:

```php
<?= $this->generateAttribute('seller_id', $item['item']); ?>
```

**Comment by primafranko** [comment]
it works! thanks
