### ISSUE TITLE
Issue: Übersetzung für FE Attribute

### ISSUE THREAD

**Issue by Irontale** [isotope/core#1707]
Hallo,
folgendes Problem:
Jeder FE-Benutzer kann zum Produkt per Textfeld-Attribut eine Anmerkung ergänzen. Das Label wird ausgeblendet, einzig der Platzhalter wird verwendet. Bei den Attribut-Optionen gibt es die Möglichkeit "Mehrsprachig", welche laut Handbuch aber nur für das Backend ist. Ich hab die bisherigen Leerauswahl-Felder der Select-Attribute (Varianten) per "Shop Konfigruation > Verschiedenes > Übersetzungen" erfolgreich übersetzt, klappt aber beim Textfeld so nicht.

**Comment by aschempp** [comment]
Du meinst der Placeholder-Text kann damit nicht übersetzt werden?

**Comment by Irontale** [comment]
Genau. Das Placeholder-Attribut wird bei bei den Übersetzungen nicht beachtet.
