### ISSUE TITLE
Alias wird nicht aus Produktnamen generiert sondern erzeugt id-n

### ISSUE THREAD

**Issue by Lillena** [isotope/core#1708]
Bei den jüngsten Isotope-Versionen wird beim Anlegen eines Produktes nicht der Artikelname für die Aliasgenerierung verwendet sondern id-n als Alias erzeugt.

Siehe auch im Forum: https://community.contao.org/de/showthread.php?63534-alias-wird-nicht-aus-Namen-generiert

Ich selbst habe die Isotope Version 2.4.0-beta im Einsatz wo es ebenfalls der Fall ist.

**Comment by aschempp** [comment]
This will be fixed in the next release: https://github.com/isotope/core/issues/1659
