### ISSUE TITLE
[2.3.4] Bestellung vom Versand ausgeschlossenes Produkt führt zu Internal Server Error

### ISSUE THREAD

**Issue by Mynyx** [isotope/core#1710]
Bei der Bestellung eines vom Versand ausgeschlossenen Produktes tritt in der Kasse im Schritt complete ein Internal Server Error auf.

Im error.log von Contao befinden sich keine Einträge.

Wenn zusätzlich ein nicht vom Versand ausgeschlossenes Produkt bestellt wird, tritt der Fehler nicht auf.

**Comment by aschempp** [comment]
Ohne Fehlermeldung kann ich leider nichts nachvollziehen, kannst du da was liefern?

**Comment by Mynyx** [comment]
Leider nicht. Vermutlich verhält es sich mit der Ursache jedoch wie unter http://www.netcu.de/faq?id_url=internal-server-error-500-php-script-bricht-ab beschrieben. Der Fehler tritt nach ungefähr 20 Sekunden auf, insofern würde ich davon ausgehen, dass es nicht an der max_execution_time sondern am memory_limit liegt. Das ist mit 512M jedoch eigentlich ausreichend hoch eingestellt, möglicherweise läuft da eine endlose Schleife?

Hast du es mal getestet? Gibt es bei dir keine Auffälligkeiten im Vergleich zu nicht vom Versand ausgeschlossenen Produkten?

**Comment by aschempp** [comment]
Bei mir tritt das Problem nicht auf. Du müsstest also am besten einen Entwickler auf dein System ansetzen der den Fehler findet und mir genaueres liefern kann.

**Comment by Mynyx** [comment]
##shipping_label##

**Comment by Mynyx** [comment]
Nach genauerer Prüfung habe ich nun festgestellt, dass das Problem dann auftritt, wenn in der Benachrichtigung bei neuen Bestellungen in der HTML-Version die Simple Tokens ``##shipping_address##`` oder ``##shipping_label##`` verwendet werden.

**Comment by aschempp** [comment]
welche Contao-Version verwendest du?

**Comment by Mynyx** [comment]
3.5.18

**Comment by aschempp** [comment]
Ich kann den Fehler nicht reproduzieren. Womöglich hast du nicht die neuste Version von Haste installiert, ich glaub da wurden mal solche Probleme behoben.
