### ISSUE TITLE
Invalid address markup / cart

### ISSUE THREAD

**Issue by FuturaDink** [isotope/core#1712]
<div> is not a text tag, and <span> requires a parent tag as p, li, h2 etc.
<img width="1158" alt="bildschirmfoto 2016-09-27 um 11 34 56" src="https://cloud.githubusercontent.com/assets/6049752/18867950/a1d5d6d0-84a6-11e6-809d-9d9d58f5f6c2.png">
better:
<img width="958" alt="bildschirmfoto 2016-09-27 um 11 37 08" src="https://cloud.githubusercontent.com/assets/6049752/18867981/c400b87e-84a6-11e6-824e-31de4898c538.png">

**Comment by aschempp** [comment]
The markup is based on hCard 1.0 examples (see http://microformats.org/wiki/hcard#Live_example).

We'll somewhen update this to h-card 2.0 (see https://github.com/isotope/core/issues/782)
