### ISSUE TITLE
[2.3.5] keine Erweiterung des DCA von Notification_Center unter Contao 4.2.4

### ISSUE THREAD

**Issue by jedoStyle** [isotope/core#1713]
Das DCA des NotificationCenters wird in der aktuellen Version 4.2.4 von Contao nicht erweitert.

Wenn mann im NotificationCenter aushält "Änderung Bestellstatus" werden die 4 zusätzlichen Felder nicht angezeigt.

**Comment by aschempp** [comment]
Das ist mit Sicherheit ein Konfigurationsfehler. Entweder hast du den internen Cache nicht neu aufgebaut, oder beispielsweise die falsche Reihenfolder der Erweiterung (sie wird vor NC geladen).

Unabhängig davon hat das aber auch nichts mit Isotope zu tun, sondern mit dem [Notification Center](https://github.com/terminal42/contao-notification_center).
