### ISSUE TITLE
Problem mit Paypal Zahlung

### ISSUE THREAD

**Issue by comolo** [isotope/core#1717]
Hallo,

ich habe festgestellt, dass der Zahlbetrag in der Bestellübersicht mit dem Zahlbetrag bei Paypal abweichen kann. Der Unterscheid liegt in meinem Fall bei 0,01 Euro, vermutlich handelt es sich um einen Rundungsfehler.

Meine Befürchtung war nun, dass der Shop die Paypal-Zahlung aufgrund der kleinen Abweichung nicht akzeptiert. Unabhängig davon, wäre es natürlich gut, wenn so ein Rundungsfehler gar nicht erst entsteht.

Contao Version: 3.5.17
Isotope: 2.3.5

Besten Dank im voraus.

<img width="392" alt="bildschirmfoto 2016-10-08 um 16 43 34" src="https://cloud.githubusercontent.com/assets/1228676/19238982/47205ff4-8f04-11e6-9dd4-a2f7286e514f.png">
<img width="836" alt="bildschirmfoto 2016-10-08 um 16 44 11" src="https://cloud.githubusercontent.com/assets/1228676/19238981/4717f33c-8f04-11e6-9ba2-5b280651fa8d.png">

**Comment by aschempp** [comment]
Wenn ich die Beträge zusammenrechne scheint das Total im Warenkorb bzw. der Bestellung nicht zu stimmen, aber PayPal liegt richtig. In der 2.4er-Version (aktuell RC1) habe ich einige Rundungs-Probleme behoben, kannst du diese mal installieren und sehen ob das Problem noch auftritt?

**Comment by comolo** [comment]
Mit der RC1 tritt das Problem nicht mehr auf. Super, vielen Dank! 👍
