### ISSUE TITLE
White page PayPal payment gateway

### ISSUE THREAD

**Issue by richardhj** [isotope/core#1719]
Several customers reported one issue with the PayPal payment gateway again and again: When redirected from the shop to PayPal, the page `paypal.com/cgi-bin/webscr` shows a white screen without any content. This occurs sporadically.

After I was able to reproduce it, I was sure it is an fault with PayPal, not Isotope. It needed long to get a significant response from the PayPal Tech Support:

> Bei meinem erneuten Test konnte ich das Problem wieder nicht feststellen. Ich habe auch die übermittelten Daten analysiert. Dabei fiel mit der Parameter "&rm=1" auf den es nicht gibt. Dieser Parameter löst vermutlich die Anzeige des alten Checkout Flows aus und könnte das Problem verursachen wenn im Browser Cash noch Cookies vom neuen Checkout sind. 

This description (displaying old checkout flow sporadically) meets my experiences while reproducing.

So after all, what is [this parameter](https://github.com/isotope/core/blob/6f0d308c364b2fbfdc1c827b1e9dccd40dcb66b8/system/modules/isotope/templates/payment/iso_payment_paypal.html5#L22) for and should it be removed?

**Comment by aschempp** [comment]
As far as I remember, that parameter meant to remove existing items from the cart, if there were any. But it might be obsolete, I'll check the PayPal documentation, thanks for reporting.

**Comment by aschempp** [comment]
According to the PayPal manual at https://developer.paypal.com/docs/classic/paypal-payments-standard/integration-guide/Appx_websitestandard_htmlvariables/#paypal-checkout-page-variables, the `rm` parameter is totally valid.

![bildschirmfoto 2016-12-21 um 11 44 44](https://cloud.githubusercontent.com/assets/1073273/21386396/edea3c6e-c772-11e6-9de5-c77fc8199c47.png)

**Comment by aschempp** [comment]
I'm closing this issue as invalid according to the documentation. If you have more information from PayPal, a contact, or an updated manual, please let us know.
