### ISSUE TITLE
[2.4.0-beta1] ProductCollection::addToTemplate() Gallery-cache bug

### ISSUE THREAD

**Issue by HenryVolkmer** [isotope/core#1723]
/*\* Description **/
Variant-Products with custom attributes causes a wrong Gallery-cache-key, so the same Productimage for different Productvariants will be loaded. 

Screencast: http://h2.softinterbit.de/isotope/1723.webm

/*\* Reproduce **/
BE
- create a Attribut "test_text" (type: textfield, selectable by customer)
- assign the "test_text"-Attribute to a producttype in section "product attributes"
- assign the core attribut "images" to section "variant attributes"
- create several Variants (3 in my Testscenario) with different images

FE
- insert all variants to your cart, use different values for each "test_text"-Attribut in your product-varian-selection (reader-page) (e.g. "foo,bar,linux,not-windows")
- go to "cart" and check the assigned product-images: you will see that the same Image for different products are assigned

/*\* bugfix **/
the cachekey "$strCacheKey" is made up of 
`product<product_id>_ <strAttibute>`

In my scenario above, we have different products with the same cachekey.

we should use the database-id as unique identifier:
`$strCacheKey         = 'product' . $objItem->id . '_' . $strAttribute;`

or disable the cache at all.

**Comment by aschempp** [comment]
This is strange. `product_id` is supposed to be the ID of the product **variant**, so the cache key should point to the correct gallery for that image. Using the item ID would generate multiple galleries for the same product variant, which is not really what we want. 

Are you able to reproduce why the cache key is the same for different product variants?

**Comment by aschempp** [comment]
I was **finally** able to fix this issue. Your pull request solved the problem because it basically disabled the intention of the cache, it generated a new gallery object for every item.

The original issue though is that Isotope uses a very stupid approach (introduced by me 🙈 ) that modifies models, but these are cached in the model registry. The cache actually did hold references to the very same object over and over again. We have already worked around this in the case of products by cloning them, and we need to do the same for galleries. See d487eab69eda5026e2a3cfc69541c665e0bba2f7

**Comment by xApep** [comment]
I know this is some old issue. 
But when I'm updating isotope from version before 2.5.4 to 2.5.4 this fix https://github.com/isotope/core/commit/d487eab69eda5026e2a3cfc69541c665e0bba2f7 is returning this error.

```
Fatal error: Uncaught exception RuntimeException with message The registry already contains an instance for tl_iso_gallery::id() thrown in system\modules\core\library\Contao\Model\Registry.php on line 180
```

**Comment by xApep** [comment]
I know this is some old issue.
But when I'm updating isotope from version before 2.5.4 to 2.5.4 this fix https://github.com/isotope/core/commit/d487eab69eda5026e2a3cfc69541c665e0bba2f7 is returning this error.

`Fatal error: Uncaught exception RuntimeException with message The registry already contains an instance for tl_iso_gallery::id() thrown in system\modules\core\library\Contao\Model\Registry.php on line 180`
