### ISSUE TITLE
[2.3.5 RC Build 6] Produktliste wird über replaceInsertTag nicht dargestellt

### ISSUE THREAD

**Issue by akroii** [isotope/core#1726]
```
[19-Oct-2016 14:18:43 Europe/Berlin] 
PHP Warning: Creating default object from empty value in xxxhtdocs/xxx/system/modules/isotope/library/Isotope/Module/ProductList.php on line 362
#0 xxxhtdocs/xxx/system/modules/isotope/library/Isotope/Module/ProductList.php(362): __error(2, 'Creating defaul...', '/homepages/10/d...', 362, Array)
#1 xxxhtdocs/xxx/system/modules/isotope/library/Isotope/Module/ProductList.php(226): Isotope\Module\ProductList->compileEmptyMessage()
#2 xxxhtdocs/xxx/system/modules/core/modules/Module.php(287): Isotope\Module\ProductList->compile()
#3 xxxhtdocs/xxx/system/modules/haste/library/Haste/Frontend/AbstractFrontendModule.php(45): Contao\Module->generate()
#4 xxxhtdocs/xxx/system/modules/isotope/library/Isotope/Module/Module.php(111): Haste\Frontend\AbstractFrontendModule->generate()
#5 xxxhtdocs/xxx/system/modules/isotope/library/Isotope/Module/ProductList.php(111): Isotope\Module\Module->generate()
#6 xxxhtdocs/xxx/system/modules/core/library/Contao/Controller.php(321): Isotope\Module\ProductList->generate()
#7 xxxhtdocs/xxx/system/modules/core/library/Contao/InsertTags.php(447): Contao\Controller::getFrontendModule('81')
#8 xxxhtdocs/xxx/system/modules/core/library/Contao/Controller.php(692): Contao\InsertTags->replace('{{insert_module...', true)
#9 xxxhtdocs/xxx/templates/megamenu.html5(103): Contao\Controller::replaceInsertTags('{{insert_module...')
#10 xxxhtdocs/xxx/system/modules/core/library/Contao/InsertTags.php(1113): include('/homepages/10/d...')
#11 xxxhtdocs/xxx/system/modules/core/library/Contao/Controller.php(692): Contao\InsertTags->replace('<!DOCTYPE html>...', false)
#12 xxxhtdocs/xxx/system/modules/core/controllers/FrontendIndex.php(477): Contao\Controller::replaceInsertTags('<!DOCTYPE html>...', false)
#13 xxxhtdocs/xxx/system/modules/core/controllers/FrontendIndex.php(28): Contao\FrontendIndex->outputFromCache()
#14 xxxhtdocs/xxx/index.php(19): Contao\FrontendIndex->__construct()
#15 {main}
```

Contao 3.5.15
Ein Listenmodul wird im Template über ein Inserttag dargestellt. Der Fehler tritt sporadisch und nach keinem erkennbaren Muster auf.

Gerne kann ich einen Link per PM zusenden.

**Comment by akroii** [comment]
Den Fehler kann man beheben indem man den Isotope-Cache löscht. Aber man kann ja nicht immer den Cache löschen.

**Comment by akroii** [comment]
Im custom .html5 Template, sieht es so aus: 
```
<li>
										<?php echo $this->replaceInsertTags('{{product::name::23}}')?>
									    <?php #echo $this->replaceInsertTags('{{insert_module::81}}');?>
									</li>
```

**Comment by aschempp** [comment]
1: Du solltest besser gleich `\Controller::getFrontendModule(81)` verwenden statt einen InsertTag zu parsen.

2: Der Fehler tritt vermutlich auf wenn die Seite im Cache liegt. Das Listen-Modul kann nicht im Cache neu generiert werden (`refresh` Flag).

**Comment by akroii** [comment]
Der Fehler tritt auch ohne refresh-Flag auf.
Die Funktion \Controller::getFrontendModule() ist leider sehr schlecht Dokumentiert.

**Comment by akroii** [comment]
Ich muss mich entschuldigen, aber bin ich der erste der versucht ein Isotope Modul per Inserttag darzustellen?

**Comment by aschempp** [comment]
ich denke nicht, das Problem liegt vermutlich eher daran dass du die Seite cachen willst, was mit Isotope schlecht funktioniert (z.B. wegen dem Warenkorb).

**Comment by akroii** [comment]
Der Eingangs genannte Fehler tritt auch mit der Funktion `\Controller::getFrontendModule()` auf.

**Comment by akroii** [comment]
@aschempp was passiert, wenn man die Buttons Warenkorb, Aktualisieren und Favoriten ausschaltet? Kann ich dann trotzdem die Seite Cachen und das Produktlisten-Modul verwenden?
Ich möchte ja nur eine einfache Liste mit Produkten... ohne Bild, Teaser, Schaltflächen o.ä.

**Comment by aschempp** [comment]
Das Problem sind nicht diese Buttons, sondern zum Beispiel ein Warenkorb auf derselben Seite. Der ist benutzerspezifisch und mit Contao kann die Seite in diesem Fall nicht gecacht werden…

**Comment by akroii** [comment]
Um zu meinem eigentlichen Problem zurückzukehren... ein Warenkorb ist in meinem Beispiel nicht dabei. Ich verwende die Produktliste als eine Art nav_default.html5... ohne Warenkorb, Buttons, Bilder, o.ä. Ich brauche nur den Namen und den Link des Produktes. Selbst Warenkorb-Funktionalitäten benutze ich nirgendwo auf meiner Seite.

**Comment by aschempp** [comment]
Das Problem liegt an deiner Konfiguration. Es scheint verschachtelte InsertTags zu geben, diese werden erst ab Contao 4 korrekt unterstützt. In deinem Fall wird das Modul während dem Cache neu gebaut, was erstens nicht geht und zweitens dann sinnlos wäre, weil nicht gecacht…

**Comment by akroii** [comment]
[#8658](https://github.com/contao/core/issues/8658)
