### ISSUE TITLE
Login page when both checkout methods are allowed

### ISSUE THREAD

**Issue by Don-Ron** [isotope/core#1729]
In the checkout configuration, it is possible to select a login page when the checkout method "Login/Registration required" is selected. When selecting "Both allowed", i would expect that I am allowed to select a login page as well. The user in the front-end would then get asked if he wants to buy as a guest or as registered user.

In order to not change the current code and configuration much I was thinking that maybe a fourth option "Both allowed; ask visitor" would be the best solution to this problem.

**Comment by aschempp** [comment]
If both is allowed, the checkout module does not know whether to redirect a guest user or not. You have to setup the login workflow yourself, please check the Isotope demo for an example.

**Comment by Don-Ron** [comment]
Ok, so its a functionality we have to program/configure and it will not be included in the isotope code.

Thanks!
