### ISSUE TITLE
Generierung von zufälligen Bestell-, Rechnungs- und Kundennummern

### ISSUE THREAD

**Issue by CodeAlDente** [isotope/core#1730]
Aktuell werden keine Kundennummern generiert, man könnte allerdings die ID aus der Datenbank des jeweiligen Mitglieds bzw. Kunden holen und dafür nutzen. Ist aber suboptimal, weil die Kundennummer dann "5" lauten könnte und nicht so ideal wäre wie eine zufällige, x-stellige Zahlenkombination.

Das gleiche gilt für die Bestell- und Rechungsnummer bzw. Auftragsnummer **document_number** welche vom Ansatz her gut ist, aber auch nur aufsteigend ist. Eine zufällige Zahlenkombination wie bei der Kundennummer wäre schöner.

**Comment by aschempp** [comment]
Kundennummern gibt es in Isotope nicht, da alles auf den Contao Mitgliedern basiert. Die Generierung müsste also da erfolgen.

Rechnungs- und Bestellnummern müssen per Gesetz (in allen mir bekannten Fällen) fortlaufen sein um vor Betrug (Rechnung vernichten) zu schützen. Ein Zufall macht entsprechend wenig Sinn.

Der Entwickler deines Vertrauens kann dies mit einer Spezialentwicklung aber sicher für dein System bauen ;-)
