### ISSUE TITLE
Google Anaylitcs E-commerce tracking

### ISSUE THREAD

**Issue by EDsolution** [isotope/core#1731]
Hi.
Found few issue with the Google analytics e-commerce tracking with Universal Analytics and was wondering if this is working in Isotope 2.2.2 and above?

Thanks!

**Comment by aschempp** [comment]
There is no implementation of Universal Analytics yet (see https://github.com/isotope/core/issues/1153). As we currently don't use that feature ourselves, I can't tell if the current works. If you want to contribute a universal analytics integration, feel free to provide a pull request.

Closing this in favor of #1153

**Comment by EDsolution** [comment]
We have to do it so we will, but it will be based on javascript.

**Comment by aschempp** [comment]
The issue with Javascript is that it will not track transactions if the client does not return to the shop, which is the case with several payment methods.

**Comment by EDsolution** [comment]
Did not really read about PHP integration but I suppose that then for example paypal returns status back to tracking?

**Comment by aschempp** [comment]
Well PayPal actually tells Isotope (the server) that the payment was successfull so the order is actually placed. That's when the emails are sent, and analytics should be tracked.

**Comment by xApep** [comment]
Thanks for the info. Will think about this and see what we can do.

Cheers.
