### ISSUE TITLE
Cache key in product list

### ISSUE THREAD

**Issue by Toflar** [isotope/core#1733]
Current code

``` php
        return md5(
            'productlist=' . $this->id . ':'
            . 'where=' . $this->iso_list_where . ':'
            . 'isorc=' . (int) \Input::get('isorc') . ':'
            . implode(',', $categories)
        );
```

Shouldn't we replace insert tags on the iso_list_where as well? Otherwise this might lead to unexpected behaviour if I use something like `{{date}}` no?

**Comment by aschempp** [comment]
This is already done by the parent class: https://github.com/isotope/core/blob/master/system/modules/isotope/library/Isotope/Module/Module.php#L73
