### ISSUE TITLE
Serialized String is passed where Array is expected

### ISSUE THREAD

**Issue by tsarma** [isotope/core#1734]
`**Fatal error: Uncaught exception TypeError with message Argument 1 passed to Isotope\Model\RequestCache::getFirstLimitForModules() must be of the type array, string given, called in /system/modules/isotope/library/Isotope/Module/ProductList.php on line 89 thrown in system/modules/isotope/library/Isotope/Model/RequestCache.php on line 380**
# 0 system/modules/isotope/library/Isotope/Module/ProductList.php(89): Isotope\Model\RequestCache->getFirstLimitForModules('a:4:{i:0;s:2:"4...', '12')`

**Comment by aschempp** [comment]
Did you install Haste 4.14.2?

**Comment by tsarma** [comment]
Sorry now I can not reproduce it again my self. 
I have now haste 4.11.4
