### ISSUE TITLE
Umbenanntes Template wird ignoriert

### ISSUE THREAD

**Issue by adnan-dev** [isotope/core#1737]
Hallo,
wenn ich (in meinem Fall) das iso_reader_default-Template in iso_reader_custom ändere, kann ich das zwar für einen bestimmten Produkttypen auswählen, aber im Frontend wird auf das default-Template zurückgegriffen.

**Comment by aschempp** [comment]
Dann hast du dies vermutlich im Frontend-Modul ausgewählt/übersteuert.

**Comment by adnan-dev** [comment]
Danke, das wars!!! Wie doof von mir!
