### ISSUE TITLE
[2.4.0] empty option for variant attribute

### ISSUE THREAD

**Issue by Toflar** [isotope/core#1738]
Attribute setup:

- Options Manager
- Mandatory field

If you make one variant the standard variant (default variant), the empty option in the front end still gets shown. This makes no sense because as you have a default variant, a choice is already made for the customer and as it is a mandatory field, there's absolutely no need for an empty option.

**Comment by Toflar** [comment]
Imho it's [this commit](https://github.com/isotope/core/commit/3ac89edc55dfbeb150255f0bdeca398845f5afdd) that needs to be adjusted now that it is possible :)

**Comment by aschempp** [comment]
Unfortunately that's not really true. As far as I remember, we need the empty option to be able to "reset" the selection". Got to really test that though.

**Comment by aschempp** [comment]
Blank option is only added for select menu's now, it does really not make sense for radios.
