### ISSUE TITLE
[2.4-rc1]  Fehlermeldung entfernen und Ausgabe der Bildergrössen verhindern

### ISSUE THREAD

**Issue by netzarbeiter** [isotope/core#1741]
Zur Zeit wird beim Anlegen einer Inline Galerie folgende Fehlermeldung ausgegeben:
Be aware that this gallery type does not support <picture> (responsive images).

Diese könnte man sich schenken, wenn man in der Hauptbildgrösse und Galeriegrösse die angelegten Bildgrössen nicht ausgeben würde.

![inline-gallery](https://cloud.githubusercontent.com/assets/1942550/20623390/a0a19436-b307-11e6-90d5-9ffbb44279bf.png)

**Comment by aschempp** [comment]
I have actually removed the message in c2afa77dde53a162d693382b462e9054013bd9e7.

The image sizes are very well supported in all galleries, the responsive part's are just not applied. But the main image size is applied, so I think selecting a predefined value does make sense depending on the setup.
