### ISSUE TITLE
The registry already contains an instance for tl_iso_address::id()

### ISSUE THREAD

**Issue by raum124** [isotope/core#1742]
Ich habe einen neuen Bestellstatus definiert mit entsprechender Benachrichtigung. Hat alles wunderbar funktioniert. Beim Austesten habe ich einige Bestellungen selber ausgeführt. Danach habe ich diese Testbestellungen wieder gelöscht. Von diesem Moment an, gab es beim Abschicken von weiteren Bestellungen im Frontend eine Fehlermeldung. Die Benachrichtigungen wurden zwar verschickt, die Bestellungen tauchten aber nicht im Isotope-Backend auf. Auch das Entfernen des neuen Bestellstatus brachte nichts. Die Datenbank hat's so verhauen, dass ich ein Notfallbackup einspielen musste. Dieses Fehlverhalten konnte ich reproduzieren. Ich vermute einen Bug. Im Forum und auch auf GitHub konnte ich zwar nichts finden. Fehlermeldung liegt bei. 

![image](https://cloud.githubusercontent.com/assets/23740045/20625862/1fb74000-b316-11e6-9dc6-7cfb76a16f27.png)

Contao 3.5.9 mit Isotope 2.3.5

**Comment by aschempp** [comment]
Actually a Contao core bug (see https://github.com/contao/core/pull/8605), but fixed in ce6e53e7e857db0288bbdefeb7c724ad76fcdc34
