### ISSUE TITLE
Migration for quanity_mode is missing

### ISSUE THREAD

**Issue by Toflar** [isotope/core#1743]
Just realized there's no update routine for https://github.com/isotope/core/commit/17c736b5e85ee236ed6c697cdcc65d8d4a7b5a03 which causes a lot of nice `InvalidArgumentExceptions` when you update from an older Isotope version :)

**Comment by aschempp** [comment]
This can't really be an issue. `minimum_quantity` and `maximum_quantity` have been added in the same release, therefore they can never be larger than zero and the conditionals would not apply…?

Code improvements in 02d74372559bb5e1e5406ccd6c7550d120c35206

**Comment by Toflar** [comment]
Dunno when it happened. But it did.

**Comment by aschempp** [comment]
Yeah, must have been because you/client edited the shipping method and did not fill the required fields.

**Comment by aschempp** [comment]
Hah! That lead me to the issue: the mode field was not mandatory! Fixed in 2aad89a83f1ee0c1bc9ee3825e2732089d76617c
