### ISSUE TITLE
Produktfilter

### ISSUE THREAD

**Issue by comolo** [isotope/core#1745]
Hallo,
ich habe folgendes Problem festgestellt.

Wenn man im Produkt-Filter ein Anfängliches Suchfeld und eine Sortierrichtung festlegt, wird diese im Frontend nicht berücksichtigt. Es wird wohl einfach der erste Filter in der Liste ausgewählt.

Modul Konfiguration:
<img width="713" alt="bildschirmfoto 2016-12-06 um 18 39 21" src="https://cloud.githubusercontent.com/assets/1228676/20936664/bb9afa54-bbe3-11e6-9585-30d31fe701f4.png">

Frontend Ergebnis:
<img width="405" alt="bildschirmfoto 2016-12-06 um 18 39 38" src="https://cloud.githubusercontent.com/assets/1228676/20936723/ed8c0ad0-bbe3-11e6-9ee6-aa03bf3512c5.png">

Frontend Ergebnis - wie ich es erwartet hätte
<img width="406" alt="bildschirmfoto 2016-12-06 um 18 42 09" src="https://cloud.githubusercontent.com/assets/1228676/20936750/0a0626fa-bbe4-11e6-9fbf-6e02257b0838.png">

Besten Dank vorab!

**Versionen**
Contao: 3.5.17
Isotope: 2.3.5

**Comment by aschempp** [comment]
This has already been fixed in https://github.com/isotope/core/commit/75394a7411611dedf3c0f63cfc05e5f65c574044 (Isotope 2.4 rc1)
