### ISSUE TITLE
[2.4.0-rc1] Array im Warenkorb

### ISSUE THREAD

**Issue by netzarbeiter** [isotope/core#1746]
Ich habe ein Attribut-Typ «Selcect-Menü» angelegt. Für «Varianten verwenden» ist ausgewählt und die Daten werden über die Options-Quelle «Eigene Datanbank-Tabelle (foreignKey)» eingebunden.

Die Ausgabe im Produktleser ist einwandfrei, im Warenkorb wird jedoch statt dem Wert ein «Array» ausgeben.

**Comment by aschempp** [comment]
Ich kann den Fehler nicht reproduzieren. Das Collection-Template hat sich in https://github.com/isotope/core/commit/654f2f0e54cfc828e0edc51e020c93f5d5552d60#diff-c7b200a123582e1ff0d1b9d236120074 geändert, sicher dass du diese Änderungen drin hast?

**Comment by netzarbeiter** [comment]
Ich habe eine frische Installation und keine abgeänderten Templates.
Ausgabe im Warenkorb:

- Attribut 1: Array
- Attribut 2: Array

Es macht übrigens keinen unterschied ob ich «Eigene Datenbank-Tabelle» oder den Option-Manager verwende.

**Comment by aschempp** [comment]
So this seems to be a PHP7 issue. Fixed in abbf25c9b1dd03b4bafe2c463efacccec5a797a1
