### ISSUE TITLE
Produktgruppen erscheinen nicht? 

### ISSUE THREAD

**Issue by markknochen1** [isotope/core#1747]
Hallo,

ich habe links unter dem Punkt "Produkte" und dann bei dem Blitz-Icon rechts unter "Produktgruppen" zwei neue
Produktgruppen erstellt, denen einen bestehenden "Default product type" zugewiesen und gespeichert.

Diese beiden neuen Produktgruppen erscheinen nun aber nicht unter der Auflistung "Produkte".

Und was ich auch noch nicht gefunden habe - wo verwaltet man diese "Default product type" ...

Danke sehr

**Comment by markknochen1** [comment]
ah, die erscheinen da nicht, wenn sie leer sind ... das ist ehrlich gesagt echt verwirrend ...

**Comment by aschempp** [comment]
wozu solltest du leere Gruppen sehen, die keine Funktion haben? ;-)
