### ISSUE TITLE
[2.4.0] «In den Warenkorb»-Link funktioniert nicht

### ISSUE THREAD

**Issue by netzarbeiter** [isotope/core#1748]
Ein Modul vom Typ «Favoriten» angelegt und unter Produktsammlung-Template «iso_collection_favorites» ausgewählt. Danach das Modul in der Seite «Favoriten» eingebunden, die Ausgabe sieht wie folgt aus:

![favoriten](https://cloud.githubusercontent.com/assets/1942550/21605317/aa524c5e-d1a8-11e6-8943-7c0c92adc53d.png)

Der «In den Warenkorb»-Link funktioniert nicht.
`favoriten.html?add_to_cart=722`

Der «Entfernen»-Link funktioniert.
`favoriten.html?add_to_cart=722&remove=722`

Der «In den Warenkorb übernehmen»-Button funktioniert.

**Comment by aschempp** [comment]
Should be fixed in 415f37c079ffa94c9986f7584b0cf7c496dd9874
