### ISSUE TITLE
Zurück-Button defekt 

### ISSUE THREAD

**Issue by sdamrau** [isotope/core#1749]
Der Zurück-Button im Checkout-Prozess funktioniert nicht mehr, seit der JS-Umstellung weg von MooTools. 

fa21ebeb042381d8b408adc0b28abf840cef2ba5   => der previousStep-Button wird auf disabled gesetzt, womit er im POST aber nicht mehr enthalten ist. Somit wird er als normaler Submit interpretiert = vorwärts zum nächsten Schritt.

Aus meiner Sicht reicht es, den nextStep-Button zu disablen, um mehrfache Submits zu verhindern, oder?

**Comment by pgerundt** [comment]
Wie wäre es damit?

```
        checkoutButton: function (form) {
            addEventListener(form, 'submit', function(e) {
                if (form.className.search(/submitting/) != -1) {
                    e.preventDefault();
                    return false;
                }
                else {
                    form.className += ' submitting';
                    try {
                        if (!document.getElementsByName('nextStep')[0].className.search(/disabled/) != -1) {
                            document.getElementsByName('nextStep')[0].className += ' disabled';
                        }
                    } catch (e) {}
                    try {
                        if (!document.getElementsByName('previousStep')[0].className.search(/disabled/) != -1) {
                            document.getElementsByName('previousStep')[0].className += ' disabled';
                        }
                    } catch (e) {}
                    setTimeout(function () {
                        window.location.reload()
                    }, 30000);
                    return true;
                }
            });
        }
```

Buttons per CSS-Klasse optisch inaktiv setzen und Formular per CSS-Klasse als "wurde gerade abgesendet" markieren.
Letzteres kann man auch alternativ mit einem Attribut per

`form.setAttribute('submitting', 'true');`

realisieren.

Funktioniert bei mir.

**Comment by aschempp** [comment]
Fixed in 1cc91348bb230394d5c8552279d01aeb0d872b4f
