### ISSUE TITLE
PDF Sonderzeichen

### ISSUE THREAD

**Issue by Irontale** [isotope/core#1750]
Besondere Zeichen wie z.B. diakritische Zeichen werden als '?' in das PDF gedruckt. Sollte dank Unicode nicht vorkommen, oder? Möglichkeiten das zu beheben?

**Comment by aschempp** [comment]
Wir verwenden die PDF-Bibliothek TCPDF welche in Contao mitgeliefert wird. Ich kann leider nicht beurteilen welche Zeichen funktionieren, eigentlich sollte aber alles in UTF8 funktionieren. Es gibt Schnittstellen in Isotope um einen eigenen PDF-Generator einzubinden, falls nötig müsstest du dazu wohl einen Entwickler kontaktieren.

**Comment by paulhaem** [comment]
Für Leute, die sich hierher verirren eine mögliche Lösung: https://community.contao.org/de/showthread.php?67646-TCPDF-und-Sonderzeichen-solved
