### ISSUE TITLE
Anlagen importieren: Ähnliche Artikelnummern im Dateinamen werden falsch zugewiesen (2.4)

### ISSUE THREAD

**Issue by michelbalzer** [isotope/core#1752]
Ich hatte vorhin mal ein paar Möglichkeiten der Dateinamenbenennung für den Anlagen-Import (do=iso_products&key=import) getestet und bin dabei auf folgendes gestoßen:

Ich habe zwei Produkte angelegt mit folgenden Artikelnummern:

- 51487478
- 514874789

Anschließend habe ich Dateien mit folgenden Dateinamen hochgeladen:

- 514874789_01.jpg
- 514874789_02.jpg
- 514874789_03.jpg

Zum Schluss habe ich die Anlagen importiert. Diese wurden dann beiden Produkten zugewiesen. Ist der Import dafür einfach zu grob ausgelegt oder kann man das getrost als Bug einstufen?

Isotope 2.4, Contao 3.5.21

**Comment by aschempp** [comment]
Das ist wohl richtig… es wird nur geprüft ob die Datei mit der Artikelnummer beginnt. Sonst würde es ja mit der fortlaufenden Nummerierung wie in deinem Fall nicht funktionieren. Ich glaube aber kaum dass wir das ändern können, oder siehst du eine einfache Lösung?

**Comment by michelbalzer** [comment]
Ich bin da zu wenig Backendler um da ’ne gescheite Lösung an der Hand zu haben ;)
