### ISSUE TITLE
Fehler beim Anlegen eines Attributes unter Contao 4.3.2

### ISSUE THREAD

**Issue by Benjaminscherf** [isotope/core#1753]
Hallo,

ich hatte dies letzte Woche schon im github der Extension DC_Multilingual eingestellt. Ich bin mir aber nicht sicher, ob es hier oder dort der Richte Ort für diese Fehlermeldung ist.

Ich versuche Isotope 2.4.0 unter Contao 4.3.2 zum laufen zu bringen. Soweit ich es sagen kann funktioniert erst einmal alles, ausser das Anlegen eines Attributes. Sobald man zum Bereich "Optionen-Quelle" kommt und eine Auswahl trifft, erscheint folgender Fehler:

Strict Standards: Declaration of DC_Multilingual::generateTree() should be compatible with Contao\DC_Table::generateTree($table, $id, $arrPrevNext, $blnHasSorting, $intMargin = 0, $arrClipboard = NULL, $blnCircularReference = false, $protectedPage = false, $blnNoRecursion = false, $arrFound = Array) in /homepages/22/d615086249/htdocs/concept/system/modules/dc_multilingual/drivers/DC_Multilingual.php on line 1463

Das betrifft nur die Auswahl "Options-Manager" und "Produkt".

Im Frontend erscheint folgende Meldung:

Strict Standards: Declaration of DC_Multilingual::generateTree() should be compatible with Contao\DC_Table::generateTree($table, $id, $arrPrevNext, $blnHasSorting, $intMargin = 0, $arrClipboard = NULL, $blnCircularReference = false, $protectedPage = false, $blnNoRecursion = false, $arrFound = Array) in /homepages/22/d615086249/htdocs/concept/system/modules/dc_multilingual/drivers/DC_Multilingual.php on line 24

Warning: Cannot modify header information - headers already sent by (output started at /homepages/22/d615086249/htdocs/concept/system/modules/dc_multilingual/drivers/DC_Multilingual.php:24) in /homepages/22/d615086249/htdocs/concept/vendor/contao/core-bundle/src/Resources/contao/library/Contao/System.php on line 657

Warning: Cannot modify header information - headers already sent by (output started at /homepages/22/d615086249/htdocs/concept/system/modules/dc_multilingual/drivers/DC_Multilingual.php:24) in /homepages/22/d615086249/htdocs/concept/vendor/contao/core-bundle/src/EventListener/MergeHttpHeadersListener.php on line 149

Warning: Cannot modify header information - headers already sent by (output started at /homepages/22/d615086249/htdocs/concept/system/modules/dc_multilingual/drivers/DC_Multilingual.php:24) in /homepages/22/d615086249/htdocs/concept/vendor/contao/core-bundle/src/EventListener/MergeHttpHeadersListener.php on line 149

Könnt Ihr hierzu was sagen bzw. einen Tip geben.
LG

**Comment by aschempp** [comment]
Looks like the method signature has changed in Contao 4.1

https://github.com/contao/core-bundle/commit/d60dc59c0ca17df061b94ae68c50623f0d94293f

**Comment by aschempp** [comment]
DC_Multilingual v3 should be used with Contao 4 (fixed in 86f7e8eaaaebc35d369845a7f08869eb3ea34646)

**Comment by aschempp** [comment]
Actually that info was not correct (removed in daf49a1853d3623dfe4a92faf25abe676a555bb4). See https://github.com/terminal42/contao-DC_Multilingual/issues/39
