### ISSUE TITLE
Coupon no longer in use after login

### ISSUE THREAD

**Issue by cnajjar** [isotope/core#1754]
The Coupons that have been added before login disappeared afterwards. I'm using isotope 2.4 and could no longer find the needed hook.

**Comment by aschempp** [comment]
You mean you entered a coupon code in a guest cart and then logged in?

**Comment by cnajjar** [comment]
exactly

**Comment by aschempp** [comment]
Fixed in 0e3bcb584a810f83850c423d3b8078865ff52f18
