### ISSUE TITLE
"The model instance has been detached and cannot be saved" in postCheckout because of 40619a1

### ISSUE THREAD

**Issue by richardhj** [isotope/core#1756]
Is there a discussion on why to prevent saving a product? See 40619a1.

This is my code:
```php
/**
     * @category ISO_HOOKS: postCheckout
     *
     * @param ProductCollection\Order $order
     * @param array                   $tokens
     *
     */
    public function postCheckout(ProductCollection\Order $order, array $tokens)
    {
        foreach ($order->getItems() as $item) {
            /** @var Product|\Model $product */
            $product = $item->getProduct();
            $product->published = '';
            $product->save();
        }
    }
```

What's the best way now to save a product in the `postCheckout` when this behavior might not be supported anymore?

**Comment by richardhj** [comment]
As I just noticed, is this not a BC breaking change following semantic versioning, whether it was a supported use case?

**Comment by aschempp** [comment]
we had to change Isotope so that the product contains customer editable information, otherwise that would not have been available in several other places. Due to containing that data the object is no longer storable as it would overwrite incorrect data in the database…
