### ISSUE TITLE
Listenpreis-Anzeige bei gleichen Stafelpreisen mehrerer Varianten

### ISSUE THREAD

**Issue by sdamrau** [isotope/core#1759]
Hat man ein Produkt mit mehreren Varianten (mind. 2), welche jeweils Staffelpreise haben, wird der grösste Preis in der Listenansicht und Detailansicht durchgestrichen angezeigt, wenn der jeweils günstigste Preis identisch ist.

Angezeigt wird dann der höchste Preis (kleinste Staffel) als durchgestrichener Preis und der niedrigste Preis als gültiger Preis (wobei letzteres ja stimmt.)

Beispiel:

Produkt X
 - Variante 1 ("rot"):
     - Staffelpreis bei 1 Stück: 20,00
     - Staffelpreis bei 5 Stück: 10,00
 - Variante 2 ("gelb"):
     - Staffelpreis bei 1 Stück: 20,00
     - Staffelpreis bei 5 Stück: 10,00

Anzeige in der Liste: 20,00 durchgestrichen 10,00 als Preis.

![image](https://cloud.githubusercontent.com/assets/4929800/22457507/232be8a6-e798-11e6-82e5-1ff1188707dc.png)

Der Fehler tritt nicht mehr auf, wenn man eine Variante als Favorit festlegt, bzw. auf der Detailseite eine Variante gewählt wurde. 
Ebenfalls tritt er nicht auf, wenn sich die niedrigen Staffelpreise unterscheiden.

Wir blenden jetzt als Workaround erstmal die "original_price" Elemente aus, da im aktuellen Projekt nicht benötigt.

Gruß
Sören

**Comment by aschempp** [comment]
Ich bin nicht sicher wo hier der Fehler ist. Müsste stattdessen "ab 10" stehen statt ein durchgestrichener Preis?

**Comment by sdamrau** [comment]
genau, wenn ich eine Variante deaktiviere (also nur noch eine live ist), sieht es korrekt aus:

![image](https://user-images.githubusercontent.com/4929800/27710681-da8bb8de-5d20-11e7-99a7-6290863948f2.png)

**Comment by aschempp** [comment]
@sdamrau haben wir dieses Problem eigentlich mal gelöst in deinem Shop?

**Comment by sdamrau** [comment]
in dem betroffenen Shop haben wir es einfach ausgeblendet - insofern: nein ;-)

**Comment by aschempp** [comment]
dann haben wir wohl keine Lösung dafür gefunden 🙈
