### ISSUE TITLE
Tippfehler in der Backendmaske Shop-Konfiguration->Typ: Elevate zoom Galerie

### ISSUE THREAD

**Issue by mpitz** [isotope/core#1760]
Falsch: Zomm-Fensterrahmen
Richtig: Zoom-Fensterrahmen

(siehe Screen Punkt 2):
![image](https://cloud.githubusercontent.com/assets/6831223/22469909/d240f43c-e7cd-11e6-9e9b-14e24a4380ae.png)

**Comment by aschempp** [comment]
Übersetzungen werden bei www.transifex.com gepflegt, du kannst diese selbstständig korrigieren.

/cc @netzarbeiter
