### ISSUE TITLE
Zoom elevate Galerie: Zoom-Fensterposition speichern nicht möglich

### ISSUE THREAD

**Issue by mpitz** [isotope/core#1761]
Die Zoom-Fensterposition lässt sich nicht speichern.
Isotope: 2.4
Contao: 4.3.4

(siehe Screen Punkt 1)
![image](https://cloud.githubusercontent.com/assets/6831223/22469985/15cb95ae-e7ce-11e6-8677-143c793db2d0.png)

**Comment by aschempp** [comment]
Most likely an issue in Contao core as validation for that field was added recently.

**Comment by qzminski** [comment]
I guess you refer to the https://github.com/contao/core/pull/8574 but I don't know how that PR can cause the error.

**Comment by aschempp** [comment]
Well the issue is that the validation is taking place inside the widget, but the widget is used for any other input cases by extension developers (I do that a lot), so it should rather be a save_callback…

**Comment by qzminski** [comment]
In fact only the validation of field mandatoriness has changed and that relates only to the values that are provided used in the Contao core (e.g. ```proportional```, ```left_center```). Any extra values should not be validated in terms of mandatoriness.

No idea what could cause the ```invalid option``` error though.

**Comment by aschempp** [comment]
Well we are using the same values (in a different context though) …

**Comment by qzminski** [comment]
That widget is called "image size" so in my opinion the validation is totally correct. Even if you are using the same values then it still should be validated that way – I don't see a case where you would like to crop the image ```center_center``` and provide only one dimension.

However for the widgets that want to use the same feature but different validation perhaps we could delegate the validation code to a different method than ```validator()``` so it can be easily overridden.

**Comment by aschempp** [comment]
Well we're using "top_left" as a position to show the image zoom…

Again, this should be a save_callback and not a widget feature. Or at least a feature toggled in a DCA property.

**Comment by aschempp** [comment]
Fixed in 848bdca492896a40b77daf2488d72292bac9ae50
