### ISSUE TITLE
Empty product attributes when using translations and variants

### ISSUE THREAD

**Issue by richardhj** [isotope/core#1762]
## What?
When using translations and variants, attributes like the `name` might not be fetched from the database. This results in a product list, that does not show product names.

![bildschirmfoto-2017-02-02-um-16 12 23](https://cloud.githubusercontent.com/assets/1284725/22555179/22b2d2b4-e963-11e6-9394-6aef5820c631.png)
![bildschirmfoto-2017-02-02-um-16 14 58](https://cloud.githubusercontent.com/assets/1284725/22555189/2c15c8f2-e963-11e6-9702-cddb048d3a7d.png)

## Why?
The query that will be generated [here](https://github.com/isotope/core/blob/2.4.0/system/modules/isotope/library/Isotope/Model/Product.php#L583-L697) looks like this in my environment.
```sql
SELECT tl_iso_product.*, 'de' AS language, IF(tl_iso_product.pid>0, parent.type, tl_iso_product.type) AS type, IFNULL(translation.name, tl_iso_product.name) AS name, IFNULL(translation.teaser, tl_iso_product.teaser) AS teaser, IFNULL(translation.description, tl_iso_product.description) AS description, IFNULL(translation.meta_title, tl_iso_product.meta_title) AS meta_title, IFNULL(translation.meta_description, tl_iso_product.meta_description) AS meta_description, IFNULL(translation.meta_keywords, tl_iso_product.meta_keywords) AS meta_keywords, IFNULL(translation.images, tl_iso_product.images) AS images, IFNULL(translation.shortfacts, tl_iso_product.shortfacts) AS shortfacts, tl_iso_product.images AS images_fallback, c.sorting FROM tl_iso_product LEFT OUTER JOIN tl_iso_product_category c ON tl_iso_product.id=c.pid LEFT OUTER JOIN tl_iso_product translation ON tl_iso_product.id=translation.pid AND translation.language='de' LEFT OUTER JOIN tl_iso_product parent ON tl_iso_product.pid=parent.id WHERE tl_iso_product.language='' AND tl_iso_product.published='1' AND (tl_iso_product.start='' OR tl_iso_product.start<'1486046760') AND (tl_iso_product.stop='' OR tl_iso_product.stop>'1486046820') AND c.page_id IN (30) GROUP BY tl_iso_product.id ORDER BY c.sorting
```
**The important thing here:** `IFNULL(translation.name, tl_iso_product.name) AS name`.
**The problem:** `tl_iso_product.name` can never be `NULL` because the dca/sql config [does not allow this](https://github.com/isotope/core/blob/2.4.0/system/modules/isotope/dca/tl_iso_product.php#L374)
SQL definition might be changed into `varchar(255) NULL`.

I fixed afterwards with `UPDATE tl_iso_product SET name = NULL WHERE name =  ''`

**Comment by aschempp** [comment]
You must have misunderstood something: `IFNULL(translation.name, tl_iso_product.name) AS name` will fetch `translation.name` if that value is not null, so the null-ness of `tl_iso_product.name` is irrelevant for the condition. All of `translation` will be `NULL` if no such record exists.

It looks like you created translations for your product but did not fill the fields in the backend.

**Comment by richardhj** [comment]
Ok, I misunderstood the query. But because the `teaser` and `description` of the non-filled translation were both `NULL`, the fallback was used (for the `name` not).
