### ISSUE TITLE
[Contao 4] Rules & Coupons

### ISSUE THREAD

**Issue by netzarbeiter** [isotope/core#1767]
Discount rounding = `w50 w50h`

**Before:**
![before](https://cloud.githubusercontent.com/assets/1942550/22779431/16279b94-eebb-11e6-922b-3116aab0cfb1.png)

**After:**
![after](https://cloud.githubusercontent.com/assets/1942550/22779447/1db5f766-eebb-11e6-8b7a-1623a91d14c0.png)

**Comment by aschempp** [comment]
Fixed in 4c6d836ffa937af90c236a65a22682d573eb454c
