### ISSUE TITLE
[Contao 4] Reports & Statistics

### ISSUE THREAD

**Issue by netzarbeiter** [isotope/core#1768]
```
.iso_be_overview #main h1:first-child {
 	display: block;
}
.tl_info {
	margin: 0 18px;
}

.be_iso_overview .item a {
	margin: 15px 0 15px 18px;
}
.be_iso_overview .item span {
	line-height: 1.5;
	margin-top: 5px;
}
```
Before:
![before](https://cloud.githubusercontent.com/assets/1942550/22779823/93063a5c-eebc-11e6-8ba7-39d8eff9cde8.png)

**After:**
![after](https://cloud.githubusercontent.com/assets/1942550/22779815/89c3a506-eebc-11e6-8438-144a057a5f82.png)

**Comment by aschempp** [comment]
Fixed in 9ba5be57afb16f426abac9a7c051c16bfb088521
