### ISSUE TITLE
[Contao 4] Reports & Statistics > Total

### ISSUE THREAD

**Issue by netzarbeiter** [isotope/core#1769]
```
.tl_select, .tl_mselect {
	width: inherit;
}
.tl_subpanel strong {
	padding-left: 18px;
}
.tl_start img,
.tl_stop img {
	margin-left: 4px;
}
```
**Before:**
![before](https://cloud.githubusercontent.com/assets/1942550/22780688/d4538f52-eebf-11e6-8ae7-441e7ebd305d.png)

**After:**
![after](https://cloud.githubusercontent.com/assets/1942550/22780684/ce62d7f6-eebf-11e6-8440-c2e0a7db2a92.png)

**Comment by aschempp** [comment]
Fixed in 0deb4d552677bd6c47a391bc492349273bd9cbfc
