### ISSUE TITLE
[Contao 4] Reports & Statistics > Per product

### ISSUE THREAD

**Issue by netzarbeiter** [isotope/core#1770]
```
.tl_select, .tl_mselect {
    width: inherit;
}
.tl_subpanel strong {
    padding-left: 18px;
}
.tl_from img {
    margin-left: 4px;
}
.tl_variants .radio_container {
    margin-top: 8px;	
}
.tl_radio {
    margin-left: 8px;
    margin-right: 4px;
}
```
**Before:**
![before](https://cloud.githubusercontent.com/assets/1942550/22781149/8821f324-eec1-11e6-9fbb-7cbcf4484395.png)

**After:**
![after](https://cloud.githubusercontent.com/assets/1942550/22781146/83999348-eec1-11e6-9564-4671aae3e68f.png)

**Comment by aschempp** [comment]
Fixed in 0deb4d552677bd6c47a391bc492349273bd9cbfc
