### ISSUE TITLE
[Contao 4] Advanced filter "Groups" remain empty

### ISSUE THREAD

**Issue by netzarbeiter** [isotope/core#1771]
Going to "Product management" and press "Groups" the opening windows remain empty.

Error message:
Failed to load resource: the server responded with a status of 500 (HTTP/2.0 500)
system/modules/isotope/group.php?do=iso_products&table=tl_iso_group&field=gid&value=0

**Comment by aschempp** [comment]
see contao/core#19

**Comment by aschempp** [comment]
This is a Contao core issue, Isotope cannot fix it.
