### ISSUE TITLE
group (using option manager) not displayed in cumulative filter

### ISSUE THREAD

**Issue by scuben** [isotope/core#1775]
I currently evaluate the possibilities of the cumulative filter. The goal was to set up a filter for wine growing regions grouped according to their country. e.g:

- italy
  - abruzzen
  - apulien
  - basilikata
- spain
  - de la Tierra
  - extremadura

remadura

The Backend version of this attribute works fine (set to select-menu):
![image](https://cloud.githubusercontent.com/assets/922919/23061504/75e4244c-f502-11e6-8583-cf47efd6270f.png)

The Frontend filter of this attribute is missing the group (the country in this case):
![image](https://cloud.githubusercontent.com/assets/922919/23061539/98f3aec6-f502-11e6-85e2-101d03dc6f38.png)

So my questions:
1. Is this the intended behaviour? And if not:
2. How is it possible to display the group (country)
3. And is it also possible not just display the group but also select the group to filter for all products with attribute defined within the selected group (e.g. all wines from italy, no matter in what exact region there were grown)

**Comment by aschempp** [comment]
This is exactly what we implemented for www.procava.ch. It is not possible out of the box (= just configuratino) but requires custom development for the client.
