### ISSUE TITLE
Integrity check can't disable rules

### ISSUE THREAD

**Issue by sleitz** [isotope/core#1777]
We installed Isotope in a Contao 4.3 managed-edition instance.
The integrity check complains about the rule module, which is active despite not being used.

There is an option to try and fix the problem automatically, but it does nothing useful. My guess is that it is not fit for Contao 4.

**Comment by netzarbeiter** [comment]
https://github.com/isotope/core/issues/1764

**Comment by sleitz** [comment]
And I did search! I did, I did, I did! :cry:

**Comment by netzarbeiter** [comment]
Thank you for reporting the bug and using the search ;-)
