### ISSUE TITLE
Reader Page Selection

### ISSUE THREAD

**Issue by rburch** [isotope/core#1779]
Suggested enhancement - Give the product reader page selection in site structure the option to apply to child pages. One of my client's sites has close to 500 product pages so it takes hours even with edit multiple to select the product reader page that they all share.

**Comment by aschempp** [comment]
Why would you have 500 product pages? You mean 500 product categories?

**Comment by rburch** [comment]
Haha, yes, 500 product categories. I know it’s a lot. They have a lot of sub categories and almost 7000 products.

**Comment by aschempp** [comment]
You might be better off using the cumulative filter…

**Comment by rburch** [comment]
You might be right, this could be the perfect use case for that. Especially because many of the categories 3 levels deep. At the moment that's not what they want though. The goal is over time to reduce and combine categories, but for now I just need to point them all to a reader.

**Comment by aschempp** [comment]
I'm closing this for now, as I don't think automatic inheritance is a good idea. Btw, this can easily be solved with overwrite-all.

**Comment by rburch** [comment]
You’re right, that’s what we ended up doing. I forgot that feature existed.
