### ISSUE TITLE
[2.4.0] "Erneut bestellen" erzeugt Problem im BE

### ISSUE THREAD

**Issue by Creasign** [isotope/core#1781]
Ich hatte "Erneut bestellen" in der Bestellübersicht aktiviert durch Auswahl einer Seite als Warenkorb. Dadurch konnte ich keine Bestellungen im BE mehr bearbeiten, die Buttons unten waren ohne Funktion, Speichern via Eingabe-Taste führte zu Fehlermeldung.

Fatal error: Call to a member function copyItemsFrom() on null in ***/web/system/modules/isotope/library/Isotope/Module/OrderDetails.php on line 154

**Comment by aschempp** [comment]
Fixed in e4f4a8e464027cf9701f1b57c832bd57f5f4f8fb
