### ISSUE TITLE
Allow multiple default variants for different member groups

### ISSUE THREAD

**Issue by sleitz** [isotope/core#1782]
Currently, a product variant can be the default variant for its product. Isotope is clever: It only allows on default variant to exist for each product. Promoting another variant to "default variant" toggles the switch of the former default variant.

In rare cases this is not the perfect solution. Imagine a shop with different member groups and a guest role. Product A has a number of variants:

- Wood: free for registered members in a certain group, only visible to such members
- Wood: 100€ for guests, and only visible for guests
- Steel: 200€ for anybody
- Gold: 500€ for anybody

In this case, we would like to set the cheapest variant as the default variant (more comfort for the user, no uncertainty about pricing etc.).

Members would need to see this option as default:

- Wood: free for registered members in a certain group, only visible to such members

Whereas guests need that variant as a default:
- Wood: 100€ for guests, and only visible for guests

Isotope does not allow this. There may only be one default variant, regardless of visibility and protection states.

Could this be a valid enhancement?

**Comment by aschempp** [comment]
As you wrote, I think this is a very rare case. I would see this as a custom development for your client. Adding it as a default feature will make the shop setup much more complex for all the regular users…
