### ISSUE TITLE
Allow lightbox view in Inline Gallery

### ISSUE THREAD

**Issue by k-webdesign** [isotope/core#1783]
Can we allow a lightbox view in the inline gallery?

At the moment this is only possible in the standard gallery, but would be also pretty useful as an optional feature in the inline gallery as the main image can be pretty small in a layout.

So "Bildanker" and the "Lightbox/Mediabox" palette have to be added into the inline gallery. Maybe we can spare "Bildanker" and use a simple checkbox instead which activates the settings in "Lightbox/Mediabox". 
![screenshot 2017-03-01 17 45 19](https://cloud.githubusercontent.com/assets/4130440/23470795/a5402dea-fea7-11e6-98c4-8454085483c5.png)

Do you need a scribble? :)

**Comment by aschempp** [comment]
see #1800
