### ISSUE TITLE
Kleinere Rechtschreibfehler in Isotope

### ISSUE THREAD

**Issue by jscholtysik** [isotope/core#1784]
Hi,

beim Durchschauen der Isotope-Optionen sind mir einige Rechtschreibfehler aufgefallen sowie fehlende Zurück-Links, die bei Verwendung des Browser-Back-Links teilweise Fehlermeldungen im Backend erzeugen...
[Isotope-Fehler.txt](https://github.com/isotope/core/files/813986/Isotope-Fehler.txt)

**Comment by Toflar** [comment]
Hey Joachim. Danke! Übersetzungen werden auf [Transifex](https://www.transifex.com/terminal42/isotope) gepflegt, du kannst sie dort selber ändern :)

**Comment by jscholtysik** [comment]
Hi Yanick,

nicht alles, was in der Textdatei enthalten ist, sind Rechtschreibfehler... ;-) Die RS-Fehler korrigiere ich dann auf Transifex...

**Comment by jscholtysik** [comment]
Rechtschreibfehler sind auf Transifex korrigiert (ich hoffe, ich habe alle gefunden... ;-) )
