### ISSUE TITLE
[2.4.1] Isotope\Model\Rule Line 283 triggers warning

### ISSUE THREAD

**Issue by intelligentspark** [isotope/core#1785]
https://github.com/isotope/core/blob/master/system/modules/isotope_rules/library/Isotope/Model/Rule.php#L283

Warning: mysql_real_escape_string(): Access denied for user ''@'localhost' (using password: NO)

Triggered on line 283:

`
$strRestriction .= "attributeValue" . ($restriction['condition'] == 'neq' ? " NOT" : '') . " IN ('" . implode("','", array_map('mysql_real_escape_string',$restriction['values'])) . "')";
`

Caused by Line 275 not catching an empty one-element array in $restriction['values']:

`
if (empty($restriction['values']))
     continue;
`

$restriction['values'] stores itself as a 1-element array with an empty string if the value is not set in the product, and triggers the warning since the empty() function does not evaluate to true.  I am able to eliminate the warning by removing "mysql_real_escape_string()" from line 283. Plus, that function is deprecated in PHP 7.  Perhaps reintroduce mysqli_real_escape_string() to handle sql injection attacks only if you have an actual value in that array?

**Comment by aschempp** [comment]
An empty-check is already performed in https://github.com/isotope/core/blob/master/system/modules/isotope_rules/library/Isotope/Model/Rule.php#L275

Should be fixed with 65f4ce1130e3db5b4949248570a35d242ab71d4c anyway.
