### ISSUE TITLE
PHP 7 compatibility

### ISSUE THREAD

**Issue by intelligentspark** [isotope/core#1786]
Are there plans in the works to ensure that isotope (isotope_rules, in this case) is php 7 compatible?  

As an example of where this becomes a problem, please refer to https://github.com/isotope/core/blob/master/system/modules/isotope_rules/library/Isotope/Model/Rule.php#L283

 mysql_real_escape_string() is used, but is deprecated in php 7.  Is it even necessary to use that since the final mysql statement goes through Database->prepare() function?

**Comment by aschempp** [comment]
It's supposed to be compatible, but that sure is a bug I need to fix.

**Comment by aschempp** [comment]
I have remove the use of this method in 65f4ce1130e3db5b4949248570a35d242ab71d4c
