### ISSUE TITLE
buttons in product frontend template not displayed

### ISSUE THREAD

**Issue by fraank** [isotope/core#1787]
In my case the array for "buttons" ($this->buttons) for checkout in all product templates are an empty array. As result the buttons for product interaction are not displayed.

I figured out that on line 503 in Model/Product/Standard.php you are checking is_array($arrConfig['buttons']). In my case the value of the variable is not an array but a string with following content:

`a:2:{i:0;s:11:"add_to_cart";i:1;s:6:"update";}`

I think some parsing is not done correctly. Can someone figure out what goes accidentally wrong here? I'm using contao 3.5.6 and the latest 2.4.1 isotope.

**Comment by Toflar** [comment]
Please make sure you have the correct dependencies. The Extension Repository does not resolve them correctly, you always have to double check manually (or use Composer that does this perfectly).

**Comment by fraank** [comment]
Yes, you're right. Following this https://isotopeecommerce.org/de/handbuch/v/2.4/r/composer.html fixes the dependency problem. Never thought of using package management outside of terminal ;)
