### ISSUE TITLE
[2.4.1] Invalid post-sale request (param error) - PayPal IPN Error

### ISSUE THREAD

**Issue by remood** [isotope/core#1788]
Seit ca. 07.03.2017 gibt es (scheinbar) Probleme mit der PayPal IPN Rückmeldung nach erfolgreicher Bezahlung einer Bestellung. Der User wird nach der PayPal Zahlung auf die "Ihre Zahlung wird durchgeführt. Bitte haben Sie Geduld..." Seite weitergeleitet, die dann nach ca. 30 Sekunden abbricht und auf den letzten Bestellschritt (Zusammenfassung) zurückgeht. Die Zahlung wurde durchgeführt, aber es wird keine Bestellung in isotope angelegt. Dieses Problem tritt nicht bei jeder Bestellung mit PayPal auf, sondern nur in ca. 30% der Fälle, ist also nur mit mehrfacher Bestellung in einem Live-System reproduzierbar. Problem tritt bei aktuellen Versionen auf (Contao 3.5.24, isotope 2.4.1), aber auch bei älteren Versionen (Contao 2.11.12 / isotope 1.4)

Im Systemlog erscheint die Fehlermeldung

> Ursprung:	Frontend
> Kategorie:	ERROR
> Benutzer:	
> Details:	Invalid post-sale request (param error): system/modules/isotope/postsale.php?mod=pay
> Funktion:	Isotope\PostSale::run
> IP-Adresse:	173.0.81.0
> Browser:	PayPal IPN ( https://www.paypal.com/ipn )

Der Bug scheint schon mehrere Shops zu betreffen, siehe Ende des Threads:

https://community.contao.org/de/showthread.php?64150-Isotope-Paypal-Problem-Payment-could-not-be-processed&p=434512&viewfull=1#post434512

**Comment by aschempp** [comment]
Looks like this was a temporary PayPal issue.
