### ISSUE TITLE
Unable to extend the tl_iso_payment dca

### ISSUE THREAD

**Issue by LeoUnglaub** [isotope/core#1790]
Hey,
after an update to 2.4.1 i am unable to extend the dca for the table tl_iso_payment. In the old version of isotope it worked fine, but since the update the database update tool does not find the fields anymore.

Here is how to reproduce it:

1. Download the Isotope demo from the official website
2: Update Contao to the latest release (3.5.25)
3: Update all extensions to the latest version
4: Create a new file in system/modules/zzzzzzz/dca/tl_iso_payment.php
5: Place the following code in it and run the database update.

Now the database update does not find any new fields to add to the database

``` php
$GLOBALS['TL_DCA']['tl_iso_payment']['fields']['fooooooo'] = array
(
    'label'     => &$GLOBALS['TL_LANG']['tl_iso_payment']['fooooooo'],
    'sql'       => "varchar(250) NOT NULL default ''",    
    'exclude'   => true,                                  
    'search'    => true,                                  
    'inputType' => 'text',                                
    'eval'      => array
    (
        'mandatory'     => true,
        'tl_class'      => 'w50',
    ),
);
```

When i replace tl_iso_payment with for example tl_member the database update tool finds the new field and adds it to the database.

Greetings
Leo

**Comment by aschempp** [comment]
I dont think thats related to isotope. Did you clear the internal cache and added the autoload.ini to define the requirements of your extension?

**Comment by LeoUnglaub** [comment]
Yes i cleared all caches (including using bypass internal cache) and also use isotope as a requirement in my autoload.ini. It also works fine for all other tables in this installation (including other isotope tables). Thats why i thought it's an isotope problem.

**Comment by aschempp** [comment]
I can't think of a reason why it could be, tl_iso_payment is a standard DCA like any other. The only special think in Isotope is tl_iso_product.

**Comment by aschempp** [comment]
I guess you solved the issue?

**Comment by LeoUnglaub** [comment]
Not really. I created the fields via mysql directly because did not have that much time. But since this seams to only affect me you can close this now. If someone else has this problem i think we can reopenit.

Greetings
Leo
