### ISSUE TITLE
Fehlerhafter Pfad bei Produktbildern unter Contao 4.3

### ISSUE THREAD

**Issue by Ainschy** [isotope/core#1794]
Bilder die nicht angepasst werden müssen, erhalten den Pfad zum isotope Produktbild Ordner, dieser wird unter Contao 4 nicht richtig aufgelöst.

**Comment by aschempp** [comment]
Das Problem ist vermutlich der fehlende Symlink in den `web`-Ordner...

**Comment by mecintosch** [comment]
Kann den Fehler bestätigen. Im Backend wird das Produktbild angezeigt im Frontend nicht. Der Isotope Bildordner befindet sich unter Contao 4 außerhalb des /web Ordners.

Bleibt wohl nur die Bilder größer als gewünscht hochzuladen. 
Neu berechnete Bilder werden angezeigt.

**Comment by aschempp** [comment]
@isotope/developers how should we solve this? The `contao:symlinks` command is currently not extendable. I can think of three solutions, but I'm not really happy with any of them:

 1. Use the `kernel.command` or `kernel.terminate` event to create the symlink when `contao:symlinks` is called. We can't tell the user about it though, at least not in the same manner as the Contao output.
 2. Add our own command. Which means the user has to call it, and we probably can't add it to the Managed Edition `initializeApplication` composer script.
 3. Move the folder to `/web` if the installation is Contao 4. Not sure how to handle existing installations though.

**Comment by rabauss** [comment]
4. can't we move it to files/isotope? the files folder is symlinked by default from contao...
or why is the contao file manager not used for the pictures?

**Comment by aschempp** [comment]
The solution will be to create a symlink, like the core does for all other files.

 1. Add a Contao Manager plugin that has the `ConfigPluginInterface`
 2. Use the config loading to register an event listener on `kernel.command`
 3. Add an event listener that adds the symlink when the Contao symlinks are created

**Comment by fritzmg** [comment]
In the mean time you could just execute
```
ln -s ../isotope isotope
```
in within the `web/` folder.

**Comment by aschempp** [comment]
Implemented in c551a9bdfa7f10e02a632fa52bf941d236b5fdfb

**Comment by fritzmg** [comment]
The fix does not work under Windows. You'll get the following error message after a composer update:
```

[Symfony\Component\Filesystem\Exception\IOException]
Failed to create symbolic link from "..\isotope" to "C:\xampp\htdocs\website\app\..\web\isotope".
```
I'll probably create a PR for this on the weekend.

**Comment by bytehead** [comment]
How is this supposed to work in a non-managed environment? And with `public` instead of `web`? 😬

**Comment by aschempp** [comment]
> How is this supposed to work in a non-managed environment? And with `public` instead of `web`? 😬

how is _what_ supposed to work?

**Comment by bytehead** [comment]
Symlinking the `isotope` directory :)

**Comment by bytehead** [comment]
Or is the `contao:symlinks` command extendable in the meantime?

**Comment by aschempp** [comment]
Not that I know of. But you can always add that symlink yourself, right?

**Comment by bytehead** [comment]
I can for sure. But it's not that obvious of a bug for less experienced people. But possible only fixable if isotope ships as a bundle because of the service definitions...?

**Comment by fritzmg** [comment]
The `contao:symlinks` command triggers the [`contao.generate_symlinks`](https://docs.contao.org/dev/reference/events/#contao-generate-symlinks) event with which you can pass your own symlinks to be generated.

**Comment by bytehead** [comment]
> The contao:symlinks command triggers the [contao.generate_symlinks](https://docs.contao.org/dev/reference/events/#contao-generate-symlinks) event with which you can pass your own symlinks to be generated.

But shouldn't that be a part of isotope?

**Comment by fritzmg** [comment]
Ideally, yes. Not sure if a Contao 3 style extension can somehow still register an event listener? Isn't there a bridge for that from the CCA?

**Comment by aschempp** [comment]
Isotope already does register such stuff, but it uses the manager plugin for it. I think it could only be done different with a bundle, which we don't have atm :(
