### ISSUE TITLE
Steuersatz kann nicht von Versandadresse abhängig gemacht werden 

### ISSUE THREAD

**Issue by chabluetzel-pwc** [isotope/core#1796]
Hallo

Ich habe beim Webshop für unseren Kunden festgestellt, dass obwohl es eine spezifische Backend-Einstellung für den Anwendungsfall gibt, die Mehrwertsteuer trotzdem nicht von der Versandadresse abhängig gemacht werden kann.

### 01 Situations-Beschreibung der Backend-Konfigurationen
Es herrschen folgende Einstellungen in der Shop-Konfiguration:

Konfigurierte Steuerklassen:
1. Es ist 1x Steuerklasse konfiguriert: "MWST Standard" mit den folgenden Einstellungen:
-> Name: **MWST Standard**
-> [x] Standard 
-> Steuerklasse im Produktpreis enthalten: "-"
-> Steuersätze hinzufügen: [x] MWST CH, [x] MWST DE
-> Es sind keine weiteren Felder spezifiziert

Konfigurierte Steuersätze:
1. -> Name: **MWST CH**
-> Steuersatz: 8%
-> Adressbasis für die Berechnung: [x] Versandadresse
-> Länder: "Schweiz"
-> Shop-Konfiguration: Standard Shop-Konfiguration ist ausgewählt
-> Es sind keine weiteren Felder spezifiziert
2. -> Name: **MWST DE**
-> Steuersatz: 19%
-> Adressbasis für die Berechnung: [x] Versandadresse
-> Länder: "Deutschland"
-> Shop-Konfiguration: Standard Shop-Konfiguration ist ausgewählt
-> Es sind keine weiteren Felder spezifiziert

### 02 Situations-Beschreibung der Beobachtungen im Frontend

**Situation bei Versandadresse = Adressbasis**
Wenn ich ein Steuersatz entsprechend konfiguriere, dass die Versandadresse als Adressbasis gilt, dann scheint der Steuersatz im Frontend nicht zu greifen, sprich, ich erhalte einen Steuersatz von 0%. 

**Situation bei Rechnungsadresse = Adressbasis**
Wenn ich den Steuersatz hingegen so konfiguriere, dass die Rechnungsadresse als Adressbasis gilt, dann greift der Steuersatz. Damit ist jedoch das nachfolgend beschriebene gewünschte Verhalten nicht gewährleistet.

**Situation bei Versandadresse + Rechnungsadresse = Adressbasis**
Wenn ich die Rechnungsadresse, sowie auch die Versandadresse (ist ja ein Multi-Select) beide ankreuze, dann verhält sich der Checkout als hätte ich nur die Rechnungsadresse als Adressbasis konfiguriert.

### 03 Gewünschtes Verhalten

Wenn ich als User ein Produkt nach Deutschland zu meinem Kollegen liefern lassen möchte, die Rechnung aber selbst bezahlen möchte und zu mir in die Schweiz schicke, dann soll der deutsche Mehrwertsteuersatz (19%) für die Rechnung gelten.

### 04 Handbuch als Referenz

Ich habe mir die entsprechende Seite zu dieser Funktion im Handbuch angeschaut. Die Funktion zur "Adressbasis für die Berechnung" wird dort wie folgt beschrieben:

> Wähle auf Basis welcher Adresse dieser Steuersatz berechnet werden soll. Die Versandadresse für nicht versendbare Produkte.

URL: https://isotopeecommerce.org/de/handbuch/v/2.4/r/steuersaetze.html

Diese Beschreibung scheint mit meiner obig beschriebenen Beobachtung nicht überein zu stimmen.

### 05 Referenz Contao Version

Wir verwenden in dem beschriebenen Fall Contao 3.5.4 mit Isotope 2.3.2.

Es wäre super, wenn die Situation gelöst werden könnte und ich bedanke mich bereits jetzt schon mal für's Zeit nehmen.

**Comment by aschempp** [comment]
Welches Land hast du als Standardversand in der Shopkonfiguration?

**Comment by chabluetzel-pwc** [comment]
Ich habe als Standard Rechnungsland "Schweiz" und als Standard Versandland ebenfalls "Schweiz" ausgewählt.

Es sind insgesamt 4 Länder bei beiden zur Auswahlmöglichkeit zugelassen: Schweiz, Deutschland, Liechtenstein, Österreich

Quelle der Einstellung: Allgemeine Einstellungen > Konfigurationen > Standard-Konfiguration

**Comment by aschempp** [comment]
Isotope 2.3.2 ist veraltet, dieser Fehler wurde in 2.3.3 bereits behoben.
