### ISSUE TITLE
Versandregel mit Mengenberechnung

### ISSUE THREAD

**Issue by mecintosch** [isotope/core#1797]
Es sind mehrere Produkttypen definiert die unterschiedliche Versandregeln haben. Funktioniert prinzipiell, jedoch nicht bei Regeln die mit Mengenberechnungen funktionieren.

Folgende Regeln gibt es vereinfacht:
1) Betrag X für Produkttyp A, Menge 1-6
2) Betrag Y für Produkttyp A, Menge 7-12 
3) Pauschalbetrag für Produkttyp B

Es sind 6 Produkte Typ A und 1 Produkt Typ B im Warenkorb, berechnet werden die Regeln 2+3 statt 1+3. 

Hätte gedacht genau für solche Fälle kann man die Versandarten für Produkttypen einschränken oder?

**Comment by aschempp** [comment]
Erst mal, es gibt keine Versandregeln, sondern nur Preisregeln. Die Anzahl bezieht sich dabei (vermutlich) auf alle Produkte, nicht nur auf das gewählte. Entsprechend wird das nicht funktionieren. Womöglich kannst du das aber über verschiedene Versandmethoden lösen, ansonsten müsstest du das wohl für deinen Fall programmieren lassen…
