### ISSUE TITLE
Detailseite verwenden: Link zeigt auf Produktliste

### ISSUE THREAD

**Issue by civ23** [isotope/core#1799]
Entweder habe ich es falsch verstanden oder die Ausgabe des Hyperlinks ist falsch.

Ich habe eine Seite Produktliste und eine Seite Produktdetails.
In den Seiteneinstellungen von "Produktliste" ist "Detailseite benutzen" angehakt und die Seite "Produktdetails" ausgewählt. Die Frontendmodule sind auch entsprechend
in den Seiten eingebunden.

Die Links in der Liste verweisen aber auf /produktliste/produkt.html anstatt /produktdetails/produkt.html

Ich habe es provisorisch so gelöst:
In der Klasse Isotope\Model\Product\Standard  in der Methode generateUrl() überprüfen, ob in $objJumpTo eine Weiterleitung angegeben ist und vor dem return entsprechend $objJumpTo mit der Zielseite überschreiben.

```php
if ($objJumpTo->iso_setReaderJumpTo)
{
	$objJumpTo = \PageModel::findByPk($objJumpTo->iso_readerJumpTo);
}
```

**Comment by aschempp** [comment]
Es ist Absicht dass das Alias der Listenseite benutzt wird. Hier verhält sich Isotope anders als andere Contao Module. Hintergrund ist, dass du die Listenseite vermutlich nach Themen benennen solltest. Beispiel: `schuhe.html` und `t-shirts.html`. Und dann heisst die Detailseite eben `schuhe/produkt1.html` und `t-shirts/produkt2.html`. Sie soll nicht `produktdetails/produkt1.html` heissen.

**Comment by civ23** [comment]
Ok, vielen Dank!
