### ISSUE TITLE
[Contao4] Probleme mit Produktgruppen und verschieben in diese

### ISSUE THREAD

**Issue by jedoStyle** [isotope/core#1801]
1. Wenn ich unter "Produkte" auf das gelbe "Netzwerkordner"-Symbol klicke (Tooltip "Produkt ID n in eine Gruppe verschieben") öffnet sich als modales Fenster "Produktgruppen" mit einer Auflistung aller Produktgruppen mit Radio-Button zum Auswählen. 

Wenn ich eine Produktgruppe auswähle und auf Anwenden klicke passiert ... Nichts!

2. Wenn ich oben auf Gruppen klicke und dann eine auswähle oder alle abwähle passiert danach auch nicht.

![screenshot at mai 27 16-55-18](https://cloud.githubusercontent.com/assets/1821865/26522311/0fa16b1e-42fe-11e7-9381-b91ca3c8fe59.png)

Der Spinner dreht auch nicht. (der steht still - neben Daten werden geladen)

Contao 4.3.10; 
Isotope 2.4.1

**Comment by netzarbeiter** [comment]
Das Problem kann ich unter Contao 4.3.10 und Isotope eCommerce 2.4.1 nachstellen.
Die Demo mit Contao 3.5.27 und Isotope eCommerce 2.4.1 funktioniert hingegen einwandfrei.

**Comment by Ainschy** [comment]
Seiten/Gruppen lassen sich wählen aber der Reload bleibt aus. Erst ein manueller Reload aktualisiert die Ansicht.

**Comment by aschempp** [comment]
Fixed in a0d2ba24080af3878c098d0515a2849bf7177ae0
