### ISSUE TITLE
[Contao 4] First Value no array in Member Callback.php > limitCountries (array_intersect_key)

### ISSUE THREAD

**Issue by rabauss** [isotope/core#1803]
In contao 4 the DCA of tl_member is a little bit different, so the following options key in the dca array cannot be found:
`$GLOBALS['TL_DCA']['tl_member']['fields']['country']['options']`
The new key is obviously `['options_callback']`.

We have disabled limitMemberCountries, so the callback wont be called. But otherwise you get warnings because of the missing options...

**Comment by aschempp** [comment]
Fixed in f7ded781c658477d10585c87a5864928412d04e7
