### ISSUE TITLE
[2.4.1] Fehlerhafter Link zu Download in Bestellbenachrichtigung

### ISSUE THREAD

**Issue by Mynyx** [isotope/core#1804]
In Bestellbenachrichtigungen ist bei Download-Artikeln der Link zum Download (unter der Überschrift "Ihre Produkte zum Herunterladen") fehlerhaft, es ist ein leeres href-Attribut angegeben.

**Comment by aschempp** [comment]
Ich vermute die E-Mail wird in deinem Fall beim ändern des Bestellstatus im Backend versendet. Das ist leider ein Konzept-Problem, denn in diesem Fall weiss Isotope nicht auf welcher Seite sich das Bestellbestätigungs-Formular befindet und kann entsprechend auch keine Links generieren.

In f827f5c04d662598cc7a59901b7aec20f849cb54 habe ich das angepasst dass keine leeren Downloads generiert werden. Die lokale Lösung für dich wäre eventuell eine Template-Anpassung und den Download-Link dann selber einbauen.
