### ISSUE TITLE
[2.4.1] Bestellbenachrichtigung wird doppelt versandt

### ISSUE THREAD

**Issue by Mynyx** [isotope/core#1805]
Wenn man eine Benachrichtigung anlegt und bei dieser als Benachrichtigungstyp "Änderung Bestellstatus" auswählt und anschließend unter Shop-Konfiguration einem Bestellstatus diese Benachrichtigung zuweist, wird die Benachrichtigung bei Abschluss einer Bestellung doppelt versandt.

**Comment by Toflar** [comment]
Nur, wenn man sowohl im Status als auch in den Einstellungen des Frontend-Moduls was ausgewählt hat.
