### ISSUE TITLE
[Contao 4] mehrere Bearbeiten bei Produkten -> Kategorieauswahl keine Übernahme

### ISSUE THREAD

**Issue by Ainschy** [isotope/core#1807]
Bei der Arbeit unter Contao4 und isotope 2.4.1 stoße ich immer wieder auf Schwierigkeiten bei den Ajax Requests  z.B. kein Reload nach Änderungen (Gruppe/Seiten Auswahl unter Produkte ) 

Bei "Mehrere bearbeiten" der Kategorie Zuordnung bei Produkten erscheint die Auswahl, diese wird aber nicht übernommen. Die Console gibt folgenden Fehler aus:

````
Uncaught TypeError: Cannot read property 'getElementsByTagName' of null
    at Object.<anonymous> (core.min.js:2)
    at HTMLAnchorElement.a (mootools.min.js:3)
(anonymous) @ core.min.js:2
a @ mootools.min.js:3
````

**Comment by aschempp** [comment]
Welche Contao4-Version?

**Comment by Ainschy** [comment]
war die 4.3 aber ist schon längste behoben.

**Comment by aschempp** [comment]
Also ticket schliessen?
