### ISSUE TITLE
[Contao 4] - related products - Individual template has no templates [isotope 2.4.1]

### ISSUE THREAD

**Issue by Ainschy** [isotope/core#1809]
Das Feld Individuelles Template ist bei dem Modul ähnliche Produkte leer. Unter Contao 3.5 finde ich die Templates, unter Contao 4.0 nicht. 

Andere Module (Listen + Reader) bieten hier eine Auswahl an .

**Comment by Ainschy** [comment]
verklickt ....

**Comment by aschempp** [comment]
Das wird leider nicht gehen, da Contao die Optionen anhand des Modultype berechnet, das Modul aber dasselbe Template wie die Produktliste verwendet.

Ich hab das Feld deshalb in fad8a5a540b64339dbb20d2aa82530e9901d115a entfernt.
