### ISSUE TITLE
[Contao 4] Attribut Downloads / Dateibaum Fehler

### ISSUE THREAD

**Issue by mecintosch** [isotope/core#1812]
Das Attribut ist angelegt und beim Produkttyp aktivert. 
Beim Artikel kann die Datei ausgewählt werden, beim Speichern erhalte ich diesen Fehler:

`An exception occurred while executing 'UPDATE tl_iso_product SET anhang='��[\\����H[9�I' WHERE id='6'': SQLSTATE[42S22]: Column not found: 1054 Unknown column 'anhang' in 'field list'`

Isotope 2.4.1 unter Contao 4.4

**Comment by aschempp** [comment]
kannst du mal per Datenbank-Update im Install-Tool prüfen ob alle Felder angelegt sind?

**Comment by mecintosch** [comment]
Genau das wars! Nach dem Datenbank-Update läufts.
