### ISSUE TITLE
[Contao 4.4.0] Simple Tokens ##cart_html## und ##cart_text## werden nicht in E-Mail übertragen

### ISSUE THREAD

**Issue by mpitz** [isotope/core#1814]
Die beiden Simple Tokens ##cart_html## und ##cart_text## werden nicht beim Versand der E-Mail berücksichtigt bzw. sind in der versendeten E-Mail leer.

Getestet in Contao 4.4.0 und Isotope 2.4.1 auf zwei Installationen.

**Comment by mpitz** [comment]
Das Problem scheint nur bei der Contao 4.4.0 Standard-Edition aufzutreten. Hier werden bei meiner Installation in der AppKernel.php die Module so geladen:

```php
// Isotope-Module BEGIN
new ContaoModuleBundle('conditionalselectmenu', $this->getRootDir()),
new ContaoModuleBundle('dc_multilingual', $this->getRootDir()),
new ContaoModuleBundle('dcawizard', $this->getRootDir()),
new ContaoModuleBundle('haste', $this->getRootDir()),
new ContaoModuleBundle('isotope', $this->getRootDir()),
new ContaoModuleBundle('isotope_reports', $this->getRootDir()),
new ContaoModuleBundle('isotope_rules', $this->getRootDir()),
new ContaoModuleBundle('multicolumnwizard', $this->getRootDir()),
new ContaoModuleBundle('notification_center', $this->getRootDir()),
new ContaoModuleBundle('tablelookupwizard', $this->getRootDir()),
// Isotope-Module END
```

Im Backend sehe ich dann die Module Notification Center und Isotop in dieser Reihenfolge:
![image](https://user-images.githubusercontent.com/6831223/27863629-54abfac0-618b-11e7-917e-4eaea8e27545.png)

Eine Installation in der Contao 4.4.0 Managed Edition zeigt die beiden Module umgekehrt.
Auch werden in den Benachrichtigungen unter Benachrichtigungstyp "Änderung Bestellstatus" keine weiter Konfigurationsmöglichkeiten angezeigt:
![image](https://user-images.githubusercontent.com/6831223/27863662-7d8e1ba8-618b-11e7-9036-725609f5bda3.png)

**Comment by Toflar** [comment]
Und was genau hat das mit Isotope zu tun dann? Die Reihenfolge ist schon relevant!

**Comment by mpitz** [comment]
Danke für die Antwort. 

Ich denke es hat entfernt was mit Isotope/Notification Center zu tun, da hier die Reihenfolge der Beiden zueinander wichtig ist und ja das Einstellen der Reihenfolge an sich hat nichts mit dem Isotope oder Notification Center zu tun.

Wie muss die Reihenfolge denn sein und wie und wo stelle ich das korrekt ein?

**Comment by rabauss** [comment]
notification-center muss wegen abhängigkeit vor isotope geladen werden!
wir haben folgende reihenfolge:

```php
new Contao\CoreBundle\HttpKernel\Bundle\ContaoModuleBundle('conditionalselectmenu', $this->getRootDir()),
new Contao\CoreBundle\HttpKernel\Bundle\ContaoModuleBundle('haste', $this->getRootDir()),
new Contao\CoreBundle\HttpKernel\Bundle\ContaoModuleBundle('dcawizard', $this->getRootDir()),
new Contao\CoreBundle\HttpKernel\Bundle\ContaoModuleBundle('multicolumnwizard', $this->getRootDir()),
new Contao\CoreBundle\HttpKernel\Bundle\ContaoModuleBundle('tablelookupwizard', $this->getRootDir()),
new Contao\CoreBundle\HttpKernel\Bundle\ContaoModuleBundle('notification_center', $this->getRootDir()),
new Contao\CoreBundle\HttpKernel\Bundle\ContaoModuleBundle('dc_multilingual', $this->getRootDir()),
new Contao\CoreBundle\HttpKernel\Bundle\ContaoModuleBundle('isotope', $this->getRootDir()),
new Contao\CoreBundle\HttpKernel\Bundle\ContaoModuleBundle('isotope_reports', $this->getRootDir()),
new Contao\CoreBundle\HttpKernel\Bundle\ContaoModuleBundle('isotope_rules', $this->getRootDir()),
```

**Comment by mpitz** [comment]
Vielen Dank!

Diese Zusammenstellung fehlte mir. Es funktioniert jetzt.

**Comment by Toflar** [comment]
BTW: https://github.com/isotope/core/blob/master/system/modules/isotope/config/autoload.ini 😄
