### ISSUE TITLE
[Contao 4] Attribut Textarea - kein TinyMCE

### ISSUE THREAD

**Issue by mecintosch** [isotope/core#1815]
Hab hier leider keine Auswahl bei "Nutze HTML-Editor" - das Select ist leer.

**Comment by netzarbeiter** [comment]
https://github.com/isotope/core/blob/master/system/modules/isotope/library/Isotope/Backend/Attribute/Callback.php#L139-L143

**Comment by mecintosch** [comment]
Habe ganz brutal die tinyMCE.php aus einer Contao 3.5 Installation in das system/config Verzeichnis von Contao 4 kopiert. Eine Übergangslösung, aber funktioniert.

**Comment by aschempp** [comment]
Fixed in a936fdb1cec21766505c6b29596e79890189020c
