### ISSUE TITLE
orderstatus->notification options_callback without filtering by type 'iso_order_status_change'

### ISSUE THREAD

**Issue by rabauss** [isotope/core#1816]
Unfortunately the options_callback for the notification in tl_iso_orderstatus works without filtering the notification by type 'iso_order_status_change'. 

because NotificationCenter\tl_module->getNotificationChoices is using the type-attribute of the module for filtering, which is defined in isotope/dca/tl_module for the frontend-modules

obviously the callback has to be replaced by own method, which filters the notifications by type 'iso_order_status_change'

**Comment by aschempp** [comment]
Fixed in 71c4caae2f6e5c09ce29a2de9d4307b81cc7afbe
