### ISSUE TITLE
Cookie / Umleitungsfehler als eingeloggter FE-User

### ISSUE THREAD

**Issue by mecintosch** [isotope/core#1817]
Sobald man als eingeloggter FE User eine Isotope Seite (Warenkorb, Produktliste) öffnet bekommt man einen Cookie Fehler. Öffnet man eine Seite auf der kein Isotope Modul eingebunden ist funktionierts.

Isotope unter Contao 4.4

![27639363-3f9e0760-5c16-11e7-8855-07a90f635e0c](https://user-images.githubusercontent.com/16761621/27902337-b23f8d3c-6235-11e7-9684-5ed99f99e460.png)

**Comment by aschempp** [comment]
This is actually with our [header-replay-bundle](https://github.com/terminal42/header-replay-bundle) which is used by Contao 4.4. I've added a conflict in 7d80cf3ab373be62ad65a603181e24610573f62a which basically prevents Isotope from being installed on Contao 4.4 until the issue is fixed there.

**Comment by mecintosch** [comment]
Wie fahre ich mit meiner Installation fort?
Den Ordner vendor/terminal42/header-replay-bundle löschen?

**Comment by Toflar** [comment]
Scheint nicht das alleinige Problem zu sein, wir konnten den Fehler noch nicht komplett beheben.

**Comment by fritzmg** [comment]
Gibt's da schon einen ETA? Verwende Isotope momentan auch in einer Contao 4.4 Installation, die demnächst online gehen soll.

**Comment by Toflar** [comment]
Ich glaube dein Problem wird durch die 4.4.1 behoben. Andy's commit ist nur eine allgmeine Verbesserung (kein Cookie setzen, wenn nicht nötig).

**Comment by fritzmg** [comment]
Verstehe. Hat @leofeyer schon ein ETA für die `4.4.2`? 😁 Die Redakteure unserer aktuellen Contao 4.4. Installationen die in Arbeit sind werden schon ein wenig ungeduldig wegen dem Picker Problem.

**Comment by netzarbeiter** [comment]
@fritzmg Mit dem Hotfix der 2.4.2 und Contao 4.4.1 taucht bei mir wenigstens der Umleitungsfehler nicht mehr auf.
