### ISSUE TITLE
Contao 4.4: close button in simple modal window not active

### ISSUE THREAD

**Issue by fritzmg** [isotope/core#1819]
The close button of the simple modal window that Isotope eCommerece and the Notification Center uses at various places has a close button that cannot be used (see screenshot).

![screen shot 2017-07-06 at 17 31 47](https://user-images.githubusercontent.com/4970961/27919223-664327ea-6271-11e7-8e86-8b14725bcd80.png)

The only way to close the modal window is to click outside of it. I am not sure if this is a `contao/core-bundle` bug or a problem with the affected extensions. I have only noticed this with modal windows from extensions so far (e.g. Isotope and Notification Center).

**Comment by aschempp** [comment]
That's actually an issue in the `dcawizard` extension

**Comment by qzminski** [comment]
@aschempp you can close this issue, I have opened the appropriate ticket in dcawizard repository.
