### ISSUE TITLE
Unnötige Fehlermeldung bei Verwaltung von Steuersätzen

### ISSUE THREAD

**Issue by soletan** [isotope/core#1820]
Szenario:

* Shop Konfiguration
* Steuersätze
* Steuersatz bearbeiten
* Es ist kein Land gesetzt. Daher zeigt die Auswahl der Bundesländer nur `-`.
* Wenn man diesen einen Eintrag anwählt und speichert, dann erscheint eine Fehlermeldung über eine ungültige Fehlermeldung.

Als Entwickler kann ich verstehen, was die Intention dabei ist. Aber Angestellte bei uns mit weniger Programmierer-Mentalität waren davon irritiert. `-` steht ja eigentlich für "keine", "nichts" ... warum ist es falsch, die Option anzuwählen, obwohl sie nicht anzuwählen richtig wäre?

IMHO natürlich ein nachrangiger Bug, mehr ein Schönheitsfehler. Man könnte die Liste ja auch leer lassen oder einfach den markierten `-` einfach ignorieren.

**Comment by aschempp** [comment]
Das ist tatsächlich ein Contao core bug: https://github.com/contao/core/issues/8781

**Comment by aschempp** [comment]
The correct solution probably is to add a blank option in the field configuration.

**Comment by aschempp** [comment]
This should be fixed in conditionalselectmenu 3.0.4
