### ISSUE TITLE
Checkout Button PreviousStep führt weiter

### ISSUE THREAD

**Issue by buster39** [isotope/core#1822]
Hallo,

wie oben beschrieben, bringt mich in der Kasse der "Zurück"-Button einen Schritt nach vorne im Verlauf.

Danke für diesen Shop!

**Comment by aschempp** [comment]
Welche Isotope-Version verwendest du? Und versuch es nochmals mit den Original Templates falls du diese angepasst hast!

**Comment by buster39** [comment]
Hi,

Contao 3.5.19 mit Isotope 2.4.0-RC1
Hab's mal mit nem Original-Template in der Kasse versucht - gibt mir den gleichen Ablauf wie oben.

Ist das nur bei mir so?

Thx

**Comment by aschempp** [comment]
Warum benutzt du eine veraltete Version? ;-)

**Comment by buster39** [comment]
Mein Fehler, sorry!
Ich hatte mich auf die Erweiterungsverwaltung in Contao verlassen, da stand bei mir, 2.4.0 sei aktuell. 
Schönen Sonntag
