### ISSUE TITLE
Produkt mit Zusatz führt zu falschen Bildern

### ISSUE THREAD

**Issue by paulhaem** [isotope/core#1824]
Hallo,
folgendes Szenario:

Produkte haben als zusätzliches Attribut ein kleines optionales Textfeld "Zusatz". Dieser Zusatz wird im Warenkorb dargestellt.

Wenn ich nun ... 
1. Produkt A ohne Zusatz / mit Zusatz in den Warenkorb einfüge
2. Produkt B ohne Zusatz in den Warenkorb einfüge
3. Produkt A mit Zusatz in den Warenkorb einfüge

Hat das zweite Produkt A dasselbe Bild wie Produkt B. Preis und sonstige Daten stimmen. Wenn ich nun Produkt B aus dem Warenkorb entferne, so erhält das zweite Produkt A plötzlich das richtige Bild.

Bug oder fehlerhafte Konfiguration?

**Comment by aschempp** [comment]
Welche Isotope-Version verwendest du? Ich kann mich erinnern dass wir solch ein Problem bereits mal behoben hatten…

**Comment by paulhaem** [comment]
Contao 3.5.28
Isotope 2.3.5.9006

Im Laufe dieser Woche wird auf 2.4.1 upgedated.

**Comment by paulhaem** [comment]
Ähnliches Issue: https://github.com/isotope/core/issues/889

**Comment by paulhaem** [comment]
Isotope ist nun auf Version 2.4.2, Fehler noch vorhanden.

Zwischenzeitlich ist mir noch aufgefallen, dass es unabhängig vom "Zusatz" ist. Sobald ich ein weiteres Produkt A, welches ein Frontend-Attribut (z.B. Size, Color, ...) hat, einfüge, tritt oben genannter Fall ein.

**Comment by paulhaem** [comment]
Konnte den Fehler mit einer frischen Contao Installation reproduzieren.

Contao 3.5.28
Isotope 2.4.2
(isotope_quickproducts dev-develop)

PHP 5.6.21

Oben beschriebener Prozess hier abgebildet:

![contao_isotope_imageissue1](https://user-images.githubusercontent.com/6862218/28660252-955f6524-72b2-11e7-9593-ec85ecf22d5f.png)

Sobald dann "Produkt B" entfernt wird, erhält das zweite Produkt A wieder das richtige Bild:

![contao_isotope_imageissue2](https://user-images.githubusercontent.com/6862218/28660253-956000ba-72b2-11e7-8041-a819b986cd09.png)

**Comment by aschempp** [comment]
Ich kann das Problem mit der Isotope Demo nicht nachstellen. Sicher dass du keine angepassten Templates verwendest? Und deaktiviere mal alle Erweiterungen.

**Comment by paulhaem** [comment]
Konnte das Problem in der Isotope-Demo reproduzieren.

![contao_isotope_imageissue3](https://user-images.githubusercontent.com/6862218/28669346-446aa1d4-72d4-11e7-8bea-e8f0e2b6ac2e.png)

Was ich gemacht hab:
1. Neues Attribut erstellt: Textfeld, Produktoptions-Einstellungen, Durch den Kunden auswählbar, Eingabeprüfung: Erweiterte alphanumerische Zeichen
2. Den Produkttypen CD (Produkt-Attribute) und T-Shirt (Varianten-Attribute) jeweils dieses Attribut hinzugefügt
3. Im Frontend: T-Shirt Würzburg hinzugefügt (Weiss, S, leeres Textfeld), CD A Perfect Circle hinzugefügt 
 (leeres Textfeld), T-Shirt Würzburg hinzugefügt (Weiss, S, befülltes Textfeld)

**Comment by Ainschy** [comment]
Das kann ich bestätigen, habe den gleichen Fehler in der Version 2.4.3 unter Contao 4.4.3
Alle Angaben zum Produkt stimmen, außer das Bild.

**Comment by Ainschy** [comment]
Die fehlerhafte Anzeige zieht sich vom Warenkorb, über Kasse bis zu den erzeugten PDF Dateien durch.

Contao 4.4.6 - Isotope 2.4.4 (dev-develop)

**Comment by michb** [comment]
Ich bin nun auch auf dieses Problem gestoßen. Contao 4.4.8 mit Isotope 2.4.4.

**Comment by aschempp** [comment]
See #1723
