### ISSUE TITLE
[Contao 4] attribute copy wont generate database structure

### ISSUE THREAD

**Issue by rabauss** [isotope/core#1825]
in contao 4 with isotope 2.4.1 when we copy attributes the database structure is not saved. so we have to call the installer to add the database field in the tl_iso_product.

**Comment by bennyborn** [comment]
Can confirm. I guess `$GLOBALS['TL_CONFIG']['bypassCache'] = true;` in https://github.com/isotope/core/blob/master/system/modules/isotope/library/Isotope/Backend/Attribute/Callback.php#L102 is pretty much useless since Symfony handles the caching.

**Comment by aschempp** [comment]
Fixed in 0acd694efe7a1e8407c624f8e8e58893f4d12f8e
