### ISSUE TITLE
[4.4.1] Weiterleitungsfehler

### ISSUE THREAD

**Issue by henobi** [isotope/core#1826]
Seit dem Shop-Upgrade von Contao 3 auf Contao 4.4 besteht bei einem Kundenprojekt das Problem, dass nach dem Frontend-Login Weiterleitungsfehler auftreten.

Ich bin dem Problem weiter auf die Spur gegangen und habe die Ursache gefunden. In der Methode ```Isotope\Model\ProductCollection\Cart::mergeGuestCart``` liegt der Hund begraben.

Hier wird zuerst ein Cookie abgefragt:
```php
$strHash = (string) \Input::cookie(static::$strCookie);
```

Falls dieses vorhanden ist, wird im weiteren Verlauf der Warenkorb übertragen, das Cookie gelöscht und die Seite neu geladen.

```php
if ('' !== $strHash) // gekürzt
{
    // Warenkorb übertragen
    // ...
    \System::setCookie(static::$strCookie, '', time() - 3600, $GLOBALS['TL_CONFIG']['websitePath']);
    \Controller::reload();
}
```

Der Aufruf ```\Controller::reload();```erzeugt nun zwar den Reload der Seite, jedoch wird die Löschung des Cookies nicht im Response-Header an der Browser übertragen. Das hat nun zur Folge, dass die Schleife nach jedem Reload wieder ausgeführt wird, da das Cookie noch weiterhin vorhanden ist was schließlich zu dem oben beschriebenen Weiterleitungsfehler führt.

Das Problem kann gelöst werden, indem man die o.g. Zeilen durch folgendes ersetzt:
```php
$redirectResponse = new \Symfony\Component\HttpFoundation\RedirectResponse(\Environment::get('uri'));
$redirectResponse->headers->clearCookie(static::$strCookie);

throw new \Contao\CoreBundle\Exception\ResponseException($redirectResponse);
```

**Comment by fritzmg** [comment]
@henobi may be this belongs into the core-bundle after all though ;).

**Comment by aschempp** [comment]
Great job on finding the issue! It took use quite a while as well, but unfortunately this is a duplicate of https://github.com/isotope/core/issues/1817 ;)
