### ISSUE TITLE
Adressdaten werden nicht gespeichert

### ISSUE THREAD

**Issue by mecintosch** [isotope/core#1828]
Nach dem Update auf 2.4.2 habe ich ein Problem.

Bestellungen werden ganz normal durchgeführt, im Backend werden aber weder Rechnungs- noch Versandadresse gespeichert. Komischerweise wird das Land gespeichert. (gabs hier nicht eine Änderung in 2.4.2?). 

Ein weiterer Fehler der unter Umständen die selbe Ursache hat:
Bei Gast-Bestellungen werden keine Benachrichtigungen via Notification Center versendet (weder an Besteller noch an Admin). 

System-Log sagt:
Error sending status update notification for order ID 59 
No notification for order ID 59

![bildschirmfoto 2017-07-26 um 16 54 25](https://user-images.githubusercontent.com/16761621/28627829-2f6bb982-7223-11e7-975d-5538f70fe559.png)

**Comment by mecintosch** [comment]
Hab die beiden Änderungen aus https://github.com/isotope/core/issues/1811 zurück gestellt, Probleme haben sich damit wieder gelöst.

**Comment by aschempp** [comment]
Fixed in 10ba338d9cb67697419115d5619c90856857481a
