### ISSUE TITLE
Nicht verfügbares Produkt - fehlerhafte Edit-URL

### ISSUE THREAD

**Issue by paulhaem** [isotope/core#1829]
Hallo,
wenn eine Variante unveröffentlicht (Eye-Icon) und diese bereits im Warenkorb eines Kunden ist, wird anschließend angezeigt, dass dieses Produkt nicht mehr verfügbar ist und es erst aus dem Warenkorb entfernt werden muss, bevor man die Bestellung abschicken kann.

Wenn es nun beispielsweise bei einem Shirt die Farbe rot nicht mehr gibt und ich via "Edit" das Attribut der Variante ändern möchte, anstatt es aus dem Warenkorb zu löschen und nochmal zu suchen, lande ich auf der Startseite. Hinter "Edit" verbirgt sich dann folgende URL:

http://baseURL/?collection_item=25

**Comment by aschempp** [comment]
Fixed in 4138d745fe5918c288baf3c613df648013ce2bea
