### ISSUE TITLE
Sortierung in Kasse-Modul wird nicht richtig angwendet

### ISSUE THREAD

**Issue by paulhaem** [isotope/core#1836]
Hallo,
ich konnte folgendes in der Isotope Demo reproduzieren:
Sowohl das Frontend-Modul Warenkorb als auch das Frontend-Modul Kasse haben beide Sortierung: "nach Datum hinzugefügt (aufsteigend)", jedoch wird diese nur im Warenkorb berücksichtigt. Wenn man dann "Zur Kassa" geht, ändert sich die Reihenfolge der Produkte. Ich konnte bisher noch kein wirkliches Muster entdecken, nachdem sortiert wurde. In diesem Beispiel scheint es so zu sein, dass alle Produkte um eines nach "oben" verschoben wurden, sodass das 1. Produkt nun das letzte ist. Ich hatte aber auch schon andere Beispiele, bei denen es nicht so war.

**Im Warenkorb-Modul:**

![contao_isotope_imageissue4](https://user-images.githubusercontent.com/6862218/28865965-d63698f6-7771-11e7-8de8-b06a8614c99a.png)

**Im Kasse-Modul:**

![contao_isotope_imageissue5](https://user-images.githubusercontent.com/6862218/28865966-d63a2df4-7771-11e7-9c72-59791069ae6e.png)

**Comment by aschempp** [comment]
I cannot reproduce this issue. If you can find a bug, feel free to provide a pull request.
