### ISSUE TITLE
Warenkorb-Error "Uncaught ReferenceError: Isotope is not defined"

### ISSUE THREAD

**Issue by DesKaisersWein** [isotope/core#1837]
Hallo liebe Community,

seit dem letzten Update von haste auf 4.17.3, funktioniert der Button bzw. die Weiterleitung des Buttons "in den Warenkorb" nicht mehr richtig. Das Produkt wird in den Warenkorb gelegt, aber ich werde immer auf meine Startseite weitergeleitet und nicht in den Warenkorb. Alle Seiten, Artikel und Module überprüft, keine falschen Einstellungen.

Dazu bekomme ich nur die Fehlermeldung: Uncaught ReferenceError: Isotope is not defined at in der Web-Konsole.

Error-Logs, sowohl von Contao, als auch die Apache-Logs sind leer.

Dazu wird folgende Zeile der index.php auf Zeile 361 als Grund angewiesen:

> Isotope.displayBox('<div class="mod_iso_messages block" data-frontend-helper="{&quot;template&quot;:&quot;mod_iso_messag es&quot;,&quot;templatePath&quot;:
> &quot;system\/modules\/isotope\/templates\/modules\/mod_iso_messages.html5&quot;,&quot;templateURL&quo t;:&quot;contao\/main.php?do=tpl_editor&amp;key=new_tpl&amp;
> original=system%2Fmodules%2Fisotope%2Ftemplates%2F modules%2Fmod_iso_messages.html5&amp;target=templa tes&amp;rt=e54c8a87330912ad213bb5be1475a590&amp;rs fhr=1&quot;,
> &quot;templateLabel&quot;:&quot;Ein neues Template erstellen&quot;}"> <p class="iso_confirm">Das gewählte Produkt wurde in den Warenkorb gelegt.</p></div>', true);

Alles andere funktioniert. Habe auch wieder die alte haste Version (4.16.1) installiert, kein Erfolg. 
Auch ein Update von Isotope auf die 2.4.3 bringt kein Erfolg!

> Installierte Erweiterungen:
> 
> Conta 3.5.28
> 
> BackupDB	3.2.2	17	
> 
> botdetection	4.2.2	7	
> 
> 
> changelanguage	3.1.3	6	
> 
> conditionalselectmenu	3.0.3	12	
> 
> dcawizard	2.3.4	13	
> 
> dc_multilingual	2.1.7	5	
> 
> dk_mmenu	1.5.1	7	
> 
> dlstats	3.9.2	10	
> 
> easy_themes	2.2.1	18	
> 
> frontend_editor	2.3.0	3	
> 
> haste	4.16.1	1	
> 
> httprequestextended	1.1.0	8	
> 
> integrity_check	3.5.29	8	
> 
> isotope	2.4.1	14	
> 
> MultiColumnWizard	3.3.6	4	
> 
> NamespaceClassLoader	1.0.2	43	
> 
> notification_center	1.4.0	6	
> 
> om_searchkeys	1.0.3	2	
> 
> rocksolid-frontend-helper	1.2.4	9	
> 
> rocksolid-slider	1.6.2	7	
> 
> subcolumns	2.1.1	18	
> 
> superfish	3.2.0	4	
> 
> tablelookupwizard	3.2.1	14

**Comment by netzarbeiter** [comment]
Funktioniert es mit der neusten [Isotope eCommerce Version 2.4.3](https://github.com/isotope/core/issues/1837)?

**Comment by DesKaisersWein** [comment]
Nein, vergessen mit rein zu schreiben, hatte gestern auf 2.4.3 geupdatet, aber da gab es noch andere Probleme mit der Produktanzeige, deshalb Backup von vor dem Update wieder eingespielt.

Also Isotope 2.4.3 = Selber Fehler.

**Comment by DesKaisersWein** [comment]
Niemand eine Idee?

**Comment by aschempp** [comment]
Hast du Mootools aktiviert?

**Comment by DesKaisersWein** [comment]
Nein Mootools sind nicht aktiviert.

**Comment by DesKaisersWein** [comment]
Niemand eine Idee?
Bin jetzt noch von php5.6 auf php7.1 umgestiegen und habe die aktuelle Isotope-Version doch installiert, bekomme mit dieser aber Probleme mit Cookies:

> Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/contao/system/modules/core/library/Contao/Template.php:306) in system/modules/core/library/Contao/System.php on line 574
> #0 [internal function]: __error(2, 'Cannot modify h...', '/var/www/html/c...', 574, Array)
> #1 system/modules/core/library/Contao/System.php(574): setcookie('ISOTOPE_TEMP_CA...', '38fa07585db142a...', 1504962645, '/contao', '', false, false)
> #2 system/modules/isotope/library/Isotope/Model/ProductCollection/Cart.php(243): Contao\System::setCookie('ISOTOPE_TEMP_CA...', '38fa07585db142a...', 1504962645, '/contao')
> #3 system/modules/isotope/library/Isotope/Model/ProductCollection.php(173): Isotope\Model\ProductCollection\Cart->save()
> #4 [internal function]: Isotope\Model\ProductCollection->updateDatabase(false)
> #5 {main}


Diese Fehlermeldung erscheint unter Seiten, deren Inhalt Produkte enthält. Auch tritt sie erst beim 2. Aufrufen einer solchen Seite auf und deaktiviere ich alle Cookies, dann taucht diese nie auf.

System.php on line 574 : 

> setcookie($objCookie->strName, $objCookie->varValue, $objCookie->intExpires, $objCookie->strPath, $objCookie->strDomain, $objCookie->blnSecure, $objCookie->blnHttpOnly);


Template.php on line 306:

> echo $this->strBuffer;

Vielleicht könnt ihr mir ja dabei helfen :)

**Comment by aschempp** [comment]
Der Cookie-Fehler ist wohl ein Bug in der neusten Isotope-Version, da habe ich beim umstellen einen Fehler gemacht. 

Die andere Fehlermeldung ergibt für mich keinen Sinn, versuch mal alle Erweiterungen ausser die von Isotope zu deaktivieren um zu sehen ob das Problem noch auftritt.

**Comment by Wagnerwagner** [comment]
> Der Cookie-Fehler ist wohl ein Bug in der neusten Isotope-Version, da habe ich beim umstellen einen Fehler gemacht.

Den Cookie-Fehler (PHP-Warning) kann ich bestätigen. 


> | 0 [internal function]: __error(2, 'Cannot modify h...', '/kunden/519316_...', 574, Array)
> | 1 system/modules/core/library/Contao/System.php(574): setcookie('ISOTOPE_TEMP_CA...', > '4b6b11b05fc3a4a...', 1505297765, '/', '', false, false)
> | 2 system/modules/isotope/library/Isotope/Model/ProductCollection/Cart.php(254): Contao\System::setCookie('ISOTOPE_TEMP_CA...', '4b6b11b05fc3a4a...', 1505297765, '')
> | 3 system/modules/isotope/library/Isotope/Model/ProductCollection.php(173): Isotope\Model\ProductCollection\Cart->save()
> | 4 [internal function]: Isotope\Model\ProductCollection->updateDatabase(false)
> | 5 {main}

taucht auch in meiner 2.4.3 Build 4 mit Contao 3.5.21 auf jeder Seite mit Isotope-Modulen auf, sobald ich einen Artikel im Warenkorb habe.

**Comment by DesKaisersWein** [comment]
> Der Cookie-Fehler ist wohl ein Bug in der neusten Isotope-Version, da habe ich beim umstellen einen Fehler gemacht.

Alles klar, dann ist das ja kein Problem meinerseits.


> Die andere Fehlermeldung ergibt für mich keinen Sinn, versuch mal alle Erweiterungen ausser die von Isotope zu deaktivieren um zu sehen ob das Problem noch auftritt.

Bereits ausprobiert, leider kein Erfolg...

**Comment by DesKaisersWein** [comment]
Hat wirklich keiner mehr eine Idee? Weil so kann ich den Shop nicht online gehen lassen

**Comment by Wagnerwagner** [comment]
Bezüglich der PHP-Warning, also dem oben beschriebenen "Cookie-Fehler":
Ich habe jetzt diesbezüglich keine funktionalen Probleme feststellen können. Die Warning bekommst du im Frontend weg, in dem du in den Contao-Einstellungen im Bereich "Sicherheitseinstellungen" den Haken bei  "Fehlermeldungen anzeigen" rausnimmst. Wenn "Fehlermeldungen protokollieren" aktiviert ist, landen die Warnings dann eben nur in "system/logs/error.log".

**Comment by aschempp** [comment]
Das Cookie-Problem ist in d5e523fd6b6012aa057587d6f843416d24c00c6a behoben.

**Comment by DesKaisersWein** [comment]
Sehr schön, schön dass ich helfen konnte.

Aber das andere Problem ist leider essentiell, hat wirklich niemand mehr eine Ahnung o.ä. 
Zustand ist derselbe, keine Fehlermeldung in den Logs, nur die Live-Konsole bringt die Meldung ...
