### ISSUE TITLE
fineuploader: Pflichtfeld error

### ISSUE THREAD

**Issue by paulhaem** [isotope/core#1839]
Hallo,
beim fineuploader-Attribut wird die Pflichtfeld-Option für das Frontend nicht richtig berücksichtigt. In beiden Fällen wurde kein Bild zum Upload ausgewählt:

Wenn Pflichtfeld **aktiv** ist, wird das Produkt zwar nicht zum Warenkorb hinzugefügt, jedoch wird die Seite durch submit neu geladen und keinerlei Feedback wird zurückgegeben, nicht so wie bei den anderen Feldern (Select, Textfeld), bei denen man das Produkt erst gar nicht in den Warenkorb legen darf, wenn diese nicht befüllt wurden.

Wenn Pflichtfeld **nicht aktiv** ist, wird folgende Fehlermeldung auf der Produktdetails-Seite ausgegeben:
`[internal function]: __error(2, 'md5_file(C:\\xam...', 'C:\\xampp\\htdoc...', 119, Array)`

Sobald ich ein Bild zum Upload auswähle, funktioniert letzteres.

**Comment by aschempp** [comment]
@qzminski apparently there are issues with the fineuploader widget. If the field is mandatory and not filled-in, there is no warning message. If it's not mandatory, the widget tries to process the value and fails if there is no file uploaded.

**Comment by qzminski** [comment]
That should be fixed in #1866. I cannot reproduce the no warning message problem however, when the field is mandatory and I try to add the product to a cart I simply get `Field "attribute_name" must not be empty!`.

**Comment by paulhaem** [comment]
@qzminski you are right. I can't reproduce the missing error message in another installation. I thought this issues sticked together. My bad, sorry. Thanks for the fix.

**Comment by aschempp** [comment]
Closed in favor of #1866
