### ISSUE TITLE
Insert-Tags werden in Dateiname (Dokument) nicht ausgegeben

### ISSUE THREAD

**Issue by paulhaem** [isotope/core#1841]
Folgender Insert-Tag führt zur leeren Ausgabe beim Dateiname:
`{{formatted_datetime::##collection_locked##::datim}}`

`##collection_locked##` gibt ohne Probleme den Timestamp beim Dateinamen aus.

Contao: 3.5.28
Isotope: 2.4.3

**Comment by Toflar** [comment]
Das ist ein InsertTag von Haste. Hast du die neuste Version?

**Comment by paulhaem** [comment]
Ja, `codefog/contao-haste` 4.17.3 ist installiert.

**Comment by aschempp** [comment]
Verwendest du das im Frontend oder Backend? Und wird der InsertTag ersetzt (ist leer) oder bleibt er einfach stehen?

**Comment by paulhaem** [comment]
Wird im Backend beim Dateiname von Dokumenten verwendet. Der InsertTag wird ersetzt.

`Bestellung_{{formatted_datetime::##collection_locked##::datim}}` ergibt `Bestellung_.pdf`.

Verwende nun mittlerweile die Unique-ID. Wäre denk ich aber sicherlich praktisch, als benutzerfreundliche ID, formatierte Timestamps in Dateinamen zu verwenden.

**Comment by aschempp** [comment]
Insert tags were actually not supported yet. Changed in b91a68d5dcf1d21fc4d6d9f55439562c6cc6a9ff
