### ISSUE TITLE
getOwnerAddress() erzeugt für optionalen Namen Leerzeile

### ISSUE THREAD

**Issue by paulhaem** [isotope/core#1845]
Hallo,
beim Dokumententemplate wird bei der Generierung der Shop-Adresse eine Leerzeile zwischen Firmenname und Adresse gesetzt, obwohl Vorname und Nachname optional sind. Wird zusätzlich der Firmenname weggelassen (ebenfalls optional), rutscht die Adresse nach oben, ebenso wenn nur Vor- / Nachname und kein Firmenname verwendet wird.

`$this->config->getOwnerAddress()->generate($config)`

```
Firmenname

Straße + Nr
PLZ + Ort
Land
```

**Comment by aschempp** [comment]
Should be fixed in a7963b507ff2058d62728ad940b008ee52444f2d
