### ISSUE TITLE
Varianten Select-Feld: Error-Feld bei 3+ Feldern

### ISSUE THREAD

**Issue by paulhaem** [isotope/core#1846]
Hallo,
folgendes Szenario:

Ein Produkt mit mehreren Varianten. Dieses Produkt hat 3 Select-Felder, die nacheinander ausgefüllt werden. Wenn das erste Feld ausgewählt wurde, erscheint beim 3. Feld ein Error-Feld ( `<p class="error">` ), welches sagt, dass dieses ausgefüllt werden muss.

Derselbe Effekt tritt bei allen Produkten auf, die drei oder mehr Select-Felder haben. Die Fehlermeldung erscheint dann jeweils beim übernächsten Feld. Also: 1. Feld ausgewählt, 3. Error, 2. Feld ausgewählt, 4. Error.

![contao_isotope_selectissue1](https://user-images.githubusercontent.com/6862218/29509148-89227c34-8657-11e7-9a5d-0c1c8e82c10c.png)

Bei einem normalen Auswahlvorgang, sollte der Benutzer nicht bereits mit Fehlermeldungen belästigt werden. Erst, wenn er versucht das Produkt ohne ausgewähltes Feld in den Warenkorb hinzuzufügen, was bereits mittels `required` verhindert werden kann.

**Comment by aschempp** [comment]
Closed in favor of #1966
