### ISSUE TITLE
Checkout - Summary on "review"

### ISSUE THREAD

**Issue by pet21221** [isotope/core#1847]
Is there a way to see the price summary with shipping costs on the last checkout process page (review) like on the cart?

- Subtotal
- Coupons
- Tax
- Shipping Cost
- Total

**Comment by aschempp** [comment]
You mean to see the shipping price in the cart? There's a shipping price calculation module for that.

**Comment by pet21221** [comment]
I mean to have a option to see the summary of all costs on the last process page (review). Like the summary on the cart, but with the shipping cost.

You can see an example (See screen). There is an section with "Your order". This is on the last process page before ordering. On the "review"-Page. The customer can see all the costs again and with the Shipping cost as summary, before ordering. 

![bildschirmfoto 2017-08-21 um 12 36 58](https://user-images.githubusercontent.com/11228500/29515677-a6deb0ce-866d-11e7-9b99-b083262d8765.png)

**Comment by pet21221** [comment]
I'am looking for like this on cart-module, but with Shipping Cost for my the last checkout-process page (review).

![screenshot-shop contao projects goekmen de-2017-08-21-12-41-52](https://user-images.githubusercontent.com/11228500/29515941-c18fcc40-866e-11e7-8d75-4f4e58bb0047.png)

**Comment by pet21221** [comment]
It also affects "Bestellungsdetails". I can the the products and the product price, but not the summary of all the costs. I can't see the summary with shipping cost and the coupons.

**Comment by aschempp** [comment]
Then you must have modified a template, because that. is the default setup…

**Comment by pet21221** [comment]
I modified already the cart template for get only the summary of costs. But the shipping cost is there 
non-existent...

**Comment by aschempp** [comment]
The shipping cost is not shown if it's zero. Otherwise it sure is shown, try the original templates please.

**Comment by pet21221** [comment]
Okay, that's was it. In the original templates the shipping cost will be added on the checkout process. Thank you.
