### ISSUE TITLE
Bug, Produktvarianten verlieren Standard Status wenn eine Schwestervariante gespeichert wird

### ISSUE THREAD

**Issue by Wagnerwagner** [isotope/core#1849]
Setzt man in einer Variante das Standard-Attribute und bearbeitet im anschluss eine andere Variante dieses Artikels verliert die als Standard definierte Variante diesen Status, unabhängig davon ob die entsprechende Checkbox in der zu speichernden Variante ausgewählt wurde oder nicht. Das Verhalten tritt in der Isotope Version 2.4.3 auf (Installation sowohl über Composer als auch über ER2)

**Comment by aschempp** [comment]
Was meinst du mit *Standard-Attribute* ?

**Comment by Wagnerwagner** [comment]
![standard-checkbox](https://user-images.githubusercontent.com/7679272/30052754-dac56b02-9226-11e7-8ac3-5af4fd7807db.JPG)

bzw. die Stern-Markierung

![standard-stern](https://user-images.githubusercontent.com/7679272/30052753-dac56594-9226-11e7-8131-4e574f2d2779.JPG)

**Comment by aschempp** [comment]
Fixed in 5d26015095b3a0f3c06d3f191287180c51444bbc
