### ISSUE TITLE
Mehrsprachiges Produkt bearbeiten: Sprachwähler nicht bedienbar

### ISSUE THREAD

**Issue by virtualize** [isotope/core#1850]
Contao: 3.5.28
Isotope: 2.4.3
PHP: 7.0.21

Bearbeitet man ein mehrsprachiges Produkt so lässt sich der Sprachwähler oben links nicht mehr bedienen, sobald oben rechts das Select Feld der Versionierung angezeigt wird. Anscheinend wird der Sprachwähler vom Versionierungsfeld überlagert, so dass dieser nicht mehr klickbar ist.

In Isotope 2.4.1 funktionierte es noch. Dieser Commit https://github.com/isotope/core/commit/37a599967b162c82bd0d18485f7e8773b8db4feb scheint der Grund für die Regression zu sein.

Bin dankbar für jeden Workaround.

**Comment by paulhaem** [comment]
Ich habe als Hotfix in `system\modules\isotope\assets\css\backend.css` folgendes ergänzt:

```
.tl_version_panel .tl_formbody {
    position: inherit;
}
```

Das überschreibt `position: relative;` und sorgt dafür, dass das Select-Feld für die Sprachauswahl wieder anklickbar ist.

**Comment by virtualize** [comment]
@paulhaem Hab Dank
@aschempp wann könnten wir mit einem Bugfix Release rechnen?

**Comment by aschempp** [comment]
Fixed in 2146acc7ac4b5a74ac8553a8d03e95c7c526c7c5
