### ISSUE TITLE
E-Mail Adresse nur, wenn nicht eingeloggt

### ISSUE THREAD

**Issue by pet21221** [isotope/core#1854]
Gibt es ein Feature, welche die E-Mail Adresse im Bestellprozess nur abfragt, wenn der User nicht eingeloggt ist? Bei eingeloggten Usern soll er automatisch die Mail Adresse des User's nehmen.

**Comment by aschempp** [comment]
Bitte wende dich an's Community Forum für Support: https://community.contao.org
