### ISSUE TITLE
Produktfilter: Suchkritieren fehlerhaft

### ISSUE THREAD

**Issue by paulhaem** [isotope/core#1858]
Hallo,
die Suche des Produktfilters behandelt Produkte anders als die Varianten. Bei der Suche kann sowohl mit dem Namen als auch mit der Artikelnummer nach dem Produkt gesucht werden. Bei den Varianten wird hingegen nur die Artikelnummer beachtet. Wird versucht nach dem Namen zu suchen, werden keine Ergebnisse geliefert.

**Comment by aschempp** [comment]
Vermutlich haben deine Produkte keinen Namen, sondern Erben diesen lediglich vom Hauptprodukt? Das ist leider aktuell nicht anders möglich, ich gehe davon aus dass sich das in der Zwischenzeit auch erledigt hat…
