### ISSUE TITLE
Ähnliche Produkte: Produkt ohne Kategorie nicht sichtbar

### ISSUE THREAD

**Issue by paulhaem** [isotope/core#1859]
Hallo,
ein öffentliches Produkt, dass als ähnliches Produkt bei einem anderen Produkt referenziert wurde, ist nicht sichtbar, wenn es keiner Kategorie / Seite angehört. Ist es verpflichtend, dass jedes Produkt auch auf einer Seite gelistet werden muss? Wäre super, wenn z.B. Zubehör nur bei einem Produkt aufscheinen und nicht separat in einer Zubehör-Liste aufgeführt werden müssen.

**Comment by aschempp** [comment]
Das Produkt muss einer Seite zugewiesen sein. Hintergrund ist dass du mit einer Contao Installation mehrere Shops mit verschiedenen Seitenbäumen machen kannst, und dann weiss Isotope nicht welches Produkt in deinem Shop überhaupt vorkommen.
