### ISSUE TITLE
Contao 4.4.3, isotope 2.4.3, Buchung erzeugt doppelte Adressbuch Einträge

### ISSUE THREAD

**Issue by Ainschy** [isotope/core#1862]
Neuen Bestellungen erzeugen jedes mal einen neuen Eintrag im Adressbuch des Kunden, auch wenn die Adresse im Adressbuchbereits vorhanden ist.

Getestet mit der Einstellung Rechnungsanschrift = Versandtanschrift

**Comment by aschempp** [comment]
I cannot reproduce this, I don't get additional addresses if I select a current one.

**Comment by Ainschy** [comment]
Ich habe Rechnungsanschrift als Versandanschrift verwenden gewählt, keine existierende Versandanschrift!

**Comment by proplab** [comment]
Das passiert, wenn im Modul "Kasse" die Checkbox "Zum Adressbuch hinzufügen" markiert wird. Jede Adresse, auch wenn sie aus dem Adressbuch oder aus der Rechnungsadresse kommt, wird als neu betrachtet und automatisch zum Adressbuch hinzugefügt. Ich musste das jetzt abschalten, weil die Adressbücher vollliefen. Eigene Adressen müssen jetzt explizit im Adressbuch angelegt werden, um gespeichert zu werden.
Besser wäre vielleicht noch eine zusätzliche Checkbox im Frontend: "Abweichende Versandadresse zum Adressbuch hinzufügen".

**Comment by paulhaem** [comment]
Fehler kann ich bestätigen für folgendes Setup:
- Contao: 3.5.34
- Isotope: 2.4.5

Adressbuch läuft momentan voll.

**Comment by aschempp** [comment]
Closed due to inactivity. Feel free to reopen if it still exists.

**Comment by sgei** [comment]
Hallo,

the bug is still there, see https://github.com/isotope/core/issues/1987

Steffen
