### ISSUE TITLE
Isotope Dateiverwaltung Upload Button weg

### ISSUE THREAD

**Issue by ManuelaMe** [isotope/core#1865]
Ich habe ein Problem mit Isotope das jetzt auf drei unterschiedlichen Webseiten aufgetaucht ist.

Wenn ich bei einem Produkt ein Bild hinzufügen will, funktioniert das ganze genau einmal. Verlasse ich das Produkt und gehe in ein zweites ist der Uploadbutton weg. Der bleibt auch verschwunden wenn ich in das Ursprünglich bearbeitete Produkt gehe. (Siehe Bilder)

Button da:
![image](https://user-images.githubusercontent.com/24274084/30271333-36df6d70-96f0-11e7-8372-a92be9c2b56e.png)

Button weg:
![image](https://user-images.githubusercontent.com/24274084/30271382-564ad80c-96f0-11e7-903a-af1a578587bf.png)

Das Problem besteht bei drei verschiedenen Contao Webseiten. Zwei davon laufen mit Contao 3.5.21 und Isotope  2.4.3 Build 5, die andere Installation läuft mit Contao 3.5.25 und Isotope 2.4.3.9004. Zwei Contaosysteme werden mit Composer genutzt eins mit der Erweiterungsverwaltung.

Manchmal taucht der Button nach einer "Nacht" wieder auf verschwindet aber nach einem Upload direkt wieder. Ich befürchte fast. das es ein Cache-Problem ist, konnte aber mit den üblichen Mitteln keine Besserung feststellen.

**Comment by netzarbeiter** [comment]
In einer Installation mit Contao 3.5.28 und Isotope eCommerce 2.4.4 (ER) funktioniert der mehrmalige Upload problemlos. Funktioniert es nach der Aktualisierung auf 2.4.4?

**Comment by ManuelaMe** [comment]
Update auf 2.4.4 hat nichts gebracht der Uploadbutton ist immer noch weg. Ich zieh das entsprechende Contao mal hoch auf 3.5.28 und schau dann nochmal nach.

**Comment by ManuelaMe** [comment]
Leider auch nach Update auf 3.5.28 immer noch weg.
Nach dem Einschalten des Punktes Interner Cache umgehen und DebugModus (hatte mich intressiert ob der überhaupt die richtigen Tabellen anwählt) ist der Button da und es sieht auch vernünftig aus im Gegensatz zu vorher.

![image](https://user-images.githubusercontent.com/24274084/30273119-e64ef710-96f7-11e7-843b-91b5321f6e9f.png)

Mach ich beides wieder aus ist der Button wieder weg. Lässt das auf ein Problem mit unserem Server schließen? Da wurde vor kurzem was durch den Serveradmin geändert.

**Comment by ManuelaMe** [comment]
Leider bin ich bei dem Problem mit dem fehlenden Button noch nicht weiter. Hat vll. einer einen Hinweiß woran das liegen könnte?

**Comment by aschempp** [comment]
Erhältst du auf der Browser-Konsole eine Fehlermeldung? Kannst du herausfinden ob der Button nur nicht sichtbar ist (mit dem Browser-Inspektor) oder tatsächlich nicht im DOM?

**Comment by ManuelaMe** [comment]
Das Problem hat sich inzwischen gelöst. 
Mein Kollege hatte auf dem Server das Pagespeed-Modul aktiviert, dass hat erstmal alle Javascripte im Backend von Contao vom laden abgehalten. Da ich davon nichts wusste hab ich darauf nicht sofort geachtet.
Im DOM war der Button immer sichtbar, nur ohne die passenden Javascripte nicht mehr sichtbar.
