### ISSUE TITLE
Warenkorb mit 0 Euro

### ISSUE THREAD

**Issue by dreibein** [isotope/core#1867]
Im Shop gibt es Produkte, die 0 Euro kosten und auch Gutscheine, die 100% Rabatt geben.
In beiden Fällen tritt folgender Fehler auf.
Der Benutzer hat noch Produkte im Warenkorb, die etwas kosten und der 100%-Gutschein nicht verrechnet wird. Nun werden diese Produkte entfernt und nur noch die kostenlosen Produkte sind vorhanden.So hat der Warenkorb einen Wert von 0,00€.
Möchte der Benutzer nun die Bestellung ausführen, kommt es zu einem Fehler.
Anstatt die Bestellung einfach durchzuführen, wird versucht, auf die Seite des Zahlungsanbieters (PayPal oder Sofortüberweisung) weiterzuleiten. Beide Fälle funktionieren nicht.
Wenn man Sofortüberweisung ausgewählt hat, sieht man den Betrag, der zu überweisen wäre. Dieser beträgt genau so viel, wie die nicht kostenlosen Produkte ausgemacht haben, die vorher noch im Warenkorb waren.
Daraus schlussfolgern wir, dass isotope bei einem Warenkorbwert von 0 Euro, versucht die Produkte aus dem alten Warenkorb zu verwenden.
Durch das Löschen aller Einträge in der  '_tl_iso_product_collection_' die im Feld '_type_' den Wert '**cart**' haben, konnte dies temporär behoben werden.
Wenn man nun ein kostenloses Produkt in Warenkorb legt und die Bestellung abschließt, funktioniert alles einwandfrei.
Allerdings handelt es sich dabei nur um eine temporäre Lösung.

Contao-Version: 3.5.28
Isotope-Version: 2.4.4

**Comment by aschempp** [comment]
Das hört sich äusserst unlogisch an. Isotope merkt sich keinen "vorherigen" Warenkorb, wenn die Produkte mit Preis entfernt sind, dann sind sie auch in der Datenbank weg. Was passiert denn ohne Gutschein?

**Comment by dreibein** [comment]
Solange der Warenkorb einen Wert über 0,00 Euro hat, dann wird der aktuelle Warenkorb verwendet und der Checkout funktioniert.
Sobald aber der Gutschein verwendet wird und nur Artikel vorhanden sind, bei denen der Gutschein greift, oder die allgemein nichts kosten und der Warenkorbwert somit auf 0 fällt, dann werden die Artikel, die vorher noch im Warenkorb waren, mitberücksichtigt.

**Comment by aschempp** [comment]
kannst du mir zwei Screenshots von deinen Warenkörben machen?

**Comment by dreibein** [comment]
Warenkorb 1:
Ein Produkt mit einem Preis über 0€
![warenkorb1](https://user-images.githubusercontent.com/26867434/32041839-ed00ab88-ba35-11e7-9c9e-a0e9e2d9fdc3.png)

Man macht den Checkout bis zu dem Punkt, wo man die Bestellung abschließen lönnte. Hier hört man aber auf.
![checkout1](https://user-images.githubusercontent.com/26867434/32041902-282e89be-ba36-11e7-87b7-e7cf1e5f719d.png)


Warenkorb 2:
Es wird ein Produkt mit 0€ hinzugefügt und das erste Produkt wird entfernt.
![warenkorb2](https://user-images.githubusercontent.com/26867434/32041875-09f88292-ba36-11e7-952a-a577935566ea.png)
![warenkorb3](https://user-images.githubusercontent.com/26867434/32041877-0bafda72-ba36-11e7-8997-52d9e01e2cf4.png)

Nun geht man wieder den Bestellprozess durch und schließt diesen komplett ab. Daraufhin wird man weiter zum Zahlungsanbieter weiter geleitet. In diesem Fall ist es Sofortüberweisung, da man diesen beim ersten Durchgang des Bestellprozesses ausgewählt hat und man keine Chance hat, die Zahlungsart wieder zu ändern, solange man die Bestellung nicht abgeschlossen hat.
![checkout2](https://user-images.githubusercontent.com/26867434/32042369-8d9a4774-ba37-11e7-8e73-843ef44169e0.png)

Doch nach der Weiterleitung erhält man nur eine Fehlermeldung.
![error_sofortueberweisung](https://user-images.githubusercontent.com/26867434/32042389-995cf890-ba37-11e7-8cd8-072d60a7fc84.png)

**Comment by aschempp** [comment]
Habt ihr diesbezüglich eine Lösung gefunden?
