### ISSUE TITLE
Download product - Link to download in notification

### ISSUE THREAD

**Issue by xApep** [isotope/core#1870]
Hi.
Is it possible to download product or generate URL to download product directly from email. When you change status to "completed" and order is paid, the customer get's notification email where download link are included so that he does not need to login to FE.

Thanks.

**Comment by aschempp** [comment]
You can link the customer to a page that shows his order details, without needing him to log in. From there on he can download the products. I'm not sure out of my head whether you can create direct download links, but it should be possible with some template hacking.

Also, please contact the community forum (https://community.contao.org) with questions, this is the bug and feature tracker for Isotope eCommerce 😉 .
