### ISSUE TITLE
[2.4.4] Warenkorb zeigt keine Optionen an

### ISSUE THREAD

**Issue by wschwaiger** [isotope/core#1871]
Das Problem gab es schon mal in V2.0. Leider scheint es wieder so zu sein, dass keine Optionen im Modul Warenkorb geladen werden.

Die Option ist als Attribute - Textfeld angelegt und unter Produktoptionen-Einstellungen gruppiert. Unter den Produkteinstellungen ist es unter Attribute zu finden.

Ich habe schon versucht das Attribut unter Varianten-Attribute zu verschieben. Ohne Erfolg. Die Ausgabe im Template gibt immer NULL. ['options'], ['configuration'], etc. funktioniert im Warenkorb-Template alles nicht.

Im Anhang ein paar Screenshots und die Template-Datei für den Warenkorb.

Danke,
W
![screencapture-skischule-edelweiss-contao-main-php-1507114430681](https://user-images.githubusercontent.com/458603/31172301-50273144-a903-11e7-8dbd-9fc3f808f672.png)
![screencapture-skischule-edelweiss-contao-main-php-1507114447348](https://user-images.githubusercontent.com/458603/31172302-503e9348-a903-11e7-9a6c-e73ff6fcf70b.png)
[iso_collection_cart.txt](https://github.com/isotope/core/files/1355505/iso_collection_cart.txt)

**Comment by aschempp** [comment]
Ich verstehe leider nicht, was meist du mit "Optionen im Warenkorb laden"?

**Comment by wschwaiger** [comment]
Ah, sorry. Da war ich wohl nicht präzise genug. Im Warenkorb wird Kursdauer und # Stunden angezeigt. Aber das Attribut erster Kurstag nicht.

**Comment by wschwaiger** [comment]
Ich habe nun das Attribut neu angelegt und neu zugewiesen. Nun klappt alles.
