### ISSUE TITLE
Call to undefined method Haste\Util\Url::removeQueryStringCallback()

### ISSUE THREAD

**Issue by xApep** [isotope/core#1873]
Hi.
I'm using Contao 3.5.29 and Isotope 2.4.4 build 3.

When I'm trying to use cumulative filter I get the following error.

`Fatal error: Call to undefined method Haste\Util\Url::removeQueryStringCallback() in C:\wamp\www\project\system\modules\isotope\library\Isotope\Module\CumulativeFilter.php on line 286`

**Comment by xApep** [comment]
You may close it.

It was a "bug" in haste, latest version is working fine.

**Comment by Toflar** [comment]
It was not a bug, you just installed an incompatible version :)

**Comment by xApep** [comment]
Well it's more Extension Manager fault, he installed dependency so I would suggest that isotope has new haste version as dependency :)

**Comment by Toflar** [comment]
That's the case already. The ER2 is unable to resolve dependencies properly. That's why ER2 is dead and Composer and Contao 4 the future :)

**Comment by xApep** [comment]
Yeah...tell that to Windows (composer) :)

**Comment by Toflar** [comment]
Composer works just fine on Windows. Anyway, unrelated.
