### ISSUE TITLE
PayPal Plus - Status für neue Bestellungen -> document_number ist ohne Inhalt

### ISSUE THREAD

**Issue by Ainschy** [isotope/core#1876]
In der Zahlungsart PayPal Plus wird bei erfolgreicher Bezahlung ein Status gesetzt. Diesem Status enthält  ein Benachrichtigung inkl. generiertem PDF mit den Auftrag zur Fertigung. 
Zu diesem Zeitpunkt ist aber noch keine document-number verfügbar. 

**Das Simple-Token documebt-number bleibt leer und der Verweis auf die Bestellung fehlt.**

Die im Kassen Modul hinterlegte Benachrichtigung wird ebenfalls ausgelöst und enthält die document-number, diese Benachrichtigung geht an den Kunden.

Auf Grund der Zahlungart Vorkasse können nicht alle Bestellungen auch einen Auftrag für die Fertigung auslösen, das sollen nur die PayPal Plus Zahlungen auslösen.

**Comment by aschempp** [comment]
Die Benachrichtigung im Bestellstatus kann dafür nicht verwendet werden. Das lässt sich aber einfach mit einer entsprechenden if-condition in der Notification lösen.
