### ISSUE TITLE
ajaxBox still opens after Include messaging enabled

### ISSUE THREAD

**Issue by xApep** [isotope/core#1878]
Hi.
When you enable "Include messaging" in checkout the iso_ajaxBox is still showing.

Contao 3.5.29, Isotope 2.4.4

**Comment by xApep** [comment]
Also I have figure out that if you have login in checkout (address) and when you 
1. login (on checkout -> address)
2. refresh checkout page
3. CartMarged message is showen

If you close it, refresh page or go to next step this CartMerged message is always showen but when you visit shopping cart this message is also there (why?) but when you close it, refresh page the message is not showen - not on shopping cart and also on checkout.

Take a look at my cartMerged message and why this is not so good approach (that is always shown until you visit shopping cart) and also when you visit shopping cart you get duplicate message for cartMerged
[Racun_st._2017-00042.pdf](https://github.com/isotope/core/files/1394849/Racun_st._2017-00042.pdf)
.

**Comment by xApep** [comment]
Also I have figure out that if you have login in checkout (address) and when you

    login (on checkout -> address)
    refresh checkout page
    CartMarged message is showen

If you close it, refresh page or go to next step this CartMerged message is always showen but when you visit shopping cart this message is also there (why?) but when you close it, refresh page the message is not showen - not on shopping cart and also on checkout.

Take a look at my cartMerged message and why this is not so good approach (that is always shown until you visit shopping cart) and also when you visit shopping cart you get duplicate message for cartMerged.
![cartemerged](https://user-images.githubusercontent.com/1315340/31722756-368e9afe-b41d-11e7-931c-72515242aee0.JPG)

**Comment by xApep** [comment]
Any news about this bug fix?

thanks.

**Comment by aschempp** [comment]
Unfortunately I'm unable to reproduce this, it seems to happen "randomly". It would be best if you can get a developer to analyze your system and figure out why this happens.
