### ISSUE TITLE
Error when trying to use Payone 

### ISSUE THREAD

**Issue by fabianperrey** [isotope/core#1879]
https://github.com/fabianperrey/core/commit/a93ca0e26f23a4eebfcde20759cf35acac7f812d

**Comment by aschempp** [comment]
I'm pretty sure the rounding should happen in the PayOne payment method?
https://github.com/isotope/core/blob/master/system/modules/isotope/library/Isotope/Model/Payment/Payone.php#L114

**Comment by fabianperrey** [comment]
Well in other cases it happens in the ProductCollection. For Example:
https://github.com/fabianperrey/core/blob/a93ca0e26f23a4eebfcde20759cf35acac7f812d/system/modules/isotope/library/Isotope/Model/ProductCollection.php#L798

But I guess it works either way
