### ISSUE TITLE
Mini-Warenkorb behält gelöschte Ware im Cache

### ISSUE THREAD

**Issue by doescher** [isotope/core#1882]
Hallo,
dies ist meine erste Fehlermeldung hier und ich hoffe, ich kann das Problem gut umschreiben.

Ich verwende Contao 3.5.30 und Isotope 2.4.4. und verwende nur den Servercache.
Wenn ich nun auf meiner Site ein Produkt in den Warenkorb lege, dann kommt es vor, das mir auf Unterseiten im Miniwarenkorb noch immer 0 als Anzahl der Produkte im Korb angezeigt wird. Genauso, wenn ich das Produkt aus dem Warenkorb lösche, hier wir auf manchen Seien noch eine 1 im Miniwarenkorb angezeigt.
Ich habe den Miniwarenkorb mit einem Modul "eigene html" eingebaut und per Inserttag {{cart::quantity}} die Anzahl der Produkte anzeigen lassen. Nun wurde mit der Tipp gegeben, hinter quantity ein |uncached zu schreiben, um das cachen der Anzahl der Produkte zu verhindern.
Dadurch kommt es aber zu folgender Fehlermeldung:
`Recoverable error: Argument 1 passed to Isotope\InsertTag::getValueForCollectionTag() must implement interface Isotope\Interfaces\IsotopeProductCollection, null given, called in /www/htdocs/w0xxxx/xxxx.de/composer/vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/InsertTag.php on line 38 and defined in composer/vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/InsertTag.php on line 73
#0 composer/vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/InsertTag.php(73): __error(4096, 'Argument 1 pass...', '/www/htdocs/w01...', 73, Array)
#1 composer/vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/InsertTag.php(38): Isotope\InsertTag->getValueForCollectionTag(NULL, Array)
#2 composer/vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/Frontend.php(284): Isotope\InsertTag->replace('cart::quantity')
#3 system/modules/core/library/Contao/InsertTags.php(1129): Isotope\Frontend->replaceIsotopeTags('cart::quantity', false, '', Array, Array, Array, 3, 16)
#4 system/modules/core/library/Contao/Controller.php(692): Contao\InsertTags->replace('...', false)
#5 system/modules/core/controllers/FrontendIndex.php(477): Contao\Controller::replaceInsertTags('...', false)
#6 system/modules/core/controllers/FrontendIndex.php(28): Contao\FrontendIndex->outputFromCache()
#7 index.php(19): Contao\FrontendIndex->__construct()
#8 {main}

Fatal error: Call to a member function sumItemsQuantity() on null in /www/htdocs/w0xxxx/xxxxde/composer/vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/InsertTag.php on line 80`

Da ich mit der Fehlermeldung nichts anfangen kann wurde mir nun ans Herz gelegt, diesen Fehler zu melden, was ich hiermit mache.

Vielleicht hat hier ja jemand eine Lösung.

Danke und Grüße,
doescher

**Comment by aschempp** [comment]
Seite mit einem Warenkorb-Modul können per Definition nicht gecacht werden, da sich die Seiten ja abhängig von der Benutzerinteraktion ändern. Normalerweise verhindert das Isotope auch automatisch, bei dir funktioniert dies wohl nicht weil du den InsertTag verwendest. Du musst die entsprechenden Seiten vom Cache ausschliessen.
