### ISSUE TITLE
Product type "class" isn't shown in FE

### ISSUE THREAD

**Issue by xApep** [isotope/core#1884]
Hi.
In product type there is a field where you can type CSS class which should be shown on product list and reader but unfortunately is not.

Contao 3.5.29, Isotope 2.4.4

**Comment by aschempp** [comment]
I fixed the CSS ID in product reader in ecc0ab93e8f60b71f8f1b15b27c85153da57fb2e. Everything else works fine for me, please make sure it's not a template modification error.
