### ISSUE TITLE
InsertTags don't work everywhere

### ISSUE THREAD

**Issue by ghost** [isotope/core#1889]
I had to discover that Isotope InsertTags don't work everywhere. One place where they don't work is a totally separate extension which provides products as map markers to Con4Gis. To link markers in the map to product details, I try to use `{{product::alias::[id]}}`, the ID is replaced by the extension automatically. But the InsertTag returns false all the time, because:

1. It is passed to Isotopes deprecated `Frontend::replaceInsertTags()` method (somebody probably should update the config.php to use the new method…)
2. This redirects to `InsertTag::replace()`
3. Let's ask the model for this product in `InsertTag::findCurrentProduct()`
4. The product model actually finds this in `Product::findAvailableByPk()` (super!)
5. Here the fun starts. Let's ask the product whether it's available in `AbstractProduct::isAvailableInFrontend()`
6. This methods tries to get a cart. But there is no cart at this point. Booh!

I think, InsertTags should be available in a global fashion (it is a global hook anyway), so checking for a cart at this point seems odd. Is it possible to bypass this check in a future version?

**Comment by aschempp** [comment]
Are you executing the insert tag in the frontend?
Please be aware that Isotope verifies if the product does exist on the website, otherwise it is not shown.

**Comment by thjapan** [comment]
Inserttags ohne Funktion in Isotope 2.5.1, Contao 4.4.18.  
Habe in einem Template folgenden Inserttag:  
`<span>{{cart::quantity}} Artikel</span>`  
  
In einer älteren Installation funktioniert es.  
Isotope 2.5@dev unter Contao 4.4.8  
  
Braucht ihr weitere Infos?
