### ISSUE TITLE
Product image: Warning: failed to open stream

### ISSUE THREAD

**Issue by GMTeams** [isotope/core#1890]
Contao 3.5.30
isotope/isotope-core 2.4.4
codefog/contao-haste	4.17.6

Sometimes (not always, but I couldn't figure out some pattern) I get this warning message when I'm adding product images:

> Warning: imagejpeg(/kunden/12345/mywebsite/assets/images/y/image-92997352.jpg): failed to open stream: No such file or directory in composer/vendor/codefog/contao-haste/library/Haste/Image/Image.php on line 189

`#0 [internal function]: __error(2, 'imagejpeg(/kund...', '/kunden/12345...', 189, Array)
#1 composer/vendor/codefog/contao-haste/library/Haste/Image/Image.php(189): imagejpeg(Resource id #297, '/kunden/12345...', 80)
#2 composer/vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/Model/Gallery/Standard.php(372): Haste\Image\Image::addWatermark('isotope/k/image...', 'files/mywebsite/as...', 'right_bottom')
#3 composer/vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/Model/Gallery/Standard.php(290): Isotope\Model\Gallery\Standard->getImageForType('lightbox', Array, true)
#4 composer/vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/Model/Gallery/Standard.php(233): Isotope\Model\Gallery\Standard->addImageToTemplate(Object(Isotope\Template), 'gallery', Array, true)
#5 system/modules/isotope/templates/isotope/iso_reader_default.html5(17): Isotope\Model\Gallery\Standard->generateGallery()
#6 system/modules/core/library/Contao/BaseTemplate.php(88): include('/kunden/12345...')
#7 system/modules/core/library/Contao/Template.php(277): Contao\BaseTemplate->parse()
#8 system/modules/core/classes/FrontendTemplate.php(46): Contao\Template->parse()
#9 composer/vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/Model/Product/Standard.php(549): Contao\FrontendTemplate->parse()
#10 composer/vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/Module/ProductReader.php(105): Isotope\Model\Product\Standard->generate(Array)
#11 system/modules/core/modules/Module.php(287): Isotope\Module\ProductReader->compile()
#12 composer/vendor/codefog/contao-haste/library/Haste/Frontend/AbstractFrontendModule.php(52): Contao\Module->generate()
#13 composer/vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/Module/Module.php(111): Haste\Frontend\AbstractFrontendModule->generate()
#14 composer/vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/Module/ProductReader.php(62): Isotope\Module\Module->generate()
#15 system/modules/core/elements/ContentModule.php(59): Isotope\Module\ProductReader->generate()
#16 system/modules/core/library/Contao/Controller.php(484): Contao\ContentModule->generate()
#17 system/modules/core/modules/ModuleArticle.php(213): Contao\Controller::getContentElement(Object(Contao\ContentModel), 'main')
#18 system/modules/core/modules/Module.php(287): Contao\ModuleArticle->compile()
#19 system/modules/core/modules/ModuleArticle.php(67): Contao\Module->generate()
#20 system/modules/core/library/Contao/Controller.php(417): Contao\ModuleArticle->generate(false)
#21 system/modules/core/library/Contao/Controller.php(277): Contao\Controller::getArticle(Object(Contao\ArticleModel), false, false, 'main')
#22 system/modules/core/pages/PageRegular.php(133): Contao\Controller::getFrontendModule('0', 'main')
#23 system/modules/core/controllers/FrontendIndex.php(285): Contao\PageRegular->generate(Object(Contao\PageModel), true)
#24 index.php(20): Contao\FrontendIndex->run()
#25 {main}`

Then I change the filename and add the changed image, now it works. But this seems not to be the failure, it's only important that I made a change on the image...
Of course I don't have special characters etc in the file.

**Comment by aschempp** [comment]
please explain, are you getting this message when adding a new image in the backend? can you make a screenshot?

**Comment by GMTeams** [comment]
Yes, when adding an image in the backend.

On the last 10 products I didn't had the message anymore. I will make a screenshot if it happens again!

**Comment by aschempp** [comment]
I'll close this then, feel free to reopen when you have new information.
