### ISSUE TITLE
Falscher Versand von Bestell-Benachrichtigungen

### ISSUE THREAD

**Issue by sleitz** [isotope/core#1893]
Wir haben einen kleinen Shop gebaut, der kostenlose und kostenpflichtige Bestellungen kennt. Für jeden der Fälle gibt es eine separate Benachrichtigung mit unterschiedlichen Texten/Anhängen. Leider erhalten derzeit Kunden bei kostenpflichtigen Bestellungen zwei Bestätigung-E-Mails, nämlich eine für kostenlose und eine für kostenpflichtige Bestellungen. Es muss sich um eine Regression handeln, da dies zum Zeitpunkt der Inbetriebnahme im Frühjahr 2017 noch funktioniert hatte. Hier die Details:

Für den Fall kostenloser Bestellungen ist in der Shop-Konfiguration der Status für neue Bestellungen auf "Konfektionieren" gesetzt. Überschrieben wird dies durch das Zahlungsmodul Barzahlung/Vorkasse, nämlich durch den Status "Warte auf Zahlung". Im Kassen-Modul ist *kein* Status ausgewählt, das Feld ist leer.

Mit dem Status "Konfektionieren" ist eine Benachrichtigung verknüpft, die dem Kunden eine Bestell-/Versand-Bestätigung zukommen lässt. Mit dem Status "Warte auf Zahlung" erhält der Kunde eine PDF-Rechnung und eine Zahlungsaufforderung per E-Mail.

Derzeit erhalten alle Kunden mit kostenpflichtigen Bestellungen beide E-Mails. Die Rechnung kommt also an, wie sie sollte. Zusätzlich aber wird die E-Mail mit der Versand-Benachrichtigung verschickt, was zu Verwirrungen und Rückfragen führt.

Die Bestellung erhält im Backend auch den korrekten Status "Warte auf Zahlung". Wird irgendwo in Isotope der Bestell-Status zweimal geändert, sodass er zwischendurch auch den falschen Status übergangsweise hat? Und warum hat es sich dann innerhalb der 2.4 vom Verhalten her geändert?

**Comment by aschempp** [comment]
Ich kann dir leider nicht sagen wie genau das funktionieren soll, aber es hört sich stark nach einem Konfigurationsproblem an. Isotope verschickt die Nachrichten ja nach einer bestimmten Regel. Entweder das gewünschte ist überhaupt möglich (und dann falsch konfiguriert), oder nicht vorgesehen.

Generell aber als Information, es ist falsch eine Benachrichtigung bei Bestellung über den Status zu versenden. Sie muss aus dem Kassen-Modul konfiguriert sein. Ich vermute du solltest eher den Inhalt der Nachricht über Simple Tokens unterschiedlich ausgeben, als mehrere Nachrichten zu versenden.

**Comment by sleitz** [comment]
Das mit den Tokens ist ein interessanter Ansatz. Ich werde mal sehen, ob man dort die notwendigen Prüfungen tatsächlich konditional abbilden kann.  
Vielleicht finde ich aber auch noch im Quellcode einen Hinweis, was sich seit Erstellung des Shops verändert hat.

**Comment by sleitz** [comment]
Ich habe deinen Vorschlag getestet, den Text kann ich so tatsächlich unterschiedlich ausgeben. Super! Dieses hier habe ich verwendet:

```php
{if order_total=="0,00 €"}War wohl kostenlos.{else}Juhuu, Umsatz!{endif}
```

Aber Verbesserungsbedarf besteht noch in anderen Feldern. In diesem konkreten Fall muss

a) die Rechnung nur bei kostenpflichtigen Bestellungen angehängt werden
b) je nach Art der Bestellung eine interne E-Mail-Benachrichtigung an eine andere Adresse erfolgen

Aber: weder das Feld für den Empfänger noch für den Dateianhang unterstützen die If-Abfrage. Fehlermeldung lautet:

    Die folgenden eingesetzten Tokens werden vom Notification-Typ nicht unterstützt: order_total.

Wäre es möglich, dieses und ggf. andere Tokens zum Zweck der Fallunterscheidung auch in den Feldern Empfänger, Absender, Anhang etc. zu aktivieren?

**Comment by sleitz** [comment]
Ergänzung: Wenn man das über die `$GLOBALS` so erweitert, dass es passen müsste, ergibt der Empfänger trotzdem keine gültige E-Mail-Adresse… :cry: 

Ich glaube fast, es ist doch einfacher, wenn ich das korrekte Verhalten aus der Vergangenheit im Quellcode wiederherstelle. Oder siehst du noch Licht?

**Comment by sleitz** [comment]
Noch ein Argument gegen Simple Tokens an dieser Stelle: Man kann pro Benachrichtigung nur ein Dokument hinterlegen. In diesem Shop braucht es aber in beiden Fällen unterschiedliche interne Dokumente, daher unterschiedliche Benachrichtigungen. Und die klappen halt nicht mehr.

**Comment by aschempp** [comment]
In Isotope 2.5 wird es möglich sein mehrere Nachrichten bei einer Bestellung zu versenden. Für alles andere müsstest du wohl eine Anpassung an deinem Shop vornehmen.

**Comment by sleitz** [comment]
Ich habe auf jeden Fall einen Punkt gefunden: Im Cash-Model wird die `checkout`-Methode aufgerufen, bevor der spezifische Status gesetzt wird. Das hat auch gute Gründe (#1044). Damit wird einmal der Status innerhalb der `checkout`-Methode gesetzt (weil vorher 0) und löst Benachrichtigung A aus, dann nochmals vom Cash-Model und löst Benachrichtigung B aus. Vermutlich war das sogar von Anfang an in unserem Shop kaputt und wir waren selbst zu doof.  
Insofern freue ich mich auf 2.5. Bis dahin muss ich den Kunden vertrösten, oder ihm eine kostenpflichtige Ersatzlösung anbieten. Etwas für euch?

**Comment by sleitz** [comment]
Ich habe jetzt temporär der Checkout-Methode ein optionales Flag hinzugefügt, mit dem ich aus dem Cash-Model heraus die zweifache Aktualisierung des Status unterdrücke. Abgelöst würde das dann von der neuen Situation in Isotope 2.5.
