### ISSUE TITLE
iso_payment percentage costs

### ISSUE THREAD

**Issue by mirkogleibe** [isotope/core#1897]
costs or discount of payment methods are only used in checkout if there is no percentage in it.

if -10 saved to tl_iso_payment > price,  -10 € is shown
if -10% saved to tl_iso_payment > price, nothing is shown

isotope dev-develop (f50aab67)
contao 3.5.31 LTS

**Comment by aschempp** [comment]
Fixed in f10a723d420db3df306ef99348f50502616ae927
