### ISSUE TITLE
Produkt mit optionalem Varianten-Attribut

### ISSUE THREAD

**Issue by GMTeams** [isotope/core#1898]
Ich habe ein Produkt mit dem Attribut "Zusatzteil".
Für das Zusatzteil wiederum gibt es eine Farbe.

Wenn ich nun ein Varianten-Attribut "Zusatzteil" und ein Varianten-Attribut "Zusatzteil-Farbe" erstelle, sind dies beide Pflichtfelder im Produkttyp.

Jedoch sollte das zweite Varianten-Attribut optional sein, da es ja im FE nur ausgewählt werden soll, wenn man das erste Attribut positiv wählt.

Noch besser wäre wenn sich das zweite Attribut erst einblendet, sobald beim ersten Attribut eine positive Auswahl stattgefunden hat. Also nach der Logik von "conditional form fields".

Ist derartiges in Planung?

Aktuell behelfe ich mir mit folgender Lösung:
Alles in ein Gesamt-Attribut, wobei die erste Option "kein Zusatzseil" darstellt.

Und noch eine generelle, aber für mich sehr wichtige Frage:
Was ist konkret der Unterschied zwischen "durch den Kunden auswählbar" und "Für Varianten verwenden"?
Nur, dass man mit "Für Varianten verwenden" einem Attribut abhängige andere Attribute wie zB "Preis" zuweisen kann? (Auch Verfügbarkeit von Produkten mit gewissen Attributen kann man damit natürlich steuern).

Stimmt das so?
Vielen Dank.

**Comment by aschempp** [comment]
Bitte wende dich an das Community Forum (https://community.contao.org) für Fragen, hier geht es um Bug & Feature Tracking für Isotope eCommerce.
