### ISSUE TITLE
Wrong currency symbol for Croatian language

### ISSUE THREAD

**Issue by xApep** [isotope/core#1899]
Hi.
We're translating some isotope store to Croatian language. They use Croatian Kuna ([wiki](https://en.wikipedia.org/wiki/Croatian_kuna)) as currancy.

In Store configuration you select HRK - Croatian Kuna under Currancy select field, below you have Use currency symbol. If you select this or not the "symbol" is always HRK, but Croatian Kuna currency symbol is "Kn".

Could you point me where I could change this in code? 

Thanks.

**Comment by aschempp** [comment]
Fixed in af1bfd79bca544334973918f3dfe1b5c26996e0b.

**Comment by xApep** [comment]
Thanks!
