### ISSUE TITLE
Paypal Standard Checkout redirect error

### ISSUE THREAD

**Issue by GMTeams** [isotope/core#1902]
Hi,

Contao 3.5.30
Isotope 2.4.4
PHP 7.0.20

**EDIT:** Now I have the same problem with SOFORT Überweisung, but this has worked before. So there seems an configuration problem in Isotope, but I couldn't figure it out.

In Live mode I can go through the Paypal Checkout, this works fine. Although the Paypal E-Mail "payment success" notification is coming.

Then I'm redirected back to Isotope, and here we habe the problem:
https://www.domain.com/kasse/complete.html?uid=USER_ID_0&amt=1.00&cc=EUR&st=Completed&tx=TX_0

This site is loading and loading again since it comes to:
https://www.domain.com/kasse/failed.html

**isotope_postsale.log:**

`[18-Dec-2017 10:17:03] New request to https://www.domain.com/system/modules/isotope/postsale.php?mod=pay&id=5.

Headers: array (
  'HOST' => 'www.domain.com',
  'ACCEPT' => '*/*',
  'USER_AGENT' => 'PayPal IPN ( https://www.paypal.com/ipn )',
  'CORRELATION_ID' => ‚12345678‘,
)

$_GET: array (
  'mod' => 'pay',
  'id' => '5',
)

$_POST: array (
  'mc_gross' => '1.00',
  'invoice' => '112',
  'protection_eligibility' => 'Eligible',
  'address_status' => 'confirmed',
  'item_number1' => '00000000000000',
  'payer_id' => ‚PAYER_ID_0‘,
  'address_street' => ‚ADRESS_STREET_0‘,
  'payment_date' => '01:06:10 Dec 18, 2017 PST',
  'payment_status' => 'Completed',
  'charset' => 'UTF-8',
  'address_zip' => ‚ADRESS_ZIP_0‘,
  'first_name' => ‚FIRST_NAME_0‘,
  'mc_fee' => '0.38',
  'address_country_code' => ‚ADRESS_COUNTRY_CODE_0‘,
  'address_name' => ‚ADRESS_NAME_0‘,
  'notify_version' => '3.8',
  'custom' => '',
  'payer_status' => 'unverified',
  'business' => 'paypal@domain.com',
  'address_country' => 'ADRESS_COUNTRY_0',
  'num_cart_items' => '1',
  'address_city' => ‚ADRESS_CITY_0‘,
  'verify_sign' => ‚VERIFY_SIGN_ID_0‘,
  'payer_email' => 'paypal@customer.com',
  'txn_id' => ’TXN_ID_0’,
  'payment_type' => 'instant',
  'last_name' => ‚LAST_NAME_0‘,
  'address_state' => '',
  'item_name1' => 'Testprodukt (T-Shirt)',
  'receiver_email' => 'paypal@domain.com',
  'payment_fee' => '',
  'quantity1' => '1',
  'receiver_id' => ‚RECEIVER_ID_0‘,
  'txn_type' => 'cart',
  'mc_gross_1' => '1.00',
  'mc_currency' => 'EUR',
  'residence_country' => ‚RESIDENCE_COUNTRY_0‘,
  'transaction_subject' => '',
  'payment_gross' => '',
  'ipn_track_id' => ‚IPN_TRACK_ID_0‘,
)

Body:
mc_gross=1.00&invoice=112&protection_eligibility=Eligible&address_status=confirmed&item_number1=00000000000000&payer_id=PAYER_ID_0&address_street=ADRESS_STREET_0&payment_date=01%3A06%3A10+Dec+18%2C+2017+PST&payment_status=Completed&charset=UTF-8&address_zip=ADRESS_ZIP_0&first_name=FIRST_NAME_0&mc_fee=0.38&address_country_code=ADRESS_COUNTRY_CODE_0&address_name=ADRESS_NAME_0&notify_version=3.8&custom=&payer_status=unverified&business=paypal%40domain.com&address_country=ADRESS_COUNTRY_0&num_cart_items=1&address_city=ADRESS_CITY_0&verify_sign=VERIFY_SIGN_ID_0&payer_email=paypal@customer.com&txn_id=TXN_ID_0&payment_type=instant&last_name=LAST_NAME_0&address_state=&item_name1=Testprodukt+%28T-Shirt%29&receiver_email=paypal%40domain.com&payment_fee=&quantity1=1&receiver_id=RECEIVER_ID_0&txn_type=cart&mc_gross_1=1.00&mc_currency=EUR&residence_country=RESIDENCE_COUNTRY_0&transaction_subject=&payment_gross=&ipn_track_id=IPN_TRACK_ID_0

[18-Dec-2017 10:17:05] Exception: Too few arguments to build the query string in /domain/1234567/domain-dev/system/modules/core/library/Contao/Database/Statement.php:331
Stack trace:
#0 /kunden/1234567/domain-dev/system/modules/core/library/Contao/Database/Statement.php(262): Contao\Database\Statement->replaceWildcards(Array)
#1 /kunden/1234567/domain-dev/composer/vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/Model/TypeAgent.php(227): Contao\Database\Statement->execute(Array)
#2 /kunden/1234567/domain-dev/system/modules/core/library/Contao/Model.php(930): Isotope\Model\TypeAgent::find(Array)
#3 /kunden/1234567/domain-dev/composer/vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/InsertTag.php(41): Contao\Model::findOneBy('uniqid', NULL)
#4 /kunden/1234567/domain-dev/composer/vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/Frontend.php(284): Isotope\InsertTag->replace('order::document...')
#5 /kunden/1234567/domain-dev/system/modules/core/library/Contao/InsertTags.php(1129): Isotope\Frontend->replaceIsotopeTags('order::document...', false, '', Array, Array, Array, 3, 61)
#6 /kunden/1234567/domain-dev/system/modules/core/library/Contao/Controller.php(692): Contao\InsertTags->replace('<DOCTYPE html P...', false)
#7 /kunden/1234567/domain-dev/composer/vendor/codefog/contao-haste/library/Haste/Util/StringUtil.php(64): Contao\Controller::replaceInsertTags('<DOCTYPE html P...', false)
#8 /kunden/1234567/domain-dev/composer/vendor/terminal42/notification_center/library/NotificationCenter/MessageDraft/EmailMessageDraft.php(162): Haste\Util\StringUtil::recursiveReplaceTokensAndTags('<DOCTYPE html P...', Array)
#9 /kunden/1234567/domain-dev/composer/vendor/terminal42/notification_center/library/NotificationCenter/Gateway/Email.php(115): NotificationCenter\MessageDraft\EmailMessageDraft->getHtmlBody()
#10 /kunden/1234567/domain-dev/composer/vendor/terminal42/notification_center/library/NotificationCenter/Model/Message.php(59): NotificationCenter\Gateway\Email->send(Object(NotificationCenter\Model\Message), Array, 'de-AT')
#11 /kunden/1234567/domain-dev/composer/vendor/terminal42/notification_center/library/NotificationCenter/Model/Notification.php(49): NotificationCenter\Model\Message->send(Array, 'de-AT')
#12 /kunden/1234567/domain-dev/composer/vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/Model/ProductCollection/Order.php(201): NotificationCenter\Model\Notification->send(Array, ‚COUNTRY_ID‘)
#13 /kunden/1234567/domain-dev/composer/vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/Model/Payment/Paypal.php(69): Isotope\Model\ProductCollection\Order->checkout()
#14 /kunden/1234567/domain-dev/system/modules/isotope/postsale.php(175): Isotope\Model\Payment\Paypal->processPostsale(Object(Isotope\Model\ProductCollection\Order))
#15 /kunden/1234567/domain-dev/system/modules/isotope/postsale.php(245): Isotope\PostSale->run()
#16 {main}`

Paypal configuration is made as documentation says.
Any suggests to this? Thanks.

**Comment by aschempp** [comment]
This is most likely a misconfiguration, but I prevented the error in ff892e1c71d20db2b84e8d696e4bf4247da90f1d
