### ISSUE TITLE
Attributes Options-Manager standard not selected

### ISSUE THREAD

**Issue by GMTeams** [isotope/core#1903]
I've got a product with 2 attributes, colour and size.
I want the size "M" to be always the standard in FE (checked, selected).

The options manager has the possibility to define a standard option.
Documentation says then this is "selected". But nothing happens, I don't see an "selected" in the HTML-Code. Neither on an radio input nor on an select menu.

I tried this with the isotope demo for a t-shirt - same result.

**Comment by aschempp** [comment]
You cannot select a default variant option, you can only select a default product variant (using the little star icon in the variant list).
