### ISSUE TITLE
Datepicker not working in frontend (Contao 4.4.7)

### ISSUE THREAD

**Issue by ameotoko** [isotope/core#1904]
The problem is in these three assets paths, which give the 404 error:
- `assets/mootools/datepicker/DATEPICKER/dashboard.css`
- `assets/datepicker/js/datepicker.min.js`
- `assets/mootools/datepicker/DATEPICKER/icon.gif`

These paths appear to be correct in my installation:
- `assets/datepicker/css/datepicker.css`
- `assets/datepicker/js/datepicker.js`
- `assets/datepicker/images/icon.svg`

**Comment by ameotoko** [comment]
These are hardcoded in `system/modules/isotope/library/Isotope/Model/Product/Standard.php` in lines 725, 726, 745. It's possible to replace the paths using `modifyFrontendPage` hook, but that only works with initial page load, not with AJAX calls, e.g. after selecting a product variant.

**Comment by aschempp** [comment]
Fixed in bf04ef2570054c7029c6bc992646249ef161de7a
