### ISSUE TITLE
Custom Payment Module with postale, invalid token

### ISSUE THREAD

**Issue by vmulot** [isotope/core#1905]
Hello,
I did a custom payment module based on the paypal one, it's for the french bank "LCL". The bank payment kit uses ATOS SIPS system (binary files for request and response).

the ipn thing is working, order is in backend, but after payment (on the bank website) when i click "return to shop", i have a contao error message : Invalid request token.
the url seems good : https://www.mywebsite/order/complete.html?uid=xxxxxxxxxxxx

My urls are :
`'normal_return_url' => \Environment::get('base') . Checkout::generateUrlForStep('complete', $objOrder),
            'cancel_return_url' => \Environment::get('base') . Checkout::generateUrlForStep('failed'),
            'automatic_response_url' => \Environment::get('base') . 'system/modules/isotope/postsale.php?mod=pay&id=' . $this->id,
`

i can't find a way to prevent this invalid token error. any idea ?
Thanks !

**Comment by aschempp** [comment]
Contao prevents POST request from unknown sources for security reasons. Make sure your payment provider does not issue a POST request when redirecting back to the website.

**Comment by vmulot** [comment]
yep i know how tokens works, and pb is, that my payment provider is sending back to website using POST request

**Comment by vmulot** [comment]
Hi again, i asked to my payment provider  if it was possible to do a GET request or if there was another way to do the return. answer was clear : No other way.
it's doing POST request (success, cancel, back to shop, failed, ...).
He tod me to do a "free pass" for their servers so it can bypass the token.
i got the ip ranges, but i can't manage to get the ip the request came from,.

i tried to check ip in the initconfig.php and if the ip is in the ranges, i  bypass the token check.
but the environnement::get('ip') is always giving my own IP adress.

any advice on how to achieve this ?

would it be an option to a config field where we can enter some ip in a whitelist for the token ? (i can't say if it's a good or bad idea for security...)

**Comment by aschempp** [comment]
Sorry but we can't provide free support for our free software. Please contact a Contao developer or the community forum for such questions.
