### ISSUE TITLE
[feature] Zahlungsarten - Template auswählen

### ISSUE THREAD

**Issue by wschwaiger** [isotope/core#1907]
Hi,

Bei einem Kunden von mir werden über den Open Payment Gateway mehrere Bezahlungsmethoden angeboten. Aktuell werden alle Methoden mit einer Konfiguration untereinander angezeigt.

Es wäre hilfreich wenn man das Template zuweisen könnte - also nicht nur ein iso_payment_opp.html5 hätte sondern mehrere und die Zahlungsarten innerhalb des OOP separat anzeigen lassen kann.

**Comment by aschempp** [comment]
Diese Funktion ist in der Version 2.5 (aktuell `develop`) bereits vorhanden.

**Comment by wschwaiger** [comment]
Gibt es in 2.4 ein Möglichkeit das zu machen?
