### ISSUE TITLE
Contao initialize.php was not found (Windows)

### ISSUE THREAD

**Issue by de-es** [isotope/core#1909]
Wenn ich mir in der Produktansicht die Produktgruppen anzeigen lassen will, kommt im Modalfenster die Fehlermeldung `Contao initialize.php was not found`.

Es sieht so aus, als würde unter Windows `file_exists` über den Symlink nicht funktionieren in 

https://github.com/isotope/core/blob/1a2627204128b16c61875e3dfa22ff5dada42fca/system/modules/isotope/initialize.php#L17

Wenn ich das entsprechend ersetze mit `require_once('../../../system/initialize.php');`, funktioniert es ohne Probleme.

Testsystem: Win7x64, PHP 7.1.9, Contao 4.4.12, Isotope 2.4.5

**Comment by joke1** [comment]
Habe gleiches Problem auf einem Win10 System mit PHP 7.1.6, Contao 4.4.14, Isotope 2.4.5.

Hier funktioniert allerdings gar kein relativer Pfad (auch nicht ../../../system/initialize.php).
Habe alle Varianten ausprobiert & bin weit über 10 Verzeichnisse hoch gegangen - ohne Erfolg.

Könnte das vielleicht auch an den Symlinks liegen? Die aufgerufene Datei /system/modules/isotope/group.php liegt ja in einem Symlink Ordner. Ggf. hat Windows damit ein Problem, da ich ansonsten keine Probleme mit relativen Pfaden haben.

Mit Angabe eines absoluten Pfades funktioniert es:
`realpath(str_replace('vendor\isotope\isotope-core\system\modules\isotope','',__DIR__) . 'system/initialize.php')`

@de-es Vielleicht kannst du mal schauen, ob es bei dir auch damit geht? Ansonsten müssten hier wohl zwei weitere Angaben berücksichtigt werden.

Siehe auch: #1136

**Comment by de-es** [comment]
@joke1 Ja, diese Lösung funktioniert bei mir auch.

**Comment by aschempp** [comment]
Can you please try if it works with this code:

```
$path = dirname(__DIR__);

while (($path = dirname($path)) && $path !== '/') {
    $script = $path.'/system/initialize.php';

    if (file_exists($script)) {
        require_once($script);
        return;
    }
}
```

**Comment by de-es** [comment]
Ja, das funktioniert.

**Comment by joke1** [comment]
Works for me, too.

**Comment by aschempp** [comment]
Behoben in der Version 2.5.3
