### ISSUE TITLE
[2.1.11] Problem in der Integration von Changelanguage in Isotope

### ISSUE THREAD

**Issue by EyeCatcher92** [isotope/core#1910]
Bei Produkte die auf deutsch und englisch verfügbar sind, wird man bei klick auf die andere Sprache (Flaggen Symbol) auf die Übersichtsseite der Produkt Kategorie geleitet.  
Von einigen Seiten wird man auch auf produkt-details.html weitergeleitet, diese gibt es jedoch nicht.

**Comment by aschempp** [comment]
Das liegt vermutlich daran dass deine alte Version von Isotope nur mit der alten Version von ChangeLanguage funktioniert.

**Comment by EyeCatcher92** [comment]
Danke. Habe Isotope nun auf Version 2.4.4  und es scheint zu funktionieren.
