### ISSUE TITLE
Icon in Backend-Ansicht auf einigen Seiten nicht korrekt

### ISSUE THREAD

**Issue by netzarbeiter** [isotope/core#1911]
In einer Installation 4.4.13 / 2.4.5 wird das Isotope-Icon auf folgenden Seiten nicht korrekt angezeigt.

- contao
- contao?do=iso_products
- contao?do=iso_orders

Auf diesen Seiten fehlt der Body-Tag «iso_backend44».

Deshalb wird folgendes CSS geladen:
```
#tl_navigation .tl_level_1_group .group-isotope {
    background: url(../images/module.svg) 8px center no-repeat;
    background-size: 16px 16px;
}
```
anstelle von:
```
body.iso_backend44 #tl_navigation .tl_level_1_group .group-isotope {
    background: url(../images/module44.svg) 5px 1px no-repeat;
    background-size: 14px 14px;
}
```

**Comment by qzminski** [comment]
See #1928.

**Comment by aschempp** [comment]
Closed in favor of #1928
