### ISSUE TITLE
No notification for order ID

### ISSUE THREAD

**Issue by mapfei** [isotope/core#1912]
Ich nutze zwei verschiedene Kassen-Module, da ich zwei geschützte Shops innerhalb einer Seite für Mitglieder unterschiedlicher Rechte nutze.

Im jeweiligen Kassen-Modul habe ich eine entsprechende Benachrichtigung ausgewählt, welche vom Typ "Änderung Bestellstatus" im NotificationCenter angelegt wurde. Die internen Empfänger der Bestellungen sind unterschiedlich und die Mails auch unterschiedlich formatiert/andere Inhalte.

Es werden aber **keine Benachrichtigungen** versendet. Im System-Log steht nach Auslösung der Bestellung:

```
No notification for order ID 101
New order ID 101 has been placed
```

SMTP ist richtig in parameters.yml konfiguriert.

Der Versand der Bestätigungsmails hat jedoch mal funktioniert! Ich habe das Gefühl, dass das erst seit Contao Version 4.5.1 nicht mehr funktioniert. Mit 4.4 hat es funktioniert. Isotope läuft in Version 2.4.5

**Comment by aschempp** [comment]
Ich schliesse dies da es schon älter ist. Falls es immer noch auftritt gerne das Ticket wieder öffnen.
