### ISSUE TITLE
Isotope Update Fehler: Duplicate entry uniqid in Tabelle tl_iso_product_collection

### ISSUE THREAD

**Issue by steve-smart** [isotope/core#1916]
Fehlermeldung bei Update von Contao 3.2.16 mit Isotope 2.1.9 auf Contao 3.5.33 mit Isotope 2.4.5:

Fatal error: Uncaught exception Exception with message Query error: Duplicate entry '' for key 'uniqid' (ALTER TABLE `tl_iso_product_collection` ADD UNIQUE KEY `uniqid` (`uniqid`);) thrown in system/modules/core/library/Contao/Database/Statement.php on line 295

Das Feld uniqid enthält für alle Bestellungen (type = oder) jeweils unterschiedliche Einträge.
Es gibt jedoch auch Zeilen mit type = cart statt type = order - das sind wohl Warenkörbe, die befüllt wurden, aber die Bestellung nicht abgeschlosssen wurde. Dort ist das Feld uniqid leer.
Das führt wohl dazu, dass der obige ALTER TABLE Befehl nicht ausgeführt werden kann (Duplicate entry).

Siehe auch:
https://community.contao.org/de/showthread.php?69661-Isotope-Update-Fehler-Duplicate-entry-uniqid-in-Tabelle-tl_iso_product_collection

**Comment by aschempp** [comment]
Es scheint als wurde die runonce.php nicht ausgeführt, die sollte das nämlich entsprechend bereinigen.

**Comment by steve-smart** [comment]
Habe heute das obige Update noch einmal auf andere Wesie durchgeführt. Wieder kam es zur obigen Fehlermeldung. Ein manuelles Ausführen von
UPDATE tl_iso_product_collection SET uniqid = NULL WHERE uniqid = "";
führt dazu, dass die DB danach korrekt aktualisiert werden kann.

Es scheint also ein Bug zu sein, dass die runonce.php nicht ausgeführt wird.

Wenn die runonce.php nicht ausgeführt wird: Ist der obige UPDATE Befehl das einzige, was darüber angestoßen wird oder könnte das Update auch im Bezug auf andere Dinge unvollständig/defekt sein?

**Comment by aschempp** [comment]
Hast du überprüft ob die runonce.php ausgeführt wurde oder nicht? Wie hast du das Update gemacht?

**Comment by steve-smart** [comment]
Ich habe das Update so gemacht:

- Auf dem Webserver eine Subdomain eingerichet (Testsystem)

- Datenbank des Livesystems geklont (Kopie der Livesystem-DB für das Testsystem)

- "Frisches" Contao 3.5.33 in die Subdomain kopiert

- Die Dateien files/*, Templates/*, dcaconfig.php, localconfig.php, initconfig.php, langconfig.php aus dem Livesystem ins Testsystem (Subdomain) kopiert, dabei in der localconfig.php die DB-Verbindung auf die neue DB des Testsystems geändert

- tl_search und tl_search_index der DB des Testsystems manuell geleert

- alle Nicht-Core-Erweiterungen aus dem system/modules-Ordner des Livesystems in den system/modules-Ordner des Testsystems kopiert

- Aufruf Install-Script (Testsystem), dabei Update der DB auf Contao 3.5 durchgeführt

- In dere Erweiterungsverwaltung des Testsystems alle Erweiterungen bis auf Isotope aktualisiert

- Es wurde nicht angezeigt, dass eine neue Version von Isotope zur Verfügung steht. Habe daher die für Isotope neu nötigen Erweiterungen dc_multilingual 2.1.7 und httprequestextended 1.1.0 über die Erweiterungsverwaltung installiert.

- Danach wurde angezeigt, dass das Isotope-Update auf Version 2.4.5 zur Verfügung steht.

- Isotope auf Version 2.4.5 aktualisiert über die Erweiterungsverwaltung

- beim Aktualisieren der DB Fehler in error.log:
PHP Fatal error: Uncaught exception 'Exception' with message 'Query error: Duplicate entry '' for key 'uniqid' (ALTER TABLE `tl_iso_product_collection` ADD UNIQUE KEY `uniqid` (`uniqid`);)' thrown in /*****/system/modules/core/library/Contao/Database/Statement.php on line 295

- über "DB aktualisierten" alles außer ALTER TABLE `tl_iso_product_collection` ADD UNIQUE KEY `uniqid` (`uniqid`); aktualisiert

- Ändern der leeren Einträge in NULL direkt in der DB:
UPDATE tl_iso_product_collection SET uniqid = NULL WHERE uniqid = "";

- Datenbank aktualisiert - jetzt hat es funktioniert!

Ich kann daher nicht sagen, ob die runonce.php ausgeführt wurde. Wie kann ich das überprüfen? Alles was ich sagen kann ist, dass die Datei runonce.php jetzt nach dem Update NICHT mehr im Ordner system/modules/isotope/config enthalten ist. Wird diese Datei nach der Ausführung wohl automatisch gelöscht?

**Comment by aschempp** [comment]
Ich schliesse dies mal da es sich in der Zwischenzeit vermutlich erledigt hat.

**Comment by steve-smart** [comment]
Nein, es hat sich leider nicht erledigt. Habe das Update auch bei einem anderen Shop gemacht und es gab ebenfalls den "Duplicate entry" Fehler.

**Comment by steve-smart** [comment]
Kurze Info: Nach dem Update von PHP 5.4 auf PHP 5.6 ist dieser Fehler nicht mehr aufgetreten.
