### ISSUE TITLE
PayPal Plus?

### ISSUE THREAD

**Issue by m-vo** [isotope/core#1917]
This isn't an issue but a question regarding the feature branch `paypal-plus-checkout`: There was some work done about a year ago but the last commit has a telltale WIP in it's message. :-) Could anybody maybe roughly point out what's still missing or why it wasn't merged yet? 

Thanks alot in advance.

**Comment by aschempp** [comment]
PayPal Plus is already integrated in the develop branch. The feature branch was an attempt to integrate their payment method selection in the checkout, but that does not work with Isotope.

**Comment by m-vo** [comment]
Thanks @aschempp
