### ISSUE TITLE
Make quantity mobile friendly

### ISSUE THREAD

**Issue by netzarbeiter** [isotope/core#1918]
Change input type from `text` to `number` for the quantity field (list, reader, cart, favourites and order details).

**Comment by ameotoko** [comment]
Isn’t it something that can be achieved by adjusting a template? I’m using a `select` element in my projects instead of `text` field, for example.

**Comment by netzarbeiter** [comment]
I can of course adjust the template, but if the type will be changed, you don't have to switch from text to numeric keyboard on the mobile. If you choose `Numeric characters` as input validation in Contao the type is `number`.
