### ISSUE TITLE
Contao 4: What to pass into setLoadAfter() in order to get my bundle load after isotope module?

### ISSUE THREAD

**Issue by Defcon0** [isotope/core#1922]
Hello,

I recently tried to declare that my Contao 4 bundle should load *after* the isotope module (isotope/isotope-core). For bundles I use the class name like ContaoCoreBundle::class. For contao 3 modules just passing in the module name works. I tried some versions with no success at all:

```
class Plugin implements BundlePluginInterface
{
    /**
     * {@inheritdoc}
     */
    public function getBundles(ParserInterface $parser)
    {
        return [
            BundleConfig::create(HeimrichHannotContaoIsotopeBundle::class)->setLoadAfter([ContaoCoreBundle::class, 'isotope', 'isotope_core', 'isotope-core']),
        ];
    }
}

```

What's exactly the name that I need to pass in here to succeed? Or is it a bug?

Bye Defcon0

**Comment by aschempp** [comment]
As you said, using the module name works for Contao 3 modules. Just be aware that Isotope consists of three modules so you might want to pass all of them.

**Comment by Defcon0** [comment]
*Very* strange, now it worked with only 'isotope'. In fact this makes sense, since the backend.css is only assigned in isotope (not in isotope_rules or isotope_eports).
