### ISSUE TITLE
Falsche Ausgabe der Versandarten bei deaktivierter Versand-Adresse

### ISSUE THREAD

**Issue by joke1** [isotope/core#1923]
Habe einen Shop, wo nur Gäste bestellen können. Bei den Versandarten habe ich für verschiedene Länder verschiedene Lieferdienste erstellt. In der Shop-Konfiguration habe ich im Bereich "Kasse" -> "Adressfelder" sämtliche Optionen in der zweiten Spalte "Für Versand-Adresse" deaktiviert, wodurch im FE keine Abfrage der Lieferadresse mehr erscheint. 
In dem Fall sollte das ausgewählte Land der Rechnungs-Adresse als Grundlage zur Berechnung der zu Verfügung stehenden Versandarten dienen. Dies geht aber nicht.
```php
Isotope::getCart()->getShippingAddress();
```
Gibt mir dort immer die Standardeinstellung (Shop-Konfiguration->Adresse->Land) aus, obwohl ein anderes Rechnungs-Land ausgewählt wurde. 
Die oben genannte Methode berechnet die Adresse dann über die letzte Möglichkeit:
https://github.com/isotope/core/blob/1a2627204128b16c61875e3dfa22ff5dada42fca/system/modules/isotope/library/Isotope/Model/ProductCollection/Cart.php#L95

Sobald ich irgendein Adressfeld für die Versand-Adresse aktiviere und im FE die Auswahl "Rechnungs-Adresse verwenden" auswähle, passt wieder alles.

Einfache Lösung wäre wahrscheinlich ein verstecktes Feld auszugeben (shippingaddress = -1), wenn alle Versand-Felder deaktiviert wurden & die Radiobox nicht angezeigt wird.

Für mich ist das kein Problem, da ich die Auswahl einfach per CSS ausblenden kann.
Ggf. kann man das aber trotzdem irgendwann berücksichtigen :)

PS: Fürs debuggen:
Wenn man einmal die Auswahl "Rechnungs-Adresse verwenden" ausgewählt hat & anschließend in der Shop-Konfiguration alle Felder deaktiviert, wird es richtig berechnet, da er sich die Auswahl noch gemerkt hat. In dem Fall muss also eine neue Bestellung erstellt bzw. die Cookies gelöscht werden.

**Comment by aschempp** [comment]
Keine Versand-Felder zu aktivieren ist bisher nicht vorgesehen. Dass damit etwas funktioniert hat war wohl eher Zufall…

**Comment by aschempp** [comment]
Im Kassenmodul gibt es eine Checkbox dass immer die Rechnungsadresse als Versandadresse genutzt werden soll. Damit dürfte dein Problem behoben sein.
