### ISSUE TITLE
Replace all new line characters in flash message

### ISSUE THREAD

**Issue by qzminski** [isotope/core#1925]
A colleague of mine just encountered a problem where the JS failed because not all new line characters were replaced. I think to fix this the following change has to be made:

```diff
if ($messages !== '') {
    $template->hasMessages = true;
-    $template->messages = str_replace(array("\n", "'"), array('', '\''), $messages);
+    $template->messages = str_replace(array("\n", "\r", "'"), array('', '', '\''), $messages);
}
```

https://github.com/isotope/core/blob/master/system/modules/isotope/library/Isotope/Frontend.php#L337

What do you think?

**Comment by aschempp** [comment]
Who added newline characters to the message in the first place? Shouldn't it be fixed there?

**Comment by aschempp** [comment]
😮 why would a template be in the flash messages?

**Comment by qzminski** [comment]
It has been there ever since:

- https://github.com/isotope/core/blob/9c594727918360a73151605600c4fec26490edbc/system/modules/isotope/library/Isotope/Message.php#L103
- https://github.com/isotope/core/blob/master/system/modules/isotope/library/Isotope/Module/Messages.php#L59
- https://github.com/isotope/core/blob/master/system/modules/isotope/templates/modules/mod_iso_messages.html5
