### ISSUE TITLE
Falsches Lade-Icon bei C4

### ISSUE THREAD

**Issue by joke1** [isotope/core#1926]
Hi,

In der [isotope.css](https://github.com/isotope/core/blob/master/system/modules/isotope/assets/css/isotope.css#L21) wird ein Lade-Icon eingebunden, welches unter Contao 4 aufgrund des neuen Themes nicht mehr funktioniert:
system/themes/**default**/images/loading.gif

Lösungsvorschlag A: Für C3 und C4 unterschiedliche CSS-Dateien laden.
Lösungsvorschlag B: Ein eigenes Lade-Icon einbinden und den eigenen images Ordner hierfür nutzen.
Lösungsvorschlag C: Kein Icon mehr nutzen ;-)

BG

**Comment by aschempp** [comment]
I think we should duplicate the loading icon in our CSS to the isotope folder. This way we can ensure it always works and liking to the backend theme definitely is and never was a good idea.

**Comment by qzminski** [comment]
Fix proposal in #1927.

**Comment by aschempp** [comment]
Closed in favor of #1927
