### ISSUE TITLE
multilingual attributes ISO-639-1 ('de') vs. locale ('de-DE')

### ISSUE THREAD

**Issue by Z3NOX** [isotope/core#1929]
https://github.com/isotope/core/blob/1a2627204128b16c61875e3dfa22ff5dada42fca/system/modules/isotope/library/Isotope/Model/Attribute.php#L468

Hi,
I used the following language-country Codes (TL_LANGUAGE) for my website [en, de-DE, en-GB, ...]. I furthermore wanted to translate self chosen attributes into the different languages (en, de). The problem here is that isotope identifies TL_LANGUAGE with the foreignKey given in the isotope settings. However, in the isotope foreignKey settings only languange codes (en, de, fr, ...) can be defined but no languange-country codes - which is the right way IMHO. This leads to the problem that e.g. 'de-DE' does not match 'de'.

I would like to propose a patch by inserting
`if (strpos($strLanguage, "-") === 2 || strpos($strLanguage, "_") === 2) {
$strLanguage = substr($strLanguage, 0, 2);
}`
[here](https://github.com/isotope/core/blob/1a2627204128b16c61875e3dfa22ff5dada42fca/system/modules/isotope/library/Isotope/Model/Attribute.php#L456).

Thank you for all the work!
z3nox

**Comment by aschempp** [comment]
why should it not be possible to have a 5-char language code, same as in the page layout? I think thats rather a missing feature?

**Comment by Z3NOX** [comment]
because:

a.) Here the "=" is explicitly assumed to be on the third position in the line where the foreignKey is given.
https://github.com/isotope/core/blob/1a2627204128b16c61875e3dfa22ff5dada42fca/system/modules/isotope/library/Isotope/Model/Attribute.php#L465

b.) Furthermore something like 'de-DE=mm_my_table' cannot be entered and saved in the backend since the callback will cut the input also hard at the third position. See
https://github.com/isotope/core/blob/1a2627204128b16c61875e3dfa22ff5dada42fca/system/modules/isotope/library/Isotope/Backend/Attribute/Callback.php#L165

**Comment by eBlick** [comment]
Is there a work in progress to this issue? I am currently updating a multilangual (6 languages) shop where a en-US and a en-UK Version is used.

No language-specific attributes appear as soon as the extended 5-char language code is in use.

**Comment by aschempp** [comment]
Fixed in 2e86f9713d90162d4d1287e670895c11b2102bd9
