### ISSUE TITLE
Einschränkender Filter mit Mehrfachauswahl-Felder

### ISSUE THREAD

**Issue by danieleicher** [isotope/core#1933]
Contao 4.4.18 / Isotope 2.5

Beim einschränkenden Filter funktioniert die Einschränkung sowie die Anzeige der Ergebnisse nur, wenn keine Multiple-Choice-Felder verwendet werden.

Beispiel:

- 2 Attribute (single choice)
- 1 Attribute (multiple choice)
- Verknüpfung mit AND und Anzeige aller Ergebnisse bei allen Attributen.

Einschränkung funktioniert nicht. Anzahl wird nicht angezeigt.
Multiple-Choice-Attribut entfernt, alles funktoiniert.

Hab nichts gefunden, dass dies dokumentiert oder begründet wird, deshalb gegebenenfalls ein Bug.

**Comment by trilobit-gmbh** [comment]
Hallo,
ich bin auch über den Fehler "gestolpert". Wenn ich es richtig gefunden habe, dann ist "Isotope\RequestCache\Filter::matches" dafür verantwortlich.

```
if ($attribute instanceof IsotopeAttributeWithRange && $attribute->allowRangeFilter()) {
    $varValues = $attribute->getValueRange($objProduct);
} elseif ($attribute instanceof IsotopeAttribute) {
    $varValues = $attribute->getValue($objProduct);
} else {
    $varValues = $objProduct->{$this->arrConfig['attribute']};
}

// If the attribute is not set for this product, we will ignore this attribute
if (null === $varValues) {
    return false;
}

if (!is_array($varValues)) {
    $varValues = deserialize($varValues, true);
}
```
Der Fehler liegt hier im letzten Teil. Diese Aussage ist true, da das serialisierte Array, welches in $varValues liegt nicht direkt dort liegt sondern "eine Ebene tiefer"

IST:
```
[0 => 'a:2:{i:0;i:407;i:1;i:408;}']
```
SOLL
```
'a:2:{i:0;i:407;i:1;i:408;}'
```

**Comment by jgollerilumy** [comment]
Ich habe selbst auch über das selbe Problem stolpern müssen.

Kann ich die trotzdem irgendwie verwenden? Gibt es da einen vielleicht Workaround?

Da der Bug nämlich schon ein Jahr offen ist, habe ich wohl eher nicht die Zeit auf einen Fix zu warten.

**Comment by aschempp** [comment]
> Da der Bug nämlich schon ein Jahr offen ist, habe ich wohl eher nicht die Zeit auf einen Fix zu warten.

@jgollerilumy Isotope eCommerce ist Open Source, du kannst dich selber um die Lösung des Problems kümmern statt zu warten... https://www.terminal42.ch/de/open-source.html

**Comment by jgollerilumy** [comment]
Ich weiss, was Open Source bedeutet. Selbst habe ich allerdings nicht das Know-How, solche Bugs zu fixen. Aus diesem Grund habe ich eure Unterstützung in der Vergangenheit übrigens auch schon vermittelt. 

In diesem Fall jetzt konnte ich leider nichts finden, was mir weiterhilft, außer, was in diesem Issue steht und einen [Report des selben Bugs](https://community.contao.org/de/showthread.php?74228-Einschr%C3%A4nkender-Filter-mit-Milti-Choice-Attributen) im Contao Forum

Da es schon ein Jahr offen ist, dachte ich, ich frage hier auch mal nach einem work around, bevor ich die Segel streiche.

**Comment by aschempp** [comment]
Der Fehler wird in der 2.5.15 behoben (dank eines [Isotope Circle Mitglieds](https://circle.isotopeecommerce.org) 😉)

**Comment by trilobit-gmbh** [comment]
Danke an Dich und den Unterstützer aus dem Circle!
