### ISSUE TITLE
Regeln und Gutscheine Enddatum

### ISSUE THREAD

**Issue by Mynyx** [isotope/core#1936]
Bei Regeln und Gutscheinen gibt es das Feld Enddatum mit folgender Beschreibung: "Falls gewollt, geben Sie hier ab welchem Datum diese Regel nicht mehr zur Verfügung steht."

Gibt man im dem Feld jedoch das heutige Datum ein, wird die Regel entgegen der Beschreibung dennoch angewandt. Gibt man das gestrige Datum ein, wird die Regel nicht mehr angewandt.

**Comment by Mynyx** [comment]
In dem Beschreibungstext fehlt außerdem das Wort "an" oder "ein".

**Comment by aschempp** [comment]
Hab's in 5d6c97da2e8878dec35c527d0913deef13582187 verbessert.
