### ISSUE TITLE
Regeln und Gutscheine: Startzeit und Endzeit

### ISSUE THREAD

**Issue by Mynyx** [isotope/core#1937]
Bei Regeln und Gutscheinen gibt es die Felder Startzeit und Endzeit. 

Lässt man diese Felder frei und gibt bei Startdatum 01.01.2018 und bei Enddatum 01.01.2019 ein, wird die Regel angewandt.

Gibt man in diese beiden Felder jedoch jeweils 00:00:00 ein und belässt Startdatum und Enddatum unverändert, wird die Regel fehlerhaft nicht mehr angewandt.

**Comment by aschempp** [comment]
Die Felder Datum und Uhrzeit sind aktuell "unabhängig". Du kannst eine Regel einschränken dass sie nur Nachmittags verfügbar ist, oder an einem gewissen Datum. Du kannst nicht sagen "von Datum um x Uhrzeit".

**Comment by Mynyx** [comment]
Könnte man dort einen Hinweis hinzufügen, dass Datum und Uhrzeit unabhängig voneinander gelten?

**Comment by zonky2** [comment]
wäre es dann nicht eine Option, per Checkbox beide Felder zu verbinden? so dass man einstellen kann, Gutschein gilt vom 01.01.2018 10.00h bis 30.01.2018 20:00h?

**Comment by DrAColian** [comment]
Gut zu wissen - da bin ich jetzt auch drüber gestolpert. Gibt es schon eine Idee ob und wann ihr das umsetzt?

**Comment by aschempp** [comment]
this should be fixed by #2120
