### ISSUE TITLE
Isotope eCommerce Upgrade step "Version 2.1.6 beta2" was not run successfully!

### ISSUE THREAD

**Issue by bytehead** [isotope/core#1939]
Isotope catches Exceptions that not really belong to Isotope:
https://github.com/isotope/core/blob/e171588a475e63a2621b5841c89f3adb52e9cd03/system/modules/isotope/library/Isotope/Upgrade.php#L48-L52

While running the installer (or the DB update in the backend) this error shows up:
![bildschirmfoto 2018-04-25 um 16 25 50](https://user-images.githubusercontent.com/754921/39252169-58be6006-48a5-11e8-839b-a5b86abc0685.png)

Here is the Exception in detail:
```
ErrorException {#114 ▼
  #message: "Referencing the "core" extension by its name (defined by getName()) is deprecated since 1.26 and will be removed in Twig 2.0. Use the Fully Qualified Extension  ▶"
  #code: 0
  #file: "/composer/vendor/twig/twig/lib/Twig/Environment.php"
  #line: 897
  #severity: E_USER_DEPRECATED
  trace: {▶}
}
```

I don't think it's the task of Isotope to catch any `Exception` there, in this case it's even a `ErrorException` with a severity of `E_USER_DEPRECATED`

**Comment by aschempp** [comment]
Fixed in 610e8f8e42812176a4e37726ed937afd5facc333
