### ISSUE TITLE
Ticket #415: Rich snippets (Microdata, Microformat or RDFa

### ISSUE THREAD

**Issue by blairwinans** [isotope/core#194]
It might be a good idea to implement any version of Rich snippets that search engines support. Google uses this in search results yielding results with more information to potential customers. It is relatively easy to do if the format be Microformats because many of the class names are already used. This can be an advantage gained with little effort.

Also see http://www.contao-community.org/viewtop  amp;t=2847

_--- Originally created by winanscreative on 2011-09-26 22:06:03 (ID 2131)_

**Comment by drdotti** [comment]
Das ist mir auch an Hand der Fehler in der Google Search Console aufgefallen, siehe auch:
[https://community.contao.org/de/showthread.php?75147-C-4-7-4-und-Isotope-2-5-12-%C2%B7-Produktinformationen-mit-Markup-auszeichnen&p=505134&viewfull=1#post505134](url)
