### ISSUE TITLE
Question: Delete multiple orders

### ISSUE THREAD

**Issue by ameotoko** [isotope/core#1940]
As of now, it's impossible to delete multiple orders in the backend, even for administrator. Is this on purpose?
Use case: delete a bunch of test (or old) orders. The ordering process in my set up involves uploading files by a customer, would be nice to be able to clean it up sometimes.

**Comment by aschempp** [comment]
Yes that is intentional, as it is very dangerous to me. If you need to wipe out all orders before going to products, it's best if you simply truncate the database tables.
