### ISSUE TITLE
Payzen payment module - Lyra could do it with some help

### ISSUE THREAD

**Issue by JLBA** [isotope/core#1941]
Hi everyone,

Lyra Network / Payzen (payzen.eu) channel manager would like to consider creating a payment module for Isotope. He is looking for how to contact you. Could you contact him directly : 
**Anis Raouane** - anis.raouane@lyra-network.com - +339 72 40 33 32 / +336 07 46 49 63
Thanks.

**Comment by aschempp** [comment]
❓ there is a contact page on the Isotope eCommerce website 😉 
https://isotopeecommerce.org/en/contact.html

**Comment by JLBA** [comment]
ok. Thanks. 
He said to me he tried but you didn't answer. But perhaps did he confound with Contao's page. I transmit.
