### ISSUE TITLE
E-Mail Adresse im Kassenmodul / Adressbuch im eingeloggten Zustand

### ISSUE THREAD

**Issue by pet21221** [isotope/core#1947]
Ich habe das Problem, dass durch Aktivieren der E-Mail Adresse in der Shop-Konfiguration auch im eingeloggten Zustand nach einer E-Mail Adresse gefragt wird.

Kann man in dem Fall nicht automatisch die E-Mail Adresse des Benutzer's nehmen und das Feld wird im eingeloggten Bereich erst garnicht gerendert?

Das selbe betrifft natürlich auch das Adressbuch, welches kein E-Mail Adresse-Feld haben soll.

Eventuell wäre dies ein Feature.

**Comment by aschempp** [comment]
über das DCA kannst du das Feld mit dem Wert aus dem Mitgliederprofil vorbelegen, eine andere Optimierung (ein/ausblenden abhängig vom Login-Zustand) ist aktuell nicht möglich.

```
// dcaconfig.php
$GLOBLAS['TL_DCA']['tl_iso_address']['fields']['email']['default'] = '{{user::email}}';
```
