### ISSUE TITLE
Description mandatory

### ISSUE THREAD

**Issue by xApep** [isotope/core#1948]
Hi. If I set description field mandatory to "no" it is still mandatory when you're adding product.
Isotope version 2.4.5

**Comment by netzarbeiter** [comment]
https://github.com/isotope/core/blob/84075c4f2951e6f5f5a6cca4fd70ebe06b411f76/system/modules/isotope/dca/tl_iso_product.php#L392

**Comment by xApep** [comment]
I know ;) but there is a backend option ... well maybe it's not meant to be? :)

**Comment by aschempp** [comment]
Fixed in 46273b2aecff9f36932c24eb0e7cb74bcacbe7c1
