### ISSUE TITLE
Iso 2.5.1: Button "Aktualisieren" ohne Wirkung

### ISSUE THREAD

**Issue by zonky2** [isotope/core#1951]
Iso 2.5.1: Button "Aktualisieren" ohne Wirkung - wenn im (Mini)-Warenkorb Items vorhanden sind, werden diese durch Ändern der Anzahl beim Item + Klick auf Aktualisieren nicht geändert

**Comment by aschempp** [comment]
im Mini-Warenkorb gibt es doch keine Eingabe für die Anzahl? Hast du das Template entsprechend angepasst?

**Comment by zonky2** [comment]
sorry - ungenau beschrieben...

also - ich habe eine Seite mit Produkten inkl. Anzahl sowie den Mini-Warenkorb

wenn ich bei dem Produkt die Anzahl ändere und aktualisiere, ändert sich das im Mini-Warenkorb nicht

**Comment by aschempp** [comment]
Ah, das ist so auch nicht vorgesehen. Der Aktualisieren-Button aktualisiert die Produktansicht (reload ohne Javascript), nicht den Warenkorb. Die Anzahl der Produkte lässt sich nur im Warenkorb einstellen (oder indem (dasselbe erneut) in den Warenkorb gelegt wird).

**Comment by zonky2** [comment]
oj!

das klingt für mich nicht sehr logisch, da nach meiner Auffassung ein User das anders erwarten würde

wäre es nicht besser hier ein FR draus zu machen?
