### ISSUE TITLE
Add support for Saferpay in sandbox mode

### ISSUE THREAD

**Issue by rflx** [isotope/core#1953]
Due that Saferpay uses other base URL's for its sandbox mode it would be great to implement a checkbox in the payment module to turn Saferpay in sandbox mode.

More information and credentials:
https://www.six-payment-services.com/en/site/e-commerce/support/testaccount.html

Please verify if its necessary to update the https password `spPassword` because its obliged to use with the general test account.

**Comment by aschempp** [comment]
Added in 115e7b533899ee53f9636126d211065e499b675c
