### ISSUE TITLE
Address book - Save data error!

### ISSUE THREAD

**Issue by onemarshall** [isotope/core#1954]
Hi, When editing a members details within the Address Book and then clicking the ‘Save data’ button,
Contao displays the following error message;

`[2018-06-20 20:47:58] app.CRITICAL: An exception occurred. {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Type error: Argument 3 passed to Isotope\\Module\\AddressBook::triggerNotificationCenter() must be an instance of User, instance of Contao\\FrontendUser given, called in /Users/rob/Sites/_cms/contao/public/dev/vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/Module/AddressBook.php on line 251 at /Users/rob/Sites/_cms/contao/public/dev/vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/Module/AddressBook.php:303)"} []`

The edited content is saved, when I reload/refresh the page, I can see the amended content. 
I have also tested with and without a notification selected. This has been tested on a clean install with just Isotope 2.5.1 installed.

I have also tested with 4.4.19 and there are no errors showing when clicking the ‘Save data’ button.

**Mac**
**Contao:** 4.5.9
**PHP:**  7.1.18
**MariaDB:** 10.3.7

Thanks

**Comment by johannes-bittner** [comment]
I can confirm the issue as depicted above. 

Contao 4.5.11
PHP 7.2.8
Isotope 2.5.1

**Comment by aschempp** [comment]
Fixed in eaf268d09ea05cbf8202b4a51b0bfa3182f1c938
