### ISSUE TITLE
Timeout bei Paypal Plus

### ISSUE THREAD

**Issue by Sukrams** [isotope/core#1955]
Wenn ich Bestellungen mit PayPal Plus bezahlen möchte, lädt die Seite nach dem Checkout sehr lange. Es passiert hier nichts, ehe es zu einem Abbruch kommt und ich einen Timeout (504 Gateway Timeout- "Gateway Timeout The gateway did not receive a timely response from the upstream server or application.") erhalte.

Aus den Logs geht leider nichts  entsprechendes hervor, was hierbei helfen könnte. Kann ich ggfs. sonst weiter bei einer ggfs. Reproduktion des Problems helfen?

Viele Grüße
Markus

**Comment by aschempp** [comment]
Für Support-Fragen wende dich bitte an das Contao Community Forum (https://community.contao.org) oder den Isotope Circle (https://circle.isotopeecommerce.org)
