### ISSUE TITLE
Iso 2.5.1 unter contao 4.5.10 Feld "Preis" läßt sich nicht editieren!

### ISSUE THREAD

**Issue by kubjo** [isotope/core#1956]
Das Feld "Preis" läßt sich sowohl bei normalen Produkten als auch bei Varianten nicht editieren!
Einen kleinen Schritt weiter kommt man, wenn man das Browserfenster auf Handygröße verkleinert, dann kann man reinklicken und löschen, aber nicht reinschreiben!
Getestet unter Win10/FF und Win10/Chorme

**Comment by kubjo** [comment]
Inzwischen konnte vielleicht das Problem näher eingegrenz werden: [Forum](https://community.contao.org/de/showthread.php?71273-Isotope-2-5-1-unter-contao-4-5-10-Feld-quot-Preis-quot-l%C3%A4%C3%9Ft-sich-nicht-editieren!)

**Comment by fritzmg** [comment]
Dir fehlt in deiner Shopkonfiguration bei den Einstellungen deines Produkttyps ein Wert in der Spalte __Ausrichtung__ bei den Produktattributen für dein eigenes Attribut. Du musst in diesem Fall entweder `clr`, `w50` (oder beides) eintragen.

**Comment by kubjo** [comment]
Hi fritzmg,
Danke! Ich bin mir noch nicht ganz sicher welches Attribut Du meinst, und ob ich den Wert bei "Attribute" oder "Varianten Attribute" eingeben soll. Mein eigenes Attribut? Meinst Du "Preis"?

**Comment by fritzmg** [comment]
Laut deinem Screenshot:

![produkte produkt id 2098 bearbeiten contao open source cms](https://user-images.githubusercontent.com/4970961/42447410-0d1d5a20-837a-11e8-9bf9-c0870c0a0f4a.png)

hast du für diesen Produkttype ein eigenes Attribut namens "Farbe". Für diesen Produkttyp hast du eingestellt, dass das Attribut "Farbe" mit den "Preis-Einstellungen" gruppiert wird. Du hast aber dann keine "Ausrichtung" definiert, wodurch das Attribut das reguläre "Preis" Attribut in der selben Attributsgruppe überlagert.

**Comment by kubjo** [comment]
DANKE! Jetzt habe ich es kappiert! Ich danchte diese Gruppiereung ist nur dafür zuständig, dass jede Frabe ihren eigenen Preis hat. Dass die Gruppierung auch "visuell" im BE gekoppelt ist, war für mich nicht klar! Warum das aber unter contao 3.5.x noch funktionierte, und es sich nach dem Update auf 4.5.x "überlappt" wundert mich dann schon!

**Comment by fritzmg** [comment]
> Warum das aber unter contao 3.5.x noch funktionierte, und es sich nach dem Update auf 4.5.x "überlappt" wundert mich dann schon!

Ja, siehe auch https://github.com/contao/core/issues/8669
