### ISSUE TITLE
InsertTag wird nicht ersetzt

### ISSUE THREAD

**Issue by akroii** [isotope/core#1958]
Nehmen wir an, wir haben im Template `iso_reader_default.html5` ein Inserttag `{{product::name}}`. 
Spätestens beim Wechsel eines Ajax Attributes im Frontend wird das `{{product::name}}` nicht ersetzt... es bleibt unverändert.

Beispiel:
Auf dem iso_reader_default.html5 befindet sich ein Text der da lautet: "Weitere Fragen zum Produkt Strechtfolie"
Wenn ich jetzt ein Attribut auswähle, dann erscheint der Lade-Spinner und anschließent wird aus "Weitere Fragen zum Produkt Strechtfolie" -> Weitere Fragen zum Produkt {{product::name}}

Isotope 2.5.1
Contao 3.5.30

**Comment by aschempp** [comment]
Es macht überhaupt keinen Sinn im entsprechenden Template den entsprechenden InsertTag zu verwenden. Dafür gibt es doch bereits entsprechende Template-Variabeln?
