### ISSUE TITLE
Ticket #440: Export Orders Functionality

### ISSUE THREAD

**Issue by blairwinans** [isotope/core#196]
_By Justin Friend in Feature Requests on Thu, Apr 14. 2011 04:18 PM_

It would be nice if people could Export Orders. This may be better suited for a module, but it seems like something everyone could benefit from.

_--- Originally created by winanscreative on 2011-09-26 22:25:02 (ID 2133)_

**Comment by jenda77** [comment]
For me it would be important too because I need to export all orders at once but not as bill.

**Comment by katgirl** [comment]
see https://github.com/katgirl/isotope-order_export, it's for isotope 1.X but you can update it for isotope 2.X

**Comment by jenda77** [comment]
Thank you. I will try to install it per Composer. I hope it will work.

**Comment by jenda77** [comment]
@katgirl I have installed your extension but I cannot find any possibility to export the orders... Where can I find it? :-)
