### ISSUE TITLE
404-Fehlerseite wird nicht korrekt ausgegeben

### ISSUE THREAD

**Issue by cubano** [isotope/core#1960]
Ich verwende den Produktleser auf einer separaten Seite und habe im Modul "Produktleser" die Funktion "Eine 404-Fehlerseite anzeigen" aktiviert, falls kein Produktalias in der URL vorhanden ist.

Nun wird die 404-Seite zwar angezeigt, jedoch enthält der body-tag folgenden HTML-Code innerhalb von class="

<esi:include src="/_fragment?_path=insertTag%3D%257B%257Bua%253A%253Aclass%257D%257D%26_format%3Dhtml%26_locale%3Dde%26_controller%3Dcontao.controller.insert_tags%253ArenderAction&clientCache=0&pageId=2380&request=de%2Fonline-shop%2Ftest&_hash=N1xWPqVBcs4LYKiGj1CGOeX53nJVgAQF0L5OmfQaKco%3D" onerror="continue" />

Contao 4.4.20, Isotope 2.5.1

**Comment by Toflar** [comment]
Kann ich mir nicht erklären, die Seite müsste ganz normal durch den Cache. Ist das bei dir reproduzierbar @aschempp ?

**Comment by aschempp** [comment]
Ich habe es noch nicht versucht nachzustellen.

@cubano funktioniert denn alles wenn du die 404-Checkbox nicht aktivierst?

**Comment by cubano** [comment]
Seitencache ist aus.

Problem tritt auf mit oder ohne aktivierter 404-Checkbox.

Seitenalias Produktliste = /de/online-shop
Seitenalias Produktleser = /de/online-shop/produktdetails

Der Seitenalias vom Produktleser wird ja überschrieben vom Alias des Produktes, also z.B. /de/online-shop/produktname (ohne /produktdetails/)

Gebe ich nun im Browser z.B. /de/online-shop/test ein, kommt die Fehlerhafte 404-Seite (mit oder ohne Checkbox 404). Gebe ich z.B. /de/test ein, kommt die korrekte Fehlerseite.

Bei deaktivierter Checkbox kommt bei /de/online-shop/produktleser die leere Produktdetailseite, was ja korrekt ist. Bei aktivierter Checkbox die Fehlerhafte 404-Seite.

**Comment by aschempp** [comment]
Es scheint als würde auf der 404-Seite die ESI-Fragmente nicht aufgelöst. Besteht dieses Problem bei dir auch bei einer normalen 404-Seite (also wenn du eine ungültige URL aufrufst)?

**Comment by cubano** [comment]
Nein, bei einer normalen Seite funktioniert es fehlerfrei. Der Fehler besteht nur bei der Shop-Detailseite. Bei der Seite domain.tld/de/online-shop habe ich "Detailseite benutzen" aktiviert und eine andere Seite ausgewählt für die Detailansicht der Produkte. Wenn ich nun domain.tld/de/online-shop/test eingebe, kommt die Fehlerhafte 404-Seite. Mit domain.tld/de/test kommt die korrekt funktionierende Fehlerseite. Contao 4.4.20, Isotope 2.5.1

**Comment by rflx** [comment]
Hallo zusammen
Bei mir genau gleich wenn ich den Produktleser auf einer separaten Seite setzte:

#### Seite mit Modul Produktliste
- [ ] Element erforderlich
- [x] Detailseite benutzen (Seite mit Modul Produktleser)

#### Seite mit Modul Produktleser
- [x] Element erforderlich
- [ ] Detailseite benutzen 

#### Modul Produktleser
- [x] Eine 404-Fehlerseite anzeigen

Der Fehler tritt auf wenn ich eine falsche Alias angebe bsp. `shop/it3m` anstatt `shop/item`. Bei Schrägstrich bzw. Slash `shop/item/` wird die übergeordnete Seite/Liste bsp. `shop` angezeigt jedoch bleibt die Adressleiste mit `shop/item/` bestehen.

Contao 4.7.4
Isotope 2.5.12

**Comment by cubex-hro** [comment]
Die 404 Seite im Produktreader wird noch über folgende Art und Weise generiert
https://github.com/isotope/core/blob/2.6/system/modules/isotope/library/Isotope/Module/ProductReader.php#L221

```
/** @var \PageError404 $objHandler */
$objHandler = new $GLOBALS['TL_PTY']['error_404']();
$objHandler->generate($objPage->id);
```

Ich habe es für mich folgendermaßen gelöst

`throw new PageNotFoundException('Page not found: ' . Environment::get('uri'));`

Bei Bedarf kann ich einen Pull Request machen damits in den Core kommt :)

**Comment by fritzmg** [comment]
Isotope is compatible with Contao 3 and that is the correct way of generating the 404 page.

**Comment by cubex-hro** [comment]
Oh my mistake I didn't even think about that anymore.

**Comment by aschempp** [comment]
Ich denke dieses Problem sollte mit den neusten Contao-Versionen behoben sein.
