### ISSUE TITLE
Unterscheidung Gastbestellung - normale Bestellung im Mail

### ISSUE THREAD

**Issue by Kahru** [isotope/core#1961]
Hallo,

ich würde gerne eine Gastbestellung markieren damit die Mitarbeiter des Shops in der Bestellemail gleich sehen können ob ein Gast oder ein registriertes Mitglied bestellt hat. Wenn ich versuche mit ##member_id## o.ä. den Typ herauszufinden, bekomme ich beim Gast da nichts zurück. ##member_*## wird beim Gast wohl nicht ausgewertet, sondern liefert einfach nur sich selbst zurück und ist damit für die IF-Abfrage nicht zu benutzen. Könntet ihr hier bitte ein Merkmal in die Intertags einbauen in die nächste Version oder habt ihr sonst noch eine Idee wie man das lösen könnte?

Gruss
Bernard

**Comment by aschempp** [comment]
Versuch es doch mal mit ##cart_member##. Ansonsten Fragen bitte direkt im Contao Community Forum (https://community.contao.org) stellen. Falls es keine Lösung gibt kannst du das Ticket gerne wieder öffnen.

**Comment by Kahru** [comment]
Hallo,

##cart_member## führt zu einer Fehlermeldung: 

> Die folgenden eingesetzten Tokens werden vom Notification-Typ nicht unterstützt: ##cart_member##.

Ich hatte mir letzte Woche schon anders beholfen. Ist halt leider nicht updatesicher. Die Order.php erweitert um

`// Add member fields
        if ($this->member > 0 && $this->getRelated('member') !== null) {
            foreach ($this->getRelated('member')->row() as $k => $v) {
                $arrTokens['member_' . $k] = Format::dcaValue($this->getRelated('member')->getTable(), $k, $v);
            }
        }
        //BG270718 Gastbestellung anzeigen
        else {
            $arrTokens['member_id']        = 'G';
        }`

und dann im Mail ein:
`{if member_id=="G"}Gastbestellung{endif}`
eingefügt

Bernard

**Comment by Toflar** [comment]
`collection_member` müsste es wohl sein.

**Comment by Kahru** [comment]
Das scheint zu gehen. Danke!
