### ISSUE TITLE
Darstellungsfehler Zahlungsinformationen PayPal (Plus)

### ISSUE THREAD

**Issue by Sukrams** [isotope/core#1963]
Hallo,

wenn PayPal Plus genutzt wird, werden die Zahlungsinformationen unschön dargestellt und das Layout ist zerschossen:

![paypal_iso1](https://user-images.githubusercontent.com/15678176/43576958-d72ad13e-964a-11e8-9318-8b677f42945d.png)
![paypal_iso2](https://user-images.githubusercontent.com/15678176/43576959-d745045a-964a-11e8-9e31-f01e4a03670c.png)
![paypal_iso3](https://user-images.githubusercontent.com/15678176/43576960-d75e246c-964a-11e8-907d-b2b52154ba2b.png)

**Comment by aschempp** [comment]
naja, es ist nicht zerschossen, es sind verschachtelte Informationen …

**Comment by Sukrams** [comment]
Aber sieht irgendwie auch unschön aus. Kann man da vielleicht irgendwie das abfangen?

**Comment by aschempp** [comment]
was willst du abfangen? Die Informationen nicht anzeigen? 😉

**Comment by Sukrams** [comment]
Vielleicht die Zeilen etwas schmaler machen? Aber das kommt vermutlich auch durch die Contao CSS?

**Comment by aschempp** [comment]
Korrekt
