### ISSUE TITLE
Attribut-Validierung sporadisch?

### ISSUE THREAD

**Issue by akroii** [isotope/core#1966]
Ich habe ein Contao 4 mit Isotope 2.5.1 welches auf php7.2 läuft.
Ich habe eine Vielzahl Attribute, bei denen sich der Endanwender durchklicken muss. Leider ist irgendwie die Validierung immer um ein Attribut verzögert bzw. übersprungen.
Also der Hinweis "Bitte füllen Sie das Feld xxx aus!" erscheint sporadisch.

Siehe hier:
![isotope](https://user-images.githubusercontent.com/8830861/44252804-bf1dd000-a1fd-11e8-9ca8-220f04dd8b2d.gif)

**Comment by aschempp** [comment]
Interessant 😂 
Verwendest du das Originaltemplate?

**Comment by akroii** [comment]
Es ist etwas abgewandelt. Aber der Teil mit den Attributen also:

```
                <?php if($this->hasOptions): ?>
                    <div class="options">
                        <?php foreach( $this->options as $arrOption ): echo $arrOption['html']; endforeach; ?>
                    </div>
                <?php endif; ?>
```

ist unverändert.

**Comment by aschempp** [comment]
Also see https://github.com/isotope/core/issues/1846
