### ISSUE TITLE
Attribute / Radio-Button-Menü / Optionen-Manager / Gruppe defekt

### ISSUE THREAD

**Issue by johannes-bittner** [isotope/core#1969]
Wenn man bei den Attributen ein Radio-Button-Menü anlegt und im Optionen-Manager Gruppen erstellt, so erscheinen bei den Produkten weder die Gruppen noch die jeweiligen Optionen: 

Attribut mit Radio-Button-Menü im Optionen-Manager: 
![grafik](https://user-images.githubusercontent.com/1597697/44578168-3a016080-a793-11e8-904f-b4346fbed111.png)

Ansicht beim Produkt:
![grafik](https://user-images.githubusercontent.com/1597697/44578195-4e455d80-a793-11e8-8c58-e10008eef92c.png)

Ist auch nicht ein einfaches CSS-Problem, weil Label und Optionen leer sind: 

![grafik](https://user-images.githubusercontent.com/1597697/44578245-6cab5900-a793-11e8-9e4d-6367fa09679d.png)

Contao 4.5.12
Isotope 2.5.1

**Comment by aschempp** [comment]
Gruppen funktionieren nur bei Select-Menü's (genau wie im Formulargenerator) und nur bei nicht-Varianten-Attributen (da bei Varianten-Attributen die Optionen ja entsprechend der Produktvarianten entfernt und sortiert werden).
