### ISSUE TITLE
[2.5.1] Versandkosten werden mal zwei gerechnet

### ISSUE THREAD

**Issue by williamsomerset** [isotope/core#1970]
Hallo liebes Isotope-Team,

Bbei GitHub gibt es das selbe Szenario leider ohne Ergebnis: https://github.com/isotope/core/issues/1920

Folgendes Problem besteht:

Wenn ich zwei Produkte mit unterschiedlichen Versandarten (in einer Versandgruppe) und unterschiedlichen Stückzahlen im Warenkorb habe und zur Auswahl der Versandoption komme, stimmen die Berechnungen der Versandgebühren dort nicht mehr.

Es wird die Summe aller Versandarten mal der Stückzahl der Produkte im Warenkorb berechnet. Was falsch ist.

Mit folgenden Aufbau kann man das Problem reproduzieren:

**Produkt 1**
Besitzt einen Produkttyp 1 dem wiederum nur eine Versandart (Versandart 1) zugewiesen ist.

**Produkt 2**
Besitzt einen Produkttyp 2 dem wiederum nur eine Versandart (Versandart 2) zugewiesen ist.

**Versandart 1**
Versandart-Typ: Pauschalpreis-Versand
Preis: 3 Euro
Pauschalpreis-Berechnung: Pro Stück
Länder: Deutschland
Produkttypen: Test-Produkttyp 1

**Versandart 2**
Versandart-Typ: Pauschalpreis-Versand
Preis: 5 Euro
Pauschalpreis-Berechnung: Pro Stück
Länder: Deutschland
Produkttypen: Test-Produkttyp 2

**Versandgruppe**
Hier sind beide Versandarten enthalten und die Gruppenberechnung ist auf „Summierter Preis der verfügbaren Versandarten“ gestellt. Diese Versandgruppe ist wiederum dem Kassen-Modul zugewiesen.

Anbei findet Ihr auch ein Bild des Problems.

Contao: 3.5.28
Isotope: 2.5.0 Build 3

<img width="1357" alt="bildschirmfoto 2018-08-20 um 19 48 42" src="https://user-images.githubusercontent.com/17226540/44991250-c4b43d80-af93-11e8-84a2-a176f10d7032.png">

**Comment by aschempp** [comment]
Versandarten können nicht über Produkttypen gruppiert werden, soweit ich es sagen kann ist solch eine Konfiguration aktuell nicht möglich.

**Comment by aschempp** [comment]
Duplicate of https://github.com/isotope/core/issues/1920

**Comment by richardhj** [comment]
@williamsomerset Bitte checke nochmal die Änderung in #1971.
