### ISSUE TITLE
Attribut Medienverwaltung mehrsprachig

### ISSUE THREAD

**Issue by mecintosch** [isotope/core#1973]
Wie ich sehe ist das Attribut nur in der Fallbacksprache verfügbar. Wie kann man das Attribut mehrsprachig nutzen?

**Comment by aschempp** [comment]
Wende dich für Fragen bitte an das Contao Community Forum (https://community.contao.org), das Ticketsystem ist für Bug-Reports und Feature-Requests.

**Comment by mecintosch** [comment]
Die Funktion ist ja scheinbar nicht implementiert - wäre also ein Feature-Request oder?

**Comment by aschempp** [comment]
Ich glaube schon dass das möglich ist, kann dir aber auswendig nicht gerade sagen wie…
