### ISSUE TITLE
Problem with Contao 4.6

### ISSUE THREAD

**Issue by plorenz-etes** [isotope/core#1974]
I've been using Contao 4.5.12 with Isotope 2.5.1 and didn't experience any problems. However, after upgrading to Contao 4.6.2 with Isotope 2.5.3 via composer, a strange problem occurred:

During the ordering process, everything works fine. On the last page of the order processing however (when finally placing the order by clicking the last button), the page just reloads. This cycle persists indefinitely, so it is not possible to finish placing the order. A downgrade back to the other versions helped.

Has compatibility with Contao 4.6 been completely tested yet?

**Comment by aschempp** [comment]
Which payment provider do you use? Have you checked your log files (both files and backend) if there is any error message?

**Comment by plorenz-etes** [comment]
The only accepted payment type is payment in advance, so there shouldn't be any issues I think. Unfortunately there were also no errors or other messages in the log file.

**Comment by aschempp** [comment]
I'm not aware of any "payment in advance" type, the regular Isotope "cash" module does not reload the page …?

**Comment by plorenz-etes** [comment]
Ah, the payment method is "cash", sorry! When viewing the last page of the payment process with the "order now" button (in German "Kostenpflichtig bestellen"). As soon as this button is pressed, the page just reloads instead of actually creating the order.

**Comment by aschempp** [comment]
Looks like someone/something is blocking the order. Maybe try disabling any extension…

**Comment by joeherold** [comment]
Same here. I realized that it is related to the embedded form. The funny part is, calling the checkout steps with app_dev.php works fine. But in productive mide it hangs.

May this be related to the $_Session stuff? Because without app_dev it is just like the form loads for the first time when you checked stuff before

**Comment by joeherold** [comment]
I guess I got the problem: Auto-clear the session form data
https://github.com/contao/core-bundle/pull/1550/files

I think it is, because in the step "process" all the POST data ist cleared. So in this step, the checkout steps are checked again, but this time all data is gone, so the review can not pass with the form, because the form asks for \Input::post("FORM_SUBMIT"), what is NULL

**Comment by joeherold** [comment]
@aschempp merci!

**Comment by joeherold** [comment]
@aschempp Hey Andreas,
I guess this was not the solution. If you take a look at OrderConditions Line 105
https://github.com/isotope/core/blob/master/system/modules/isotope/library/Isotope/CheckoutStep/OrderConditions.php#L105
you validate the form-field. The widget is validating against FORM_DATA, what is not available now.

I would add this line before the foreach loop (before Line 101):
```php
$_SESSION['FORM_DATA'] = is_array($_SESSION['CHECKOUT_DATA']) ? $_SESSION['CHECKOUT_DATA'] : array();
```
just tried it out in an installation and it works for me.

**Comment by aschempp** [comment]
Sorry about that issue. It has already been fixed in version 2.5.7 😇

**Comment by joeherold** [comment]
@aschempp perfect ☺️

**Comment by joeherold** [comment]
One more thing I was thinking about. Maybe the CHECKOUT_DATA should be unset after a successful checkout. So that the checkboxes are not set on the 2nd order

**Comment by aschempp** [comment]
That should already be the case.
https://github.com/isotope/core/blob/master/system/modules/isotope/library/Isotope/Model/ProductCollection/Order.php#L248

**Comment by joeherold** [comment]
Ah perfekt, did not realize this. THX Andi
