### ISSUE TITLE
permissions: translation for "miscellaneous" not working

### ISSUE THREAD

**Issue by fritzmg** [isotope/core#1975]
When editing the Isotope Module permissions, the translation for "miscellaneous" won't work (due to `:hide`, I think?).

![screenshot_2018-09-17 benutzergruppen gruppe id 21 bearbeiten - contao open source cms](https://user-images.githubusercontent.com/4970961/45622877-d0b8f880-ba85-11e8-8f8f-014c164c29df.png)

**Comment by aschempp** [comment]
Fixed in b143489ec508a4cd28515d4fde534413220e7915
