### ISSUE TITLE
Regeln & Gutscheine

### ISSUE THREAD

**Issue by patricklas** [isotope/core#1977]
![nav-fddf7b68](https://user-images.githubusercontent.com/43609285/46081209-40bd3200-c19c-11e8-923f-49076bd33271.png)

Hallo,
ich hab da ein merkwürdiges Problem nach der Installation von Isotope. Kann auch im Netz nichts darüber finden. Beim Screenshot oben wird das Menü dargestellt wie es sein soll. Laut Handbuch.

Die Regeln & Gutscheine werden bei mir aber nicht angezeigt. Habe auf die aktuelle Version aktualisiert. Trotzdem nichts. Das Menü im Backend schaut bei mir so aus:

<img width="217" alt="isotope_2 5 4" src="https://user-images.githubusercontent.com/43609285/46081328-8e399f00-c19c-11e8-95e0-71622053c716.png">

Habe Contao 3.5.35 frisch installiert und dann isotope. Die Erweiterungen die isotope braucht sind auch alle drauf. Alle aktuell. Kann auch im Handbuch nichts finden.

Vielleicht könnt ihr mir da kurz weiterhelfen?
Woran könnte das liegen?

Lg, Patrick

**Comment by aschempp** [comment]
Du hast die Erweiterung vermutlich deaktiviert. Bitte wende dich an das Contao Community Forum (https://community.contao.org) für Support-Fragen.
