### ISSUE TITLE
Eigenschaften eines bestellten Produktes werden nicht richtig an PayPal weitergegeben.

### ISSUE THREAD

**Issue by michb** [isotope/core#1979]
In einem Shop werden Produkte verkauft, die Varianten und gleichzeitig ein im Frontend wählbare Option haben.
Beides ist angelegt als Select-Menü über den Options-Manager.
Es wurde auch ein Update auf die aktuelle Isotope Version 2.5.4 gemacht.

Im PayPal wird dann bei einer Eigenschaft als ausgewählte Option "Array" angezeigt.

**Als Beipsiel:**
ich hab ein Produkt im Warenkorb und machen den Checkout durch lasse mir dann in Zeile 145
https://github.com/isotope/core/blob/a4aaa3792d2cecb69a12570a60f266d588242a4b/system/modules/isotope/library/Isotope/Model/Payment/Paypal.php#L137-L145

```php
echo "<pre>".print_r($arrData,1)."</pre>";
die();
```
ausgeben erhalte ich 
```php
Array
(
    [item_number_1] => 990
    [item_name_1] => ... (Menge: 250 Gramm, Mahlgrad: Array)
    [amount_1] => 5.40
    [quantity_1] => 1
)
```
Ursache des Problems liegt in
https://github.com/isotope/core/blob/a4aaa3792d2cecb69a12570a60f266d588242a4b/system/modules/isotope/library/Isotope/Isotope.php#L544

hier findet die Zuordnung statt, die dann aus dem Array ein String machen sollte. Dies geschieht auch, aber in

https://github.com/isotope/core/blob/a4aaa3792d2cecb69a12570a60f266d588242a4b/system/modules/isotope/library/Isotope/Isotope.php#L559

ist es dann wieder ein Array.

**Comment by aschempp** [comment]
Wer sollte `formatProductConfiguration` denn aufrufen? Das finde ich nirgends im PayPal-Modul?

**Comment by michb** [comment]
Also der Ablauf ist so:
https://github.com/isotope/core/blob/a4aaa3792d2cecb69a12570a60f266d588242a4b/system/modules/isotope/library/Isotope/Model/Payment/Paypal.php#L123

https://github.com/isotope/core/blob/a4aaa3792d2cecb69a12570a60f266d588242a4b/system/modules/isotope/library/Isotope/Model/ProductCollectionItem.php#L257

https://github.com/isotope/core/blob/a4aaa3792d2cecb69a12570a60f266d588242a4b/system/modules/isotope/library/Isotope/Isotope.php#L507

**Comment by aschempp** [comment]
Ich gehe davon aus dass dieses Problem mittlerweile erledigt ist.
