### ISSUE TITLE
Individuelles Template für "mod_iso_relatedproducts" nicht auswählbar

### ISSUE THREAD

**Issue by toblr** [isotope/core#1984]
**Hallo!**

Ich hatte gerade den Fehler, dass ich leider kein individuelles Template für ```mod_iso_relatedproducts``` im Modul **"Ähnliche Artikel"** auswählen konnte.

Nach kurzem Rumprobieren und Überlegen bin ich auf die Idee gekommen, einfach `mod_iso_productlist` zu kopieren, auf `mod_iso_relatedproducts` umzubenennen und siehe da, ich konnte es auswählen. 

Contao 4 blockiert ja das Auswählen von anderen, nicht stimmigen Templates für Module. In Contao 3 war ja das Auswählen von z.B. `ce_text` für `ce_image` möglich.

Leider liefert Isotope von selbst kein `mod_iso_relatedproducts`-Template mit, was natürlich gewissermaßen keinen Sinn macht, aber dennoch für manche ein Problem darstellen könnte, sollten diese nicht auf dieselbe Idee kommen.

Wäre ein kleiner Vorschlag von meiner Seite!

**Comment by aschempp** [comment]
Das ist wirklich blöd, aber ich wüsste nicht was wir da tun wollen. Für Related Products wird das normale Listentemplate verwendet, das zu dupliziere nur damit eine Auswahl erscheint macht ja auch wenig Sinn?

**Comment by manjarco** [comment]
Gleiches gilt übrigens auch für `mod_iso_productvariantlist`

Auch, wenn dadurch Duplikate von Templates entstehen wären diese wahrscheinlich am nutzerfreundlichsten. Oder es gibt eine Möglichkeit auch "unpassende" Templates von Entwickler-Seite aus für bestimmt Module frei zu geben!?

**Comment by fritzmg** [comment]
Du müsstest zumindest nicht den Inhalt duplizieren, wenn du im Template einfach nur
```php
$this->extend('mod_iso_productlist');
```
schreibst.

**Comment by codesache** [comment]
Hallo Andreas,
das Problem habe ich auch mit einem Projekt das ich übernommen habe, in dem das Template mod_iso_list_related.html5 um Bootstrap CSS Klassen in der foreach erweitert wurde.

An der Stelle macht es schon Sinn genau das TPL anzupassen!

Getestet habe ich es auch in einer anderen C4.4.x bei dem auch die Auswahl nicht möglich ist.

Falls ich was für euch testen soll, lass es mich wissen.

Viele Grüße

Markus

**Comment by fredigut** [comment]
Ich habe ein ähnliches Problem mit der Auswahl von Templates in verschiedenen isotope-Modulen (**Contao 4.8.1 und Istope 2.6**). Wenn ich beispielsweise als  Modul eine einfache Produktliste erstelle, sehe ich bei  «Produklisten-Template» nicht, welches Template von isotope verwendet wird. Erst wenn ich das Template dupliziere und in meinem Fall umbenenne  (dazu muss ich in einer alten Version erst nachschauen, welches Template überhaupt verwendet wird -> iso_list_default), ist es  im Klappmenu auswählbar (umbannt zu-> iso_list_default_wuc). Das ähnliche Problem habe ich auch bei andern Isotope-Modulen bzw. Templates.
<img width="519" alt="Bildschirmfoto 2019-09-15 um 16 57 55" src="https://user-images.githubusercontent.com/42616484/64923483-7bb7db80-d7da-11e9-9a4c-785ca630a7f7.png"> Oder mache ich da eine Denkfehler?

**Comment by fritzmg** [comment]
Aktualisiere auf Contao 4.8.3.

**Comment by fredigut** [comment]
Vielen Dank für den guten Tipp! Ich habe das Update auf Contao 4.8.3 installiert. Nun werden die Templates korrekt angezeigt! Perfekt!

**Comment by JessesNei** [comment]
Contao 4.8.4
Isotope 2.6

Im Frontend Modul (z. B. Product Reader oder Order Details ) sind die Templates für das Modul nach der Erstellung und Platzierung im entsprechenden in der Shopconfig hinterlegten Templates- Ordner im Feld 'custom module template' nicht auswählbar, da diese nicht angezeigt werden.

![Screenshot 2019-10-10 at 09 05 13](https://user-images.githubusercontent.com/21311184/66546403-3bc7e800-eb3d-11e9-9e96-695e18b49766.png)
![Screenshot 2019-10-10 at 09 04 50](https://user-images.githubusercontent.com/21311184/66546404-3bc7e800-eb3d-11e9-83d3-e56d42307444.png)

**Comment by akroii** [comment]
@JessesNei versuch einmal das Template direkt in das `templates`-Verzeichnis (also unter Unterverzeichnis direkt in den Ordner templates rein) hineinzuverschieben.
Irgendwie habe ich da in letzter Zeit Probleme 🤷‍♂️

**Comment by aschempp** [comment]
This issues has been fixed in Contao 4.9. Since Isotope 2.8 will only support Contao 4.9+, I'm closing this ticket.
