### ISSUE TITLE
Isotope Kassenmodul - Checkout Steps überspringen - Kaufen Button fehlt bzw. falscher Name

### ISSUE THREAD

**Issue by sgei** [isotope/core#1986]
Contao: 3.5.36
Isotope: 2.5.7

Ich habe aktuell das Problem, dass bei einem verkürzten Checkout der "Kaufen" Button nicht angezeigt wird. bzw. wird ein "Weiter" Button angezeigt, der aber als Kaufen-Button funktioniert.

Also,

Wenn ich im Kassenmodul einstelle, dass lediglich die hinterlegte Mitgliederadresse als Rechnungsadresse verwendet werden soll und der Rest ist vom Kunden wählbar, dann werden alle 4 Steps angezeigt und ich sehe auf der Zusammenfassungsseite auch den Kaufen-Button:

Kassenmodul:
![isotope_kasse_02-1](https://user-images.githubusercontent.com/2803995/46905907-a6c6ea80-cefa-11e8-87c4-9b0e1c96fadd.jpg)
Shop-Frontend:
![isotope_kasse_02-2](https://user-images.githubusercontent.com/2803995/46905908-a6c6ea80-cefa-11e8-9c3e-5ecc24227bd9.jpg)

Da ich aber nur per Mail verschicke brauche ich keine Versandadresse wählen zu lassen. Des Weitern gibt es nur eine Versandoption und eine Zahlungsoption.
Wähle ich alle Punkte im Kassenmodul an, dann werden diese Checkout-Steps auch übersprungen und ich lande gleich auf der Bestellzusammenfassung.

**ABER:** Der Kaufen-Button ist nicht da. Allerdings wird ein "Weiter"-Button angezeigt, der bei Klick die Bestellung auslöst.

Kassenmodul:
![isotope_kasse_01-1](https://user-images.githubusercontent.com/2803995/46905905-a6c6ea80-cefa-11e8-93b0-06151436f022.jpg)
Shop-Frontend:
![isotope_kasse_01-2](https://user-images.githubusercontent.com/2803995/46905906-a6c6ea80-cefa-11e8-8505-450a6e5129f7.jpg)

Steffen

**Comment by aschempp** [comment]
Der Fehler ist in der 2.5.8 behoben.
