### ISSUE TITLE
Contao 3.5.36, isotope 2.5.7, Buchung erzeugt doppelte Adressbuch Einträge

### ISSUE THREAD

**Issue by sgei** [isotope/core#1987]
Hallo,

es wird bei jeder Bestellung ein neuer Eintrag in der tl_iso_address erzeugt, auch wenn die Adresse schon vorhanden ist.

Getestet habe ich mit verschiedenen Einstellungen im Kassenmodul.

![2018-10-14_11h18_08](https://user-images.githubusercontent.com/2803995/46914813-ddf0d680-cfa2-11e8-886f-8f3c9a2e5550.png)

Wähle ich Mitgliederadresse als Rechnungsadresse und Versandadresse (siehe Bild oben), dann wird die Adresse bei jeder Bestellung in die tl_iso_address geschrieben, sie ist aber nicht im Kunden-Adressbuch sichtbar:

![2018-10-14_11h21_14](https://user-images.githubusercontent.com/2803995/46914846-45a72180-cfa3-11e8-89c2-0690388aa409.png)

Stelle ich das Kassenmodul so ein:

![2018-10-14_11h22_12](https://user-images.githubusercontent.com/2803995/46914867-7c7d3780-cfa3-11e8-90e4-c146d7478bf4.png)

Wird im Checkout die Mitgliederadresse gezogen und jetzt zweifach in der tl_iso_address abgespeichert:

![2018-10-14_11h27_31](https://user-images.githubusercontent.com/2803995/46914900-468c8300-cfa4-11e8-892e-ebbdb1a99536.png)

Im Kundenadressbuch ist sie jetzt sichtbar...

![2018-10-14_11h29_04](https://user-images.githubusercontent.com/2803995/46914907-66bc4200-cfa4-11e8-8a4b-6dee22e5fbdb.png)

Steffen

**Comment by aschempp** [comment]
Das ist korrekt, die Adressen werden dupliziert damit sich die Bestellung nicht ändert wenn ein Kunde seine Adresse editiert. Daher auch die unterschiedliche `ptable`.
