### ISSUE TITLE
Zahlungsart Viveum - vorausgewählte Zahlungsart - wie bei Postfinance

### ISSUE THREAD

**Issue by mecintosch** [isotope/core#1991]
Viveum und Postfinance greifen im Hintergrund auf das selbe System zu. In Isotope kann man bei Postfinance eine Zahlugsart vorauswählen damit man nach dem Check-Out direkt zur Zahlungsseite von Visa, Mastercard, Sofort usw. gelangt. Diese Funktion ist bei Viveum nicht integriert obwohl sie hier genauso funktioniert.

Eine quick and dirty Änderung im Postfinance Modul hat genügt und ich kann die Funktion auch über Viveum nutzen.

Habe lediglich in der Datei iso_payment_postfinance.html5 das Form Action von

> https://e-payment.postfinance.ch/ncol/<?= ($this->debug ? 'test' : 'prod') ?>/orderstandard_utf8.asp

auf 

> https://viveum.v-psp.com/ncol/<?= ($this->debug ? 'test' : 'prod') ?>/orderstandard_utf8.asp

geändert.

Vielleicht lässt sich die Funktion auch direkt in Viveum integrieren?!

**Comment by aschempp** [comment]
The field has been added in 2.5.8

**Comment by mecintosch** [comment]
Super dass das umgesetzt wurde.

Hier die aktuelle Liste der Zahlungsarten die vorausgefüllt werden können. 
[VIVEUM.pdf](https://github.com/isotope/core/files/2510728/VIVEUM.pdf)

```
    public function getPaymentMethods()
     {
         return array(
             'CreditCard__American_Express'          => 'CreditCard - American Express',
             'CreditCard__Billy'                     => 'CreditCard - Billy',
             'CreditCard__CB'                        => 'CreditCard - CB',
             'CreditCard__Diners_Club'               => 'CreditCard - Diners Club',
             'CreditCard__JCB'                       => 'CreditCard - JCB',
             'CreditCard__MaestroUK'                 => 'CreditCard - MaestroUK',
             'CreditCard__MasterCard'                => 'CreditCard - MasterCard',
             'CreditCard__VISA'                      => 'CreditCard - VISA',
             'EPS__EPS'                              => 'EPS',
             'PAYPAL__PAYPAL'                        => 'PayPal'
             'paysafecard__paysafecard'              => 'Paysafecard',
             'PostFinance_Card__PostFinance_Card'    => 'PostFinance Card',
             'DirectEbanking__Sofort_Uberweisung'    => 'Sofortüberweisung DE',
             'DirectEbanking__DirectEbankingAT'      => 'Sofortüberweisung AT',
             'DirectEbanking__DirectEbankingBE'      => 'Sofortüberweisung BE',
             'DirectEbanking__DirectEbankingCH'      => 'Sofortüberweisung CH',
             'DirectEbanking__DirectEbankingFR'      => 'Sofortüberweisung FR',
             'DirectEbanking__DirectEbankingGB'      => 'Sofortüberweisung GB',
             'DirectEbanking__DirectEbankingIT'      => 'Sofortüberweisung IT',
             'DirectEbanking__DirectEbankingNL'      => 'Sofortüberweisung NL'
      );
    }
```

**Comment by aschempp** [comment]
Funktionieren die denn auch bei Postfinance?

**Comment by mecintosch** [comment]
Die Einträge sind von Postfinance übernommen, habe nur einige Zahlungsarten ergänzt.
Müssten also bei Viveum und Postfinance funktionieren.

Kann gerne testen! (Viveum)
