### ISSUE TITLE
postsale.php: "This exception has no message. Use $exception->getResponse() instead"

### ISSUE THREAD

**Issue by richardhj** [isotope/core#1993]
Hi,
on the postsale request, the following error gets logged.
https://sentry.io/share/issue/3cad708238e14c80bcb5ba58fd020553/
It is running nonetheless.

**Comment by aschempp** [comment]
Well that's supposed to be there? Is there an actual error?

**Comment by richardhj** [comment]
Looks correct. Sentry must not be catching this. Closing this.

**Comment by aschempp** [comment]
FYI here's what my sentry config looks like (might be outdated though):

```
sentry:
    skip_capture:
        - Contao\CoreBundle\Exception\PageNotFoundException
        - Contao\CoreBundle\Exception\AccessDeniedException
        - Contao\CoreBundle\Exception\InvalidRequestTokenException
        - Lexik\Bundle\MaintenanceBundle\Exception\ServiceUnavailableException
        - Symfony\Component\HttpKernel\Exception\NotFoundHttpException
        - Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException
        - Symfony\Component\HttpKernel\Exception\ServiceUnavailableHttpException
        - Contao\CoreBundle\Exception\InternalServerErrorHttpException
```

**Comment by richardhj** [comment]
Thanks. Haven't had to opt out that exceptions til now :-)

**Comment by fritzmg** [comment]
I also noticed that `ResponseException`s from the `postsale.php` are reported to Sentry. What I don't get though is, why it only happens there. Any `ResponseException`s from within Contao itself are not reported to Sentry - and I don't really get the difference.

**Comment by richardhj** [comment]
https://github.com/isotope/core/blob/f080efc8ca544243963a2a8c5dbaa00d1fc2b60f/system/modules/isotope/postsale.php#L180
My guess:
The ResponseExceptions becomes caught (this is what the Contao Core does with those exceptions, i.e. PrettyErrorScreenListener and the like). But then, this exception will be thrown again, and the Contao listener on this exception does not have any impact.

**Comment by fritzmg** [comment]
> Second guess: It is outside of the scope of the exception listeners?

Must be. But that would also mean, that within Contao 4, the `postsale.php` isn't actually sending these responses?

**Comment by aschempp** [comment]
Looks like a bug in Contao to me. Can both of you try if https://github.com/contao/contao/pull/525 fixes the issue?

**Comment by fritzmg** [comment]
Looks good, found no issues so far 👍

**Comment by richardhj** [comment]
Closing in favor of contao/contao#525.
