### ISSUE TITLE
Isotope Nach Umstellung auf PHP 7.2 Datenbank nicht aktualisierbar 

### ISSUE THREAD

**Issue by markush2** [isotope/core#1995]
Hallo.

Ich stelle gerade eine Seite auf PHP 7.2 um.
Alles klappt soweit ganz gut, auch das Isotope.

Allerdings läßt sich eine Spalte in der Tabelle nicht aktualisieren: ALTER TABLE `tl_iso_product_collection` ADD UNIQUE KEY `uniqid` (`uniqid`);

Wenn ich das im Backend oder auch im Install-Tool probiere, bekomme ich folgende Fehlermeldung:
```Fatal error: Uncaught exception Exception with message Query error: Duplicate entry 'WG-7-5bdf1400373408.00506545' for key 'uniqid' (ALTER TABLE `tl_iso_product_collection` ADD UNIQUE KEY `uniqid` (`uniqid`);) thrown in system/modules/core/library/Contao/Database/Statement.php on line 295```

``` #0 system/modules/core/library/Contao/Database.php(207): Contao\Database\Statement->query('ALTER TABLE `tl...')
#1 system/modules/repository/classes/RepositoryManager.php(477): Contao\Database->query('ALTER TABLE `tl...')
#2 system/modules/repository/classes/RepositoryBackendModule.php(153): RepositoryManager->update('database')
#3 system/modules/core/classes/BackendModule.php(98): RepositoryBackendModule->compile()
#4 system/modules/repository/classes/RepositoryBackendModule.php(72): Contao\BackendModule->generate()
#5 system/modules/repository/classes/RepositoryManager.php(57): RepositoryBackendModule->generate()
#6 system/modules/core/classes/Backend.php(423): RepositoryManager->generate()
#7 system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('repository_mana...')
#8 contao/main.php(20): Contao\BackendMain->run()
#9 {main}` ```

Die Abfrage 
```SELECT * FROM tl_iso_product_collection WHERE uniqid = 'WG-7-5bdf1400373408.00506545';```

gibt folgendes Ergebnis:
```127.0.0.1/web194_db2/tl_iso_product_collection/		https://s163.goserver.host/phpmyadmin5/db_qbe.php?db=web194_db2
 Zeige Datensätze 0 -  0 (1 insgesamt, Die Abfrage dauerte 0.0025 Sekunden.)

SELECT * FROM tl_iso_product_collection WHERE uniqid = 'WG-7-5bdf1400373408.00506545';



1478	1541346311	order	0	1541346311	0	[BLOB - 295 B]	[BLOB - 991 B]	NULL	NULL	1477	WG-7-0532	WG-7-5bdf1400373408.00506545	2	NULL	NULL	2	1	8	1252	1252	9.60	8.06	19.40	16.30	EUR	de	NULL` ```

**Comment by aschempp** [comment]
Ich kann mir nicht erklären warum der Fehler auftritt wenn es nur einen Datensatz dazu gibt. Kannst du mal (mit einer Kopie der Datenbank!!) versuchen alle Daten zu löschen, den Key anzulegen, und dann die Daten wieder zu importieren?

**Comment by aschempp** [comment]
Ich schliesse dies vorerst mangels Feedback. Gerne wieder öffnen wenn du meine Frage beantworten kannst.
