### ISSUE TITLE
Keine Übernahme von Gutscheincodes nach Login

### ISSUE THREAD

**Issue by webmarketiere** [isotope/core#1998]
Moin zusammen,

nachdem wir bereits diverse Shops mit Istope erfolgreich umgesetzt haben, die ohne das Marketinginstrument Gutscheine arbeiten, haben wir jetzt eine Kundin, die die Gutscheinfunktion benötigt. Dabei ist herausgekommen, dass unabhängig von Browser die Gutscheine nach Login nicht übernommen werden. 

Mein Anliegen habe ich bereits im Contao-Forum gepostet: [https://community.contao.org/de/showthread.php?72643-Gutscheincode-wird-bei-Login-nicht-%C3%BCbertragen&highlight=gutschein](url)

Beim Aufsetzen einer Testumgebung ist dann aufgefallen, dass das Gutscheinfeld gar nicht ohne weiteres sichtbar gemacht werden kann. Auch aus den Templates kann man keine richtigen Rückschlüsse ziehen.

Beitrag hier: [https://community.contao.org/de/showthread.php?72705-Gutscheinfeld-im-Warenkorb](url)

Nach Durchsicht des Contao-Forums ist mir dann aufgefallen, dass dieses Problem schon sehr oft aufgetreten ist und nie behandelt wurde. 

Verwendet wird Contao 3.5.31 und Isotope 2.5.9

**Comment by arboc** [comment]
Auch wir haben das Problem:
Wird ein Gutscheincode vor dem Login eingegeben, ist er nach dem Login nicht mehr vermerkt und muss neu eingegeben werden.

Das ist in sofern ärgerlich, da der Gutscheincode beim Warenkorb eingegeben wird, und der Login später im Checkoutprozess erfolgt. Der Kunde glaubt, alles ist ok und stellt dann auf der ketzten Seite im Checkout fest, dass der Code fehlt. Oftmals wird es auch hier übersehen, und dann erfolgt eine Reklamation. 

Das ist für alle sehr ärgerlich. 

Tritt auf bei Contao 4.4.31 und Isotope 2.5.9
