### ISSUE TITLE
Current category page not used for jumpTo of product list

### ISSUE THREAD

**Issue by rabauss** [isotope/core#2000]
Why is the desired behavior that in scope 'current_category' of product list the current category page for jumpTo  is not used? Instead in this scope the page of first product category is always used!

https://github.com/isotope/core/blob/43c5c3d7aae9072d6ed2e107fdaf7d12ec618e6e/system/modules/isotope/library/Isotope/Module/Module.php#L219

This behavior is not useful, if the product is in multiple categories and you want to keep the trail of page tree while jumping to product detail! At the moment I am considering to disable this option with another module parameter.

**Comment by aschempp** [comment]
I think you can currently only have one reader page in Isotope, because the system tries to prevent duplicate content. I have learned however that there is no duplicate content on the same page, and this could probably be solved with according meta tags anyway…

**Comment by aschempp** [comment]
This will be changed in 2.6
