### ISSUE TITLE
Produktvariantliste: Sortierung funktioniert nicht mit "alle Kategorien"

### ISSUE THREAD

**Issue by sebssch** [isotope/core#2001]
![themes magna sweets frontend-module modul id 63 bearbeiten - contao open source cms 2018-12-05 15-11-57](https://user-images.githubusercontent.com/18069290/49519075-75d2b880-f8a0-11e8-8072-ca4e102e7ade.png)

Wenn man bei der Produktvariantliste `Alle Kategorien` (1 im Bild) ausgewählt hat greift die Sortierung nicht. Sobald man auf die Einstellung `Aktive Kategorie`(2 im Bild) umschaltet und die Produkte richtig zuweist funktioniert die Sortierung wie gewünscht.

**Comment by aschempp** [comment]
Das ist richtig. Die manuelle Sortierung erfolg pro Seite. Bei "Alle Kategorien" werden mehrere Seiten gleichzeitig dargestellt, da gibt es keine Sortierung.

**Comment by sebssch** [comment]
@aschempp Vielen Dank für die Info.

**Comment by Xirdion** [comment]
Es wurde nun das Modul so angepasst, dass nur noch eine Kategorie verwendet wird. (alle Produkte, die gefunden werden sollen, haben diese Kategorie zugewiesen bekommen)
Trotzdem greift die Sortierung für die Produkte nicht.
![module](https://user-images.githubusercontent.com/17783055/50955625-ebdac880-14b9-11e9-989e-8ebf56378f82.png)
___
Contao-Version: 4.4.32
Isotope-Version: 2.5.10

Ich bin den Code soweit durchgegangen bis dahin, wo die Produkte eigentlich sortiert werden sollten.
Das geschieht ja in `system/modules/isotope/library/Isotope/Module/Product` in der Funktion `protected static function find()` in Zeile 567 (`call_user_func_array('array_multisort', $arrParam);`).

`$arrParam` ist bei uns folgendermaßen aufgebaut:
```
0 => Array mit den Namen der Produkte
1 => 4 (= SORT_ASC)
2 => 0 (= SORT_REGULAR)
3 => Array mit den Product-Models
```
Mit `array_multisort` könnte ohne Probleme die Liste der Namen sortiert werden, aber die Liste der Produkte wird nicht sortiert (`return = false`)

- ein Teil der Liste der Produktnamen, nach denen Sortiert werden soll:
![list](https://user-images.githubusercontent.com/17783055/50955926-a36fda80-14ba-11e9-8ae9-60ab12bffcc4.png)

- gefundene Produkte, die sortiert werden sollen:
![screenshot from 2019-01-10 09-17-46](https://user-images.githubusercontent.com/17783055/50955939-b4b8e700-14ba-11e9-81f2-1ffe34b25e47.png)

---
@aschempp 
Haben wir hier noch einen Fehler in der Konfiguration des Moduls? Oder funktioniert in diesem Fall die Sortierung der Produkte nicht?

**Comment by aschempp** [comment]
Should be fixed in 8ef050604e9dfc312d15e7a1ba898e3dbc6c0c95
