### ISSUE TITLE
DHL - united kingdom address

### ISSUE THREAD

**Issue by gebi84** [isotope/core#2005]
there is a bug, when using a street_1 like 

> 11 Dene Hill

So the code from 
system/modules/isotope/library/Isotope/EventListener/DHLBusinessCheckoutListener.php
createPerson()

> $person->setFullStreet($address->street_1);
returns NULL

the Method setFullStreet ist marked as deprecated and buggy:
https://github.com/Petschko/dhl-php-sdk/blob/bcb64adc548ce7cd0ef161d885f6b36c98601a7f/includes/Address.php#L334

my temporary fix is to reset the streetName and set the required field streetNumber to .

```php
$person->setFullStreet($address->street_1);

if(!$person->getStreetName()) {
	$person->setStreetName($address->street_1);
	$person->setStreetNumber('.');
}
```

**Comment by aschempp** [comment]
Interesting issue. Looks like the Isotope address form is not compatible with DHL?

**Comment by gebi84** [comment]
yes, becaus, dhl needs street and strettnr separate. But here is no logic for extracting a adress from 1 string for all addresse over the world ;-)

**Comment by Petschko** [comment]
The function `setFullStreet` is deprecated, because of the issue with different address formats

See here: https://github.com/Petschko/dhl-php-sdk/blob/master/includes/Address.php#L325
