### ISSUE TITLE
SVGs not working in product edit form

### ISSUE THREAD

**Issue by fritzmg** [isotope/core#2008]
When uploading SVGs for a product, they are not shown in the edit view:

![screenshot_2019-01-12 produkte produkt id 94 bearbeiten - contao open source cms](https://user-images.githubusercontent.com/4970961/51073543-af060180-1672-11e9-86ee-7e0e859ee1a9.png)

However, they do work fine everywhere else, e.g. the back end product listing and the front end.

**Comment by aschempp** [comment]
fixed in 962fd35b19a7a5c54736ad4f2800a4b26dfb9e61
