### ISSUE TITLE
ProductCollection::updateDatabase not executed when custom surcharge present

### ISSUE THREAD

**Issue by fritzmg** [isotope/core#2011]
I am not sure if this might be a bug somewhere within Isotope - or if I am setting up my own surcharge in the wrong way.

I am adding a custom surcharge via the `findSurchargesForCollection` Isotope hook. This works fine for the cart, my surcharge is displayed correctly there.

However, during checkout, when I select the the payment method (shipping is skipped in my case), I am first redirected from `checkout/payment` to `checkout/confirm` - but then redirected back to `checkout/payment`. Looking at the database I can see that the payment method was never actually saved into the cart collection.

So, when submitting the POST request for `checkout/payment`, the payment method will be stored in the cart collection object and thus Isotope thinks everything is fine with the checkout step - but for some reason, the change is never committed to the database. And thus the following step simply redirects back to the payment step again.

This only happens when my custom surcharge is added via the aforementioned hook. Upon further inspection it looks like `ProductCollection::updateDatabase` which is registed via `register_shutdown_function` is never actually executed and thus the payment information gets lost for the next step. However, I have no idea why this is happening.

I have created a gist here, showing the way I implemented the surcharge. It should be the most simple way to integrate a general, custom surcharge: https://gist.github.com/fritzmg/ac2d919c261c94b12d36eb18af5e9670

_Note:_ in reality there is of course a condition for adding the surcharge within the `findSurchargesForCollection` hook.

* Contao 4.6.14
* Isotope 2.5.10

**Comment by aschempp** [comment]
How is a custom surcharge related to the payment method??

**Comment by aschempp** [comment]
Except for something like limiting the payment to the cart total, which might change when adding the surcharge?

**Comment by fritzmg** [comment]
> How is a custom surcharge related to the payment method??

It isn't. I don't know why the aformentioned thing happens. I only know that, when the surcharge is present, the collection is not committed to the database on the payment method step. For some reason, the collection is not saved via the `register_shutdown_function`.

**Comment by fritzmg** [comment]
Yeah - it had nothing to do with the surcharge itself.

However, I found out that, whenever I access the session in the `findSurchargesForCollection`, the problem occurs. So something as simple as
```php
<?php

use Isotope\Model\ProductCollection;
use Symfony\Component\HttpFoundation\Session\Session;

class MySurcharge
{
    protected $session;

    public function __construct(Session $session)
    {
        $this->session = $session;
    }

    public function findSurchargesForCollection(ProductCollection $collection): array
    {
        $this->session->has('foo');
        return [\MySurchargeModel::build()];
    }
}
```
breaks the saving of the payment in the collection - for some reason -_-

I also noticed that the hook is executed twice within the same request, even when I put an `exit` there. As if there is another sub request - though I am not sure which component would trigger a sub request (and subsequently would trigger this hook).

**Comment by fritzmg** [comment]
Yeah, accessing the session within the `findSurchargesForCollection` hook does not work. It will lead to the following exception:
```
Failed to start the session because headers have already been sent by "vendor\symfony\http-foundation\Response.php" at line 363.
```
As a work around one can either use
```php
if (headers_sent()) {
    return [];
}
```
within the hook, or catch any `\RuntimeException` when accessing the session:
```php
try {
    if (!$this->session->has('…')) {
        // …
    }
} catch(\RuntimeException $e) {
    // …
}
```
