### ISSUE TITLE
"Produktpreis Versand" rechnet falsch

### ISSUE THREAD

**Issue by manjarco** [isotope/core#2012]
Der Versandart-Typ "Produktpreis Versand" berechnet nur die Versandkosten für das Produkt mit dem höchsten Gesamt-Versand-Preis.

Warenkorb-Beispiel:
4 x Produkt mit je 2€ Versand
2 x Produkt mit je 10€ Versand
Müsste als Versandkosten 28€ ergeben
Angezeigt werden aber 20€

Contao 4.4.32
Isotope 2.5.10

**Comment by aschempp** [comment]
Du hast gesehen dass man die Berechnung entsprechend auf Produkttypen einschränken kann? Mit einem Screenshot deiner Konfiguration könnte ich mehr sagen.

**Comment by manjarco** [comment]
Das habe ich gesehen und ist nicht angewendet. 

Hier die Konfiguration:

![produktpreis-versand-config](https://user-images.githubusercontent.com/274524/51825498-31362d00-22e5-11e9-835c-401a70f92e00.jpg)

Ich habe das Ganze gerade auch mit einer frischen C 4.4 / Iso 2.5 Installation reproduzieren können.

**Comment by manjarco** [comment]
Falls es einen Unterschied macht: ich konnte das Verhalten sowohl bei Produkten mit als auch ohne Varianten feststellen.

**Comment by aschempp** [comment]
Ich habe gerade im Code nachgesehen, und die Berechnung ist tatsächlich absichtlich so. So richtig erklären kann ich mir das auch nicht… ausser dass man eben ggf. den höchsten Versandpreis aller Produkte nehmen möchten. 🤔
