### ISSUE TITLE
Fehler bei Bestellungen mit vom Versand ausgeschlossenen Produkten

### ISSUE THREAD

**Issue by Mynyx** [isotope/core#2014]
Bei Bestellungen, die ausschließlich vom Versand ausgeschlossene Produkte enthalten, wird in tl_iso_product_collection dennoch in der Spalte shipping_address_id statt "0" jeweils eine ID gespeichert, die darüber hinaus in der Tabelle tl_iso_address nicht existiert.

Im Bestellablauf treten keine Auffälligkeiten auf, auch der Abschnitt Versandadresse wird in der Kasse korrekterweise nicht angezeigt.

**Comment by aschempp** [comment]
Kann es sein dass die ID der Rechnungsadresse gespeichert wird? Bezieht sich deine Aussage auf die Bestellung oder den Warenkorb-Datensatz?

**Comment by Mynyx** [comment]
Das Problem bezieht sich auf Bestellungen (type = order). Es handelt sich nicht um die ID der jeweiligen Rechnungsadresse, sondern um andere IDs, die in der Tabelle tl_iso_address nicht existieren.

**Comment by aschempp** [comment]
Dann ist es vermutlich die ID welche die Rechnungsadresse zuvor im Warenkorb hatte 🤔

**Comment by aschempp** [comment]
Fixed in f3efe36f2be2f3879812a6d952b58e5370cbc0ba
