### ISSUE TITLE
Konfigurationen bearbeiten: In Liste Staat wird erster Eintrag anstatt Default-Eintrag "-" ausgewählt

### ISSUE THREAD

**Issue by Mynyx** [isotope/core#2015]
Beim Bearbeiten einer Konfiguration (Shop-Konfiguration -> Allgemeine Einstellungen -> Konfigurationen) wird nach der Auswahl eines Landes automatisch der erste Eintrag in der Liste Staat ausgewählt (zum Beispiel bei Deutschland dann Baden-Württemberg oder bei China dann Beijing) statt dem Default-Eintrag "-".

**Comment by aschempp** [comment]
Dies ist/war ein Fehler in der Abhängigkeit "conditionalselectmenu" und ist in der neusten Version behoben.
