### ISSUE TITLE
Weiterleitung bei "einschränkender Filter" funktioniert nicht.

### ISSUE THREAD

**Issue by eBlick** [isotope/core#2017]
Ich habe eine Produktvariantenliste mit einschränkendem Filter auf Seite A (tuergriffe-komplett).
Beim Filtern soll der User auf Seite B (tuergriffe) weitergeleitet werden.
Dies funktioniert aber nicht. Die Filter URLs sind nach wie vor auf Seite A.
Hier ein screenshot der Einstellungen im Filter:
![bildschirmfoto 2019-01-29 um 15 32 52](https://user-images.githubusercontent.com/6641281/51915342-2f4e9580-23db-11e9-9380-e80127f25324.png)

Hier noch ein Screenshot aus dem Frontend bei Mouseover im Filter. Hier wird weiterhin die Seite tuergriffe-komplett verlinkt:
![bildschirmfoto 2019-01-29 um 15 34 29](https://user-images.githubusercontent.com/6641281/51915469-72106d80-23db-11e9-82ca-f9274f31a310.png)

**Comment by aschempp** [comment]
Die Weiterleitungsseite sollte **nach dem anwenden** des Filters zum Zuge kommen. Der Link geht auf die Seite auf welcher das Modul auch drauf ist, danach wird auf die konfigurierte Seite weitergeleitet. Das ist ähnlich wie im Formulargenerator, dort wird das Formular auch an die bestehende Seite gesendet und **danach** weitergeleitet.

Macht das so Sinn für dich?
