### ISSUE TITLE
Server Error when I try to edit product type in the shop config

### ISSUE THREAD

**Issue by bizon1** [isotope/core#2020]
When I try to edit the product types in the shop configuration I get the following error:

`Type error: Argument 1 passed to Isotope\Backend\ProductType\AttributeWizard::getColumns() must be an instance of MultiColumnWizard, instance of MenAtWork\MultiColumnWizardBundle\Contao\Widgets\MultiColumnWizard given, called in /path/to/project/vendor/menatwork/contao-multicolumnwizard-bundle/src/Contao/Widgets/MultiColumnWizard.php on line 543`

Contao 4.4.34
Isotope-core 2.5.10 
menatwork/contao-multicolumnwizard-bundle 3.4.0@beta8

**Comment by fritzmg** [comment]
I think Isotope is simply not compatible with `menatwork/contao-multicolumnwizard-bundle`. You have to uninstall `menatwork/contao-multicolumnwizard-bundle`.

**Comment by aschempp** [comment]
Looks like a BC break in `multicolumnwizard` (see https://github.com/isotope/core/issues/2020)

**Comment by stefanheimes** [comment]
@bizon1 we have a new version of the mcw (3.4.1) which should fix the problem.
