### ISSUE TITLE
Preisaufschläge oder -abschläge lassen sich nicht bearbeiten

### ISSUE THREAD

**Issue by itcbchris** [isotope/core#2021]
Beim Pflegen der Optionen für eine Produktvariante lassen sich die Preisaufschläge oder -abschläge nicht mehr angeben. Sprich der Bereich wird nicht angezeigt oder ist ausgeblendet.

Ich vermute das Problem liegt an diese Einstellung:

`<input type="hidden" name="FORM_FIELDS[]" value="{label_legend},type,isDefault,label;{price_legend:hide},price;{publish_legend},published">`

Also Sprich das die der Preis-Bereich ausgeblendet wird. Bewusst habe ich keine Einstellung getroffen, die dies hervorrufen sollte. Ich hatte lediglich einmal versucht bei einem Produkt das Feld Preis auch in die Varianten mit auf zu nehmen. Aber da kam ja eine Fehlermeldung.

VG

**Comment by aschempp** [comment]
dir fehlt vermutlich die Erweiterung `multicolumnwizard`

**Comment by aschempp** [comment]
hat sich hier noch etwas ergeben?

**Comment by itcbchris** [comment]
Entschuldigung allgegenwärtige Grippe ... 

Ja aus der Doku war für mich nicht ersichtlich, das man die Optionen die man bei den Varianten braucht weiter "oben" abwählen muss.

Ich habe also für das einzelne Produkt den Preis abgewählt und dann bei der Variantenansicht hinzu und dann hat er geklappt.

VG&danke
