### ISSUE TITLE
Warning: A non-numeric value encountered

### ISSUE THREAD

**Issue by Ainschy** [isotope/core#2025]
https://github.com/isotope/core/blob/e95d8b26c4c14ae31f1e2c692a3a69785f80ca17/system/modules/isotope/library/Isotope/Frontend.php#L685

Ist ein Options-Wert 0.00  bzw. +0.00 wird an dieser Stelle ein Warning erzeugt.

_Warning: A non-numeric value encountered in /srv/www/kunde/public/vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/Frontend.php on line 685_

`$fltAmount += $objOption->getAmount($fltPrice, 0);`

da hier versucht wird der Wert als String(0) "" hinzuzufügen. 

`$fltAmount += (float)$objOption->getAmount($fltPrice, 0);` 
oder
`$fltAmount += floatval($objOption->getAmount($fltPrice, 0));`

schafft Abhilfe.

**Comment by aschempp** [comment]
Could this be related to https://github.com/isotope/core/pull/2007?
/cc @fritzmg

**Comment by aschempp** [comment]
Fixed in version 2.5.12
