### ISSUE TITLE
Hreflang-Rückbeziehung fehlt

### ISSUE THREAD

**Issue by Kahru** [isotope/core#2026]
Hallo, 

Sistrix wirft mir bei einem mehrsprachigen Isotopeshop für jedes Produkt den Fehler "Hreflang-Rückbeziehung fehlt" aus.

Bei dem Shop gibt es für die Einzelansicht immer eine eigene Detailseite. Die hat layoutechnische Gründe und funktioniert auch alles einwandfrei. Auch der Wechsel der Sprachen zwischen den Produkten geht perfekt.

Aber Sistrix wirft diesen hreflang-Rückbeziehung-Fehler auf. Geht man dem nach, dann sieht man, dass hier von Isotope wohl doch der Alias falsch gebildet wird. Changelaguage halte ich für unschuldig:

klickt man im deutschen auf Produkt1, dann kommt:
domain.de/liste/produkt1.html (das ist meiner bescheidenen Ansicht nach schon verkehrt, da müsste details stehen!)

Klickt man nun auf Changelanguage EN kommt:
domain.en/details/produkt1.html (die Unterseite erscheint korrekt)

Klickt man wieder auf DE kommt:
domain.de/details/produkt1.html (die Unterseite erscheint auch korrekt, das wäre wohl auch der richtige Alias!)

Dito passiert wenn man von der englischen Seite aus startet. Der Besucher merkt solange er nicht auf den Alias schaut von dem Verhalten übrigens nichts. Aber der Sistrix dem fällt das auf, da die liste/produktx.html natürlich keine entsprechende hreflang-Seite haben.

Isotope 2.5.10.3
Changelanguage 3.1.9.6
Contao 3.5.38
Detailseite benutzen ist der Seitenstruktur angehakt und mit der entsprechenden Unterseite verbunden.

Da es sich um eine Kundenseite handelt, kann ich die Seite hier nicht öffentlich posten. Der Kunde ist sich übrigens sicher, dass es den Fehler früher in 2.4 so nicht gab, aber das könnte auch am veränderten Suchverhalten von Sistrix liegen. 

Andreas sende mir im Bedarfsfall bitte eine Mail, dann bekommst Du den Link auf die Seite.

Bernard

**Comment by aschempp** [comment]
Grundsätzlich ist es so, dass ein Produkt in Isotope immer auf mehreren Seiten vorkommen kann. Und die Listenseite absichtlich auch als Detailseite verwendet wird, damit die URL entsprechend "hübsch" ist. Du solltest die Detailseite dem Produkt nicht zuweisen. Immer die erste zugewiesene Seite (einer Sprache) wird als hreflang verwendet.

E-Mail Support bieten wir lediglich gemäss Isotope Circle (https://circle.isotopeecommerce.org) an.

**Comment by Kahru** [comment]
Hallo, danke für die Antwort. 

Ob ich die Detailseite dem Produkt zuweise oder nicht ändert nichts an den Sistrix-Fehlern und auch nichts an der "doppelten" Bildung der Aliasnamen oder am sonstigen Verhalten. 

Durch die Isotope-Vermischung zwischen Liste und Details sind die Produktunterseiten bei mehrsprachigen Seiten halt nicht mehr eindeutig und verursachen damit das HReflang-Rückbeziehungs-Problem bei eigenen Detailseiten. Das mag zwar hübscher aussehen, dem Sistrix-Tool bzw. Google bei der hreflang-Prüfung ist das aber egal. Das Contao-Nachrichtenmodul, das ja so ähnlich arbeiten muss, verhält sich hier eindeutig. Es zeigt konsequent nur die Alias-Details.

**Comment by aschempp** [comment]
Beim Contao News-Modul gibt es auch nur eine Detailseite. Bei Isotope gibt es eine Detailseite für jeden Listen-Seite welche du auswählst. Es gibt aber nur eine primäre Detailseite, nämlich die welche zuoberst in der Liste ist (pro Sprache).

Das resultiert daraus dass du folgendes haben kannst:

1. /telefone/mobile/iphone-xr.html
2. /marken/apple/iphone-xr.html
3. /anschlüsse/lightning/iphone-xr.html

Das selbe Produkt kann unter mehreren Rubriken erscheinen. Aber die primäre URL, und damit die hreflang, ist immer die 1.

**Comment by Kahru** [comment]
Hallo, das ist mir denke ich soweit schon alles klar. 

Ändert aber nichts an der meiner Ansicht nach falschen Bildung des Detailaliasnamen aus dem Listenaliasnamen. Anbei mal ein Screenshot wo man eindeutig sieht, dass Aliasname oben und hreflang im Quellcode nicht zusammenpassen. Da steht oben .../koffer/... Das ist die Listen-Seite. Da müsste aber .../Details/... im Alias stehen.

![2019-03-04_131611](https://user-images.githubusercontent.com/5871470/53733168-715a7380-3e80-11e9-8289-9d30320fdd9e.jpg)

**Comment by aschempp** [comment]
Ich bin mir nicht 100% sicher, aber für mich sieht das richtig aus.

die `rel=alternate` mit `hrefslang=` sind die primären Links, es gibt pro Sprache immer nur einen. Die `rel=canonical` sind "Seiten mit gleichem Inhalt aber nicht die primäre URL" des Produkts. Wie gesagt solltest du die Details-Seite nicht in deinen Produkten auswählen, dann wäre es vermutlich bereits so wie du es gerne hättest.

**Comment by Kahru** [comment]
Hallo, ich habe keine Details eingetragen
![2019-03-04_151040](https://user-images.githubusercontent.com/5871470/53739914-3a418d80-3e93-11e9-8054-7b65f752e9d5.jpg)

**Comment by aschempp** [comment]
Ah, danke für den Screenshot. Das sieht dann schon eher nach einem Bug aus!
