### ISSUE TITLE
Sofortüberweisung: Benachrichtigungspasswort MUSS gesetzt sein

### ISSUE THREAD

**Issue by p1nkm4n** [isotope/core#2027]
Es ist leider nicht mehr möglich das Benachrichtigungspasswort nicht zu setzen oder löschen zu lassen. Daher funktioniert die Zahlungsmethode bei neu angelegten Projekten bei Sofort leider nicht mehr weil dort das Benachrichtigungspasswort automatisch gesetzt ist.

**Comment by aschempp** [comment]
Was bedeutet "Automatisch gesetzt"?

**Comment by p1nkm4n** [comment]
Das Passwort ist bei Sofort (bzw. Klarna) nicht mehr optional sondern wird beim anlegen eines neuen Projekts gesetzt. Durch den Support kann es auch nicht mehr gelöscht oder deaktiviert werden.

**Comment by aschempp** [comment]
Ich kann leider nicht ganz folgen. Kann man bei Isotope kein Passwort eingeben?

**Comment by p1nkm4n** [comment]
In der Dokumentation von Isotope steht:

> (ACHTUNG: Das Benachrichtigungspasswort darf im SOFORT-Backend nicht gesetzt sein. Der Support von SOFORT kann dies löschen, falls es aus Versehen schon gesetzt wurde.

Dieses Passwort kann aber wie geschrieben nicht mehr gelöscht werden. In einer Testinstallation funktioniert die Zahlungsabwicklung mit einem alten Projekt ohne Probleme, in der gleichen Installation mit einem neuen allerdings nicht mehr. Man wird zwar korrekt zu Sofort geleitet und kann bezahlen beim zurückkehren zum Shop wird die Zahlung dann allerdings nicht erkannt. 
Ich schätze das dies eben an diesem Benachrichtigungspasswort liegt, ich hab auch mit Sofort bzw. Klarna telefoniert und die haben mir gesagt dass dieses Passwort nicht mehr gelöscht werden kann und bei neuen Projekten immer vorhanden ist.

**Comment by aschempp** [comment]
Ich verstehe den Bug nicht ganz. Das Projekt-Passwort kannst du doch im Isotope Zahlungsmodul eingeben? Oder geht es dir nur um die Dokumentation?

**Comment by aschempp** [comment]
Oder ist das Benachrichtigungs-Passwort nicht mehr gleich wie das Projektpasswort?

**Comment by p1nkm4n** [comment]
Die Zahlungsbestätigung funktioniert so in der jetzigen Form nicht mehr. Bei alten Projekten ohne Benachrichtigungspasswort funktioniert es. Bei neuen Projekten mit eben diesem Passwort funktioniert es nicht daher vermute ich das es mit dem Benachrichtigungspasswort zusammenhängt.

**Comment by aschempp** [comment]
Hast du denn ein Projekt-Passwort eingegeben? Ein anderes als das Benachrichtigungspasswort? Kann man diese nicht gleich setzen?

**Comment by aschempp** [comment]
Ich schliesse das mal mangels weitere Infos. Gerne wieder öffnen wenn meine Frage beantwortet werden kann.
