### ISSUE TITLE
Backend Bestell-Details image max-width setzen

### ISSUE THREAD

**Issue by SGehle** [isotope/core#2029]
Um zu breite Bilder in den Bestell-Details im Backend zu verhindern sollte hierfür folgender Eintrag in der backend.css ergänzt werden:

```
.mod_iso_orderdetails .image_container img {
	max-width: 100%;
	height: auto;
}
```

**Comment by fritzmg** [comment]
Well, you are supposed to select an order details module for the back end in the shop configuration (which would have a gallery setting, which would have a defined image size).

**Comment by SGehle** [comment]
Das gleiche Problem tritt in der Produkt-Ansicht auf - hierfür kann ich ja leider kein Backend Modul wählen...

**Comment by fritzmg** [comment]
> Das gleiche Problem tritt in der Produkt-Ansicht auf - hierfür kann ich ja leider kein Backend Modul wählen...

In that case your images are reaching the maximum GD image width and height configured in your system settings. You need to either:

* increase the maximum GD image width/height (and also possibly increase the `memory_limit` accordingly)
* switch to Imagick/Gmagick
* upload smaller images for your products, if your server environment cannot handle large images

**Comment by SGehle** [comment]
Nein, das hat damit absolut nichts zutun. Ich kann für die Produkt-Ansicht im Backend kein Modul auswählen, bei dem ich die Bildgröße einstellen kann. Der Server kann die Bilder entsprechend verarbeiten, nur die Lightbox des Mediamanagers das Bild nicht an den Viewport anpasst...

**Comment by fritzmg** [comment]
Ah, you mean the lightbox. You did not specify that ;)

**Comment by aschempp** [comment]
Also ich bin nicht sicher wovon ihr beider hier redet 😆 

`.mod_iso_orderdetails` hat keine Lightbox. Und die Lightbox in der Produktansicht kommt von Contao selber, darauf haben wir wenig Einfluss.

@SGehle kannst du das Problem mit einem Screenshot beschreiben?

**Comment by fritzmg** [comment]
I think he means this:

![screenshot-isotope](https://user-images.githubusercontent.com/4970961/58538860-520c8180-81f6-11e9-920c-1107fbeb3d49.png)

The image shown there can go outside the viewport.

**Comment by SGehle** [comment]
Danke @fritzmg - genau das war gemeint.
