### ISSUE TITLE
Is encryption  of address-data planned?

### ISSUE THREAD

**Issue by itxup** [isotope/core#2031]
Hello, 

first of all: thanks for providing isotope, imho it's a great solution. 
I'm trying to create an offer for a customer in which isotope would play the main part and I just realized that the customer's data in tl_iso_address isn't encrypted. Are you planning to add this as a feature? I'm not sure whether encryption is really a mandatory point for shops but on the other hand in times of GDPR/ DSGVO it might be better...
I know that there was a leads-encryption-module by hoff (for leads of course, not isotope) - could this way provide a solution here too if adapted? 

Thx a lot!

**Comment by aschempp** [comment]
There are no plans to encrypt that data. First of all, it is not private data, the address is/can be in a public telephone book, in your e-mail, letterhead or whatever. Secondly, encryption would only make any sense if you **transfer** the data somewhere. Having it on the same server as the decryption key does not really benefit anything in my opinion. Using an SSL certificate for your server/backend benefits this 1000 more than encryption the database. But we can't force people to use an SSL encryption…

Yes, I'm aware of the hoff extension, but I never saw any point in it. The reason it exists is *my lawyer told me*, and I'm sorry but that's a german thing swiss people can't agree with 😂
