### ISSUE TITLE
In Contao 4.7 tcpdf is not longer Core-Bundle

### ISSUE THREAD

**Issue by netzarbeiter** [isotope/core#2033]
Is there a possibility to require the tcpdf-bundle?

https://community.contao.org/de/showthread.php?74427-Nach-update-auf-4-7-Error-beim-Checkout

**Comment by fritzmg** [comment]
I don't think there is any possibility, as long as versions older than Contao 4.7 have to be supported. But Isotope could add
```
{
    "suggest": {
        "contao/tcpdf-bundle": "For document creation you need to install the contao/tcpdf-bundle when using Contao 4.7 and up."
    }
}
```
to the `composer.json` and may be make the core independent from the presence of `contao/tcpdf-bundle` - and instead give a notification in the back end somewhere, if `contao/tcpdf-bundle` is missing (in Contao >=4.0,<4.7).

**Comment by aschempp** [comment]
I have added a backend error message/warning in c636f3b660e96cf2937b0be56b4238e18b1161f6
