### ISSUE TITLE
MwSt. für Versandkosten bei Produkten mit zwei untersch. Steuerklassen

### ISSUE THREAD

**Issue by toblr** [isotope/core#2034]
Hallo zusammen,
Ich sitze gerade an einem Isotope im Contao 4.4.34 für einen Kunden und habe ein Problem, was ich leider bisher auch nicht anderweitig lösen und es evtl. für die Zukunft von Isotope interessant sein könnte.

Der Kunde hat sowohl Produkte mit **7% MwSt.** als auch mit **19% MwSt.** Soweit so gut. 

Legt man Produkte mit **7%** in den Warenkorb, werden die Versandkosten auch mit **7%** besteuert. Legt man Produkte mit **19%** in den Warenkorb, werden die Versandkosten auch mit **19%** besteuert. Das ist alles soweit richtig. 
Legt man nun aber sowohl ein Produkt mit **7% als auch mit 19%** in den Warenkorb, werden die Versandkosten mit beiden Steuerklassen besteuert, wenn "Aufgeteilt" für die Versandkosten ausgewählt wurde.

Allerdings müsste es laut der Buchhaltung unseres Kunden so sein, dass die MwSt. von dem Produkt, dass den **höheren** Wert hat, zur Versteuerung der Versandkosten verwendet wird, also in meinem Falle 19%.

Leider konnte ich dazu auch nur einen 4 Jahre alten Contao-Blogpost finden, der mir leider nicht weiterhelfen konnte: https://community.contao.org/de/showthread.php?35944-Versandkosten-MwSt-bei-Produkten-mit-zwei-verschiedenen-Steuerklassen

Ist sowas für die Zukunft geplant oder ist dies bereits irgendwie lösbar? 

Danke!

**Comment by aschempp** [comment]
Nun, da sind meine Informationen schlicht anders als die der Buchhaltung. Aufgeteilt heisst, die Steuern werden entsprechend den Produktpreisen prozentual berechnet. 

Der Hintergrund liegt darin, dass der Versand eine Nebenleistung der Produkte ist, und deshalb auch entsprechend den Produkten besteuert wird. Aus meiner Sicht ist deine Buchhaltung hier falsch.

Falls du nicht mit denen Argumentieren willst, kannst du es nur über verschiedene Produkttypen lösen. Wenn du zwei Versandmodule gruppierst, und eines pro Steuer anlegst, kannst du das 7% Modul auf entsprechende Produkttypen einschränken und es wird nicht mehr gezogen wenn ein 19%-Produkt im Warenkorb ist.

PS: wäre toll wenn du das danach entsprechend im Forum dokumentierst 😉

**Comment by toblr** [comment]
Okay vielen Dank, wird kommentiert! 👍
