### ISSUE TITLE
The registry already contains an instance for tl_iso_gallery::id()

### ISSUE THREAD

**Issue by ngdot** [isotope/core#2041]
Hi, folgenden Fehler erhalte ich im Warenkorb wenn ich eine Galerie zuweise.
Nutze das unveränderte iso_collection_default.html5 Template zur Ausgabe.

Jemand eine Idee/Tipp?

> Fatal error: Uncaught exception RuntimeException with message The registry already contains an instance for tl_iso_gallery::id() thrown in system/modules/core/library/Contao/Model/Registry.php on line 180
#0 system/modules/core/library/Contao/Model.php(699): Contao\Model\Registry->register(Object(Isotope\Model\Gallery\Standard))
#1 system/modules/core/library/Contao/Model.php(689): Contao\Model->attach()
#2 system/modules/core/library/Contao/Model.php(750): Contao\Model->detach(true)
#3 composer/vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/Model/Gallery.php(73): Contao\Model->preventSaving()
#4 composer/vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/Model/ProductCollection.php(1508): Isotope\Model\Gallery::createForProductAttribute(Object(Isotope\Model\Product\Standard), 'images', Array)
#5 [internal function]: Isotope\Model\ProductCollection->Isotope\Model\{closure}('images', Object(Isotope\Model\ProductCollectionItem))
#6 system/modules/core/library/Contao/Template.php(152): call_user_func_array(Object(Closure), Array)
#7 templates/iso_collection_default.html5(42): Contao\Template->__call('getGallery', Array)
#8 templates/iso_collection_default.html5(42): Isotope\Template->getGallery('images', Object(Isotope\Model\ProductCollectionItem))
#9 system/modules/core/library/Contao/BaseTemplate.php(88): include('/var/www/vhosts...')
#10 system/modules/core/library/Contao/Template.php(277): Contao\BaseTemplate->parse()
#11 system/modules/core/classes/FrontendTemplate.php(46): Contao\Template->parse()
#12 composer/vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/Module/AbstractProductCollection.php(169): Contao\FrontendTemplate->parse()
#13 composer/vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/Module/Cart.php(51): Isotope\Module\AbstractProductCollection->compile()
#14 system/modules/core/modules/Module.php(282): Isotope\Module\Cart->compile()
#15 composer/vendor/codefog/contao-haste/library/Haste/Frontend/AbstractFrontendModule.php(52): Contao\Module->generate()
#16 composer/vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/Module/Module.php(111): Haste\Frontend\AbstractFrontendModule->generate()
#17 composer/vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/Module/AbstractProductCollection.php(56): Isotope\Module\Module->generate()
#18 system/modules/mergecssclasses/elements/ContentModuleMerged_C35.php(63): Isotope\Module\AbstractProductCollection->generate()
#19 system/modules/core/library/Contao/Controller.php(476): ContentModuleMerged->generate()
#20 system/modules/core/modules/ModuleArticle.php(213): Contao\Controller::getContentElement(Object(Contao\ContentModel), 'main')
#21 system/modules/core/modules/Module.php(282): Contao\ModuleArticle->compile()
#22 system/modules/core/modules/ModuleArticle.php(67): Contao\Module->generate()
#23 system/modules/core/library/Contao/Controller.php(409): Contao\ModuleArticle->generate(false)
#24 system/modules/core/library/Contao/Controller.php(269): Contao\Controller::getArticle(Object(Contao\ArticleModel), false, false, 'main')
#25 system/modules/core/pages/PageRegular.php(133): Contao\Controller::getFrontendModule('0', 'main')
#26 system/modules/core/controllers/FrontendIndex.php(267): Contao\PageRegular->generate(Object(Contao\PageModel), true)
#27 index.php(20): Contao\FrontendIndex->run()
#28 {main}

**Comment by aschempp** [comment]
bitte erkläre *eine Galerie zuweise*?
