### ISSUE TITLE
Produkt-Filter Bedingung

### ISSUE THREAD

**Issue by SGehle** [isotope/core#2043]
Wie genau Funktioniert die Bedingung beim Produkt-Filter?
Wenn ich z.B. tl_iso_product.pid != 0 eingebe bekomme ich folgenden Fehler:
Contao 4.4.39 - Isotope 2.5.12

`{"exception":"[object] (Doctrine\\DBAL\\Exception\\InvalidFieldNameException(code: 0): An exception occurred while executing 'SELECT DISTINCT p1.size AS options\n            FROM tl_iso_product p1\n            LEFT OUTER JOIN tl_iso_product p2 ON p1.pid=p2.id\n            WHERE\n                p1.language=''\n                AND p1.size!=''\n                \n                AND p1.published='1'\n                AND (p1.start='' OR p1.start<'1558434720')\n                AND (p1.stop='' OR p1.stop>'1558434780')\n             AND (\n                    p1.pid=0 OR (\n                        p2.published='1'\n                        AND (p2.start='' OR p2.start<'1558434720')\n                        AND (p2.stop='' OR p2.stop>'1558434780')\n                    )\n                )\n                AND (\n                    p1.id IN (\n                        SELECT pid\n                        FROM tl_iso_product_category\n                        WHERE page_id IN (114,204)\n                    )\n                    OR p1.pid IN (\n                                    SELECT pid\n                                    FROM tl_iso_product_category\n                                    WHERE page_id IN (114,204)\n                                )\n                )\n                AND (\n                    p2.type IN (3)\n                )\n                 AND tl_iso_product.pid != 0':\n\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 'tl_iso_product.pid' in 'where clause' at /homepages/15/d697471085/htdocs/contao18/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:80, Doctrine\\DBAL\\Driver\\PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'tl_iso_product.pid' in 'where clause' at /homepages/15/d697471085/htdocs/contao18/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:109, PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'tl_iso_product.pid' in 'where clause' at /homepages/15/d697471085/htdocs/contao18/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:107)"}`

**Comment by aschempp** [comment]
Der Produkt-Filter hatte noch falsche Tabellen-Aliase verwendet. In 2.5.13 sollte es mit deinem Query gehen.

**Comment by SGehle** [comment]
Vielen Dank @aschempp  - funktioniert nun korrekt!
