### ISSUE TITLE
Falscher HTTP-Statuscode bei fehlgeschlagener Validierung von PayPal-Zahlungsbestätigung

### ISSUE THREAD

**Issue by Mynyx** [isotope/core#2044]
Wenn eine PayPal-Zahlungsbestätigung beispielsweise wegen eines Serverfehlers von PayPal nicht validiert werden kann, wird dennoch der HTTP-Statuscode 200 zurückgegeben. Dies führt dazu, dass PayPal die Übermittlung der Zahlungsbestätigung als erfolgreich abgeschlossen betrachtet und keine weiteren Übermittlungsversuche unternimmt.

Ursache ist, dass in Isotope\Model\Payment\Paypal::validateInput im Fall der UnexpectedValueException im Gegensatz zur RuntimeException keine Response mit dem Statuscode 500 erfolgt:
https://github.com/isotope/core/blob/master/system/modules/isotope/library/Isotope/Model/Payment/Paypal.php#L289-L291

**Comment by aschempp** [comment]
aus meiner Sicht ist das Absicht? Wenn PayPal uns eine Antwort 200 nicht mit einem VERIFIED gibt, dann sagt PayPal uns dass die Zahlungsdaten nicht korrekt sind. Würden wir in diesem Fall den IPN immer wieder neu anfordern, würden wir ja jedes Mal wieder eine ungültige Prüfung auslösen?

**Comment by Mynyx** [comment]
Dann wäre es sinnvoll zwischen drei Fällen zu unterscheiden: VERIFIED mit Status-Code 200, INVALID mit Status-Code 200, sonstige Antwort mit beliebigen Status-Code.

Das Problem mit der derzeitigen Lösung ist, dass PayPal im Fall eines Serverfehlers teilweise dennoch den HTTP-Statuscode 200 zurückgibt, derzeit aber alle Antworten ungleich VERIFIED mit HTTP-Statuscode 200 als invalid betrachtet werden.

**Comment by aschempp** [comment]
Das ist doch auch richtig? Die PayPal API sagt, bei erfolgt kommt ein *VERIFIED*. Wenn kein *VERIFIED* kommt, können wir uns nicht darauf verlassen dass es erfolgreich war?
