### ISSUE TITLE
Produkttyp bearbeiten Fehler

### ISSUE THREAD

**Issue by SGehle** [isotope/core#2045]
Beim bearbeiten eines Produkttypen wird folgende Fehlermeldung ausgegeben:
Type error: Argument 1 passed to Isotope\Backend\ProductType\AttributeWizard::getColumns() must be an instance of MultiColumnWizard, instance of MenAtWork\MultiColumnWizardBundle\Contao\Widgets\MultiColumnWizard given, called in /html/dev/deineparty/vendor/menatwork/contao-multicolumnwizard-bundle/src/Contao/Widgets/MultiColumnWizard.php on line 644

Anpassung in Isotope\Backend\ProductType\AttributeWizard::getColumns() notwendig. 

Contao: 4.4.20
Isotope: 2.5.13
MultiColumnWizard-Bundle: 3.4.1

**Comment by aschempp** [comment]
siehe https://github.com/menatwork/contao-multicolumnwizard-bundle/issues/39
