### ISSUE TITLE
Product Manager

### ISSUE THREAD

**Issue by rburch** [isotope/core#2050]
We are importing products and the data looks correct in the database but we keep getting an internal server error when we try and open the product manager.

Isotope\Model\Product\Standard has no model type

Anyone know what that could be? We using latest Isotope and Contao 4.4.40

**Comment by aschempp** [comment]
Looks like you're importing incorrect data. Make sure tl_iso_product.type is the ID of your tl_iso_producttype model, and tl_iso_producttype.type is "standard" and not the class name.

**Comment by fritzmg** [comment]
This error can also happen, if `tl_iso_producttype.attributes` does not contain the `type` information. Which can also happen in the back end - if an error occurs during saving, not all the necessary data will be serialized into `tl_iso_producttype.attributes` and then the product manager cannot be opened anymore.
