### ISSUE TITLE
Variant Reader: Changing attribute options clears other attribute options

### ISSUE THREAD

**Issue by eBlick** [isotope/core#2052]
When changing an attribute option in a variant reader, other options are cleared if they are not available for the selected option. Example 
-> Product has three colors blue, green, white
-> blue has two sizes L, M
-> green has one size L
-> white has one size M

When blue / L is selected and I change to green, the size is not pre-selected.
This means  the user needs to click on the size although only one size is available.
In this small use case it is no problem but when handling 8-10 attributes it is not user-friendly because every time the user changes options, he needs to actively select every option.

If only one option is available it should be pre-selected.

**Comment by aschempp** [comment]
Will be fixed in Isotope 2.6
