### ISSUE TITLE
Page Class Issue

### ISSUE THREAD

**Issue by rburch** [isotope/core#2056]
We are using a class that extends Contao\PageModel and Isotope\Model\Product\Standard::generateUrl() checks for Contao\PageModel in the function definition. So when we try to look at orders in the backend of isotope we're getting an error and can't view them.

**Comment by richardhj** [comment]
It is discouraged to override Contao core classes, so it is very unlikely that any change will be introduced promoting this pattern. You should rather find a way to achieve what you need while not overriding Contao core classes. (IMO Model classes can also be defined as `final class`).

Besides this, `generateUrl()` only has a type cast to `\PageModel`, which means that your custom model should be accepted by this method. Though, a stack trace would help to gain deeper insights on this issue.
