### ISSUE TITLE
Gutschein mit Beschränkung -> Produkt-Bedingungen "Falsch" wird nicht angewendet

### ISSUE THREAD

**Issue by andreas361** [isotope/core#2057]
Ich möchte einen Gutschein erstellen, welcher auf alle Produkte bis auf eines angewendet werden kann.

![photo_2019-07-26_12-19-55](https://user-images.githubusercontent.com/6040761/61945252-d03f9700-af9f-11e9-98d0-b652113479e9.jpg)

Wende ich nun den Gutschein an, erhalte ich zwar den Hinweis, dass der Gutschein hinzugefügt wurde. Tatsächlich wird er das jedoch nicht (Summe/Zwischensumme ändert sich nicht und Gutschein ist auch nirgends sichtbar).

Das Problem liegt anscheinend an "Produktbedingungen: falsch". Wird hier "wahr" gewählt, wird der Gutschein korrekt angewendet (allerdings dann natürlich nur anwednbar für das Produkt, welches ich eigentlich ausschließen möchte).

**Comment by aschempp** [comment]
Hast du eine Warenkorb- oder eine Produktregel?

**Comment by andreas361** [comment]
Eine Warenkorbregel

**Comment by aschempp** [comment]
Und das Produkt befindet sich nicht im Warenkorb?

**Comment by andreas361** [comment]
Genau - befindet sich das Produkt im Warenkorb, kann ich den Gutschein nicht anwenden. 

Befindet sich das Produkt nicht im Warenkorb, kann ich den Gutschein zwar anwenden, aber es wird eben nichts abgezogen.
