### ISSUE TITLE
[2.5.16] Falsche Berechnung von $item['tax_free_total']

### ISSUE THREAD

**Issue by chrizdee** [isotope/core#2059]
Im Warenkorb wird bei Produkten mit Aufschlag der `$item['tax_free_total']` falsch berechnet.

**Beispiel:**
Produktpreis: 100 € netto
Aufschlag: 100 € netto
MwSt.: 19%

**Anzeige im Warenkorb:**
$item['tax_free_total'] = 219 €

Korrekt wären 200 €.

Der Aufschlag wird anstatt als netto, mit brutto zum Produktpreis addiert.

![isotope-cart](https://user-images.githubusercontent.com/4388030/63589128-94045400-c5a8-11e9-8ff5-c90a216ca1b8.png)

**Comment by fritzmg** [comment]
Same problem here. I am using a temporary work around directly in the templates 😬 
```php
/** @var ProductCollectionItem $collectionItem */
$collectionItem = $item['item'];

/** @var TaxClass $productTaxClass */
$productTaxClass = TaxClass::findById($collectionItem->tax_id);

$grossPrice = $collectionItem->getPrice();
$totalGrossPrice = $collectionItem->getTotalPrice();

$netPrice = $productTaxClass->calculateNetPrice($grossPrice);
$totalNetPrice = $productTaxClass->calculateNetPrice($totalGrossPrice);

$formattedNetPrice = Isotope::formatPriceWithCurrency($netPrice);
$formattedTotalNetPrice = Isotope::formatPriceWithCurrency($totalNetPrice);
```
(in our case, the product price includes the tax)

**Comment by aschempp** [comment]
Can you please test 26f2ce9e4388c86cd8710a4a47d5695b61c37557 ?

**Comment by fritzmg** [comment]
Fix within hotfix/2.6.3 looks good 👍

**Comment by aschempp** [comment]
I have fixed an implementation bug in 454d54d5de9af003c3b543320b5afbc466d6cb21
@fritzmg @chrizdee can you please see if this change still works in your systems?
