### ISSUE TITLE
2.6.0: Detailseite zeigt Produktliste

### ISSUE THREAD

**Issue by k-webdesign** [isotope/core#2060]
Huhu,
ich hab eine lokale Installation mit 2.5.15 und sie auf dem Webhosting auf die 2.6 geupdated. Lokal bekomme ich beim Klick auf das Produkt noch die Detailseite des Produkts angezeigt, unter der 2.6 ändert sich zwar die URL, ich sehe aber noch mal den Inhalt der Detailseite. 

Eben noch mal getestet und auf die 2.5.15 zurückgerollt: So geht es wieder.

Das Problem ließ sich im Forum reproduzieren:
https://community.contao.org/de/showthread.php?75829-Keine-Produktdetailseite-mehr-seit-Update-auf-2-6&p=509878

VG Kim

**Comment by aschempp** [comment]
ist im Forum entsprechend beantwortet.

**Comment by akroii** [comment]
Das Problem wie eingangs beschrieben tritt in der Isotope-Version 2.6.4 nach wie vor auf.

Bei der Seite "Produkt-Übersicht" wurde eine Detailseite festgelegt.
- [x] Detailseite benutzen -> (kategorie/detailseite)
- [ ] Element erforderlich

Das Modul Produktliste enthält beim Punkt "Weiterleitung":
- [ ] Link zur primären URL
- [ ] Ausblenden bei Produktansicht

Das Modul Produktleser enthält:
- [ ] Eine 404-Fehlerseite anzeigen

Wenn ich versuche die Produktdetailseite aufzurufen erscheint in der URl zwar der richtige Alias, aber ohne das Produkt. Es wird hierbei das Listing aufgerufen, statt den Produktleser. In der Breadcrumb steht interessanter Weise "404". 

Das Interessante ist, dass wenn ich den Produktleser auf die Produkt-Übersicht packe, das entsprechende Produkt gefunden wird. Das Produkt wird dann unter dem Listing dargestellt.

Die Weiterleitung zur Produktdetail-Seite funktioniert irgendwie nicht, obwohl ich sie eingestellt habe.

Das Problem scheint recht komplex. Gerne kann ich einen Zugang erstellen (sofern gewünscht).
