### ISSUE TITLE
Übersetzungen Optionen-Manager funktionieren nicht

### ISSUE THREAD

**Issue by siegelsupport** [isotope/core#2061]
Mir ist aufgefallen das in einer Contao 4.7.7. Installation mit Isotope 2.6. Attributwerte die mit dem Optionen-Manager verwaltet werden mit dem Übersetzungstool nicht übersetzt werden. Könnt Ihr das bestätigen?

beste Grüße

Robert

**Comment by aschempp** [comment]
Die Werte im Optionen-Manager lassen sich direkt dort übersetzen, daher ist das Übersetzungstool hier nicht nötig. Du solltest links oben eine Sprachauswahl sehen, wie auch bei den Produkten von Isotope.
