### ISSUE TITLE
Please pass as 4th parameter $arrConfig to HOOK addCollectionToTemplate

### ISSUE THREAD

**Issue by tsarma** [isotope/core#2062]
File Path: //modules/isotope/library/Isotope/Model/ProductCollection.php

```php
// !HOOK: allow overriding of the template
if (isset($GLOBALS['ISO_HOOKS']['addCollectionToTemplate'])
    && \is_array($GLOBALS['ISO_HOOKS']['addCollectionToTemplate'])
) {
    foreach ($GLOBALS['ISO_HOOKS']['addCollectionToTemplate'] as $callback) {
        \System::importStatic($callback[0])->{$callback[1]}($objTemplate, $arrItems, $this, $arrConfig);
    }
}
```

Right now there is no way of finding out which cart module is wrapping ProductCollection. if you pass `$arrConfig` you can read all informations related to the module e.g. 'Shopping Cart Module'.

**Comment by aschempp** [comment]
The method can be called from anywhere, so there's no guarantee of having a cart module. I'm assuming you added additional configuration to your cart module? Maybe you should rather add it to the store config?

**Comment by tsarma** [comment]
> The method can be called from anywhere, so there's no guarantee of having a cart module. 

I thought of so, but at least we can use available information inside `$arrConfig`. Even if it is an empty array, it is information.

I am trying to manipulate the products in collection depending upon which shopping cart module is used. Since we don't have at the moment any information of the cart module, I am just checking for the template name used for the product Collection `$objTemplate->getName()` and take action accordingly. which works for me but I think it is not robust. 

Had I got the information of the cart module in use, I would have assing some special cssID to the cart module and check for it.

Adding information to the store config I am not able to see any solution in my case. Since in the same shop depending upon the cart, some products are allowed to add and some are not, which are removed automatically.
