### ISSUE TITLE
Wrong version number in store configuration

### ISSUE THREAD

**Issue by chberger** [isotope/core#2063]
![grafik](https://user-images.githubusercontent.com/3606282/64063076-b07b3e80-cbef-11e9-92c7-e862899a5b49.png)

According to my log output, it should be 2.6.1

`Updating contao/news-bundle (4.4.41 => 4.4.42): Downloading (100%)
  - Updating codefog/contao-haste (4.23.6 => 4.24.0): Downloading (100%)
  - Updating isotope/isotope-core (2.5.16 => 2.6.1): Downloading (100%)
Generating optimized autoload files`

**Comment by aschempp** [comment]
Fixed in version 2.6.2
