### ISSUE TITLE
The search functionality in the product group modal isn't working anymore

### ISSUE THREAD

**Issue by chberger** [isotope/core#2064]
Seems like the search functionality in the product group modal isn't working anymore. I always get all results, independent of any search term entered.

![grafik](https://user-images.githubusercontent.com/3606282/64063166-03a1c100-cbf1-11e9-9794-acf07cfb5694.png)

Anyway, the search functionality in the pages modal still works as expected:

![grafik](https://user-images.githubusercontent.com/3606282/64063148-df45e480-cbf0-11e9-850d-1e152131979a.png)

**Comment by aschempp** [comment]
Unfortunately, this is yet another Contao BC issue. I have attempted to fix this in https://github.com/contao/contao/pull/1410
