### ISSUE TITLE
Log Rotation

### ISSUE THREAD

**Issue by Mynyx** [isotope/core#2065]
The log file ```var/logs/isotope_postsale.log``` is not rotated. (The log rotation of the regular ```var/logs/prod-YYYY-MM-DD.log``` works well.)

**Comment by aschempp** [comment]
That's because the log files are written using the Contao 3 methods, as Isotope is still compatible with Contao 3 😞

**Comment by Toflar** [comment]
Can't we just call `Automator::rotateLogs()` here: https://github.com/isotope/core/blob/master/system/modules/isotope/postsale.php#L203?

:)

**Comment by aschempp** [comment]
we can't run that on every access of the file. But I added a daily cron job in Contao 4
