### ISSUE TITLE
StringUtil::trimsplit in Isotope\Model\Product\Standard is incompatible with Contao 3.5

### ISSUE THREAD

**Issue by flyer303** [isotope/core#2067]
Here you are using StringUtil::trimsplit (I think) since Isotope 2.6.0:
https://github.com/isotope/core/blob/9265ce556c3b3e5e0ea8ecbb1f95a0d7892ce449/system/modules/isotope/library/Isotope/Model/Product/Standard.php#L438

This seems to be incompatible with Contao 3.5, because as far as I can see there is no trimsplit in StringUtil. In Contao 3.5 trimsplit is located in functions.php.

I know Contao 3.5 is outdated and I should upgrade to 4.x (I'm actually working on it). 
Just a hint because Isotope 2.6  is still marked as compatible (^3.5.2) in composer.json?

Possible solution:
```
if (version_compare(VERSION, '4.0', '<')) {
    $keywords = trimsplit(' |-', $keywords);
} else {
    $keywords = StringUtil::trimsplit(' |-', $keywords);
}
```

**Comment by aschempp** [comment]
You're right, we should use the global `trimsplit` instead.

**Comment by aschempp** [comment]
Der Fehler ist in der 2.6.2 behoben.
