### ISSUE TITLE
ProduktCache: SQL Fehler serialize / unserialize bei terminierten Produkten

### ISSUE THREAD

**Issue by Ainschy** [isotope/core#2071]
Contao 4, nicht unter Contao 3.5
Isotope 2.5 + 2.6
PHP 7.1

Beschreibung:
app.CRITICAL: An exception occurred. {"exception":"[object] (PDOException(code: 0): You cannot serialize or unserialize PDOStatement instances at XXX\vendor\contao\core-bundle\src\Resources\contao\library\Contao\Database\Statement.php:329)"}

Setup:
- Ein Produkt soll zeitlich veröffentlicht werden
- eine Produktliste mit der Option: "Zeige nur die neuen Produkte", alternativ die Option ("Zeige alte Produkte"
- beim Aufruf im FE wird versucht den ProduktCache zu erstellen beim speichern steigt die Seite  mit der erwähnten Fehlermeldung aus.

Hinweis: Das betroffene Produkt muss nicht mal zu der Kategorie der Seite gehören

**Comment by aschempp** [comment]
Der Fehler ist in der 2.6.2 behoben.
