### ISSUE TITLE
Länder ohne Staaten werden nicht akzeptiert

### ISSUE THREAD

**Issue by manjarco** [isotope/core#2078]
Wählt ein Kunde im Checkout ein Land aus, in dem es keine Staaten gibt, und bekommt daher nur die Leerauswahl "-" angezeigt, kann er den Checkout-Prozess nicht fortsetzen wenn das Feld Staat verpflichtend ist (was es sein muss wenn Versand in die USA angeboten wird).

Umgangen habe ich das jetzt für z.B. Serbien mit einem Eintrag in app/Resources/contao/languages/en/subdivisions.php:

`$GLOBALS['TL_LANG']['DIV']['rs']['RS-01'] = 'None';`

**Edit:**

Besser ist natürlich wie anscheinend üblich:
`$GLOBALS['TL_LANG']['DIV']['rs']['RS-01'] = 'Serbia';`

Ich habe nun noch folgende Länder ausfindig machen können, denen auch der Nicht-Eintrag fehlt (habe allerdings nur die in der ISO_3166-2 mit der subdivisions.php verglichen, die explizit keine Subdivisions haben):

```
$GLOBALS['TL_LANG']['DIV']['ax']['AX-01'] = 'Åland Islands';
$GLOBALS['TL_LANG']['DIV']['cw']['CW-01'] = 'Curaçao';
$GLOBALS['TL_LANG']['DIV']['gg']['GG-01'] = 'Guernsey';
$GLOBALS['TL_LANG']['DIV']['im']['IM-01'] = 'Isle of Man';
$GLOBALS['TL_LANG']['DIV']['je']['JE-01'] = 'Jersey';
$GLOBALS['TL_LANG']['DIV']['rs']['RS-01'] = 'Serbia';
$GLOBALS['TL_LANG']['DIV']['mf']['MF-01'] = 'St. Martin';
$GLOBALS['TL_LANG']['DIV']['sx']['SX-01'] = 'Sint Maarten';
```

**Comment by aschempp** [comment]
Die Länder scheinen "neuer" zu sein als unsere Subdivisions-Datei. Hast du überprüft ob diese Länder auch wirklich keine Subdivisions haben? Und haben wir vielleicht noch Subdivisions in unsere Liste für Länder die es gar nicht mehr gibt?

**Comment by manjarco** [comment]
Die Frage ist, ob die komplette ISO 3166-2 gespiegelt wird/werden soll. Wie seid ihr bisher da vorgegangen?

Man stößt dann ja auf Probleme wie dieses:

> The Republic of Kosovo unilaterally declared independence on 17 February 2008, but Serbia continues to claim it as part of its own sovereign territory. There is no ISO 3166 country code for Kosovo, however "XK", a self assigned code is used by many international organisations.
[https://en.wikipedia.org/wiki/ISO_3166-2:RS#cite_note-1](url)

**Comment by aschempp** [comment]
Bei der Liste der Länder richten wir uns nach Contao, und soweit mir bekannt geht das nach der offiziellen ISO/UNO-Norm. Ich musste auch schon bei einem System "Tibet" als Land hinzufügen, weil die Kundin im esoterischen Bereich tätig war. Aber sowas können wir nicht lösen, das soll die UNO lösen 😉 

Ich konnte leider keine technische Datenquelle finden. Vielleicht müssen wir die Daten für bekannte, fehlende Länder aus Wikipedia zusammentragen? https://en.wikipedia.org/wiki/ISO_3166-2

**Comment by manjarco** [comment]
Stimmt, solche Fälle muss und kann man wenn, dann nur für den Einzelfall lösen.

Es geht im Grunde auch "nur" um die Subdivisions (da die Contao-Liste korrekt zu sein scheint). Und da weicht die isotope-Liste von der ISO-Liste ab. Eine verlässliche Datenquelle, die nicht ein paar hundert Euro im Jahr kostet konnte ich auch nicht finden. Woher sind die Daten denn bisher gekommen?

Wenns nur händisch geht kann ich mich die Tage da mal dran geben.

**Comment by aschempp** [comment]
Ich denke die Quelle war der Link im Code, welcher wohl nicht mehr funktioniert. Daher die Vermutung auf "händisch" 😢

**Comment by aschempp** [comment]
Ich habe die genannten Subdivisions in cf1740036405f1e92eccf4c0699c4f973fed1028 mal hinzugefügt. Wir können die ja immer noch jederzeit überarbeiten 😊
