### ISSUE TITLE
Rechnungsadresse wird als Versandadresse an Paypal übergeben

### ISSUE THREAD

**Issue by manjarco** [isotope/core#2079]
Gibt der Kunde eine von der Rechnungsadresse abweichende Versandadresse im Checkout an wird nicht diese an Paypal weitergegeben sondern die Rechnungsadresse. Das kann Kunden verwirren, da Paypal einen Hinweis einblendet, dass das die Versandadresse sei, die von der ursprünglichen Website übertragen wurde und man sie bei Bedarf dort ändern soll (was dann ja nicht geht, man hat sie ja schon korrekt angegeben).

**Comment by aschempp** [comment]
Leider unterstützt PayPal nur eine einzelne Adresse (bzw. so ist die Schnittstelle aktuell implementiert). Wenn man nicht angemeldet ist, wird diese Adresse als Rechnungsadresse verwendet. Ich bin mir also nicht sicher ob eine entsprechende Änderung Sinn macht. Eigentlich müsste PayPal ja nie nach der Lieferadresse fragen, diese Info wurde ja schon in Isotope erfasst…?

**Comment by manjarco** [comment]
Du hast mit allem Recht. Paypal fragt ja auch gar nicht nach einer Adresse sondern bekommt sie von Isotope. Allerdings verwirrt diese Mitteilung die Kunden, wenn sie zwei verschiedene Adressen angegeben haben (wie ich hier mal beispielhaft):

![Bildschirmfoto 2019-09-30 um 16 54 10](https://user-images.githubusercontent.com/274524/65902505-de080300-e3ba-11e9-8c82-b4127f5ccfa3.png)

Kunde eines Kunden ist dadurch dann zurück zu isotope gegangen, hat die Adresse kontrolliert, sie für richtig befunden, dann wieder zu paypal… hin und her. Und hat dann den Kauf abgebrochen (z.T. sehr teure Produkte, die weltweit verschickt werden, da will man kein Risiko eingehen).

**Comment by fritzmg** [comment]
Ich finde auch, dass Isotope hier die Lieferadresse an das Template übergeben sollte, falls vorhanden, andernfalls die Rechnungsadresse.

**Comment by aschempp** [comment]
Dieses gleiche Problem haben andere Systeme auch: https://wordpress.org/support/topic/shipping-address-sent-to-paypal-instead-of-billing-address/#post-10371707

Hier wird das umgekehrte gemacht, was auch nicht zielführend ist. Ich denke wir müssen dies einfach so lassen, jede Änderung wäre für andere wieder falsch. Schlussendlich lässt sich das über das `iso_payment_paypal` Template frei anpassen, z.B. auch die Adresse entfernen (was ggf. aber dazu führt dass die Käuferin diese bei PayPal nochmals eingeben muss).
