### ISSUE TITLE
Neues Attribut führt zu Darstellungsfehler im Backend

### ISSUE THREAD

**Issue by Mynyx** [isotope/core#2080]
Wenn ein neues Attribut vom Typ `Textfeld` in der Feldgruppe `Preis-Einstellungen` erstellt wird, führt dies zu einem Darstellungsfehler im Backend.

Dadurch werden die anderen Felder in der Feldgruppe `Preis-Einstellungen` überlagert und es können bei diesen keine Eingaben mehr getätigt werden.

**Comment by manjarco** [comment]
Hast du schon probiert in der Produkttyp-Einstellung dem Attribut/Feld unter "Ausrichtung" eine der contao-eigenen Klassen ([https://docs.contao.org/books/api/dca/palettes.html#arranging-fields](url)) mitzugeben?
