### ISSUE TITLE
Nur ID statt Wert in Liste und Reader, wenn Gruppe in Attribut

### ISSUE THREAD

**Issue by DanEi75** [isotope/core#2082]
Ein Fehler ist mir jetzt schon häufiger begegnet und mittlerweile habe ich die Ursache gefunden:

Bei einem eigenen Attribut, wo der **Optionen-Manager** verwendet wird, wird im Frontend (Liste und Reader) immer die ID und nicht der Wert angezeigt, wenn im Attribut mindestens ein **Gruppen-Eintrag** vorhanden ist und nicht nur Optionen. 

Sobald die Gruppe deaktiviert ist, wird der eingegebene Wert angezeigt.

Contao 4.4.43 / Isotope 2.6.2

**Comment by aschempp** [comment]
bezieht sich dies auf ein Attribut das im Template mit `generateAttribute()` ausgegeben wird? Also nicht auf ein Frontend-Attribut?

**Comment by DanEi75** [comment]
Genau. 

FE-Ausgabe via iso_list_default, iso_list_variants und iso_reader_default sind in meinem Fall betroffen, immer mit generateAttribute(). 

Funktioniert alles korrekt, aber sobald eine Gruppe in der Attributsdefinition drin ist, nicht mehr. Unabhängig, ob Checkbox/Select-Variante, Mehr- oder Einfachauswahl (für BE).
