### ISSUE TITLE
wrong breadcrumb

### ISSUE THREAD

**Issue by asaage** [isotope/core#2083]
The breadcrum does not work as expected for me.
I have set up this tree:

- home
- products
    - cat A
    - cat B
        - cat B1
        - cat B2
    - cat C
- product_reader

All the category pages only contain a productlist and are configured to use the reader page (product_reader).

Issue 1: the last item in the breadcrumb is not replaced it's allways ```<li class="active last">product_reader</li>```
Issue 2: the deepest category is removed from the breadcrumb so the breadcrumb of productdetail of a B2 Product renders like this:
```Root >> products >> catB >> product_reader```
But i expect:
```Root >> products >> catB >> catB2 >> Product-title```

It seems im stuck here https://github.com/isotope/core/blob/master/system/modules/isotope/library/Isotope/Frontend.php#L530-L535
Any ideas? Am I missing something?
Versions: 4.8.3 / 2.6.2 - no customized templates

**Comment by aschempp** [comment]
If the code returns on that line, it must mean there is either no product alias in the URL, or no product is found with that alias?

**Comment by asaage** [comment]
That is not the case

- the reader displays the correct product
- the ```<head><title>``` contains the product-name
- meta-description works as well

At least i am able to work around the first issue
- if i give the readerpage a name of ```{{product::name}}```  or
- if i place the breadcrumb **after** the product reader (i tried different combinations like module in article, module in layout, module in rootcontent-article)

Both solutions not very satisfying...

nevertheless, the deepest category is still missing in the breadcrumb although it is marked as ```.trail``` in the main-navigation.

**Comment by asaage** [comment]
Something similar happens on my checkout-page...

Breadcrumb above checkout-module:
```Site  →  shop  →  checkout```

Breadcrumb below checkout-module:
```Site  →  shop  →  Step 3 of 4 (Payment) - checkout```

expected:
```Site  →  shop  →  checkout  →  Step 3 of 4 (Payment)```

**Comment by asaage** [comment]
I reverted back to "no separate detail-page".
The contao-core Breadcrumb seems to be a kind of quirky thing.

For example: if you work with articles and show them as teaser then open that Teaser your breadcrumb will look like ...PageName → ArticleTitle

**Comment by asaage** [comment]
I reverted back to "no separate detail-page".
That leaves me for some strange reason now with a active (not clickable) category and no ProductTitle...
The contao-core Breadcrumb seems to be a kind of quirky thing.

For example: if you work with articles and show them as teaser your breadcrumb will look like 
```... → PageTitle```
then open that Teaser your breadcrumb will look like
```... → PageName → ArticleTitle```
To achive that with FAQ, News and Events you will always have to put a ReaderPage as Child of the ListPage.

I Did not try but i guess if you follow the later concept you will end up with the desired bredcrumb
```... → CategoryPageName → ProductTitle``` but that defeats the whole purpose of **a/one** dedicated detailpage if you need one for each category.

**Comment by sixtmedia** [comment]
I've already tried to put a ReaderPage as child of a ListPage. It doesn't change the breadcrumb path.

I have another Installation ( Contao 4.4.34 Isotope 2.5.10 ) where the breadcrumb is correct. But I have not yet discoverd the reason, why it changed in the latest version.

**Comment by cmichael-de** [comment]
I got the same issues like @asaage  and @sixtmedia . After I did an update from Contao 3.5.36 and Isotope Version 2.4.6 to Contao 4.4.45 and Isotope Version 2.6.3 there is one item less in the breadcrumb items array.  Here you can see the print_r($items) from old (correct working) version and new (wrong) version.

**(Working:)** Contao 3.5.36 and Isotope Version 2.4.6 
<pre>
`
            [items] => Array
                (
                    [0] => Array
                        (
                            [isRoot] => 1
                            [isActive] => 
                            [href] => 
                            [title] => stilwohnen
                            [link] => stilwohnen
                            [data] => Array
                                (
                                    [id] => 2
                                    [pid] => 1
                                    [sorting] => 128
                                    [tstamp] => 1547205140
                                    [title] => Biedermeier Möbel gefertigt mit Qualität, hochwertige Stilmöbel
                                    [alias] => index
                                    [type] => regular
                                    [pageTitle] => Biedermeier Möbel hochwertig nachgebaut - individuelle Stilmöbel
                                    ...
                                    [trail] => Array
                                        (
                                            [0] => 1
                                            [1] => 2
                                        )

                                )

                            [class] => first
                        )

                    [1] => Array
                        (
                            [isRoot] => 
                            [isActive] => 
                            [href] => arbeitszimmer.html
                            [title] => Biedermeier Arbeitszimmer - Stilmöbel individuell angefertigt
                            [link] => Arbeitszimmer
                            [data] => Array
                                (
                                    [id] => 4
                                    [pid] => 1
                                    [sorting] => 384
                                    [tstamp] => 1541175730
                                    [title] => Arbeitszimmer
                                    [alias] => arbeitszimmer
                                    [type] => regular
                                    [pageTitle] => Biedermeier Arbeitszimmer - Stilmöbel individuell angefertigt
                                   ...
                                    [trail] => Array
                                        (
                                            [0] => 1
                                            [1] => 4
                                        )

                                )

                            [class] => 
                        )

                    [2] => Array
                        (
                            [isRoot] => 
                            [isActive] => 
                            [href] => arbeitszimmer/biedermeier-schreibtische.html
                            [title] => Biedermeier Schreibtische - elegante Möbel für entspanntes Arbeiten
                            [link] => Biedermeier Schreibtische
                            [data] => Array
                                (
                                    [id] => 52
                                    [pid] => 4
                                    [sorting] => 128
                                    [tstamp] => 1525264463
                                    [title] => Biedermeier Schreibtische
                                    [alias] => arbeitszimmer/biedermeier-schreibtische
                                    [type] => regular
                                    [pageTitle] => Biedermeier Schreibtische - elegante Möbel für entspanntes Arbeiten
                                  ...
                                    [trail] => Array
                                        (
                                            [0] => 1
                                            [1] => 4
                                            [2] => 52
                                        )

                                )

                            [class] => 
                        )

                    [3] => Array
                        (
                            [isRoot] => 
                            [isActive] => 1
                            [href] => arbeitszimmer/biedermeier-schreibtische.html
                            [title] => Detailseite
                            [link] => Detailseite
                            [data] => Array
                                (
                                    [id] => 91
                                    [pid] => 52
                                    [sorting] => 1312
                                    [tstamp] => 1504784304
                                    [title] => Detailseite
                                    [alias] => arbeitszimmer/biedermeier-schreibtische
                                    [type] => regular
                                    [pageTitle] => 
                                   ...
 </pre>
`

**(Wrong:)** Contao 4.4.45 / Isotope Version 2.6.3
<pre>
`
            [items] => Array
                (
                    [0] => Array
                        (
                            [isRoot] => 1
                            [isActive] => 
                            [href] => 
                            [title] => stilwohnen
                            [link] => stilwohnen
                            [data] => Array
                                (
                                    [id] => 2
                                    [pid] => 1
                                    [sorting] => 128
                                    [tstamp] => 1547205140
                                    [title] => Biedermeier Möbel gefertigt mit Qualität, hochwertige Stilmöbel
                                    [alias] => index
                                    [type] => regular
                                    [pageTitle] => Biedermeier Möbel hochwertig nachgebaut - individuelle Stilmöbel
                                     ...
                                    [trail] => Array
                                        (
                                            [0] => 1
                                            [1] => 2
                                        )

                                )

                            [class] => first
                        )

                    [1] => Array
                        (
                            [isRoot] => 
                            [isActive] => 
                            [href] => arbeitszimmer.html
                            [title] => Biedermeier Arbeitszimmer - Stilmöbel individuell angefertigt
                            [link] => Arbeitszimmer
                            [data] => Array
                                (
                                    [id] => 4
                                    [pid] => 1
                                    [sorting] => 384
                                    [tstamp] => 1541175730
                                    [title] => Arbeitszimmer
                                    [alias] => arbeitszimmer
                                    [type] => regular
                                    [pageTitle] => Biedermeier Arbeitszimmer - Stilmöbel individuell angefertigt
                                    ...
                                    [trail] => Array
                                        (
                                            [0] => 1
                                            [1] => 4
                                        )

                                )

                            [class] => 
                        )

                    [2] => Array
                        (
                            [isRoot] => 
                            [isActive] => 1
                            [href] => arbeitszimmer/biedermeier-schreibtische.html
                            [title] => Detailseite
                            [link] => Detailseite
                            [data] => Array
                                (
                                    [id] => 52
                                    [pid] => 4
                                    [sorting] => 1312
                                    [tstamp] => 1504784304
                                    [title] => Detailseite
                                    [alias] => arbeitszimmer/biedermeier-schreibtische
                                    [type] => regular
                                    [pageTitle] => 
                                    ...
                                    [trail] => Array
                                        (
                                            [0] => 1
                                            [1] => 4
                                            [2] => 52
                                            [3] => 91
                                        )
                                    [hasJQuery] => 1
                                    [hasMooTools] => 
                                    [isMobile] => 
                                    [layoutId] => 5
                                    [template] => fe_page_details
                                    [templateGroup] => 
                                    [outputFormat] => html5
                                )

                            [class] => 
                        )
                    ...
`
</pre>

**Comment by aschempp** [comment]
fixed in 931f1d52ec6e8cf102565538218422d7aca4611e
