### ISSUE TITLE
Fehler im Modul Adressbuch Link "Neue Adresse anlegen"

### ISSUE THREAD

**Issue by Mynyx** [isotope/core#2084]
Wenn ein Frontend-Benutzer im Modul Adressbuch auf den Link "Neue Adresse anlegen" klickt, wird dieser auf das Loginformular des Backends (`/contao/login`) umgeleitet.

**Comment by aschempp** [comment]
sind die Weiterleitungen korrekt konfiguriert?

**Comment by Mynyx** [comment]
Welche Weiterleitungen? Bei dem Modul Adressbuch kann keine Weiterleitung konfiguriert werden?

**Comment by aschempp** [comment]
Ich kann das bei mir Lokal nicht reproduzieren. Der Link zeigt immer auf die aktuelle Seite + `?act=create`. Vielleicht liegt es an einer Erweiterung?

**Comment by JLArtdesign** [comment]
Nein, an einer Erweiterung kann es nicht liegen.

Ich habe bei einem Kunden dasselbe Problem. 

Sowohl der Link „Neue Adresse anlegen“, als auch der Link „Bearbeiten“ leitet fehlerhaft um.
Die Links zeigen zwar auf z.B. „www.domain.de/adressbuch.html?act=create“ und 
„www.domain.de/adressbuch.html?act=edit&address=1“, man landet aber trotzdem im Backend-Login.

Es sind auch keinerlei Domainumleitungen z.B. in der .htaccess angelegt.

Ich konnte den Fehler auch bei einer kompletten Neuinstallation, nur nacktes Contao 4.4.40 bis 4.4.44 und isotope 2.5.14 bis 2.16.2 ohne sonstige Erweiterungen, reproduzieren.
Was ich ebenfalls getestet habe sind verschiedene PHP-Versionen 7.1 und 7.2.
Auch auf zwei komplett unterschiedlichen Webservern (Hetzner und webgo) ist der Fehler vorhanden.

Von daher kann ich eine Erweiterung als Fehlerquelle auschließen.

**Comment by goransi** [comment]
hello
I have contao 4.4.44 and Isotope 2.63. After last update in user pages none of user modules not loaded!
Does anybody can check own shops!?

**Comment by goransi** [comment]
Hello,
Yes I have the same problem :-(
any solution?

**Comment by goransi** [comment]
any news, issue update?

**Comment by aschempp** [comment]
I'm unable to reproduce this issue locally. Please debug this on your server and provide a pull request to fix it 😊

**Comment by Mynyx** [comment]
@goransi Which Contao version do you use?

**Comment by goransi** [comment]
4.4.44

**Comment by Mynyx** [comment]
@JLArtdesign is using 4.4.40 to 4.4.44 and I'm using 4.4.44, too. 

Maybe the issue occurs only with Contao 4.4 and not 4.8?

@aschempp Have you tried to reproduce it with Contao 4.4?

**Comment by goransi** [comment]
it's copy of real shop
https://dev1.vpsline.eu/contao
u: aschempp
p: aschempp

**Comment by goransi** [comment]
yes I have 4.4.44 and isotope 2.6.3
tested on 4.8. the same issue!

**Comment by aschempp** [comment]
I use 4.4.41 as well locally.
Again, this is open source, so anyone can debug the issue on their local machine. Feel free to find/pay a developer of your choice if you need help finding the issue in the code. A pull request is very welcome, but I'm currently off to holiday so there won't be much happening here if you need this fixed quickly 😉

**Comment by goransi** [comment]
does any body have fixed it?

**Comment by JLArtdesign** [comment]
Workaround:

Jeweils bei den Links "&rt={{request_token}}" im Template "mod_iso_addressbook.html" ergänzen:

Zeile 10:
`<p><a class="add" href="<?php echo $this->addNewAddress; ?>&rt={{request_token}}" title="<?php echo $this->addNewAddressLabel; ?>"><?php echo $this->addNewAddressLabel; ?></a></p>`

Zeile 18:
`<a class="edit" href="<?php echo $address['edit_url']; ?>&rt={{request_token}}" title="<?php echo $this->editAddressLabel; ?>"><?php echo $this->editAddressLabel; ?><span class="invisible"> <?php echo $address['label']; ?>`

Damit ist der Fehler behoben.
Getestet mit 
Contao 4.4.40 / isotope 2.5.14
und
Contao 4.8.5 / isotope 2.6.3

Siehe auch Fehler #2091

**Comment by goransi** [comment]
it's work nice!! :-)
I have tested on contao 4.4.44 -> isotope 2.6.3 and contao 4.8.5 -> isotope 2.6.3
Best regards to all!
Thank you ...

**Comment by aschempp** [comment]
see https://github.com/codefog/contao-haste/commit/67435863412c2829c9e45f53d637db4c6e1d79b1

**Comment by aschempp** [comment]
fixed in Haste 4.24.3
