### ISSUE TITLE
Produktgruppen-Modal: Untergruppen lassen sich nicht auskalppen

### ISSUE THREAD

**Issue by mpitz** [isotope/core#2087]
Contao: 4.4.44
Isotope: 2.6.2

Man kann über Produktgruppen, verschachtelte Gruppen, also mit Untergruppen anlegen:
![image](https://user-images.githubusercontent.com/6831223/67075943-7dcfda00-f18c-11e9-9038-2fd4061d4bf1.png)

Allerdings kann man beim Zuweisen der Produkte zur Gruppe diese Untergruppen nicht mehr auswählen, da sich im Modal die Untergruppen nicht ausklappen lassen:
![image](https://user-images.githubusercontent.com/6831223/67075959-87594200-f18c-11e9-828e-16d96381b302.png)

**Comment by JLArtdesign** [comment]
Ich habe bei einer Installation das gleiche Problem.
Es wurden verschiedene Isotope-Versionen getestet 2.5.14-2.6.2.

Vorrübergehend "gelöst" habe ich das Problem dann, indem ich bei Contao auf die Version 4.4.40 zurück gegangen bin.
Kurz gesagt:
Bei Contao in der Version 4.4.40 funktioniert die Gruppenauswahl, ab der 4.4.41 nicht mehr.

Ich gehe daher davon aus, dass das Problem nicht bei Isotope, sondern bei Contao liegt.

**Comment by aschempp** [comment]
Tatsächlich ist das ein Fehler in Contao 4.4, siehe https://github.com/contao/contao/pull/1020
In 130d29d640d665e642330d287f20b117526df898 habe ich eine temporäre Lösung eingebaut.
