### ISSUE TITLE
Varianten-Attribute wie z.B. Select-Menü lediglich für Beschreibung verwenden können

### ISSUE THREAD

**Issue by DanEi75** [isotope/core#2089]
Bei Varianten werden eigene Attribute wie Select-Menü immer als eindeutige Identifikatoren verwendet. Das ist allerdings oft gar nicht gewünscht.

**Beispiel:** 

- Ich erstelle ein Select-Menü, wo ich dann pro Variante dann im BE auswählen kann, ob z.B. eine Anleitung vorhanden ist. Die Auswahl wäre also lediglich eine beschreibende Funktion, welche die Verwaltung im BE vereinfacht.
- **Folge:** Der automatische Link zur Variante ist https://xyz.ch/shop/article1.html?color=1&**manual=2**
- Soweit ich getestet habe, wird die richtige Variante aber auch angezeigt, wenn der Manual-Parameter in diesem Beispiel gelöscht wird. Color ist als Identifikator ausreichend.
- Wird ein Produkt in den Warenkorb gelegt, muss - so wie es jetzt ist - der Attributwert, der ja bei einem Varianten-Attribut wie z.B. Select-Menü leider immer zwingend ist, als Feldwert mitgeliefert werden, sonst wird moniert, dass der Wert fehlt. Aber es soll ja eben nur eine zusätzliche Info sein und keine Identifikation. Man kann es zwar als Hidden-Feld einfügen, aber es macht sowohl die Varianten-URL wie auch die zwingend benötigen Feldwerte für den Warenkorb-Eintrag unnötig lang.

**Idee:** Bei der Definition des Attributes auswählen, ob es die Variante definiert oder nur zusätzlich beschreibt. Wenn Definition, dann soll es zwingender Teil der Varianten-URL sein und der Feldwert muss für den Warenkorb-Eintrag vorhanden sein. Wenn nur Beschreibung, dann nicht. Zudem wäre ein beschreibendes Attribut auch optional möglich.

Das wäre für meine Projekte eine extreme Vereinfachung und würde zudem die URL sehr verschlanken und vor 404-Fehler vorbeugen.

Danke für die Abklärung, ob diese Anpassung in einer zukünftigen Version umgesetzt werden könnte ;-).

**Comment by aschempp** [comment]
Diese Definition ist doch bereits möglich? Du kannst auf dem Attribut definieren ob es für die Variantenauswahl gilt, nur für die Frontend-Bedienung oder keines von beidem.

**Comment by DanEi75** [comment]
Hallo Andreas

Damn, du hast völlig recht! Ich hatte die völlig irrige Annahme, dass die Checkbox für die Varianten bei der Attributsdefinition dazu dient, sie überhaupt als Variantenattribut auswählen zu können.

Habe das nun bei den gewünschten Attributen deaktiviert und es wird absolut korrekt angezeigt.

Sorry, nichts für ungut!
