### ISSUE TITLE
Sortierung in Produktvarianten-Liste

### ISSUE THREAD

**Issue by bastlwastl** [isotope/core#2090]
Produkte in der Produktvarianten-Liste lassen sich nur nach Datum, Artikelnummer, Name oder Preis sortieren.
Eine manuelle Sortierung wie bei der Produktliste ist nicht möglich.
Ist das ein Fehler oder besteht die Möglichkeit der manuellen Sortierung bei der Produktvarianten-Liste nicht?
Besteht vielleicht die Möglichkeit nach einem Attribut zu sortieren?
Ich dachte hier an ein Attribut vom Typ Textfeld bei dem ich einfach eine Zahl angebe, nach dem dann die Produktvarianten sortiert werden.

**Comment by aschempp** [comment]
Das ist korrekt, Varianten lassen sich so nicht sortieren, weil Varianten keiner Seite zugewiesen sind. Du kannst beliebige Attribute zum sortieren verwenden, dazu gibt es eine Einstellung in den Attributen.

**Comment by bastlwastl** [comment]
> Du kannst beliebige Attribute zum sortieren verwenden, dazu gibt es eine Einstellung in den Attributen.

Ja perfekt! Damit lässt sich so ziemlich alles umsetzten... Danke!
