### ISSUE TITLE
Token-Warnung bei Klick auf Adressbuch-Links "Neu" und "Bearbeiten"

### ISSUE THREAD

**Issue by sixtmedia** [isotope/core#2091]
Ich bekomme beim Versuch eine neue Adresse im Adressbuch anzulegen - oder eine bestehende Adresse zu bearbeiten - immer eine Token-Warnung ausgegeben.
Der Link heißt korrekt "...?act=crate" allerdings ohne Token-String.

Ich habe den Token über den inserttag ( &rt={{request_token}} )bei den Links im Template ergänzt und konnte das Problem so beheben.

Kann das jemand reproduzieren? Oder stimmt was nicht in meinen EInstellungen?

Contao 4.8.4
Isotope 2.6.3 

![image](https://user-images.githubusercontent.com/8387359/68463176-59f13880-020e-11ea-96fd-d516a9580d36.png)

**Comment by aschempp** [comment]
passiert das im Frontend oder im Backend?

**Comment by sixtmedia** [comment]
Das passiert im Frontend.

**Comment by JLArtdesign** [comment]
Kann ich bestätigen.
Der Workaround mit der Ergänzung  "&rt={{request_token}}" bei den Links funktioniert auch bei Contao 4.4.40 und isotope 2.5.14

Siehe #2084

**Comment by aschempp** [comment]
Duplicate of #2084
