### ISSUE TITLE
Questions about db-tables

### ISSUE THREAD

**Issue by xcy7e** [isotope/core#2092]
I am building a desktop application for a customer using isotope. It's not clear (to me) how the data in the db is related. I did not find a database documentation and since the webshop is not as popular as it deserves, I couldn't find answers to the following

**Questions:**
- What's the [`pid`] column?
- How are `prices` related to `products`? (`tl_iso_product_price` does not use a `[product_id]` column)
- How are taxes related to products? (Neither `tl_iso_tax_rate` nor `tl_iso_tax_class` uses a `[product_id]` column, is there a relation table?)
- How are products and pages related?
- What is a `product_collection`?
- Is there any compressing used when serving the images or are they being shown 'as-is'?

If anyone of you can answer at least one of this questions I'd really, really appreaciate it and I **promise** I will contribute to a non-existing db-structure documentation in the near future!

**Comment by richardhj** [comment]
> * What's the [`pid`] column?

Reference on "parent id", as for example: an item belongs to an order (item.pid=order.id)

> * How are `prices` related to `products`? (`tl_iso_product_price` does not use a `[product_id]` column)

tl_iso_product_price.pid=tl_iso_product.id

A product may have many prices (varying for member group/quantity). Prices are only available in `tl_iso_product_price` if the product type uses "advanced prices".

> * How are taxes related to products? (Neither `tl_iso_tax_rate` nor `tl_iso_tax_class` uses a `[product_id]` column, is there a relation table?)

If I remember correctly, you have to go via the `tl_iso_product_collection_surcharge` table. A tax is a surcharge.
`tl_iso_product_collection_surcharge.pid=tl_iso_product_collection.id`

> * How are products and pages related?

I guess the relations are represented in the `tl_iso_product_category` table. NB: a front end module "product list" can also show products on a sub-page, so you may have to check page inheritance.

> * What is a `product_collection`?

A product collection may be a cart or an order. Once a user checks out, the cart gets transformed into an order. Orders are immutable (they have different model classes).

> * Is there any compressing used when serving the images or are they being shown 'as-is'?

Original images get uploaded to /isotope dir while they are served as they may get served compressed. This handles Contao.

**Comment by richardhj** [comment]
The database structure is based on the definition made in the DCA (data configuration array) files. You can find some information under https://docs.contao.org/dev/reference/dca/config/#reference.

**Comment by xcy7e** [comment]
Thank you richard for the insight! This is extremely helpful. One last question I may not stated clearly is, where the actual price is being stored. This might be a decimal value. Am I right, assuming `product_price` is parent of `product_pricetier` (storing the actual price), both being related by the pid?

**Comment by richardhj** [comment]
Do you use the API, or write your application in PHP? The product price can be fetched via `IsotopeProduct::getPrice($quantity=10)->getAmount()`.

The db structure:
When `tl_iso_producttype.prices = 0` (where `tl_iso_product.type=tl_iso_producttype.id`) the so-called "advanced pricing" is disabled. This means, only one plain price applies to the product.
When advanced pricing is enabled, the product price is subject to change by means of the quantity, or the member group (VIP customers may have different prices).

`tl_iso_product_pricetier` has the actual price (float/decimal) as well as the minimum quantity the price applies to. 
`tl_iso_product_pricetier.pid=tl_iso_product_price.id` 

`tl_iso_product_price` holds the additional constraints (to which config id, which member group does this pricing apply, from when until which date does the pricing apply?).  If you don't use these constraints, the values are `0`. 
`tl_iso_product_price.pid tl_iso_product.id`

**Comment by xcy7e** [comment]
I am unable to use an API or PHP. I am building a product-manager in C# that requires offline-synchronization to manage data offline. Therefor I need to touch the data directly. Sadly.

The provided information, to say the least, will help me alot!
