### ISSUE TITLE
Deferred Image Resizing Funktion

### ISSUE THREAD

**Issue by michaelgawlik** [isotope/core#2094]
**Rahmenbedingungen:**
Contao 4.8.5
Isotope 2.6.3
PHP 7.3.11

mit aktivierten Debug-Modus bekomme ich folgenden Fehler auf Listen- / Leserseiten:

`Uncaught PHP Exception ErrorException: "Warning: getimagesize( ... ): failed to open stream: No such file or directory" at ...`

Bild gibts dort tatsächlich nicht. Aber auf der Seite gibts auch keine Probleme, richtige Bilder sowie richtige Bildgrößen.

**Comment by fritzmg** [comment]
Isotope needs to apply the same fix as here: https://github.com/codefog/contao-social_images/issues/27#issuecomment-549553841

**Comment by aschempp** [comment]
Do I assume correctly that https://github.com/isotope/core/pull/2085 fixes this?

**Comment by fritzmg** [comment]
I think so :)
