### ISSUE TITLE
Stock / Product availability

### ISSUE THREAD

**Issue by xcy7e** [isotope/core#2095]
I don't see a field in the BE to define how many items are on stock. Neither do I see such column in the database. I see an extension available "cfg_isotope_stock_management" but when searching this repo's issues I find comments from 2013 stating this feature will be added to the isotope core so I assume it's already there and I just missed it.

**Comment by Toflar** [comment]
No, there's never been any addition of stock management to Isotope.
There are a few third party products, e.g. https://shop.codefog.pl/product/isotope-stock-management.html.

**Comment by xcy7e** [comment]
Thanks for your reply. To clearify this, using vanilla isotope, a product can be ordered an infinite amount of times?

**Comment by Toflar** [comment]
Yes.
