### ISSUE TITLE
Custom product field attributes get lost during product option widgets generation

### ISSUE THREAD

**Issue by qzminski** [isotope/core#2096]
If I create a custom field in `tl_iso_product` and give it some attributes:

```php
$GLOBALS['TL_DCA']['tl_iso_product']['fields']['foobar'] = [
    'label' => &$GLOBALS['TL_LANG']['tl_iso_product']['foobar'],
    'exclude' => true,
    'inputType' => 'select',
    'options' => ['foo', 'bar'],
    'eval' => ['mandatory' => true, 'includeBlankOption' => true],
    'attributes' => ['legend' => 'shipping_legend', 'customer_defined' => true, 'ajax_option' => true],
    'sql' => ['type' => 'string', 'length' => 8, 'notnull' => false],
];
```

those attributes will at some point get lost when generating product option widgets:

https://github.com/isotope/core/blob/master/system/modules/isotope/library/Isotope/Model/Product/Standard.php#L639

which then are inaccessible at a later stage:

https://github.com/isotope/core/blob/master/system/modules/isotope/library/Isotope/Model/Product/Standard.php#L686

------

Currently the workaround is to define an extra form field type that will preserve attributes, but also register a new attribute:

config.php:
```php
$GLOBALS['TL_FFL']['foobar_select'] = \FoobarBundle\Widget\SelectWidget::class;
\Isotope\Model\Attribute::registerModelType('foobar_select', \FoobarBundle\Attribute\SelectMenu::class);
```

SelectWidget.php:
```php
namespace FoobarBundle\Widget;

class SelectWidget extends \Contao\FormSelectMenu
{
    /**
     * @inheritDoc
     */
    public static function getAttributesFromDca($arrData, $strName, $varValue = null, $strField = '', $strTable = '', $objDca = null)
    {
        $attributes = parent::getAttributesFromDca($arrData, $strName, $varValue, $strField, $strTable, $objDca);
        $attributes['attributes'] = $arrData['attributes']; // preserve the attributes

        return $attributes;
    }
}
```

SelectMenu.php
```php
namespace FoobarBundle\Attribute;

class SelectMenu extends \Isotope\Model\Attribute\SelectMenu
{
}
```

------

PS. It is not enough to register the attribute like that:

```php
\Isotope\Model\Attribute::registerModelType('foobar_select', 'Isotope\Model\Attribute\SelectMenu');
```

because the class `Isotope\Model\Attribute\SelectMenu` is already assigned to `select`:

https://github.com/isotope/core/blob/master/system/modules/isotope/library/Isotope/Model/Attribute.php#L173

**Comment by aschempp** [comment]
What exactly is the problem here? Why do you not read from `$GLOBALS['TL_DCA']` to fetch the attribute values?

**Comment by qzminski** [comment]
The problem is that the attribute `ajax_option` is not accessible at this stage: 

https://github.com/isotope/core/blob/master/system/modules/isotope/library/Isotope/Model/Product/Standard.php#L686

because it gets lost insigde `Widget::getAttributesFromDca()` method.

**Comment by aschempp** [comment]
what if you write it to the `eval` field?

**Comment by qzminski** [comment]
You mean like `'eval' => ['attributes' => ['ajax_option' => true]]`? That _might_ work but does not look like a correct solution to me, rather a workaround.

**Comment by aschempp** [comment]
sorry for the late feedback. Are you saying this is a bug, because the flag is ignored in the Standard product?

**Comment by qzminski** [comment]
Yes I think it's a bug. The attributes should be preserved imo.
