### ISSUE TITLE
attributeOption.php: priceformat

### ISSUE THREAD

**Issue by ChrMue** [isotope/core#2097]
Warum lässt sich das Label bei Options nicht frei festlegen und ist hardgecoded mit "%s (%s)"?
In dem aktuellen Projekt werden gleischpreisige Optionen gruppiert und der Preis in dem Gruppenlabel ausgegeben. Daher ist die Preisangabe bei der Auflistung der Options überflüssig (und Platzverschwendung), lässt sich aber so leider nicht entfernen.

**Comment by aschempp** [comment]
wie würdest du es denn konfigurierbar machen?

**Comment by asaage** [comment]
Hab einen ziemlich ähnlichen Fall und bin dabei auf diesen post gestoßen - die Lösung dort ist aber auch suboptimal.
https://community.contao.org/de/showthread.php?70762-Darstellung-Aufpreis-von-Optionen

Gut wäre denke ich, wenn man den Wert für ```$blnPriceInLabel``` aus einer shop-configuration holen könnte, oder von mir aus auch aus einer dcaconfig. https://github.com/isotope/core/blob/master/system/modules/isotope/library/Isotope/Model/AttributeOption.php#L57

**Comment by aschempp** [comment]
Fixed in 7bbd8ef4bd29f8acba81c7403df0ba469f32e4eb

**Comment by asaage** [comment]
Kann mir jemand einen Tip geben, wie die Sprachdatei heißen muss und wo die abzulegen ist?
Ich krieg's irgendwie nicht hin. 🤔

**Comment by aschempp** [comment]
Das siehst du doch im angemerkten Commit (siehe vorheriger Kommentar)

**Comment by asaage** [comment]
2.7.0 ist noch nicht released 🤦‍♂️ da kann ich ja ewig probieren.
