### ISSUE TITLE
Getting error on fresh Contao 4.8.5 installation using Install Tool via Contao Manager

### ISSUE THREAD

**Issue by rhymeadam** [isotope/core#2098]
Attempted to load class "MultilingualModel" from the global namespace. Did you forget a "use" statement?

https://github.com/isotope/core/blob/master/system/modules/isotope/library/Isotope/Model/AttributeOption.php#L37

**Comment by aschempp** [comment]
Which version of `DC_Multilingual` is installed on your system? You should see that in the dependencies of Isotope.

**Comment by rhymeadam** [comment]
Hey Andreas, thanks for the quick reply.  In the composer.json file it's saying "terminal42/dc_multilingual": "~2.0".  All I did was install Contao via Contao Manager, then used Contao Manager to install Isotope, then when it was finished, it was asking me to continue to the Install Tool.  Clearing the production and dev cache worked, actually, but I feel like someone who didn't know much about Contao wouldn't know to do that immediately.

**Comment by aschempp** [comment]
That's very strange, as the cache should be cleared on installation. But only the production cache, so if you got that error in dev, that might be because the cache was not up to date. I'm closing this as I assume it's not an Isotope issue, let me know if you find something more.
