### ISSUE TITLE
abgeschlossene Bestellungen lassen sich wieder in den Status "Neue Bestellung" zurücksetzen

### ISSUE THREAD

**Issue by swinde** [isotope/core#2100]
Hallo,
die Auflistung, im Shopbackend, für die Bestellungen hat ja verschiedene Statusausgaben wie "Neue Bestellung" "In Bearbeitung" "Versendet" usw.
Jetzt ist mir auf gefallen, das man jede Bestellung wieder in Neu zurücksetzen kann! Gerade durch das Problem im Zusammenhang mit diesem Issue https://github.com/isotope/core/issues/2058# kommt das jetzt gehäuft vor.
**Frage:** wäre es möglich eine Abfrage einzubauen, wenn das Feld "Bezahldatum" ausgefüllt ist, dann  den Status "Neue Bestellung" nicht auswählbar zu machen?
Steffen Winde

**Comment by richardhj** [comment]
Die Bestellstatus sind nutzerdefiniert, es handelt sich nicht um von Isotope-definierte Status. Das schließt eine Logik seitens Isotope aus.
Du kannst aber einien save_callback erstellen auf das "status"-Feld der Bestellung (tl_iso_product_collection) und dort die entsprechende Logik implentieren (throw exception if status==x).

**Comment by swinde** [comment]
Okay danke für Deine Antwort. 
Leider fehlen mir dazu etwas die Kenntnisse!
Ich frage mich nur gerade, wenn schon die DCA Datei tl_iso_product_collection bearbeitet werden soll, könnte das ja auch standardmäßig abgefragt werden.

**Comment by richardhj** [comment]
> Ich frage mich nur gerade, wenn schon die DCA Datei tl_iso_product_collection bearbeitet werden soll, könnte das ja auch standardmäßig abgefragt werden.

Das geht wie gesagt nicht, weil Bestellstatus in jeder Isotope-Installation abweichen (sie sind nutzerdefiniert).

Deswegen muss die Logik individualprogrammiert eingebaut werden.

Wie du einen Callback registrierst: https://docs.contao.org/dev/framework/dca/
