### ISSUE TITLE
Zahlungsart Viveum - Rechnungsnummer mit übergeben

### ISSUE THREAD

**Issue by mecintosch** [isotope/core#2101]
Aktuell wird nur die ID der Bestellung aber nicht die Rechnungsnummer an Viveum übergeben.
Es gibt ein eigenes Feld (COM) welches dazu lt. Viveum Support für die Rechnungsnummer genutzt werden kann/soll. 

In der Viveum.php habe ich bei SHA-OUT bereits ergänzt.

In der PSP.php habe ich das Feld ebenso eingefügt, nur weiß ich nicht wie ich an die Rechnungsnummer komme. Andere Werte funktionieren zB:

```
Bestell ID: 
'COM'           => $objOrder->getId()

Quelle (Warenkorb ID): 
'COM'           => $objOrder->source_collection_id
```
Als Rechnungsnummer habe ich vergeblich versucht:

```
'COM'           => $objOrder->document_number
```

Wäre, denke ich, für alle die Viveum etc. nutzen hilfreich, da die Zuordnung der Bestellung anhand der Rechnungsnummer viel einfacher ist. 

Oder kann es nicht funktionieren da Rechnungsnummer erst danach vergeben wird?

**Comment by aschempp** [comment]
> Oder kann es nicht funktionieren da Rechnungsnummer erst danach vergeben wird?

Genau so ist es. Die Rechnungsnummer wird erst nach erfolgreicher Bestellung vergeben, sonst wäre sie nicht mehr fortlaufend…
