### ISSUE TITLE
Auswertung pro Produkt (Abfrage Fehler)

### ISSUE THREAD

**Issue by operatorone** [isotope/core#2102]
Hallo, seit kurzem erhalte ich eine Fehlermeldung bei der Auswertung pro Produkt im Backend. Sie lautet wie folgt: 

`An exception occurred while executing 'SELECT IFNULL(p1.id, i.product_id) AS product_id, IFNULL(p1.name, ANY_VALUE(i.name)) AS variant_name, IFNULL(p2.name, ANY_VALUE(i.name)) AS product_name, p1.sku AS product_sku, p2.sku AS variant_sku, IF(p1.pid=0, p1.type, p2.type) AS type, ANY_VALUE(i.configuration) AS product_configuration, SUM(i.quantity) AS quantity, SUM(i.tax_free_price * i.quantity) AS total, DATE_FORMAT(FROM_UNIXTIME(o.locked), '%Y%m') AS dateGroup FROM tl_iso_product_collection_item i LEFT JOIN tl_iso_product_collection o ON i.pid=o.id LEFT JOIN tl_iso_orderstatus os ON os.id=o.order_status LEFT OUTER JOIN tl_iso_product p1 ON i.product_id=p1.id LEFT OUTER JOIN tl_iso_product p2 ON p1.pid=p2.id WHERE o.type='order' AND o.order_status>0 AND o.locked IS NOT NULL AND o.order_status=3 GROUP BY dateGroup, product_id HAVING dateGroup>=201911 AND dateGroup<=202001': SQLSTATE[42000]: Syntax error or access violation: 1305 FUNCTION web105_db5.ANY_VALUE does not exist`

Die Auswertung "Gesamt" funktioniert einwandfrei. Ein Datenbank-Update habe ich durchgeführt. Hier war nichts zu aktualisieren.

Verwende die Version 2.6.4 mit Hotfix auf 2.6.5

**Comment by operatorone** [comment]
Hat niemand eine Idee dazu?

**Comment by Toflar** [comment]
Doch, MariaDB hat keine `ANY_VALUE()` Funktion. Das ist einfach ein Bug.
