### ISSUE TITLE
Shop-Konfiguration > Konfigurationen > Bankdaten > Neues Feld: Kontoinhaber

### ISSUE THREAD

**Issue by minstyle** [isotope/core#2104]
Schön wäre es, wenn in der "Shop-Konfiguration" von Isotope im Bereich "Bankdaten" noch ein Eingabefeld "Kontoinhaber" zur Verfügung stehen würde:

![image](https://user-images.githubusercontent.com/2649562/72789783-a0163f80-3c34-11ea-8a45-33700d91839f.png)

Auch wäre es gut, wenn es hierfür ein "Simple Token", wie z. B. ##config_bankAccountHolder## gäbe.

**Comment by fritzmg** [comment]
Solche Dinge kannst du dir ja wie in Contao gewohnt selbst per DCA Änderung anlegen.

**Comment by minstyle** [comment]
Ich habe das Feld nun selbst via DCA eingebunden und lasse es via Simple Token in der entsprechenden Benachrichtigungs-E-Mail ausgeben.

Screenshot:

![image](https://user-images.githubusercontent.com/2649562/72797133-dce83380-3c40-11ea-9b73-b5ad24a8200f.png)

Wieso ist dieses Feld in Isotope denn nicht standardmäßig unter "Bankdaten" aufgeführt?

**Comment by fritzmg** [comment]
> Wieso ist dieses Feld in Isotope denn nicht standardmäßig unter "Bankdaten" aufgeführt?

Weil es nicht existiert? Oder was genau meinst du damit? ;)

**Comment by minstyle** [comment]
Ja, genau ;)

**Comment by fritzmg** [comment]
Grundsätzlich ist die Angabe eines "Kontoinhabers" nicht notwendig, bei einer Überweisung mit IBAN. Die Angabe eines dedizierten "Kontoinhabers" ist daher eher ein Relikt aus früheren Zeiten.

**Comment by minstyle** [comment]
OK, danke für die Info.

In meinem Fall benötige ich die Angabe des Kontoinhabers, da der Kunde dies so wünscht.

**Comment by fritzmg** [comment]
Na dann ist es ja gut, dass Contao so einfach anpassbar ist ;)
