### ISSUE TITLE
"Warning: array_multisort(): Array sizes are inconsistent" in Product.php - Debug Mode

### ISSUE THREAD

**Issue by theDyingMountain** [isotope/core#2107]
In my Contao 4.8, isotope 2.6.6 installation I got the an ErrorException `Warning: array_multisort(): Array sizes are inconsistent` in the Debug Mode. The problem appears when `$objProducts` contains duplicate Entries. Because of the id as key (`$arrData[$strField][$objProduct->id]`) `$arrData` is smaller than `$objProducts` [L567](https://github.com/isotope/core/blob/master/system/modules/isotope/library/Isotope/Model/Product.php#L567)

**Comment by theDyingMountain** [comment]
When I run the generated query in my database it found out that the group by cause not working because of grouped category id .

`SELECT tl_iso_product.*, 'en' AS language, IF(tl_iso_product.pid>0, parent.type, tl_iso_product.type) AS type, IFNULL(translation.name, tl_iso_product.name) AS name, IFNULL(translation.teaser, tl_iso_product.teaser) AS teaser, IFNULL(translation.description, tl_iso_product.description) AS description, IFNULL(translation.meta_title, tl_iso_product.meta_title) AS meta_title, IFNULL(translation.meta_description, tl_iso_product.meta_description) AS meta_description, IFNULL(translation.meta_keywords, tl_iso_product.meta_keywords) AS meta_keywords, IFNULL(translation.images, tl_iso_product.images) AS images, IFNULL(translation.size, tl_iso_product.size) AS size, IFNULL(translation.color, tl_iso_product.color) AS color, IFNULL(translation.material, tl_iso_product.material) AS material, IFNULL(translation.style, tl_iso_product.style) AS style, IFNULL(translation.pattern, tl_iso_product.pattern) AS pattern, IFNULL(translation.cutout, tl_iso_product.cutout) AS cutout, tl_iso_product.images AS images_fallback, GROUP_CONCAT(c.page_id) AS product_categories, c.sorting FROM tl_iso_product LEFT OUTER JOIN tl_iso_product translation ON tl_iso_product.id=translation.pid AND translation.language='en' LEFT OUTER JOIN tl_iso_product parent ON tl_iso_product.pid=parent.id LEFT OUTER JOIN tl_iso_product_category c ON IFNULL(parent.id, tl_iso_product.id)=c.pid WHERE tl_iso_product.language='' AND tl_iso_product.published='1' AND (tl_iso_product.start='' OR tl_iso_product.start<'1580478240') AND (tl_iso_product.stop='' OR tl_iso_product.stop>'1580478300') AND tl_iso_product.pid=0 AND c.page_id = 514 AND (tl_iso_product.pid = 0 OR tl_iso_product.type=1) AND tl_iso_product.id IN (SELECT pid FROM tl_iso_product_price) GROUP BY tl_iso_product.id,  translation.id, c.id ORDER BY c.sorting`

**Comment by aschempp** [comment]
> The problem appears when `$objProducts` contains duplicate entries.

You mean the same product appears multiple times in the result? That should never happen…? Did you write your own query or how did you configure Isotope?

**Comment by theDyingMountain** [comment]
Okay I found the problem. The table tl_iso_product_category contains duplicate entries. I don't know how this is happened.  This isoptope shop was configured and developed by another company.
