### ISSUE TITLE
Sorting of productfilter options (type foreign key) is missing

### ISSUE THREAD

**Issue by theDyingMountain** [isotope/core#2110]
When using foreign key options for the product filter, an `ORDER BY` clause is missing in the `SELECT `statement. See [Line 272](https://github.com/isotope/core/blob/6454562633a8ec09cae38f543856a47f602406ee/system/modules/isotope/library/Isotope/Model/Attribute/AbstractAttributeWithOptions.php#L258)

**Comment by aschempp** [comment]
Do you think it should be sorted by label?

**Comment by theDyingMountain** [comment]
Yes, in my case I needed an alphabetical sorting by label. I think that is the most commonly used case, for all users.
