### ISSUE TITLE
Fehlerhaftes Markup (Google rich snippeds)

### ISSUE THREAD

**Issue by doescher** [isotope/core#2111]
Hallo,
ich bekomme seit ein paar Tagen von Google den Hinweis, dass bei meinen Produkten in meinem Isotope-Shop (2.6.6) unter Contao 3.5.40 fehlerhaftes Markup zu finden ist:

> price: 12,99 € (Die Property 12,99 € ist keine gültige Spezifikation für den Preis. Weitere Informationen findest du unter http://schema.org/price.)

> description: Das Feld description ist ein empfohlenes Feld. Bitte gib einen Wert ein, falls verfügbar.

> image: Das Feld image ist ein empfohlenes Feld. Bitte gib einen Wert ein, falls verfügbar.

Die drei oben genannten werden aber doch eigentlich aus dem Isotope-Shop extrahiert, aber leider nicht bei Google angezeigt. Beim Preis scheint mir, dass hier ein Punkt statt einem Komma stehen sollte, damit Google den Preis versteht...

Außerdem fehlt bei Offer der Wert für Itemprop. In einer Diskussion fand ich den Hinweis auf [diese Fehlerbehebung](https://github.com/isotope/core/commit/342e8aa15efcda45b72c027cc299b4ebcf1447c4#diff-a9f33f885022f62692f33c024fcc9a80). Aber auch hier hat sich ein Fehler eingeschlichen, denn es muss wohl »itemprop="offer**s**"« heißen, damit Google es versteht.

Ich habe selbst in das Template die Werte für priceCurrency, url, availability und itemCondition eingetragen, da diese bei allen Produkten gleich sind. Es wäre natürlich schick, wenn man diese direkt aus dem Shop ausfüllen könnte.

Viele Grüße

**Comment by asaage** [comment]
Die Fehler mit itemprop offer**s** und price kann ich auch bestätigen.
Hatte durch Templateanpassungen alles behoben - hier mein Snippet:

```html
<div class="offer" itemprop="offers" itemscope="" itemtype="http://schema.org/Offer">
<meta itemprop="price" content="30.90"> <!-- mit Punkt und ohne &nbsp -->
<meta itemprop="priceCurrency" content="€">
<meta itemprop="url" content="https://produkt-url.html">
<meta itemprop="availability" content="http://schema.org/OnlineOnly">
<meta itemprop="priceValidUntil" content="2020-04-12">
<div class="price">30,90&nbsp;<span class="currency">€</span></div>
</div>
```
Konnte jedoch nicht feststellen, dass meine Produkte jemals mit Produktauszeichnungen bei Google gelistet wurden 🤷🏼‍♂️ .

**Comment by doescher** [comment]
Hallo assage,
müsste bei priceCurrency nicht eher EUR stehen?
Überschreibt nicht das zweite Price-Attribut das von Dir händisch eingesetzte mit Punkt?

**Comment by asaage** [comment]
> müsste bei priceCurrency nicht eher EUR stehen?

könnte richtig sein - https://schema.org/priceCurrency
[google](https://search.google.com/structured-data/testing-tool) bemeckert aber das "€" auch nicht

> Überschreibt nicht das zweite Price-Attribut...

Nein - das zweite ist nur ein div mit ```class="price"```

**Comment by asaage** [comment]
That still does not address the main-point: ```itemprop="offers"``` vs ```itemprop="offer"```

**Comment by aschempp** [comment]
Oh sorry, I didn't realize that. Fixed in f374e62893716ad8cc5d846425c8f148dd7e0206 (will be released in 2.6.9)
