### ISSUE TITLE
Double ampersand &amp; in language files

### ISSUE THREAD

**Issue by fk-caupo** [isotope/core#2112]
amp doppelt:

tl_iso_orderstatus.xlf
<target>Auswertungen &amp;amp; Statistiken</target>

modules.xlf
<target>Isotope eCommerce: Auswertungen &amp;amp; Statistiken</target>

**Comment by netzarbeiter** [comment]
Dieser Fehler ist in allen Sprachfiles von **isotope_reports/languages/xx/modules.xlf** und **isotope_reports/languages/xx/tl_iso_orderstatus.xlf**:
`<source>Isotope eCommerce: Reports &amp;amp; Statistics</source>`
`<source>Reports &amp;amp; Statistics</source>`

Auf Transifex ist es wie folgt hinterlegt:
`Reports &amp; Statistics`

Im Backend von Contao steht es wie folgt im Quelltext:
`Reports &amp; Statistics`
