### ISSUE TITLE
Menüpunkt Auswertungen &amp; Statistiken in Contao 4.9

### ISSUE THREAD

**Issue by Mynyx** [isotope/core#2113]
Der Menüpunkt ``Auswertungen & Statistiken`` wird in Contao 4.9 als ``Auswertungen &amp; Statistiken`` angezeigt:

![image](https://user-images.githubusercontent.com/1632642/75095935-4211aa80-559a-11ea-9dc7-85ccba64a49c.png)

**Comment by richardhj** [comment]
Duplicate of #2112

**Comment by Mynyx** [comment]
Duplikat ovn #2112
