### ISSUE TITLE
Fehler im Versandkostenmodul Flat.php

### ISSUE THREAD

**Issue by mp-itconsulting** [isotope/core#2114]
In version 2.67 ist Im Shipping-Modul Flat.php ist in Zeile 32 eine Klammer zuviel:

syntax error, unexpected ')' at .../vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/Model/Shipping/Flat.php:32)

Fehler:
if ('' === (string) $this->arrData['price']))

Richtig:
if ('' === (string) $this->arrData['price'])

Gruß
M.P.

**Comment by aschempp** [comment]
Fixed in ee509929389d4153c6afb5583c2703ccb21199a6
