### ISSUE TITLE
Produkt-Liste/Leser bleibt bei Varianten hängen

### ISSUE THREAD

**Issue by macuos** [isotope/core#2116]
Im Einsatz ist Contao 4.9.1 mit Isotope 2.6.9.

Als Gast im Shop unterwegs, funktioniert die Auswahl der Produkt-Varianten über ein Select-Menü nicht, bzw. bleibt in einer Dauerschleife (Lade Produktdaten ...) hängen. Getestet mit Safari, Firefox und Chrome unter macOS. Die mobile Version von Safari zeigt das gleiche Verhalten. IE und Opera Coast wiederum nicht.

Legt der Gast zuerst ein Produkt ohne Varianten in den Warenkorb, funktioniert danach auch die Auswahl von Produkt-Varianten. Leert der Gast den Warenkorb, funktioniert die Auswahl von Produkt-Varianten weiterhin. Erst nach Löschen des Browsercache bleibt die Auswahl von Produkt-Varianten erneut in einer Dauerschleife hängen.

Im Backend angemeldet, ist der Wechsel zwischen den Produkt-Varianten im Frontend jederzeit problemlos möglich, egal welche Browser in Verwendung ist.

Im Forum gibt es dazu seit Anfang November 2019 folgendes Thema.

[https://community.contao.org/de/showthread.php?76422-Isotope-Produktliste-Varianten-bleibt-hängen](url)

**Comment by aschempp** [comment]
gibt es denn eine Fehlermeldung in der Browser-Konsole?

**Comment by macuos** [comment]
ich finde in der Konsole leider keine Fehlermeldung, der Ladevorgang dreht sich einfach unendlich weiter. Was ich herausgefunden habe. Wenn in der Seitenstruktur auf den Seiten wo die Produktliste/leser eigenbunden ist, "Immer aus dem Shared-Cache laden" aktiviert ist, dann funktioniere auch der Variantenwechsel als Gast problemlos. Die Folge davon ist aber, dass Prdukte die keine Variante haben und in den Warenkorb gelegt werden, mit einem "Ungültiges Anfrage-Token" quitiert wird.

**Comment by aschempp** [comment]
das sieht für mich sehr stark nach einem Server- oder Javascript-Problem aus. Da müsstest du wohl deinen Server analysieren (lassen), warum der entsprechende Request nicht gesendet oder nicht beantwortet wird.

**Comment by macuos** [comment]
downgrade auf 4.4 durchgeführt. Danach ist das Problem nicht mehr vorhanden. Hängt evtl. mit dem neuen Caching ab Version 4.8 zusammen. Bin zuvor direkt von 4.4 auf 4.9 gewechselt, davon nehme ich erstmal abstand.

**Comment by aschempp** [comment]
ich kann dir leider nicht direkt sagen wo der Fehler liegt, da ich ihn selber nicht habe. Generell sollte Isotope aber mit Contao 4.9 genauso funktionieren. Ich schliesse das Ticket mal, du darfst es aber gerne wieder öffnen wenn neue Erkenntnisse vorhanden sind.
