### ISSUE TITLE
Mehrere Varianten auf einmal verschieben ist fehlerhaft

### ISSUE THREAD

**Issue by cubano** [isotope/core#2117]
Wenn ich versuche, mehrere Varianten von einem Produkt zu einem anderen zu verschieben, klappt es nicht. Die Ablage ist dann leer und die Varianten sind weg. Einige davon sind dann in der Produktliste wiederzufinden (also als Produkt und nicht mehr als Variante), andere sind komplett verschwunden.

Verschiebe ich eine Variante einzeln, dann klappt es.

Contao 4.4.46, Isotope 2.6.9

**Comment by aschempp** [comment]
Should be fixed in 517c774481d9fd34a83bf1d1c34e7ebfcd626c4a
