### ISSUE TITLE
Willkürliche Ausgabe des Canonical Tags

### ISSUE THREAD

**Issue by cubano** [isotope/core#2118]
Die Shop-Produkte haben jeweils 2 zugewiesene Kategorien. Nun müsste eigentlich die 1. Kategorie als canonical verwendet werden. Obwohl die Sortierung im Backend richtig ist, wird teilweise die 2. Kategorie als canonical verwendet. Das Ganze geschieht ziemlich willkürlich, denn es kann sein, dass bei Produkten mit gleichen Kategorien, es beim einen korrekt und beim anderen falsch ausgegeben wird? In der Datenbank ist die Sortierung bei orderPages korrekt hinterlegt.

**orderPages Produkt 1:**
`a:2{i:0,s:2:"46";i:1,s:2:"58";}`

**orderPages Produkt 2 (= identisch):**
`a:2{i:0,s:2:"46";i:1,s:2:"58";}`

Jedoch erzeugt die Funktion getCategories folgende Ausgaben:

getCategories Produkt 1:
`Array
(
    [0] => 46
    [1] => 58
)`

getCategories Produkt 2:
`Array
(
    [0] => 58
    [1] => 46
)`

Irgendwas scheint also bei der Array-Sortierung schief zu gehen, ev hier?
`// Sort categories by the backend drag&drop
            $arrOrder = deserialize($this->orderPages);
            if (!empty($arrOrder) && \is_array($arrOrder)) {
                $this->arrCategories[$key] = array_unique(
                    array_merge(
                        array_intersect(
                            $arrOrder,
                            $this->arrCategories[$key]
                        ),
                        $this->arrCategories[$key]
                    )
                );
            }`

**Comment by aschempp** [comment]
könnte es eventuell an der Sortierung in der Tabelle `tl_iso_product_category` liegen?

**Comment by cubano** [comment]
Wenn die Spalte `sorting` in der Tabelle `tl_iso_product_category` für die Sortierung zuständig ist, dann wird es wohl das sein. Die Sorting-Werte verändern sich nicht beim Verschieben der Kategorien.

**Comment by aschempp** [comment]
Nein soweit ich mich erinnere bezieht sich die Sortierung auf die Reihenfolge der Produke **auf einer bestimmten Seite**.

Ich habe aber gerade deinen serialisierten String getestet, und der ist nicht gültig. Hast du den selber generiert?

**Comment by cubano** [comment]
Ooops sorry, den hatte ich falsch abgetippt. Das ist der korrekte String:
`a:2:{i:0;s:2:"46";i:1;s:2:"58";}`

**Comment by cubano** [comment]
Mir ist noch das gleiche Verhalten bei der sitemap.xml aufgefallen. Auch hier wird die URL teilweise aus der ersten, teilweise aus der zweiten Kategorie generiert.

**Comment by aschempp** [comment]
Verwendet ihr eine Reader-Page für die Anzeige der Produkte (Einstellung in der Seitenstruktur)? Ev. behebt https://github.com/isotope/core/commit/9eb56216f5fb649572c71fd1e241dd848061831c das Problem.

**Comment by aschempp** [comment]
This is most likely fixed by 6e9cdea53fa80309d42d2e067aadd9b71a999cd9
