### ISSUE TITLE
PayPal: Sofortige Zahlungsbestätigung

### ISSUE THREAD

**Issue by DaxCheller** [isotope/core#2123]
Ein Kunde von uns bekommt in unregelmäßigen Abständen folgende Mail:

> Guten Tag *** ! 
> 
> Bitte überprüfen Sie den Server, der für sofortige Zahlungsbestätigungen von PayPal zuständig ist. Sofortige Zahlungsbestätigungen an den/die folgende(n) URL(s) sind fehlgeschlagen:
> 
> https://www.***.de/system/modules/isotope/postsale.php?mod=pay&id=1 
> 
> Wenn Sie diese URL nicht erkennen, nutzen Sie vielleicht einen Serviceprovider, der die sofortige Zahlungsbestätigung in Ihrem Namen verwendet. Bitte wenden Sie sich mit den oben genannten Informationen an Ihren Serviceprovider. Wenn dieses Problem weiterhin besteht, könnten die sofortigen Zahlungsbestätigungen für Ihr Konto deaktiviert werden. 
> 
> Wir bedanken uns für die rasche Erledigung dieser Angelegenheit.
> 
> Herzliche Grüße
> 
> Ihr PayPal-Team

Nach einer gewissen Zeit wird IPN deaktiviert und die Bestellungen über PayPal sind in Contao nicht mehr sichtbar bzw. werden im Shop nicht mehr vermerkt. Ein erneutes aktivieren von IPN bringt das ganze wieder zum Laufen und der "Spaß" beginnt von vorne. 

Beim Aufruf des Links erhalte ich "Failed Dependecy", die Ausgabe des postsale logs ist folgende:

```
[01-Apr-2020 07:30:16] New request to https://www.***.de/system/modules/isotope/postsale.php?mod=pay&id=1.

Headers: array (
  'HOST' => 'www.***.de',
  'X_REAL_IP' => '****',
  'X_FORWARDED_FOR' => '****',
  'CONNECTION' => 'close',
  'DNT' => '1',
  'UPGRADE_INSECURE_REQUESTS' => '1',
  'USER_AGENT' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36',
  'SEC_FETCH_DEST' => 'document',
  'ACCEPT' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
  'SEC_FETCH_SITE' => 'none',
  'SEC_FETCH_MODE' => 'navigate',
  'ACCEPT_ENCODING' => 'gzip, deflate, br',
  'ACCEPT_LANGUAGE' => 'de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7,fr;q=0.6',
  'COOKIE' => '_ga=GA1.2.1347637912.1570606706; ISOTOPE_TEMP_CART=6617ed210a7bb303a31058c66f19b165a66ecd86; PHPSESSID=0beb360c8946eddd4bb96283962a868a; BE_USER_AUTH=868528db59d5dd7d208f66679a5a8826c09f45ff; BE_PAGE_OFFSET=0',
)

$_GET: array (
  'mod' => 'pay',
  'id' => '1',
)

$_POST: array (
)

Body:
```

Zum System: Es ist ein Contao 4.4.46 mit Isotope 2.6.3, das System wurde von Contao 3.X updated, davor hat alles wunderbar funktioniert.

**Comment by aschempp** [comment]
Please update to the latest version, it should be fixed there. I'm closing this issue, but please reopen if the problem persists.

**Comment by DaxCheller** [comment]
I successfully updated to the latest version last week but the problem persists. I got another E-Mail from PayPal like above.

**Comment by aschempp** [comment]
did you find any other information in the meantime?

**Comment by aschempp** [comment]
Closing this due to lack of feedback.

**Comment by janoschbatschi** [comment]
I'm facing the same problem. The shop exists for several months now. At least since the beginning of November (no log for October), there are errors in the log: "Paypal did not return a valid order". Sometimes the order gets accepted, sometimes it doesn't. 

Log:
`[15.11.2020 13:39] New post-sale request: system/modules/isotope/postsale.php?mod=pay&id=2
[15.11.2020 13:39] Isotope\Model\Payment\Paypal did not return a valid order`

I also received the Mail above from PayPal two times in the last days.

Updated yesterday from Contao 4.4.47 and Isotope 2.6.10 to:
Contao: 4.4.54
Isotope: 2.6.14
But that didn't affect the issue.

Interestingly, there are no entries in the Paypal IPN transaction history for today although in the Contao Log there is 3 times following entry: New post-sale request: system/modules/isotope/postsale.php?mod=pay&id=2. 
Yesterday, there are 3 transactions in the Paypal IPN history but 9(!) entries in the Contao Log.

**Comment by aschempp** [comment]
are there any orders anyhow related to the errors? What can you see in the log file if you enable debug logging in the payment method?

**Comment by janoschbatschi** [comment]
i can't see a pattern here. today there again was this error. nothing in the PayPal IPN transaction history. there is no registered order visible in isotope, but there is an entry related to this order in the postsale.log (see below). a problem might be the wrong charset I just changed to UTF-8 (which is not that easy to find: https://formsmarts.com/enable-utf-8-encoding-paypal). But there are no obvious umlauts in those specific orders.

any help is appreciated!

> [16-Nov-2020 12:26:32] New request to https://shop.xxx.at/system/modules/isotope/postsale.php?mod=pay&id=2.
> 
> Headers: array (
>   'CONNECTION' => 'close',
>   'CORRELATION_ID' => '84e2xxxxa82',
>   'USER_AGENT' => 'PayPal IPN ( https://www.paypal.com/ipn )',
>   'ACCEPT' => '*/*',
>   'HOST' => 'shop.xxxx.at',
> )
> 
> $_GET: array (
>   'mod' => 'pay',
>   'id' => '2',
> )
> 
> $_POST: array (
>   'transaction_subject' => '',
>   'txn_type' => 'send_money',
>   'payment_date' => '07:10:29 Nov 13, 2020 PST',
>   'last_name' => 'Bxxxxx',
>   'residence_country' => 'DE',
>   'payment_gross' => '',
>   'mc_currency' => 'EUR',
>   'business' => 'info@xxxx.at',
>   'payment_type' => 'instant',
>   'protection_eligibility' => 'Ineligible',
>   'verify_sign' => 'AbVcWT1qbhflopGKakxxxxxxx-AU.KfO1FRQSTOY0',
>   'payer_status' => 'verified',
>   'payer_email' => 'sxxxx@gmx.de',
>   'txn_id' => '75N5257xxxxx798451',
>   'receiver_email' => 'info@xxxx.at',
>   'first_name' => 'Rxxxx',
>   'payer_id' => 'G5WX9xxxxDA6C',
>   'receiver_id' => 'QTB44xxxxL2P6',
>   'memo' => 'Restzahlung zur Bestellung',
>   'payment_status' => 'Completed',
>   'mc_gross' => '100.00',
>   'charset' => 'windows-1252',
>   'notify_version' => '3.9',
>   'ipn_track_id' => '84e21xxxxa82',
> )
> 
> Body:
> transaction_subject=&txn_type=send_money&payment_date=07%3A10%3A29+Nov+13%2C+2020+PST&last_name=Bxxxx&residence_country=DE&payment_gross=&mc_currency=EUR&business=info%40xxxx.at&payment_type=instant&protection_eligibility=Ineligible&verify_sign=AbVcWT1qbhflopGKaxxxxUAxZ203REzcVz-AU.KfO1FRQSTOY0&payer_status=verified&payer_email=sxxxxx%40gmx.de&txn_id=75N52572AFxxxxx451&receiver_email=info%40xxxx.at&first_name=Rxxxx&payer_id=G5WX9xxxxDA6C&receiver_id=QTB44xxxxL2P6&memo=Restzahlung+zur+Bestellung&payment_status=Completed&mc_gross=100.00&charset=windows-1252&notify_version=3.9&ipn_track_id=84e2xxxxxxa82

and here a test order that worked flawlessly:

> [15-Nov-2020 22:12:33] New request to https://shop.xxxx.at/system/modules/isotope/postsale.php?mod=pay&id=2.
> 
> Headers: array (
>   'ACCEPT_ENCODING' => 'gzip,deflate',
>   'CONNECTION' => 'close',
>   'HOST' => 'shop.xxxx.at',
>   'USER_AGENT' => 'PayPal IPN ( https://www.paypal.com/ipn )',
>   'ACCEPT' => 'text/plain, application/json, application/*+json, */*',
> )
> 
> $_GET: array (
>   'mod' => 'pay',
>   'id' => '2',
> )
> 
> $_POST: array (
>   'mc_gross' => '2.00',
>   'invoice' => '10xxxx3',
>   'protection_eligibility' => 'Eligible',
>   'address_status' => 'confirmed',
>   'item_number1' => '',
>   'item_number2' => '',
>   'payer_id' => 'BCTSxxxxQ7K4A',
>   'address_street' => 'xxxx',
>   'payment_date' => '13:12:24 Nov 15, 2020 PST',
>   'payment_status' => 'Completed',
>   'charset' => 'windows-1252',
>   'address_zip' => 'xxxx',
>   'first_name' => 'Xxxxx',
>   'mc_fee' => '0.41',
>   'address_country_code' => 'AT',
>   'address_name' => 'Xxxx Xxxx',
>   'notify_version' => '3.9',
>   'custom' => '',
>   'payer_status' => 'verified',
>   'business' => 'info@xxxx.at',
>   'address_country' => 'Austria',
>   'num_cart_items' => '2',
>   'address_city' => 'xxx',
>   'verify_sign' => 'AB-hEOLcMHJX2X8wbiXNxxxxxxOKakTpm8OHvAABTJKNajbmw',
>   'payer_email' => 'xxxxx@gmx.at',
>   'txn_id' => '31556223xxxxx182N',
>   'payment_type' => 'instant',
>   'last_name' => 'Xxxxx',
>   'address_state' => '',
>   'item_name1' => 'Nxxxx',
>   'receiver_email' => 'info@xxxx.at',
>   'item_name2' => 'Versand (Pauschalversand)',
>   'payment_fee' => '',
>   'shipping_discount' => '0.00',
>   'quantity1' => '6',
>   'insurance_amount' => '0.00',
>   'quantity2' => '1',
>   'receiver_id' => 'QTB4xxxx2L2P6',
>   'txn_type' => 'cart',
>   'discount' => '0.00',
>   'mc_gross_1' => '1.20',
>   'mc_currency' => 'EUR',
>   'mc_gross_2' => '0.80',
>   'residence_country' => 'AT',
>   'shipping_method' => 'Default',
>   'transaction_subject' => '',
>   'payment_gross' => '',
>   'ipn_track_id' => '85e48613a3ffb',
> )
> 
> Body:
> mc_gross=2.00&invoice=10xxxx3&protection_eligibility=Eligible&address_status=confirmed&item_number1=&item_number2=&payer_id=BCTSUNxxxx7K4A&address_street=xxxx&payment_date=13%3A12%3A24+Nov+15%2C+2020+PST&payment_status=Completed&charset=windows-1252&address_zip=xxx&first_name=XXXX&mc_fee=0.41&address_country_code=AT&address_name=XXXX+XXXX&notify_version=3.9&custom=&payer_status=verified&business=info%40xxxx.at&address_country=Austria&num_cart_items=2&address_city=XXXX&verify_sign=AB-hEOLcMHJX2X8wbiXNGxxxxxOKakTpm8OHvAABTJKNajbmw&payer_email=xxxx%40gmx.at&txn_id=31556223xxxx182N&payment_type=instant&last_name=XXXX&address_state=&item_name1=NXxxxxx&receiver_email=info%40xxxx.at&item_name2=Versand+%28Pauschalversand+%2829&payment_fee=&shipping_discount=0.00&quantity1=6&insurance_amount=0.00&quantity2=1&receiver_id=QTB44Xxxxx2P6&txn_type=cart&discount=0.00&mc_gross_1=1.20&mc_currency=EUR&mc_gross_2=0.80&residence_country=AT&shipping_method=Default&transaction_subject=&payment_gross=&ipn_track_id=85exxxxa3ffb

**Comment by MarkKnochen** [comment]
Ich habe in PayPal den Zeichensatz auf UTF-8 gestellt - ich bekomme allerdings keine Bestellungen im Shop an.

Siehe https://github.com/isotope/core/issues/2299

Es wird wieder kein Log-File erstellt - Zahlung über PayPal funktioniert - nur der Eingang der Bestellung im Isotope nicht.
Und die nicht erstellen Log-Files sind auch ein Problem beim Fehler finden
