### ISSUE TITLE
Texteingabe von Besteller bei Produkt ermöglichen?

### ISSUE THREAD

**Issue by DanEi75** [isotope/core#2126]
Ich habe folgende Anforderung, die eigentlich nach meinem Verständnis von Isotope bereits umsetzbar sein müsste. Allerdings bringe ich es nicht fertig und ich bin mittlerweile nicht mehr sicher, ob es an mir liegt. Meine Anfrage in Contao-Community war bislang nicht hilfreich:

Für verschiedene Produkte ist eine Textfeld oder Textarea-Eingabe durch den Besucher notwendig, damit es in den Warenkorb eingefügt werden kann.

Mein Vorgehen:

1.  Attribut 'sign_sponsortship' erstellt, Typ Textare, und "Durch den Kunden auswählbar" aktiviert. Pflichtfeld mal deaktiviert.

![Safari Screenshot 2020-04-03 17 17 30](https://user-images.githubusercontent.com/26572890/78426218-e72ca200-7673-11ea-8f53-ceb183f36c23.png)

2. Attributtyp an betreffenden Produkttyp angehängt.

![Safari Screenshot 2020-04-03 17 18 48](https://user-images.githubusercontent.com/26572890/78426298-ed228300-7673-11ea-9d05-209b4802fa52.png)

3. iso_list_default angepasst `<?= $this->generateAttribute('sign_sponsorship'); ?>`

![Safari Screenshot 2020-04-03 17 20 03](https://user-images.githubusercontent.com/26572890/78426314-f1e73700-7673-11ea-9ded-d3202a025009.png)

4. Produktliste aufgerufen (Template ist definitiv richtig verknüpft!).

![Safari Screenshot 2020-04-03 17 25 16](https://user-images.githubusercontent.com/26572890/78426366-f4e22780-7673-11ea-9658-f78fa8ff9486.png)

Nach meinem Verständnis müsste jetzt das Textarea-Feld für die Kundeneingabe erscheinen, oder? Ich habe zig Varianten (Textfeld, Pflichtfeld etc.) getestet, kein Erfolg.

Momentan weiss ich nicht, ob ich die Option falsch verstanden habe, ich einen Fehler gemacht habe oder sich hier ein Bug eingeschlichen hat.

Ich habe es mit Contao 4.4.43 (Isotope 2.6.2) und 4.9.2 (Isotope 2.6.10) getestet.

**Comment by aschempp** [comment]
`generateAttribute` wird nicht für die Eingabe verwendet, nur für reguläre Felder. Hast fu mal das Original-Template versucht?

**Comment by DanEi75** [comment]
Hoi Andreas. Danke für die Rückfrage. Das verwirrt mich jetzt gerade, denn im Manual steht:

![image](https://user-images.githubusercontent.com/26572890/78507635-91462000-7781-11ea-9740-971ad5f5cc26.png)

Also, ich habe das Original-Template von iso_list_default genommen und dort einfach die Zeile eingefügt. Bei iso_reader_default übrigens das selbe Problem...

**Comment by aschempp** [comment]
Das ist wohl etwas verwirrend geschrieben. Aber da steht „wird automatisch ausgegeben“. Danach wär ein „Andernfalls kannst du“ passend 😬

**Comment by netzarbeiter** [comment]
https://github.com/isotope/docs/commit/601fbafccc2209f40ddde902db8e5f4fda163f62

**Comment by DanEi75** [comment]
Hoi Andreas. Ah, jetzt hat es geklappt! Super! Ja, in der Tat, hat mich die Anleitung verwirrt. 

Also, dann ist es aber so, dass das Feld aber "nur" im Reader-Template mittels

```
<?php if($this->hasOptions): ?>
<div class="options">
<?php foreach( $this->options as $arrOption ): echo $arrOption['html']; endforeach; ?>
</div>
<?php endif; ?>
```

ausgegeben wird, oder? Im List-Template ist das nicht der Fall. Für meinen UseCase ist das prima so.

Wenn ich deshalb noch eine Text-Anpassung anregen darf :

_...wird es automatisch im Frontend **(mittels $this->options im Reader-Template)** angezeigt. Andernfalls kannst..._

Aber super Sache und danke für die Unterstützung! Bin gespannt, ob die Info über den ganzen Bestellprozess mitgezogen wird :-).

**Comment by netzarbeiter** [comment]
Ich habe die Doku angepasst und schliesse das Ticket.
https://isotopeecommerce.org/de/handbuch/v/2.6/r/textarea.html
