### ISSUE TITLE
Error for products with variants after isotope update

### ISSUE THREAD

**Issue by ghnewbi** [isotope/core#2127]
Hi everyone, 
I already discovered the following issue some updates ago. Other users also reported it in the forum, so I hoped it would have been repaired by now, but obviously it hasn't, so I would like to report it and offer a solution that I hard coded into the isotope plugin code.

After every isotope update, now to 2.6.10 within a contao 4.9.2 installation, my products with variants do not load any more, meaning that the product page throws an error and so does the product list, since it contains products with variants.
The error log displays the following error:
"An exception occurred while executing 'SELECT id, protected, groups FROM tl_iso_product ..."

It was already discussed in the contao forum that this happens due to the fact that "groups" is a reserved word in some MySQL versions.
I solved the issue by changing the file /vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/Model/Product/Standard.php as follows:
'SELECT id, protected, **tl_iso_product.groups** FROM tl_iso_product ..."
Just one simple change and my shop works again, since the database now interprets groups as a column name instead of the reserved word. 
I wonder if you could change the database query accordingly within the next release, because changing the plugin code after every update is not a proper solution, of course.

Thanks.

**Comment by fritzmg** [comment]
Yeah, `\Contao\Database::quoteIdentifier(…)` needs to be used for any such direct queries.

**Comment by aschempp** [comment]
fixed in 2af05f78d5ad63f323a75b6a0339370310433aa4
