### ISSUE TITLE
Attribute "upload" wrong value in Frontend

### ISSUE THREAD

**Issue by michb** [isotope/core#2128]
How to reproduced:
1. in Backend configure an attribute of the type upload
2. in Frontend upload a file, e.g. `contao.jpg`
3. in cart it only displays 'g'

Problem imho occurs in 
https://github.com/isotope/core/blob/622980a8c94c7776bf9c4d2bdfb386bf3494cf2e/system/modules/isotope/library/Isotope/Model/Attribute/Upload.php#L79

- then value in my example would be `isotope/uploads/contao.jpg`
- which get converted to `basename($value) // contao.jpg`
- and then to `substr(basename($value), 9) // g`

Is there any way to display the image again?

Same problem may occur using fineUploader, but I haven't tested it.

**Comment by aschempp** [comment]
which version of Isotope and Contao are you using?

**Comment by michb** [comment]
sorry forgot to mention:
Contao: 4.9.2
Isotope: 2.6.10

**Comment by aschempp** [comment]
File hashes have been removed in 2.5.14 (263900f2608cea1d42222279fa802d6e00fdb6a8), but apparently this is a leftover. Fixed in 629a46ec3b39b2a9c0815c89a538568c260eac07
