### ISSUE TITLE
Payment Checkout anpassen (mPAY24)

### ISSUE THREAD

**Issue by mecintosch** [isotope/core#2129]
Möchte man die Checkout Seite des Payment Providers anpassen (in meinem Fall mPAY24), muss man die Mpay24.php anpassen. Wie mache ich das updatesicher?

Original:

```
        $mpay24 = $this->getApiClient();

        $mdxi = new Mpay24Order();
        $mdxi->Order->Tid = $objOrder->getId();
        $mdxi->Order->Price = $objOrder->getTotal();
        $mdxi->Order->URL->Success = \Environment::get('base') . Checkout::generateUrlForStep('complete', $objOrder);
        $mdxi->Order->URL->Error = \Environment::get('base') . Checkout::generateUrlForStep('failed');
        $mdxi->Order->URL->Confirmation = \Environment::get('base') . 'system/modules/isotope/postsale.php?mod=pay&id=' . $this->id;

        $template = new \FrontendTemplate('iso_payment_mpay24');
        $template->setData($this->row());
        $template->location = $mpay24->paymentPage($mdxi)->getLocation();

```
Angepasst:

 ```
        $mpay24 = $this->getApiClient();

        $mdxi = new Mpay24Order();
        $mdxi->Order->setLogoStyle("display:inline;max-width:120px;padding:1em 0");
        $mdxi->Order->setHeaderStyle("background-color:transparent;border:none;text-align:center;margin:2em 0 1em");
        $mdxi->Order->setStyle("background-color:#f8f8f8;font-size:12px");
        $mdxi->Order->setPageHeaderStyle("background-color:#9bb70d;color:#fff");
        $mdxi->Order->setPageCaptionStyle("color:#fff;font-weight:bold");
        $mdxi->Order->setButtonsStyle("border:none;background-color:#9bb70d;color:#fff;font-weight:bold;font-size:1.2em;text-transform: uppercase;padding: 15px 20px;border-radius: 3px;height:auto");

        $mdxi->Order->Tid = $objOrder->getId();
        $mdxi->Order->TemplateSet->setCSSName("MODERN");
        $mdxi->Order->Price = $objOrder->getTotal();
        $mdxi->Order->URL->Success = \Environment::get('base') . Checkout::generateUrlForStep('complete', $objOrder);
        $mdxi->Order->URL->Error = \Environment::get('base') . Checkout::generateUrlForStep('failed');
        $mdxi->Order->URL->Confirmation = \Environment::get('base') . 'system/modules/isotope/postsale.php?mod=pay&id=' . $this->id;
        $mdxi->Order->URL->Cancel = \Environment::get('base') . Checkout::generateUrlForStep('review');

        $template = new \FrontendTemplate('iso_payment_mpay24');
        $template->setData($this->row());
        $template->location = $mpay24->paymentPage($mdxi)->getLocation();

```

Oder einfach nach jedem Update die Anpassung erneut durchführen?

**Comment by fritzmg** [comment]
Lassen sich die Styles nicht im mPAY24 Backend setzen?

**Comment by mecintosch** [comment]
Leider nein, da gibt es sonst keine Möglichkeit, hatte auch schon Kontakt mit der Technik von mPAY24.

Für die Anpassung ist einiges zu beachten (zB. die Reihenfolge der Einträge). Hab die Infos aus dieser Doku: https://docs.mpay24.com/docs/cheatsheet-paymentpage-customization

**Comment by fritzmg** [comment]
Verstehe. Ich sehe da zwei Lösungen: Isotope baut selbst einen Hook nach folgendem Block ein

https://github.com/isotope/core/blob/38b4c2a4d4bad6c28752a490f4208ef655a24c29/system/modules/isotope/library/Isotope/Model/Payment/Mpay24.php#L95-L100

wo jeder Hook subscriber dann das `$mdxi` Objekt beliebig ändern kann.

Oder du implementierst dir einfach deine eigene Zahlungsmethode, die von `\Isotope\Model\Payment\Mpay24` erweitert und nur die `checkoutForm` Methode überschreibt.

**Comment by aschempp** [comment]
Ich habe die Konfiguration in 2eee617ac743634ea646f1d3623dc6eb3c0e16d3 ins Template verschoben, entsprechend kannst du das ab der nächsten Isotope-Version dort vornehmen 😎

**Comment by mecintosch** [comment]
Wollte die Anpassung gerade in der aktualisierten Version im Template einfügen. Aber leider funktioniert das so nicht. Lt. mPAY24 Doku müssen die Anpassungen/Einträge in einer gewissen Reihenfolge übermittelt werden: https://docs.mpay24.com/docs/mdxi-xml#section-urltype

Somit gibt es Anpassungen an verschiedenen Stellen, siehe mein erstes Posting.

**Comment by aschempp** [comment]
kannst du erklären was noch nicht funktioniert?

**Comment by mecintosch** [comment]
Die Template-Anpassungen werden von mPay24 gar nicht übernommen. 

Da die Reihenfolge der Anpassungen wichtig ist müsste man wohl den kompletten Block über das Template anpassen können:
```

        $mpay24 = $this->getApiClient();

        $mdxi = new Mpay24Order();
        $mdxi->Order->Tid = $objOrder->getId();
        $mdxi->Order->Price = $objOrder->getTotal();
        $mdxi->Order->URL->Success = \Environment::get('base') . Checkout::generateUrlForStep('complete', $objOrder);
        $mdxi->Order->URL->Error = \Environment::get('base') . Checkout::generateUrlForStep('failed');
        $mdxi->Order->URL->Confirmation = \Environment::get('base') . 'system/modules/isotope/postsale.php?mod=pay&id=' . $this->id;

        $template = new \FrontendTemplate('iso_payment_mpay24');
        $template->setData($this->row());
        $template->location = $mpay24->paymentPage($mdxi)->getLocation();

```

Gerne kann ich etwaige Änderungen am Code vorab testen.

**Comment by aschempp** [comment]
also du meinst damit man muss `setLogoStyle` etc. aufrufen bevor man den `Price` setzt? Das erscheint mir sehr unlogisch…?

**Comment by mecintosch** [comment]
Lt. Doku ja:
https://docs.mpay24.com/docs/mdxi-xml#schema-description

**Comment by aschempp** [comment]
Die Doku zeigt doch nur ein Beispiel der Inhalte. Ich lese da nirgends dass die Reihenfolge relevant ist? Sollte bei einem XML ja definitiv auch nicht sein…

Hast du die Anpassung im Template mal versucht, und geschaut was im Debug Log steht?

**Comment by aschempp** [comment]
Versuch den oberen Teil des Template `iso_payment_mpay24.html` so anzupassen (einfach deine Zeile einfügen):

```
<?php
    $mpay24 = $this->mpay24;
    $mdxi = $this->mdxi;
    $mdxi->Order->TemplateSet->setCSSName("MODERN");
    $location = $mpay24->paymentPage($mdxi)->getLocation()
?>
```

**Comment by mecintosch** [comment]
Danke, soeben versucht. Leider werde ich dann zur Startseite weitergeleitet.

Im isotope_mpay24.log finde ich den Eintrag:

```
<status>ERROR</status>
<returnCode>INVALID_MDXI</returnCode>
<errNo>13</errNo>
<errText>Invalid MDXI: ERROR-1871: noname.xml:10: element TemplateSet: SchemasValidation: Element 'TemplateSet': This element is not expected.</errText>
```

Hier steht ein Hinweis bzgl. Reihenfolge der Einträge:
https://docs.mpay24.com/docs/working-with-the-mpay24-php-sdk-redirect-integration

**Comment by aschempp** [comment]
Ich habe mir das nochmals angesehen. Die vermutlich einzige sinnvolle Lösung wäre im Template das MDIX-Objekt selber neu zu erstellen, damit die Informationen in der richtigen Reihenfolge übergeben werden können. Das ist zwar etwas aufwändig aber dafür (mit den Anpassungen in 2.6.10) bereits möglich. Im Template in etwa so:

```
<?php
    $mdxi = new Mpay24\Mpay24Order();

    // Hier die eigenen Order-Anpassungen

    $mdxi->Order->Tid = $this->mdxi->Order->Tid;
    $mdxi->Order->Price = $this->mdxi->Order->Price;
    $mdxi->Order->URL->Success = $this->mdxi->Order->URL->Success;
    $mdxi->Order->URL->Error = $this->mdxi->Order->URL->Error
    $mdxi->Order->URL->Confirmation = $this->mdxi->Order->URL->Confirmation;

    $mpay24 = $this->mpay24;
    $location = $mpay24->paymentPage($mdxi)->getLocation()
?>
```
