### ISSUE TITLE
Add product to group not possible

### ISSUE THREAD

**Issue by michb** [isotope/core#2131]
**Contao:** `4.9.2` 
**Isotope:** `2.6.10`

When I want to add a group to a product a popup opens with no inner content looking like this
![iso_group](https://user-images.githubusercontent.com/17873830/79265758-e3302980-7e96-11ea-90d9-fa993cdc91c3.png)
I tracked it down to this line 

https://github.com/contao/contao/blob/b9c1002fb70588936db66415dbfa286fd11617f6/core-bundle/src/Resources/contao/library/Contao/Template.php#L678
if i comment this out it works fine.

Also I noticed that when I want to set a group to multiple products at once they will be set to `gid=0`. I could fix it by replacing this line 

https://github.com/isotope/core/blob/c77fc8d738d568a6c5d97ce5370c87add6cd4087/system/modules/isotope/library/Isotope/Backend.php#L286

with `\Controller::reload();`

**Comment by aschempp** [comment]
I have fixed the `exit` statement in 799a28ef91ad5d787589f1379541dc88c0bb8085. Not sure about the `fastcgi_finish_request `, that probably needs to be fixed in Contao.

**Comment by aschempp** [comment]
see https://github.com/contao/contao/pull/1728 for the bugfix in Contao about `fastcgi_finish_request`.
