### ISSUE TITLE
Paypal IPN - eBay

### ISSUE THREAD

**Issue by p33k** [isotope/core#2132]
Gibt es hierfür eine Lösung? Isotope unabhängige Bestellungen über eBay triggern eine Benachrichtung an Isotope und führen so zu Fehlermeldungen mit Androhung der Deaktivierung
der sofortigen Zahlungsbestätitungen seitens PayPal.

https://isotopeecommerce.org/de/handbuch/v/2.6/r/zahlungsart-paypal.html

Hinweise zur gleichzeitigen Nutzung von Isotope, eBay und IPN #
Betreibt man mit dem PayPal-Konto zusätzlich einen eBay-Shop (oder andere Systeme), versucht PayPal auch bei eBay-Bestellungen via IPN mit Isotope zu kommunizieren. Isotope meldet sich dann zwar mit einen 500 oder 424-Status-Code zurück, es tauchen aber vermehrt Fehler im System-Log auf und PayPal verschickt mehrmals Mails, dass die IPN-URL auf Fehler überprüft werden soll.

**Comment by bennyborn** [comment]
Einfach garnichts bei PayPal eintragen.
Keine Ahnung warum im Handbuch erwähnt wir man müsse die IPN konfigurieren aber beim Initialisieren der PayPal-Zahlung wird automatisch schon die korrekte URL für die IPN mitgegeben:

**Comment by aschempp** [comment]
Man **muss** bei PayPal leider eine URL eintragen, damit IPN überhaupt aktiviert werden kann. Und man **muss** es aktivieren, damit Isotope funktioniert. Ich sehe folgende Möglichkeiten:
 1. Nutzung von PayPal PLUS (statt PayPal Standard). PLUS nutzt die Api und kein IPN
 2. als Default-URL bei PayPal ein eigenes Script hinterlegen, welches PP für die eBay-Anfragen „zufrieden stellt“.
