### ISSUE TITLE
Order cannot be completed when orderCompleteJumpTo has alias "complete"

### ISSUE THREAD

**Issue by ameotoko** [isotope/core#2133]
It is impossible to place an order in some specific case, when your `completedOrderJumpToPage` is a child page of your Checkout page and has an alias `complete`, i.e. the same as `Checkout::STEP_COMPLETE`. So, if I want my shop to be something like `/shop`, `/shop/checkout` and `/shop/checkout/complete`, the last step will not work, because Contao router will take over and the last checkout step will never run.

It might not be a real issue, but may be it's worth mentioning in the handbook or in a comment. Once you run into this issue, it's nearly impossible to pinpoint, because nothing is erroring, customer gets redirected to the success page, but the order is never placed.

**Comment by aschempp** [comment]
that is true, but unfortunately there is nothing we can do about that. If you create a Contao page with the same path as your news alias, you will run into the exact same issue.
