### ISSUE TITLE
PayPal: Sofortige Zahlungsbestätigung

### ISSUE THREAD

**Issue by DaxCheller** [isotope/core#2137]
> Ein Kunde von uns bekommt in unregelmäßigen Abständen folgende Mail:
> 
> > Guten Tag *** !
> > Bitte überprüfen Sie den Server, der für sofortige Zahlungsbestätigungen von PayPal zuständig ist. Sofortige Zahlungsbestätigungen an den/die folgende(n) URL(s) sind fehlgeschlagen:
> > https://www.***.de/system/modules/isotope/postsale.php?mod=pay&id=1
> > Wenn Sie diese URL nicht erkennen, nutzen Sie vielleicht einen Serviceprovider, der die sofortige Zahlungsbestätigung in Ihrem Namen verwendet. Bitte wenden Sie sich mit den oben genannten Informationen an Ihren Serviceprovider. Wenn dieses Problem weiterhin besteht, könnten die sofortigen Zahlungsbestätigungen für Ihr Konto deaktiviert werden.
> > Wir bedanken uns für die rasche Erledigung dieser Angelegenheit.
> > Herzliche Grüße
> > Ihr PayPal-Team
> 
> Nach einer gewissen Zeit wird IPN deaktiviert und die Bestellungen über PayPal sind in Contao nicht mehr sichtbar bzw. werden im Shop nicht mehr vermerkt. Ein erneutes aktivieren von IPN bringt das ganze wieder zum Laufen und der "Spaß" beginnt von vorne.
> 
> Beim Aufruf des Links erhalte ich "Failed Dependecy", die Ausgabe des postsale logs ist folgende:
> 
> ```
> [01-Apr-2020 07:30:16] New request to https://www.***.de/system/modules/isotope/postsale.php?mod=pay&id=1.
> 
> Headers: array (
>   'HOST' => 'www.***.de',
>   'X_REAL_IP' => '****',
>   'X_FORWARDED_FOR' => '****',
>   'CONNECTION' => 'close',
>   'DNT' => '1',
>   'UPGRADE_INSECURE_REQUESTS' => '1',
>   'USER_AGENT' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36',
>   'SEC_FETCH_DEST' => 'document',
>   'ACCEPT' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
>   'SEC_FETCH_SITE' => 'none',
>   'SEC_FETCH_MODE' => 'navigate',
>   'ACCEPT_ENCODING' => 'gzip, deflate, br',
>   'ACCEPT_LANGUAGE' => 'de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7,fr;q=0.6',
>   'COOKIE' => '_ga=GA1.2.1347637912.1570606706; ISOTOPE_TEMP_CART=6617ed210a7bb303a31058c66f19b165a66ecd86; PHPSESSID=0beb360c8946eddd4bb96283962a868a; BE_USER_AUTH=868528db59d5dd7d208f66679a5a8826c09f45ff; BE_PAGE_OFFSET=0',
> )
> 
> $_GET: array (
>   'mod' => 'pay',
>   'id' => '1',
> )
> 
> $_POST: array (
> )
> 
> Body:
> ```
> 
> Zum System: Es ist ein Contao 4.4.46 mit Isotope 2.6.3, das System wurde von Contao 3.X updated, davor hat alles wunderbar funktioniert.

Trotz der Hinweises von @aschempp Isotope zu updaten besteht das Problem weiterhin. Isotope läuft jetzt unter 2.6.9

**Comment by operatorone** [comment]
Könnte dies nicht durch ein Update auf 4.4.47 gelöst werden? Siehe hier https://github.com/isotope/core/issues/2058#issuecomment-575558468

**Comment by DaxCheller** [comment]
Danke für den Hinweis! Werde ich testen und gebe Rückmeldung, sollte dies die Ursache des Problems sein.

**Comment by aschempp** [comment]
Gibt es dazu eine Rückmeldung?

**Comment by aschempp** [comment]
Duplicate of https://github.com/isotope/core/issues/2123
