### ISSUE TITLE
Product Attribute -> Options not translatable

### ISSUE THREAD

**Issue by leoleimser** [isotope/core#2138]
The options of a product attribute won't get translated. See screenshots below.
I'm using
Contao 4.4.48
Isotope eCommerce 2.6.10

![screenshot_options](https://user-images.githubusercontent.com/51824005/81295572-eae78600-9070-11ea-876e-ec83d56bc09a.png)
![screenshot_translations](https://user-images.githubusercontent.com/51824005/81295569-e9b65900-9070-11ea-872c-1775ac11ec8a.png)

**Comment by aschempp** [comment]
Options can be translated **inside** the option configuration (same as products), you do not need the _translation_ config for that.
