### ISSUE TITLE
Paypal PLUS - Leere Seite nach Absenden

### ISSUE THREAD

**Issue by operatorone** [isotope/core#2139]
Hallo,

wenn ich Paypal PLUS als Zahlungsart im System einstelle und dabei auch einen Live-Key und Secret nutze werde ich nach klicken auf "Bezahlen" in der Kasse auf die URL http://dev.korncorner.de/kasse/process weitergeleitet. Leider sehe ich hier dann nichts mehr bezüglich Paypal oder der Kasse.

Im Code finde ich nur diesen iFrame:

> <div class="mod_iso_checkout block">
> <div class="process first last">
> <div id="paypal_plus5"><iframe id="iframe_0.42271039884508355" allowtransparency="true" scrolling="no" style="height: 150px; border: none; width: 990px;"></iframe></div>
> <script src="https://www.paypalobjects.com/webstatic/ppplus/ppplus.min.js" type="text/javascript"></script>
> <script type="application/javascript">var ppp=PAYPAL.apps.PPP({"approvalUrl":"https://www.paypal.com/cgi-bin/webscr?cmd=_express-checkout&token=EC-0P140337DL659743L","placeholder":"paypal_plus5","mode":"live","country":"DE","language":"de"})</script>
> </div>
> <script>Isotope.checkoutButton(document.getElementById('iso_mod_checkout'))</script>
> </div>

und im Log diesem Eintrag

`[07-May-2020 23:31:37] Array
(
    [intent] => sale
    [redirect_urls] => Array
        (
            [return_url] => http://dev.xxxx.de/kasse/complete?uid=2020-5eb47e023f17b3.46744716
            [cancel_url] => http://dev.xxxx.de/kasse/failed
        )

    [payer] => Array
        (
            [payment_method] => paypal
            [payer_info] => Array
                (
                    [email] => xxxx@gmail.com
                    [first_name] => Hans
                    [last_name] => Dampf
                    [billing_address] => Array
                        (
                            [line1] => Musterstr. 100
                            [city] => Musterhausen
                            [postal_code] => 12345
                            [country_code] => DE
                        )

                )

        )

    [potential_payer_info] => Array
        (
            [billing_address] => Array
                (
                    [line1] => Musterstr. 100
                    [line2] => 
                    [city] => Musterhausen
                    [state] => 
                    [postal_code] => 12345
                    [country_code] => DE
                )

        )

    [transactions] => Array
        (
            [0] => Array
                (
                    [amount] => Array
                        (
                            [total] => 3.59
                            [currency] => EUR
                        )

                    [item_list] => Array
                        (
                            [items] => Array
                                (
                                    [0] => Array
                                        (
                                            [name] => Dinkelkorn 1 Kg
                                            [price] => 3.59
                                            [currency] => EUR
                                            [quantity] => 1
                                            [sku] => DK-010
                                        )

                                )

                        )

                )

        )

)`

Ich bräuchte hier bitte dringend Hilfe. Bin auch Circle-Mitglied.
Danke, Tilman

**Comment by aschempp** [comment]
Mede dich bitte per E-Mail oder im Circle Ticketsystem. Hier bei GitHub ist der „freie Support“.

**Comment by operatorone** [comment]
Habe das Ticket im Circle eingestellt.
