### ISSUE TITLE
Update requires reinstall

### ISSUE THREAD

**Issue by xcy7e** [isotope/core#2141]
After updating the isotope-extension the install-tool forces me to reinstall isotope from scratch.

Am I going to face this situation everytime I'm going to update isotope, in the future?!

Are the isotope-modules on the pages like "Produktleser",etc. be removed when I uninstall isotope? (Will this partially destroy my layout?)

**Comment by fritzmg** [comment]
> After updating the isotope-extension the install-tool forces me to reinstall isotope from scratch.

What exactly do you mean by that?

**Comment by xcy7e** [comment]
It says "Updating the database could destroy your customer/product data. Therefor the database-update-tool was locked" and asks to search for professional help or donation for a migration tool.
Alternatively it recommends uninstalling isotope and reinstalling it.

**Comment by aschempp** [comment]
It looks like you have some tables from Isotope 1 left in your database. Did you update from an old version?

**Comment by aschempp** [comment]
Closing because the issue seems stale.
