### ISSUE TITLE
verrutschte Spaltenüberschrift bei Shop-Konfig Adressdaten

### ISSUE THREAD

**Issue by zonky2** [isotope/core#2143]
bei `th` sollte m.E. die Klasse `hidden` weg und nur beim `div` stehen bleiben

![Zwischenablage02](https://user-images.githubusercontent.com/1045318/82873832-64b6b500-9f35-11ea-975e-af875c37b028.jpg)

**Comment by aschempp** [comment]
das scheint eine Verhaltensänderung im MultiColumnWizard zu sein. Behoben in ce2c884107d0d69eb7274c7ae8a9318445b0a42a

**Comment by zonky2** [comment]
> das scheint eine Verhaltensänderung im MultiColumnWizard zu sein

o.k. - darann habe ich nicht gedacht... dann wäre eine Änderung im MCW ggf. besser?

**Comment by fritzmg** [comment]
The same issue still exists for the attribute tables for product types. But it is an issue of the MCW, not Isotope.

See https://github.com/menatwork/contao-multicolumnwizard-bundle/pull/103
