### ISSUE TITLE
Produktdaten werden nicht geladen

### ISSUE THREAD

**Issue by ghnewbi** [isotope/core#2146]
Hallo, 
ich habe seit dem Update auf Contao 4.9 den gleichen Fehler wie in #2116. Bei Contao 4.4 bestand dieser nicht.
Wenn ich etwas im Dropdownfeld auswähle, um einen Variantenartikel zu laden, erscheint die Meldung "Lade Produktdaten ..." mit dem Drehbildchen und geht nicht wieder weg.
Da dieses Problem nicht bei allen Artikeln auftauchte, habe ich ein bisschen herumprobiert.
Dabei ist mir Folgendes aufgefallen: 
Der Fehler tritt nur dann auf, wenn der Elternartikel mindestens 4 Produktbilder hat und auch nur, wenn ich nicht eingeloggt bin, während ich das Frontend teste. Möglicherweise tritt bei größeren Datenmengen, verursacht durch die Bilder, ein Timeout beim Laden der Varianten per Ajax auf, der aber nur dann auftritt, wenn die Seite aus dem Cache geladen wird.
Vielleicht wäre es hier sinnvoll, beim Aufruf der Varianten die Bilder des Elternartikels nicht noch einmal mitzuladen oder den Wert des Timeouts zu erhöhen.
Viele Grüße

**Comment by aschempp** [comment]
und du hast keinen Javascript-Fehler in der Konsole? Funktioniert denn der Request?

**Comment by ghnewbi** [comment]
Also ich sehe keinen Fehler. Interessant ist, wie ich gerade festgestellt habe, dass die Produkte auch dann geladen werden, wenn ich das Backend nur in einem zweiten Browsertab lade, ohne mich einzuloggen.

**Comment by aschempp** [comment]
das scheint mir eher ein Zufall zu sein. Hast du eine Fehlermeldung im Server-Log? Bekommst du eine Meldung wenn du in Contao 4.9 den Debug-Mode aktivierst? Und/oder siehst du eine Fehlermeldung wenn du dir die (XHR-) Requests in der Browser-Konsole anschaust?

**Comment by bear30** [comment]
Moin, bei mir ist der Fehler auch bei einem Shop bei der Variantenauswahl. 4.9.x geht nicht. 4.4.50 geht.

**Comment by michaelgawlik** [comment]
Moin.

Bei mir steht im Netzwerk-Tab beim wählen einer Option: Type - XHR -> Status (failed) und in der Konsole:
`POST http://blablabla.de/seite.html net::ERR_INCOMPLETE_CHUNKED_ENCODING 200 (OK)`

und bei jedem weiteren klick:
```
Uncaught DOMException: Failed to execute 'send' on 'XMLHttpRequest': The object's state must be OPENED.
    at XMLHttpRequest.window.XMLHttpRequest.send (http://gc.kis.v2.scr.kaspersky-labs.com/FD126C42-EBFA-4E12-B309-BB3FDD723AC…mtfcC6R3uxC03gYj1sRDavKxbtaNY5JbVN3u_uGbnaTnfnPIEB_3aCXfSYoLg1dyMM:1067:18)
    at HTMLFieldSetElement.<anonymous> (http://blablabla.de/system/modules/isotope/assets/js/isotope.min.js?v=88a28a3a:1:4053)
    at HTMLFieldSetElement.dispatch (http://blablabla.de/assets/jquery/js/jquery.min.js?v=f23ac71a:2:42571)
    at HTMLFieldSetElement.v.handle (http://blablabla.de/assets/jquery/js/jquery.min.js?v=f23ac71a:2:40572)
```

In einem Browser in dem diese Kaspersky-Erweiterung nicht installiert ist, scheint es zu funktionieren.

**Comment by bennyborn** [comment]
Wir hatten das Problem letztens auch bei einem Kunden.

Die Seite lief via HTTPS und beim Hoster (IONOS) war HTTP2 aktiv. Die Meldung im Chrome war `ERR_HTTP2_PROTOCOL_ERROR`.
Mit HTTP war es dann die o.g. `ERR_INCOMPLETE_CHUNKED_ENCODING`.
Leider haben wir keine wirkliche Lösung gefunden.

Da auf unserem Vorschauserver alles klappte haben wir dem Kunden zu einem Umzug auf einen anderen Hoster geraten. Dort trat das Problem dann auch nicht mehr auf.

In unserem Fall waren keine Erweiterungen oder Virenscanner involviert.

**Comment by HenryVolkmer** [comment]
related https://github.com/isotope/core/issues/2154

**Comment by bear30** [comment]
Ich habe das Problem jetzt auch auf einem Server von IONOS (ehemals 1und1) nach dem Update auf die 4.9.5. 

Auch dort hängt ein Shop bei der Variantenauswahl in der Sanduhr fest. Selbe Fehlermeldung im Chrome wie bei bennyborn. Ich habe den Shop jetzt mal zu all-inkl. rüber gespiegelt und dort getestet. Da funktioniert alles. Das scheint also irgendwie mal wieder an den Servereinstellungen von BigBlue zu hängen. Leider hilft mir das nicht weiter, da der Kunde auf den Server dort schwört. 

Hat da jemand vielleicht noch eine Idee dazu?

Contao 4.9.5 und Isotope 2.6.13.

**Comment by bear30** [comment]
Ich habe noch etwas weiter daran herumgespielt. Legt man erst den aus Standardartikel in den Warenkorb und wählt dann eine Variante (auch von einem andern Produkt mit Varianten) dann hängt er nicht mehr und alles funktioniert ab dann ohne Fehler. 
Hängt das wieder mit dem Setzen des Token-Cookies zusammen? Also mal den Workaround von fritzmg aus https://github.com/contao/contao/issues/2246 eingebaut und getestet. Das ändert an dem, dass das Token-Cookie gelöscht wird bei Ionos nichts. Das Cookie verschwindet sobald sich die Sanduhr dreht, dann passiert ein paar Sekunden in der Console nichts und dann erscheint der net::ERR_HTTP2_PROTOCOL_ERROR 200.

**Comment by aschempp** [comment]
We've been able to fix this in Contao core (https://github.com/contao/contao/pull/2416) thanks to an Isotope Circle member 😎  for anyone not on the latest Contao version, this is most likely also fixed by https://github.com/codefog/contao-haste/pull/154

**Comment by eBlick** [comment]
This behaviour seems to be back on Contao 4.9.24 an isotope 2.7.4

`Uncaught DOMException: Failed to execute 'send' on 'XMLHttpRequest': The object's state must be OPENED.
    at HTMLFieldSetElement.submitForm (https://domain/system/modules/isotope/assets/js/isotope.js?v=8cee0302:262:21)
    at HTMLFieldSetElement.dispatch (domain/assets/jquery/js/jquery.min.js?v=0e7977d2:2:43064)
    at HTMLFieldSetElement.v.handle (domain/assets/jquery/js/jquery.min.js?v=0e7977d2:2:41048)`
