### ISSUE TITLE
Attribute Download

### ISSUE THREAD

**Issue by bekanntmacher** [isotope/core#2148]
Das Attribute "Download" scheint nicht korrekt zu funktionieren. Zwar wird mit '<?= $this->generateAttribute('pdf'); ?>' das PDF sauber angezeigt. 

Das Attribut ist einem Variantenartikel auf Ebene Variante zugeordnet.
Bei Klick passiert nichts. Beim Wechsel der Variante wird das PDF inline ausgegeben (
![Naturmedizinpendel__Baj__-_Verlag_RGS](https://user-images.githubusercontent.com/1622464/84482920-de220780-ac98-11ea-9f0e-15f3d320e07f.png)

Beim Dem Link fehlt der Parameter 'cid'

**Comment by bekanntmacher** [comment]
Kann ich hier noch irgend etwas beitragen, helfen, nachprüfen, etc. ?

**Comment by aschempp** [comment]
was erwartest du denn von der Methode? Das PDF wird damit ja im Reader ausgegeben, das macht doch keinen Sinn?
