### ISSUE TITLE
Download auf gleicher Seite wie Leser

### ISSUE THREAD

**Issue by bekanntmacher** [isotope/core#2149]
Fügt man im Artikel wo sich der reader befindet ein CE-Element Download ein führt die bei Klick zu einem 404. (Filter, Liste und Leser sind dabei alle im selben Artikel)

**Comment by aschempp** [comment]
hilfreich wäre welchen Fehler du bekommst? 😉

**Comment by bekanntmacher** [comment]
Das Problem ist nicht mehr da. Reproduzieren kann ich es nicht mehr. Es tauchte auf mit etlichen Tests diesbezüglich: https://github.com/isotope/core/issues/2148 auf. Ev. hatte es etwas mit dem Cache zu tun, welchen ich nochmals gelöscht habe.

Ich schliesse mal dieses Ticket.
