### ISSUE TITLE
Product specific shipping price shows only the highest and not the sum

### ISSUE THREAD

**Issue by biwerr** [isotope/core#2150]
I don't know if its by design but if you put multiple Products with Product specific shipping prices in your basket. You will only the the Shipping Prices from the Product with the hightest shippig rate.

In our Case we want to get the sum of the shipping prices from the products. How can i fix this?

**Comment by aschempp** [comment]
A new option in Isotope 2.7 will allow to choose this: https://github.com/isotope/core/commit/60f0a5978e5f221f475f54d2552017cdcfdf44e9

**Comment by biwerr** [comment]
Thanks for the quick fix 👍
