### ISSUE TITLE
Pages filter in Product Management no longer refreshes the page

### ISSUE THREAD

**Issue by rhymeadam** [isotope/core#2158]
Hi guys, not sure if this has been added yet so sorry if it has!

I recently installed Contao 4.10 and I'm noticing that the "Pages" filter no longer works.  I tracked it down to the AJAX call where it's calling Controller::reload().  Basically, while they were working on 4.10, they changed the status code for the Ajax exception response from 302, to 307, and again so now it's 303.

https://github.com/contao/core-bundle/blob/master/src/Exception/AjaxRedirectResponseException.php#L19

I think we just need to add codes 307 and 303 to backend.js for the new Contao exception versions to fix this issue.

https://github.com/isotope/core/blob/master/system/modules/isotope/assets/js/backend.js#L111

https://github.com/isotope/core/blob/master/system/modules/isotope/assets/js/backend.js#L191

**Comment by Tastaturberuf** [comment]
I have this one in Contao 4.9.5 too.

**Comment by chberger** [comment]
Same issue with Contao 4.4.51. Response code is 303, but backend.js checks for 302 ...

**Comment by aschempp** [comment]
This should be fixed by #2161

**Comment by Tastaturberuf** [comment]
Yes is solved with 2.4.16. Thanks @aschempp
