### ISSUE TITLE
Änderungen der manuelle Sortierung nicht möglich - Contao 4.9 - Isotope 2.6.13

### ISSUE THREAD

**Issue by Ainschy** [isotope/core#2163]
Will man die Reihenfolge der Produkte einer Kategorie / Seite über die manuelle Sortierung in isotope ändern wird das Overlay zur Sortierung nicht fertig geladen, das Loading-Spinner-Overlay bleibt stehen.

Die Seitenauswahl wird korrekt geladen, das darauf folgende Overlay für die Sortierung hängt. Der Link wird korrekt per Ajax aufgerufen (händisch den Request im neuen Tag aufgerufen, die Liste wird geladen) aber nicht angezeigt.

**Comment by fritzmg** [comment]
Welche Contao Version?

**Comment by Ainschy** [comment]
4.9.5

**Comment by fritzmg** [comment]
> leider gibts keinen Hinweis an welcher Stelle die Anfrage nicht durch geht

Überprüfe den Request über den Network Tab deines Browsers.

**Comment by Ainschy** [comment]
Der Ajax Request wird korrekt aufgerufen, hab den Request in einen neuen Tab erfolgreich öffnen können.

![xhr Request Overlay](https://user-images.githubusercontent.com/1788135/91636906-a3f91400-ea04-11ea-9d00-87bf3d1c58c2.png)

**Comment by fritzmg** [comment]
May be related to https://github.com/isotope/core/pull/2161 ? Try to replace the files from PR #2161 and #2162

**Comment by Ainschy** [comment]
Works for me (y)
