### ISSUE TITLE
Konflikt bei Mehrsprachigkeit zwischen Isotope & Contao-News-Kategorien

### ISSUE THREAD

**Issue by HendrikBengs** [isotope/core#2164]
Ich nutze eine mehrsprachige Contao-Installation (4.4) mit Isotope. Ich habe zusätzlich dazu die Erweiterung `codefog/contao-news_categories` installiert und wollte die Mehrsprachigkeit aktivieren (https://github.com/codefog/contao-news_categories/blob/master/docs/multilingual-features.md). Dazu ist es notwendig die Erweiterung `terminal42/dc_multilingual` in der Version `^3.0` zu installieren. Isotope nutzt dieselbe Erweiterung in der Version `~2.0`. Durch diesen Konflikt ist eine Nutzung der Mehrsprachigkeit innerhalb der Erweiterung `codefog/contao-news_categories`  leider nicht möglich.

Gibt es bereits Erfahrungen mit dieser Kombination / Problematik? (Isotope + News-Kategorien + Mehrsprachigkeit)

**Comment by aschempp** [comment]
The current version v4 does not work with Contao 3, but Isotope does. We should update the dependency though and raise the minimum requirement for Isotope.

**Comment by aschempp** [comment]
added in 459d2a7077d0462ce675d3467461f8646505452a (with BC for Contao 3.5 🙈 )
