### ISSUE TITLE
Bezahldatum bleibt leer, beim Verwenden von PayPal Plus

### ISSUE THREAD

**Issue by flowerner** [isotope/core#2165]
Wir sind vor kurzem bei einem Shop von der normalen PayPal Option zu PayPal Plus gewechselt. Seitdem bleibt im Backend in der Detailansicht der Bestellungen das Datum leer.
Contao: 3.5.40
Isotope: 2.6.13
![Bildschirmfoto 2020-09-13 um 19 49 54](https://user-images.githubusercontent.com/26644534/93024978-8a59ee00-f5fa-11ea-8951-c732f338a8c1.png)

**Comment by flowerner** [comment]
Eine Vermutung zum Bug. In den anderen Funktionen wird am Schluss noch das Order-Objekt gespeichert, in der PayPal Plus Option nicht.
Hier der Part aus der PayPal.php
`$objOrder->setDatePaid(time());
 $objOrder->updateOrderStatus($this->new_order_status);

 $objOrder->save();`

Und hier der Part aus der PayPalPlus.php
`$objOrder->checkout();
        $objOrder->setDatePaid(time());
        $objOrder->updateOrderStatus($this->new_order_status);
        

        return true;`

**Comment by aschempp** [comment]
Geändert in 81baf7338604cddf3e9362d396539480ccae3157
