### ISSUE TITLE
Can't add products to cart

### ISSUE THREAD

**Issue by onemarshall** [isotope/core#2168]
Hi, when I try to add/click the 'Add To Cart' button, the page refreshes, but no product is added to the cart, and the page does not redirect to cart page.

I have tried a fresh install of Contao 4.9.8 and installed the Isotope (Version: 2.6.13) demo, but this too does the same thing with the T-Shirts, and there is an error when you click on a CD product, 'tracks is not a valid attribute'.

The 2042 Outer space item can be added the cart, is there an issue with variants?

**Contao**: 4.9.8
**Isotope**: 2.6.13
**PHP**: 7.3.23

Thanks

**Please watch video for details.**
https://www.loom.com/share/a7841fcb372842c39998f8e5cedf4ccd

![Screenshot 2020-10-08 at 09 03 02](https://user-images.githubusercontent.com/59648/95431462-1b478f00-0945-11eb-92d3-6ee74eef6fd3.png)

**Comment by aschempp** [comment]
I've seen this before if you have a cookie bar or adblocker that does not allow the teporary cart cookie

**Comment by onemarshall** [comment]
Hi Aschempp, thanks for pointing that out!

**Comment by aschempp** [comment]
I guess that means it's fixed 😂

**Comment by vmulot** [comment]
Hi, i have the same pb on Contao 3.5.4 & Isotope 2.6.15,
i have product variants enabled, but i don't need variant options on product list, so i checked : Disable product options (performance!) on the product list module. 
When checked, the add to cart button isn't working, just refreshing the page, if i uncheck, it's adding to cart.

I have no ad blocker nor cookie bar, any idea ?
Thanks
Note : i'm in preview mode, all the shop pages are hidden, don't know yet if it's the pb.

**Comment by aschempp** [comment]
This will not work. You cannot add a product to the cart without selecting a variant, and you can't select a variant if you disable product options.

**Comment by vmulot** [comment]
Can't it use the default variant when the checkbox is checked?
Thanks

**Comment by aschempp** [comment]
Please create a separate issue to discuss new ideas
