### ISSUE TITLE
Not possible to "manually sort products in a page"

### ISSUE THREAD

**Issue by V15** [isotope/core#2169]
If I try to manually sort products in a page, I can choose the page in the site structure but after hitting "apply" I get the spinnig "Loading data ..." dialog and thats it. Might be similar to the problem [#2158](https://github.com/isotope/core/issues/2158#issue-685729596) 

Contao 4.4.54
Isotope 2.6.13

**Comment by aschempp** [comment]
This should be fixed by https://github.com/isotope/core/pull/2161
