### ISSUE TITLE
Produktliste lädt nicht. Artikel zwischen verschiednen Gruppen verschieben funktioniert nicht

### ISSUE THREAD

**Issue by webmurkser** [isotope/core#2170]
Contao: 4.9.8
Isotope: 2.6.13

![produktliste-laedt-nicht](https://user-images.githubusercontent.com/8065885/95653011-9b145b80-0af5-11eb-9a32-e90e5cc3947c.jpg)
Versuche ich über den Button: "Grupen" die Ansicht der Artikel nur auf eine bestimmte Gruppe einzugrenzen, lädt dies nicht. Siehe Bild. Bricht man den Ladevorgang mit einem refresh der Seite ab, werden die Produkte korrekt angezeigt (also der Inhalt der gewünschten Produktgruppe). 

Handelt es sich um eine Produktgruppe die "tiefer" liegt kann man über das breadcrumb Menü der Produktgruppen problemlos zu anderen Gruppen wechseln. Also egal wie viel Ebenen.
![breadcrum-auswahl](https://user-images.githubusercontent.com/8065885/95653106-402f3400-0af6-11eb-9ebf-ace41c475fb5.jpg)
Hier könnte ich entweder auf "Kleidung" oder auf "Alle" klicken - Artikel werden geladen.

Was bei der Gelegenheit auch nicht geht, ist, wenn man  einen Artikel in eine andere Produktgruppe mit dem "Produktgruppen-Icon" verschieben möchte. 
![produktgruppe-zuordnen](https://user-images.githubusercontent.com/8065885/95653166-c0ee3000-0af6-11eb-99c9-fd45966fe808.jpg) - hier ist das Problem identisch zu der Produktliste laden. Die Auswahl ist möglich aber sobald man diese bestätigt, lädt dies ewig ohne Ergebnis. Hier allerdings mit der Konsequenz, dass ein refresh der Seite keine "Verschiebung" des Artikels durchführt - es bleibt wie es war.

Im Error-Log /var/logs ist nichts zu finden. Auch im Contao System-Log (Backend) ist nicht. Alle Caches bereits gelöscht.

**Comment by fritzmg** [comment]
Is there a JavasScript error in the console?

**Comment by webmurkser** [comment]
Nein, keine Fehler - nur mehrere identische Warnungen:
`The Theme.hoverRow() function has been deprecated in Contao 4 and will be removed in Contao 5. Assign the CSS class "hover-row" instead.
hoverRow @ mootools.min.js,mooRainbow.min.js,chosen.min.js,simplemodal.min....-3b539eaa.js:8
onmouseout @ contao?do=iso_products&ref=yuLeabj0:515`
Je nach Kategorie mal mehr mal weniger identische Zeilen.

**Comment by aschempp** [comment]
This should be fixed by #2161
