### ISSUE TITLE
"Daten werden geladen" bleibt "hängen" - Produktgruppen / Auswahl Sortierung Backend

### ISSUE THREAD

**Issue by xprojects-de** [isotope/core#2172]
Hallo zusammen,

will ich im Backend nach Produktgruppen anzeigen bzw. die Sorttierung nach Kategorie anzeigen geht das "Daten werden geladen" nicht mehr weg und bleibt forever.

In der Javasscript-Konsole wird kein Fehler geworfen.

Kennt ihr das Problem?

Isotope 2.6.13 unter Contao 4.9.9
![Bildschirmfoto 2020-10-30 um 18 57 11](https://user-images.githubusercontent.com/55982921/97740930-40fa2b00-1ae2-11eb-9a7a-ab521e57d1ae.png)

Danke und Grüße

**Comment by aschempp** [comment]
Duplicate of https://github.com/isotope/core/issues/2170

**Comment by contaoacademy** [comment]
Ich habe das Problem mit der 2.6.14 unter Contao 4.4.54 immer noch. Kannst du noch mal prüfen ob der Fix auch für Contao 4.4 funktoniert?

**Comment by contaoacademy** [comment]
Vergiss es. Lag wohl am Browser-Cache… Jetzt geht es.
