### ISSUE TITLE
Frontend 404 Error

### ISSUE THREAD

**Issue by mohanaraj1812** [isotope/core#2173]
Hello all, 

I am new to Contao CMS with Isotope e-Commerce. I have installed both systems based on the available documentation/instruction. 

Further, when I open the store front-end I saw only the 404 error instead of the index/sample page. I unable to resolve this issue with a forum, etc.,

So, I request could anyone please assist me to resolve this issue and share the references to create the eCommerce storefront related setup(Like other shops (Magento) storefront pages) if possible.

Thanks in advance.

**Comment by aschempp** [comment]
This is the bug and feature tracker for Isotope eCommerce. Please refer to the Contao support options (https://to.contao.org/support) to get help about setting up your Contao installation.
