### ISSUE TITLE
Add to Cart button creates no cookie!

### ISSUE THREAD

**Issue by onemarshall** [isotope/core#2175]
Hi,
I have an issue with the 'Add to cart' button!
When the 'Add to cart' button is clicked in the reader page, it does not generate the cookie (ISOTOPE_TEMP_CART), so the product is not added to the cart! I have checked that there is no cookie bar or ad blocker! 

What could be the issue?
Thanks

**Comment by aschempp** [comment]
looks like you solved the issue?
