### ISSUE TITLE
Adressbuch Adresse bearbeiten oder hinzufügen leer

### ISSUE THREAD

**Issue by SGehle** [isotope/core#2178]
Sobald ich versuche eine Adresse zu bearbeiten oder hinzuzufügen wird nichts ausgegeben. 
Der Workaround aus #2084 funktioniert leider nicht, das Formular wird weiterhin nicht angezeigt. Das löschen der Adressen funktioniert hingegen.

Contao: 4.9.9
Isotope: 2.6.14

**Comment by aschempp** [comment]
Fixed in 8e6111cec156116949d80b0b15e92db40f69c290. The issue occurs because you did not select a member template in the module configuration (because that field is apparently not mandatory anymore in latest Contao).
