### ISSUE TITLE
compatibility issues due to dc_multilingual

### ISSUE THREAD

**Issue by asaage** [isotope/core#2179]
Is there a way you could require a higher version of [DC_Multilingual](https://github.com/terminal42/contao-DC_Multilingual)?
I want to use [news_categories](https://github.com/codefog/contao-news_categories) but composer can't resolve version conflicts.
I'm running contao 4.10.

**Comment by fritzmg** [comment]
Duplicate of https://github.com/isotope/core/issues/2164

**Comment by asaage** [comment]
Thank you.
🤔 i don't expect 2.7 to be comming soon.

**Comment by asaage** [comment]
@fritzmg could you tell me how to require the named branch with the included fix?
It should be https://github.com/isotope/core/tree/feature/rule-group but i'm only familiar with taged-versions and ```@dev``` and it's not in dev.

**Comment by fritzmg** [comment]
You can just require `dev-develop`.
