### ISSUE TITLE
Produktleser - seperate Detailseite

### ISSUE THREAD

**Issue by pet21221** [isotope/core#2182]
Seit dem Update auf isotope 2.6.15 von 2.5.10 habe ich folgendes Problem.
Die Detailseite "produkt.html" (Produktleser) wird nicht korrekt ausgegeben. Stattdessen sehe ich statische Inhalte aus der Seite, wo die Produktliste integriert ist und den Title aus meiner 404-Seite. Aber nicht die eigentliche produkt.html-Seite. Bei einem Downgrade auf 2.5 funktioniert es wieder einwandfrei. Ab der 2.6 nicht mehr.

Das Häkchen in der Produktliste-Konfiguration "Ausblenden bei Produktansicht" wurde zusätzlich gesetzt.

Ich habe im Forum und hier nach ähnlichem Fehlerbild gesucht. Leider hat mir nichts dergleichen geholfen. Das sieht mir nach einem Bug aus.

**Comment by aschempp** [comment]
möglicherweise hast du eine spezielle Konfiguration und must in der Produktliste die Option `Link zur primären URL` aktivieren.

**Comment by pet21221** [comment]
Der Fehler tritt in Kombination mit contao-inherit-article auf. Sprich mit Artikeln, die auf Unterseiten vererbt können. Zuvor gab es nie Probleme in Kombi - erst mit der 2.6*-Version.

**Comment by aschempp** [comment]
dann könnte es gut sein dass die Erweiterung mit Isotope nicht kompatibel ist, da Isotope die URL-Struktur manipuliert. Das werden wir wohl erst ändern können wenn Isotope nur noch mit Contao 4.10+ funktioniert (= das wird noch sehr lange dauern).
