### ISSUE TITLE
Isotope breaks log rotation in Contao 4

### ISSUE THREAD

**Issue by dmolineus** [isotope/core#2183]
Since #2065 the `Contao\Automator::logRotate`  is readded to the cron job by Isotope (https://github.com/isotope/core/search?q=rotatelogs). The Contao\Automator::logRotate rotates all log files in system/logs. In fact system/logs is a symlink to var/logs so it affects all log files generated by monolog. The issue occurs because of the different log file formats. Contao expects a fixed log file name, like error.log. The monolog configuration creates a date based error log file prod-YYYY-MM-DD.log. The Contao log rotation adds a numeric suffix to the files, which doesn't make any sense for date based files. As the result the the log directory is spamed with date based log files having the suffix .1.

Reference: https://github.com/contao/contao/issues/2579

**Comment by aschempp** [comment]
I don't think this is something we can fix in Isotope but a Contao bug?

**Comment by aschempp** [comment]
This has been fixed in Contao core in the meantime.
