### ISSUE TITLE
mPay24 - API Anpassungen ab 01.01.2021

### ISSUE THREAD

**Issue by saress** [isotope/core#2184]
Wie auf Slack bereits angemerkt [https://contao.slack.com/archives/CLTUNH78X/p1608548888302400](https://contao.slack.com/archives/CLTUNH78X/p1608548888302400) wird es lt. Auskunft von Unzer (neuer Eigentümer von mPay24) ab 01.01.2021 eine Umstellung auf PSD2 und 3D Secure 2.0 geben und damit verbunden müssen zukünftig auch einige Kundendaten übermittelt werden.

Der Support hat bezüglich der zu übergebenden Daten folgende Infos übermittelt:

[https://docs.mpay24.com/docs/extended-requirements](https://docs.mpay24.com/docs/extended-requirements)

`
 <BillingAddr Mode="ReadOnly">
  <Name Gender="M" Birthday="1990-01-31">John Doe</Name>
  <Street>Main street 1</Street>
  <Zip>1010</Zip>
  <City>Vienna</City>
  <Country Code="AT" />
  <Email>billing@mpay24.test</Email>
  <Phone>+4368012345678</Phone>
 </BillingAddr>
 `

und hier noch ein Beispiel der Übergabe:

[https://github.com/mpay24/mpay24-php/wiki/How-to-work-with-Order-objects](https://github.com/mpay24/mpay24-php/wiki/How-to-work-with-Order-objects)

Vorab herzlichen Dank
Sascha

**Comment by aschempp** [comment]
Fixed in c92bb18c9cf66533b84339f01a7cd1cb0c8d1193
