### ISSUE TITLE
Question: dc_multilingual requirement.

### ISSUE THREAD

**Issue by rburch** [isotope/core#2186]
I see 2.7 is really close. Is it stable enough to try on a dev site? I'm having issues with other plugins that need a newer version of dc_multilingual, but 2.6.15 still requires an older version.

**Comment by asaage** [comment]
>  stable enough to try on a dev site?

I'm having no issues so far - but i didn't try any payment-related stuff.

**Comment by rburch** [comment]
OKay great. I don't the payment stuff at this point anyway.

**Comment by aschempp** [comment]
Be aware that there is currently a major issue in DC_Multilingual support: https://github.com/terminal42/contao-DC_Multilingual/pull/70

If you're using multilingual product attributes, better not update to 2.7 or it might break your data. Everything else is fine, we hope to fix (and release) 2.7 by next week 🎉
