### ISSUE TITLE
[2.6.15] Mehrere Produkte bearbeiten/überschreiben - SQL Fehler duplicate entry in pid_fromtable_version

### ISSUE THREAD

**Issue by digitalraumtcc** [isotope/core#2188]
Contao: Version 4.9.9
Isotope: Version 2.6.15

Bei der Contao Funktion "mehrere bearbeiten" kommt es zu einem leicht reproduzierbaren Fehler: 

Vorgangsweise in meiner Demo Installation: 
1) Produkte 
2) mehrere Bearbeiten 
3) Auswahl von 2008 Würzburg und 2009 Frankfurt
4) bearbeiten
5) Name wählen 
6) beliebige Änderung 
7) speichern 

Resultat ist folgender Fehler: 

> An exception occurred while executing 'INSERT INTO tl_version (`pid`, `tstamp`, `version`, `fromTable`, `username`, `userid`, `description`, `editUrl`, `active`, `data`) VALUES ('20', '1611071236', '2', 'tl_iso_product_price', 'backendlogin', '1', '2008 Würzburg 2', 'contao?do=iso_products&act=edit&id=20&rt=MLz_B238r3O0qdsfdssdsdlXDutGiqsZNCYpvC2k2VCxs&ref=Mrpp5EB1&fields=1', '1', 'a:2:{s:6:\"prices\";a:0:{}s:5:\"tiers\";a:0:{}}')': SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '20-tl_iso_product_price-2' for key 'pid_fromtable_version'

**Comment by 9teufel** [comment]
Kann den selben Fehler bestätigen.

Contao 4.9.11
Isotope 2.6.15

Wurde auch schon im Forum gemeldet:
https://community.contao.org/de/showthread.php?79987-Datenbankfehler-mehrere-Produkte-überschreiben-eigenes-Attribut
