### ISSUE TITLE
Validierung schlägt fehl, wenn Bestellbedingungsformulare für Checkout angegeben werden

### ISSUE THREAD

**Issue by kollmeier** [isotope/core#2193]
Da die generierten Optionvalues Backslashes enthalten, werden sie durch das Selectfield escaped. Dem Widget muss ein `['eval']['decodeEntities'] = true` mitgegeben werden, was fälschlicherweise dem MultiColumnWizard übergeben wird:
https://github.com/isotope/core/blob/e3b77e13b37b38429566d3e50318befc1561f989/system/modules/isotope/dca/tl_module.php#L327

Besser wäre es hier aufgehoben:
https://github.com/isotope/core/blob/e3b77e13b37b38429566d3e50318befc1561f989/system/modules/isotope/library/Isotope/Backend/Module/OrderConditionFields.php#L40

```php
'step' => [
                'label' => &$GLOBALS['TL_LANG']['tl_module']['iso_order_conditions']['step'],
                'inputType' => 'select',
                'options_callback' => ['Isotope\Backend\Module\OrderConditionFields', 'getSteps'],
                'eval' => [
                   'decodeEntities' => true,
                    'includeBlankOption' => true,
                    'style' => 'width:300px',
                    'columnPos' => 'checkout',
                ],
            ],
```

**Comment by aschempp** [comment]
Closed in favour of https://github.com/isotope/core/pull/2194
