### ISSUE TITLE
Featurewunsch: Bestellbedingungsformulare abhängig von Produktvarianten im Warenkorb anzeigen

### ISSUE THREAD

**Issue by kollmeier** [isotope/core#2195]
Bestellbedingungsformulare können (Stand Version 2.7) abhängig von Produkttypen angezeigt werden. Wenn ich allerdings Produkte habe, die von Produktvarianten abhängig weitere Angaben benötigen, dann können diese nicht nur bei Bedarf angezeigt werden (da der Produkttyp bei Varianten gleich bleibt).

Beispiel:
Ich verkaufe Audio-CDs, will meinen Kunden aber die Möglichkeit bieten, diese als Download direkt zu laden, während der Versand läuft, falls das gewünscht ist. Dazu habe ich drei Produktvarianten "Nur Versand", "Versand + Download" und "Nur Download". Nur bei den Varianten, die einen Download beinhalten, soll das Formular "Ich verzichte auf das 14-tägige Widerrufsrecht, um die Downloads direkt zu erhalten" angezeigt werden.

Das kann meines Erachtens gelöst werden, indem das Formular von der entsprechenden Produktvariante abhängig gemacht werden kann.

**Comment by fritzmg** [comment]
There are several ways you could already achieve that right now. You could for example adjust the form dynamically with the  `orderConditions` Isotope Hook. Or you could implement your own Checkout step and replace the existing `\Isotope\CheckoutStep\OrderConditions*` steps.

**Comment by kollmeier** [comment]
Thank you for your response! I will try that and close this request.

Am Do., 18. Feb. 2021 um 10:29 Uhr schrieb Fritz Michael Gschwantner <
notifications@github.com>:
