### ISSUE TITLE
Error in PayPal Plus checkout

### ISSUE THREAD

**Issue by danielkochengineer** [isotope/core#2200]
Hi,

in Isotope 2.7 (Contao 4.9) I get the following error message after clicking the purchase button:

Zugriff nicht erlaubt

When I inspect it, it shows this error:

[Error] Refused to change the document base URL to https://www.paypalobjects.com/web/res/42d/e43ec3e8876931cd23820cc0008e9 because it does not appear in the base-uri directive of the Content Security Policy.

Do I have a mistake in my setup or is this a bug?

Thank you!

**Comment by aschempp** [comment]
Sounds like a bug in your setup, maybe you server sets incorrect Content Security Policy?

**Comment by danielkochengineer** [comment]
Thanks @aschempp. How can I check my server settings for this policy? In the previous version 2.6 it worked just fine. By the way, I am on Hetzner Webhosting Level 1.

**Comment by aschempp** [comment]
In Isotope 2.6, a user was (incorrectly) redirected to PayPal instead of displaying PayPal PLUS on the website with javascript. Either you should use PayPal Standard (if you did not actively subscribe to PayPal PLUS) or contact your hosting provider if they implemented a _Content Security Policy_.
