### ISSUE TITLE
Tracking numbers for shipping token doesn't work

### ISSUE THREAD

**Issue by sietsevandreven** [isotope/core#2208]
Isotope 2.7
Contao 4.9.12
NotificationCenter Version 1.5.18

When Updating order status:

We want to use Tracking Numbers. Under that field there's the following help text:
_Here you can enter the shipping tracking information. Use the ##log_shipping_tracking## simple token in the notification._

But whenever we try to use ##log_shipping_tracking## in our corresponding Notification Center message, our text editor gives this error:
_The following tokens you have used are not supported by this notification type: ##log_shipping_tracking##_

**Comment by qzminski** [comment]
It's only about the labels and it will be fixed once #2207 is merged.
