### ISSUE TITLE
Checkout Order Conditions form

### ISSUE THREAD

**Issue by rburch** [isotope/core#2211]
I made a contao form for people to upload proof of being a tax free organization during checkout. I'm running into an issue in the Checkout module that my checkout steps are invalid not matter what I select.

Here's a screen shot: 
<img width="699" alt="Screen Shot 2021-03-24 at 3 12 32 PM" src="https://user-images.githubusercontent.com/1537395/112370807-3704de80-8cb4-11eb-8c6b-ede2330707d9.png">

**Comment by aschempp** [comment]
I'm pretty sure uploads will not work at that stage, what should happen to the files?
Regarding the error, did you correctly name the fields (e.g. not reuse the same name multiple times)?

**Comment by aschempp** [comment]
Sorry, I just realized this actually shows the backend configuration. This issue should be fixed by https://github.com/isotope/core/pull/2194
