### ISSUE TITLE
Related Products Cache Error

### ISSUE THREAD

**Issue by Xirdion** [isotope/core#2212]
Contao Version: 4.9
Isotope Version: 2.6.15

### Folgendes Szenario:
Bei einem Produkt sind verschiedene IDs als Related Products hinterlegt.
Das Hauptprodukt gibt es verschiedenen Sprachen.
Die Related Products aber (noch) nicht.

Wenn nun z. B. für die Deutsche Seite die Produkte geladen werden, werden die IDs der Related Products in die Cache-Tabelle geschrieben.
Wechselt man auf eine Sprache, für welche die Related Products noch nicht definiert sind, dann wird zuerst versucht aus dem Cache die IDs zu laden. Diese werden auch gefunden. Allerdings können die Artikel nicht angezeigt werden, weil sie in der Ziel-Sprache noch nicht existieren.
Darum werden 0 Produkte geladen. Das neue Ergebnis wird wiederum in den Cache geschrieben.

Wechselt man wieder auf die deutsche Seite, dann wird der Cache-Eintrag gelesen, in welchem **für die IDs ein leeres Feld** steht. Somit werden nun auch auf der deutschen Seite **keine Produkte** angezeigt, obwohl diese existieren.

### Verbesserung:
Beim Schreiben in den Cache sollte eventuell die **aktuelle Sprache** mitgespeichert werden.

Des Weiteren wäre es schön, wenn man auswählen kann, dass das Fallback-Produkt stattdessen angezeigt werden könnte, wenn es für die Sprache noch nichts gibt.

**Comment by aschempp** [comment]
Hmm, nach meinem Verständnis werden die Produkte doch in der Fallback-Sprache angezeigt, wenn sie nicht übersetzt sind? Oder meinst du damit dass du sie nicht der entsprechenden Seitenstruktur zugewiesen hast? Lässt sich das Problem vielleicht lösen indem du verschiedene Frontend-Module verwendest?

**Comment by Xirdion** [comment]
Wir haben herausgefunden, dass die Produkte angezeigt werden, wenn sie eine Kategorie in der entsprechenden Zielsprache besitzen.
Dies war uns vorher nicht bewusst und haben deshalb erwartet, dass immer die Fallback-Sprache angezeigt wird, auch wenn das Produkt keine Kategorie (Seite) in dieser Sprache besitzt.

**Comment by aschempp** [comment]
Nein das ist nicht der Fall. Das Produkt muss mindestens einer Seite in jeder Root-Seitenstruktur zugewiesen sein. Ich schliesse demnach das Ticket, aber wir können es gerne wieder öffnen falls du noch einen Fehler findest.
