### ISSUE TITLE
Ausgegraute Punkte in der Statistik

### ISSUE THREAD

**Issue by netzarbeiter** [isotope/core#2218]
In der Statistik hat es einige ausgegraute Punkte.

![statistik](https://user-images.githubusercontent.com/1942550/113980494-d692a700-9846-11eb-8647-dbf5cd26d4b4.png)

So viel ich weiss, ist die Idee dahinter, Möglichkeiten einer Implementierungen aufzuzeigen.

Für die [Benutzer:innen](https://community.contao.org/de/showthread.php?80694-Gutscheinstatistik-immer-leer) ist es missverständlich, weil sie denken, irgendetwas in der Konfiguration vergessen zu haben.

Mögliche Lösung:
- Wir entfernen die nicht implementierten Punkte
- Wir weissen textlich darauf hin, dass diese Punkte noch nicht in Isotope zur Verfügung stehen und an wenn man sich wenden kann, um diese umzusetzen

**Comment by aschempp** [comment]
Ich denke wir können die tatsächlich entfernen. Sie waren als Ideen für weitere Statistiken gedacht, aber nie umgesetzt.
