### ISSUE TITLE
Do not start session to check if messages exist

### ISSUE THREAD

**Issue by rabauss** [isotope/core#2220]
Unfortunately, every check for messages is starting a session here:
https://github.com/isotope/core/blob/a558651ce8ff422f389a29708d922841831ad552/system/modules/isotope/library/Isotope/Message.php#L172

 that prevents caching on every non isotope page because the `modifyFrontendPage` hook triggers the check always here:
https://github.com/isotope/core/blob/a558651ce8ff422f389a29708d922841831ad552/system/modules/isotope/library/Isotope/Frontend.php#L227

@fritzmg mentioned in slack that it has to be refactored to `\Contao\Session` and because of https://github.com/contao/contao/pull/2954 this would be solved!

**Comment by aschempp** [comment]
That's why I created https://github.com/contao/contao/pull/2954 😆
