### ISSUE TITLE
generateAttribute('type') unterschiedliche Ausgabe

### ISSUE THREAD

**Issue by skalec** [isotope/core#2221]
Ich habe ein Template inne dem ich folgendes abfrage 

if ($this->generateAttribute('type') == 'XYZ'

Nun viel aus das unter Windows sowohl im Chrome als auch im IE hier die Ausgabe als Zahl also die ID des Produkttyps erfolgt. Auf OSX unter Chrome ist die ebenso.

Allerdings wird unter OSX Safari den Produkttypname anstelle der ID ausgeben. Somit muss ich meine Abfrage umbauen in

if ($this->generateAttribute('type') == 'XYZ' || $this->generateAttribute('type') == NUMBER ): ?>

Ich weis nicht ob dies ein Handling Fehler von mir ist oder das vom Safari kommt.

**Comment by aschempp** [comment]
Inwiefern hat der PHP-Code im Template etwas mit dem verwendeten Browser zu tun?

**Comment by skalec** [comment]
Da es sich um eine PHP Script / Contao mit dem Modul Isotope handelt muss es doch vom PHP kommen oder liege ich da so falsch. Es kann doch nicht sein das bei dem einen System eine ID und bei einem anderen der Name ausgegeben wird. Die Daten kommen doch nur aus dem Skript bzw. der Datenbank.

**Comment by aschempp** [comment]
Richtig, deshalb kann es mit dem Browser eigentlich nichts zu tun haben. Deine Aussage war dass es sich in verschiedenen Browsern anders verhält?

**Comment by skalec** [comment]
Das ist richtig. Unter Windows mit dem Internet Explorer wird Der Name angezeigt. Unter Windows mit dem Chrome wird der Name angezeigt. Unter macOS mit dem Safari wird die ID angezeigt. Unter macOS mit dem Chrome wird der Name angezeigt.￼￼Ich bin mir nicht darüber bewusst in Safari etwas eingestellt zu haben dass er das übersetzt. Ich wüsste auch gar nicht wie das geht.￼

**Comment by aschempp** [comment]
das kann ich dir auch nicht sagen. Hast du mal den Quelltext geprüft, ob es dort auch Unterschiede gibt?

**Comment by skalec** [comment]
Habe gerade gesehen das es im generiertem Quelltext ebenfalls Unterschiede gibt.

im Safari wird 

`<div class="breakline_Zubehör"></div>`

im Chrome
`<div class="breakline_4"></div>`

ausgegeben.

Da dies alles durch Template generiert wird, kann doch der Fehler nicht bei mir liegen oder? Das wird doch warum auch immer anders interpretiert. Die Codes im Hintergrund sind doch die selben.

Der Type 4 heist Zubehör.

**Comment by aschempp** [comment]
Ich kann leider nicht beurteilen warum dein System sich da anders verhält, bisher ist das weder bei mir lokal und scheinbar bei jemand anderem aufgetreten. Ev. müsstest du einen Entwickler an dein System lassen, der das analysieren kann?

**Comment by skalec** [comment]
Wie würde ich so eine Remotesitzung herstellen. Also wie stelle ich den Kontakt her? Remote ist kein Problem.

**Comment by aschempp** [comment]
Mit eine(r/m) Entwickler:in deines Vertrauens oder mit uns via https://isotopeecommerce.org/de/circle.html (kostenpflichtig).
