### ISSUE TITLE
Checkout validation of shipping country

### ISSUE THREAD

**Issue by bennyborn** [isotope/core#2224]
We have a customer who exclusively ships to germany but billing can also be done in other countries. Setting up the shop config accordingly revealed a problem with the address validation.

![image](https://user-images.githubusercontent.com/226890/115712528-2c05a280-a375-11eb-9c45-874d3bd057f1.png)

If the customer chooses e.g. Austria as the billing country and sets "Shipping address" to `Use billing address` the shop seems to have no problem with the fact that Austria is a country that cannot be shipped to. 

Of course if the customer selects `Different shipping address` he would see that there is no option for Austria but it seems the checkout lacks a crucial validation in this case.

**Comment by aschempp** [comment]
hmm, the correct way would probably not to show these addresses as shipping options?

**Comment by bennyborn** [comment]
> hmm, the correct way would probably not to show these addresses as shipping options?

Not sure if I got what you mean. Of course the shipping methods are configured accordingly (in this case restricted to Germany). 

IMHO the user should not be able to proceed from the address step if he chooses a billing country that is not available for shipping (if the items in the cart require shipping at all).

Maybe the fix could look something like this:
Add a blank option as default for the shipping country. If the user chooses `Use billing address` run a validation that the selected billing country is also available in the shipping country field. If not (and shipping is needed) throw an error 🤷

**Comment by aschempp** [comment]
Reading this again, shouldn't you limit the shipping methods as well? The shop would then show "the products cannot be shipped to your country"?

**Comment by bennyborn** [comment]
> [...] The shop would then show "the products cannot be shipped to your country"?

Absolutely correct and we've already done that but that still leads to an unpleasant UX.

**Comment by aschempp** [comment]
imho that is not a bug, configuring the shipping options is the correct step.
