### ISSUE TITLE
Isotope für PHP 8 optimieren

### ISSUE THREAD

**Issue by minstyle** [isotope/core#2226]
Hier das gewünschte Ticket zur "Contao Show 10" (https://www.youtube.com/watch?v=9NajdKGLTXY).

Wäre schön, wenn Isotope bald auch für PHP 8 kompaibel gemacht wird.

**Comment by aschempp** [comment]
hast du das zufällig selber schon versucht? Wäre dir eine nötige Änderung gerade bewusst (abgesehen von der composer.json)?

**Comment by aschempp** [comment]
Isotope 2.8 wird für PHP8 freigegeben sein.

**Comment by contaoacademy** [comment]
Vielleicht könntet Ihr in der aktuellen Readme einen Hinweis einfügen, dass aktuell kein PHP 8 unterstützt wird und mit der Version 2.8 geplant ist.

**Comment by fritzmg** [comment]
The problem is that currently Composer will install version 2.3 of Isotope, if you use PHP 8, since versions 2.3 and lower allow that.
