### ISSUE TITLE
Extensions for MediaManager not using attribute setting

### ISSUE THREAD

**Issue by rhymeadam** [isotope/core#2227]
Hi all, it looks like the MediaManager widget isn't using the "extensions" that are set on the attribute record.  I believe the line below should be updated to use "$this->extensions" or even "$this->extensions ?: $GLOBALS['TL_CONFIG']['validImageTypes']", and then it should be resolved.  Let me know if this makese sense.  Thanks!

https://github.com/isotope/core/blob/6e9cdea53fa80309d42d2e067aadd9b71a999cd9/system/modules/isotope/library/Isotope/Widget/MediaManager.php#L315

**Comment by rhymeadam** [comment]
@aschempp any thoughts here?

**Comment by aschempp** [comment]
What images would you add support for? I think they are hardcoded because it's a special widget type that would not support everything, but I haven't yet investigated.

**Comment by rhymeadam** [comment]
For example, we have a client who wants to use it for PDFs, so I changed it to the code in my previous comment, and it works nicely.  I don't see what the "extensions" field on tl_iso_attribute is even doing for the MediaManager at this point, do you?

**Comment by aschempp** [comment]
uhm, the media manager is meant to manage images only, it generates a preview in the back end etc. Maybe you should use the download attribute for PDFs instead?

**Comment by rhymeadam** [comment]
sure, that's fine for that particular case, but what if we wanted to limit the MediaManager to just PNG images for some reason?  the "extensions" field should allow you to limit the MediaManager to just PNG images using the "extensions" field.  right now, i don't believe the "extensions" field is even doing anything at all on MediaManager widgets, and yet it's in the palette as if it should be.

**Comment by aschempp** [comment]
Changed in d65c07b194e2beff8281263f2109f7b8dd0ba805
