### ISSUE TITLE
Cart Items incorrect 

### ISSUE THREAD

**Issue by lumas-consulting** [isotope/core#2230]
We have problems with the cart items in an isotope multidomain installation.
in the 'de' environment everything looks good and the number of cart items is correct for each client.

In the 'nl' environment all clients seem to share the same cart. The site with the cart list is not cached at all.
The cookie ISOTOPE_TEMP_CART ist the same for all clients.

The configuration of the de and the nl root and the shop configuration are exactly the same.

**Comment by aschempp** [comment]
Is any other page of the NL tree cached? What Contao version are you on?

**Comment by aschempp** [comment]
closing this due to no feedback
