### ISSUE TITLE
Postsale kills custom hooks

### ISSUE THREAD

**Issue by bennyborn** [isotope/core#2233]
We've created an extension that makes use of the `sendNotificationMessage` hook from Notification Center. It's all working fine except on payment methods that require postsale (e.g. PayPal). 

After some debugging we've found the problem:

https://github.com/isotope/core/blob/857c15bda0376c5b03c2d87f7d82e7b81703ac6b/system/modules/isotope/postsale.php#L228-L241

This way you kill all hooks except the ones you deem to be "okay".

I'm not exactly sure why this method was created in the first place but it needs to be either removed or reworked into a blacklist. instead of a whitelist Otherwise this will kill all hooks that would otherwise work totally fine.

**Comment by aschempp** [comment]
see https://github.com/isotope/core/pull/2231
