### ISSUE TITLE
"Mehrere bearbeiten" funktioniert nicht beim Verschieben in Produktgruppen

### ISSUE THREAD

**Issue by k-webdesign** [isotope/core#2234]
Sobald ich mehrere Produkte bearbeite, erhalte ich unten den Button "Gruppe". Hake ich das Produkt an und will es in die Gruppe verschieben, filtert sich die Liste lediglich. Ich kann es nur manuell über das Icon verschieben.

Browser-Aufnahme: [https://drive.google.com/file/d/1mutjhMczo_5P9qDxbhgTAFV88cXUq8U2/view](url)

**Comment by aschempp** [comment]
Aufgetreten wegen 517c774, behoben in cc85bb3
