### ISSUE TITLE
Bestellungen: Mehrere Bearbeiten -> Bearbeiten / Überschreiben nicht mehr möglich unter 2.7 

### ISSUE THREAD

**Issue by Ainschy** [isotope/core#2235]
Leider steht mit 2.7 ein wichtiger Workflow Faktor nicht mehr zur Verfügung.

Den Bestellstatus in einem Rutsch bei mehreren Bestellungen über Mehrere Bearbeiten -> Überschreiben ändern. 

Bitte dringend wieder ermöglichen.

**Comment by Toflar** [comment]
Neuste 2.7?

**Comment by Ainschy** [comment]
2.7.3

Es werden keine Felder zur Auswahl angezeigt.

**Comment by aschempp** [comment]
Fixed in 68423d4f549a863741f6ec3fef1206d341f34f23
