### ISSUE TITLE
Übersetzung tl_iso_config.address_fields.1

### ISSUE THREAD

**Issue by Mynyx** [isotope/core#2239]
In der Übersetzung ``tl_iso_config.address_fields.1`` ist ``Bezahlen`` fälschlich klein geschrieben.

https://github.com/isotope/core/blob/f22f6e3a27db8d870e8daeb6923b8930a9acee03/system/modules/isotope/languages/de/tl_iso_config.xlf#L168-L171

**Comment by aschempp** [comment]
siehe #2259
