### ISSUE TITLE
iso_document_default.html5 - Translation fehlt bei per email verschickter PDF-Rechnung

### ISSUE THREAD

**Issue by berecont** [isotope/core#2242]
Wenn eine Rechnung "manuell" aus dem Backend als PDF erstellt wird, dann werden die beiden Infoblöcke 'Platziert' und 'Währung' mit angedruckt.  
Wenn die Bestellung im Frontend abgeschlossen wurde und via email die Rechnung versendet wird, fehlen diese beiden Infoblöcke in der generierten PDF.  
siehe auch [Forumeintrag](https://community.contao.org/de/showthread.php?81292-inspiredminds-contao-isotope-pdf-templates-fehlende-Infos)  

aufgefallen und getestet in einer Installation:  
Isotope 2.7.3  
Contao 4.9.16  
und getestet in einer lokalen Installation:  
Isotope 2.6.1 mit Demoshop installiert  
Contao 4.9.9

betrifft [iso_document_default.html5](https://github.com/isotope/core/blob/90050203cd38bd2f8aed9402ffb1f4846a39d494/system/modules/isotope/templates/document/iso_document_default.html5#L20)

**Comment by aschempp** [comment]
Fixed in 98c64c373a6a914f433967894b38fa43b9c8a64c
