### ISSUE TITLE
Produkte-Varianten im Sitemap bei deaktivierten Produkten

### ISSUE THREAD

**Issue by delirius** [isotope/core#2244]
Die **Produkte-Varianten** werden im **Sitemap** (sitemap.xml) aufgenommen auch wenn das **Produkt deaktiviert** ist. Das führt zu 404-Fehler da die Variante nicht abrufbar ist.

Contao 4.11.5
Isotope 2.7.3
(Lagerverwaltung ~1.4 von codefog)

**Comment by aschempp** [comment]
Die Produktvarianten sollten doch nicht im Sitemap sein? Wie sieht denn die URL einer Variante im Sitemap aus?

**Comment by aschempp** [comment]
should be fixed by 9e73daf2129431d3a3c1825d6aebe86f4305d218
