### ISSUE TITLE
EU-Umsatzsteuerreform ab 01.07.2021

### ISSUE THREAD

**Issue by dominikager** [isotope/core#2246]
Hallo,

seit 1.7.2021 gibt es eine Umsatzsteuerreform, wie kann das mit den Steuersätzen in Isotope abgebildet werden?

Danke

**Comment by aschempp** [comment]
Die Steuersätze lassen sich frei konfigurieren, damit sollte alles möglich sein. Was möchtest du konkret machen?

**Comment by dominikager** [comment]
Danke für die Antwort!
Ich möchte in AT 20% und in DE 19%
wahrscheinlich müssen alle Preise dafür netto hinterlegt sein oder?
Danke

**Comment by aschempp** [comment]
in AT 20% und in DE 19% ist nach meinem Wissen der Standardfall. Die Preise müssen dafür nicht netto sein, aber du musst die Steuern entsprechend konfigurieren. Falls der Endpreis des Produktes sich ändern soll, musst du natürlich entweder Nettopreise haben oder die Preise anpassen.
