### ISSUE TITLE
tax_free_price is not calculated correctly when using rule

### ISSUE THREAD

**Issue by xApep** [isotope/core#2247]
This were a "issue" in 2015, here:
https://github.com/isotope/core/issues/1345
https://github.com/isotope/core/commit/bba910405c47e1b607ac57d1c215259e02432806

But now after all this years I have noticed that the problem still persis. I have test this is 2.3.5, 2.4.0 and current latest isotope.

**Examples**

- I enter product price as a gross price. 
- I set rule "-5" to this product. 
- TAX classes config is like this (meaning; deduct tax from product price)

![image](https://user-images.githubusercontent.com/1315340/130096075-4f7349af-6aac-40de-bbcd-73dcb586d989.png)

The "tax_free_price" (database field or "$this->tax_free_subtotal" in the FE)  is calculated **wrongly**.
Without rule the tax_free_price is calculated correctly. 

And since without rule the tax free price is calculated correctly but with rule is wrongly I suppose there is a bug somewhere, but I didn't had any luck finding it.

**Comment by xApep** [comment]
@aschempp do you have any quick fix/idea for this issue?

**Comment by xApep** [comment]
I did some more digging and found out this.

Gross product price before discount: 23.00
Gross product price after discount: 19.00
Discount amount: -4
Tax rate: 5%

-- Screenshot of a dump
![image](https://user-images.githubusercontent.com/1315340/132299537-fd17d36b-f8b0-4698-9153-570dedcbe1d7.png)
--

I have debuged the system\modules\isotope\library\Isotope\Model\TaxRate.php, **calculateAmountIncludedInPrice** function.

Dumps (in if _$this->isPercentage()_)
```
dump($fltPrice);
dump($fltPrice - ($fltPrice / (1 + ($this->getAmount() / 100))));
```

The real issue as you can see: 19.00 - 0.9 is not 17.90 but 18.10.

**So how did he get the 17.90?**
Because he is **taking tax from the gross price before discount**, which is 1.095  (23 / 1.05 = 1.095). 
So 19.00 - 1.095 = 17.90

Now the funny thing is that as you can see on screenshot the Tax rate is correct but when he is calculating the tax_free_subtotal he is taking the wrong tax amount (calculateAmountIncludedInPrice). Also you can see the red highlighted dump that there is right calculation somewhere in function.

I hope that this explanation helps you somehow, I tried my best to explain it logicly :)

_p.s. Setting of the TAX class in Contao backend are set a on first screenshot of this issue, meaning you enter gross price as a product price._

**Comment by asaage** [comment]
I think i ran into a similar issue some time ago.
You should check if tax is applied to your discount or not.

**Comment by xApep** [comment]
> I think i ran into a similar issue some time ago.
> You should check if tax is applied to your discount or not.

@asaage can you explain little bit more? :)

**Comment by asaage** [comment]
In
Rules & Coupons › Edit rule IDx (where your -4 discount is defined)
Apply discount to: that is cart subtotal i guess
Tax Class: should be the same that is included in your product-price (not splitted or undefined)

**Comment by xApep** [comment]
@asaage by this:  _Tax Class: should be the same that is included in your product-price (not splitted or undefined)_
you mean as an option in Edit rule? Because there is no TAX class option in Rules & Coupons :)

**Comment by asaage** [comment]
> Because there is no TAX class option in Rules & Coupons :)

It exists only for Rules of Type: 'Cart' + Apply discount to: 'to the cart subtotal'.

**Comment by xApep** [comment]
> > Because there is no TAX class option in Rules & Coupons :)
> 
> It exists only for Rules of Type: 'Cart' + Apply discount to: 'to the cart subtotal'.

Ah, now I see it. But the tax_free_total or tax_free_subtotal is still incorrect and also this is not OK case because I need product discount not a cart total discount.

**Comment by asaage** [comment]
Then its probably bug like labeled by @aschempp and not a misconfiguration like i did in the past.
Sorry i can't dig more into this.

**Comment by xApep** [comment]
With upgrade to Isotope 2.4.0 and above and using tax_free_total and not subtotal the echo of tax is correct.

**Comment by asaage** [comment]
> I have test this is 2.3.5, 2.4.0 **and current latest isotope.**

> With upgrade to Isotope 2.4.0 and above and using tax_free_total and not subtotal the echo of tax is correct.

🙈

**Comment by xApep** [comment]
Haha, don't even mention it 🤒 
When I was testing in the first place I always had tax_free_subtotal in collection template.
