### ISSUE TITLE
Attribute Select // Custom Callback

### ISSUE THREAD

**Issue by bb-mt** [isotope/core#2248]
Hello,

for a installation which includes many small hotels i need to filter the Options of a attribute for the vairants of products. I found some old Postings here which recommends to add a custom callback. This works so far but there are two problems. 

Problem 1: The Options are not shown in the Frontend. (a empty Select Box appears) Without the Custom Callback everything works fine. I cant find a difference in the Database. 

Problem 2: 
when working in the Backend sometimes this error appears. The class Exists only once.  

Compile Error: Cannot declare class tl_bb_att1, because the name is already in use

The code for the Callback: 

 Eigenes Modul -> DCA -> tl_iso_product

```
$GLOBALS['TL_DCA']['tl_iso_product']['fields']['zimmerkategorie']['options_callback'] = array('tl_bb_att1','bb_select_season');



class tl_bb_att1 extends Backend
{
	
	
	public function __construct()
	{
		parent::__construct();
		$this->import('BackendUser', 'User');
	}	
		public function bb_select_season()
	{
	
	if($this->User->isAdmin){
			$season = Database::getInstance()->query("SELECT 
				*
				FROM 
				tl_bb_zi
				WHERE published=1");
				$season_arr = $season->fetchAllAssoc();
				//	$season_ausgabe[] = '';
foreach($season_arr as $season){
				$season_ausgabe[$season['id']] = $season['name'];
	}
	}else{
$season = Database::getInstance()->query("SELECT 
				*
				FROM 
				tl_bb_zi
				WHERE published=1 AND kunde ='".$this->User->kunde."'");
				$season_arr = $season->fetchAllAssoc();
				//	$season_ausgabe[] = '';
foreach($season_arr as $season){
				$season_ausgabe[$season['id']] = $season['name'];
	}
	}
	
	return $season_ausgabe;
	
	}

	
}
```

**Comment by aschempp** [comment]
First of all, you should never have a class in your DCA file. Secondly, your code does not handle front end (it checks the current back end user only). However, please refer to the Contao community support (https://to.contao.org/support) to get help with this, this issue tracker is meant to handle bug reports and feature requests not provide community support.
