### ISSUE TITLE
Invalid option value in the store configuration after update to Contao 4.9.20

### ISSUE THREAD

**Issue by netzarbeiter** [isotope/core#2249]
After updating to the newest Contao 4.9, do I have the following problem.

If I setup a new or want to change a Store configuration and the Price formatting is `10'000.00`, the Store configuration can't be saved. 

Go to:
Store configuration > General settings > Store configurations https://github.com/isotope/core/search?q=ISO_NUM

Error: 
Invalid option value!

![isotope](https://user-images.githubusercontent.com/1942550/131352702-b3497b70-fb64-41b7-8a40-b1bb92359cca.png)

Under contao 4.9.17 it still worked, i guess it has to do with the closed vulnerabilities in contao 4.9.18.

**Comment by aschempp** [comment]
@ausi any idea?

**Comment by fritzmg** [comment]
Probably because `'` gets encoded.

**Comment by aschempp** [comment]
Is that a bug or intentional? Do I need to enable `decodeEntities`?

**Comment by fritzmg** [comment]
> Do I need to enable decodeEntities?

I think so.

**Comment by ausi** [comment]
> Is that a bug or intentional?

Most probably a bug, option values are predefined and should therefore not get encoded IMO. Does’t the select widget automatically use decodeEntities?

**Comment by aschempp** [comment]
@ausi I only know I didn't change anything 😅

**Comment by ausi** [comment]
@aschempp should we create an issue in Contao too? I think it would be nice if this works for `select`s out of the box...

**Comment by aschempp** [comment]
Absolutely, if you think it can be fixed 😊

**Comment by ausi** [comment]
> should we create an issue in Contao too?

Done: https://github.com/contao/contao/issues/3421
