### ISSUE TITLE
Verwendung des Simple Tokens "payment_id" in einfacher if-Abfrage führt nach Contao-Update in Notifications zu einer Fehlermeldung

### ISSUE THREAD

**Issue by drum-und-dran** [isotope/core#2252]
Nach dem Update der Contao Version auf die Version 4.9.20 lässt sich eine bestehende Notification vom Typ "Isotope eCommerce: Benachrichtigung" > "Änderung Bestellstatus" nicht mehr abspeichern.

Unter dem HTML-Eingabefeld erscheint folgende Fehlermeldung:
`Die folgenden eingesetzten Tokens werden vom Notification-Typ nicht unterstützt: payment_id=="1"}.`

Der verwendete Code lautet wie folgt:
`{if payment_id=="1"}
Zahlungsmethode: Barzahlung
{endif}`

Die Notification lässt sich somit nicht mehr abspeichern, eine Änderung der Notification ist somit aktuell nur direkt über die Datenbank möglich.

**Comment by aschempp** [comment]
kannst du testen ob folgende Code-Änderung den Fehler behebt? https://github.com/terminal42/contao-notification_center/pull/240/files

**Comment by drum-und-dran** [comment]
> kannst du testen ob folgende Code-Änderung den Fehler behebt? https://github.com/terminal42/contao-notification_center/pull/240/files

Hallo Andreas,
ich habe die Änderungen vorgenommen, der Fehler tritt jetzt nicht mehr auf.

Dank und Grüße,
Gunnar

**Comment by aschempp** [comment]
danke für's testen. Ist somit kein Isotope-Fehler daher schliesse ich dieses Ticket.

**Comment by operatorone** [comment]
Hallo Andreas, wird der Fix dann in Notification Center übernommen?

**Comment by tblumrich** [comment]
Hallo!
Ich hab leider aktuell auch das o.g. Problem bei einer HTML Bestädigungsmail, kann aufgrund der Fehlermeldung nicht abspeichern:
`Die folgenden eingesetzten Tokens werden vom Notification-Typ nicht unterstützt: payment_id=="2"}.`

Meine Passage:
`{if payment_id=="2"}
Ihre Zahlungsart: ##payment_label##
Es ist nichts weiter zu tun. Wir versenden Ihre Ware so schnell wie möglich.
{else}
Ihre Zahlungsart: ##payment_label##
Zahlen Sie bitte die Gesamtsumme ##order_total## vereinbarungsgemäß auf folgendes Konto:
...
{endif}`

Im Nur-Text Bereich keine Probleme. Hatte auch gerade alles aktualisiert: Contao 4.9.26, Isotope 2.7.4.
Dort ist der o.g. Fix sicher schon drin, oder?

**//edit**
Okay, hab nachgesehen, offensichtlich noch nicht, nach den Änderungen im Code gehts nun.

**Comment by contaoacademy** [comment]
@aschempp Ich habe aktuell ebenfalls dieses Problem. Der Fix solle somit ins NC integriert werden: https://github.com/terminal42/contao-notification_center/pull/240/files
