### ISSUE TITLE
Produkte: Anpassung Datepicker

### ISSUE THREAD

**Issue by DJFlakeZ** [isotope/core#2253]
Hallo,
ich würde es begrüßen, wenn ich im Isotope bei der Veröffentlichung nicht nur ein Datum als Möglichkeit hätte - sondern wie bei Artikel in Contao auch Uhrzeiten nutzen kann um gezielt Elemente offline zu nehmen oder anzuzeigen. Ist da was geplant? :-)

![image](https://user-images.githubusercontent.com/91278813/134547232-ef13c61d-e091-45bb-88dc-e0c12f584785.png)

LG
FlakeZ

**Comment by aschempp** [comment]
geändert in 35378019f44d27d482c8e3ba153a56234609bc80
