### ISSUE TITLE
Bestellbedingungsformular speichert nicht.

### ISSUE THREAD

**Issue by jakober** [isotope/core#2254]
Guten Morgen,

finde leider keine Lösung und hoffe auf Hilfe.
Isotope Version 2.7.3
Contao Version 4.9.1

Ich möchte eine DSGVO Checkbox im Bestellformularschritt einbinden.
Habe das Formular erstellt.
Dann im Kassenmodul das bei "Bestellbedingungsformular" das Formular ausgewählt und den Checkout-Schritt angegeben.

Nach dem Speichern ist es aber leider direkt wieder weg -> Felder sind wieder leer. Ein Fehler erscheint nicht. Auch im Log nicht.

Kennt jemand das Problem?

**Comment by fritzmg** [comment]
Contao 4.9.1 ist nicht die neueste Contao Version. Bevor du dich um Probleme kümmerst, solltest du immer zuerst sicherstellen, dass du die aktuelle Version aller Pakete hast, um ausschließen zu können, dass ein etwaiger Fehler bereits in den neuesten Versionen der jeweiligen Pakete behoben ist.

**Comment by jakober** [comment]
> Contao 4.9.1 ist nicht die neueste Contao Version. Bevor du dich um Probleme kümmerst, solltest du immer zuerst sicherstellen, dass du die aktuelle Version aller Pakete hast, um ausschließen zu können, dass ein etwaiger Fehler bereits in den neuesten Versionen der jeweiligen Pakete behoben ist.

**Comment by jakober** [comment]
Danke fritzmg. Genau das war das Problem. Nach Update des Contao-Core auf 4.12 hats geklappt.
