### ISSUE TITLE
Restrict Frontend::injectScripts() to fe_page

### ISSUE THREAD

**Issue by koertho** [isotope/core#2255]
The implementation of Frontend::injectScripts() leads to issues in combination with Content Elements and Frontend Modules inheriting from the Fragment Controllers, as the `modifyFrontendPage` is also executed when calling `Template::getResponce`. So the messages are lost in nowhere.

A simple solution would be to restrict the execution to `fe_page`-Templates, that should be no problem thanks to the `$templateName`-Parameter (see https://docs.contao.org/dev/reference/hooks/modifyFrontendPage/).

See also https://github.com/contao/contao/issues/3263

**Comment by aschempp** [comment]
Fixed in 0b1d8acc85751867e275a679acc5b33aa6b04234
