### ISSUE TITLE
Duplicated products on Lister if they have variants

### ISSUE THREAD

**Issue by xApep** [isotope/core#2257]
Hey.

Contao 3.5.4
Isotope 2.6.15 and above.

I have product type with attribute; size and price for each variant. 
Price is defined on variant level.

So, product variants are:
- Variant 1: Size 10cm, price 10 EUR
- Variant 2: Size 20cm, price 20 EUR

Now on Listing you get 3 same product
- 1. is with price from 10 EUR (when you click it you get empty selection, because default variant is not defined)
- 2. is with 10 EUR price (when you click it you get selected option with Variant 1)
- 3. is with 20 EUR price (when you click it you get selected option with Variant 1)

Now the problem is that I don't won't to show the same products with all variants as a product in Listing, but only one product on Listing; as it was working in versions before 2.6.15 (idk which one was the latest that was working like that). 

It somehow does not have sense that is working like that. Imagine you have products with 10 variants each.

**Comment by aschempp** [comment]
this is most likely caused because you either choose the variant product list module, or because you set a custom SQL filter that destroys the grouping. Can you check that please?

**Comment by xApep** [comment]
I also thought that but the Listing module is correct one.

Here is the screen shot of it.
![image](https://user-images.githubusercontent.com/1315340/138073664-086486ab-7099-4242-a4ad-91c3dd5d5d22.png)

**Comment by aschempp** [comment]
please update to the latest version and see if this problem still exists. If it does, it might be caused by an extension you have installed.

**Comment by xApep** [comment]
@aschempp Thank you for your feedback. The issue was in un-seen old extension. We extended the regular product list, because by default isotope doesn't have option to display product discounted value in product list :/
