### ISSUE TITLE
Contao-Upgrade 4.12.2 -> 4.12.3 breaks Isotope 2.7.3

### ISSUE THREAD

**Issue by jochi44** [isotope/core#2258]
After upgrading Contao from V4.12.2 to V4.12.3, Isotope V2.7.3 does not work at all.

The logfile in `/var/logs` shows the following errors:

`[2021-10-21T13:00:22.661139+02:00] request.INFO: Matched route "tl_page.293". {"route":"tl_page.293","route_parameters":{"_token_check":true,"_controller":"Contao\\FrontendIndex::renderPage","_scope":"frontend","_locale":"de","_format":"html","_canonical_route":"tl_page.293","parameters":"","pageModel":{"Contao\\PageModel":[]},"_route":"tl_page.293","_route_object":{"Contao\\CoreBundle\\Routing\\Page\\PageRoute":[]}},"request_uri":"https://abc.tld/mitglieder-interner-bereich/kategorie1.html","method":"GET"} []`

`[2021-10-21T13:00:22.814963+02:00] request.CRITICAL: Uncaught PHP Exception TypeError: "Return value of Contao\CoreBundle\Util\LocaleUtil::formatAsLocale() must be of the type string, null returned" at /var/www/clients/client1/web5/web/schivereinanras/vendor/contao/core-bundle/src/Util/LocaleUtil.php line 112 {"exception":"[object] (TypeError(code: 0): Return value of Contao\\CoreBundle\\Util\\LocaleUtil::formatAsLocale() must be of the type string, null returned at /var/www/clients/client/web/web/abc/vendor/contao/core-bundle/src/Util/LocaleUtil.php:112)"} []`

**Comment by aschempp** [comment]
this looks like an error in Contao core. Do you have a stack trace from the front end?

**Comment by aschempp** [comment]
see https://github.com/contao/contao/issues/3593
