### ISSUE TITLE
Neu angelegtes Feld wird nicht an NotificationCenter übergeben

### ISSUE THREAD

**Issue by contaoacademy** [isotope/core#2262]
Ich habe ein neues Feld für «tl_iso_product_collection» angelegt.
`$GLOBALS['TL_DCA']['tl_iso_product_collection']['fields']['custom_field']`

Wenn ich nun bei der Bestellung auf «Speichern» klicke und gleichzeitig den «Status» ändere, wird der Wert für das Feld nicht an die Benachrichtigung an den SimpleToken übergeben.
Wenn ich allerdings erst «speichern» klicke und dann den Status der Bestellung ändere und noch mal «speichern» klicke, dann kommen die Daten auch bei der Mail an.

Siehe auch #2219

**Comment by aschempp** [comment]
should be fixed by 2666d48a4f48728de2a160ed804653403b0500ba
