### ISSUE TITLE
Flash messages do not get reset in checkout

### ISSUE THREAD

**Issue by qzminski** [isotope/core#2269]
In my Isotope stock management extension there is an option to display a warning message if the product out of stock is added to the cart. The message is added via `addProductToCollection` hook and thus is executed when going from the cart to the checkout.

The problem is, that the messages are not reset if there is `$_POST` data: https://github.com/isotope/core/blob/f22f6e3a27db8d870e8daeb6923b8930a9acee03/system/modules/isotope/library/Isotope/Message.php#L146

… and in the checkout there always seems to be some `$_POST` data, for example: https://github.com/isotope/core/blob/f22f6e3a27db8d870e8daeb6923b8930a9acee03/system/modules/isotope/library/Isotope/CheckoutStep/Address.php#L113

This makes the `$_SESSION['ISO_INFO']` messages never reset and appear on every checkout step. For now, I have bypassed the problem by creating a custom `iso_scripts.html5` template and calling `\Isotope\Message::reset()` there.

I am not entirely sure if it's an issue in my extension or Isotope, and how to actually fix it. @aschempp what do you think?

**Comment by aschempp** [comment]
good catch! I've seen this but was never able to reproduce or analyze it. Should be fixed by e01a6f52612f400991eaa5310304c280e73e6057
