### ISSUE TITLE
Coupon leads to wrong price for payment step

### ISSUE THREAD

**Issue by bennyborn** [isotope/core#2271]
The following incident just happened:

- Customer adds two products to the cart (e.g. both for 5€)
- In the cart, the customer adds a coupon code worth 10€
- Subtotal therefore now equals 0€
- After choosing a proper shipping method the grandtotal is now 5€ (+5€ for shipping)
- He's now in the review and can complete the order without choosing a payment method to pay for the shipping cost
- Order gets confirmed event though there are still 5€ left to be paid with an now unknown payment method

This is the result of two problems:

1. The checkout asks for shipping before payment (that should be switched around)
2. The following block prevents the inclusion of surcharges while the Collection is still a Cart and not an Order (Cart is converted to Order at review step) https://github.com/isotope/core/blob/0b1d8acc85751867e275a679acc5b33aa6b04234/system/modules/isotope/library/Isotope/Frontend.php#L70-L74 This then leads to `Isotope\CheckoutStep\PaymentMethod::isAvailable()` reporting `false` because the subtotal does not include any shipping or other surcharges that may justify a payment

As a temporary fix we'd change the order of the `$GLOBALS['ISO_CHECKOUTSTEP']` so shipping comes before payment and comment out the 3 lines in `Frontend.php`.

Of course this now leads to all surcharges being also displayed in the cart (when going back) but it least it seems to work correctly.

Any idea what the best solution would be and if our proposed change might do more harm than good?

**Comment by aschempp** [comment]
Shipping always is before payment, and always has been. Otherwise it would not be possible to allow "cash payment" if shippping is "pickup" etc.
https://github.com/isotope/core/blob/2.7/system/modules/isotope/config/config.php#L390-L391

Did you mix something up or maybe there's something on your system changing that?

**Comment by bennyborn** [comment]
You're right, I got that mixed up. I actually meant _"asks for **shipping** before **payment**"_

> Shipping always is before payment, and always has been. Otherwise it would not be possible to allow "cash payment" if shippping is "pickup" etc.

Interesting case, never actually had that exact requirement and wasn't aware you could limit payment methods based on shipping methods. But this makes it even more complex 😕

Any thoughts on how to solve the original problem then?

**Comment by aschempp** [comment]
I think I have found and solved the problem in 4392f21b04fc0210e9057e90124078d5535b8cbc
(thanks to an [Isotope Circle](https://circle.isotopeecommerce.org) member 😊)
