### ISSUE TITLE
Übersetzung nach Deutsch fehlt

### ISSUE THREAD

**Issue by berecont** [isotope/core#2275]
Contao 4.13.0
Isotope 2.8.x-dev
Übersetzung fehlt unter Shop-Konfiguration » Konfiguration » Preise
![isotope-28xdev](https://user-images.githubusercontent.com/33038265/157434167-4d08c604-6b47-4378-9d5e-a982509a90f5.png)

**Comment by fritzmg** [comment]
@berecont translations are managed on Transifex and will likely only be updated before a release. You would need to manually check whether the translation is not yet already present on Transifex.

**Comment by aschempp** [comment]
updated in 116a0dbb4b9141894a1a80f70b930d5c6d793cd2
