### ISSUE TITLE
List all Attributes in Reader?

### ISSUE THREAD

**Issue by spirescreative** [isotope/core#2280]
I am at a loss as to how to list all attributes in the reader, without manually calling each one by name with $this->generateAttribute. Seems I wouldn't need to modify the template every time a new attribute is added to the attributes list...? What am I missing? Thank you in advance.

**Comment by spirescreative** [comment]
So, I'm not sure if this the appropriate way to do this with Isotope and Contao, as I had to create a new mysqli connection, but here is a solution to list a product's associated attributes, if they are not null, by querying the attribute table and referencing each one with the product being listed in the reader:
```
$query = "SELECT * FROM tl_iso_attribute";
$result = $conn->query($query);

if ($result->num_rows > 0) {
  while($row = $result->fetch_assoc()) {
    if($this->generateAttribute($row['field_name'])){ 
    	echo "$row[name]: ". $this->generateAttribute($row['field_name']) . "<br>" . PHP_EOL; 
    }
  	
  }
}
```

**Comment by aschempp** [comment]
I don't think this is a supported use case. Isotope product templates are _meant_ to be customized to reflect your product. Since we do not (and will not) have something like content elements, this seems the only way to generate a useful view in the front end?

**Comment by spirescreative** [comment]
I am making the assumption that Attributes is the appropriate place to include a product's custom specs, beyond SKU, price and other built-in attributes. As an example, if a store sold TVs, the attributes might be Display Type, Resolution, Refresh Rate, etc. My understanding is that custom fields are configured in Attributes and then associated with the Product Type so that the spec could be included when adding a product under Product Management. If this is incorrect, please let me know. 

As far as I know, there is no command to list all custom attributes in the Reader and no configuration in Product Management to show certain or all custom attributes in the Reader; hard coding each custom attribute in the template is not Back-end Contributor friendly nor is it dynamic. Perhaps there is a more appropriate way to inject this into the object class? Does Contao have database management class that I can use instead of making my own connection to MySQL?

**Comment by tsarma** [comment]
@spirescreative Have you tried with function `ProductType::getAttributes()` to get all set attributes?

**Comment by spirescreative** [comment]
> @spirescreative Have you tried with function `ProductType::getAttributes()` to get all set attributes?

I'm curious how this is used properly... calling it directly throws errors as does $this->getAttributes() (with or without 'echo'.) Any insight on the use of this function would be appreciated.

**Comment by tsarma** [comment]
@spirescreative In the product reader template `$this->product->getType()->getAttributes()` should get you the list of attributes.

**Comment by aschempp** [comment]
> I am making the assumption that Attributes is the appropriate place to include a product's custom specs, beyond SKU, price and other built-in attributes. As an example, if a store sold TVs, the attributes might be Display Type, Resolution, Refresh Rate, etc.

"Unfortunately", Isotope is very flexible. You _can_ use this for product spect, but you also use it to have your users enter structured data. If you look at https://www.procava.ch/shop/pinna-fidelis-crianza-75.html, the wine details are attribute. But there are also three attributes for the description sections at the bottom, because a wine must always have a "Produktionsmethode", "Ausbau" and "Degustationsnotiz". So it ultimatively boils down to your custom setup and templates 😊
