### ISSUE TITLE
Nettopreis wird falsch berechnet

### ISSUE THREAD

**Issue by henobi** [isotope/core#2281]
Hallo liebes Isotope-Team.

Mir ist folgender Bug in Isotope bei der Berechnung des Nettopreises aufgefallen:

![Bildschirmfoto 2022-03-25 um 12 42 56](https://user-images.githubusercontent.com/26099839/160116762-f86c7afa-2692-4dde-ae1f-009669b3bea0.png)

Wenn ich den Nettopreis manuell nachrechne erhalte ich:
`2000,16 / 1,07 = 1869,31`

Auf dem Rechnungstemplate von Isotope steht aber `1870,33`.

Wie kann das sein?

Vielen Dank im Voraus.

Im Template wurden die Angaben über die Standardvariablen von Isotope eingebunden:
```php
 $this->subtotal
 $this->tax_free_total
 $this->total

```

**Comment by henobi** [comment]
Nach meiner Stichprobe habe ich das Problem nur bei Bestellungen mit kostenlosem Versand feststellen können.
Bei Bestellungen mit Versandkosten hat die Berechnung in meiner Stichprobe gestimmt.

**Comment by contaoacademy** [comment]
- Wie sieht die Konfiguration der Steuerklasse aus?
Speziell die Einstellungen für (Steuersatz im Produktpreis enthalten, Steuersätze hinzufügen)

- Welche Steuerklasse wurde bei der Versandart konfiguriert?

**Comment by aschempp** [comment]
closing this since https://github.com/isotope/core/pull/2531 might fix it
