### ISSUE TITLE
[2.7.4] Bug: Isotope/Backend/Product/Fallback/reset() must be static (Contao 4.9.27)

### ISSUE THREAD

**Issue by arboc** [isotope/core#2282]
The class Isotope/Backend/Product/Fallback extends Backend (Controller).  
The parent method reset is static but not the method in Fallback.  

This results in an error, when I update a variant of a product:

`[2022-03-30 13:11:39] request.CRITICAL: Uncaught PHP Exception Symfony\Component\ErrorHandler\Error\FatalError: "Compile Error: Cannot make static method Contao\Controller::reset() non static in class Isotope\Backend\Product\Fallback" at vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/Backend/Product/Fallback.php line 26 {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Compile Error: Cannot make static method Contao\\Controller::reset() non static in class Isotope\\Backend\\Product\\Fallback at vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/Backend/Product/Fallback.php:26)"} []`

An update isn't possible anymore.

**Comment by aschempp** [comment]
This has been fixed directly in Contao, please update to the latest version.
https://github.com/contao/contao/pull/4294
