### ISSUE TITLE
The selection of product groups does not work anymore

### ISSUE THREAD

**Issue by netzarbeiter** [isotope/core#2284]
- Contao 4.9.28
- Isotope 2.8.x-dev (29144766d15669458ff5c004789a05b8e357a78e)

Got to «Product management» and click «Groups».

Instead of the possibility to select a group, a page is displayed (not the 404 in every installation).

![product-groups](https://user-images.githubusercontent.com/1942550/161755281-a620155f-8e25-4562-8bbe-637fdae11b67.png)

Unsupported picker context

In Contao 4.9.27 it works as expected.

Isotope 2.7.4 is not affected.

**Comment by aschempp** [comment]
This is a bug in Contao that should be fixed by https://github.com/contao/contao/pull/4481

**Comment by bytehead** [comment]
Is this the same error? 

<img width="908" alt="Bildschirmfoto 2022-04-26 um 11 11 45" src="https://user-images.githubusercontent.com/754921/165266011-99fcafd4-79fc-4623-8c82-65f8425fdced.png">

Edit: is not. See #2289
