### ISSUE TITLE
Need "group_legend" for tl_iso_rule

### ISSUE THREAD

**Issue by rhymeadam** [isotope/core#2286]
Just wanted to let you know! Pretty minor, I know 😁

**Comment by aschempp** [comment]
not sure what you mean?

**Comment by rhymeadam** [comment]
In Rules & Coupons, if you select the Type "Cart Group", the "group_legend" language entry is missing
<img width="954" alt="Screen Shot 2022-04-20 at 3 45 58 PM" src="https://user-images.githubusercontent.com/36767740/164311046-42b183d5-0010-47fa-8db4-e1dd04637fc7.png">
.

**Comment by aschempp** [comment]
fixed in 39f8a0665b903224de340c6c7c0b229845d9bc5b
