### ISSUE TITLE
Need to use language entry for Per Product report

### ISSUE THREAD

**Issue by rhymeadam** [isotope/core#2287]
I'm seeing "Produkt" is hard-coded here where it should be a language entry: https://github.com/isotope/core/blob/eaf45d96c3ff9768ced99c1dc9ca6e6662d84713/system/modules/isotope_reports/library/Isotope/Report/SalesProduct.php#L261

**Comment by rhymeadam** [comment]
Same with "Total": https://github.com/isotope/core/blob/eaf45d96c3ff9768ced99c1dc9ca6e6662d84713/system/modules/isotope_reports/library/Isotope/Report/SalesProduct.php#L272

**Comment by aschempp** [comment]
Yeah that looks like a bug to me. Could you do a pull request to fix it? 🙃

**Comment by aschempp** [comment]
fixed in 2a0dcc279a14bded7f629bc835c46364ecf86635
