### ISSUE TITLE
"Edit Multiple" on variant populates the fields gtin and sku

### ISSUE THREAD

**Issue by michb** [isotope/core#2288]
If you `edit multiple` **variants** and copy them Isotope will fill the fields `gtin` and `sku` with some random values.
Don't know why or where this comes from. These fields are not configured in the product nor in the variants.
But if you again copy these entries with the `edit multiple` actions this will lead to an error:
`An exception occurred while executing a query: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'gtin' at row 1`
Copying one entry, with the `+` icon, works without problems and won't fill the fields.

In Contao **4.13.2** and Isotope **2.8.x-dev**

**Comment by michb** [comment]
Issue still persists in Isotope **2.8.0**

**Comment by aschempp** [comment]
Fixed in 788e77f
