### ISSUE TITLE
RuntimeException: Move product to a product group

### ISSUE THREAD

**Issue by bytehead** [isotope/core#2289]
`isotope/isotope-core: dev-2.8`
`contao/core-bundle: 4.13.2`

<img width="908" alt="Bildschirmfoto 2022-04-26 um 11 11 45" src="https://user-images.githubusercontent.com/754921/165266403-149b4511-e7d3-4014-907e-3e8ed0c8d2d7.png">

**Comment by aschempp** [comment]
that does not look like an isotope issue?

**Comment by bytehead** [comment]
This happens when I click on this:

<img width="396" alt="Bildschirmfoto 2022-04-26 um 17 42 08" src="https://user-images.githubusercontent.com/754921/165339435-363f2cfb-6742-46c9-ab92-50a9a3319f96.png">

**Comment by aschempp** [comment]
I just debugged this, and it is fixed by https://github.com/contao/contao/pull/4481 as well. So I guess it is a duplicate 😉

**Comment by bytehead** [comment]
Nice, thanks a lot! 😘
