### ISSUE TITLE
Use of rules throws error in cart.

### ISSUE THREAD

**Issue by asconsulting** [isotope/core#2290]
I have a rule in place to allow adding a quantity of only one for each product. There error is triggered when viewing the cart. With this rule enabled I get the following error. If the rule is not enabled it works as expected. 

Unsupported operand types: string * int at _<install_path>_/vendor/isotope/isotope-core/system/modules/isotope_rules/library/Isotope/Model/ProductCollectionSurcharge/Rule.php:195)"} []

**Comment by aschempp** [comment]
should be fixed by 0cdfe3cd
