### ISSUE TITLE
Linked categories - products cannot be selected

### ISSUE THREAD

**Issue by siegelsupport** [isotope/core#2292]
I have an Isotope 2.8 with the new selection features for the linked catgeories. But unfortunately I can't change or add any products.
The button is always disabled...

<img width="1179" alt="Bildschirmfoto 2022-05-09 um 19 31 16" src="https://user-images.githubusercontent.com/2368325/167465129-7e608d0b-136a-49df-b547-d89639ef00dd.png">
<img width="1167" alt="Bildschirmfoto 2022-05-09 um 19 30 51" src="https://user-images.githubusercontent.com/2368325/167465141-fac909f7-4c76-4df4-a8dd-6a76dc04f0d4.png">
.

**Comment by chibko** [comment]
I have the same issue… Contao 4.13.4, Isotope 2.8

**Comment by aschempp** [comment]
unfortunately, this is a bug in the latest Contao version, see https://github.com/contao/contao/pull/4711 for the bugfix.

**Comment by aschempp** [comment]
The bug has been fixed in the latest Contao version.
