### ISSUE TITLE
Add support for public folder Contao 4.13

### ISSUE THREAD

**Issue by contaoacademy** [isotope/core#2293]
Please add support for `public` folder. Currently, the `web` folder is hard-coded:
https://github.com/isotope/core/blob/631b7da08abce98ab3f54ece141acab034855f2f/system/modules/isotope/library/Isotope/EventListener/SymlinkCommandListener.php#L49

**Comment by aschempp** [comment]
should be fixed in 268dd47640cc3bbd84043e7686abf354eaf258a8
