### ISSUE TITLE
Reorder sold out products

### ISSUE THREAD

**Issue by mirkanglanz** [isotope/core#2296]
PHP 7.4.29, Contao 4.9.27, Isotope eCommerce 2.8.0

It should not be possible to reorder sold out or unpublished products. 
Is it possible to implement hiding the reorder button if one of the products is not available?

**Comment by aschempp** [comment]
Isotope eCommerce does not offer stock management out of the box. But there are solutions available on our Marketplace: https://www.isotopeecommerce.org/en/marketplace.html

**Comment by mirkanglanz** [comment]
@aschempp 
Thank you for your quick answer. 
I consider it a bug that it's possible to reorder products which are not on the website as they have the attribute "published" on 0.
