### ISSUE TITLE
2.8.2 / Contao 4.9.30 - ajax request failed

### ISSUE THREAD

**Issue by Ainschy** [isotope/core#2303]
Auf der Artikeldetailseite wird eine Produkt-Größe per Select geändert der Ajax Request ruft aber nicht die Detailseite auf sondern die Root Seite. 

Habe die Installation wieder auf 2.7.4 gesetzt und das Problem trat nicht mehr auf. 

Werder im Debug Modus noch in den Logs waren Auffälligkeiten.

**Comment by rhymeadam** [comment]
I just had this happen too. I removed the "action" property on the form in my custom iso_reader template and it resolved the issue.

**Comment by Ainschy** [comment]
Interesting, I will check it out.

**Comment by Ainschy** [comment]
I have change the custom iso_reader template to the original. 

First xhr goes now to domain.tld/null and a second request can't finished -> `Uncaught DOMException: Failed to execute 'send' on 'XMLHttpRequest': The object's state must be OPENED.`

**Comment by netzarbeiter** [comment]
The [unnecessary action from forms has been removed](https://github.com/isotope/core/commit/5b9cbe05ed25969f45df5fefd52c1f61f66e9045) in the following templates:

- iso_filter_default.html5
- iso_list_default.html5
- iso_list_variants.html5
- iso_reader_default.html5

Please remove `action="<?= $this->action ?>"`  in the template.

**Comment by aschempp** [comment]
Fixed in 25cd6816ef26bc18267ad1d0f24ddaef2200a094
