### ISSUE TITLE
Saferpay payment currently completely broken

### ISSUE THREAD

**Issue by plandolt** [isotope/core#2306]
We just set up a new isotope ecommerce project with 2.8.3 and integrated Saferpay. 

The actual behavior is that after initializing payment, redirecting to the saferpay payment page and doing an actual payment there, one is redirected back to the `/complete.html` page. There, the content gets reloaded a couple of times until the payment is deemed failed.

After a deep dive into [`Saferpay.php`](https://github.com/isotope/core/blob/2.8/system/modules/isotope/library/Isotope/Model/Payment/Saferpay.php) we discovered that the method [`processPostsale` ](https://github.com/isotope/core/blob/2.8/system/modules/isotope/library/Isotope/Model/Payment/Saferpay.php#L45) never gets triggered.

I've created a [PR](https://github.com/isotope/core/pull/2305) that fixes that with some inspiration from [`PSP.php`](https://github.com/isotope/core/blob/2.8/system/modules/isotope/library/Isotope/Model/Payment/PSP.php#L45).

**Comment by aschempp** [comment]
Postsale is supposed to be triggered by the server-to-server call, not by the web request. I think that would be the configuration mentioned in https://docs.isotopeecommerce.org/manual/de/backend-configuration/store-configuration/checkout-flow/payment-methods/payment-method-saferpay/#datenübergabe but the docs says its not strictly necessary 🤔

**Comment by plandolt** [comment]
Hi @aschempp 

Yes I imagined that, but in 2.8 the [postsale.php](https://github.com/isotope/core/blob/2.7/system/modules/isotope/postsale.php) (link from the 2.7 branch) is missing. But the [Saferpay.php](https://github.com/isotope/core/blob/2.8/system/modules/isotope/library/Isotope/Model/Payment/Saferpay.php#L209) class is still using this path.

What will be the correct way to fix this?

**Comment by aschempp** [comment]
the file is gone, but the routes still work: https://github.com/isotope/core/blob/2.8/system/modules/isotope/library/Isotope/Controller/PostsaleController.php#L16-L17

**Comment by plandolt** [comment]
Ah, now it's starting to become clear for me. But we might still have an issue (not tested yet). The Saferpay JSON API now has two URLs for Success and Failure for server to server Notification.

<img width="1179" alt="image" src="https://user-images.githubusercontent.com/922919/174031416-3ba01e3e-9634-43c1-a5d6-06453e0bde0d.png">

Should https://github.com/isotope/core/blob/2.8/system/modules/isotope/library/Isotope/Model/Payment/Saferpay.php#L249 be twice with keys `SuccessNotifyUrl` and `FailNotifyUrl`?

**Comment by aschempp** [comment]
Ah, I didn't see this is automatically included in the API request. Then it should not be necessary to configure. 

However, now this does not explain why it did not work for you in the first place. Can you check if the route can be called or anything is logged?

Also be aware this will not work if you for example added htaccess-protection to the server.

**Comment by aschempp** [comment]
fixed in https://github.com/isotope/core/pull/2305 then
