### ISSUE TITLE
saferpay postsale bug - wrong postsale url

### ISSUE THREAD

**Issue by gebi84** [isotope/core#2307]
Hi,

there is a bug in the code file **system/modules/isotope/library/Isotope/Model/Payment/Saferpay.php**
`NotifyUrl `is sent with two // 

Code should be
`'NotifyUrl' => Environment::get('base') . 'system/modules/isotope/postsale.php?mod=pay&id=' . $this->id.'&orderid='.$objOrder->getId()`
without / before system

https://github.com/isotope/core/blob/d67197e0642e6666c64e90045567401c9e955fc7/system/modules/isotope/library/Isotope/Model/Payment/Saferpay.php#L249

**Comment by plandolt** [comment]
Hi @gebi84 

The whole file is gone since 2.8.0 therefore we created a [PR](https://github.com/isotope/core/pull/2305) to make the saferpay assert and capture the payment in the success url redirect back to the shop. This might help you.

**Comment by aschempp** [comment]
see https://github.com/isotope/core/pull/2305
