### ISSUE TITLE
double rel=canonical tags

### ISSUE THREAD

**Issue by asaage** [isotope/core#2310]
I decided to enable the contao cannonical-url feature (since [4.13](https://docs.contao.org/manual/de/layout/seitenstruktur/seiten-konfigurieren/#kanonische-url)) because i have a lot of paginated content.
Now a ```link rel="canonical"``` appears twice on pages with the reader module.
(Not always - i guess only for products with multiple categories)

Since it is a rootpage-setting i can't disable it for the readerpage.
Would it be possible to override or set the contao value instead of just adding the tag to the head in case the feature is enabled?
I guess somewhere around here: https://github.com/isotope/core/blob/2.8/system/modules/isotope/library/Isotope/Module/ProductReader.php#L174

**Comment by aschempp** [comment]
fixed in bcfb5c5a8c484fb3f59a3836078032e6bc618f3b
