### ISSUE TITLE
Is supporting the new PayPal Checkout planned?

### ISSUE THREAD

**Issue by ben-eSM** [isotope/core#2311]
PayPal recently launched their new PayPal Checkout and actively pushing their clients to move to this new tech. It seems that PayPal Plus has been replaced by the new Checkout as you are no longer able to request a PayPal Plus activation for your account.

Are there plans to provide a PayPal Checkout payment module in the near future?

**Comment by contaoacademy** [comment]
Yesterday @Ainschy has mentioned over the Slack-Channel that @richardhj is checking the effort. I think we should do a fundraising to get this done quickly.

**Comment by Ainschy** [comment]
The sandbox tests look good, but in live operation we get an authentication error. Now we take a closer look at what is going wrong.

**Comment by DenisKusche** [comment]
Is the new Paypal Checkout already supported in 2.8.5?

**Comment by contaoacademy** [comment]
No.
You could follow the progress in this branch.
https://github.com/isotope/core/tree/feature/paypal-checkout

**Comment by DenisKusche** [comment]
Are there any thoughts already with which version this functionality will be released? And is there any way to support the development on this?

**Comment by aschempp** [comment]
It can likely be released in the next minor version. Support is always appreciated at https://github.com/sponsors/terminal42 or https://ko-fi.com/terminal42 🙃

**Comment by omuellersch** [comment]
Any idea, when PayPal Checkout will be supported? It seems that it is not possible to set up PayPal Plus Connection for a new shop. Only PayPal Standard vie email is working.

**Comment by Ainschy** [comment]
You can use [https://github.com/isotope/core/tree/feature/paypal-checkout](url)

**Comment by omuellersch** [comment]
OK, thanks.
Just replace files in "root/vendor/isotope/isotope-core" with this bundle?

**Comment by Ainschy** [comment]
in your root composer.json you can set the isotope/core package to `"isotope/isotope-core": "dev-feature/paypal-checkout as 2.9",`

**Comment by MDevster** [comment]
@aschempp is planned to release the branch dev-feature/paypal-checkout or can still be supported here so that it is not too far "away" from 2.8?

**Comment by aschempp** [comment]
I always rebase it after a release (until we have 2.9) 😉

**Comment by contaoacademy** [comment]
Would it be possible to release the paypal-checkout as a separate small bundle for isotope. Then it would be detached from the release process and could be changed independently of the core in case of further adjustments.

**Comment by MDevster** [comment]
@aschempp thank you!

**Comment by aschempp** [comment]
> Would it be possible to release the paypal-checkout as a separate small bundle for isotope. Then it would be detached from the release process and could be changed independently of the core in case of further adjustments. 

That's not how these payment methods currently work, but we're considering this for a v3.

**Comment by netgroupgmbh** [comment]
Hi, we have the same issue as [omuellersch](https://github.com/isotope/core/issues/2311#issuecomment-1326245676). 
I don't want to be too pushy, but is there a planned timeframe for the implementation? So we can give some answer to our customer. ;o)

**Comment by DenisKusche** [comment]
Is there already a plan when this feature will be released? It´s been quiet for a while around this feature.

**Comment by contaoacademy** [comment]
@DenisKusche 
As long as the new version has not been released, you can install the feature branch.

To do this, adjust the version of isotope in your composer.json.
`"isotope/isotope-core": "dev-feature/paypal-checkout as 2.9"`
