### ISSUE TITLE
Bei Gastbestellung wird per Default "Abweichende Versand-Adresse" ausgewählt

### ISSUE THREAD

**Issue by contaoacademy** [isotope/core#2316]
- Contao: 4.13.5
- Isotope: 2.8.4

Bisher war beim Checkout (Kasse) bei Gastbestellung als Standardwert «Rechnungs-Adresse verwenden» ausgewählt.
Was auch so gewünscht ist.

Aktuell ist allerdings «Abweichende Versand-Adresse» als Standard gesetzt und kann nicht geändert werden.
Beim Debuggen ist mir Folgendes aufgefallen.
(siehe Screenshot)

Warum hier einmal bei `default = 1 `und einmal `default = true `zurückgegeben wird, konnte ich nicht herausfinden.

![screen-20220704_LgJS9AMt](https://user-images.githubusercontent.com/23719181/177178783-9f0ceb50-9d7e-4573-9bae-7e6cc97d30ce.jpg)

![screen-20220704_81ovRw5V](https://user-images.githubusercontent.com/23719181/177179166-7812deb9-aef0-484f-989f-baf0fed11d9f.jpg)

**Comment by netzarbeiter** [comment]
Fehler tritt nur mit Contao 4.13 auf.

**Comment by drum-und-dran** [comment]
Same here. Contao 4.13 LTS

![Firefox_Screenshot_2022-12-20T13-37-02 784Z](https://user-images.githubusercontent.com/5277998/208680063-12abc177-0917-4118-9ada-746c9ca66e87.png)

**Comment by drum-und-dran** [comment]
Wie wird denn dieser Bug offiziell als Bug deklariert? 

Kann das bitte ein Entwickler mit der entsprechenden Berechtigung übernehmen? 
Eventuell beschleunigt dies die Fehlerbehebung etwas. 

Mittlerweile ist das Issue ja seit Anfang Juli offen, jetzt haben wir Ende Dezember.

Besten Dank!

**Comment by netzarbeiter** [comment]
Wenn dir die Fehlerbehebung hier zu langsam ist, hast du folgende Möglichkeiten:

- Du nimmst Kontakt mit einem Entwickler bzw. einer Entwicklerin auf und bezahlst sie für den Bugfix
- Du korrigierst den Fehler selber und lässt uns per PR daran teilhaben
- Du wirst Mitglied im [Circle](https://www.isotopeecommerce.org/de/circle.html) und erhältst Support zum Vorzugspreis

**Comment by aschempp** [comment]
Der Fehler hat tatsächlich nichts mit Contao 4.9/4.13 zu tun sondern mit der Datenbank bzw. Doctrine-Version. Behoben in 1c9d337b76ad086c7a693c9e04432e7fbadd7e17

**Comment by contaoacademy** [comment]
Danke

**Comment by AlexanderWillner** [comment]
Ich glaube, dass es hier u.U. einen Folgefehler gibt: aktuell wird in der DB keine Versandadresse gespeichert (`shipping_address_id = 0`), wenn die Standardoption `Rechnungs-Adresse verwenden` ausgewählt wird. Kann das sein?

**Comment by aschempp** [comment]
alles kann sein 😆 gerne analysieren, einen Bugfix-PR machen oder wenigesten ein GitHub Issue, weil dass hier ist geschlossen und da geht es verloren.
