### ISSUE TITLE
Inline Gallery: Add support for responsive images

### ISSUE THREAD

**Issue by contaoacademy** [isotope/core#2318]
I can specify an image format in the gallery configuration. However, this isn't used for the output in the template.

For example, if I specify a pixel ratio of `1x, 1.5x, 2x`, the image would not be generated with `srcset` attribute. There is only a simple image with `src` attribute.

**Comment by aschempp** [comment]
this should be supported since https://github.com/isotope/core/pull/1627. Does it work if you have image composition (`<picture>` element)?

**Comment by contaoacademy** [comment]
Doesn't work at all. The html-element is generated as `<img>` and not as `<picture>`.
Maybe I have missed something.

![screen-20220711_71n6qMjh](https://user-images.githubusercontent.com/23719181/178269886-9b512894-db68-414c-a097-6c3346687027.jpg)

**Comment by contaoacademy** [comment]
I think the template `iso_gallery_inline.html5` is outdated.
See here: https://github.com/isotope/core/blob/2.8/system/modules/isotope/templates/gallery/iso_gallery_inline.html5#L13

I should look like this:
https://github.com/isotope/core/blob/2.8/system/modules/isotope/templates/gallery/iso_gallery_standard.html5#L5

**Comment by contaoacademy** [comment]
Interesting: https://github.com/isotope/core/commit/32d9188b706a1e511507ec223f76a1029770c9a8
_Be aware that this gallery type does not support &lt;picture&gt; (responsive images)._

**Comment by aschempp** [comment]
yeah, because they would interfere with the javascript I guess. Since this is intentional, I think the issue can be closed? 🙃
