### ISSUE TITLE
Deutsche Übersetzung bei Mitgliedergruppe fehlt

### ISSUE THREAD

**Issue by contaoacademy** [isotope/core#2320]
Bei den Einstellungen der Mitgliedergruppe fehlt die Übersetzung.
![screen-20220712_91YRHWbQ](https://user-images.githubusercontent.com/23719181/178516611-bd918694-0cf9-4537-a7d3-403e77de1abb.jpg)

**Comment by aschempp** [comment]
should be fixed by f20450caed76c89b09f9fa0bebb9d7ccb0cc712e

**Comment by contaoacademy** [comment]
Fehler ist noch nicht behoben und noch in der 2.8.x-dev vom 20.07.2022 enthalten.
