### ISSUE TITLE
Warning: Undefined array key "id"

### ISSUE THREAD

**Issue by tsarma** [isotope/core#2326]
Contao: 4.13.6
Isotope: 2.8.5
PHP: 8.1.6

In debug modus, On a page with product list module, it shows this warning of undefined array key.

```
vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/Model/Product/Standard.php:1029
```
![Screenshot 2022-07-15 at 13 24 09](https://user-images.githubusercontent.com/683894/179214302-50a7cdd2-96a9-4d60-9f48-425824d12d89.png)

**Comment by aschempp** [comment]
see https://github.com/isotope/core/pull/2338
