### ISSUE TITLE
Dots in translation keys in `tl_iso_config.xlf`

### ISSUE THREAD

**Issue by ameotoko** [isotope/core#2327]
This DCA definition has dots in options array elements, which means their respective translations had dots in translation keys before https://github.com/isotope/core/commit/2f713ffaeaa875baf973795409e5a2e6701242f5.

https://github.com/isotope/core/blob/175a07f4b3e84fcfee63d48f8eda91f8475cf512/system/modules/isotope/dca/tl_iso_config.php#L513-L519

However, after converting to XLIFF in https://github.com/isotope/core/commit/2f713ffaeaa875baf973795409e5a2e6701242f5, this now is invalid, because XLIFF loader loads this like `$GLOBALS['TL_LANG']['tl_iso_config']['currencyProvider']['ecb']['int']` instead of `['ecb.int']`:

https://github.com/isotope/core/blob/175a07f4b3e84fcfee63d48f8eda91f8475cf512/system/modules/isotope/languages/en/tl_iso_config.xlf#L362-L367

The most obvious fix is probably replace `ecb.int` with `ecb_int`, but it would require migration, and I am not familiar with `runonce` system...

**Comment by aschempp** [comment]
Can't we escape the name in the language file to `tl_iso_config.admin\.ch`?

**Comment by ameotoko** [comment]
Escaping does not work in `.xlf` files, but it's possible to have a `tl_iso_config.php` file with just these two translations, along with `tl_iso_config.xlf` storing everything else. This works.

**Comment by aschempp** [comment]
I have applied a fix in a4148a8a5be244767ab527c85dad3581dc184940. Since we still handle the old DB values in the automater, and update would not break anything and a migration is not really necessary imho. You would need to select a new value when editing a config, but that's fine with me. Let me know if you disagree 🙃

**Comment by ameotoko** [comment]
LGTM :)
