### ISSUE TITLE
Warning: Cookie "ISOTOPE_TEMP_CART" verfügt über keinen gültigen Wert für das "SameSite"-Attribut

### ISSUE THREAD

**Issue by contaoacademy** [isotope/core#2328]
Firefox zeigt mir folgende Warnung in der Console an:

> Das Cookie "ISOTOPE_TEMP_CART" verfügt über keinen gültigen Wert für das "SameSite"-Attribut. Bald werden Cookies ohne das "SameSite"-Attribut oder mit einem ungültigen Wert dafür als "Lax" behandelt. Dadurch wird das Cookie nicht länger an Kontexte gesendet, die zu einem Drittanbieter gehören. Falls Ihre Anwendung das Cookie in diesen Kontexten benötigt, fügen Sie bitte das Attribut "SameSite=None" zu ihm hinzu. Weitere Informationen zum "SameSite"-Attribut finden Sie unter https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite.

**Comment by aschempp** [comment]
I don't think this is a problem, the cookie must never be sent to third parties.
