### ISSUE TITLE
Fehler Eingabemaske neue Produkte

### ISSUE THREAD

**Issue by nimbec** [isotope/core#2329]
Bei der Erfassung neuer Produkte wird mir (zunächst) kein Textfeld für die Eingabe der Artikelnummer angezeigt. Bei mehrmaligem Bearbeiten wird es dann irgendwann mal angezeigt und ein Speichern des Produktes ist ohne Angabe der Artikelnummer nicht möglich. In der Produktübersicht wird das Produkt auch ohne Probleme ohne Artikelnummer gelistet.

**Comment by contaoacademy** [comment]
Hast du ggf. eigene Attribute ergänzt und die Reihenfolge der Felder in den Produktatrributen verändert?
Kannst du einen Screenshot deines Produkttyps und der Eingabemaske posten?

Es könnte auch sein, dass du bei dem Feld nach der Artikelnummer mit `clr` arbeiten musst.
Siehe auch: https://docs.isotopeecommerce.org/manual/de/backend-configuration/store-configuration/products/product-types/#ausrichtung

**Comment by aschempp** [comment]
Ich denke auch dass die Konfiguration des Produttyps angepasst werden muss. Manchmal verschwinden sonst Felder (bzw. werden in der Darstellung überlagert).
