### ISSUE TITLE
Image with watermark is not created

### ISSUE THREAD

**Issue by contaoacademy** [isotope/core#2331]
- Contao 4.9.31 | 4.13.6
- PHP 7.4 | 8.1
- Isotope 2.8.5

When I activate the watermark function in the gallery, the image is displayed in the frontend without a watermark.
No matter which gallery I use, the image is always displayed without watermark in the frontend.

**Comment by aschempp** [comment]
what graphics library do you use? Imagick or GD?

**Comment by contaoacademy** [comment]
imagick module version = 3.7.0

**Comment by BennyK80** [comment]
Any news on this?

**Comment by aschempp** [comment]
I'm not sure we can actually fix this, since watermark support was only available with Gd but probably conflicts with the multiple image library support of the latest Contao versions. Maybe @ausi has a hint?

**Comment by ausi** [comment]
I’d debug `$picture` before and after this code block: https://github.com/isotope/core/blob/98aae516dff019663cda6f1a6805fdbe3d922b72/system/modules/isotope/library/Isotope/Model/Gallery/Standard.php#L382-L392

**Comment by aschempp** [comment]
This was a bug in the Haste library, see https://github.com/codefog/contao-haste/issues/194
