### ISSUE TITLE
Display problems of widgets and fields in the backend

### ISSUE THREAD

**Issue by contaoacademy** [isotope/core#2333]
Contao 4.13.6
Isotope: 2.8.5
PHP 8.1
Browser: Firefox

If the browser window has a smaller viewport, then it can happen that the fields in the backend are too long and are cut off.

Example: Range filter module (See screenshot)
![screen-20220720_XV2Bkdqk](https://user-images.githubusercontent.com/23719181/179976759-bdc02aef-06f5-489d-9a7b-3a33929f90ca.jpg)

**Comment by aschempp** [comment]
fixed in f8efa24643fd4f753dacd2c7235d3fe875b2edfb
