### ISSUE TITLE
Failed to create "symbolic" link

### ISSUE THREAD

**Issue by berecont** [isotope/core#2345]
new installation 4.9 or 4.13
tested with local installation, laragon under php74
can't install latest version »
`ERROR web/isotope Failed to create "symbolic" link from "C:\laragon\www\myproject\isotope" to "C:\laragon\www\myproject\web\isotope": symlink(): No such file or directory`
installing `2.7.*` is possible
updateing from `2.7.4` to latest `2.8.*` is possible, too

**Comment by fritzmg** [comment]
I can confirm the problem. I think the `SymlinkListener` simply needs to make sure the `isotope` directory exists.

**Comment by aschempp** [comment]
I'm wondering how it can be that this directory does not exist? Since it must be added by the composer plugin when installing the legacy extension?

**Comment by fritzmg** [comment]
Which composer plugin are you referring to?

**Comment by exscorp** [comment]
Kann das Problem bestätigen. War schon am verzweifeln das ich auf einmal Contao mit Isotope nicht installieren kann bis ich den issue und Tipp von @berecont gesehen habe.

![Screenshot 2022-08-04 163402](https://user-images.githubusercontent.com/3008649/182877556-fdfd9c29-879f-4b1f-9b08-ea22840eea30.png)

Habe mehrere Isotope-Versionen probiert. **2.8.1**  bis **2.8.5** funktionieren nicht, kommt immer der symlink-Fehler. 
**2.8** wurde ohne Probleme installiert und dabei auch der Isotope-Ordner erstellt. Dann konnte man auf 2.8.5 aktualisieren.

**Comment by aschempp** [comment]
> Which composer plugin are you referring to?

I was referring `contao-community-alliance/composer-plugin`. But I see that the folder is not really created there, no idea how that ever worked 🤷
