### ISSUE TITLE
Notifications for completed orders are combined, instead of being overridden

### ISSUE THREAD

**Issue by ameotoko** [isotope/core#2356]
Some of the payment methods, like `Cash` and `PaypalPlus` for example, execute both `$objOrder->checkout()` and `$objOrder->updateOrderStatus()` when the final checkout step is processed.

https://github.com/isotope/core/blob/b255e439f0555fe122c9f0e0bdd76f08479a08fa/system/modules/isotope/library/Isotope/Model/Payment/Cash.php#L23-L30

The problem is, `$objOrder->checkout()` sends notifications for completed orders, set in Store config, and `$objOrder->updateOrderStatus()` sends notifications for completed orders, set in the payment method.

However, the description for `Store configuration -> Status for new orders` says: _"Choose a matching status for new orders. A payment module can override this."_

In reality, the status from the store configuration is initially applied, and _then_ overridden, meaning – if you have notifications on order status change, all of them are sent – first from the store config, and then also from the payment method.

**Comment by ameotoko** [comment]
On a successful checkout, my instance is supposed to send 2 emails – one to the manager, and one to the client.

In a default case, that's what happens.

When a payment method is used, that "overrides" the order status – 4 emails are sent.

If I set notifications in the dedicated checkout module – 6 (!) emails are sent.

**Comment by ameotoko** [comment]
The comment in this code block

https://github.com/isotope/core/blob/b255e439f0555fe122c9f0e0bdd76f08479a08fa/system/modules/isotope/library/Isotope/Model/ProductCollection/Order.php#L229-L232

makes me think that the methods are called in the wrong order here?

> https://github.com/isotope/core/blob/b255e439f0555fe122c9f0e0bdd76f08479a08fa/system/modules/isotope/library/Isotope/Model/Payment/Cash.php#L23-L30

Seems to fix my issue, when I switch them like this:

```php
$objOrder->updateOrderStatus($this->new_order_status);
$objOrder->checkout();
```

**Comment by aschempp** [comment]
You should not set a notification for a payment status. Only use the checkout module configuration for that. Status notifications are only meant for statuses you set manually (e.g. to "has been shipped" after payment).

**Comment by ameotoko** [comment]
I see. I have been using different checkout modules for different product types, in order to set different payment methods which use different statuses, which send different notifications. What I should have been using instead, is just setting notifications in checkout modules 😂

I guess I had trust issues because of #2332 🙂

I will close the issue after I update and test my configuration later today.
