### ISSUE TITLE
SymlinkListener requires webmozart/path-util

### ISSUE THREAD

**Issue by Toflar** [isotope/core#2357]
See https://github.com/isotope/core/blob/2.8/system/modules/isotope/library/Isotope/EventListener/SymlinkListener.php#L53

But that does not exist in `composer.json` causing an error in later Contao versions which use `symfony/filesystem`.
So I think we should do both, switch to `symfony/filesystem` and define the dependency on top.

**Comment by aschempp** [comment]
we cannot switch because we support Contao 4.9. Added dependency in 84224490b1d045c371d81aacb73ed530c663584c
