### ISSUE TITLE
Editing option in the options manager breaks in PHP8 when the parent attribute is a variant

### ISSUE THREAD

**Issue by jamesdevine** [isotope/core#2360]
To replicate, when using Isotope with PHP8:

1. Add an attribute under "Store configuration > Attributes" that uses the options manager, tick the "Add product to variants wizard" box
2. Attempt to add an option for the attribute via the options manager

The following error will display: Warning: Undefined array key "price".

I have found the cause of this, but i'm unsure if this is something that needs to be fixed in Isotope or in the Terminal42 multilingual DCA driver.

In system/modules/isotope/library/Isotope/Backend/AttributeOption/Callback.php, line 76:

```
if (null === $objAttribute || $objAttribute->isVariantOption()) {
           unset($GLOBALS['TL_DCA'][AttributeOption::getTable()]['fields']['price']);
}
```
 
 The price field is removed from the DCA if the attribute option is marked as being a variant option.
 
This causes an undefined array key warning from the DCA driver (terminal42/dc_multilingual/src/Driver.php line 216) which is expecting the price field to be present because it is still present in the palette.

**Comment by aschempp** [comment]
Sounds like a bug in DC_Multilingual to me, because it should just ignore missing fields in the palette. I have also fixed this in Isotope (4bd9196b54e2237ad1357c2207eab44c95be4ba4) but please create an issue for DC_Multilingual.
