### ISSUE TITLE
Autoloading of classes without correct namespace in payment module

### ISSUE THREAD

**Issue by hangarsieben** [isotope/core#2362]
It appears that the isotope payment module starts the autoloading of "Module" classes without correct namespace. 

`Error: During inheritance of Isotope\Model\Payment, while autoloading Module: Uncaught ErrorException: Warning: Cannot declare class Module, because the name is already in use in /vendor/contao/core-bundle/src/Resources/contao/library/Contao/ClassLoader.php:177`

Stack trace:

`#0 /www/htdocs/contao/vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/Model/Payment.php(54): Contao\ClassLoader::load('Module')`

IsotopePayment class does not respect the Contao namespace in line [85](https://github.com/isotope/core/blob/cce4d7331e4636b174721170add0720dbaa03fd3/system/modules/isotope/library/Isotope/Interfaces/IsotopePayment.php#L85) and [95](https://github.com/isotope/core/blob/cce4d7331e4636b174721170add0720dbaa03fd3/system/modules/isotope/library/Isotope/Interfaces/IsotopePayment.php#L95). 

In IsotopePayment.php `\Module` is declared instead of `\Contao\Module`, leading to autoloading interpreting this as `"Module"`. This leads to errors in Contao Manager, rendering further package operations impossible. 

Observed in Contao 4.13.6, 4.13.7 and 4.13.8 with isotope 2.8.5, 2.8.6 and 2.8.7 running on PHP 7.4, 8.0 and 8.1 in combination with the Eclipse X Theme from Premium Contao Themes.

See also corresponding forum discussion [here](https://forum.premium-contao-themes.com/forum/themes/eclipse-x/25492-general-error-bei-cache-warm-up-eclipse-x-4-1-8-contao-4-13). H/t for this find and solution to @timgatzky.

**Comment by aschempp** [comment]
Closed in favour of https://github.com/isotope/core/pull/2363
