### ISSUE TITLE
Set default order status *before* payment process has been completed

### ISSUE THREAD

**Issue by AlexanderWillner** [isotope/core#2365]
Steps that will reproduce the problem?
1. Set a default order status
2. Order an item
3. Cancel the payment process

What is the expected result?
The order should have the default order status

What happens instead?
The order still has order status `0`

Possible workaround:
Change to code accordingly.

Any additional information:
Specifically at https://github.com/isotope/core/blob/6ea66e0b7c3f366835190d435e4cd6b5497cdfe0/system/modules/isotope/library/Isotope/Model/ProductCollection/Order.php#L231 the order status is set to the default status only *after* the payment process has been completed.

When, e.g., the payment process has crashed (software issue, network issue, ...) the order is not visible in the backend.

**Comment by aschempp** [comment]
if the payment process was not successful, the order is not placed and the user is taken back to the confirm screen. This is the intended behaviour in Isotope eCommerce, otherwise you would likely end up with a lot of unpaid orders where the customer will never finish them.

**Comment by AlexanderWillner** [comment]
Well, there are different use cases. The idea is the following:

* Cart > Order (status: new) > Payment > Success (status: payed)
* Cart > Order (status: new) > Payment > Cancelled (status: cancelled)
* Cart > Order (status: new) > Payment > Network / Server issues (status: new)

Currently the last two use cases can't be identified:

* Cart > Order (status: none) > Payment > Success (status: payed)
* Cart > Order (status: none) > Payment > Cancelled (status: none)
* Cart > Order (status: none) > Payment > Network / Server issues (status: none)

**Comment by aschempp** [comment]
as I said. If the payment is not successful, the order is not placed. Thats the default behaviour in almost any shop I have ever seen, and can't be easily changed in Isotope. It would be nice to have such an option for advanced shops, but there's currently not plans to add that feature on our side.
