### ISSUE TITLE
No buttons for "Add to favorites  or Add to wishlist"

### ISSUE THREAD

**Issue by xApep** [isotope/core#2366]
Hey.
When enabling **Add to favorite**s or **Add to whishlist** on product list or product reader, no buttons are generated in frontend.

I have debugged also the `$this->actions` but none of them are returned, except for the "add to cart".
Also manual `<input name="add_to_favorites"` doesn't do anything.
![image](https://user-images.githubusercontent.com/1315340/188205316-be9c2643-980b-41c1-8463-1c5247aa8101.png)

Running Contao 4.11.9 and Isotope 2.7.4

**Comment by netzarbeiter** [comment]
The user has to be logged in before the buttons are displayed.

Please always update to the latest Contao and Isotope version before submitting a bug report.

**Comment by xApep** [comment]
Didn't even think for a second you need to be sign in to use benefits of Add to Favorites.

Thanks for the info.

**Comment by aschempp** [comment]
FYI favorites will be supported for guests starting in Isotope 2.9 😎
