### ISSUE TITLE
Products with variants sorting by sku 

### ISSUE THREAD

**Issue by cboelter** [isotope/core#2375]
I've created a producttype with variants. So in the productlist is the product with its main variant shown. Everything fine.
If I enable the sorting by sku in the productlist the sorting is not working. I've checked the code a little bit and it seems the sorting is applied to the main product, the variant is not loaded before the sorting is applied, but the main product does not have an sku if the variants are enabled.

Is this a known limitation or is something wrong with my configuration?

I tested to load the default variant here: https://github.com/isotope/core/blob/2.8/system/modules/isotope/library/Isotope/Model/Product.php#L557-L559
That fixed the problem for me but I'm not sure about side effects.

**Comment by aschempp** [comment]
I think that's currently a known limitation (if each variant has its own SKU). Also applies to any other field. The only solution I can think of would be a server-side sorting. There's already a similar implementation for prices, maybe they can be dynamically applied if the sorting attribute is configured on a variant.

**Comment by aschempp** [comment]
Fixed by #2378
