### ISSUE TITLE
Sorting by dateAdded is not working for Variant list

### ISSUE THREAD

**Issue by xApep** [isotope/core#2376]
If we use variant list then sorting by dateAdded is not working correctly.

After little debugging I have found out that variants have 0 for dateAdded and of course it does not work then.

tl_iso_products
<img width="369" alt="image" src="https://user-images.githubusercontent.com/1315340/193324012-5c28631c-a98e-4a77-b786-30754b253261.png">

Contao: 4.13.8
Isotope: 2.8.7

**Comment by aschempp** [comment]
Fixed in 30d244ef3910e9267c9cac3d9b4c7d243d0472fc
