### ISSUE TITLE
PDF-Rechnungen im Dateisystem ablegen

### ISSUE THREAD

**Issue by fenepedia** [isotope/core#2383]
Eine Kundin von mir möchte für Ihre Buchhaltung alle generierten Rechnungen gerne im Dateisystem ablegen. Ist so eine Funktion geplant?

**Comment by asaage** [comment]
Hast du probiert das über's notification-center zu machen?
Dort kann man doch glaube ich auch in einem Ordner speichern.

**Comment by fenepedia** [comment]
Danke für den Hinweis. Das war auch mein erster Gedanke. Leider gibt es dort nur eine Ablage für CSV und Plaintext bzw. XML.Vielleicht gibt es ja noch einen anderen Workaround.

**Comment by 9teufel** [comment]
Es werden alle generierten PDF Rechnungen im Ordner system/tmp abgelegt.

Der Ordner wird regelmäßig per TL_CRON geleert, das habe ich unterbunden:
contao/config/config.php
```
$GLOBALS['TL_CRON']['monthly']['purgeTempFolder'] = [\Contao\Automator::class, 'purgeTempFolder']; 
unset($GLOBALS['TL_CRON']['daily']['purgeTempFolder']);
unset($GLOBALS['TL_CRON']['monthly']['purgeTempFolder']);
```

Vielleicht hilft's...

**Comment by aschempp** [comment]
ich denke das ist aktuell nicht eingebaut, aber du kannst eine Rechnung im Backend ja jederzeit (neu) generieren lassen, also wozu ablegen?

**Comment by asaage** [comment]
> also wozu ablegen?

Ich vermute mal Archivierungsrichtlinien / Original / etc...

Eine Möglichkeit, die mir noch einfällt, die ich mal in einem shop eingebaut hatte:
Einige Cloudanbieter ermöglichen sowas wie E-mail-Freigabe (HiDrive von Strato zum Beispiel und dropbox)
Für nextcloud gibts sowas wohl auch - hab ich mich aber noch nicht rangewagt wegen "inofficial"
Da kann man sich zu einem definierten Ordner eine spezielle Email-Adresse geben lassen und wenn man dort was hinsendet werden die Anhänge in dem Ordner abgelegt. Wäre vielleicht eine Option wenn man die Möglichkeit hat und das nicht unbedingt im contao Dateisystem gespeichert werden muss.

**Comment by fenepedia** [comment]
Vielen Dank für eure Ideen und Vorschläge.

Die Vermutung von @asaage ist korrekt. Sie möchte einfach ein Archiv mit allen Rechnungen für die Steuererklärung haben. Und Sie möchte Sich einfach nicht darum kümmern müssen. Bisher bekommt Sie jede Mail an ein Postfach und holt dort die Datei manuell aus Ihren E-Mails. Das manuelle Generieren der Rechnung kennt Sie schon. Das löst Ihr Problem allerdings nicht mit dem Archiv.

Die Idee mit der [Dropbox](https://help.dropbox.com/de-de/create-upload/email-files-to-dropbox) klingt nach einer Lösung, die klappen könnte. Ich schlage Ihr das mal vor. Danke für den Tipp.

Falls die Dropbox nicht klappt, werde ich mal die Lösung mit dem Temp-Ordner versuchen. GGf. ein Bash-Script um die Dateien von dort regelmäßig in einen anderen Ordner zu kopieren.
