### ISSUE TITLE
PHP 8 warning Isotope Label InsertTag

### ISSUE THREAD

**Issue by tsarma** [isotope/core#2384]
`Undefined array key 2` at line 56

https://github.com/isotope/core/blob/2.8/system/modules/isotope/library/Isotope/InsertTag.php#L56

![196653117-091234b0-8013-4c31-bf67-f94b88b3ffbd](https://user-images.githubusercontent.com/683894/197999348-a57cbf00-114c-4a4a-8e9b-5116a4ca41a2.png)

**Comment by aschempp** [comment]
fixed in e80f11b0f1e30adf44a7949d2387d9f6f76f5441
