### ISSUE TITLE
 Undefined array key "ISO_CONFIRM"

### ISSUE THREAD

**Issue by Ernestopheles** [isotope/core#2386]
isotope 2.8.8   contao 4.13.14   php 8.1   lokale Umgebung   dev Mode 

Neu aufgesetzte Webseite; lege einen Artikel in den Warenkorb; das geht noch, allerdings bringt die Produktseite (enthält lister und reader) im Versuch, die Bestätigungsmeldung zusammenzustellen, diesen Fehler:

Undefined array key "ISO_CONFIRM"  at vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/Message.php:84  

Debug ergibt, dass $_SESSION zu diesem Zeitpunkt in der Tat keinen Eintrag "ISO_CONFIRM" hat.

**Comment by Ernestopheles** [comment]
Der Fehler tritt im dev-Modus auf. Im prod-Modus wird er scheinbar ignoriert.

**Comment by Ernestopheles** [comment]
has been resolved (missing php extension DOM in IDE)

**Comment by aschempp** [comment]
fixed in 3295555b5fc9d54c29869b59d46b7c59a20cf576

**Comment by Ernestopheles** [comment]
Thanks a lot😃
Am 17. Jan. 2023, 09:19 +0100 schrieb Andreas Schempp ***@***.***>:
