### ISSUE TITLE
Benutzer sieht nur Produkte mit zugeordneter Produktgruppe oder selbst angelegte

### ISSUE THREAD

**Issue by Ernestopheles** [isotope/core#2388]
Problem: Admin legt diverse Produkte an, ohne eine Produktgruppe zuzuordnen. Benutzer sieht trotz aller Rechte nur selbst angelegte Produkte.

"Lösung": Durch Löschen aller Produktgruppen sieht der Benutzer nun tatsächlich alle Produkte und nicht nur die selbst angelegten. 

1. Vorschlag: Im Isotope Handbuch dokumentieren (ist das so korrekt? Wenn ja, ändere ich gerne die Doku per PR):

"Wenn ihr Produktgruppen definiert habt, MUSS jedes Produkt einer Produktgruppe zugeordnet werden. Ansonsten kann es sein, dass Redakteure Produkte, die sie nicht selber angelegt haben, gleichwohl Rechte vorhanden, nicht sehen können."

2. Vorschlag: Mir scheint, der Fehler wäre zu beheben, wenn bei der Prüfung der Rechte im Produktpanel der Fall "Produktgruppe nicht zugewiesen" richtig abgefangen würde.

**Comment by aschempp** [comment]
Gibt es denn eine Option "Produktgruppe nicht zugewiesen"?

**Comment by Ernestopheles** [comment]
Es gibt die Option, Produktgruppen zuzuweisen , dies ist nicht obligatorisch.

**Comment by aschempp** [comment]
aber es gibt keine Berechtigung für "keiner Gruppe zugewiesen", oder?

**Comment by Ernestopheles** [comment]
Nein, nur "erlaubte Produktgruppen" zur Auswahl

**Comment by aschempp** [comment]
> Vorschlag: Mir scheint, der Fehler wäre zu beheben, wenn bei der Prüfung der Rechte im Produktpanel der Fall "Produktgruppe nicht zugewiesen" richtig abgefangen würde.

Ich denke nicht dass Produkte ohne Gruppen angezeigt werden sollen, wenn man nur bestimmte Gruppen sehen darf. Und wenn man alles sehen darf, sollten keine Gurppen eingeschränkt werden (wie du korrekt angemerkt hast). Von daher gerne einen Vorschlag für's Handbuch, wo würdest du das hinpacken? Bei den Berechtigungen für die Gruppen?

**Comment by Ernestopheles** [comment]
> Ich denke nicht dass Produkte ohne Gruppen angezeigt werden sollen, wenn man nur bestimmte Gruppen sehen darf.

Das sehe ich auch so.

Wenn man alles sehen kann, tritt das beschriebene Problem auf. Der Benutzer sieht nur selbst angelegte Produkte. Wenn ich es richtig in Erinnerung habe, gilt das unabhängig davon, ob Gruppen eingeschränkt wurden.

Also: es gibt Produktgruppen, diese wurden dem Benutzer nicht als erlaubt zugeordnet. Oder eben doch. Dann sieht der Benutzer Produkte, die der Admin angelegt hat, nicht.  Auch wenn diese Produkte keiner Produktgruppe zugeordnet sind.

Insofern doch eher ein Bug, oder?

**Comment by aschempp** [comment]
> Dann sieht der Benutzer Produkte, die der Admin angelegt hat, nicht. Auch wenn diese Produkte keiner Produktgruppe zugeordnet sind.

Wenn die Produkte keiner Gruppe zugeordnet sind, dann sind sie in keiner Gruppe die der User sehen darf?

**Comment by Ernestopheles** [comment]
Ja, erscheint mir aber dennoch unplausibel, denn ohne existierende Gruppen sieht der User ja auch die Produkte.
Am 6. Juni 2023, 09:35 +0200 schrieb Andreas Schempp ***@***.***>:

**Comment by aschempp** [comment]
Wenn es keine Gruppen gibt sind die Gruppen in den Berechtigungen auch nicht eingeschränkt. Ähnlich gilt es übrigens auch für Dateien: man sieht nur Dateien innerhalb der freigegebenen Ordner, Dateien im Root sieht nur der Admin (nur kann man bei Isotope den Admin-Modus sozusagen aktivieren indem man keine Berechtigungen vergibt).
