### ISSUE TITLE
Switching Variants with PHP 8.1 and Isotope 2.8.8

### ISSUE THREAD

**Issue by rburch** [isotope/core#2399]
We were having issues when upgrading to Isotope 2.2.8 while running PHP 8.1. I'm not sure where the issue is, but when trying to switch variants on the front-end on a product page, variant data would not update on the page. We were not seeing any errors in Ajax or anything in the error logs. When switching back to PHP 8.0 things worked as they should. We testing this with default modules and templates.

**Comment by aschempp** [comment]
did you enable or disable the Contao debug mode?

**Comment by rburch** [comment]
Sorry I was away. We did, but I don't think we saw anything in there. I'll share this with Mark. He was directly working on it. Maybe he'll have more insight.

**Comment by aschempp** [comment]
Closing this for now. Feel free to follow up if you have more information.
