### ISSUE TITLE
Warning: Undefined Array Key

### ISSUE THREAD

**Issue by rburch** [isotope/core#2400]
I'm getting one of these for every custom attribute on the website. Contao 4.13.14, Isotope 2.8.8, PHP 8.0.x

Undefined array key "rail_color" in /home/mayhewtools/public_html/vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/Model/Product/Standard.php on line 909

These along with a couple core Contao array key warnings are filling up my logs and my servers. I'm forces to regular go in and delete the logs. Some of them are getting so big that I can't even open them. Had one that was 300gb!

**Comment by aschempp** [comment]
fixed in 7f81e8b9ae9fe75a3bbe69f8c475cdb5cc348a6f
