### ISSUE TITLE
Contao Site Structure issue PHP 8.1

### ISSUE THREAD

**Issue by rburch** [isotope/core#2401]
With Isotope installed on Contao 4.13.15 I get the following error when trying to access a page in the Contao site structure and when trying to access select a page as a category for a product in Isotope. I'm using Isotope 2.8.8.

An exception occurred while executing a query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'dbname.tl_iso_products' doesn't exist

**Comment by aschempp** [comment]
A table named `tl_iso_products` does not exist in Isotope 2. It did exist in Isotope 1 through, I would assume you are using an outdated extension that causes this problem.
