### ISSUE TITLE
Error on sitemap generation with product variants

### ISSUE THREAD

**Issue by cboelter** [isotope/core#2402]
I'm having a lot of products with variants and default variants. If I try to call the sitemap.xml route (Contao 4.13) I'm getting an exception.

`Warning: DOMDocument::createElement(): unterminated entity reference card_format=141`

The generated URL looks like the following:

`myproduct.html?card_text=28&card_format=141`

The `&` characters are not changed to `&amp;` which breaks the xml generation. For testing I've added a `StringUtil::ampersand()`call here https://github.com/isotope/core/blob/2.8/system/modules/isotope/library/Isotope/Frontend.php#L370. Then the sitemap.xml is generated correctly without errors.

If this approach is okay for you, I'll be able to create a pull request.

**Comment by cboelter** [comment]
Is there any feedback for me?  :-)

**Comment by aschempp** [comment]
I wonder if this is not rather a bug in Contao @Toflar ?

**Comment by Toflar** [comment]
Depends on which format the SitemapController expects and I really don't know nor do I have time to investigate. If you think you found a bug in Contao, create a PR with unit tests covering the case so we can actually see what we're talking about.

**Comment by aschempp** [comment]
see https://github.com/contao/contao/pull/6148
