### ISSUE TITLE
under devilbox sides with a product list module are not loaded (error 503)

### ISSUE THREAD

**Issue by Ernestopheles** [isotope/core#2405]
see: [devilbox issue #949](https://github.com/cytopia/devilbox/issues/949)

Probably merely an issue with devilbox' new release (v3 beta), but some suggestions from here would be helpful (perhaps).

**Comment by Ernestopheles** [comment]
Update, more error details, see https://github.com/cytopia/devilbox/issues/949

**Comment by aschempp** [comment]
there's not much we can do here from Isotope side, especially not with any debug or error output. I'm closing this issue, but feel free to add more information related to Isotope if you have any.

**Comment by Ernestopheles** [comment]
Thank you @aschempp; I hope this issue will be fixed by them. If I have any information related to Isotope I will post them here.
