### ISSUE TITLE
Undefined array key "enabled" - AbstractProductFilter.php

### ISSUE THREAD

**Issue by rburch** [isotope/core#2406]
Isotope 2.8.9, Contao 4.13.15, PHP 8.1
PHP Warning:  Undefined array key "enabled" in /home/ampers/public_html/vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/Module/AbstractProductFilter.php on line 245

**Comment by aschempp** [comment]
fixed in 40843567e15ca779060b6dbacbdfe79cb16d9530
