### ISSUE TITLE
Attempt to read property "id" on null

### ISSUE THREAD

**Issue by rburch** [isotope/core#2407]
Isotope 2.8.9, Contao 4.13.15, PHP 8.1
PHP Warning:  Attempt to read property "id" on null in /home/ampers/public_html/vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/Model/Product/Standard.php on line 632

**Comment by aschempp** [comment]
fixed in 69903f4a954dbb8cec534e6fecd929a3c79a95b3
