### ISSUE TITLE
PHP Warning:  Undefined array key "noHtml"

### ISSUE THREAD

**Issue by rburch** [isotope/core#2408]
Isotope 2.8.9, Contao 4.13.15, PHP 8.1
PHP Warning:  Undefined array key "noHtml" in /home/ampers/public_html/vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/Model/Attribute.php on line 420

**Comment by aschempp** [comment]
fixed in 3ed235f0f14e06c0411409e6c6f8370ae347af00
