### ISSUE TITLE
"Top customers" report

### ISSUE THREAD

**Issue by henobi** [isotope/core#2415]
Hi,
I programmed a report to list the top customers of an isotope shop.
Especially in case of B2B shops this is usually a super useful info. 

I was wondering if this might be also interesting to other users and if I should provide a pull request?

Best,
Hendrik

Sorry, had to anonymize the customers data.

<img width="1169" alt="Bildschirm­foto 2023-02-04 um 19 32 56" src="https://user-images.githubusercontent.com/26099839/216783990-3d906357-9d67-4de5-bb76-2b79d13a6876.png">

<img width="1140" alt="Bildschirm­foto 2023-02-04 um 19 33 59" src="https://user-images.githubusercontent.com/26099839/216783993-a63cbeaf-eb97-44f3-9341-ba6340d58f1f.png">

**Comment by aschempp** [comment]
That sounds great! Would be happy to add if you provide a pull request. 😊

**Comment by aschempp** [comment]
closing in favor of https://github.com/isotope/core/pull/2416
