### ISSUE TITLE
Cannot install Isotope on PHP 8.1

### ISSUE THREAD

**Issue by SpeGal** [isotope/core#2421]
We are running a Contao 4.13.15 installation on PHP 8.1 and cannot install Isotope 2.8.9 via Contao Manager. We get the following error:

`> Resolving dependencies using Composer Cloud v3.5.1
[6.9MiB/0.36s] Loading composer repositories with package information
[67.9MiB/8.67s] Updating dependencies
[92.8MiB/8.94s] Your requirements could not be resolved to an installable set of packages.
[92.8MiB/8.94s] 
  Problem 1
    - Conclusion: don't install isotope/isotope-core 2.8.5 (conflict analysis result)
    - Conclusion: don't install isotope/isotope-core 2.8.6 (conflict analysis result)
    - Conclusion: don't install isotope/isotope-core 2.8.9 (conflict analysis result)
    - isotope/isotope-core 2.8.1 requires symfony/polyfill-php80 ^4.4 || ^5.0 || ^6.0 -> found symfony/polyfill-php80[dev-main, v1.14.0, ..., 1.28.x-dev (alias of dev-main)] but it does not match the constraint.
    - Root composer.json requires isotope/isotope-core ^2.8 -> satisfiable by isotope/isotope-core[2.8.0, ..., 2.8.9].
    - isotope/isotope-core 2.8.0 requires terminal42/notification_center ^1.0 -> satisfiable by terminal42/notification_center[1.7.0, 1.7.1].
    - terminal42/notification_center[1.7.0, ..., 1.7.1] require codefog/contao-haste ^5.0 -> satisfiable by codefog/contao-haste[5.0.0, ..., 5.0.16].
    - Conclusion: don't install codefog/contao-haste 5.0.16 (conflict analysis result)
[92.8MiB/8.94s] <warning>Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.</warning>
[37.7MiB/8.97s] Memory usage: 37.73MB (peak: 190.69MB), time: 8.98s.
[37.7MiB/8.97s] Finished Composer Cloud resolving.
# Cloud Job ID oq2BBq3D5C6Axwll33w8e9RcKFkbKIlRPYVFNyvS3uVwTRJtwAbjXGAa6hUbwYjuujGHpci80Ba3cuWSMnUQby0DnI8r7s3MXuLqNP failed`

The mentioned polyfill-php80 is installed with version v1.27.0 (according to Contao Manager).
The mentioned contao-haste is installed with version 5.0.16
In the installed package list we have only installed four extensions by ourselves:
Flipbert, Contao Sticky Footer, URL Rewrite and Notifications Center – all in the newest versions.

Isotope might not be fully PHP 8.1 compatible yet or incompatible with its own Notification Center according to this forum entry:
[https://community.contao.org/de/showthread.php?84606-Isotope-l%C3%A4sst-sich-nicht-installieren&p=569117#post569117](url)

**Comment by netzarbeiter** [comment]
You need to require terminal42/notification_center:^1.6 and then do a full system update.

**Comment by SpeGal** [comment]
Downgrading Notification Center to 1.6.16 resolves the problem because that means Isotope can downgrade haste from 5 to 4.

Isotope requires haste 4.* and is therefore not PHP 8.1 compatible since haste 4.* is not compatible with PHP 8.1 nor with Contao 4.13.

**Comment by netzarbeiter** [comment]
Contao 4.13.15, Isotope 2.8.9 and Haste 4.25.23 are compatible with PHP 8.1.

**Comment by SpeGal** [comment]
Haste 4.25.23 requires php: ~7.0 || ~8.0
Notifications Center 1.7 requires Haste 5.*
Isotope is incompatible with Haste 5.*

Therefore Isotope is not compatible with Contao 4.13.15, PHP 8.1 because it also requires Notification Center which needs Haste 5 in its latest release! No question about it!
The "solution" cannot be to downgrade another extension! This is still an issue and should not be closed! People in the forum are having trouble installing this extension.

**Comment by netzarbeiter** [comment]
`php: ~7.0 || ~8.0`

This means that it works for every PHP 7 and PHP 8 version. I have an installation running with PHP 8.1 (Contao 4.13.15, Isotope 2.8.9 and Haste 4.25.23).

**Comment by SpeGal** [comment]
#2422
