### ISSUE TITLE
Several php8 errors

### ISSUE THREAD

**Issue by a-v-l** [isotope/core#2425]
Isotope 2.8.10, Contao 4.13.15, PHP 8.1

Uncaught PHP Exception ErrorException: "Warning: Undefined array key "group"" at vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/Model/Attribute/AbstractAttributeWithOptions.php line 98
```php
if ($option['group']) {
```
fixed with:
```php
if ($option['group'] ?? false) {
```

leads to:
Uncaught PHP Exception ErrorException: "Warning: Undefined array key "group"" at vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/Model/Product/Standard.php line 711
```php
} elseif (!\in_array($option['value'], $arrOptions) && !$option['group']) {
```
fixed with:
```php
} elseif (!\in_array($option['value'], $arrOptions) && !($option['group'] ?? false)) {
```

**Comment by a-v-l** [comment]
https://github.com/a-v-l/isotope-core/commit/7206dec1817a2c163762188682b30f3055a139c2

**Comment by a-v-l** [comment]
Uncaught PHP Exception ErrorException: "Warning: Trying to access array offset on value of type null" at vendor/isotope/isotope-core/system/modules/isotope_rules/library/Isotope/Rules.php line 261 (and 266)

Fixed in: https://github.com/a-v-l/isotope-core/commit/f0e565fa03cc514df9296797d15ebc29b01dc0d9

**Comment by a-v-l** [comment]
Uncaught PHP Exception ErrorException: "Warning: Attempt to read property "id" on null" at vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/CheckoutStep/Address.php line 327

Fixed in: https://github.com/a-v-l/isotope-core/commit/c52adb85f27ecced93f4ae564440ee04bdc8d474

**Comment by a-v-l** [comment]
And putting products in the cart leads to several errors:

Uncaught PHP Exception ErrorException: "Warning: Undefined array key "membersOnly"" at vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/Module/CartAddress.php line 110

Uncaught PHP Exception ErrorException: "Warning: Undefined array key "addressDetails"" at vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/Module/CartAddress.php line 187

Uncaught PHP Exception ErrorException: "Warning: Undefined array key "tl_member"" at vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/Module/CartAddress.php line 187

**Comment by aschempp** [comment]
thanks! closing this in favor of https://github.com/isotope/core/pull/2426
