### ISSUE TITLE
Bestellung bearbeiten kann nicht aufgerufen werden

### ISSUE THREAD

**Issue by siegelsupport** [isotope/core#2428]
Ich habe seit neuestem das Problem das wenn in einer Contao Version 4.13.15 unter PHP 7.4.33 mit Isotope 2.8.10 folgende Fehlermeldung erscheint wenn man auf Bestellung bearbeiten geht.

Argument 1 passed to Contao\CoreBundle\Util\LocaleUtil::formatAsLocale() must be of the type string, null given, called in /homepages/u69131/sb_shop/vendor/contao/core-bundle/src/Resources/contao/library/Contao/InsertTags.php on line 1530

Ich habe gesehen das es hierzu schonmal eine Fehlermeldung gab, habe aber keinen Workarround gefunden damit umzugehen...

Danke fürs nachsehen und hoffentlich gibts eine Lösung.

**Comment by netzarbeiter** [comment]
Wurde mit [Contao 4.13.16 ](https://github.com/contao/contao/pull/5606/) behoben.

**Comment by siegelsupport** [comment]
Super Danke!
Am 1. März 2023, 11:53 +0100 schrieb netzarbeiter ***@***.***>:
