### ISSUE TITLE
Unpublished variants are included in the filter 

### ISSUE THREAD

**Issue by criwas** [isotope/core#2430]
**Example**
Product: T-shirt 123
- Variant 1: Size: L (published)
- Variant 2: Size: XL (not published)

When I select "XL" in the "Size" filter, T-shirt 123 is still displayed, even though the XL variant is hidden.

The „published“ condition is only used when BE_USER_LOGGED_IN is set. If I remove the if statement it works as desired.
https://github.com/isotope/core/blob/2.8/system/modules/isotope/library/Isotope/RequestCache/FilterQueryBuilder.php#L153

**Comment by aschempp** [comment]
Thanks for providing a bug fix! Should be fixed by 7a40b73e7e91542e210dc8b216142787e717c846
