### ISSUE TITLE
quantity to add to cart set to zero -> quantity 1 will be added to cart

### ISSUE THREAD

**Issue by Ernestopheles** [isotope/core#2431]
Contao 4.13.16; Isotope 2.8.10; PHP 8.1 local environment.

Input zero to quantity field of product; click cart button. quantity 1 will be added to cart

**Comment by aschempp** [comment]
that is the intended behaviour, enter 0 is the same as leaving the field blank. Adding zero items to the cart makes no sense to me.

**Comment by Ernestopheles** [comment]
OK, I See. Just wanted to make sure it's mit a side effect If my extension.
