### ISSUE TITLE
DB Update Error: Isotope eCommerce Upgrade step "Version 2.3.0 stable" was not run successfully!

### ISSUE THREAD

**Issue by JessesNei** [isotope/core#2433]
PHP 7.4 und 8.0
Contao 4.9.39 und Contao 4.13.16

I tried to update Isotope from 2.7.4 to 2.8.10 the update via Contao Manager works without any Problems.
But the Database Upate is not working. 

I tried to update the Contao Core too and changed the PHP Version to 8.0 to check if it works than but i had alwas the same messsage.

In the Installtool i get the following message:

Isotope eCommerce Upgrade step "Version 2.3.0 stable" was not run successfully!
An exception occurred while executing a query: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'FROM tl_iso_product WHERE IS NOT NULL' at line 2 in /home/httpd/vhosts/helialpin.ch/dev.helialpin.ch/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php on line 86

**Comment by JessesNei** [comment]
With the following Versions Contao 4.9.39 and Isotope 2.8.2 i can open the Intsalltool as soon as I update Isotope to 2.8.3 or higher i get the Installtool error.

**Comment by aschempp** [comment]
I guess this error happens because you have attributes that were not correctly configured and do not have a database field name. I have implemented a fix in ce6ce3d568c3d06cbb9f2beedfc99be58d81ca94.
