### ISSUE TITLE
Backend - Bestellung das Feld "notification_shipping_tracking" wird nicht ausgegeben.

### ISSUE THREAD

**Issue by swinde** [isotope/core#2437]
In den Isotope 2.8 Versionen wird in der Bestellverwaltung beim Aktivieren "Benachrichtigung senden", nicht mehr die Felder
"ctrl_notification_shipping_tracking" und "ctrl_notification_customer_notes" wie in den Versionen 2.7 ausgegeben!
Stattdessen wird der Bestellstatus nochmals ausgegeben!
Dadurch ist es nicht mehr möglich dem Kunden eine Trackingnummer zu übermitteln!

Wenn notwendig kann ich Screenshots beider Varianten oder Systemzugang bereitstellen.

Contao: 4.13
Isotope 2.8.10
Php 8.1

**Comment by southanx** [comment]
Der selbe Fehler tritt bei mir auf nach dem Update von Contao 4.13.16 auf Contao 4.13.18. Wenn man beim Bestellstatus auf Benachrichtigung senden klickt, so öffnet sich unten der Bestellstatus nochmals, aber nicht das Feld zur Auswahl der Benachrichtigung.
<img width="949" alt="Bildschirm­foto 2023-03-27 um 10 50 29" src="https://user-images.githubusercontent.com/104497180/227899482-1fa05ccb-b496-4785-8b8d-8b43c0012030.png">
Macht man das Update rückgängig funktioniert wieder alles.
Isotope 2.8.10 und ein Update von php 8.1.17 auf php 8.2.4 hat auch nicht geholfen.

**Comment by aschempp** [comment]
Das könnte mit den Änderungen in https://github.com/contao/contao/pull/5864 zusammen hängen. Funktioniert es wieder wenn du die Änderungen der Ajax.php rückgängig machst?

**Comment by southanx** [comment]
Das würde ich gerne ausprobieren - nur wo finde ich diese Ajax.php?

**Comment by southanx** [comment]
Bingo - gefunden, gegen den alten Inhalt ausgetauscht, Problem ist weg...

**Comment by aschempp** [comment]
Danke @southanx, damit konnte ich es beheben. Fixed in 2e1805e3bd212eddff49f06a1b469b701ff7e828

**Comment by swinde** [comment]
Danke auch von mir!

**Comment by southanx** [comment]
Danke Andreas!
Anke
