### ISSUE TITLE
Bestellstatus kann nicht geändert werden

### ISSUE THREAD

**Issue by kaipk** [isotope/core#2439]
In der aktuellen Isotope Version 2.8.10 kann der Bestellstatus einer Bestellung nicht geändert werden. Es kommt folgende SQL Fehlermeldung. Contao 4.9.25

> An exception occurred while executing 'UPDATE tl_iso_product_collection SET `order_status`=NULL WHERE id='12'': SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'order_status' cannot be null

> An exception occurred while executing 'UPDATE tl_iso_product_collection SET `sendNotification`=NULL WHERE id='12'': SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'sendNotification' cannot be null

Hat das Problem noch jemand?

**Comment by siegelsupport** [comment]
ich hatte das Problem kurzzeitig auch, es wurde aber durch en upadte im Contao core glaube ich behoben. jetzt bei mir unter Contao 4.13.16 und isotope 2.8.10 funktioniert alles wieder.

**Comment by kaipk** [comment]
ja, danke, Contao Update hat geholfen
