### ISSUE TITLE
Suggestion: Add a way to sort products in product list with multiple fields

### ISSUE THREAD

**Issue by kimleta** [isotope/core#2440]
I had a problem where I really couldn't fix it in nicely manner. I just copied whole code and hard-coded second field. There is not any way to include two of them ! 

Problem was that I need to sort products by a number and by name and in current sorting logic I can select just one field....

If there is any way to do it nicely please tell me, I would appreciate feedback.

**Comment by aschempp** [comment]
The `RequestCache` configuration supports multiple sorting fields for a product list, so you might want to try to create your own sorting module that affects the list instead of adjusting the code of the list itself.

**Comment by kimleta** [comment]
@aschempp I will try to do like that, thank you. I will close a topic when I succeed :)

**Comment by kimleta** [comment]
I tried doing it through that, but I still need too much overwriting for it to work... I hardcoded a line in the code and for each update, I will add the same code. 

It's a dirty solution but neither of my colleagues didn't found a more amicable solution.
