### ISSUE TITLE
ArrayUtil not compatible with Contao 4.9

### ISSUE THREAD

**Issue by rabauss** [isotope/core#2442]
Unfortunately the attribute class is no longer compatible with contao 4.9 because of `ArrayUtil`

https://github.com/isotope/core/blob/bec5100a3df8c4e582b8b9bcbab8cdf06dbff100/system/modules/isotope/library/Isotope/Model/Attribute.php#L417

Because of https://github.com/isotope/core/commit/3ed235f0f14e06c0411409e6c6f8370ae347af00 / https://github.com/isotope/core/issues/2408

Temporary solution - add a conflict to your `composer.json`:
```json
  "conflict": {
      "isotope/isotope-core": ">= 2.8.10 <= 2.8.11"
  },
```

**Comment by aschempp** [comment]
Fixed in fd9e638ca499eedac44f36772cac943446287e9f
