### ISSUE TITLE
Uncaught TypeError: Isotope.displayBox is not a function

### ISSUE THREAD

**Issue by CollinAlpert** [isotope/core#2445]
I'm using Contao 4.12.7, Isotope 2.8.12 and PHP 7.3.33. When clicking the select boxes generated by product variants in the front end, I get the error `Uncaught TypeError: Isotope.displayBox is not a function` in the browser's JS console.

This is what it looks like:
<img width="819" alt="Screenshot 2023-04-16 at 22 36 26" src="https://user-images.githubusercontent.com/14217185/232340635-41f23cb2-2ac9-498c-81f8-3d258b3f672c.png">

What could cause this behavior? Shouldn't the function be included in the JS added by the Isotope package?

**Comment by aschempp** [comment]
Yes, the `isotope.js` should automatically be added to the frontend. Did you maybe adjust your `fe_page` template to not include the standard javascripts?

**Comment by CollinAlpert** [comment]
Hi, thanks for the reply! I can see that the `isotope.pkgd.min.js` file is added (I didn't add that manually). Is that correct or should any other JS files be loaded?

**Comment by aschempp** [comment]
that generally sounds like the correct file. Can you make sure it contains the `Isotope.displayBox` method? Also make sure there are no other errors on the page, they can stop that Isotope script from working.

**Comment by CollinAlpert** [comment]
That seems to be the problem, the file does not contain any `displayBox` function.
This is the header of the JS file, was the `displayBox` function maybe added after v3.0.1?

<img width="383" alt="Screenshot 2023-05-04 at 17 57 21" src="https://user-images.githubusercontent.com/14217185/236261910-3e42bf1f-43ef-4fbd-96ea-8ab6062909fe.png">

There are no other JS errors on the page.

**Comment by Toflar** [comment]
That's not the same Isotope file at all. This is some other script (https://isotope.metafizzy.co/). Not related to Isotope eCommerce.

**Comment by CollinAlpert** [comment]
Ah, makes sense. How does the JS usually get included? I do have my own `fe_page` template, but am not excluding anything. Maybe I need to explicitly add the JS to my `fe_page` template? What would that look like?

**Comment by aschempp** [comment]
Contao extensions include their scripts automatically through `$GLOBALS['TL_JAVASCRIPT']`, so maybe the `$this->mooScripts` section in your `fe_page` is missing?

**Comment by aschempp** [comment]
Closing this since it looks like an issue in your project. Feel free to follow up if you have more information.

**Comment by CollinAlpert** [comment]
I managed to further pinpoint the location where the browser complains:
<img width="909" alt="Screenshot 2023-06-24 at 17 04 13" src="https://github.com/isotope/core/assets/14217185/85b626d6-12d9-438a-8948-c391b537de36">

My `fe_page` template contains the line `<?= $this->mooScripts ?>`, so I think everything is setup correctly.
When I look at the source code of the product detail page, I see `<script src="assets/js/jquery.min.js,isotope.min.js-33554745.js">`, so the JS seems to be correctly added. And that file seems to be the one [here](https://github.com/isotope/core/blob/2.8/system/modules/isotope/assets/js/isotope.min.js).

Although I still don't know why the browser complains about `displayBox` when it is defined in the same file. When calling functions like `Isotope.hideBox()` the JS console, I get the same error.
