### ISSUE TITLE
Replace webmozart/path-util with symfony/filesystem as it is abandoned

### ISSUE THREAD

**Issue by AlexanderWillner** [isotope/core#2449]
As commented in https://github.com/isotope/core/commit/84224490b1d045c371d81aacb73ed530c663584c: The package `webmozart/path-util` is abandoned and we should use symfony/filesystem instead. Any plans or thoughts on this one?

**Comment by aschempp** [comment]
We can/will change this as soon as support for Contao 4.9 is dropped.
