### ISSUE TITLE
Hide protected products from autocomplete

### ISSUE THREAD

**Issue by AlexanderWillner** [isotope/core#2454]
Description: Hide protected products from autocomplete
Version: 2.8.12

**Steps that will reproduce the problem?**
1. Enable autocomplete
2. Type the title of a product that is protected

**What is the expected result?**
The list should only include products I'm allowed to query.

**What happens instead?**
A full list of products.

**Possible workaround:**
While some products are filtered already using SQL, we can't do this here as allowed groups are stored in the database as a PHP serialised array.

**Any additional information:**

In https://github.com/isotope/core/blob/a97a09fca202bdc8e0534d07d7196cd2bca56481/system/modules/isotope/library/Isotope/Module/ProductFilter.php#L119
the complete list of products are returned. A possibility to filter (to be discussed):

```php
            $user_groups = FrontendUser::getInstance()->groups ?? [];
            $data = [];
            foreach($objProducts as $objProduct)
            {
                if ($objProduct->published && ($objProduct->guests || ! $objProduct->protected))
                {
                    // note: $this->iso_searchExact can't be used here
                    $data[] = $objProduct->{$this->iso_searchAutocomplete};
                }
                else
                {
                    $prod_groups = unserialize($objProduct->groups) ?? [];
                    $matches = array_intersect($prod_groups, $user_groups);
                    if ($matches)
                    {
                        $data[] = $objProduct->{$this->iso_searchAutocomplete};
                    }
                }
            }
            //$data = array_values($objProducts->fetchEach($this->iso_searchAutocomplete));
```

**Comment by aschempp** [comment]
Fixed in 626f227bbb8811ad9879f03b838701a415b28793
