### ISSUE TITLE
PHP warning: Undefined variable $i in iso_collection_invoice.html5

### ISSUE THREAD

**Issue by jochi44** [isotope/core#2458]
Isotope V2.8.12
Contao V4.13.24
PHP V8.1.19
================================================================

The server error.log shows these php warnings when generating (printing) an invoice in the backend:

`PHP message: PHP Warning:  Undefined variable $i in /var/www/client/web/vendor/isotope/isotope-core/system/modules/isotope/templates/collection/iso_collection_invoice.html5 on line 12
PHP message: PHP Warning:  Undefined variable $i in /var/www/client/web/vendor/isotope/isotope-core/system/modules/isotope/templates/collection/iso_collection_invoice.html5 on line 27
`

**Comment by aschempp** [comment]
fixed in 07bfc179572450117d843ccb7e772699ff35ad69
