### ISSUE TITLE
PHP warning: Cannot modify header information - headers already sent

### ISSUE THREAD

**Issue by jochi44** [isotope/core#2459]
Isotope V2.8.12
Contao V4.13.24
PHP V8.1.19
================================================================

The server error.log shows this php warning when generating (printing) an invoice in the backend:

`PHP message: PHP Warning:  Cannot modify header information - headers already sent by (output started at /var/www/client/web/vendor/tecnickcom/tcpdf/include/tcpdf_static.php:320) in /var/www/client/web/vendor/contao/core-bundle/src/HttpKernel/Header/NativeHeaderStorage.php on line 27PHP message: PHP Warning:  Cannot modify header information - headers already sent by (output started at /var/www/client/web/vendor/tecnickcom/tcpdf/include/tcpdf_static.php:320) in /var/www/client/web/vendor/symfony/http-foundation/Session/SessionUtils.php on line 52" while reading upstream, server: abc.tld, request: "POST /contao?do=iso_orders&key=print_document&id=140&rt=abc HTTP/2.0"
`

**Comment by aschempp** [comment]
Isotope does not load the `tcpdf_static.php` by default, so maybe you changed something on your TCPDF configuration?

**Comment by jochi44** [comment]
Not that I know of.
I did install the package https://github.com/katgirl/isotope_documents.
Maybe that's related.

Nevertheless, I close this topic.
