### ISSUE TITLE
Saferpay löst keinen Request aus

### ISSUE THREAD

**Issue by gassi101** [isotope/core#2464]
Hallo,
ich habe die aktuellste Contao 4.13 Version und den Shop in 2.8.13 vorliegen. Ich habe alle Daten bei Saferpay korrekt eingegeben ( customerid-terminalid, Saferpay API-Benutzer, passwort etc.
Laut Saferpay Support sieht alles korrekt aus - aber es kommt nicht mal eine Anfrage bei Saferpay an!
Auch wird ein leeres Errorlog von istope erzeugt:
```
[14-Jun-2023 13:08:47] Saferpay request failed with error .
Request:
Response:
.
```

Daher sehr schwer zu sagen woran das liegen kann?!

**Comment by aschempp** [comment]
meine erste Vermutung wäre, dass auf deinem Server/Hosting die ausgehende Verbindung blockiert ist.

**Comment by gassi101** [comment]
Hey,
ich habe die Seite jetzt von Hosteurope zu Hostpoint mal umgezogen. Diese haben ein eigenes Shopsystem das auch eine Saferpay anbindung hat. Leider genau das gleiche. Der Support meint es liegt nicht am Server.

Im Errorlog kommt beim server auch nix im Domlog steht:
```
2003:6:63:c32b - - [16/Jun/2023:12:28:35 +0200] "POST /kasse/failed.html HTTP/2.0" 303 442 "https://domain/kasse/failed.html" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/114.0"
200e1ab:c32b - - [16/Jun/2023:12:28:36 +0200] "GET /kasse/process.html HTTP/2.0" 303 438 "https://domain/kasse/failed.html" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/114.0"
```
Grüße Gassi

**Comment by aschempp** [comment]
hast du Benutzername und Passwort für Saferpay eingetragen?

**Comment by gassi101** [comment]
Hey Andreas,

ja hab ich - ich hänge mal die Config an... Habe mir beim Saferpay Backend auch alle nötigen daten eingerichtet (wobei das inzwischen alles ganz anders läuft wie im Handbuch beschrieben!)
Aber ich denke das wichtigste hab ich gemacht!

Gruß Gasi
![Screenshot 2023-06-19 at 11-02-48 Shop-Konfiguration staging sepps-glace ch](https://github.com/isotope/core/assets/9196586/3659b82c-53c0-42c7-823b-c71d9fa07865)

**Comment by aschempp** [comment]
Behoben in 8a48dde2fdc571a5a7f4fd744860633fa2bf47aa
