### ISSUE TITLE
Cart item user data publicly available

### ISSUE THREAD

**Issue by 0xhtml** [isotope/core#2465]
The URL to edit cart items doesn't check whether the item you are trying to edit actually belongs to your cart or someone else's cart. You can't edit someone else's cart und the button says 'add to cart' rather then 'edit cart'. However, you can see which user selectable attributes the user who's cart item you are viewing has selected. This poses in my opinion a security problem cause you could leak sensitive information entered in e.g. text attributes. An attacker could (especially if the shop has a small product pallet) enumerate the collection_item query parameter from 1 to inf on every product and leak all user attribute data. To reproduce this issue simply add a product with some user attributes to cart and open the edit link in a private browser window.

**Comment by aschempp** [comment]
Fixed in bd4a2d661f3c264bdb536a5dd99971045a0dc3a9
