### ISSUE TITLE
Attribute type Change

### ISSUE THREAD

**Issue by rburch** [isotope/core#2470]
ISO 2.8.11. When I try and change a text field attribute to a Select Menu attribute I get the following error.

An exception occurred while executing a query: SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column 'quantity_in_container' at row 1

Once I get that error any select attribute that I've previously made throws the same error when I try and open the options manager.

**Comment by aschempp** [comment]
Should be fixed in 0db588af4d72ff5bd501e288ec71db5b6a2d3d93
