### ISSUE TITLE
Checkout module redirect to cart, if cart has error, ignores html suffix

### ISSUE THREAD

**Issue by michb** [isotope/core#2471]
If you go to the checkout page but your cart has an error and the `iso_cart_jumpTo` page is set in the checkout module. You will be redirected to the cart as you cannot complete the checkout.

But the redirect happening in 
https://github.com/isotope/core/blob/216f8c0c2a8f385485c3cdd660f43bcaf6ab47c2/system/modules/isotope/library/Isotope/Module/Checkout.php#L565
ignores html suffix. If I test it with `... ->getFrontendUrl() ...` it works in my case.

So in my case 

- I go to `/kasse.html`
- Cart has error and will be redirected to `/warenkorb`
- But it should be `/warenkorb.html`

Contao: 4.13.25
Isotope: 2.8.14
legacy routing on

**Comment by aschempp** [comment]
Fixed in acdec47b35172c0089238c1a9e6d9cb4680c0544
