### ISSUE TITLE
Bestellbedingungen - Erweitertes Formular - Checkboxen - Optionen ansprechen

### ISSUE THREAD

**Issue by keved93** [isotope/core#2475]
Contao 4.13.24
Isotop 2.8.12 (habe in den Changelog für die neuen Versionen geschaut, nichts davon betrifft dieses Problem hier)

Hi,
leider ist es nicht möglich, im Notification Center die einzelnen Felder von Checkboxen anzusprechen, wenn man die Bestellbedingungen erweitert. Lediglich das Formular-Feld an sich kann geprüft werden. Andere Formularfelder, die eine Eingabe benötigen, sind natürlich kein Problem wie zum Beispiel "Bemerkungen" als Text-Feld.

```
Beispiel = Ausgabe in den Mails
##form_checkboxfieldname## = Array
##form_checkboxfieldname_option1## = ##form_checkboxfieldname_option1##
##form_checkboxfieldname_option2## = ##form_checkboxfieldname_option2##
##form_checkboxfieldname_option3## = ##form_checkboxfieldname_option3##

Richtig hier wäre
##form_checkboxfieldname## = Array
##form_checkboxfieldname_option1## = 0 / 1
##form_checkboxfieldname_option2## = 0 / 1
##form_checkboxfieldname_option3## = 0 / 1
```

Das hat zur Folge, dass man im Notification Center mittels {if form_checkboxfieldname_option1=="1"}Placeholder{endif} leider nicht arbeiten kann, um die Mails entsprechenden anzupassen.

Getestet wurden die selben Formularfelder natürlich auch mit einen normalen Formular und E-Mail Versand über Notifaction-Center mit dem selben Inhalt, bei dem alles problemlos geliefert wurde, wie es sein soll.

**Comment by aschempp** [comment]
hast du dazu im Community Forum nachgefragt? Ich bin mir ziemlich sicher dass das geht, weiss aber die entsprechende Codierung nicht auswendig …

**Comment by keved93** [comment]
Wie bereits erwähnt, wurde hier ein Test mit normalen Standard-Benachrichtigung über Notification-Center (ohne Drittanbieter Benachrichtungstyp) durchgeführt, bei dem es funktioniert. Somit ist die Codierung hier die richtige.

Wenn `<input type="checkbox" name="checkboxfieldname[]" value="option1">` ausgewählt ist, muss in diesem Falle ##form_checkboxfieldname_option1## verfügbar sein.

Dies trifft aber nicht bei eurem erweiterten Benachrichtigungstyp zu.
