### ISSUE TITLE
PHP 8.1 Warning: Undefined array key

### ISSUE THREAD

**Issue by sietsevandreven** [isotope/core#2476]
We are using extension Product feeds for Isotope eCommerce by Rhyme Digital, LLC](http://rhyme.digital/).

After updating to php 8.1 we get the following three warnings per product in the xml file:

Undefined array key "gid_google_product_category"
Undefined array key "gid_product_type"
Undefined array key "gid_shipping_weight"

The path for these warnings is: vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/EventListener/CalculatePrice/QuantitySurchagePriceListener.php line 44.

We fixed the issue by changing
$attribute = $GLOBALS['TL_DCA']['tl_iso_product']['attributes'][$name];
to
$attribute = $GLOBALS['TL_DCA']['tl_iso_product']['attributes'][$name] ?? null;.

We're not entirely sure this is the right way though.

I addressed this issue to the extension builder, but he advised to address it to the isotope core.

I look forward to hearing from you.

**Comment by aschempp** [comment]
fixed in e0523710dc1b30f28a2101dab14b5911829993fd
