### ISSUE TITLE
Isotope Options Radio Menu CSS Class not delivered

### ISSUE THREAD

**Issue by spitffm** [isotope/core#2477]
Adding CSS Classes to product options does not work properly. Both ways, adding options by product or by attribute does not show css class in radio button menu (frontend).  (Contao Version 4.13.25 / Isotope Version 2.8.14)

**Comment by aschempp** [comment]
siehe https://community.contao.org/de/showthread.php?85395-Isotope-Produktoptionen-Radio-Menü-CSS-Klasse-wird-nicht-angezeigt
