### ISSUE TITLE
Shipping weight php issue

### ISSUE THREAD

**Issue by sietsevandreven** [isotope/core#2478]
When using <?= $this->generateAttribute('shipping_weight') ?> in iso_reader_default.html5 to display the shipping weight we get an error on the frontend when debug mode is active:

**Undefined array key "format" in vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/Model/Attribute/Weight.php on line 62**

We've changed the code
**from:**
$arrOptions['format'] ?: '%s %s',

**to:**
isset($arrOptions['format']) ?: '%s %s',

It now seems to work, but we're not sure if this is the right solution.

**Comment by aschempp** [comment]
Fixed in 04fe987a750be8358dc91dd4fec17ed2454c3b8c

**Comment by aschempp** [comment]
Fixed in 04fe987a750be8358dc91dd4fec17ed2454c3b8c
