### ISSUE TITLE
Attribute template cannot be selected

### ISSUE THREAD

**Issue by doishub** [isotope/core#2479]
The `customTpl` field exists in the DCA `tl_iso_attribute.php` but has not yet been included in the palette.

https://github.com/isotope/core/blob/2db8e93e356f6be3ed3839dd301ca0c03351d932/system/modules/isotope/dca/tl_iso_attribute.php#L571C10-L571C19

**Comment by aschempp** [comment]
it is dynamically added for customer defined fields or variant options. Are you sure your fields are one of that type?
https://github.com/isotope/core/blob/2.8/system/modules/isotope/library/Isotope/Backend/Attribute/Callback.php#L44-L48

**Comment by doishub** [comment]
In fact, I don't use any of these types. Why is this not possible for the other types? In my case I would like to add more information to the checkbox widget (multiple).
Currently I have written a workaround and catch this in the `iso_reader_default` template by overriding the widget options.

**Comment by aschempp** [comment]
if the attribute does not render a widget (form field), it does not have a template. These templates are the same as you can select in the Contao form generator.

**Comment by doishub** [comment]
Aff, I completely overlooked the template selection for that. Thank you!
