### ISSUE TITLE
CSS classes for attribute widget options are not outputted

### ISSUE THREAD

**Issue by doishub** [isotope/core#2481]
CSS classes can be assigned via the options source and the options manager, but these are not output in the frontend. Do I have the wrong expectation of this field or is it a bug?

![image](https://github.com/isotope/core/assets/48379929/1a46d1fe-c357-481c-8f8c-ba01bbacd360)

**Comment by aschempp** [comment]
as far as I know, you have to manually adjust the `form_radio` template for the class to be generated, since the standard Contao template does not support that :/
