### ISSUE TITLE
Shopsystem in bereits bestehenden Rechnungskreislauf integrieren

### ISSUE THREAD

**Issue by sophie1702** [isotope/core#2484]
Hallo,

Ich befinde mich gerade in der Situation, das ich schon ein funktionierendes Shopsystem in Betrieb habe.
Dieses wurde nun weiterentwickelt und um mehrere Konfigurationen Erweitert und soll jetzt in Betrieb genommen werden und das andere ablösen.
Gibt es hier jetzt die Möglichkeit, bei den Bestellnummern (und der darauf basierenden Rechnungsnummer), an einer selbstgewählten Stelle zu starten. Also nicht nur den Präfix festzulegen, sondern die komplette Startzahl? Da in den beiden anderen System die in dem neuen vereint werden, ja schon Bestellungen ausgelöst wurden und der Rechnungskreislauf nahtlos weiterlaufen muss.

Viele Grüße

**Comment by asaage** [comment]
Notfalls auf DB-Ebene indem du ```AUTO_INCREMENT``` setzt.
Ich kann dir leider aus dem Kopf nicht sagen bei welcher Tabelle das passieren muss (vermutlich tl_iso_orders o.ä.).
https://www.w3schools.com/mysql/mysql_autoincrement.asp

**Comment by aschempp** [comment]
Eine direkte Einstellung dafür gibt es nicht. Du müsstest z.B. eine Testbestellung machen, und dort dann die Rechnungsnummer **manuell in der Datenbank auf die letzte aus deinem vorherigen System** festlegen. Isotope zählt dann bei der nächsten Bestellung automatisch weiter.

PS: GitHub ist für Bugs und Feature Requests, generelle Fragen bitte ins Contao Forum: https://community.contao.org/de/forumdisplay.php?111-isotope
