### ISSUE TITLE
Unsupported operand types: string

### ISSUE THREAD

**Issue by kreadiv** [isotope/core#2502]
If no prices are defined because Isotope should be used as "Product Catalog", this error message appears:

`TypeError: "Unsupported operand types: string * int" at /vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/Model/ProductCollectionItem.php line 342`

The method getPrice() returns an empty string. Shouldn't return the method "null" if no price is set?

**Comment by aschempp** [comment]
Should be fixed in fda57f603b5eabcf989f07cf334d8c9269fd9387
