### ISSUE TITLE
Warning: Undefined array key vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/Model/Gallery/Standard.php:348)"} []

### ISSUE THREAD

**Issue by rburch** [isotope/core#2511]
Another array key warning.  Isotope 2.17 contao 4.13.35 PHP 8.1

Warning: Undefined array key vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/Model/Gallery/Standard.php:348)"} [] #2511

**Comment by aschempp** [comment]
We have fixed several PHP8 issues in the upcoming version 2.9, I think this has been fixed as well, since I cannot reproduce it anymore.
