### ISSUE TITLE
Canonical setting on product detail pages has no effect.

### ISSUE THREAD

**Issue by sixtmedia** [isotope/core#2512]
When trying to adapt the canonical to the URLs of the product variants (sitemap.xml), I realised that the canonical settings have no effect.

I wanted to release the parameters so that there is no mismatch between the canonical and the sitemap URL when the sitemap.xml links are called up 

In this case, the product reader is integrated on an extra page. Neither the canonical settings on the product detail page nor a setting on the category page have any effect on the canonical-Tag when the product details are displayed.

Is this an error or do I have to make the settings elsewhere?

Contao 4.13.35
Isotope 2.8.17
PHP 8.1

Contao community thread with test and screenshots
[https://community.contao.org/de/showthread.php?86163-Isotope-Varianten-in-der-Sitemap-xml-und-Canonicals](https://community.contao.org/de/showthread.php?86163-Isotope-Varianten-in-der-Sitemap-xml-und-Canonicals)

**Comment by aschempp** [comment]
In 2.9.2 the product page can now configure whether the variant URL or the product URL is generated (new checkbox). Additionally, it will correctly generate the cannonical URL including the query parameters if available.
