### ISSUE TITLE
Umleitungsfehler mit Shopkonfigurations-Wechsler

### ISSUE THREAD

**Issue by bastlwastl** [isotope/core#2520]
Contao 4.13.38
Isotope eCommerce 2.8.17

Der Fehler tritt nur mit einer PHP-Version >= 8.1 auf.
Der Fehler konnte in einer neu installiertem Isotope Demo-Installation nachgestellt werden.

Ist bei dem Shopkonfigurations-Wechsler-Modul **nur eine Shopkonfiguration angehakt**, dann bekommt man beim Aufrufen der Seite einen Umleitungsfehler.

**Comment by aschempp** [comment]
fixed in 3a56d39f51695a63d24b6069a82d77e8e45e74cd
