### ISSUE TITLE
PHP 8 warning in `ProductCollection::getLatestItem()`

### ISSUE THREAD

**Issue by ameotoko** [isotope/core#2528]
`ProductCollection::getLatestItem()` throws

```
Warning: Trying to access array offset on value of type null
```

because `$this->arrCache` is still `null` if the collection is empty.

https://github.com/isotope/core/blob/5e82ac900f0016697ebf10c58a9812d94d97ee57/system/modules/isotope/library/Isotope/Model/ProductCollection.php#L893-L913

**Comment by aschempp** [comment]
Fixed in c43ba36a3bce20f4ac08f515c28856165be22213
