### ISSUE TITLE
Datenbankeinträge tax_free_subtotal und tax_free_total sind falsch befüllt

### ISSUE THREAD

**Issue by katgirl** [isotope/core#2530]
Wir haben folgende Konfiguration:

1 x Shopkonfiguration
10 x Steuersätze (für EU)
1 x Steuerklasse (MwSt.)

Der Kunde möchte das die Endkundenpreise in allen Ländern der EU identisch sind. Daher wird am Produkt nur ein Preis gepflegt. Der Steuersatz wird nach Land berechnet.

Das funktioniert auch so weit auf der Rechnung, Warenkorb, Kasse. Jedoch werden in der Datenbank falsche Werte für die Felder: ```tax_free_subtotal``` und ```tax_free_total``` eingetragen. Das wäre aber wichtig, da der Kunde den reinen Umsatz gerne in den Auswertungen & Statistiken dargestellt bekommen möchte.

**Comment by aschempp** [comment]
see https://github.com/isotope/core/pull/2531
