### ISSUE TITLE
Limit member countries does not work

### ISSUE THREAD

**Issue by bennyborn** [isotope/core#2535]
Enabling `Limit member countries` in the shop configuration does not work and will not limit the selectable countries in `ModuleRegistration` anymore.

Having `CompatibilityHelper::isFrontend()` in the `config.php` seems to always return `false`.
I've fixed this in my local installation by moving the check into the `limitCountries` method https://github.com/isotope/core/blob/2.9/system/modules/isotope/library/Isotope/Backend/Member/Callback.php#L27

Happened in Contao 4.13 / Isotope 2.9

**Comment by aschempp** [comment]
Fixed in 0f2d84e0289f5fe2a3a58ac276c35dd42d8f1f44
