### ISSUE TITLE
PayPal Warning Regarding Instant Payment Notifications (IPN)

### ISSUE THREAD

**Issue by BBmt89** [isotope/core#2543]
Hello,

In a shop that switched to the new PayPal Checkout last week (including Contao 4.13.49  and Isotope 2.9.1 updates), we received a PayPal warning email today regarding Instant Payment Notifications (IPN) for the old checkout, which is no longer in use.

system/modules/isotope/postsale.php?mod=pay&id=2

The ID refers to the payment ID, correct? The ID 2 is currently deactivated.

Is this a bug, and/or is there something that needs to be done?

Thank you! 

Paypal Message: 

PayPal IPNs sent to the following URL(s) are not being received:

system/modules/isotope/postsale.php?mod=pay&id=2

If you do not recognize this URL, you may be using a service provider that handles IPN on your behalf. Please contact your service provider with the information above. If this issue persists, IPNs for your account may be disabled.

Orginal: 
Überprüfen Sie Ihren Server, der die sofortigen Zahlungsbestätigungen (IPN) von PayPal verarbeitet. IPNs, die an die folgenden URL(s) gesendet werden, werden nicht empfangen:

system/modules/isotope/postsale.php?mod=pay&id=2

Wenn Sie diese URL nicht kennen, nutzen Sie möglicherweise einen Dienstleister, der IPN in Ihrem Namen verwendet. Bitte wenden Sie sich an Ihren Dienstleister mit den oben genannten Informationen. Wenn dieses Problem weiterhin besteht, kann es sein, dass IPNs für Ihr Konto deaktiviert sind.

**Comment by aschempp** [comment]
It seems likely that the IPN URL was configured directly in the PayPal interface. PP then tries to continue to send IPN notifications for new payments, that result in the error. Can you check your PayPal account for that?
