### ISSUE TITLE
Exportdatei der Bestellungen bringen neuerdings andere Werte

### ISSUE THREAD

**Issue by berecont** [isotope/core#2544]
Contao 4.13.49
Isotope 2.9.1

Export der Bestellungen dürfte sich seit September 2024 (??) geändert haben:
`Bestellungen -> Kunde (UTF-8)` bringt nun in der vorletzten Spalte den Bestellwert ohne Steuer, in der letzten Spalte inkl. Steuer. Dies war bisher nicht so.
`Produkte -> Kunde (UTF-8)` bringt weiterhin in beiden der letzten Spalte die Bruttopreise

Bug oder so gewünscht?
Bleibt die Auswertung in dieser Form? Ich frage, weil die Kundenbuchhaltung diese Auswertungen für das Finanzamt heranzieht und dementsprechend aufbereitet werden muss.

**Comment by aschempp** [comment]
In Isotope Core gibt es keinen Export der Bestellungen. Du scheint eine entsprechende Erweiterung installiert oder eine Anpassung deines Systems zu haben. Bitte kontaktiere den/die entsprechende Entwickler:in.
