### ISSUE TITLE
unable to restart a payment after an incompleted paypal payment

### ISSUE THREAD

**Issue by ghost** [isotope/core#285]
I'm not able to restart a paypal payment after the first try is finished, but not validated.

Inside paypal the user can read 

"Diese Rechnung wurde bereits gezahlt. Um weitere Informationen zu erhalten, wenden Sie sich an den Händler."

and inside the shop

"Der Bezahlvorgang ist fehlgeschlagen. Bitte versuchen Sie es erneut oder wählen Sie eine andere Bezahlmethode."

This can happen, if paypal can't reach the shop server and the payment ist not validated.

The PaymentModule should be called to display a bit more detailed information.

Maybe PP retries (do they?) it after a while and will received a notify during postsale.php call. In this "on_hold"-status it should handle the rest of the process... e.g. "postsaleCheckout"-hocks, etc.

_--- Originally created by v_r on 2011-11-17 16:55:49 (ID 2530)_

**Comment by matzke** [comment]
same happend to me on a local dev machine :-)

**Comment by aschempp** [comment]
This should not happen in Isotope 2.3, which version are you using?
