### ISSUE TITLE
Remove Coupons from Basket

### ISSUE THREAD

**Issue by rezico** [isotope/core#423]
I miss the feature to remove Coupons from the Basket. Thanks alot!

_--- Originally created by rezico on 2012-04-25 17:12:46 (ID 3120)_

**Comment by CodeAlDente** [comment]
:+1: +1

**Comment by virtualize** [comment]
@aschempp is this possible by now?

I did not found any updates on this except this thread from last year. https://community.contao.org/de/showthread.php?49316-Gutscheincode-im-Warenkorb-wieder-entfernen
Thanks.

**Comment by aschempp** [comment]
The ticket is open and assigned to version 3.0, what do you think? ;)

**Comment by virtualize** [comment]
I think we could use this feature right now :) 
Anyway, we will need to implement something like this in an upcoming project. Maybe we can create a pull request then.

**Comment by aschempp** [comment]
This feature has already been added (in 2.5 I think).
