### ISSUE TITLE
error after update to 1.3.13

### ISSUE THREAD

**Issue by zonky2** [isotope/core#525]
Hallo

ich habe über die Update-Funktion von 1.3.12 stable auf 1.3.13 stable geupdatet und bekomme im FE folgenden Fehler:

Fatal error: Uncaught exception Exception with message Query error: Table 'DB123.tl_iso_labels' doesn't exist (SELECT \* FROM tl_iso_labels WHERE language='de') thrown in /mnt/web6/123/htdocs/cms/system/libraries/Database.php on line 686

(DB Aktualisierung gibt "alles ok." aus)

**Comment by ways2web** [comment]
ich hab das Problem nun auch ... beim update auf  1.3.14 wird beim DB Update ein Drop Table "tl_iso_labels" vorgeschlagen. Nach erweiterung Isotope repparieren kommt beim DP Update dann wieder ein CREATE TABLE `tl_iso_labels`

dann wird mir auf einmal version 1.4.8 stable als installiert angezeigt und bietet ein update auf Version 1.3.14 stable Build 5 . Very confused

**Comment by aschempp** [comment]
Diese Versionen werden nicht mehr unterstützt…

**Comment by ways2web** [comment]
jepp... ich versuche mich ja an einem update... aber das ist leichter gesagt als getan :)
