### ISSUE TITLE
Mehrere Produkte mit unterschiedlichen Varianten

### ISSUE THREAD

**Issue by felixpfeiffer** [isotope/core#563]
Ich habe zwei Varianten, Farbe und Durchmesser. Nun soll es in einer Produktgruppe Produkte geben, die entweder beide Varianten besitzen oder nur eine der beiden. Ganz einfach, es gibt Produkte, bei denen Durchmesser und Farbe zur Auswahl stehen und welche, bei denen nur der Durchmesser gewählt werden kann.

Im Produkttyp habe ich bei beiden Varianten-Feldern den zweiten Radio-Button (Mandatory: No never) markiert.

Wenn ich nun die Varianten automatisch für ein Produkt erstellen will aber nur z.B. zwei Durchmesser auswähle, bekomme ich einen Fehler, dass auch in der andere Variante etwas ausgewählt werden muss. Wofür ist dann der "Mandatory"-Befehl?

Ach so, Contao 2.11.9, Isotope 1.4.0 rc2 aus dem Repo.

**Comment by mr-158** [comment]
Ich hab genau das gleiche Problem, die Variante 2 funktioniert bei mir aber nicht, da die Option bei der Ausgabe im Warenkorb nicht ignoriert wird. 

Muss bei dieser Variante sonst noch was eingestellt werden damit das funktioniert?
