### ISSUE TITLE
Canonical Tag flexible for user

### ISSUE THREAD

**Issue by my-om** [isotope/core#855]
Each product should be a input Field for additional head tag(Canonical Tag). User can decide which strategy for canonical Tag(c-link) is there own.  
The Strategy can be : 
1) I didn´t work with canonical Tag, because each product is unique and I want each product is relevant for google search engine. 
2) I have a categry-page for a few products. Each single product in the category get a canonical Link, with a link(c-link) on the category page.
3) I want only some few c-link for products, which are not unique  
This is very important feature, because each seo-strategy is different and can decide among a lot of money or success of the shop.

**Comment by aschempp** [comment]
Canonical support has been added in Contao 4.13
