### ISSUE TITLE
Bug: Iso 1.4.8 Rabattberechnung bei zwei Produkttypen "überlagert" sich

### ISSUE THREAD

**Issue by zonky2** [isotope/core#950]
Ich habe zwei Produkttypen "Deckel" und "Tiegel" - beide können separat gekauft werden da ind. Logos/Drucke drauf.

Auf die Deckel an sich gibt es Rabatt vs. auf die Tiegel an sich gibt es Rabatt.

Einstellungen: (in verschiedenen Rabatten)

Produktanzahl: von .. bis...
Mengen-Berechnungsmodus: gesamter Warenkorb
Produkt-Einschränkungen: Produkttyp
Produkttypen: einmal Deckel vs. anderer Rabatt Tiegel

Habe ich 10 Deckel und einen Tiegel, bekommt der eine Tiegel auch einen Rabatt obwohl dieser z.B. erst ab 6 Tiegel weniger pro Stück kosten soll

kann man das fixen?

zonky

**Comment by xantippe** [comment]
Hallo,

wurde inzwischen an den Regeln gearbeitet bzw. diese angepasst? Es steht die Frage nach einem Update im Raum, was aber interessant wird, wenn dieser "Bug" behoben ist.

Gruss

**Comment by aschempp** [comment]
Es wurde einiges gemacht. Aber am besten installierst du die Demo und findest heraus ob drin ist was du möchtest ;-)

**Comment by xantippe** [comment]
o.k. - dann werde ich das mal testen...

Dank vorab!
