### ISSUE TITLE
HOOK "calculatePrice"

### ISSUE THREAD

**Issue by katgirl** [isotope/core#979]
Um einen Aufschlag zum Preis berechnen zu können muss man wissen um welches Produkt es sich handelt. Über den Hook kommt man aber nicht mehr an das Produkt.

Fall:
Wir haben ein Attribut "laenge" in welchem der Kunde einen int-Wert eingeben kann.
Das Attribut Formel "formel" beinhaltet eine Berechnungsformel anhand der Länge

z.B. Länge*1.28
Damit wäre der Preis = 12.80 Euro

Nun ist es aber so, das dazu der Hook "calculatePrice" verwendet werden muss. dieser hat als $objSource aber nur Isotope/Model/ProductPrice. Die Information um welches Produkt es sich handelt ist verloren oder sehe ich das falsch?

**Comment by tsarma** [comment]
Works:
`Product::findByPK($objSource->pid)`

Did not work: (on checkout steps)
`$objSource->getRelated('pid');`

Fatal error: Uncaught exception Exception with message Field pid does not seem to be related thrown in system/modules/core/library/Contao/Model.php on line 604
