### ISSUE TITLE
Related products should be related by sku not id

### ISSUE THREAD

**Issue by fjacobi** [isotope/core#981]
The only place to see the id is currently editing the product from the product list, then going back to the product you want to connect and then pasting it.

The id isn't used anywhere else (afaik) from an shop administrators point of view, so why are we using them here? Shouldn't that be the sku?
Or even better: copy the technique used in Rules & coupons to add products.

**Comment by qzminski** [comment]
Just wondering, can't we use the https://github.com/terminal42/contao-tablelookupwizard to make the related products management even easier?

**Comment by Toflar** [comment]
We always wanted to do that but the problem there are the variants. They do not necessarily have a different product name so when you search for the product name, you'll never ever see the variant. So it would likely have to be an isotope specific widget, maybe built on top of the tablelookupwizard which should be a lot easier now that I rewrote it and split it up into many tiny methods.

**Comment by aschempp** [comment]
I think this is obsolete since we support the picker widget in Contao 4.13
